### ISSUE TITLE
Error when I try to query from .aquery (async) with Qdrant DB as storage_context [Bug]: 

### ISSUE THREAD

**Issue by nileshchilka1** [run-llama/llama_index#10008]
### Bug Description

General Error when I try to query from .aquery (async) with Qdrant DB as storage_context

### Version

llama-index==0.9.26

### Steps to Reproduce

aclient = qdrant_client.AsyncQdrantClient(url=qdrant_endpoint)

vector_store = QdrantVectorStore(aclient=aclient, collection_name=collection_name)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

vector_store_c = QdrantVectorStore(aclient=aclient, collection_name=collection_name_c)
storage_context = StorageContext.from_defaults(vector_store=vector_store_c)

document_index = GPTVectorStoreIndex.from_documents([], storage_context=storage_context,
                                                        service_context=service_context,async_client=True)
query_engine = document_index.as_query_engine()

document_index_c = GPTVectorStoreIndex.from_documents([], storage_context=storage_context_c,
                                                        service_context=service_context,async_client=True)
query_engine_c = document_index_c.as_query_engine()

async def run_async(query_engine, query_engine_c, question, llm):
    responses_scores = await asyncio.gather(query_util_async(query_engine, question, llm),
                                   query_util_async(query_engine_c, question, llm))
    return responses_scores

async def query_util_async(query_engine, question, llm):
    response = await query_engine.aquery(question)
    return response

response = asyncio.run(run_async(query_engine, query_engine_c, question, llm))

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\backends\asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\anyio\_backends\_asyncio.py", line 1203, in receive
    await self._protocol.read_event.wait()
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\backends\asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\anyio\core\_tasks.py", line 119, in __exit_
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\transports\default.py", line 239, in __aiter_
    async for part in self._httpcore_stream:
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\async\connection_pool.py", line 338, in __aiter_
    async for part in self._stream:
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\async\http11.py", line 315, in __aiter_
    raise exc
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\async\http11.py", line 308, in __aiter_
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\_async\http11.py", line 177, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\_async\http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with map_exceptions(exc_map):
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\contextlib.py", line 153, in _exit_
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\qdrant_client\http\api_client.py", line 173, in send_inner
    response = await self._async_client.send(request)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\_client.py", line 1634, in send
    raise exc
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\_client.py", line 1628, in send
    await response.aread()
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\_models.py", line 909, in aread
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\_models.py", line 909, in <listcomp>
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\_models.py", line 927, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\_models.py", line 985, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\client.py", line 147, in __aiter_
    async for chunk in self._stream:
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\transports\default.py", line 238, in __aiter_
    with map_httpcore_exceptions():
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\contextlib.py", line 153, in _exit_
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Nilesh Chilka\Desktop\chat-gpt\chat\Hr policies\chat-genai-empchat-api\app.py", line 172, in query_llama_index_retrieval_2
    response = query_doc_async(query_engine, query_engine_c, question, llm, email, thread_id, app_type, object_id)
  File "C:\Users\Nilesh Chilka\Desktop\chat-gpt\chat\Hr policies\chat-genai-empchat-api\Document_Retrieval.py", line 145, in query_doc_async
    response = asyncio.run(run_async(query_engine, query_engine_c, question, llm))
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Nilesh Chilka\Desktop\chat-gpt\chat\Hr policies\chat-genai-empchat-api\Document_Retrieval.py", line 122, in run_async
    responses_scores = await asyncio.gather(query_util_async(query_engine, question, llm),
  File "C:\Users\Nilesh Chilka\Desktop\chat-gpt\chat\Hr policies\chat-genai-empchat-api\Document_Retrieval.py", line 156, in query_util_async
    response = await query_engine.aquery(question)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\llama_index\core\base_query_engine.py", line 36, in aquery
    return await self._aquery(str_or_query_bundle)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 185, in _aquery
    nodes = await self.aretrieve(query_bundle)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 130, in aretrieve
    nodes = await self._retriever.aretrieve(query_bundle)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\llama_index\core\base_retriever.py", line 72, in aretrieve
    nodes = await self._aretrieve(query_bundle)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\llama_index\indices\vector_store\retrievers\retriever.py", line 99, in _aretrieve
    return await self._aget_nodes_with_embeddings(query_bundle)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\llama_index\indices\vector_store\retrievers\retriever.py", line 171, in _aget_nodes_with_embeddings
    query_result = await self._vector_store.aquery(query, **self._kwargs)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\llama_index\vector_stores\qdrant.py", line 569, in aquery
    response = await self._aclient.search(
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\qdrant_client\async_qdrant_client.py", line 278, in search
    return await self._client.search(
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\qdrant_client\async_qdrant_remote.py", line 342, in search
    search_result = await self.http.points_api.search_points(
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\qdrant_client\http\api\points_api.py", line 894, in search_points
    return await self._build_for_search_points(
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\qdrant_client\http\api_client.py", line 146, in request
    return await self.send(request, type_)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\qdrant_client\http\api_client.py", line 163, in send
    response = await self.middleware(request, self.send_inner)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\qdrant_client\http\api_client.py", line 195, in _call_
    return await call_next(request)
  File "C:\Users\Nilesh Chilka\anaconda3\envs\myenv\lib\site-packages\qdrant_client\http\api_client.py", line 175, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException
```

**Comment by nileshchilka1** [comment]
increasing value of timeout solved my issue
