### ISSUE TITLE
[Bug]: Issue in getting the number of tokens used

### ISSUE THREAD

**Issue by Adidev-KGP** [run-llama/llama_index#10107]
### Bug Description

When running the code from llama_index docs to get a count of tokens used, an issue is getting raised.

The issue is occurring at : `/home/adidev/.local/lib/python3.8/site-packages/llama_index/callbacks/token_counting.py`

The specific block of code is [line 40 to line 58 of `token_counting.py`] :
```
    elif EventPayload.MESSAGES in payload:
        messages = cast(List[ChatMessage], payload.get(EventPayload.MESSAGES, []))
        messages_str = "\n".join([str(x) for x in messages])

        response = payload.get(EventPayload.RESPONSE)
        response_str = str(response)

        # try getting attached token counts first
        try:
            messages_tokens = 0
            response_tokens = 0
            print("////////////////////// RESPONSE/////////", response.raw)
            if response is not None and response.raw is not None:
                usage = dict(response.raw.get("usage"))  # type: ignore
                print("//////////////////////USAGE/////////", usage)

                if usage is not None:
                    messages_tokens = usage.get("prompt_tokens", 0)
                    response_tokens = usage.get("completion_tokens", 0)
  ```

When I got the logs `response.raw` had normal content but `response.raw` was missing the field `usage` so it getting the error `TypeError: 'NoneType' object is not iterable`

This is the printed response.raw:
```
RESPONSE///////// {'id': 'chatcmpl-8i9UIzDAJGy8xdc0O3YU7xLs4NK83', 'choices': [Choice(delta=ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None), finish_reason='stop', index=0, logprobs=None)], 'created': 1705533594, 'model': 'gpt-3.5-turbo-0613', 'object': 'chat.completion.chunk', 'system_fingerprint': None}
```

It doesn't have a key by the name usage to an error is occuring usage is None.

### Version

0.9.24

### Steps to Reproduce

1. Make a directory `listOfLesson` and put some .txt files in that.
2.  Run the following python code:
```
import os.path, tiktoken
from llama_index import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    StorageContext,
    load_index_from_storage,
    set_global_service_context,
)
from llama_index.callbacks import CallbackManager, TokenCountingHandler
from llama_index import ServiceContext, set_global_tokenizer

# set_global_tokenizer(
#     tiktoken.encoding_for_model("gpt-3.5-turbo").encode
# )
# token_counter = TokenCountingHandler(verbose=True)
# callback_manager = CallbackManager([token_counter])
token_counter = TokenCountingHandler(
    tokenizer=tiktoken.encoding_for_model("gpt-3.5-turbo").encode
)
callback_manager = CallbackManager([token_counter])


from llama_index import ServiceContext
from llama_index.node_parser import SentenceWindowNodeParser
service_context = ServiceContext.from_defaults(chunk_size=1500, chunk_overlap=150, callback_manager=callback_manager)
set_global_service_context(service_context)

# check if storage already exists
PERSIST_DIR = "./storage"
if not os.path.exists(PERSIST_DIR):
    # load the documents and create the index
    documents = SimpleDirectoryReader("listOfLesson").load_data()
    index = VectorStoreIndex.from_documents(documents, service_context=service_context)
    # store it for later
    index.storage_context.persist(persist_dir=PERSIST_DIR)
else:
    # load the existing index
    storage_context = StorageContext.from_defaults(persist_dir=PERSIST_DIR)
    index = load_index_from_storage(storage_context)

# either way we can now query the index
query_engine = index.as_query_engine(similarity_top_k=5, response_mode="refine", streaming=True)
response = query_engine.query("Who is the enemy? Give a detailed answer")
# response.print_response_stream() # to print response in streaming manner
print(">>>>>>>>>>>>>>>>>>>>>>>",response)
# print(token_counter.total_llm_token_count)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "starter.py", line 45, in <module>
    response = query_engine.query("Who is the enemy?Give a detailed answer")
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/core/base_query_engine.py", line 30, in query
    return self._query(str_or_query_bundle)
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/query_engine/retriever_query_engine.py", line 171, in _query
    response = self._response_synthesizer.synthesize(
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/response_synthesizers/base.py", line 146, in synthesize
    response_str = self.get_response(
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/response_synthesizers/refine.py", line 151, in get_response
    response = self._refine_response_single(
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/response_synthesizers/refine.py", line 246, in _refine_response_single
    response = get_response_text(response)
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/response/utils.py", line 9, in get_response_text
    for response in response_gen:
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/llms/llm.py", line 58, in gen
    for response in chat_response_gen:
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/llms/base.py", line 107, in wrapped_gen
    callback_manager.on_event_end(
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/callbacks/base.py", line 122, in on_event_end
    handler.on_event_end(event_type, payload, event_id=event_id, **kwargs)
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/callbacks/token_counting.py", line 156, in on_event_end
    get_llm_token_counts(
  File "/home/adidev/.local/lib/python3.8/site-packages/llama_index/callbacks/token_counting.py", line 53, in get_llm_token_counts
    usage = dict(response.raw.get("usage"))  # type: ignore
TypeError: 'NoneType' object is not iterable
```

**Comment by logan-markewich** [comment]
This is fixed in the latest version of llama-index, please update

https://github.com/run-llama/llama_index/blob/e3e1de976d3aeb8914c370d030ee97a399c64767/llama_index/callbacks/token_counting.py#L55

**Comment by Adidev-KGP** [comment]
> This is fixed in the latest version of llama-index, please update
> 
> https://github.com/run-llama/llama_index/blob/e3e1de976d3aeb8914c370d030ee97a399c64767/llama_index/callbacks/token_counting.py#L55

Thanks a lot! That worked.
