### ISSUE TITLE
Recursive retrieval error throw this random error sometimes 

### ISSUE THREAD

**Issue by Jeevi10** [run-llama/llama_index#10100]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Traceback (most recent call last):
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/pydantic/v1/main.py", line 522, in parse_obj
    obj = dict(obj)
          ^^^^^^^^^
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/gradio/blocks.py", line 1191, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/gradio/utils.py", line 666, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/tmp/ipykernel_3810496/301643083.py", line 137, in chat
    bot_response = pack.run(user_input)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/Desktop/ROME/My Documents/RAG-lang/multiDocRetriever.py", line 181, in run
    return self.query_engine.query(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/core/base_query_engine.py", line 40, in query
    return self._query(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py", line 171, in _query
    nodes = self.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py", line 127, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/core/base_retriever.py", line 61, in retrieve
    nodes = self._retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py", line 184, in _retrieve
    retrieved_nodes, _ = self._retrieve_rec(query_bundle, query_id=None)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py", line 157, in _retrieve_rec
    nodes = obj.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/core/base_retriever.py", line 61, in retrieve
    nodes = self._retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/Desktop/ROME/My Documents/RAG-lang/multiDocRetriever.py", line 40, in _retrieve
    retrieved_nodes = self.retriever.retrieve(query_bundle)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/core/base_retriever.py", line 61, in retrieve
    nodes = self._retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/core/base_auto_retriever.py", line 35, in _retrieve
    retrieval_spec = self.generate_retrieval_spec(query_bundle)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/auto_retriever/auto_retriever.py", line 164, in generate_retrieval_spec
    return self._parse_generated_spec(output, query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/auto_retriever/auto_retriever.py", line 135, in _parse_generated_spec
    StructuredOutput, self._output_parser.parse(output)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/auto_retriever/output_parser.py", line 12, in parse
    query_and_filters = VectorStoreQuerySpec.parse_obj(json_dict)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jalagurajah/anaconda3/envs/RAG2/lib/python3.11/site-packages/pydantic/v1/main.py", line 525, in parse_obj
    raise ValidationError([ErrorWrapper(exc, loc=ROOT_KEY)], cls) from e
pydantic.v1.error_wrappers.ValidationError: 1 validation error for VectorStoreQuerySpec
__root__
  VectorStoreQuerySpec expected dict not NoneType (type=type_error)
  
  llama_index==0.9.32

**Comment by logan-markewich** [comment]
@Jeevi10 seems like an issue with the LLM generating the spec -- it was likely not generated properly

**Comment by GarryReuben** [comment]
I'm getting this error as well with `VectorIndexAutoRetriever`. I think the LLM is outputting an empty query string, but the vector index needs it? I tried setting `default_empty_query_vector` but no luck. 

Might be related to [8523](https://github.com/run-llama/llama_index/issues/8523)?
