### ISSUE TITLE
[Question]: Running into shapes mismatch when using Recursive Retriever and loaded vectorstoreindex from disk

### ISSUE THREAD

**Issue by anirsub** [run-llama/llama_index#10128]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi there, I am trying to use an index that is loaded from disk with a recursive retriever and am running into a shapes mismatch. Here is the code example:

`import os
import sys

from llama_index import load_index_from_storage
from llama_index.retrievers import RecursiveRetriever
from llama_index.storage.storage_context import StorageContext
from llama_index.retrievers import RecursiveRetriever
from llama_index.query_engine import RetrieverQueryEngine
from llama_index import VectorStoreIndex, ServiceContext
from llama_index.embeddings import resolve_embed_model

# Load the vector store(s) to be used for RAG
top_k = 2
# Define embedding and llm models
embed_model = resolve_embed_model("local:BAAI/bge-small-en")
llm = Ollama(model="mistral")

service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)

storage_context = StorageContext.from_defaults(persist_dir="./storage")
index = load_index_from_storage(storage_context)
all_nodes = index.docstore.docs.values()
all_nodes_dict = {n.node_id : n for n in all_nodes}

print(f"Length of all nodes dict : {len(all_nodes_dict)}")

# Define the retriever
retriever = index.as_retriever(similarity_top_k = top_k)
retriever = RecursiveRetriever(
    "vector",
    retriever_dict={"vector": retriever},
    node_dict = all_nodes_dict,
    verbose=True,
)
nodes = retriever.retrieve(
    "How do I see more than 100 values when using Advanced Search?"
)
for node in nodes:
    display_source_node(node, source_length=2000)`

And here is the error message : 
`Length of all nodes dict : 1150
Retrieving with query id None: How do I see more than 100 values when using Advanced Search?
Traceback (most recent call last):
  File "/Users/anisub/Desktop/test-dev/rag/gdc_ug_chat/query_vector_store.py", line 31, in <module>
    nodes_with_score, additional_nodes = retriever.retrieve_all(query_bundle)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anisub/.pyenv/versions/test-env/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py", line 195, in retrieve_all
    return self._retrieve_rec(query_bundle, query_id=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anisub/.pyenv/versions/test-env/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py", line 157, in _retrieve_rec
    nodes = obj.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anisub/.pyenv/versions/test-env/lib/python3.11/site-packages/llama_index/core/base_retriever.py", line 61, in retrieve
    nodes = self._retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anisub/.pyenv/versions/test-env/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 88, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anisub/.pyenv/versions/test-env/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 164, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anisub/.pyenv/versions/test-env/lib/python3.11/site-packages/llama_index/vector_stores/simple.py", line 274, in query
    top_similarities, top_ids = get_top_k_embeddings(
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anisub/.pyenv/versions/test-env/lib/python3.11/site-packages/llama_index/indices/query/embedding_utils.py", line 31, in get_top_k_embeddings
    similarity = similarity_fn(query_embedding_np, emb)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anisub/.pyenv/versions/test-env/lib/python3.11/site-packages/llama_index/core/embeddings/base.py", line 48, in similarity
    product = np.dot(embedding1, embedding2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (1536,) and (384,) not aligned: 1536 (dim 0) != 384 (dim 0)`

Am I doing something wrong with retrieving the nodes and passing all_nodes_dict to the retriever?

**Comment by anirsub** [comment]
The two embedding models were different, Llama Index assumes OpenAI ada embeddings when nothing is specified. Issue was not passing in the right service context when loading index from storage.

This is the line that fixed the issue:
`index = load_index_from_storage(storage_context, service_context=service_context)`
