### ISSUE TITLE
[Bug]: image_mimetype not found during MultiModal Retrievala

### ISSUE THREAD

**Issue by ZachHandley** [run-llama/llama_index#10162]
### Bug Description

I basically forced it to pull images even though it didn't want to, because of that it seemingly tried to use the image_mimetype for some reason on the `ImageNode`

### Version

0.9.32

### Steps to Reproduce

1. Create a multimodal vector index of images and text in Qdrant
2. I am using the base64 encoding, basically my project setup is https://github.com/zachhandley/LlamaIndexAPI and when it pulls the images using the method there it gives me that error, I can reproduce it locally but I'm unsure if I can reliably reproduce it in prod, the error message should be enough IMO

### Relevant Logs/Tracbacks

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/app/server.py", line 262, in get_summary
    summary = await actions.summarize_user(assessment.userId)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/app/api/ai_actions.py", line 216, in summarize_user
    ai_response = await query_engine.aquery(query_str)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/llama_index/core/base_query_engine.py", line 46, in aquery
    return await self._aquery(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/llama_index/query_engine/multi_modal.py", line 220, in _aquery
    response = await self.asynthesize(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/llama_index/query_engine/multi_modal.py", line 146, in asynthesize
    llm_response = await self._multi_modal_llm.acomplete(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/llama_index/multi_modal_llms/openai.py", line 380, in acomplete
    return await self._acomplete(prompt, image_documents, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/llama_index/multi_modal_llms/openai.py", line 362, in _acomplete
    message_dict = self._get_multi_modal_chat_messages(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/llama_index/multi_modal_llms/openai.py", line 173, in _get_multi_modal_chat_messages
    generate_openai_multi_modal_chat_message(
  File "/Users/zachhandley/Documents/GitHub/My-Project/api/.venv/lib/python3.11/site-packages/llama_index/multi_modal_llms/openai_utils.py", line 41, in generate_openai_multi_modal_chat_message
    mimetype = image_document.image_mimetype or "image/jpeg"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NodeWithScore' object has no attribute 'image_mimetype'
```

**Comment by ravi03071991** [comment]
@ZachHandley `ImageDocument` [here](https://github.com/ZachHandley/LlamaIndexAPI/blob/ab58fb5b60d1898eee842d8fcf4f0469d705b9d5/app/db/vector_stores.py#L159) [expects image_mimetype](https://github.com/run-llama/llama_index/blob/1ea68e8b8a299066d46b195333db49918d13aedf/llama_index/schema.py#L463). You can by default fix it to None and that should solve the issue.

**Comment by hatianzhang** [comment]
`image_mimetype` is optional field of `ImageNode`.
@ZachHandley I am wondering are you trying to access `image_mimetype` for text nodes since it seems you are building multi model vector index

**Comment by hatianzhang** [comment]
since the error log shows you are creating chat msg using `NodeWithScore`.
you need to get node form nodewithscore and assert it is imagenode

**Comment by ZachHandley** [comment]
I believe this is closed :)
