### ISSUE TITLE
[Bug]: Bug in LLMQuestionGenerator.generate()

### ISSUE THREAD

**Issue by mim201820** [run-llama/llama_index#10190]
### Bug Description

Im using the LLMQuestionGenerator with LLamaCPP llm and Im getting an error. on how the llm output is getting parsed. 
Im not using the latest version of llama-idex but I checked the code it was not fixed in the newest versions

### Version

0.9.31

### Steps to Reproduce

Here is the code Im using

```
# Define LLM
llm = LlamaCpp(
    model_path="models/mistral-7b-instruct-v0.1.Q4_K_M.gguf",
    streaming=False,
    n_ctx=2048,
    n_gpu_layers=40,
    n_threads=4,
    n_batch=1000,
    use_mlock=True
)


tool_choices = [
    ToolMetadata(
        name="uber_2021_10k",
        description=(
            "Provides information about Uber financials for year 2021"
        ),
    ),
    ToolMetadata(
        name="lyft_2021_10k",
        description=(
            "Provides information about Lyft financials for year 2021"
        ),
    ),
]
service_context = ServiceContext.from_defaults( llm=llm)

question_gen = LLMQuestionGenerator.from_defaults(service_context=service_context)
query_str = "Compare and contrast Uber and Lyft"
choices = question_gen.generate(tool_choices, QueryBundle(query_str=query_str))
```

The error I got is the following:
```
Traceback (most recent call last):
  File venv/lib/python3.9/site-packages/pydantic/v1/main.py", line 522, in parse_obj
    obj = dict(obj)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sub_questions_retrieval.py", line 84, in <module>
    choices = question_gen.generate(tool_choices, QueryBundle(query_str=query_str))
  File "venv/lib/python3.9/site-packages/llama_index/question_gen/llm_generators.py", line 78, in generate
    parse = self._prompt.output_parser.parse(prediction)
  File "venv/lib/python3.9/site-packages/llama_index/question_gen/output_parser.py", line 17, in parse
    sub_questions = [SubQuestion.parse_obj(item) for item in json_dict]
  File "venv/lib/python3.9/site-packages/llama_index/question_gen/output_parser.py", line 17, in <listcomp>
    sub_questions = [SubQuestion.parse_obj(item) for item in json_dict]
  File "venv/lib/python3.9/site-packages/pydantic/v1/main.py", line 525, in parse_obj
    raise ValidationError([ErrorWrapper(exc, loc=ROOT_KEY)], cls) from e
pydantic.v1.error_wrappers.ValidationError: 1 validation error for SubQuestion
```

The bug is in

>  llama_index/question_gen/output_parser.py

we should loop over "items" of the json_dict so this is my fix for the bug

```
class SubQuestionOutputParser(BaseOutputParser):
    def parse(self, output: str) -> Any:
        json_dict = parse_json_markdown(output)
        if not json_dict:
            raise ValueError(f"No valid JSON found in output: {output}")

        sub_questions = [SubQuestion.parse_obj(item) for item in json_dict["items"]]
        return StructuredOutput(raw_output=output, parsed_output=sub_questions)

```

**Comment by nalmeida84** [comment]
Hi @mim201820, why you closed the bug?

**Comment by mim201820** [comment]
I checked the latest version and I found that fix was implemented
