### ISSUE TITLE
[Bug]: Circular import on OpenAIPydanticProgram

### ISSUE THREAD

**Issue by thiagosalvatore** [run-llama/llama_index#10212]
### Bug Description

Not being able to import anything from `programs` because of a circular import on `OpenAIPydanticProgram`.

I'm using python 3.11 with poetry

### Version

0.9.35

### Steps to Reproduce

- Install llama-index 0.9.35 on python 3.11 with poetry in a fresh virtual env
- Add `from llama_index.program import OpenAIPydanticProgram`
- The error will be raised

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/thiagosalvatore/Projects/Personal/rezume/src/infrastructure/extractors/PDFExtractor.py", line 36, in <module>
    from llama_index.program import (
  File "/Users/thiagosalvatore/Projects/Personal/rezume/.venv/lib/python3.11/site-packages/llama_index/program/__init__.py", line 5, in <module>
    from llama_index.program.openai_program import OpenAIPydanticProgram
  File "/Users/thiagosalvatore/Projects/Personal/rezume/.venv/lib/python3.11/site-packages/llama_index/program/openai_program.py", line 4, in <module>
    from llama_index.agent.openai.utils import resolve_tool_choice
  File "/Users/thiagosalvatore/Projects/Personal/rezume/.venv/lib/python3.11/site-packages/llama_index/agent/__init__.py", line 2, in <module>
    from llama_index.agent.custom.pipeline_worker import QueryPipelineAgentWorker
  File "/Users/thiagosalvatore/Projects/Personal/rezume/.venv/lib/python3.11/site-packages/llama_index/agent/custom/pipeline_worker.py", line 27, in <module>
    from llama_index.query_pipeline.components.agent import (
  File "/Users/thiagosalvatore/Projects/Personal/rezume/.venv/lib/python3.11/site-packages/llama_index/query_pipeline/__init__.py", line 19, in <module>
    from llama_index.query_pipeline.components.router import (
  File "/Users/thiagosalvatore/Projects/Personal/rezume/.venv/lib/python3.11/site-packages/llama_index/query_pipeline/components/router.py", line 16, in <module>
    from llama_index.selectors.types import BaseSelector
  File "/Users/thiagosalvatore/Projects/Personal/rezume/.venv/lib/python3.11/site-packages/llama_index/selectors/__init__.py", line 3, in <module>
    from llama_index.selectors.pydantic_selectors import (
  File "/Users/thiagosalvatore/Projects/Personal/rezume/.venv/lib/python3.11/site-packages/llama_index/selectors/pydantic_selectors.py", line 4, in <module>
    from llama_index.program.openai_program import OpenAIPydanticProgram
ImportError: cannot import name 'OpenAIPydanticProgram' from partially initialized module 'llama_index.program.openai_program' (most likely due to a circular import) (/Users/thiagosalvatore/Projects/Personal/rezume/.venv/lib/python3.11/site-packages/llama_index/program/openai_program.py)
```

**Comment by thiagosalvatore** [comment]
I tested on 0.9.34 and apparently it is not happening in that version
