### ISSUE TITLE
[Bug]: httpx.RemoteProtocolError when using OpenAILike

### ISSUE THREAD

**Issue by kdy0912** [run-llama/llama_index#10231]
### Bug Description

 I set up the model openchat-3.5-0106 and am running it as server using vllm.
my vllm version is 0.2.4+cu118
here is the command.
`python -m vllm.entrypoints.openai.api_server     --model "/root/autodl-tmp/kdy/models/openchat-3.5-0106"     --served-model-name "openchat"`

I am trying to define OpenAILike model and using llama_index with this code:
```from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_index import ServiceContext
from llama_index.llms.openai_like import OpenAILike
from llama_index import set_global_service_context

openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8000/v1"
llm = OpenAILike(
    api_key=openai_api_key,
    api_base=openai_api_base,
    model="openchat",
    #is_chat_model=True,  
    context_window=32768,
    
)

service_context = ServiceContext.from_defaults(llm=llm, embed_model="local:BAAI/bge-small-zh-v1.5")
set_global_service_context(service_context)

documents = SimpleDirectoryReader("/root/autodl-tmp/RAG/data").load_data()
index = VectorStoreIndex.from_documents(documents)
index.storage_context.persist(persist_dir="./storage")

query_engine = index.as_query_engine(streaming=True, similarity_top_k=3)
response_stream = query_engine.query("who is the man in the story?")
print(str(response_stream))
```

the content in `/root/autodl-tmp/kdy/RAG/data` is a story and I want to get the answer according to the stroy I supply.
But there is an error below.

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 209, in _receive_event
    event = self._h11_state.next_event()
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/h11/_connection.py", line 469, in next_event
    event = self._extract_next_receive_event()
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/h11/_connection.py", line 419, in _extract_next_receive_event
    event = self._reader.read_eof()  # type: ignore[attr-defined]
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/h11/_readers.py", line 204, in read_eof
    raise RemoteProtocolError(
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_transports/default.py", line 111, in __iter__
    for part in self._httpcore_stream:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 361, in __iter__
    for part in self._stream:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 337, in __iter__
    raise exc
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 329, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 198, in _receive_response_body
    event = self._receive_event(timeout=timeout)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 208, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/root/miniconda3/envs/kdy/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/kdy/RAG/openai_test.py", line 26, in <module>
    print(str(response_stream))
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/llama_index/core/response/schema.py", line 104, in __str__
    for text in self.response_gen:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/llama_index/llms/llm.py", line 65, in gen
    for response in completion_response_gen:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/llama_index/llms/base.py", line 231, in wrapped_gen
    for x in f_return_val:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/llama_index/llms/openai.py", line 432, in gen
    for response in client.completions.create(
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/openai/_streaming.py", line 43, in __iter__
    for item in self._iterator:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/openai/_streaming.py", line 55, in __stream__
    for sse in iterator:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/openai/_streaming.py", line 47, in _iter_events
    yield from self._decoder.iter(self.response.iter_lines())
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/openai/_streaming.py", line 223, in iter
    for line in iterator:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_models.py", line 863, in iter_lines
    for text in self.iter_text():
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_models.py", line 850, in iter_text
    for byte_content in self.iter_bytes():
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_models.py", line 887, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_client.py", line 124, in __iter__
    for chunk in self._stream:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_transports/default.py", line 110, in __iter__
    with map_httpcore_exceptions():
  File "/root/miniconda3/envs/kdy/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
```
and after I removed the code in the last line, the bug didn't happened

### Version

0.9.33

### Steps to Reproduce

the code is given in the Bug Description

### Relevant Logs/Tracbacks

```shell
my server also reported the error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/responses.py", line 261, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/responses.py", line 257, in wrap
    await func()
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/responses.py", line 234, in listen_for_disconnect
    message = await receive()
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 587, in receive
    await self.message_event.wait()
  File "/root/miniconda3/envs/kdy/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f223013eef0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
    await self.asgi_callable(scope, receive, wrapped_send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/starlette/responses.py", line 254, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
    self.cancel_scope.cancel()
exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
INFO 01-24 11:21:20 async_llm_engine.py:111] Finished request cmpl-d3f97d823fda4432a359fe3ad5cd7d9f.
```

**Comment by logan-markewich** [comment]
In order to print a streaming response, you can do `response.print_response_stream()` or iterate over the stream

```
for token in response.response_gen:
  print(token, end="", flush=True)
```

**Comment by kdy0912** [comment]
@logan-markewich It doesn’t seem to work. I think the problem is due to the connection of the sever.
```
Traceback (most recent call last):
  File "/root/autodl-tmp/kdy/RAG/openai_test.py", line 26, in <module>
    for token in response_stream.response_gen:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/llama_index/llms/llm.py", line 65, in gen
    for response in completion_response_gen:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/llama_index/llms/base.py", line 231, in wrapped_gen
    for x in f_return_val:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/llama_index/llms/openai.py", line 432, in gen
    for response in client.completions.create(
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/openai/_streaming.py", line 43, in __iter__
    for item in self._iterator:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/openai/_streaming.py", line 55, in __stream__
    for sse in iterator:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/openai/_streaming.py", line 47, in _iter_events
    yield from self._decoder.iter(self.response.iter_lines())
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/openai/_streaming.py", line 223, in iter
    for line in iterator:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_models.py", line 863, in iter_lines
    for text in self.iter_text():
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_models.py", line 850, in iter_text
    for byte_content in self.iter_bytes():
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_models.py", line 887, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_client.py", line 124, in __iter__
    for chunk in self._stream:
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_transports/default.py", line 110, in __iter__
    with map_httpcore_exceptions():
  File "/root/miniconda3/envs/kdy/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/kdy/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
```

**Comment by kdy0912** [comment]
@dosu-bot I solved the problem after I altered this code 
`query_engine = index.as_query_engine(streaming=True, similarity_top_k=3)`
to 
`query_engine = index.as_query_engine(streaming=False, similarity_top_k=3)`
and it ran successfully!
Why would this happen ?

**Comment by logan-markewich** [comment]
@kdy0912 I was not able to reproduce with this script (note I used a crappy small LLM, so that it could run on a T4 instance)
https://colab.research.google.com/drive/1h-eHhoKUnkJQ2TTsw4HxOd0f1zVd97Ol?usp=sharing

**Comment by kdy0912** [comment]
@logan-markewich Thank you for your help! I ran your code in colab and it ran successfully, so I thought this happened due to my environment. After checking the pip list, I found the cause.
`vllm 0.2.4+cu118 has requirement pydantic==1.10.13, but you have pydantic 2.5.3.`
then I changed the version of the pydantic to 1.10.13, the problem solved!
Thank you very much!

**Comment by kdy0912** [comment]
@logan-markewich Thank you for your help! I ran your code in colab and it ran successfully, so I thought this happened due to my environment. After checking the pip list, I found the cause.
`vllm 0.2.4+cu118 has requirement pydantic==1.10.13, but you have pydantic 2.5.3.`
then I changed the version of the pydantic to 1.10.13, the problem solved!
Thank you very much!

**Comment by logan-markewich** [comment]
Great!
