### ISSUE TITLE
How to query oracle database in natural language. 

### ISSUE THREAD

**Issue by Aman78695** [run-llama/llama_index#10277]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

This is my code..

import openai
import os
#
from sqlalchemy import create_engine
from llama_index import SQLDatabase
from llama_index.llms import OpenAI
from llama_index.embeddings import OpenAIEmbedding
from llama_index import ServiceContext
from llama_index.indices.struct_store.sql_query import NLSQLTableQueryEngine
from llama_index.tools.query_engine import QueryEngineTool
from llama_index.agent import OpenAIAgent

import cx_Oracle
import os
from sqlalchemy import create_engine

# Set the environment variable for Oracle Instant Client
instant_client_dir = r'C:\instantclient-basic-windows.x64-21.12.0.0.0dbru\instantclient_21_12'
os.environ["PATH"] = f"{instant_client_dir};{os.environ['PATH']}"

db_user = "readonlyu"
db_password = "rou"
db_host = "10.0.4.4"
db_port = "1521"  # Assuming the default Oracle Database port is used
db_service_name = "CBO"
db_name="BRLPS_CBO_MIS"

oracle_connection_string = f"{db_user}/{db_password}@{db_host}:{db_port}/{db_service_name}"

connection = cx_Oracle.connect(oracle_connection_string)

print(connection.version)

engine = create_engine(f"oracle+cx_oracle://{db_user}:{db_password}@{db_host}:{db_port}/{db_service_name}",echo=True)

reviews_db = SQLDatabase(engine,include_tables=['m_cbo'])

llm = OpenAI(model_name="gpt-3.5-turbo",
             api_key="",
             temperature=0,
             streaming=True)
embedding = OpenAIEmbedding()
#
servicecontext = ServiceContext.from_defaults(llm=llm,
                                embed_model=embedding,
                                chunk_size=500)

sql_query_engine = NLSQLTableQueryEngine(sql_database=reviews_db,
                                         tables=['m_cbo'],
                                         service_context=servicecontext)

description = ("Provides information about cbo name id district id etc. "
                "Use a detailed plain text question as input to the tool.")

sql_tool = QueryEngineTool.from_defaults(query_engine=sql_query_engine,
                                     name="sql_query",
                                     description=description)
#
agent = OpenAIAgent.from_tools(tools=[sql_tool],verbose=True)

response = agent.chat("What is the cbo_id of Radha?")

The error is...

(env) C:\Users\Geotechnosoft\Desktop\llamaindex_db>python lamaindex.py
11.2.0.4.0
2024-01-25 23:20:35,147 INFO sqlalchemy.engine.Engine select sys_context( 'userenv', 'current_schema' ) from dual
2024-01-25 23:20:35,150 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-01-25 23:20:35,876 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-01-25 23:20:35,878 INFO sqlalchemy.engine.Engine SELECT a_tables.table_name 
FROM all_tables a_tables
WHERE (coalesce(a_tables.tablespace_name, :coalesce_1) NOT IN (:coalesce_2_1, :coalesce_2_2)) AND a_tables.owner = :owner_1 AND a_tables.iot_name IS NULL AND a_tables.duration IS NULL MINUS SELECT a_mviews.mview_name AS table_name
FROM all_mviews a_mviews
WHERE a_mviews.owner = :owner_2
2024-01-25 23:20:35,883 INFO sqlalchemy.engine.Engine [generated in 0.00744s] {'coalesce_1': 'no tablespace', 'owner_1': 'READONLYU', 'owner_2': 'READONLYU', 'coalesce_2_1': 'SYSTEM', 'coalesce_2_2': 'SYSAUX'}
2024-01-25 23:20:36,037 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "C:\Users\Geotechnosoft\Desktop\llamaindex_db\lamaindex.py", line 42, in <module>  
    reviews_db = SQLDatabase(engine,include_tables=['m_cbo'])
  File "C:\Users\Geotechnosoft\Desktop\llamaindex_db\env\lib\site-packages\llama_index\utilities\sql_wrapper.py", line 72, in __init__
    raise ValueError(
ValueError: include_tables {'m_cbo'} not found in database

**Comment by nerdai** [comment]
@Aman78695 were you able to further investigate as to why the `m_cbu` table cannot be found? Dosu provided three suggestions in its response to look into for possible reasons.
