### ISSUE TITLE
[Bug]: TypeError with python llama-index package

### ISSUE THREAD

**Issue by sasha42** [run-llama/llama_index#10301]
### Bug Description

When I install llamaindex with pip on my mac, I get the following error:
```
➜ llamaindex-cli
Traceback (most recent call last):
  File "/Users/sasha/miniconda3/bin/llamaindex-cli", line 5, in <module>
    from llama_index.command_line.command_line import main
  File "/Users/sasha/miniconda3/lib/python3.9/site-packages/llama_index/__init__.py", line 13, in <module>
    from llama_index.callbacks.global_handlers import set_global_handler
  File "/Users/sasha/miniconda3/lib/python3.9/site-packages/llama_index/callbacks/__init__.py", line 7, in <module>
    from .token_counting import TokenCountingHandler
  File "/Users/sasha/miniconda3/lib/python3.9/site-packages/llama_index/callbacks/token_counting.py", line 6, in <module>
    from llama_index.utilities.token_counting import TokenCounter
  File "/Users/sasha/miniconda3/lib/python3.9/site-packages/llama_index/utilities/token_counting.py", line 6, in <module>
    from llama_index.llms import ChatMessage, MessageRole
  File "/Users/sasha/miniconda3/lib/python3.9/site-packages/llama_index/llms/__init__.py", line 39, in <module>
    from llama_index.llms.openllm import OpenLLM, OpenLLMAPI
  File "/Users/sasha/miniconda3/lib/python3.9/site-packages/llama_index/llms/openllm.py", line 49, in <module>
    class OpenLLM(LLM):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/Users/sasha/miniconda3/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

This happens with the conda installation of Python on my Mac Os Ventura 13.5.2 (22G91). When I install this with a virtual environment, it works correctly. Here's my Python environment:

```
(base) ➜  ~ python
Python 3.9.12 (main, Apr  5 2022, 01:52:34)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

(base) ➜  ~ which python
/Users/sasha/miniconda3/bin/python
```

### Version

0.9.38

### Steps to Reproduce

1. Install with `sudo pip3 install llama-index`
2. Run `llamaindex-cli`
3. Get error shown above

**Comment by logan-markewich** [comment]
@sasha42 this usually happens because of an issue with typing_extenstions 

Maybe try `pip install -U llama-index typing-extensions==4.5.0`

**Comment by sasha42** [comment]
That worked, thanks!
