### ISSUE TITLE
[Question]: LLama-Index asking for OpenAI key while loading an index even though using a custom embedding model?

### ISSUE THREAD

**Issue by rudrakhsha-c** [run-llama/llama_index#10330]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

```
loggingggg 
StorageContext(docstore=<llama_index.storage.docstore.simple_docstore.SimpleDocumentStore object at 0x7f7f7327ee50>, index_store=<llama_index.storage.index_store.simple_index_store.SimpleIndexStore object at 0x7f7b14a1ee90>, vector_stores={'default': <llama_index.vector_stores.simple.SimpleVectorStore object at 0x7f7b32df7510>, 'image': <llama_index.vector_stores.simple.SimpleVectorStore object at 0x7f7b32ec0290>}, graph_store=<llama_index.graph_stores.simple.SimpleGraphStore object at 0x7f7b32d31750>)  ---sc
INFO:llama_index.indices.loading:Loading indices with ids: ['vector_index']
Loading indices with ids: ['vector_index']
Traceback (most recent call last):
  File "/home/devuser/anaconda3/lib/python3.11/site-packages/llama_index/llms/utils.py", line 29, in resolve_llm
    validate_openai_api_key(llm.api_key)
  File "/home/devuser/anaconda3/lib/python3.11/site-packages/llama_index/llms/openai_utils.py", line 371, in validate_openai_api_key
    raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devuser/rudr/llama_bot_rag/fast_model_app.py", line 143, in <module>
    index2 = load_index_from_storage(sc, 'vector_index')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devuser/anaconda3/lib/python3.11/site-packages/llama_index/indices/loading.py", line 33, in load_index_from_storage
    indices = load_indices_from_storage(storage_context, index_ids=index_ids, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devuser/anaconda3/lib/python3.11/site-packages/llama_index/indices/loading.py", line 78, in load_indices_from_storage
    index = index_cls(
            ^^^^^^^^^^
  File "/home/devuser/anaconda3/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 49, in __init__
    super().__init__(
  File "/home/devuser/anaconda3/lib/python3.11/site-packages/llama_index/indices/base.py", line 61, in __init__
    self._service_context = service_context or ServiceContext.from_defaults()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devuser/anaconda3/lib/python3.11/site-packages/llama_index/service_context.py", line 167, in from_defaults
    llm_predictor = llm_predictor or LLMPredictor(
                                     ^^^^^^^^^^^^^
  File "/home/devuser/anaconda3/lib/python3.11/site-packages/llama_index/llm_predictor/base.py", line 104, in __init__
    self._llm = resolve_llm(llm)
                ^^^^^^^^^^^^^^^^
  File "/home/devuser/anaconda3/lib/python3.11/site-packages/llama_index/llms/utils.py", line 31, in resolve_llm
    raise ValueError(
ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******
```
Getting the above error in the below section of the code:
I am using ```mistralai/Mistral-7B-v0.1``` as the llm and ```sentence-transformers/all-mpnet-base-v2``` as my embedding model from huggingface.
Once all my documents are indexed, I am storing the index in a directory ```persist_dir``` from which I am then loading the index for inference.
Below is the relevant code for the above description:
```
llm = HuggingFaceLLM(
        # determines how much previous context is considered when generating new tokens
        context_window=1024,
        # control the length of generated output
        max_new_tokens=256,
        # additional settings: temperature(randomness) & do_sample: false -> will selects similar words
        # with highest probability(no variable randomness)
        generate_kwargs={"temperature": 0.5, "do_sample": True},
        # giving the context to llm(we have defined a system prompt above)
        system_prompt=system_prompt,
        # query format to the model
        query_wrapper_prompt=query_wrapper_prompt,
        tokenizer_name="mistralai/Mistral-7B-v0.1",
        model_name="mistralai/Mistral-7B-v0.1",
        # decides whether to use cpu or gpu (here: auto)
        device_map="cpu",
        # max tokens which can be fed into the model from user input
        tokenizer_kwargs={"max_length": 1024},
        # uncomment this if using CUDA to reduce memory usage
        # the datatype to be used when loading models parameters into pytorch tensor objects. using 16bit floating point numbers reduces
        # memory usage as compared to using 32 bit
        # model_kwargs={"torch_dtype": torch.float16}
        model_kwargs={"torch_dtype": torch.float32}
    )

    embed_model = LangchainEmbedding(
        HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
    )

    # this embedding model has 1536 dimensions in the tensor same as llama2
    # from llama_index.embeddings import HuggingFaceEmbedding
    # max_length = 1024
    # embed_model = HuggingFaceEmbedding(model_name = "sentence-transformers/all-mpnet-base-v2", max_length=max_length, device='cpu')

    # Log embedding model name
    mlflow.log_param("embedding_model", "intfloat/e5-mistral-7b-instruct")
    documents_dir = "/home/devuser/rudr/llama_bot_rag/Data"
    mlflow.log_artifacts(documents_dir, artifact_path="indexed_documents")

    # os.environ["OPENAI_API_KEY"] = "my_key_here"

    # Process and load documents
    documents = SimpleDirectoryReader("/home/devuser/rudr/llama_bot_rag/Data").load_data()

    # Log the number of documents processed
    mlflow.log_metric("num_documents_indexed", len(documents))

    service_context = ServiceContext.from_defaults(
        chunk_size=2048,
        llm=llm,
        embed_model=embed_model
    )

    index = VectorStoreIndex.from_documents(documents, service_context=service_context)

    print('loggingggg ')
    # sc = storage_context.from_defaults(persist_dir='persist_dir')
    # index = load_index_from_storage(sc, 'vector_index')

    # storing the vector index in persist_dir
    # naming the id as vector_index
    index.set_index_id("vector_index")
    index.storage_context.persist('persist_dir')

    sc = storage_context.from_defaults(persist_dir='persist_dir')
    print(sc, ' ---sc')
    index2 = load_index_from_storage(sc, 'vector_index')

    query_engine = index2.as_query_engine()
    print('after indexing query engine')

    # Handling queries (example)
    response = query_engine.query("give me steps to reset my expired ad password.")
    print(response)
```

Why do i need to mention the openai api key even though i am using sentence transformers as my embedding model?

**Comment by logan-markewich** [comment]
@rudrakhsha-c when you load the index, pass in the service context

`index = load_index_from_storage(storage_context, service_context=service_context)`
