### ISSUE TITLE
[Bug]: ImageDocument not setting `id_` property in constructor

### ISSUE THREAD

**Issue by ZachHandley** [run-llama/llama_index#10333]
### Bug Description

I was trying to insert into Qdrant Vector DB which requires UUID's or int's basically, and I was doing the following

```python
async def run_pipeline_async(
        self,
        documents: list[Document | ImageDocument],
        parallel: bool = False,
    ) -> tuple[list[str], list[str]]:
        """
        Runs the pipeline for text documents
        """
        image_documents = []
        text_documents = []
        image_nodes_added = []
        text_nodes_added = []
        for document in documents:
            doc_id = str(ULID.from_timestamp(time.time()).to_uuid())
            print(f"Document ID: {doc_id}")
            if isinstance(document, ImageDocument):
                print("Found an image document")
                # Create the document with the current timestamp ULID
                image_doc = ImageDocument(
                    **document.dict(),
                    # doc_id=doc_id,
                    id_=doc_id,
                )
                image_documents.append(image_doc)
            else:
                print("Found a text document")
                # Create the text document with the current timestamp ULID
                txt_doc = Document(
                    **document.dict(),
                    # doc_id=doc_id,
                    id_=doc_id,
                )
                text_documents.append(txt_doc)
        if parallel:
            if len(image_documents) > 0:
                img_nodes = await self.image_pipeline.arun(
                    documents=image_documents,
                    num_workers=4,
                )
                self.image_nodes.extend(img_nodes)
            if len(text_documents) > 0:
                txt_nodes = await self.text_pipeline.arun(
                    documents=text_documents,
                    num_workers=4,
                )
                self.text_nodes.extend(txt_nodes)
        else:
            if len(image_documents) > 0:
                print(f"Image Documents: {len(image_documents)}")
                img_nodes = await self.image_pipeline.arun(
                    documents=image_documents,
                )
                self.image_nodes.extend(img_nodes)
                print(f"Image Nodes Encoded: {len(img_nodes)}")
            if len(text_documents) > 0:
                print(f"Text Documents: {len(text_documents)}")
                txt_nodes = await self.text_pipeline.arun(
                    documents=text_documents,
                )
                self.text_nodes.extend(txt_nodes)
                print(f"Text Nodes Encoded: {len(self.text_nodes)}")

        if len(self.text_nodes) > 0:
            print(f"Adding Text Nodes, Count: {len(self.text_nodes)}")
            text_nodes_added = await self.txt_vector_store.async_add(
                self.text_nodes
            )
            print(f"Text Nodes Added: {len(text_nodes_added)}")
        if len(self.image_nodes) > 0:
            print(f"Adding Image Nodes, Count: {len(self.image_nodes)}")
            print(
                f"Image Node to Add: {json.dumps(self.image_nodes[0].dict(), indent=4)}"
            )
            image_nodes_added = await self.img_vector_store.async_add(
                self.image_nodes
            )
            print(f"Image Nodes Added: {len(image_nodes_added)}")

        return text_nodes_added, image_nodes_added
```

Thing is, it was giving me an error inserting an `ImageDocument`, and on further debugging, it isn't setting the `doc_id` properly (you can see my commented out attempts)

### Version

0.9.38

### Steps to Reproduce

Using Qdrant (for an error if it's not a UUID), I used `python-ulid` to generate my UUID's based on the current timestamp, so I set the `doc_id` of an ImageDocument and a TextDocument and then printed them, then printed them out after they were embedded as a node, and the node had some old ID (maybe cached?) and yeah so.

Really, you just gotta try to index an ImageDocument and TextDocument with a unique ID generated by you and set it via `doc_id`

### Relevant Logs/Tracbacks

```shell
Adding Text Nodes, Count: 1
Text Nodes Added: 1
Adding Image Nodes, Count: 1
Image Node to Add: {
    "id_": "1234567890_test_image_1",
    "embedding": [
        0.05083873122930527,
        -0.009365182369947433,
        -0.02368076518177986,
        0.030776046216487885,
        0.008690356276929379,
        -0.014311055652797222,
        -0.04092549905180931,
        0.00477311946451664,
        0.0004632243071682751,
        -0.035784319043159485,
        0.01696140691637993,
        0.018940802663564682,
        -0.036646779626607895,
        0.07348212599754333,
        -0.004361686762422323,
        -0.06478264927864075,
        0.03456362336874008,
        0.016546541824936867,
        0.07481683790683746,
        0.01674913987517357,
        -0.03563469648361206,
        0.04614941030740738,
        -0.01496303454041481,
        0.006889647338539362,
        0.04481087252497673,
        -0.00800740160048008,
        -0.004063351079821587,
        -0.019762832671403885,
        -0.008159656077623367,
        -0.03528854623436928,
        -0.022363843396306038,
        0.01639038883149624,
        -0.055741194635629654,
        0.0013736967230215669,
        2.1760217805422144e-06,
        -0.026077304035425186,
        -0.005074073560535908,
        0.003059597220271826,
        0.05153971165418625,
        -0.04916031286120415,
        0.058709245175123215,
        0.033300936222076416,
        -0.015247098170220852,
        -0.03565802797675133,
        -0.04458636790513992,
        -0.008727099746465683,
        -0.026205770671367645,
        0.01756468415260315,
        0.017763037234544754,
        0.036658305674791336,
        0.024883277714252472,
        -0.03833048790693283,
        0.03614046797156334,
        -0.019129227846860886,
        0.03610212355852127,
        -0.03576461970806122,
        0.014621807262301445,
        -0.08647678792476654,
        -0.0021154372952878475,
        -0.04164222255349159,
        0.01943567767739296,
        0.007288013119250536,
        -0.05085529386997223,
        0.02864679880440235,
        0.05160705745220184,
        0.03298065438866615,
        -0.012158233672380447,
        -0.11149156838655472,
        0.0060554565861821175,
        -0.013571237213909626,
        -0.049570128321647644,
        0.04596026614308357,
        -0.015949880704283714,
        -0.019637128338217735,
        -0.02539806254208088,
        -0.034361228346824646,
        -0.05728409066796303,
        0.07299098372459412,
        -0.0064503103494644165,
        -0.03158384561538696,
        -0.05359660089015961,
        -0.011565860360860825,
        -0.00376080721616745,
        0.047093261033296585,
        -0.04653108865022659,
        0.02050160989165306,
        -0.030419310554862022,
        0.017226023599505424,
        0.009347272105515003,
        -0.08452510833740234,
        -0.028289929032325745,
        -0.03657988831400871,
        0.008996326476335526,
        -0.0029852651059627533,
        0.016395917162299156,
        -0.013716014102101326,
        0.0035223644226789474,
        -0.06192085146903992,
        0.07975208759307861,
        -0.041411034762859344,
        -0.01346614956855774,
        -0.08736065030097961,
        0.01403141487389803,
        0.0007787783979438245,
        0.0014991110656410456,
        0.01811615377664566,
        -0.01761407032608986,
        0.00882468931376934,
        -0.022154057398438454,
        0.04837516322731972,
        -0.029126334935426712,
        -0.004911602474749088,
        -0.017194749787449837,
        -0.009073303081095219,
        0.046152886003255844,
        -0.04062138497829437,
        -0.011233781464397907,
        0.0038839757908135653,
        -0.00779692130163312,
        0.036299459636211395,
        0.008138791657984257,
        0.07803621143102646,
        -0.040178634226322174,
        0.018710987642407417,
        0.018888166174292564,
        -0.015496191568672657,
        0.021543243899941444,
        0.011642180383205414,
        -0.005914614535868168,
        0.0495462492108345,
        0.04328996688127518,
        0.027117451652884483,
        0.04848121479153633,
        -0.049225881695747375,
        0.018692022189497948,
        0.02599627524614334,
        0.07398615777492523,
        -0.028635185211896896,
        0.04660646989941597,
        -0.06289642304182053,
        0.013780398294329643,
        0.017238164320588112,
        0.016590431332588196,
        0.023512935265898705,
        -0.03155049681663513,
        -0.06450707465410233,
        0.0468832403421402,
        -0.05062607675790787,
        0.020394133403897285,
        0.050161056220531464,
        -0.05138728395104408,
        0.0798221156001091,
        0.006296361796557903,
        -0.021749304607510567,
        -0.0356825515627861,
        -0.014493176713585854,
        -0.053962819278240204,
        -0.02441687136888504,
        -0.040753260254859924,
        0.07974862307310104,
        0.03118463046848774,
        -0.02664070390164852,
        0.03625257685780525,
        -0.0220961831510067,
        -0.028247326612472534,
        -0.04772181063890457,
        -0.0005146321491338313,
        -0.05992585048079491,
        -0.0669708177447319,
        0.049148786813020706,
        -0.0031832545064389706,
        0.027177808806300163,
        0.026902951300144196,
        0.041339460760354996,
        0.018669368699193,
        0.09045800566673279,
        0.055186815559864044,
        -0.06546232104301453,
        -0.029749874025583267,
        -0.007886774837970734,
        -0.00722063472494483,
        0.008769641630351543,
        -0.032811786979436874,
        -0.029374204576015472,
        0.01882161758840084,
        0.06392131000757217,
        -0.01633930578827858,
        0.04918494448065758,
        0.045620694756507874,
        0.002774751977995038,
        0.03658771142363548,
        0.04099942371249199,
        -0.02828262560069561,
        -0.04632197692990303,
        0.05000420659780502,
        0.0174929928034544,
        -0.05039256438612938,
        -0.053365956991910934,
        -0.02522207796573639,
        -0.0019513946026563644,
        0.015037690289318562,
        -0.0013052629074081779,
        0.006647109054028988,
        -0.07355701178312302,
        0.006923529785126448,
        0.03473944962024689,
        -0.003576405346393585,
        0.006889663636684418,
        -0.07263293117284775,
        0.03016136772930622,
        -0.026400506496429443,
        0.00492338789626956,
        -0.0036699222400784492,
        0.005394048988819122,
        -0.07189469039440155,
        -0.028337949886918068,
        0.018338672816753387,
        -0.06709939241409302,
        0.016351930797100067,
        0.014086215756833553,
        0.006096786353737116,
        -0.02498544380068779,
        0.002678816206753254,
        0.0077339280396699905,
        0.04301027953624725,
        0.0010536079062148929,
        0.014982686378061771,
        -0.021229328587651253,
        -0.05463189259171486,
        -0.01416082214564085,
        -0.0358930304646492,
        0.052940528839826584,
        0.05849291384220123,
        0.02891363389790058,
        -0.04418927803635597,
        -0.003989330492913723,
        0.04424426704645157,
        0.030266353860497475,
        0.06412172317504883,
        0.0002882284752558917,
        -0.008226863108575344,
        0.024552974849939346,
        0.024504685774445534,
        0.03547152131795883,
        0.041874151676893234,
        0.04346879944205284,
        0.005684528965502977,
        -0.007904653437435627,
        0.03042108751833439,
        -0.019887462258338928,
        0.03927981108427048,
        -0.03296447917819023,
        -0.022812936455011368,
        -0.004916799254715443,
        -0.014207616448402405,
        -0.11797100305557251,
        -0.07263237982988358,
        -0.011346077546477318,
        -0.01270812563598156,
        0.006727656815201044,
        0.0928262323141098,
        -0.027105633169412613,
        0.034740202128887177,
        7.900083437561989e-05,
        0.0849151685833931,
        -0.0546620711684227,
        0.027247270569205284,
        0.007354694418609142,
        -0.017235511913895607,
        0.03646857663989067,
        0.0026537308003753424,
        -0.0703723207116127,
        0.009988839738070965,
        -0.01325638871639967,
        0.0034660841338336468,
        0.026407329365611076,
        -0.002911314368247986,
        0.0032605386804789305,
        0.015169463120400906,
        0.007104677148163319,
        -0.029943084344267845,
        -0.001716732163913548,
        -0.06681562215089798,
        -0.014823595061898232,
        0.011176479049026966,
        0.0526716485619545,
        -0.011358298361301422,
        -0.03836073353886604,
        0.03318818658590317,
        0.023487890139222145,
        0.022582994773983955,
        0.019063357263803482,
        0.01888539083302021,
        -0.004418579861521721,
        0.008685157634317875,
        -0.04543878138065338,
        -0.03745370730757713,
        0.04602967947721481,
        -0.00315852090716362,
        -0.02148844487965107,
        -0.03213934972882271,
        -0.007357628084719181,
        -0.006231473758816719,
        -0.01802925579249859,
        -0.014609009027481079,
        0.011272992007434368,
        0.057463616132736206,
        0.0007060869829729199,
        0.02221606858074665,
        0.005932793952524662,
        0.03138056769967079,
        -0.007934089750051498,
        0.033732835203409195,
        0.06971689313650131,
        -0.04169848933815956,
        0.008043453097343445,
        -0.038384564220905304,
        -0.05124567821621895,
        0.004843713715672493,
        0.06921748071908951,
        0.03380843624472618,
        -0.04418090358376503,
        -0.04488315433263779,
        -0.006181578151881695,
        0.059116292744874954,
        -0.060977157205343246,
        -0.03980294242501259,
        -0.014967347495257854,
        -0.00043987270328216255,
        0.0036998020950704813,
        0.0001978042273549363,
        -0.022611280903220177,
        0.02926669269800186,
        -0.01958036608994007,
        -0.03328258916735649,
        0.0427568182349205,
        -0.033358555287122726,
        -0.00869385339319706,
        -0.002877116436138749,
        -0.019286802038550377,
        0.05160871520638466,
        0.059919100254774094,
        -0.02222185581922531,
        -0.012560628354549408,
        -0.03713124245405197,
        -0.004199339542537928,
        0.026315098628401756,
        -0.030820149928331375,
        -0.01644338294863701,
        0.029802817851305008,
        -0.023816965520381927,
        0.025400418788194656,
        -0.004492633044719696,
        -0.037134863436222076,
        -0.018076488748192787,
        0.020991450175642967,
        -0.0005515615339390934,
        -0.01672244630753994,
        -0.017673177644610405,
        0.008702097460627556,
        0.0622953325510025,
        0.04323522001504898,
        0.0691363587975502,
        0.07329221069812775,
        -0.07248831540346146,
        0.012738858349621296,
        -0.0055707949213683605,
        -0.09113721549510956,
        -0.01919800415635109,
        -0.03332921490073204,
        -0.02817072719335556,
        0.03405464440584183,
        0.05149943381547928,
        0.04311051219701767,
        0.016610579565167427,
        -0.05964210256934166,
        -0.014621648006141186,
        0.044800303876399994,
        -0.11846018582582474,
        0.009284851141273975,
        0.010372884571552277,
        -0.014831497333943844,
        -0.014728103764355183,
        0.03872515261173248,
        0.009576964192092419,
        -0.004029723349958658,
        -0.05270416662096977,
        -0.062227148562669754,
        -0.060909345746040344,
        0.02227173000574112,
        -0.00864801462739706,
        -0.012478371150791645,
        -0.10400527715682983,
        -0.026919152587652206,
        -0.0010484042577445507,
        0.009388229809701443,
        0.014939865097403526,
        -0.07253966480493546,
        0.002100599929690361,
        0.0002764899400062859,
        0.0012482047313824296,
        0.0649954304099083,
        -0.03138713166117668,
        0.01820012554526329,
        -0.0220672395080328,
        -0.018645312637090683,
        0.07535994797945023,
        0.036520425230264664,
        -0.0245770663022995,
        0.017515137791633606,
        0.06064582243561745,
        0.0510372519493103,
        0.02883906662464142,
        -0.018097825348377228,
        0.008076151832938194,
        -0.040756456553936005,
        -0.027826586738228798,
        0.05049169808626175,
        -0.06524746865034103,
        -0.04974408447742462,
        -0.06334635615348816,
        -0.005075029097497463,
        0.041613850742578506,
        0.0489535853266716,
        -0.03020983748137951,
        -0.09465085715055466,
        0.02010779082775116,
        0.010442173108458519,
        -0.0019182077376171947,
        0.014619595371186733,
        0.013726352714002132,
        0.025065435096621513,
        -0.006739311385899782,
        -0.022182732820510864,
        -0.01464714203029871,
        -0.024708805605769157,
        0.025692690163850784,
        0.004362661857157946,
        0.009395149536430836,
        -0.07152450829744339,
        0.005470473784953356,
        -0.013215089216828346,
        0.03911273181438446,
        0.0053654019720852375,
        0.04573722183704376,
        0.012461461126804352,
        -0.005633619613945484,
        -0.025451717898249626,
        0.0039421506226062775,
        0.02844334952533245,
        0.031726110726594925,
        -0.03465427830815315,
        -0.0052862889133393764,
        -0.02028762176632881,
        0.003516220021992922,
        -0.030608490109443665,
        0.038526587188243866,
        -0.05650978907942772,
        -0.01313729491084814,
        0.05994049459695816,
        0.029308730736374855,
        -0.0029254606924951077,
        -0.03292180970311165,
        -0.007753993850201368,
        -0.030776282772421837,
        0.02357124350965023,
        0.05641262233257294,
        -0.04116320610046387,
        0.014619434252381325,
        0.017955701798200607,
        0.009151550009846687,
        0.02340744249522686,
        -0.00714071374386549,
        0.0021649340633302927,
        0.08328241854906082,
        -0.011650243774056435,
        0.01551596075296402,
        -0.03400720655918121,
        -0.04930127039551735,
        -0.0008116055396385491,
        0.022979091852903366,
        0.0070709832943975925,
        -0.03536522760987282,
        -0.03833289071917534,
        -0.02420022338628769,
        -0.005618988070636988,
        0.051637742668390274,
        -0.02984965406358242,
        0.0023040035739541054,
        -0.025265445932745934,
        0.027066670358181,
        -0.04572271928191185,
        0.017976850271224976,
        0.038952913135290146,
        0.007366723846644163,
        -0.013357541523873806,
        -0.04932517930865288,
        -0.027580002322793007,
        0.04739981144666672,
        -0.01651032641530037,
        0.023026399314403534,
        -0.016315443441271782,
        0.024763599038124084,
        0.022667672485113144,
        -0.07963000237941742,
        0.026954948902130127,
        0.015406451188027859,
        0.0017210044898092747,
        -0.047221530228853226,
        -0.06755442172288895,
        -0.06795661896467209,
        0.008171778172254562,
        -0.04921109974384308,
        -0.04699065536260605,
        -0.013939794152975082,
        -0.0038422371726483107,
        0.001779783982783556,
        -0.08673051744699478,
        0.007304375525563955,
        -0.009137802757322788,
        0.02941807359457016,
        -0.017851704731583595,
        -0.033278051763772964,
        0.01437276042997837,
        0.04139911010861397,
        0.03883052617311478,
        -0.0017153809312731028,
        0.017263224348425865,
        0.08187902718782425,
        0.015010167844593525,
        0.005873174872249365,
        0.031276557594537735,
        -0.007902007550001144,
        -0.02583932690322399,
        -0.0208470169454813,
        0.04947556555271149,
        0.06027420982718468,
        0.045878514647483826,
        0.01756957732141018,
        0.01969718188047409,
        0.007169903255999088,
        -0.0452473908662796,
        -0.006763272453099489,
        0.03337397426366806,
        0.03336072713136673,
        -0.025414377450942993,
        -0.03719819337129593,
        0.05360175669193268,
        -0.0005124334711581469,
        -0.027965378016233444,
        -0.008628937415778637,
        0.07444816827774048,
        0.00262870523147285,
        -0.020103830844163895,
        -0.005790466908365488,
        -9.021952203339674e-33,
        0.007083074189722538,
        -0.060852911323308945,
        -0.005388573743402958,
        -0.0027954927645623684,
        0.008621775545179844,
        0.012117310427129269,
        0.005002888850867748,
        -0.011515248566865921,
        -0.04795118421316147,
        0.003344031050801277,
        -0.013241464272141457,
        -0.017397990450263023,
        0.029023325070738792,
        -0.014311798848211765,
        0.012436958029866219,
        0.03728083148598671,
        -0.01866396889090538,
        0.03293488919734955,
        0.021239079535007477,
        0.026055345311760902,
        -0.05511758476495743,
        0.043443676084280014,
        0.10116689652204514,
        0.001280639204196632,
        0.009151510894298553,
        0.06837576627731323,
        -0.057075385004282,
        -0.0080926064401865,
        -0.016390375792980194,
        0.028974182903766632,
        -0.015162850730121136,
        0.0362207293510437,
        -0.04098576679825783,
        -0.007115519139915705,
        -0.04642403498291969,
        -0.0454382449388504,
        -0.004714039154350758,
        -0.03617523983120918,
        -0.019499333575367928,
        0.0210904348641634,
        -0.0015905658947303891,
        0.015251880511641502,
        0.050424907356500626,
        -0.006178933195769787,
        0.027813471853733063,
        0.020179759711027145,
        0.02910168655216694,
        0.006376884412020445,
        -0.08721089363098145,
        0.015040729194879532,
        -0.012030900456011295,
        0.05223565921187401,
        0.019506139680743217,
        -0.018881062045693398,
        0.02999844402074814,
        -0.027129750698804855,
        0.02335214614868164,
        0.01801810972392559,
        0.014155675657093525,
        0.026405315846204758,
        -0.025224823504686356,
        4.5814875193173066e-05,
        0.0726332888007164,
        0.002868380630388856,
        -0.0351848341524601,
        0.055776651948690414,
        0.01765543222427368,
        -0.00319538707844913,
        0.04795689508318901,
        0.0003227634006179869,
        0.018589356914162636,
        0.011606023646891117,
        -0.012139804661273956,
        -0.0207041185349226,
        -0.01610206812620163,
        0.02593100070953369,
        0.03952460363507271,
        0.026625407859683037,
        0.0014568987535312772,
        0.08467301726341248,
        -0.026285827159881592,
        -0.024916158989071846,
        0.020213797688484192,
        0.021125465631484985,
        -0.0455610454082489,
        -0.08262348175048828,
        -0.029593680053949356,
        0.03909558057785034,
        -0.02961615100502968,
        0.007935798726975918,
        -0.019459372386336327,
        0.05826008692383766,
        -0.055078789591789246,
        -0.007760698441416025,
        0.025080488994717598,
        0.05286597087979317,
        -0.009328975342214108,
        0.039514847099781036,
        -0.04286469891667366,
        -0.002636900171637535,
        0.06307343393564224,
        0.013773108832538128,
        -0.01798975095152855,
        0.010335105471313,
        0.05214932560920715,
        0.01286470890045166,
        -0.0277196504175663,
        -0.013157364912331104,
        -0.06420130282640457,
        -0.03786756843328476,
        -0.04531024768948555,
        -0.031574200838804245,
        0.055510178208351135,
        0.019839469343423843,
        0.015040050260722637,
        0.011222685687243938,
        -0.005272206850349903,
        0.018960772082209587,
        0.04285769537091255,
        0.033860720694065094,
        -0.00875488668680191,
        0.05645923689007759,
        -0.012686275877058506,
        -0.00010618274245643988,
        -0.024953719228506088,
        0.010234707035124302,
        -0.04349243640899658,
        -0.02683599852025509,
        -0.0012355208164080977,
        -0.0021854443475604057,
        0.008830777369439602,
        0.0031114486046135426,
        2.6920156415144447e-07,
        -0.008976168930530548,
        0.05532890558242798,
        0.001489719026722014,
        0.03536249324679375,
        -0.00443688640370965,
        0.07111739367246628,
        0.032693929970264435,
        -0.02031056396663189,
        -0.03822557255625725,
        0.013194859027862549,
        0.017992917448282242,
        0.010586357675492764,
        -0.08963309228420258,
        0.007082980591803789,
        -0.022666901350021362,
        -0.06093376502394676,
        -0.06599460542201996,
        0.02230134792625904,
        -0.059582341462373734,
        -0.0146385058760643,
        0.042097002267837524,
        0.04226217791438103,
        0.05719425529241562,
        -0.08061783015727997,
        -0.020847689360380173,
        -0.07858041673898697,
        -0.06553301215171814,
        0.008253393694758415,
        -0.018589120358228683,
        0.0018039895221590996,
        0.003455412108451128,
        -0.006865937728434801,
        0.038143228739500046,
        0.012356593273580074,
        -0.026950441300868988,
        0.017060333862900734,
        0.013888896442949772,
        -0.0070930360816419125,
        -0.0351099818944931,
        0.008573275059461594,
        0.02324267476797104,
        0.04828891158103943,
        0.034710273146629333,
        -0.0385873019695282,
        0.027491450309753418,
        0.027736779302358627,
        0.018368931487202644,
        -0.07117386162281036,
        -0.008488953113555908,
        0.00799488928169012,
        0.03421798720955849,
        -0.019822893664240837,
        -0.002423922996968031,
        0.02086450159549713,
        0.006155758630484343,
        0.009831875562667847,
        -0.028965048491954803,
        0.0075844223611056805,
        0.0261202584952116,
        -0.0013265687739476562,
        -0.028498893603682518,
        0.030654866248369217,
        -0.03564242273569107,
        0.02329537272453308,
        -0.025135386735200882,
        0.025360526517033577,
        0.00023348662944044918,
        8.679189070899433e-36,
        0.010254627093672752,
        0.0123567134141922,
        0.02897254377603531,
        0.014894581399857998,
        0.02515966072678566,
        0.03177553415298462,
        0.019243936985731125,
        0.03907794877886772,
        -0.017742395401000977,
        -0.08459197729825974,
        -0.00029808716499246657
    ],
    "metadata": {
        "keywords": {
            "keywords": [
                {
                    "keyword": "raspberries",
                    "confidence": 0.95
                },
                {
                    "keyword": "fruit",
                    "confidence": 0.9
                },
                {
                    "keyword": "bowl",
                    "confidence": 0.85
                },
                {
                    "keyword": "fresh",
                    "confidence": 0.8
                },
                {
                    "keyword": "red",
                    "confidence": 0.75
                }
            ]
        }
    },
    "excluded_embed_metadata_keys": [],
    "excluded_llm_metadata_keys": [],
    "relationships": {},
    "text": "This is a test image document for the AI pipeline. It is a picture pulled randomly.",
    "start_char_idx": null,
    "end_char_idx": null,
    "text_template": "{metadata_str}\n\n{content}",
    "metadata_template": "{key}: {value}",
    "metadata_seperator": "\n",
    "class_name": "Document"
}
Traceback (most recent call last):
  File "/Users/my-user/Documents/GitHub/my-folder/api/app/db/vector_stores_temp.py", line 190, in <module>
    asyncio.run(main())
  File "/Users/my-user/Documents/GitHub/my-folder/api/.venv/lib/python3.11/site-packages/nest_asyncio.py", line 31, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my-user/Documents/GitHub/my-folder/api/.venv/lib/python3.11/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/my-user/Documents/GitHub/my-folder/api/app/db/vector_stores_temp.py", line 182, in main
    text_node_ids, image_node_ids = await vector_store_temp.run_test_pipeline(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my-user/Documents/GitHub/my-folder/api/app/db/vector_stores_temp.py", line 122, in run_test_pipeline
    ) = await VectorStoreTemp._pipeline.run_pipeline_async(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my-user/Documents/GitHub/my-folder/api/app/ai/zpipeline.py", line 233, in run_pipeline_async
    image_nodes_added = await self.img_vector_store.async_add(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my-user/Documents/GitHub/my-folder/api/.venv/lib/python3.11/site-packages/llama_index/vector_stores/qdrant.py", line 264, in async_add
    await self._aclient.upsert(
  File "/Users/my-user/Documents/GitHub/my-folder/api/.venv/lib/python3.11/site-packages/qdrant_client/async_qdrant_client.py", line 947, in upsert
    return await self._client.upsert(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my-user/Documents/GitHub/my-folder/api/.venv/lib/python3.11/site-packages/qdrant_client/async_qdrant_remote.py", line 1106, in upsert
    await self.openapi_client.points_api.upsert_points(
  File "/Users/my-user/Documents/GitHub/my-folder/api/.venv/lib/python3.11/site-packages/qdrant_client/http/api/points_api.py", line 1090, in upsert_points
    return await self._build_for_upsert_points(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my-user/Documents/GitHub/my-folder/api/.venv/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 146, in request
    return await self.send(request, type_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my-user/Documents/GitHub/my-folder/api/.venv/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 169, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Format error in JSON body: data did not match any variant of untagged enum PointInsertOperations"},"time":0.0}'
```

**Comment by ZachHandley** [comment]
I take it all back, RedisCache was messing with me.
