### ISSUE TITLE
[Question]: Using query_engine.query() failed as socket cannot be created

### ISSUE THREAD

**Issue by njuthappy** [run-llama/llama_index#10332]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

[Question]: Using query_engine.query() failed as socket cannot be created
"Traceback (most recent call last):
  File "D:\Software_Route\Anaconda\envs\yezituanlc\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\Software_Route\Anaconda\envs\yezituanlc\lib\site-packages\httpcore\_backends\sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "D:\Software_Route\Anaconda\envs\yezituanlc\lib\socket.py", line 847, in create_connection
    raise err
  File "D:\Software_Route\Anaconda\envs\yezituanlc\lib\socket.py", line 835, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060]"

**Comment by njuthappy** [comment]
AddressFamily.AF_INET SocketKind.SOCK_STREAM 0  ('172.67.69.87', 443) asdfffff%%%%%%%%%%%%
timeout 5.0 xxxxxxxxx
AddressFamily.AF_INET SocketKind.SOCK_STREAM 0  ('104.26.5.130', 443) asdfffff%%%%%%%%%%%%
timeout 5.0 xxxxxxxxx
AddressFamily.AF_INET SocketKind.SOCK_STREAM 0  ('104.26.4.130', 443) 

"D:\Software_Route\Anaconda\envs\yezituanlc\lib\socket.py", line 847, in create_connection

I locate the error happen at "create connection". I am using a proxy to visit replicate LLM, not sure if there is any method to set de proxy when creating the connection.

**Comment by hatianzhang** [comment]
ic. can you try not to use proxy?
