### ISSUE TITLE
[Bug]: Lamma2 model can't be a JSONQueryEngine.

### ISSUE THREAD

**Issue by wangm23456** [run-llama/llama_index#10352]
### Bug Description

Lamma2 model can't be a JSONQueryEngine.

I run the example in document: https://docs.llamaindex.ai/en/stable/examples/query_engine/json_query_engine.html

The following error occurred：

### Version

0.9.39

### Steps to Reproduce

```python
from llama_index.llms import OpenAILike

default_remote_model = {   
    "model": "ollama/llama2:7b-chat-q4_0",
    "temperature": 0.0, 
    "api_key": "Bearer sk-***",
    "api_base": "http://localhost:port",
    "max_tokens": 256
}
llm = OpenAILike(**default_remote_model)
llm.is_chat_model = True

from llama_index.indices.service_context import ServiceContext
from llama_index.llms import OpenAI
from llama_index.indices.struct_store import JSONQueryEngine
import json

def build_json_query(llm):
    json_value = {
        "blogPosts": [
            {
                "id": 1,
                "title": "First blog post",
                "content": "This is my first blog post",
            },
            {
                "id": 2,
                "title": "Second blog post",
                "content": "This is my second blog post",
            },
        ],
        "comments": [
            {
                "id": 1,
                "content": "Nice post!",
                "username": "jerry",
                "blogPostId": 1,
            },
            {
                "id": 2,
                "content": "Interesting thoughts",
                "username": "simon",
                "blogPostId": 2,
            },
            {
                "id": 3,
                "content": "Loved reading this!",
                "username": "simon",
                "blogPostId": 2,
            },
        ],
    }

    # JSON Schema object that the above JSON value conforms to
    json_schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "description": "Schema for a very simple blog post app",
        "type": "object",
        "properties": {
            "blogPosts": {
                "description": "List of blog posts",
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "Unique identifier for the blog post",
                            "type": "integer",
                        },
                        "title": {
                            "description": "Title of the blog post",
                            "type": "string",
                        },
                        "content": {
                            "description": "Content of the blog post",
                            "type": "string",
                        },
                    },
                    "required": ["id", "title", "content"],
                },
            },
            "comments": {
                "description": "List of comments on blog posts",
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "description": "Unique identifier for the comment",
                            "type": "integer",
                        },
                        "content": {
                            "description": "Content of the comment",
                            "type": "string",
                        },
                        "username": {
                            "description": (
                                "Username of the commenter (lowercased)"
                            ),
                            "type": "string",
                        },
                        "blogPostId": {
                            "description": (
                                "Identifier for the blog post to which the comment"
                                " belongs"
                            ),
                            "type": "integer",
                        },
                    },
                    "required": ["id", "content", "username", "blogPostId"],
                },
            },
        },
        "required": ["blogPosts", "comments"],
    }
    # llm.is_chat_model = False
    service_context = ServiceContext.from_defaults(
        chunk_size=1024,
        llm=llm,
    )
    # json_value = json.load(open(json_path, "r"))
    nl_query_engine = JSONQueryEngine(
        json_value=json_value,
        json_schema=json_schema,
        service_context=service_context,
        # synthesize_response=True,
    )
    return nl_query_engine

query_engine = build_json_query(llm)
response = query_engine.query(message)
```

### Relevant Logs/Tracbacks

```shell
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/pyenv/lib/python3.10/site-packages/llama_index/indices/struct_store/json_query.py", line 56, in default_output_processor
    datum: List[DatumInContext] = parse(expression).find(json_value)
  File "/pyenv/lib/python3.10/site-packages/jsonpath_ng/ext/parser.py", line 174, in parse
    return ExtentedJsonPathParser(debug=debug).parse(path)
  File "/pyenv/lib/python3.10/site-packages/jsonpath_ng/parser.py", line 38, in parse
    return self.parse_token_stream(lexer.tokenize(string))
  File "/pyenv/lib/python3.10/site-packages/jsonpath_ng/parser.py", line 62, in parse_token_stream
    return new_parser.parse(lexer = IteratorToTokenStream(token_iterator))
  File "/pyenv/lib/python3.10/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/pyenv/lib/python3.10/site-packages/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/pyenv/lib/python3.10/site-packages/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/pyenv/lib/python3.10/site-packages/jsonpath_ng/parser.py", line 78, in p_error
    raise JsonPathParserError('Parse error at %s:%s near token %s (%s)'
jsonpath_ng.exceptions.JsonPathParserError: Parse error at 1:3 near token retrieve (ID)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pyenv/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/pyenv/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/pyenv/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/pyenv/lib/python3.10/site-packages/gradio/blocks.py", line 1183, in call_function
    prediction = await fn(*processed_input)
  File "/pyenv/lib/python3.10/site-packages/gradio/utils.py", line 636, in async_wrapper
    response = await f(*args, **kwargs)
  File "/pyenv/lib/python3.10/site-packages/gradio/chat_interface.py", line 410, in _submit_fn
    response = await anyio.to_thread.run_sync(
  File "/pyenv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/pyenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/pyenv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/pyenv/llamaIndex/test_gradio.py", line 90, in qa
    return query(message, history)
  File "/pyenv/llamaIndex/test_gradio.py", line 78, in query
    response = query_engine.query(message)
  File "/pyenv/lib/python3.10/site-packages/llama_index/core/base_query_engine.py", line 40, in query
    return self._query(str_or_query_bundle)
  File "/pyenv/lib/python3.10/site-packages/llama_index/indices/struct_store/json_query.py", line 151, in _query
    json_path_output = self._output_processor(
  File "/pyenv/lib/python3.10/site-packages/llama_index/indices/struct_store/json_query.py", line 63, in default_output_processor
    raise ValueError(f"Invalid JSON Path: {expression}") from exc
ValueError: Invalid JSON Path: To retrieve the comments written by Jerry using JSON Path
```

**Comment by logan-markewich** [comment]
This relies on the LLM writing correct JSON. You can try engineering the prompt template, but in general, I would expect llama2 to be very bad at this (and open-source models in general for this task)
https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/usage_pattern.html#getting-and-setting-custom-prompts
