### ISSUE TITLE
[Bug]: `from llama_index import Document` no longer working

### ISSUE THREAD

**Issue by juleskuehn** [run-llama/llama_index#10396]
### Bug Description

Upgrading to LlamaIndex v0.9.40 (from v.0.9.22) a new error occurred resulting from `from llama_index import Document`

This caused the following error:
```
ModuleNotFoundError: No module named 'llama_index.llms.custom'
```

Changing the import code to `from llama_index.schema import Document` solves the problem.

### Version

0.9.40

### Steps to Reproduce

`from llama_index import Document`

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\django\core\management\__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jkuehn\git_repos\otto\django\librarian\models.py", line 13, in <module>
    from llama_index import Document as LlamaDocument
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\llama_index\__init__.py", line 13, in <module>
    from llama_index.callbacks.global_handlers import set_global_handler
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\llama_index\callbacks\__init__.py", line 7, in <module>
    from .token_counting import TokenCountingHandler
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\llama_index\callbacks\token_counting.py", line 6, in <module>
    from llama_index.utilities.token_counting import TokenCounter
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\llama_index\utilities\token_counting.py", line 6, in <module>
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\llama_index\llms\__init__.py", line 1, in <module>
  File "C:\Users\jkuehn\AppData\Roaming\Python\Python311\site-packages\llama_index\llms\ai21.py", line 7, in <module>
ModuleNotFoundError: No module named 'llama_index.llms.custom'
```

**Comment by logan-markewich** [comment]
@juleskuehn I cannot reproduce
https://colab.research.google.com/drive/18A1BuaNX1aQG_z6-8nSFUs04Wx2vTrKF?usp=sharing

**Comment by juleskuehn** [comment]
Weird. Now I can't either. Sorry about that!
