### ISSUE TITLE
[Documentation]: clear docs on using streaming with ReAct Agent (and other agents)

### ISSUE THREAD

**Issue by nick-youngblut** [run-llama/llama_index#10484]
### Documentation Issue Description

https://docs.llamaindex.ai/en/latest/examples/agent/react_agent_with_query_engine.html# does not contain any info on using `agent.stream_chat()` instead of `agent.chat()`.

Using `stream_chat()` as shown in https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/root.html#usage-pattern does not work.

In general, it is not very clear where streaming is supported versus not, and when supported, how to implement it. For instance, if stream_chat() is asynchronous, then how can that be implemented in a streamlit app (or similar)?

### Documentation Link

https://docs.llamaindex.ai/en/latest/examples/agent/react_agent_with_query_engine.html#

**Comment by logan-markewich** [comment]
@nick-youngblut why does that example in the second link not work? It works for me

https://colab.research.google.com/drive/1MKsvvds2PVd3mKGgot4lDycvP0AdjwtI?usp=sharing

It depends on the LLM you are using having streaming implemented though

**Comment by nick-youngblut** [comment]
@logan-markewich thanks for the quick response! Do you know why `stream_chat()` would throw an error that usually indicates an asynchronous operation, but I'm using `stream_chat()` and not `astream_chat()`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/workspaces/genomics_guide/app.py", line 147, in <module>
    resp = st.session_state.query_engine.stream_chat(prompt)
  File "/usr/local/lib/python3.9/site-packages/llama_index/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/llama_index/agent/runner/base.py", line 539, in stream_chat
    chat_response = self._chat(
  File "/usr/local/lib/python3.9/site-packages/llama_index/agent/runner/base.py", line 442, in _chat
    cur_step_output = self._run_step(
  File "/usr/local/lib/python3.9/site-packages/llama_index/agent/runner/base.py", line 306, in _run_step
    cur_step_output = self.agent_worker.stream_step(step, task, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/llama_index/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/llama_index/agent/react/step.py", line 621, in stream_step
    return self._run_step_stream(step, task)
  File "/usr/local/lib/python3.9/site-packages/llama_index/agent/react/step.py", line 527, in _run_step_stream
    agent_response = StreamingAgentChatResponse(
  File "<string>", line 10, in __init__
  File "/usr/local/lib/python3.9/asyncio/queues.py", line 36, in __init__
    self._loop = events.get_event_loop()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.
```

Note the use of `asyncio`.

**Comment by logan-markewich** [comment]
Dosu was hallucinating

I'm guessing it's failing due to this default factory?
https://github.com/run-llama/llama_index/blob/0bcc8b509a698a455f9b0868c18d57613f692b21/llama_index/chat_engine/types.py#L65

**Comment by nick-youngblut** [comment]
It appears that just the initialization of `asyncio.Queue` does not play nicely with streamlit.

**Comment by logan-markewich** [comment]
@nick-youngblut yea a lazy init is the solution here it seems

**Comment by sherif-abdelkarim** [comment]
@nick-youngblut I am currently facing the same issue as well. Are you going to make a pull request with your modifications above or should I do it?

**Comment by nick-youngblut** [comment]
Please go ahead. I'm currently focused on other priorities that have nothing to do with llama-index.

**Comment by sherif-abdelkarim** [comment]
> Please go ahead. I'm currently focused on other priorities that have nothing to do with llama-index.

Thank you.
