### ISSUE TITLE
[Feature Request]: support gguf for embed_model

### ISSUE THREAD

**Issue by sirus20x6** [run-llama/llama_index#10515]
### Feature Description

it appears that gguf isn't supported for embedding models

```
...................................................................................................
llama_new_context_with_model: n_ctx      = 4000
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =   500.00 MiB
llama_new_context_with_model: KV self size  =  500.00 MiB, K (f16):  250.00 MiB, V (f16):  250.00 MiB
llama_new_context_with_model:        CPU input buffer size   =    15.83 MiB
llama_new_context_with_model:        CPU compute buffer size =   301.40 MiB
llama_new_context_with_model: graph splits (measure): 1
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
Model metadata: {'tokenizer.ggml.add_eos_token': 'false', 'tokenizer.ggml.padding_token_id': '2', 'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.architecture': 'llama', 'llama.rope.freq_base': '10000.000000', 'llama.context_length': '32768', 'general.name': 'cognitivecomputations_dolphin-2.6-mistral-7b-dpo-laser', 'tokenizer.ggml.add_bos_token': 'true', 'llama.embedding_length': '4096', 'llama.feed_forward_length': '14336', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'llama.rope.dimension_count': '128', 'tokenizer.ggml.bos_token_id': '1', 'llama.attention.head_count': '32', 'llama.block_count': '32', 'llama.attention.head_count_kv': '8', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.file_type': '7'}
/usr/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/usr/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/code/git/ontherag/./myrag.py", line 49, in <module>
    service_context = ServiceContext.from_defaults(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/llama_index/service_context.py", line 191, in from_defaults
    embed_model = resolve_embed_model(embed_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/llama_index/embeddings/utils.py", line 84, in resolve_embed_model
    embed_model = HuggingFaceEmbedding(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/llama_index/embeddings/huggingface.py", line 82, in __init__
    model = AutoModel.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3194, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory e5-mistral-7b-instruct.

```

### Reason

I don't know enough about llamaindex to answer what's stopping the feature from working.

### Value of Feature

gguf is smaller, faster, and all in one file that has almost no perplexity loss vs fp16

**Comment by logan-markewich** [comment]
@sirus20x6 I think huggingface technically supports it, I just haven't implemented the code to detect and load gguf files.

If you can point me towards docs for how to load with huggingface, that will probably help motivate me to implement it haha

**Comment by logan-markewich** [comment]
As a workaround, you can load the model and tokenizer, and pass it in

```
model = <load model from huggingface>
tokenizer = <load tokenizer from huggingface>
embed_model = HuggingFaceEmbedding(model=model, tokenizer=tokenizer,  ..)
```

**Comment by sirus20x6** [comment]
so I have to upload the model to hugging face and then use that format? oh wait. I'm not sure what to even use for tokenizer. is that just the tokenizer.json from the original fp16?

**Comment by logan-markewich** [comment]
You tell me hahaha 

I think it probably is. 

Not saying you have to upload the model to huggingface, just that it has to be loaded with huggingface modules in order to work with HuggingFaceLLM

Really though, for gguf, you should be using ollama or llama.cpp (both of which we have support for)

**Comment by sirus20x6** [comment]
how do I use llama.ccp in llamaindex for embeddings?

**Comment by logan-markewich** [comment]
@sirus20x6 you can't at the moment (and tbh I really wouldn't recommend it either -- using an LLM for embeddings is pretty subpar, using an actual model trained for embeddings is ideal (I.e. bge, etc.)

**Comment by sirus20x6** [comment]
according to the embedding leaderboard https://huggingface.co/spaces/mteb/leaderboard [Salesforce](https://huggingface.co/Salesforce)
/
[SFR-Embedding-Mistral](https://huggingface.co/Salesforce/SFR-Embedding-Mistral) is the highest ranking embedding model. the gguf is found here https://huggingface.co/dranger003/SFR-Embedding-Mistral-GGUF

**Comment by logan-markewich** [comment]
If you want to contribute an embedding class to support this, I encourage you to :) 

(Imo, maybe a spicy take, a 14GB embedding model that barely beats a 1GB embedding model doesn't feel very worth it)

**Comment by sirus20x6** [comment]
well I spent good money on 512GB of ram for a reason
