### ISSUE TITLE
[Question]: Trying to add a custom LlamaFactory LLM

### ISSUE THREAD

**Issue by jayavanth** [run-llama/llama_index#10555]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I wrapped the LlamaFactory LLM in this class but when run it, the response is empty and I'm getting these bunch of pydantic errors

Class based on CustomLLM:
```
class LlamaFactoryLLM(CustomLLM):
    _model = ChatModel()
    context_window: int = Field(
        default=3900,
        description="The maximum number of context tokens for the model.",
        gt=0,
    )
    def __init__(self, *args, **kwargs)-> None:
        super().__init__(*args, **kwargs)

        # self.context_window = 3000

        #self._model = ChatModel()  # Initialize LlamaFactory ChatModel

    @llm_chat_callback()
    def chat(self, messages: Sequence[ChatMessage], **kwargs) -> ChatResponse:
        responses = self._model.chat(messages, **kwargs)
        return [ChatResponse(response_text=response.response_text) for response in responses]

    @llm_chat_callback()
    def stream_chat(
        self,
        xyz, abc 
    ) -> Generator[str, None, None]:
        # Call stream_chat of ChatModel
        print(xyz, abc)
        return self._model.stream_chat(xyz,abc)


    def complete(self, *args, **kwargs):
        pass

    def stream_complete(self, *args, **kwargs):
        pass

    @property
    def metadata(self) -> LLMMetadata:
        """LLM metadata."""
        return LLMMetadata(
            context_window = self.context_window,
            num_output = 3000,
        )
```

```
WARNING:llama_index.response_synthesizers.refine:Validation error on structured response: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 202, in _give_response_single
    program(
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 68, in __call__
    return StructuredRefineResponse(answer=answer, query_satisfied=True)
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Validation error on structured response: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 202, in _give_response_single
    program(
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 68, in __call__
    return StructuredRefineResponse(answer=answer, query_satisfied=True)
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
WARNING:llama_index.response_synthesizers.refine:Validation error on structured response: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 284, in _refine_response_single
    program(
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 68, in __call__
    return StructuredRefineResponse(answer=answer, query_satisfied=True)
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Validation error on structured response: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 284, in _refine_response_single
    program(
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 68, in __call__
    return StructuredRefineResponse(answer=answer, query_satisfied=True)
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
WARNING:llama_index.response_synthesizers.refine:Validation error on structured response: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 284, in _refine_response_single
    program(
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 68, in __call__
    return StructuredRefineResponse(answer=answer, query_satisfied=True)
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Validation error on structured response: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 284, in _refine_response_single
    program(
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 68, in __call__
    return StructuredRefineResponse(answer=answer, query_satisfied=True)
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
WARNING:llama_index.response_synthesizers.refine:Validation error on structured response: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 284, in _refine_response_single
    program(
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 68, in __call__
    return StructuredRefineResponse(answer=answer, query_satisfied=True)
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Validation error on structured response: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 284, in _refine_response_single
    program(
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 68, in __call__
    return StructuredRefineResponse(answer=answer, query_satisfied=True)
  File "/home/ubuntu/anaconda3/envs/rag/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StructuredRefineResponse
answer
  none is not an allowed value (type=type_error.none.not_allowed)
```

any idea what might be going wrong?

**Comment by logan-markewich** [comment]
@jayavanth since you didn't implement complete or stream_complete, if any method calls those, it will return nothing

My advice is to implement those methods. You can see some examples of other classes that implement complete() by calling chat() and returning the expected output type, its not too bad :) 

https://github.com/run-llama/llama_index/blob/60b75cb014bccf60a153d5dc5295a91c7cdcd9f6/llama_index/llms/mistral.py#L201
