### ISSUE TITLE
[Bug]: Optional dependency on `llama-index-llms-openai` causes import errors

### ISSUE THREAD

**Issue by alex-feel** [run-llama/llama_index#10643]
### Bug Description

I've encountered an issue with the `llama-index-postprocessor-rankgpt-rerank` package that seems to stem from its handling of dependencies, specifically `llama-index-llms-openai`. Despite not using any `OpenAI` related functionality directly in my code, the mere instantiation of `RankGPTRerank` causes a `ModuleNotFoundError` unless `llama-index-llms-openai` is installed. This behaviour suggests an unconditional import of `OpenAI` within the `RankGPTRerank` class, which leads to a hard dependency on the `llama-index-llms-openai` package.

### Version

0.10.1

### Steps to Reproduce

1. **Environment Setup**: Ensure that `llama-index-core`, `llama-index-postprocessor-rankgpt-rerank`, and other related `llama-index` packages are installed, except for `llama-index-llms-openai`.

2. **Code Sample**: Use the following sample code snippet, which attempts to instantiate `RankGPTRerank` without directly requiring `OpenAI` functionalities.

<details>
<summary>Details</summary>

```python
import os
from typing import List

import nest_asyncio
from dotenv import load_dotenv
from google.oauth2 import service_account  # noqa
from llama_index.core.indices import VectorStoreIndex
from llama_index.core.schema import Node
from llama_index.core.schema import QueryBundle
from llama_index.llms.gemini import Gemini
from llama_index.postprocessor.rankgpt_rerank import RankGPTRerank
from llama_index.response_synthesizers.google import set_google_config
from llama_index.vector_stores.google import GoogleVectorStore

load_dotenv()

nest_asyncio.apply()

# Define settings
llm = Gemini(api_key=os.getenv('GEMINI_API_KEY'))
embed_model = llm

credentials = service_account.Credentials.from_service_account_file(
    'service_account_key.json',
    scopes=[
        'https://www.googleapis.com/auth/generative-language.retriever',
    ],
)
set_google_config(auth_credentials=credentials)

corpus_id = os.getenv('CORPUS_ID')

# Set up the Google Vector Store
store = GoogleVectorStore.from_corpus(
    corpus_id=corpus_id,
)

index = VectorStoreIndex.from_vector_store(
    vector_store=store,  # noqa
    embed_model=embed_model,
    chunk_size=256,
)

retriever = index.as_retriever(
    chunk_size=256,
    similarity_top_k=40,
)


def get_retrieved_nodes(query_str: str, retriever_to_use, reranker_top_n: int = 3,
                              with_reranker: bool = True) -> List[Node]:
    query_bundle = QueryBundle(query_str)
    # Configure retriever
    retrieved_nodes = retriever_to_use.retrieve(query_bundle)

    if with_reranker:
        # Configure reranker
        reranker = RankGPTRerank(
            llm=Gemini(
                api_key=os.getenv('GEMINI_API_KEY'),
                temperature=0.0,
            ),
            top_n=reranker_top_n,
            verbose=True,
        )
        retrieved_nodes = reranker.postprocess_nodes(
            retrieved_nodes, query_bundle)

    return retrieved_nodes


retrieved_nodes = get_retrieved_nodes(
    query_str='What is LlamaIndex?',
    retriever_to_use=retriever,
    reranker_top_n=3,
    with_reranker=True,
)
```

</details> 

3. **Execution**: Run the script. Without `llama-index-llms-openai` installed, the execution should fail with a `ModuleNotFoundError`.

4. **Expected Behavior**: The library should either handle the absence of `llama-index-llms-openai` gracefully when an alternative LLM is provided or document the necessity of its presence.

5. **Actual Behavior**: The script raises a `ModuleNotFoundError` indicating that `llama_index.llms.openai` module cannot be found, despite not using any OpenAI-specific functionality.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\User\Projects\project\temp.py", line 17, in <module>
    from llama_index.postprocessor.rankgpt_rerank import RankGPTRerank
  File "C:\Users\User\Projects\project\venv\lib\site-packages\llama_index\postprocessor\rankgpt_rerank\__init__.py", line 1, in <module>
    from llama_index.postprocessor.rankgpt_rerank.base import RankGPTRerank
  File "C:\Users\User\Projects\project\venv\lib\site-packages\llama_index\postprocessor\rankgpt_rerank\base.py", line 12, in <module>
    from llama_index.llms.openai import OpenAI
ModuleNotFoundError: No module named 'llama_index.llms.openai'

Process finished with exit code 1
```

**Comment by alex-feel** [comment]
#### Suggested Solutions:

I understand the utility of providing a default LLM for ease of use, but it might be beneficial for the library's flexibility and usability to adopt one of the following approaches:

1. **Lazy Importing**: Delay the import of `OpenAI` until it's explicitly needed. This could prevent the error from occurring in scenarios where `OpenAI` is not used.

2. **Conditional Importing**: Implement a mechanism to conditionally import `OpenAI` based on the runtime configuration or through explicit user action, ensuring that the import only occurs if `OpenAI` functionality is required.

3. **Dependency Injection**: Allow users to inject their preferred LLM instance (e.g., `Gemini`) at runtime, avoiding the need for a default import altogether.

4. **Documentation Update**: If maintaining the current implementation is preferable, it may be helpful to explicitly document this dependency requirement to guide users in setting up their environment correctly.

Thank you for considering this issue.
