### ISSUE TITLE
[Bug]: AttributeError: module 'html' has no attribute 'entities'

### ISSUE THREAD

**Issue by gallupliu** [run-llama/llama_index#10741]
### Bug Description

Traceback (most recent call last):
  File "/mnt/workspace/hetong/hetong_v3.py", line 13, in <module>
    from llama_index.embeddings.huggingface import HuggingFaceEmbedding
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/embeddings/huggingface/__init__.py", line 1, in <module>
    from llama_index.embeddings.huggingface.base import (
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/embeddings/huggingface/base.py", line 11, in <module>
    from llama_index.core.base.embeddings.base import (
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/__init__.py", line 8, in <module>
    from llama_index.core.base.response.schema import Response
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/base/response/schema.py", line 7, in <module>
    from llama_index.core.schema import NodeWithScore
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/schema.py", line 14, in <module>
    from llama_index.core.utils import SAMPLE_TEXT, truncate_text
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/utils.py", line 89, in <module>
    globals_helper = GlobalsHelper()
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/utils.py", line 45, in __init__
    import nltk
  File "/home/pai/envs/dev/lib/python3.10/site-packages/nltk/__init__.py", line 135, in <module>
    from nltk.featstruct import *
  File "/home/pai/envs/dev/lib/python3.10/site-packages/nltk/featstruct.py", line 97, in <module>
    from nltk.sem.logic import (
  File "/home/pai/envs/dev/lib/python3.10/site-packages/nltk/sem/__init__.py", line 67, in <module>
    from nltk.sem.relextract import clause, extract_rels, rtuple
  File "/home/pai/envs/dev/lib/python3.10/site-packages/nltk/sem/relextract.py", line 104, in <module>
    def descape_entity(m, defs=html.entities.entitydefs):
AttributeError: module 'html' has no attribute 'entities'

### Version

0.9.43

### Steps to Reproduce

Traceback (most recent call last):
  File "/mnt/workspace/hetong/hetong_v3.py", line 13, in <module>
    from llama_index.embeddings.huggingface import HuggingFaceEmbedding
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/embeddings/huggingface/__init__.py", line 1, in <module>
    from llama_index.embeddings.huggingface.base import (
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/embeddings/huggingface/base.py", line 11, in <module>
    from llama_index.core.base.embeddings.base import (
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/__init__.py", line 8, in <module>
    from llama_index.core.base.response.schema import Response
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/base/response/schema.py", line 7, in <module>
    from llama_index.core.schema import NodeWithScore
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/schema.py", line 14, in <module>
    from llama_index.core.utils import SAMPLE_TEXT, truncate_text
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/utils.py", line 89, in <module>
    globals_helper = GlobalsHelper()
  File "/home/pai/envs/dev/lib/python3.10/site-packages/llama_index/core/utils.py", line 45, in __init__
    import nltk
  File "/home/pai/envs/dev/lib/python3.10/site-packages/nltk/__init__.py", line 135, in <module>
    from nltk.featstruct import *
  File "/home/pai/envs/dev/lib/python3.10/site-packages/nltk/featstruct.py", line 97, in <module>
    from nltk.sem.logic import (
  File "/home/pai/envs/dev/lib/python3.10/site-packages/nltk/sem/__init__.py", line 67, in <module>
    from nltk.sem.relextract import clause, extract_rels, rtuple
  File "/home/pai/envs/dev/lib/python3.10/site-packages/nltk/sem/relextract.py", line 104, in <module>
    def descape_entity(m, defs=html.entities.entitydefs):
AttributeError: module 'html' has no attribute 'entities'

**Comment by gallupliu** [comment]
code:
`from llama_index.embeddings.huggingface import HuggingFaceEmbedding

# loads BAAI/bge-small-en-v1.5
embed_model = HuggingFaceEmbedding(model_name="./maidalun1020/bce-embedding-base_v1")
embeddings = embed_model.get_text_embedding("Hello World!")
print(len(embeddings))
print(embeddings[:5])
`
nltk :3.8.1
python:3.10
