### ISSUE TITLE
[Bug]: ValueError: "RetryAgentWorker" object has no field "_router_query_engine"

### ISSUE THREAD

**Issue by fsuarezj** [run-llama/llama_index#10921]
### Bug Description

Following the steps from https://docs.llamaindex.ai/en/stable/examples/agent/custom_agent.html I get the following error when executing with `python customAgent.py`

It looks like a problem related to pydantic, but when I remove the underscore from `_router_query_engine` changing the variable to `router_query_engine` I get another error:

```
Traceback (most recent call last):
  File "/home/ferda/Documents/dev/AI/LLM/llamaIndexAgentLearning/llamaindexagentlearning/customAgent.py", line 243, in <module>
    agent_worker = RetryAgentWorker.from_tools(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ferda/Documents/dev/venvs/llamaIndexAgentLearning/lib/python3.11/site-packages/llama_index/core/agent/custom/simple.py", line 113, in from_tools
    return cls(
           ^^^^
  File "/home/ferda/Documents/dev/AI/LLM/llamaIndexAgentLearning/llamaindexagentlearning/customAgent.py", line 79, in __init__
    self.router_query_engine = RouterQueryEngine(
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ferda/Documents/dev/venvs/llamaIndexAgentLearning/lib/python3.11/site-packages/pydantic/v1/main.py", line 405, in __setattr__
    self.__fields_set__.add(name)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'RetryAgentWorker' object has no attribute '__fields_set__'. Did you mean: '__fields__'?
```

Here my pyproject.toml:

```
[tool.poetry.dependencies]
python = ">=3.11,<3.12"
llama-index = "^0.10.5"
llama-index-readers-wikipedia = "^0.1.2"
llama-index-llms-openai = "^0.1.2"
wikipedia = "^1.4.0"
pydantic = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Version

0.10.5

### Steps to Reproduce

Copying the code from https://docs.llamaindex.ai/en/stable/examples/agent/custom_agent.html

Executing the code with `python customAgent.py`

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/ferda/Documents/dev/AI/LLM/llamaIndexAgentLearning/llamaindexagentlearning/customAgent.py", line 243, in <module>
    agent_worker = RetryAgentWorker.from_tools(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ferda/Documents/dev/venvs/llamaIndexAgentLearning/lib/python3.11/site-packages/llama_index/core/agent/custom/simple.py", line 113, in from_tools
    return cls(
           ^^^^
  File "/home/ferda/Documents/dev/AI/LLM/llamaIndexAgentLearning/llamaindexagentlearning/customAgent.py", line 79, in __init__
    self._router_query_engine = RouterQueryEngine(
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ferda/Documents/dev/venvs/llamaIndexAgentLearning/lib/python3.11/site-packages/pydantic/v1/main.py", line 357, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "RetryAgentWorker" object has no field "_router_query_engine"
```

**Comment by logan-markewich** [comment]
This is a pretty classic pydantic error 

Try switching `from pydantic import ..` to `from llama_index.core.bridge.pydantic import`

The reason is, under the hood, we still use the v1 compatibility imports

**Comment by fsuarezj** [comment]
Thanks @logan-markewich , but errors continue to be the same with and without underscore... :/ Any ideas on how to solve it?

**Comment by fsuarezj** [comment]
Thanks @logan-markewich , it worked!!! :) Not completely sure on where to change the docs page, but I'll try to find it and do a pull request :)
