### ISSUE TITLE
[Bug]: TypeError: GithubClient.get_branch() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by aaronjolson** [run-llama/llama_index#10952]
### Bug Description

Getting this error
```
Loading llama_index repository by run-llama
Traceback (most recent call last):
  File "C:\Users\aaols\PycharmProjects\experiments\llamaindex_activeloop_vectorize_data_from_github.py", line 123, in <module>
    main()
  File "C:\Users\aaols\PycharmProjects\experiments\llamaindex_activeloop_vectorize_data_from_github.py", line 79, in main
    docs = loader.load_data(branch="main")
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\llama_index\readers\github\repository\base.py", line 295, in load_data
    return self._load_data_from_branch(branch)
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\llama_index\readers\github\repository\base.py", line 256, in _load_data_from_branch
    self._github_client.get_branch(
TypeError: GithubClient.get_branch() got an unexpected keyword argument 'timeout'
```

These are my imports
```
import os
import textwrap
from dotenv import load_dotenv
from llama_index.core import download_loader
from llama_index.readers.github import GithubRepositoryReader, GithubClient
from llama_index.core import VectorStoreIndex
from llama_index.vector_stores.deeplake import DeepLakeVectorStore
from llama_index.core.storage.storage_context import StorageContext
import re
```
Trying to use `docs = loader.load_data(branch="main")` where loader is
`loader = GithubRepositoryReader(*)`

it appears to be blowing up on llama_index.readers.github.repository -> base.py -> line 256

```
   def _load_data_from_branch(self, branch: str) -> List[Document]:
        """
        Load data from a branch.

        Loads github repository data from a specific branch.

        :param `branch`: branch name

        :return: list of documents
        """
        branch_data: GitBranchResponseModel = self._loop.run_until_complete(
            self._github_client.get_branch(
                self._owner, self._repo, branch, timeout=self._timeout
            )
        )
```

these are my llama deps
```
llama-index==0.10.6
llama-index-agent-openai==0.1.1
llama-index-core==0.10.6.post1
llama-index-embeddings-openai==0.1.1
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.2
llama-index-multi-modal-llms-openai==0.1.1
llama-index-program-openai==0.1.2
llama-index-question-gen-openai==0.1.1
llama-index-readers-file==0.1.3
llama-index-readers-github==0.1.3
llama-index-vector-stores-deeplake==0.1.1
llamaindex-py-client==0.1.13
```

### Version

0.10.6

### Steps to Reproduce

try to load 
loader = GithubRepositoryReader(*)
loader.load_data(branch="main")

**Comment by logan-markewich** [comment]
Whoops. One sec.

**Comment by logan-markewich** [comment]
Ok, round two :) `llama-index-readers-github==0.1.3`
