### ISSUE TITLE
[Bug]: KeyError: 'content' from github_client.py", line 424, in get_blob

### ISSUE THREAD

**Issue by aaronjolson** [run-llama/llama_index#10955]
### Bug Description

Getting this error
'''
Traceback (most recent call last):
  File "C:\Users\aaols\PycharmProjects\experiments\llamaindex_activeloop_vectorize_data_from_github.py", line 123, in <module>
    main()
  File "C:\Users\aaols\PycharmProjects\experiments\llamaindex_activeloop_vectorize_data_from_github.py", line 79, in main
    docs = loader.load_data(branch="main")
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\llama_index\readers\github\repository\base.py", line 296, in load_data
    return self._load_data_from_branch(branch)
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\llama_index\readers\github\repository\base.py", line 267, in _load_data_from_branch
    return self._loop.run_until_complete(
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\llama_index\readers\github\repository\base.py", line 401, in _generate_documents
    async for blob_data, full_path in buffered_iterator:
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\llama_index\readers\github\repository\utils.py", line 75, in __anext__
    await self._fill_buffer()
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\llama_index\readers\github\repository\utils.py", line 149, in _fill_buffer
    results: List[GitBlobResponseModel] = await asyncio.gather(
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\llama_index\readers\github\repository\github_client.py", line 424, in get_blob
    return GitBlobResponseModel.from_json(
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\dataclasses_json\api.py", line 63, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\dataclasses_json\api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "C:\Users\aaols\PycharmProjects\experiments\venv\lib\site-packages\dataclasses_json\core.py", line 172, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'content'
'''
Attempting to load https://github.com/run-llama/llama_index into GithubRepositoryReader for vectorization

I am not exactly sure what the issue is here. Some edge case with the GitBlobResponseModel, it looks like it is expecting to get a 'content' key using  but it is not able to, \dataclasses_json\api.py", line 63, in from_json

I am running Python 3.10.6

These are my llama deps

```
llama-index==0.10.6
llama-index-agent-openai==0.1.1
llama-index-core==0.10.6.post1
llama-index-embeddings-openai==0.1.1
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.2
llama-index-multi-modal-llms-openai==0.1.1
llama-index-program-openai==0.1.2
llama-index-question-gen-openai==0.1.1
llama-index-readers-file==0.1.3
llama-index-readers-github==0.1.4
llama-index-vector-stores-deeplake==0.1.1
llamaindex-py-client==0.1.13
```

### Version

0.10.6

### Steps to Reproduce

loader = GithubRepositoryReader(*)  # where owner is run-llama and repo is llama-index 
loader.load_data(branch="main")

**Comment by logan-markewich** [comment]
Fixed in `llama-index-readers-github==0.1.5`

Well, "fixed" -- more like skipping the file if no content is found in the blob, so that it doesn't crash the entire loop :)
