### ISSUE TITLE
[Bug]: 'NodeWithScore' object has no attribute 'image_mimetype'

### ISSUE THREAD

**Issue by ZachHandley** [run-llama/llama_index#10995]
### Bug Description

I built a retrieval pipeline for images, I am trying to run a MultiModalVectorStoreIndex on a list of Nodes, but the nodes are ImageNodes, improperly converted to NodeWithScore (or the image_mimetype is supposed to be there?)

### Version

^0.10.7

### Steps to Reproduce

So I made this code to retrieve images from a vector database without querying but just retrieving them all and filtering into Clusters (I may need to change my `record_to_image_node` function but

Oh and just to add -- **it does have an image_mimetype, I have explicitly set it before inserting into the Qdrant Vector Store and have checked it's there**

```python
def record_to_image_node(self, record: Record) -> ImageNode:
        if record.payload is None:
            raise ValueError(
                "Record payload is None, cannot convert to ImageNode"
            )
        if not isinstance(record.payload, dict):
            raise TypeError("Record payload is not a dictionary")
        if not isinstance(record.vector, list) and record.vector.get("text-dense", None) is not None:  # type: ignore
            node_content = json.loads(record.payload.get("_node_content", "{}"))
            node = ImageNode(
                id_=record.id,
                embedding=record.vector.get("text-dense"),  # type: ignore
                metadata=node_content.get("metadata", {}),
                text=record.payload.get("text", ""),
                image=record.payload.get("image", None),
                image_path=record.payload.get("image_path", None),
                image_url=record.payload.get("image_url", None),
                image_mimetype=record.payload.get("image_mimetype", None),
            )
        else:
            node_content = json.loads(record.payload.get("_node_content", "{}"))
            node = ImageNode(
                id_=record.id,
                embedding=record.vector,
                metadata=node_content.get("metadata", {}),
                text=record.payload.get("text", ""),
                image=record.payload.get("image", None),
                image_path=record.payload.get("image_path", None),
                image_url=record.payload.get("image_url", None),
                image_mimetype=record.payload.get("image_mimetype", None),
            )
        return node

    def _text_to_image_retrieve(
        self,
        query_str: str,
    ) -> List[NodeWithScore]:
        """
        Retrieve images from the vector store based on a users ID, grouped by Cluster ID and organized by most relevanr
        to the least relevant to the user per cluster
        """
        if isinstance(self.vector_client, AsyncQdrantClient):
            raise ValueError("This method is not supported for async clients")

        image_records = self.qdrant_helper.get_nodes_paginated(
            vector_client=self.vector_client,
            collection_name=self.img_vector_store.collection_name,
            query_filter=Filter(
                must=[
                    FieldCondition(
                        key="user_id",
                        match=MatchText(
                            text=self.user_id,
                        ),
                    ),
                ],
            ),
            limit=100,
            get_all=True,
        )
        image_nodes = [
            self.record_to_image_node(record) for record in image_records
        ]
        # Now that we have the image nodes as ImageNode instead of Record, we need to get all the different clusters
        clusters: dict[str, list[ImageNode]] = {}
        images_retrieved: list[NodeWithScore] = []
        for image_node in image_nodes:
            cluster_id = image_node.metadata.get("cluster_id")
            if not cluster_id:
                continue
            if cluster_id not in clusters:
                clusters[cluster_id] = []
            clusters[cluster_id].append(image_node)
        # For now, we'll just return the top_k images in each cluster, maybe check similarity and pick the most different images?
        for cluster_id in clusters:
            if len(clusters[cluster_id]) > 1:
                index = MultiModalVectorStoreIndex(
                    nodes=clusters[cluster_id],
                    use_async=False,
                    embed_model=self.embedder._text_model,
                    image_embed_model=self.embedder._image_model,
                )
                engine = index.as_query_engine(
                    llm=self.vision_llm,
                )
                query = """\
                    These images are clustered because they are similar to each other. \
                    Please return the most relevant images per cluster based on the user's query. \n
                    """
                query += query_str
                query_embed = self.embedder.get_img_query_embedding(query)
                query_bundle = QueryBundle(
                    query_str=query,
                    embedding=query_embed,
                )
                response = engine.query(query_bundle)
                for result in response.source_nodes:
                    images_retrieved.append(result)
        return images_retrieved
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/zachhandley/Documents/GitHub/my-project/api/app/db/vector_stores_temp.py", line 295, in <module>
    asyncio.run(main())
  File "/Users/zachhandley/Documents/GitHub/my-project/api/.venv/lib/python3.11/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/.venv/lib/python3.11/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/app/db/vector_stores_temp.py", line 238, in main
    user_images = await vector_store_temp.get_user_images()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/app/db/vector_stores_temp.py", line 191, in get_user_images
    return await self._image_retriever.aretrieve(query_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/app/ai/zimage_retriever.py", line 244, in aretrieve
    return await self._atext_to_image_retrieve(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/app/ai/zimage_retriever.py", line 233, in _atext_to_image_retrieve
    response = await engine.aquery(query_bundle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/.venv/lib/python3.11/site-packages/llama_index/core/base/base_query_engine.py", line 46, in aquery
    return await self._aquery(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/.venv/lib/python3.11/site-packages/llama_index/core/query_engine/multi_modal.py", line 232, in _aquery
    response = await self.asynthesize(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/.venv/lib/python3.11/site-packages/llama_index/core/query_engine/multi_modal.py", line 158, in asynthesize
    llm_response = await self._multi_modal_llm.acomplete(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/.venv/lib/python3.11/site-packages/llama_index/multi_modal_llms/openai/base.py", line 380, in acomplete
    return await self._acomplete(prompt, image_documents, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/.venv/lib/python3.11/site-packages/llama_index/multi_modal_llms/openai/base.py", line 362, in _acomplete
    message_dict = self._get_multi_modal_chat_messages(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zachhandley/Documents/GitHub/my-project/api/.venv/lib/python3.11/site-packages/llama_index/multi_modal_llms/openai/base.py", line 173, in _get_multi_modal_chat_messages
    generate_openai_multi_modal_chat_message(
  File "/Users/zachhandley/Documents/GitHub/my-project/api/.venv/lib/python3.11/site-packages/llama_index/multi_modal_llms/openai/utils.py", line 41, in generate_openai_multi_modal_chat_message
    mimetype = image_document.image_mimetype or "image/jpeg"
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NodeWithScore' object has no attribute 'image_mimetype'
```

**Comment by hatianzhang** [comment]
i think you probably need to set image_mimetype for image node when you do indexing.
When you retrieve nodes, you can check the type of the node. If it is image node, you can fetch `image_mimetype` for such node. Just checking by `if isinstance(document, ImageDocument):`

**Comment by hatianzhang** [comment]
@ZachHandley sorry given limited code and info, I may spend some time understanding what is going on

From error log, it seems that you are passing `node_with_score` objects to `complete` function from MM LLM. I try to understand how this step happened. Could you give us more context?

**Comment by ZachHandley** [comment]
@hatianzhang I pull nodes from Qdrant Vector Database, those nodes are Records, so I convert them to Image Nodes, which is also in my code above. Then, I sort those image nodes based on cluster ID. Afterwards, I give them to the multi modal vector store index, the error occurs after I ask the index about each cluster. So basically, somewhere between when I create the query engine, and it queries, it converts my ImageNodes to a NodeWithScore and drops the image_mimetype is my theory.

That is the whole file. The only missing context is possibly 

```python
class ZQdrantHelper:
    def __init__(
        self,
    ):
        pass

    def get_nodes_paginated(
        self,
        vector_client: QdrantClient,
        collection_name: str,
        query_filter: Filter,
        limit: int = 100,
        get_all: bool = False,
    ) -> list[Record]:
        """
        Synchronously get the embeddings from the user paginated to manage request size.
        """
        nodes = []
        nodes_pulled: tuple[
            list[Record], PointId | None
        ] = vector_client.scroll(
            collection_name=collection_name,
            scroll_filter=query_filter,
            with_vectors=True,
            with_payload=True,
            limit=limit,
        )
        offset_id = nodes_pulled[1]
        nodes.extend(nodes_pulled[0])
        if get_all:
            while offset_id:
                nodes_pulled: tuple[
                    list[Record], PointId | None
                ] = vector_client.scroll(
                    collection_name=collection_name,
                    scroll_filter=query_filter,
                    with_vectors=True,
                    with_payload=True,
                    limit=limit,
                    offset=offset_id,
                )
                offset_id = nodes_pulled[1]
                nodes.extend(nodes_pulled[0])
        return nodes
```

So if you want to mirror it, just create a qdrant vector store, insert images, use this pagination function to get em all, and then try to create a MultiModalVectorStoreIndex from the nodes and query a group of them or all of them

**Comment by hatianzhang** [comment]
@ZachHandley sg thanks, will try to reproduce later

**Comment by ZachHandley** [comment]
@hatianzhang Does not fix it. I believe the issue is with the `asynthesize`, called from `_aquery` right [here](https://github.com/run-llama/llama_index/blob/1892c3d804e1bbf09daf8f49183f909f702e612f/llama-index-core/llama_index/core/query_engine/multi_modal.py#L217) -- the `nodes = await self.aretrieve` returns `NodeWithScore`, and the call to `asynthesize` takes a `NodeWithScore` object, which then calls 

```
def _get_image_and_text_nodes(
    nodes: List[NodeWithScore],
) -> Tuple[List[NodeWithScore], List[NodeWithScore]]:
    image_nodes = []
    text_nodes = []
    for res_node in nodes:
        if isinstance(res_node.node, ImageNode):
            image_nodes.append(res_node)
        else:
            text_nodes.append(res_node)
    return image_nodes, text_nodes
    ```
    
    so maybe I need to override the way that Llama Index does it to preserve ImageNode's?

**Comment by hatianzhang** [comment]
@ZachHandley here is the fix https://github.com/run-llama/llama_index/pull/11064/files
Hope it will fix your issue

**Comment by ZachHandley** [comment]
Thank you! @hatianzhang
