### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.readers.schema'

### ISSUE THREAD

**Issue by qilong-zhang** [run-llama/llama_index#11011]
### Bug Description

This is my package version
```
llama-hub                                0.0.79.post1
llama-index                              0.10.7
llama-index-agent-openai                 0.1.1
llama-index-core                         0.10.6.post1
llama-index-embeddings-openai            0.1.1
llama-index-legacy                       0.9.48
llama-index-llms-openai                  0.1.2
llama-index-multi-modal-llms-openai      0.1.1
llama-index-program-openai               0.1.2
llama-index-question-gen-openai          0.1.1
llama-index-readers-file                 0.1.3
llamaindex-py-client                     0.1.13
exa-py                                   1.0.8
```

If I want to import ExaToolSpec,
```python
from llama_hub.tools.exa.base import ExaToolSpec 
```
 it will report a bug:
```
  File "/root/RAG/test.py", line 4, in <module>
    from llama_hub.tools.exa.base import ExaToolSpec 
  File "/root/mambaforge3/envs/rag/lib/python3.9/site-packages/llama_hub/tools/exa/__init__.py", line 2, in <module>
    from llama_hub.tools.exa.base import (
  File "/root/mambaforge3/envs/rag/lib/python3.9/site-packages/llama_hub/tools/exa/base.py", line 6, in <module>
    from llama_index.readers.schema.base import Document
ModuleNotFoundError: No module named 'llama_index.readers.schema'
```

### Version

0.10.7

### Steps to Reproduce

from llama_hub.tools.exa.base import ExaToolSpec 

### The above line will report this error
```
  File "/root/RAG/test.py", line 4, in <module>
    from llama_hub.tools.exa.base import ExaToolSpec 
  File "/root/mambaforge3/envs/rag/lib/python3.9/site-packages/llama_hub/tools/exa/__init__.py", line 2, in <module>
    from llama_hub.tools.exa.base import (
  File "/root/mambaforge3/envs/rag/lib/python3.9/site-packages/llama_hub/tools/exa/base.py", line 6, in <module>
    from llama_index.readers.schema.base import Document
ModuleNotFoundError: No module named 'llama_index.readers.schema'
```

**Comment by qilong-zhang** [comment]
@dosu-bot This works for me. But after I changed it, I had another problem
```
Traceback (most recent call last):
  File "/root/RAG/test.py", line 4, in <module>
    from llama_hub.tools.exa.base import ExaToolSpec
  File "/root/mambaforge3/envs/rag/lib/python3.9/site-packages/llama_hub/tools/exa/__init__.py", line 2, in <module>
    from llama_hub.tools.exa.base import (
  File "/root/mambaforge3/envs/rag/lib/python3.9/site-packages/llama_hub/tools/exa/base.py", line 7, in <module>
    from llama_index.tools.tool_spec.base import BaseToolSpec
ModuleNotFoundError: No module named 'llama_index.tools'
```

**Comment by qilong-zhang** [comment]
@dosubot I still have trouble. When I run 
```python
import llama_index.tools
```
It reports
```
Traceback (most recent call last):
  File "/root/RAG/2_LlamaIndex + Metaphor.py", line 3, in <module>
    import llama_index.tools
ModuleNotFoundError: No module named 'llama_index.tools'
```

But if I run 
```python
import llama_index
```
It is ok.

**Comment by logan-markewich** [comment]
@qilong-zhang try starting with a fresh venv and see if that helps

**Comment by logan-markewich** [comment]
In a new terminal

```
pip uninstall llama-index  # just in case it was installed globally 
python -m venv venv
source venv/bin/activate
pip install llama-index
```

**Comment by qilong-zhang** [comment]
@logan-markewich Thanks for your reply.
