### ISSUE TITLE
[Bug]: ModuleNotFoundError for `llama_index.core.llms.base` when importing `Gemini`

### ISSUE THREAD

**Issue by alex-feel** [run-llama/llama_index#11081]
### Bug Description

I've encountered a ModuleNotFoundError while working with the llama_index package, specifically when trying to import the Gemini class. Here's the error message I received:

```bash
Traceback (most recent call last):
  File "C:\Users\User\Projects\project\query_index.py", line 26, in <module>
    from llama_index.llms.gemini import Gemini
...
ModuleNotFoundError: No module named 'llama_index.core.llms.base'
```

This error occurs when executing the following import statement:

```bash
from llama_index.llms.gemini import Gemini
```

Upon inspecting the `utils.py` file within the `llama_index.llms.gemini` module, I noticed it attempts to import `ChatMessage`, `ChatResponse`, and `CompletionResponse` from `llama_index.core.llms.base`, which seems to lead to the issue:

```bash
from llama_index.core.llms.base import (
    ChatMessage,
    ChatResponse,
    CompletionResponse,
)
```

### Version

0.10.10

### Steps to Reproduce

- Add the import statement to your script:

```python
from llama_index.llms.gemini import Gemini
```

- Attempt to run your script.
- Observe the `ModuleNotFoundError` indicating that the `llama_index.core.llms.base` module cannot be found.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\User\Projects\project\query_index.py", line 26, in <module>
    from llama_index.llms.gemini import Gemini
  File "C:\Users\User\Projects\project\venv\lib\site-packages\llama_index\llms\gemini\__init__.py", line 1, in <module>
    from llama_index.llms.gemini.base import Gemini
  File "C:\Users\User\Projects\project\venv\lib\site-packages\llama_index\llms\gemini\base.py", line 22, in <module>
    from llama_index.llms.gemini.utils import (
  File "C:\Users\User\Projects\project\venv\lib\site-packages\llama_index\llms\gemini\utils.py", line 7, in <module>
    from llama_index.core.llms.base import (
ModuleNotFoundError: No module named 'llama_index.core.llms.base'
```

**Comment by alex-feel** [comment]
After further investigation, I discovered that the problem was due to a version mismatch. Installing the specific version `llama-index-llms-gemini==0.1.2` resolved the `ModuleNotFoundError` issue I was experiencing. My apologies for any confusion—there are quite a few modules to keep track of! Thank you for your patience.
