### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'tree_sitter'

### ISSUE THREAD

**Issue by aaronjolson** [run-llama/llama_index#11273]
### Bug Description

I am trying to test passing nodes that custom split code using the CodeSplitter class.
I am getting this error
```
(venv) PS C:\Users\aaols\PycharmProjects\ai-experiments> python code_indexer.py
Traceback (most recent call last):
  File "C:\Users\aaols\PycharmProjects\ai-experiments\code_indexer.py", line 125, in <module>
    main()
  File "C:\Users\aaols\PycharmProjects\ai-experiments\code_indexer.py", line 80, in main
    CodeSplitter(
  File "C:\Users\aaols\PycharmProjects\ai-experiments\venv\lib\site-packages\llama_index\core\node_parser\text\code.py", line 57, in __init__
    from tree_sitter import Parser  # pants: no-infer-dep
ModuleNotFoundError: No module named 'tree_sitter'
```

My imports
```
import os
import textwrap
from llama_index.core import SimpleDirectoryReader
from llama_index.core.node_parser import CodeSplitter
from dotenv import load_dotenv
from llama_index.core import VectorStoreIndex
from llama_index.vector_stores.deeplake import DeepLakeVectorStore
from llama_index.core.storage.storage_context import StorageContext
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.core.extractors import TitleExtractor
from llama_index.core.ingestion import IngestionPipeline, IngestionCache
```

my llama deps
```
llama-index==0.10.11
llama-index-agent-openai==0.1.4
llama-index-cli==0.1.3
llama-index-core==0.10.11.post1
llama-index-embeddings-openai==0.1.5
llama-index-indices-managed-llama-cloud==0.1.2
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.5
llama-index-multi-modal-llms-openai==0.1.3
llama-index-program-openai==0.1.3
llama-index-question-gen-openai==0.1.2
llama-index-readers-file==0.1.4
llama-index-readers-github==0.1.6
llama-index-readers-llama-parse==0.1.2
llama-index-vector-stores-chroma==0.1.2
llama-index-vector-stores-deeplake==0.1.2
llama-parse==0.3.4
llamaindex-py-client==0.1.13
```

### Version

0.10.11

### Steps to Reproduce
```
# create the pipeline with transformations
    pipeline = IngestionPipeline(
        transformations=[
            CodeSplitter(
                language="python",
                max_chars=max_chars,
                chunk_lines=chunk_lines,
                chunk_lines_overlap=chunk_overlap),
            TitleExtractor(),
            OpenAIEmbedding(),
        ]
    )
```

**Comment by logan-markewich** [comment]
does `pip install  tree-sitter` fix the issue?

**Comment by aaronjolson** [comment]
@logan-markewich - yes, I ended up needing to pip install tree-sitter and tree-sitter-languages
Should those be added to the project dependencies?

**Comment by mcavdar** [comment]
@logan-markewich 

I believe we can add the following to the pyproject.toml. 

```
[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
tree-sitter = "*"
tree-sitter-languages = "*"
```

Let me know if it’s worth creating a PR for this.

**Comment by slyapustin** [comment]
@mcavdar It would be nice if you can fix that!
