### ISSUE TITLE
[Bug]: Error with MarkdownElementNodeParser + Gemini (Vertex AI): Gemini model don't support system messages

### ISSUE THREAD

**Issue by barun-saha** [run-llama/llama_index#11323]
### Bug Description

Hello,

I'm using `llama_parse` to extract content from PDF files. Next, I'm trying to parse them using `MarkdownElementNodeParser`. The LLM used is Gemini Pro (via Vertex AI).

This works well when I use `llama_parse` to extract the content in text format. However, when I extract them in Markdown format, it throws an error: `ValueError: Gemini model don't support system messages`.

Below, an MWE is provided. It looks like the row separator line (`|---|---|`) creates problem. Strangely, on removing that line, there is no complaint.

I have the following packages installed, among others:

```
llama-index==0.10.12
llama-index-core==0.10.12
llama-index-llms-langchain==0.1.3
llama-index-embeddings-langchain==0.1.2
llama-index-vector-stores-chroma==0.1.4
llama-index-llms-vertex==0.1.2
```

### Version

0.10.12

### Steps to Reproduce

```python
from llama_index.core import Document
from llama_index.core.node_parser import MarkdownElementNodeParser
from llama_index.llms.vertex import Vertex


documents = [
    Document(
        text='''
|Content|Page Number|
|---|---|
|Introduction|27|
'''
    )
]
llm = Vertex(model='gemini-pro')
node_parser = MarkdownElementNodeParser(
    llm=llm,
    show_progress=True
)
nodes = node_parser.get_nodes_from_documents(documents, show_progress=True)
```

### Relevant Logs/Tracbacks

```shell
Parsing nodes:   0%|          | 0/1 [00:00<?, ?it/s]Embeddings have been explicitly disabled. Using MockEmbedding.

1it [00:00, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]C:\project_path\venv\lib\site-packages\llama_index\core\program\utils.py:58: UserWarning: Failed to use `OpenAIPydanticProgram`. Please ensure that is installed by running `pip install llama-index-program-openai`.
  warnings.warn(
Parsing nodes:   0%|          | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\project_path\md_parser_gemini_test.py", line 22, in <module>
    nodes = node_parser.get_nodes_from_documents(documents, show_progress=True)
  File "C:\project_path\venv\lib\site-packages\llama_index\core\node_parser\interface.py", line 75, in get_nodes_from_documents
    nodes = self._parse_nodes(documents, show_progress=show_progress, **kwargs)
  File "C:\project_path\venv\lib\site-packages\llama_index\core\node_parser\relational\base_element.py", line 113, in _parse_nodes
    nodes = self.get_nodes_from_node(node)
  File "C:\project_path\venv\lib\site-packages\llama_index\core\node_parser\relational\markdown_element.py", line 57, in get_nodes_from_node
    self.extract_table_summaries(table_elements)
  File "C:\project_path\venv\lib\site-packages\llama_index\core\node_parser\relational\base_element.py", line 191, in extract_table_summaries
    summary_outputs = asyncio.run(
  File "C:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\project_path\venv\lib\site-packages\llama_index\core\async_utils.py", line 110, in run_jobs
    return await asyncio_mod.gather(*pool_jobs)
  File "C:\project_path\venv\lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\project_path\venv\lib\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Python\lib\asyncio\tasks.py", line 615, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\project_path\venv\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "C:\project_path\venv\lib\site-packages\llama_index\core\async_utils.py", line 106, in worker
    return await job
  File "C:\project_path\venv\lib\site-packages\llama_index\core\node_parser\relational\base_element.py", line 178, in _get_table_output
    response = await query_engine.aquery(summary_query_str)
  File "C:\project_path\venv\lib\site-packages\llama_index\core\base\base_query_engine.py", line 46, in aquery
    return await self._aquery(str_or_query_bundle)
  File "C:\project_path\venv\lib\site-packages\llama_index\core\query_engine\retriever_query_engine.py", line 203, in _aquery
    response = await self._response_synthesizer.asynthesize(
  File "C:\project_path\venv\lib\site-packages\llama_index\core\response_synthesizers\base.py", line 213, in asynthesize
    response_str = await self.aget_response(
  File "C:\project_path\venv\lib\site-packages\llama_index\core\response_synthesizers\compact_and_refine.py", line 19, in aget_response
    return await super().aget_response(
  File "C:\project_path\venv\lib\site-packages\llama_index\core\response_synthesizers\refine.py", line 335, in aget_response
    response = await self._agive_response_single(
  File "C:\project_path\venv\lib\site-packages\llama_index\core\response_synthesizers\refine.py", line 436, in _agive_response_single
    structured_response = await program.acall(
  File "C:\project_path\venv\lib\site-packages\llama_index\core\response_synthesizers\refine.py", line 76, in acall
    answer = await self._llm.astructured_predict(
  File "C:\project_path\venv\lib\site-packages\llama_index\core\llms\llm.py", line 235, in astructured_predict
    return await program.acall(**prompt_args)
  File "C:\project_path\venv\lib\site-packages\llama_index\core\program\llm_program.py", line 120, in acall
    response = await self._llm.achat(messages, **llm_kwargs)
  File "C:\project_path\venv\lib\site-packages\llama_index\core\llms\callbacks.py", line 50, in wrapped_async_llm_chat
    f_return_val = await f(_self, messages, **kwargs)
  File "C:\project_path\venv\lib\site-packages\llama_index\llms\vertex\base.py", line 289, in achat
    chat_history = _parse_chat_history(messages[:-1], self._is_gemini)
  File "C:\project_path\venv\lib\site-packages\llama_index\llms\vertex\utils.py", line 172, in _parse_chat_history
    raise ValueError("Gemini model don't support system messages")
ValueError: Gemini model don't support system messages
  0%|          | 0/1 [00:00<?, ?it/s]

Process finished with exit code 1
```

**Comment by logan-markewich** [comment]
Thats... unfortunate lol

lets see if this can be fixed
