### ISSUE TITLE
[Bug]: ImportError: `llama-index-readers-file` package not found

### ISSUE THREAD

**Issue by mphipps2** [run-llama/llama_index#11336]
### Bug Description

I'm calling: 
image_documents = SimpleDirectoryReader(doc_dir).load_data()

But I get a ModuleNotFoundError for  llama_index.readers.file.base (inside  llama_index/core/readers/file/base.py) gets called in the readers directory and the :

> `=

def _try_loading_included_file_formats() -> Dict[str, Type[BaseReader]]:
    try:
        from llama_index.readers.file.base import (
            DocxReader,
            EpubReader,
            HWPReader,
            ImageReader,
            IPYNBReader,
            MarkdownReader,
            MboxReader,
            PandasCSVReader,
            PDFReader,
            PptxReader,
            VideoAudioReader,
        )  # pants: no-infer-dep
    except ImportError:
        raise ImportError("`llama-index-readers-file` package not found")

> `=

### Version

llama-index: 0.10.12, llama-index-readers-file: 0.1.5

### Steps to Reproduce

Call image_documents = SimpleDirectoryReader(doc_dir).load_data() using the newest release

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/llama_index/core/readers/file/base.py", line 21, in _try_loading_included_file_formats
    from llama_index.readers.file.base import (
ModuleNotFoundError: No module named 'llama_index.readers.file.base'
  File "/llama_index/core/readers/file/base.py", line 396, in load_data
    SimpleDirectoryReader.load_file(
  File "/llama_index/core/readers/file/base.py", line 303, in load_file
    default_file_reader_cls = SimpleDirectoryReader.supported_suffix_fn()
  File "/llama_index/core/readers/file/base.py", line 35, in _try_loading_included_file_formats
    raise ImportError("`llama-index-readers-file` package not found")
ImportError: `llama-index-readers-file` package not found
```

**Comment by mphipps2** [comment]
Hi Logan, thanks for the quick response. Starting the new virtual environment worked for me. Not sure where the conflict was, but either way, all good now and will close the ticket. Thanks again
