### ISSUE TITLE
[Bug]: index.as_chat_engine is throwing error openai.NotFoundError: Error code: 404

### ISSUE THREAD

**Issue by ramakrse** [run-llama/llama_index#11356]
### Bug Description

I am using version 0.10.6, using `Settings` as per [documentation](https://docs.llamaindex.ai/en/stable/examples/llm/azure_openai.html#use-your-llm) instead of `ServiceContext` with Azure OpenAI. it is working well for `index.as_query_engine`.

However, when I changed to chate engine, as below
```
chat_engine = index.as_chat_engine(chat_mode='best', system_prompt=system_prompt, verbose=True)
response = chat_engine.chat(prompt)
```

### Version

0.10.6

### Steps to Reproduce

follows the steps of this [documentation](https://docs.llamaindex.ai/en/stable/examples/customization/llms/AzureOpenAI.html) page
```
chat_engine = index.as_chat_engine(chat_mode='best', system_prompt=system_prompt, verbose=True)
prompt = 'What is most interesting about this essay'
response = chat_engine.chat(prompt)
```

### Relevant Logs/Tracbacks

```shell
2024-02-24 20:19:51.761 Uncaught app exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/localuser/Documents/AnacondaProjects/genAI2/azure_llm/maintenance_chat_assistance_V2.py", line 282, in <module>
    main(config)
  File "/Users/localuser/Documents/AnacondaProjects/genAI2/azure_llm/maintenance_chat_assistance_V2.py", line 252, in main
    response = chat_engine.chat(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 575, in chat
    chat_response = self._chat(
                    ^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 520, in _chat
    cur_step_output = self._run_step(
                      ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 372, in _run_step
    cur_step_output = self.agent_worker.run_step(step, task, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 572, in run_step
    return self._run_step(
           ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 447, in _run_step
    agent_chat_response = self._get_agent_response(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 321, in _get_agent_response
    chat_response: ChatResponse = self._llm.chat(**llm_chat_kwargs)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 93, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/llms/openai/base.py", line 237, in chat
    return chat_fn(messages, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/llms/openai/base.py", line 296, in _chat
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 663, in create
    return self._post(
           ^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by logan-markewich** [comment]
With azure openai, the minimum api version you need is 2023-07-01-preview

Microsoft has been quite slow to adapt to openais tools api

**Comment by ramakrse** [comment]
@logan-markewich  for your quick response.
I am using version `2023-12-01-preview`

**Comment by ramakrse** [comment]
@dosu-bot, I am using simple high level api `index.as_chat_engine` not agent with tools.

**Comment by logan-markewich** [comment]
@ramakrse are you using gpt-4? I've seen the base gpt-4 version throw this on azure, need to use a preview version of gpt-4 I think

**Comment by ramakrse** [comment]
@logan-markewich, I am using `gpt-35-turbo`. I found one mistake that while setting llm using AzureOpenAI, there is one parameter `engine` missed. I fixed that.. Now it throws he below error `ValueError: Tool with name functions not found`

```
File "/Users/localuser/Documents/AnacondaProjects/genAI2/azure_llm/maintenance_chat_assistance_V2.py", line 260, in main
    response = chat_engine.chat(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 575, in chat
    chat_response = self._chat(
                    ^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 520, in _chat
    cur_step_output = self._run_step(
                      ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 372, in _run_step
    cur_step_output = self.agent_worker.run_step(step, task, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 572, in run_step
    return self._run_step(
           ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 469, in _run_step
    self._call_function(
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 356, in _call_function
    EventPayload.TOOL: get_function_by_name(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 50, in get_function_by_name
    raise ValueError(f"Tool with name {name} not found")
ValueError: Tool with name functions not found
```

**Comment by ramakrse** [comment]
@dosu-bot, I tried with the [chat_engine_best.ipynb](https://github.com/run-llama/llama_index/blob/main/docs/examples/chat_engine/chat_engine_best.ipynb) example. 

I have setup the azure openai Settings as per [documentation](https://docs.llamaindex.ai/en/stable/examples/llm/azure_openai.html#use-your-llm). During the process, I have figured that llm, we need to use `engine`. After that, I get error 404 goes away. Now, new error `ValueError: Tool with name functions not found`

```
File "/Users/localuser/Documents/AnacondaProjects/genAI2/azure_llm/paul.py", line 104, in main
    response = chat_engine.chat("What are the first programs Paul Graham tried writing?")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 575, in chat
    chat_response = self._chat(
                    ^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 520, in _chat
    cur_step_output = self._run_step(
                      ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 372, in _run_step
    cur_step_output = self.agent_worker.run_step(step, task, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 572, in run_step
    return self._run_step(
           ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 469, in _run_step
    self._call_function(
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 356, in _call_function
    EventPayload.TOOL: get_function_by_name(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/genAI2/lib/python3.11/site-packages/llama_index/agent/openai/step.py", line 50, in get_function_by_name
    raise ValueError(f"Tool with name {name} not found")
```

**Comment by ramakrse** [comment]
Any work around available? If not give the steps of low-level APIs to set up the chat engine for Azure Openai using 0.10.6 instead of index.as_chat_engine high level API

**Comment by ramakrse** [comment]
@dosu-bot. high-level api  `index.as_chat_engine()` is failing, please give low-level API for chat for azure openai model using settings.

**Comment by ramakrse** [comment]
@dosu-bot. Why are you recommending AzureOpenAIMultiModal? It does not use index that I have... Please relook your response
