### ISSUE TITLE
[Bug]: Query Fusion Retriever with metadata filtering fails

### ISSUE THREAD

**Issue by rahulkrprajapati** [run-llama/llama_index#11391]
### Bug Description

I have a redis vector index store and a doc store and an upsatash vector store defined. When I define my retriever such that it filters the nodes by metadata it seems to fail.

### Version

0.10.1

### Steps to Reproduce

defining a base retriever with metadata filter enabled 

```python
base_retriever = self.base_index.as_retriever(
                    similarity_top_k=self.similarity_top_k,
                    filters=MetadataFilters(
                        filters=[
                            ExactMatchFilter(key="namespace", value=self.namespace)
                        ]
                    ),
                )
retriever = AutoMergingRetriever(
                    base_retriever, self.storage_context, verbose=verbose
                )
                
bm24_retriever = BM25Retriever.from_defaults(
                docstore=self.docstore, similarity_top_k=self.similarity_top_k
            )

fusion_retriever = QueryFusionRetriever(
                [retriever, bm24_retriever],
                similarity_top_k=self.similarity_top_k,
                num_queries=1,  # set this to 1 to disable query generation
                mode="reciprocal_rerank",
                use_async=True,
                verbose=verbose,
            )
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/rahulprajapati/VSCode/ProtoSearchBackend/DocCore/picore.py", line 363, in process_streamlit_fetch_query_results
    retrived_nodes = fusion_retriever.retrieve(query_bundle)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py", line 229, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/retrievers/fusion_retriever.py", line 188, in _retrieve
    results = self._run_nested_async_queries(queries)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/retrievers/fusion_retriever.py", line 146, in _run_nested_async_queries
    task_results = run_async_tasks(tasks)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 49, in run_async_tasks
    outputs: List[Any] = asyncio.run(_gather())
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 47, in _gather
    return await asyncio.gather(*tasks_to_execute)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py", line 249, in aretrieve
    nodes = await self._aretrieve(query_bundle)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py", line 273, in _aretrieve
    return self._retrieve(query_bundle)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/retrievers/auto_merging_retriever.py", line 171, in _retrieve
    initial_nodes = self._vector_retriever.retrieve(query_bundle)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py", line 229, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 94, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 170, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/Users/rahulprajapati/anaconda3/envs/supaBaseProto/lib/python3.10/site-packages/llama_index/vector_stores/upstash/base.py", line 122, in query
    raise ValueError("Metadata filtering not supported")
ValueError: Metadata filtering not supported
```

**Comment by MeshanKhosla** [comment]
Hi, this is because Metadata filtering is not supported in UpstashVector yet. It's on the [roadmap](https://upstash.com/docs/vector/overall/roadmap) and should be available within the next few weeks.

**Comment by rahulkrprajapati** [comment]
@MeshanKhosla thought it might be so. They also seem to releasing a feature for adding index names or namespaces in a few days.
