### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'dataclasses_json'

### ISSUE THREAD

**Issue by NB-123** [run-llama/llama_index#11436]
### Bug Description

I tried to install llama-index using poetry. However, I keep getting the following error:

Traceback (most recent call last):
  File "llamaindex_pandas_query_engine.py", line 15, in <module>
    from llama_index.readers.file import PyMuPDFReader
  File "/.venv/lib/python3.10/site-packages/llama_index/readers/file/__init__.py", line 1, in <module>
    from llama_index.readers.file.docs import DocxReader, HWPReader, PDFReader
  File "/.venv/lib/python3.10/site-packages/llama_index/readers/file/docs/__init__.py", line 1, in <module>
    from llama_index.readers.file.docs.base import DocxReader, HWPReader, PDFReader
  File "/.venv/lib/python3.10/site-packages/llama_index/readers/file/docs/base.py", line 11, in <module>
    from llama_index.core.readers.base import BaseReader
  File "/.venv/lib/python3.10/site-packages/llama_index/core/__init__.py", line 10, in <module>
    from llama_index.core.base.response.schema import Response
  File "/.venv/lib/python3.10/site-packages/llama_index/core/base/response/schema.py", line 7, in <module>
    from llama_index.core.schema import NodeWithScore
  File "/.venv/lib/python3.10/site-packages/llama_index/core/schema.py", line 13, in <module>
    from dataclasses_json import DataClassJsonMixin
ModuleNotFoundError: No module named 'dataclasses_json'

I also tried to manually install dataclasses_json, install all the underlying packages in llama-index one-by-one and reinstalling/deleting everything. I am running my code in a virtual environment. 

### Version

0.10.12

### Steps to Reproduce

1) Download Poetry
2) Poetry add llama-index
3) Run this code:

from llama_index.readers.file import PyMuPDFReader
reader = PyMuPDFReader()

**Comment by logan-markewich** [comment]
@NB-123 This works in google colab.

Maybe try in a fresh terminal
```
pip uninstall llama-index  # remove any possible global install
python -m venv venv
source venv/bin/activate
pip install llama-index
python -c "from llama_index.readers.file import PyMuPDFReader"
```

**Comment by NB-123** [comment]
@logan-markewich thanks for the suggestion. 

Doing the following worked for me:
pip3 uninstall dataclasses-json
pip uninstall dataclasses-json
poetry remove dataclasses-json

pip3 uninstall llama-index
pip uninstall llama-index
poetry remove llama-index

And finally clearing all pycache files in my IDE (Visual Studio).
