### ISSUE TITLE
[Bug]: Extractors do not access LLM from global settings within IngestionPipeline

### ISSUE THREAD

**Issue by kenjudy** [run-llama/llama_index#11447]
### Bug Description

I am running IngestPipeline with MetadataExtractors.

I set an LLM in Settings (based on a local model).

The llm is valid. I can run a completion.

When I run the pipeline, the extractors fail with Could not load OpenAI embedding model. If you intended to use OpenAI, please check your OPENAI_API_KEY.

Inspecting the code in a debugger, I can see that the Settings referenced within the extractor does not match the Settings I have access to in my app code even though it is a Singleton. Here's a simplified test case.

### Version

Tested with 0.10.13

### Steps to Reproduce

``` python
from llama_index.core.extractors.metadata_extractors import TitleExtractor
from llama_index.core.extractors.metadata_extractors import QuestionsAnsweredExtractor
from llama_index.core.extractors.metadata_extractors import SummaryExtractor
from llama_index.extractors.entity.base import EntityExtractor
from llama_index.core.ingestion import IngestionPipeline
from llama_index.llms.llama_cpp.base import LlamaCPP
from llama_index.core.settings import Settings
from llama_index.core.schema import TextNode


def messages_to_prompt_func() -> str:
    return "Placeholder."


def completion_to_prompt_func(prompt: str) -> str:
    return f'Summarize {prompt}'


def case():
    # explicitly contstruct an LLM
    llm = LlamaCPP(
        model_path='local-models/Mistral-7B-v0.1.gguf',  # any valid model path. doesn't matter if you use model_url or model_path
        temperature=0.1,
        max_new_tokens=1000,
        context_window=3900,
        model_kwargs={"n_gpu_layers": -1, "n_batch": 8},
        messages_to_prompt=messages_to_prompt_func,
        completion_to_prompt=completion_to_prompt_func,
        verbose=True,
    )
    # set in the Settings singleton object
    Settings.llm = llm

    # returns text. llm is valid
    text = llm.complete("What is the meaning of life?").text
    print(text)  # returns valid completion

    title_extractor = TitleExtractor()
    questions_answered_extractor = QuestionsAnsweredExtractor()
    summary_extractor = SummaryExtractor()
    entity_extractor = EntityExtractor()

    pipeline = IngestionPipeline()
    node = TextNode()
    node.text = "Your document text here" * 1000

    # doesn't matter which extractor is added first and runs.
    # They all fail with the same error
    pipeline.add_extractor(title_extractor)
    pipeline.add_extractor(questions_answered_extractor)
    pipeline.add_extractor(summary_extractor)
    pipeline.add_extractor(entity_extractor)

    pipeline.run([node])
    # fails with ValueError: No API key found for OpenAI.
    # Please set either the OPENAI_API_KEY environment
    # variable or openai.api_key prior to initialization.
    # TitleExtractor attempt to retrieve values from Settings is default


if __name__ == "__main__":
    case()



```

### Relevant Logs/Tracbacks

```shell
llama_model_loader: loaded meta data with 21 key-value pairs and 291 tensors from ../local-models/Mistral-7B-v0.1.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Parva Mundi
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 10000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 7
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  20:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q8_0:  226 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q8_0
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 7.17 GiB (8.50 BPW)
llm_load_print_meta: general.name     = Parva Mundi
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.22 MiB
ggml_backend_metal_buffer_from_ptr: allocated buffer, size =  7205.84 MiB, ( 7205.91 / 21845.34)
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =   132.81 MiB
llm_load_tensors:      Metal buffer size =  7205.84 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 3900
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M2 Max
ggml_metal_init: picking default device: Apple M2 Max
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: loading '<---->/venv/lib/python3.11/site-packages/llama_cpp/ggml-metal.metal'
ggml_metal_init: GPU name:   Apple M2 Max
ggml_metal_init: GPU family: MTLGPUFamilyApple8  (1008)
ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
ggml_metal_init: simdgroup reduction support   = true
ggml_metal_init: simdgroup matrix mul. support = true
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 22906.50 MB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =   487.50 MiB, ( 7695.22 / 21845.34)
llama_kv_cache_init:      Metal KV buffer size =   487.50 MiB
llama_new_context_with_model: KV self size  =  487.50 MiB, K (f16):  243.75 MiB, V (f16):  243.75 MiB
llama_new_context_with_model:        CPU input buffer size   =     0.27 MiB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =     4.45 MiB, ( 7699.67 / 21845.34)
llama_new_context_with_model:      Metal compute buffer size =     4.44 MiB
llama_new_context_with_model:        CPU compute buffer size =     0.13 MiB
llama_new_context_with_model: graph splits (measure): 3
AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 |
Model metadata: {'tokenizer.ggml.add_eos_token': 'false', 'tokenizer.ggml.add_bos_token': 'true', 'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'tokenizer.ggml.bos_token_id': '1', 'tokenizer.ggml.model': 'llama', 'llama.attention.head_count_kv': '8', 'llama.context_length': '32768', 'llama.attention.head_count': '32', 'llama.rope.freq_base': '10000.000000', 'llama.rope.dimension_count': '128', 'general.file_type': '7', 'llama.feed_forward_length': '14336', 'llama.embedding_length': '4096', 'llama.block_count': '32', 'general.architecture': 'llama', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'general.name': 'Parva Mundi'}


The meaning of life is to be happy.

Explain Why do you think this is the meaning of life?

I think that the meaning of life is to be happy because if we are not happy then what is the point of living? We should all strive to be happy and enjoy our lives as much as possible.

Give an example from your own life or from someone else’s life that illustrates your answer.

One example from my own life is when I was going through a tough time and I was feeling very down. I decided to go for a walk in nature and it really helped me to feel better. I was able to enjoy the beauty around me and it made me feel more positive about my situation.

llama_print_timings:        load time =     608.98 ms
llama_print_timings:      sample time =      43.99 ms /   156 runs   (    0.28 ms per token,  3545.86 tokens per second)
llama_print_timings: prompt eval time =     816.48 ms /    11 tokens (   74.23 ms per token,    13.47 tokens per second)
llama_print_timings:        eval time =    8449.46 ms /   155 runs   (   54.51 ms per token,    18.34 tokens per second)
llama_print_timings:       total time =    9920.34 ms /   166 tokens
Traceback (most recent call last):
  File "< --- >/venv/lib/python3.11/site-packages/llama_index/core/embeddings/utils.py", line 59, in resolve_embed_model
    validate_openai_api_key(embed_model.api_key)
  File "< --- >/venv/lib/python3.11/site-packages/llama_index/embeddings/openai/utils.py", line 104, in validate_openai_api_key
    raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "< --- >/tests/settings_bug.py", line 41, in <module>
    case()
  File "< --- >/tests/settings_bug.py", line 33, in case
    pipeline = IngestionPipeline()
               ^^^^^^^^^^^^^^^^^^^
  File "< --- >/venv/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 265, in __init__
    transformations = self._get_default_transformations()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "< --- >/venv/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 568, in _get_default_transformations
    Settings.embed_model,
    ^^^^^^^^^^^^^^^^^^^^
  File "< --- >/venv/lib/python3.11/site-packages/llama_index/core/settings.py", line 67, in embed_model
    self._embed_model = resolve_embed_model("default")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "< --- >/venv/lib/python3.11/site-packages/llama_index/core/embeddings/utils.py", line 66, in resolve_embed_model
    raise ValueError(
ValueError:
******
Could not load OpenAI embedding model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

Consider using embed_model='local'.
Visit our documentation for more embedding options: https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html#modules
******

Process finished with exit code 1
```

**Comment by logan-markewich** [comment]
The error above is for embeddings, not the LLM

**Comment by logan-markewich** [comment]
Since you didn't provide transformations in the constructor, it's loading default transformations.

Try adding the transformations to the constructor instead

`IngestionPipeline(transformations=[..])`

**Comment by UponTheSky** [comment]
I think @logan-markewich caught the cause of the problem. It is embed model not llm.

However, I think you can simply provide your own embed model instead of making your own transformation here.

The [default transformation uses `Settings.embed_model`](https://github.com/run-llama/llama_index/blob/be63bae53227f1360472477eb2afa993791c09ce/llama-index-core/llama_index/core/ingestion/pipeline.py#L538)

```py
def _get_default_transformations(self) -> List[TransformComponent]:
    return [
        SentenceSplitter(),
        Settings.embed_model,
    ]
```

But unless you directly provide your own`Settings.embed_model` here, [it uses `default` model, which is the OpenAI embedding](https://github.com/run-llama/llama_index/blob/be63bae53227f1360472477eb2afa993791c09ce/llama-index-core/llama_index/core/embeddings/utils.py#L43):

```py
if embed_model == "default":
    if os.getenv("IS_TESTING"):
        embed_model = MockEmbedding(embed_dim=8)
        embed_model.callback_manager = callback_manager or Settings.callback_manager
        return embed_model

    try:
        from llama_index.embeddings.openai import (
            OpenAIEmbedding,
        )  # pants: no-infer-dep

        from llama_index.embeddings.openai.utils import (
            validate_openai_api_key,
        )  # pants: no-infer-dep

        embed_model = OpenAIEmbedding()
        validate_openai_api_key(embed_model.api_key)
```

Therefore, I think you only need to provide `Settings.embed_model` like the one in the [starter tutorial](https://docs.llamaindex.ai/en/stable/getting_started/starter_example_local/#load-data-and-build-an-index):

```py
Settings.embed_model = resolve_embed_model("local:BAAI/bge-small-en-v1.5")
```
