### ISSUE TITLE
[Bug]: ImportError: `llama-index-readers-file` package not found but is installed

### ISSUE THREAD

**Issue by rwood-97** [run-llama/llama_index#11469]
### Bug Description

I am trying to migrate my package to v0.10.0 and am having issues with importing the llama_index github readers.

Other relevant packages from pip list:
``` 
llama-index                              0.10.13.post1
llama-index-agent-openai                 0.1.5
llama-index-cli                          0.1.5
llama-index-core                         0.10.13
llama-index-embeddings-openai            0.1.6
llama-index-indices-managed-llama-cloud  0.1.3
llama-index-legacy                       0.9.48
llama-index-llms-azure-openai            0.1.4
llama-index-llms-huggingface             0.1.3
llama-index-llms-llama-cpp               0.1.3
llama-index-llms-openai                  0.1.6
llama-index-multi-modal-llms-openai      0.1.4
llama-index-program-openai               0.1.4
llama-index-question-gen-openai          0.1.3
llama-index-readers-file                 0.1.6
llama-index-readers-github               0.1.7
llama-index-readers-llama-parse          0.1.3
llama-index-vector-stores-chroma         0.1.4
llama-parse                              0.3.4
llamaindex-py-client                     0.1.13
```

### Version

0.10.13.post1

### Steps to Reproduce

``` python

from llama_index.readers.github import (
    GithubClient,
    GitHubIssuesClient,
    GitHubRepositoryIssuesReader,
    GithubRepositoryReader,
)
```

or simply:

``` python

 import llama_index.readers.github
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/rwood/Library/Caches/pypoetry/virtualenvs/reginald-INSspBS7-py3.11/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 22, in _try_loading_included_file_formats
    from llama_index.readers.file import (
ImportError: cannot import name 'DocxReader' from 'llama_index.readers.file' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rwood/Library/Caches/pypoetry/virtualenvs/reginald-INSspBS7-py3.11/lib/python3.11/site-packages/llama_index/readers/github/__init__.py", line 8, in <module>
    from llama_index.readers.github.repository.base import (
  File "/Users/rwood/Library/Caches/pypoetry/virtualenvs/reginald-INSspBS7-py3.11/lib/python3.11/site-packages/llama_index/readers/github/repository/base.py", line 38, in <module>
    DEFAULT_FILE_READER_CLS = _try_loading_included_file_formats()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rwood/Library/Caches/pypoetry/virtualenvs/reginald-INSspBS7-py3.11/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 36, in _try_loading_included_file_formats
    raise ImportError("`llama-index-readers-file` package not found")
ImportError: `llama-index-readers-file` package not found
```

**Comment by rwood-97** [comment]
@dosu-bot 

I just created a new venv and it has fixed the issue.
Here is my new pip list:
```
llama-index                              0.10.13.post1
llama-index-agent-openai                 0.1.5
llama-index-cli                          0.1.5
llama-index-core                         0.10.13
llama-index-embeddings-openai            0.1.6
llama-index-indices-managed-llama-cloud  0.1.3
llama-index-legacy                       0.9.48
llama-index-llms-azure-openai            0.1.4
llama-index-llms-huggingface             0.1.3
llama-index-llms-llama-cpp               0.1.3
llama-index-llms-openai                  0.1.6
llama-index-multi-modal-llms-openai      0.1.4
llama-index-program-openai               0.1.4
llama-index-question-gen-openai          0.1.3
llama-index-readers-file                 0.1.6
llama-index-readers-github               0.1.7
llama-index-readers-llama-parse          0.1.3
llama-index-vector-stores-chroma         0.1.4
llama-parse                              0.3.4
llamaindex-py-client                     0.1.13
```

Can you check if this is different from the one above?

**Comment by logan-markewich** [comment]
@rwood-97  maybe I would try from a fresh venv?

I see you are using poetry. In a new terminal
```
pip uninstall llama-index  # remove an global install
poetry shell
pip install llama-index llama-index-vector-stores-chroma llama-index-readers-github llama-index-llms-azure-openai llama-index-llms-huggingface llama-index-llms-llama-cpp
```

**Comment by rwood-97** [comment]
Hi, sorry I should have closed this. 
A new venv fixed the issue though, thanks!
