### ISSUE TITLE
[Bug]: LangChainDeprecationWarning

### ISSUE THREAD

**Issue by FadelDabaja** [run-llama/llama_index#11510]
### Bug Description

I keep getting this error despite installing the latest version of langchain-community. 

### Version

0.10.14

### Steps to Reproduce

First bug-report so unsure if it's correct:

But I'm using AzureOpenAI + OpenAI Pydantic Program + OpenAI for embedding + Cohere for reranking.

### Relevant Logs/Tracbacks

```shell
/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatAnyscale`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/langchain/embeddings/__init__.py:29: LangChainDeprecationWarning: Importing embeddings from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.embeddings import HuggingFaceBgeEmbeddings`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/langchain/embeddings/__init__.py:29: LangChainDeprecationWarning: Importing embeddings from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.embeddings import HuggingFaceEmbeddings`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import AI21`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import Cohere`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import FakeListLLM`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import OpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/runner/OS-AI/main.py", line 1, in <module>
    from util.ai.azure import init_azure, init_openai_embed, init_openai
  File "/home/runner/OS-AI/util/ai/azure.py", line 2, in <module>
    from llama_index.llms.azure_openai import AzureOpenAI
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/__init__.py", line 17, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/embeddings/__init__.py", line 11, in <module>
    from llama_index.embeddings.huggingface import HuggingFaceEmbedding
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/embeddings/huggingface/__init__.py", line 1, in <module>
    from llama_index.embeddings.huggingface.base import (
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/embeddings/huggingface/base.py", line 11, in <module>
    from llama_index.core.base.embeddings.base import (
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/indices/base.py", line 12, in <module>
    from llama_index.core.ingestion import run_transformations
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/ingestion/__init__.py", line 2, in <module>
    from llama_index.core.ingestion.pipeline import (
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/ingestion/pipeline.py", line 31, in <module>
    from llama_index.core.ingestion.api_utils import get_client
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/ingestion/api_utils.py", line 20, in <module>
    from llama_index.core.ingestion.data_sources import (
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/ingestion/data_sources.py", line 340, in <module>
    ConfigurableDataSources = build_conifurable_data_source_enum()
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/llama_index/core/ingestion/data_sources.py", line 117, in build_conifurable_data_source_enum
    DataSource(
  File "/home/runner/OS-AI/.pythonlibs/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DataSource
component_type
  subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)
```

**Comment by logan-markewich** [comment]
Do you need langchain? I would just uninstall it if you aren't using it.

Also, the error at the end of all that tells me you need to either install in a fresh venv, or you are mixing legacy imports with non-legacy imports

**Comment by mahaling** [comment]
I am getting the same error but while using llama_index.embeddings.azure_openai. I am using 10.14 version of llama-index. Has there been known issues with azure openai embeddings?

**Comment by logan-markewich** [comment]
No known issues. Maybe try with a fresh venv?

**Comment by logan-markewich** [comment]
@jyo64 please start with a fresh venv

In a new terminal

```
pip uninstall llama-index  # remove any global install
python -m venv venv
source venv/bin/activate
pip install llama-index llama-index-llms-azure-openai llama-index-embeddings-azure-openai
```

**Comment by logan-markewich** [comment]
@jyo64 are you sure you followed exactly?

Instead, you could try uninstalling everything then and reinstalling 

```
pip freeze | grep llama | xargs pip uninstall -y
pip install -U llama-index llama-index-llms-azure-openai llama-index-embeddings-azure-openai --force-reinstall --no-cache-dir

```
