### ISSUE TITLE
[Bug]: SimpleFileNodeParser() KeyError: 'extension'

### ISSUE THREAD

**Issue by SawyerCzupka** [run-llama/llama_index#11547]
### Bug Description

When trying to use the IngestionPipeline to load some documents with the SimpleFileNodeParser() it errors because its looking for a metadata key that doesn't exist.

### Version

0.10.12 & 0.10.14.post1

### Steps to Reproduce

Use this pipeline on documents generated with naive SimpleDirectoryReader:

```python
def get_pipeline(
    vector_store: BasePydanticVectorStore | None,
    together_embed_model_name: str = "togethercomputer/m2-bert-80M-32k-retrieval",
) -> IngestionPipeline:
    if os.environ.get("TOGETHER_API_KEY") is None:
        raise ValueError("TOGETHER_API_KEY environment variable must be set")

    transformations = [
        SimpleFileNodeParser(),
        SentenceSplitter(
            chunk_size=384, chunk_overlap=64
        ),  # Ensures that the chunks are not too large
        TogetherEmbedding(
            model_name=together_embed_model_name,
        ),
    ]

    return IngestionPipeline(
        transformations=transformations,
        vector_store=vector_store,
    )
```
    
   

### Relevant Logs/Tracbacks

```shell
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/home/sawyer/git/gef-ml/.venv/lib/python3.10/site-packages/certifi/cacert.pem'
DEBUG:httpcore.connection:connect_tcp.started host='localhost' port=6333 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7fe9f35db8e0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'transfer-encoding', b'chunked'), (b'vary', b'accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers'), (b'content-type', b'application/json'), (b'content-encoding', b'gzip'), (b'date', b'Fri, 01 Mar 2024 18:15:50 GMT')])
INFO:httpx:HTTP Request: GET http://localhost:6333/collections/temp "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
INFO:gef_ml.ingestion:Found 1 projects in directory ../data/to_ingest/.
  0%|                                                                 | 0/1 [00:00<?, ?it/s]INFO:gef_ml.ingestion:Ingesting project 10087: Started...
DEBUG:llama_index.core.readers.file.base:> [SimpleDirectoryReader] Total files added: 4
DEBUG:fsspec.local:open file: /home/sawyer/git/gef-ml/scripts/../data/to_ingest/10087/p10087_doc0.pdf
DEBUG:fsspec.local:open file: /home/sawyer/git/gef-ml/scripts/../data/to_ingest/10087/p10087_doc1.pdf
DEBUG:fsspec.local:open file: /home/sawyer/git/gef-ml/scripts/../data/to_ingest/10087/p10087_doc2.pdf
DEBUG:fsspec.local:open file: /home/sawyer/git/gef-ml/scripts/../data/to_ingest/10087/p10087_doc3.pdf
DEBUG:gef_ml.ingestion:First Doc Metadata: {'page_label': '1', 'file_name': '/home/sawyer/git/gef-ml/scripts/../data/to_ingest/10087/p10087_doc0.pdf', 'file_path': '/home/sawyer/git/gef-ml/scripts/../data/to_ingest/10087/p10087_doc0.pdf', 'file_type': 'application/pdf', 'file_size': 558431, 'creation_date': '2024-03-01', 'last_modified_date': '2024-03-01'}
DEBUG:gef_ml.ingestion:Loaded 190 documents for project 10087.
ERROR:gef_ml.ingestion:Ingesting project 10087: Failed.
ERROR:gef_ml.ingestion:Traceback: 'extension'
Traceback (most recent call last):
  File "/home/sawyer/git/gef-ml/gef_ml/ingestion.py", line 102, in ingest
    self._ingest_project_id(project_id, show_progress=False)
  File "/home/sawyer/git/gef-ml/gef_ml/ingestion.py", line 77, in _ingest_project_id
    self.pipeline.run(
  File "/home/sawyer/git/gef-ml/.venv/lib/python3.10/site-packages/llama_index/core/ingestion/pipeline.py", line 750, in run
    nodes = run_transformations(
  File "/home/sawyer/git/gef-ml/.venv/lib/python3.10/site-packages/llama_index/core/ingestion/pipeline.py", line 124, in run_transformations
    nodes = transform(nodes, **kwargs)
  File "/home/sawyer/git/gef-ml/.venv/lib/python3.10/site-packages/llama_index/core/node_parser/interface.py", line 116, in __call__
    return self.get_nodes_from_documents(nodes, **kwargs)
  File "/home/sawyer/git/gef-ml/.venv/lib/python3.10/site-packages/llama_index/core/node_parser/interface.py", line 76, in get_nodes_from_documents
    nodes = self._parse_nodes(documents, show_progress=show_progress, **kwargs)
  File "/home/sawyer/git/gef-ml/.venv/lib/python3.10/site-packages/llama_index/core/node_parser/file/simple_file.py", line 68, in _parse_nodes
    ext = document.metadata["extension"]
KeyError: 'extension'
```

Metadata for the first loaded document:
 ```shell
First Doc Metadata: {'page_label': '1', 'file_name': '/home/sawyer/git/gef-ml/scripts/../data/to_ingest/10087/p10087_doc0.pdf', 'file_path': '/home/sawyer/git/gef-ml/scripts/../data/to_ingest/10087/p10087_doc0.pdf', 'file_type': 'application/pdf', 'file_size': 558431, 'creation_date': '2024-03-01', 'last_modified_date': '2024-03-01'}
```

**Comment by SawyerCzupka** [comment]
@dosu-bot does the 'extension' metadata key get set by llamaindex anywhere?

**Comment by MrLion7** [comment]
same here

**Comment by dino-su** [comment]
same here
