### ISSUE TITLE
[Question]: RAG CLI example gives openAI Rate Limit Error

### ISSUE THREAD

**Issue by gittar** [run-llama/llama_index#11593]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am tring to run the RAG CLI example decribed in https://docs.llamaindex.ai/en/latest/use_cases/q_and_a/rag_cli.html#/api/llama_index.readers.SimpleDirectoryReader.rst

I did the following as described at the above page:
```
pip install -U llama-index
pip install -U chromadb
export OPENAI_API_KEY=<api_key> (using a valid OpenAI API key, I am in tier1, having only paig USD 6 so far)
```

There is a small (12k) text file in docs/

If I run 
`cli rag --files docs/*`
I get:
`Retrying llama_index.embeddings.openai.base.aget_embeddings in 0.6492698516383741 seconds as it raised RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}.
Traceback (most recent call last):
  File "/home/fritzke/miniconda2/envs/ragcli/bin/llamaindex-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/fritzke/miniconda2/envs/ragcli/lib/python3.11/site-packages/llama_index/cli/command_line.py", line 269, in main
    args.func(args)
  File "/home/fritzke/miniconda2/envs/ragcli/lib/python3.11/site-packages/llama_index/cli/rag/base.py", line 371, in <lambda>
...
  File "/home/fritzke/miniconda2/envs/ragcli/lib/python3.11/site-packages/openai/_base_client.py", line 1550, in _retry_request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/fritzke/miniconda2/envs/ragcli/lib/python3.11/site-packages/openai/_base_client.py", line 1519, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
`
Due to being in Tier1 on OpenAI I have low rate limits. 

Can I "slow down" cli rag or is there another solution?

**Comment by gittar** [comment]
I was able to solve the problem by funding my account at OpenAI (did not know this was necessary since I had attached my CC details and had been able befor to make API calls without advance "funding") and creating a new API key.
