### ISSUE TITLE
[Bug]: Unable to run CLI for llama index v0.10 imgration

### ISSUE THREAD

**Issue by mw19930312** [run-llama/llama_index#11624]
### Bug Description

I'm following the migration guide for llama_index v0.10. https://docs.llamaindex.ai/en/latest/getting_started/v0_10_0_migration.html

I'm using poetry for my dependency management. However, I cannot use the CLI provided in the tutorial to migrate all imports in my .py files. Instead, the CLI command brought me a complaint on the llama_index library in my poetry environment.

It seems that even after I installed the latest version of llama_index in my poetry environment, it still kills off the old version when I'm running the CLI comman. Can I get some help on how to move forward? Thanks!

### Version

0.0.15

### Steps to Reproduce

poetry add llama_index@^0.10.15
poetry update llama_index
poetry add llama-index-core

(brevian-lib-0aNJl4sa-py3.11) weimiao@Weis-MacBook-Pro-3 brevian-lib % llamaindex-cli update brevian_lib

### Relevant Logs/Tracbacks

```shell
(brevian-lib-0aNJl4sa-py3.11) weimiao@Weis-MacBook-Pro-3 brevian-lib % llamaindex-cli update brevian_lib
Traceback (most recent call last):
  File "/Users/weimiao/Library/Caches/pypoetry/virtualenvs/brevian-lib-0aNJl4sa-py3.11/bin/llamaindex-cli", line 5, in <module>
    from llama_index.cli.command_line import main
  File "/Users/weimiao/Library/Caches/pypoetry/virtualenvs/brevian-lib-0aNJl4sa-py3.11/lib/python3.11/site-packages/llama_index/cli/command_line.py", line 4, in <module>
    from llama_index.cli.rag import RagCLI, default_ragcli_persist_dir
  File "/Users/weimiao/Library/Caches/pypoetry/virtualenvs/brevian-lib-0aNJl4sa-py3.11/lib/python3.11/site-packages/llama_index/cli/rag/__init__.py", line 1, in <module>
    from llama_index.cli.rag.base import RagCLI, default_ragcli_persist_dir
  File "/Users/weimiao/Library/Caches/pypoetry/virtualenvs/brevian-lib-0aNJl4sa-py3.11/lib/python3.11/site-packages/llama_index/cli/rag/base.py", line 9, in <module>
    from llama_index.core import (
ImportError: cannot import name 'SimpleDirectoryReader' from 'llama_index.core' (unknown location)
```

**Comment by logan-markewich** [comment]
@mw19930312 create a fresh venv, seems your env is corrupted with a previous v0.9.x install
