### ISSUE TITLE
[Bug]: `llama-index-embeddings-fastembed` fails on import

### ISSUE THREAD

**Issue by Danipulok** [run-llama/llama_index#11642]
### Bug Description

MRE:
```python
from llama_index.embeddings.fastembed import FastEmbedEmbedding
```

Maybe it fails only on Windows. Here is basic OS info:
```
Python: 3.11.7
OS: Windows 10
Version: 22H2
```

### Version

0.9.42.post1

### Steps to Reproduce

Libs versions:
```
llama-index==0.9.42.post1
llama-index-agent-openai==0.1.5
llama-index-core==0.10.15
llama-index-embeddings-fastembed==0.1.4
llama-index-embeddings-openai==0.1.6
llama-index-llms-openai==0.1.7
llama-index-program-openai==0.1.4
llama-index-vector-stores-opensearch==0.1.6
llamaindex-py-client==0.1.13

pydantic==2.6.3
pydantic_core==2.16.3
```

Most important versions:
```
llama-index==0.9.42.post1
llama-index-embeddings-fastembed==0.1.4

pydantic==2.6.3
pydantic_core==2.16.3
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "D:\Code\projects\project\.mre.py", line 1, in <project>
    from llama_index.embeddings.fastembed import FastEmbedEmbedding
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\__init__.py", line 13, in <project>
    from llama_index.callbacks.global_handlers import set_global_handler
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\callbacks\__init__.py", line 7, in <project>
    from .token_counting import TokenCountingHandler
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\callbacks\token_counting.py", line 6, in <project>
    from llama_index.utilities.token_counting import TokenCounter
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\utilities\token_counting.py", line 6, in <project>
    from llama_index.llms import ChatMessage, MessageRole
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\llms\__init__.py", line 1, in <project>
    from llama_index.core.llms.types import (
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\__init__.py", line 19, in <project>
    from llama_index.core.indices import (
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\indices\__init__.py", line 4, in <project>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\indices\composability\__init__.py", line 4, in <project>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\indices\composability\graph.py", line 7, in <project>
    from llama_index.core.indices.base import BaseIndex
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\indices\base.py", line 12, in <project>
    from llama_index.core.ingestion import run_transformations
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\ingestion\__init__.py", line 2, in <project>
    from llama_index.core.ingestion.pipeline import (
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\ingestion\pipeline.py", line 31, in <project>
    from llama_index.core.ingestion.api_utils import get_client
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\ingestion\api_utils.py", line 20, in <project>
    from llama_index.core.ingestion.data_sources import (
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\ingestion\data_sources.py", line 340, in <project>
    ConfigurableDataSources = build_conifurable_data_source_enum()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\projects\project\.venv\Lib\site-packages\llama_index\core\ingestion\data_sources.py", line 117, in build_conifurable_data_source_enum
    DataSource(
  File "D:\Code\projects\project\.venv\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DataSource
component_type
  subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)
```
```

**Comment by Danipulok** [comment]
It seems the error was because I has previous llama-index package installed. Sorry for confusion.
