### ISSUE TITLE
[Bug]: ValueError: Unknown document type: <class 'llama_index.legacy.schema.Document'>

### ISSUE THREAD

**Issue by Deepa-Tilwani** [run-llama/llama_index#11706]
### Bug Description

According my understanding, it seems that there might be a compatibility issue with the types of documents being processed in the script. Following the example from the documentation: 

I am doing from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, ServiceContext

### Version

0.10.6

### Steps to Reproduce

from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, ServiceContext
def train():
    
    documents = SimpleDirectoryReader("/work/dtilwani/Reasons/Data/").load_data() # give the path of the directory which contains all the files of the dataset
    os.environ["REPLICATE_API_TOKEN"] = "api"

    llama2_7b_chat = "meta/llama-2-7b-chat:8e6975e5ed6174911a6ff3d60540dfd4844201974602551e10e9e87ab143d81e"
    llm = Replicate(
        model=llama2_7b_chat,
        temperature=1.0,
        additional_kwargs={"top_p": 0.95, "max_new_tokens": 300},
    )

    embed_model = resolve_embed_model("local:BAAI/bge-small-en")
    service_context = ServiceContext.from_defaults(
        chunk_size=512,
        llm=llm,
        embed_model=embed_model
    )
    
    rerank = SentenceTransformerRerank(
    model="cross-encoder/ms-marco-MiniLM-L-12-v2", top_n=10 
    )

    index = VectorStoreIndex.from_documents(documents, service_context=service_context)

    return [index, rerank]

### Relevant Logs/Tracbacks

```shell
[nltk_data] Downloading package punkt to /home/dtilwani/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
/work/dtilwani/Reasons/AdvRAG/Advanced_RAG_LLAMA/Advanced_RAG_Indirect.py:117: DeprecationWarning: Call to deprecated class method from_defaults. (ServiceContext is deprecated, please use `llama_index.settings.Settings` instead.) -- Deprecated since version 0.10.0.
  service_context = ServiceContext.from_defaults(
/home/dtilwani/.local/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "/work/dtilwani/Reasons/AdvRAG/Advanced_RAG_LLAMA/Advanced_RAG_Indirect.py", line 170, in <module>
    main()
  File "/work/dtilwani/Reasons/AdvRAG/Advanced_RAG_LLAMA/Advanced_RAG_Indirect.py", line 167, in main
    prompting(file_name,d)
  File "/work/dtilwani/Reasons/AdvRAG/Advanced_RAG_LLAMA/Advanced_RAG_Indirect.py", line 140, in prompting
    t = train()
  File "/work/dtilwani/Reasons/AdvRAG/Advanced_RAG_LLAMA/Advanced_RAG_Indirect.py", line 127, in train
    index = VectorStoreIndex.from_documents(documents, service_context=service_context)
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/indices/base.py", line 135, in from_documents
    nodes = run_transformations(
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/ingestion/pipeline.py", line 127, in run_transformations
    nodes = transform(nodes, **kwargs)
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/node_parser/interface.py", line 115, in __call__
    return self.get_nodes_from_documents(nodes, **kwargs)
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/node_parser/interface.py", line 75, in get_nodes_from_documents
    nodes = self._parse_nodes(documents, show_progress=show_progress, **kwargs)
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/node_parser/interface.py", line 184, in _parse_nodes
    build_nodes_from_splits(splits, node, id_func=self.id_func)
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/node_parser/node_utils.py", line 91, in build_nodes_from_splits
    raise ValueError(f"Unknown document type: {type(document)}")
ValueError: Unknown document type: <class 'llama_index.legacy.schema.Document'>
```

**Comment by logan-markewich** [comment]
@Deepa-Tilwani it seems like you mixed legacy imports with non-legacy imports? You should use either all legacy imports or not

**Comment by Deepa-Tilwani** [comment]
I have list of json file in and I am trying to read like this :
documents = SimpleDirectoryReader("/work/dtilwani/Reasons/Data/").load_data() 

I updated it with the following : 


from llama_index.legacy.schema import TextNode

# Convert your custom Document objects to TextNode objects
text_nodes = [TextNode(text=doc.text) for doc in documents]

# Now you can use text_nodes with VectorStoreIndex.from_documents
index = VectorStoreIndex.from_documents(text_nodes, service_context=service_context)

I have this error now : 
Traceback (most recent call last):
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/readers/file/base.py", line 21, in _try_loading_included_file_formats
    from llama_index.readers.file import (
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/readers/file/__init__.py", line 1, in <module>
    from llama_index.readers.file.docs import DocxReader, HWPReader, PDFReader
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/readers/file/docs/__init__.py", line 1, in <module>
    from llama_index.readers.file.docs.base import DocxReader, HWPReader, PDFReader
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/readers/file/docs/base.py", line 15, in <module>
    from llama_index.core.readers.file.base import get_default_fs
ImportError: cannot import name 'get_default_fs' from 'llama_index.core.readers.file.base' (/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/readers/file/base.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/dtilwani/Reasons/AdvRAG/Advanced_RAG_LLAMA/Advanced_RAG_Indirect.py", line 177, in <module>
    main()
  File "/work/dtilwani/Reasons/AdvRAG/Advanced_RAG_LLAMA/Advanced_RAG_Indirect.py", line 174, in main
    prompting(file_name,d)
  File "/work/dtilwani/Reasons/AdvRAG/Advanced_RAG_LLAMA/Advanced_RAG_Indirect.py", line 147, in prompting
    t = train()
  File "/work/dtilwani/Reasons/AdvRAG/Advanced_RAG_LLAMA/Advanced_RAG_Indirect.py", line 111, in train
    documents = SimpleDirectoryReader("/work/dtilwani/Reasons/Data/").load_data() # give the path of the directory which contains all the files of the dataset
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/readers/file/base.py", line 396, in load_data
    SimpleDirectoryReader.load_file(
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/readers/file/base.py", line 303, in load_file
    default_file_reader_cls = SimpleDirectoryReader.supported_suffix_fn()
  File "/home/dtilwani/.local/lib/python3.9/site-packages/llama_index/core/readers/file/base.py", line 35, in _try_loading_included_file_formats
    raise ImportError("`llama-index-readers-file` package not found")
ImportError: `llama-index-readers-file` package not found


When I do pip list here it is showing it have above package :
<img width="768" alt="image" src="https://github.com/run-llama/llama_index/assets/26201575/8726be81-7832-46c8-a935-0191be9ea263">

**Comment by logan-markewich** [comment]
@Deepa-Tilwani just start with a fresh venv

In a new terminal 

```
pip uninstall llama-index
python -m venv venv
source venv/bin/activate
pip install llama-index
```

And again, please ensure all imports are using llama.index.legacy, or ensure all imports are updated to the non-legacy, there cannot be both

**Comment by trishachander** [comment]
@Deepa-Tilwani Has your issue been resolved? If so, how did you fix it?
