### ISSUE TITLE
[Bug]: RecursionError: maximum recursion depth exceeded in comparison in RaptorPack

### ISSUE THREAD

**Issue by marib00** [run-llama/llama_index#11830]
### Bug Description

I've been trying to run RaptorPack on a corpus of around 1700 documents and I'm getting the recursion depth exceeded error every time. When I limit it to 500 documents everything is fine. Tried doing `import sys; sys.setrecursionlimit(1000000)` but to no avail.

### Version

 0.10.18.post1

### Steps to Reproduce

```
from llama_index.packs.raptor import RaptorPack
pack = RaptorPack(documents, llm=llm, embed_model=embed_model)
# just make sure documents are sufficiently large
```

### Relevant Logs/Tracbacks

```shell
Generating embeddings for level 0.
Performing clustering for level 0.
Traceback (most recent call last):
  File "/opt/conda/envs/llama-index/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llama-index/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2024.2.1-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2024.2.1-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2024.2.1-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.python-2024.2.1-universal/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.vscode-server/extensions/ms-python.python-2024.2.1-universal/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.python-2024.2.1-universal/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/mnt/Sync-shared/projects/rag/Untitled-1.py", line 76, in <module>
    pack = RaptorPack(documents, llm=llm, embed_model=embed_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llama-index/lib/python3.11/site-packages/llama_index/packs/raptor/base.py", line 343, in __init__
    self.retriever = RaptorRetriever(
                     ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llama-index/lib/python3.11/site-packages/llama_index/packs/raptor/base.py", line 134, in __init__
    asyncio.run(self.insert(documents))
  File "/opt/conda/envs/llama-index/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llama-index/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llama-index/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llama-index/lib/python3.11/site-packages/llama_index/packs/raptor/base.py", line 184, in insert
    nodes_per_cluster = get_clusters(cur_nodes, id_to_embedding)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llama-index/lib/python3.11/site-packages/llama_index/packs/raptor/clustering.py", line 157, in get_clusters
    get_clusters(
  File "/opt/conda/envs/llama-index/lib/python3.11/site-packages/llama_index/packs/raptor/clustering.py", line 157, in get_clusters
    get_clusters(
  File "/opt/conda/envs/llama-index/lib/python3.11/site-packages/llama_index/packs/raptor/clustering.py", line 157, in get_clusters
    get_clusters(
  [Previous line repeated 968 more times]
  File "/opt/conda/envs/llama-index/lib/python3.11/site-packages/llama_index/packs/raptor/clustering.py", line 152, in get_clusters
    total_length = sum([len(tokenizer.encode(node.text)) for node in cluster_nodes])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llama-index/lib/python3.11/site-packages/llama_index/packs/raptor/clustering.py", line 152, in <listcomp>
    total_length = sum([len(tokenizer.encode(node.text)) for node in cluster_nodes])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/llama-index/lib/python3.11/site-packages/tiktoken/core.py", line 116, in encode
    if match := _special_token_regex(disallowed_special).search(text):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by marib00** [comment]
It's seems that it gets stuck in an infinite recursion actually; an iterative version of the relevant function (`get_clusters`) results in an infinite loop 🤷‍♂️
