### ISSUE TITLE
[Bug]: module 'google.generativeai' has no attribute 'aget_embedding'

### ISSUE THREAD

**Issue by Ilnicki010** [run-llama/llama_index#11864]
### Bug Description

I tried to use `llama_index.core.evaluation.RetrieverEvaluator` with `llama_index.embeddings.google.GooglePaLMEmbedding`. When doing so I get the error: `AttributeError: module 'google.generativeai' has no attribute 'aget_embedding'`.

It looks like llama-index is trying to use `aget_embedding` method from `google.generativeai` that is not there (and I couldn't find any version when it was)

I temporarily solved that by transforming an async version of `get_query_embedding` in `llama_index.google.embeddings.google.palm.GooglePaLMEmbedding` into a sync one.

```python
...
async def _aget_query_embedding(self, query: str) -> List[float]:
        """The asynchronous version of _get_query_embedding."""
        return self._get_query_embedding(query)
...
```

### Version

0.10.18

### Steps to Reproduce

Follow these instructions to evaluate retrieval but instead of `llama_index.embeddings.openai.OpenAIEmbedding
` use `llama_index.embeddings.google.GooglePaLMEmbedding` https://docs.llamaindex.ai/en/stable/examples/evaluation/retrieval/retriever_eval.html

when you run `retriever_evaluator.aevaluate_dataset(val_dataset)` you should get an error

### Relevant Logs/Tracbacks

```shell
Task exception was never retrieved
future: <Task finished name='Task-27' coro=<tqdm_asyncio.gather.<locals>.wrap_awaitable() done, defined at /Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/tqdm/asyncio.py:75> exception=AttributeError("module 'google.generativeai' has no attribute 'aget_embedding'")>
Traceback (most recent call last):
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/evaluation/retrieval/base.py", line 185, in eval_worker
    return await self.aevaluate(query, expected_ids=expected_ids, mode=mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/evaluation/retrieval/base.py", line 151, in aevaluate
    retrieved_ids, retrieved_texts = await self._aget_retrieved_ids_and_texts(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/evaluation/retrieval/evaluator.py", line 56, in _aget_retrieved_ids_and_texts
    retrieved_nodes = await self.retriever.aretrieve(query)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/base/base_retriever.py", line 249, in aretrieve
    nodes = await self._aretrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 101, in _aretrieve
    await embed_model.aget_agg_embedding_from_queries(
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 151, in aget_agg_embedding_from_queries
    query_embeddings = [await self.aget_query_embedding(query) for query in queries]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 151, in <listcomp>
    query_embeddings = [await self.aget_query_embedding(query) for query in queries]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 125, in aget_query_embedding
    query_embedding = await self._aget_query_embedding(query)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/embeddings/google/palm.py", line 57, in _aget_query_embedding
    return await self._model.aget_embedding(query)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google.generativeai' has no attribute 'aget_embedding'
Task exception was never retrieved
future: <Task finished name='Task-28' coro=<tqdm_asyncio.gather.<locals>.wrap_awaitable() done, defined at /Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/tqdm/asyncio.py:75> exception=AttributeError("module 'google.generativeai' has no attribute 'aget_embedding'")>
Traceback (most recent call last):
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/evaluation/retrieval/base.py", line 185, in eval_worker
    return await self.aevaluate(query, expected_ids=expected_ids, mode=mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/evaluation/retrieval/base.py", line 151, in aevaluate
    retrieved_ids, retrieved_texts = await self._aget_retrieved_ids_and_texts(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/evaluation/retrieval/evaluator.py", line 56, in _aget_retrieved_ids_and_texts
    retrieved_nodes = await self.retriever.aretrieve(query)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/base/base_retriever.py", line 249, in aretrieve
    nodes = await self._aretrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 101, in _aretrieve
    await embed_model.aget_agg_embedding_from_queries(
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 151, in aget_agg_embedding_from_queries
    query_embeddings = [await self.aget_query_embedding(query) for query in queries]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 151, in <listcomp>
    query_embeddings = [await self.aget_query_embedding(query) for query in queries]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 125, in aget_query_embedding
    query_embedding = await self._aget_query_embedding(query)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dominikilnicki/Workspace/project_name/.venv/lib/python3.11/site-packages/llama_index/embeddings/google/palm.py", line 57, in _aget_query_embedding
    return await self._model.aget_embedding(query)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google.generativeai' has no attribute 'aget_embedding'
```

**Comment by logan-markewich** [comment]
just a typo, it should be using the method on the class, not the google module.

**Comment by Ilnicki010** [comment]
I'm running the `retriever_evaluator.aevaluate_dataset(val_dataset)` and it uses the `_aget_query_embedding` from `GooglePaLMEmbedding` class under the hood. I'm not calling this method directly

**Comment by logan-markewich** [comment]
I know, I meant a typo in the source code
