### ISSUE TITLE
[Feature Request]: Allow IngestionPipeline to use a custom API_Base and Custom model. 

### ISSUE THREAD

**Issue by antoineross** [run-llama/llama_index#11898]
### Feature Description

There are wrapper API's that allow us to use openAI client using custom API_Base, see: https://openrouter.ai/models/mistralai/mistral-7b-instruct:nitro?tab=api

What I would like for the feature to have is to be able to use this feature for LLamaIndex's Ingestion Pipeline.

### Reason

The reason is just so that the IngestionPipeline supports more models. 

### Value of Feature

I believe this is in line with LlamaIndex roadmap of inclusive of as many models as possible to the roster

**Comment by antoineross** [comment]
Just for more information in reproducing, this is how you can test it, currently it breaks because it maps the model to the contextsize which I believe can be set at a higher-level API such as in (OpenAI):

```

async def main():
    OPENROUTER_API_KEY = os.environ["OPENROUTER_API_KEY"] 
    llm_model="mistralai/mixtral-8x7b-instruct:nitro"

    llm = OpenAI(temperature=0.1, model=llm_model, api_base="https://openrouter.ai/api/v1", api_key=OPENROUTER_API_KEY, max_tokens=512)
    text_splitter = TokenTextSplitter(
        separator=" ", chunk_size=512, chunk_overlap=128
    )

    PINECONE_API_KEY = os.environ['SECRET_PINECONE_API_KEY']
    PINECONE_INDEX_NAME = os.environ['SECRET_PINECONE_INDEX']

    # Create a Pinecone client
    pc = Pinecone(api_key=PINECONE_API_KEY)
    pinecone_index = pc.Index(PINECONE_INDEX_NAME)
    print(f"Connected to Pinecone index: {PINECONE_INDEX_NAME}")

    # ---------------- Extractor Logic ---------------- #
    print("Generating extractors, using LLM model: ", llm.model)
    extractors = [
        TitleExtractor(nodes=5, llm=llm),
        QuestionsAnsweredExtractor(questions=3, llm=llm), # 
        EntityExtractor(prediction_threshold=0.5), # Entity extractor extracts lists of (persons, locations etc.). Uses BERT (free but uses your devices compute)
        SummaryExtractor(summaries=["prev", "self"], llm=llm), 
        KeywordExtractor(keywords=10, llm=llm),
        # CustomExtractor()
    ]

    transformations = [text_splitter] + extractors

    # ---------------- Directory Reading -> Processing Logic ---------------- #

    uber_docs = SimpleDirectoryReader( #input_files=["documents/Ethical_Hacking_RHartleyTeachingStudents.pdf"]
                                    input_dir="documents").load_data()
    pipeline = IngestionPipeline(transformations=transformations)
    workers = multiprocessing.cpu_count()

    uber_nodes = await pipeline.arun(documents=uber_docs,
                            num_workers=workers,
                            show_progress=True,)

    # ---------------- Generating Embeddings ---------------- #
    # First save the metadata of the nodes in a JSON file
    import json
    # Create an empty list to store all the metadata
    all_metadata = []

    # Append the metadata of each node to the list
    for node in uber_nodes:
        all_metadata.append(node.metadata)

    # Save all the metadata in a single JSON file
    with open("llamaindex-output/10k-vFinalv1.json", "w") as f:
        json.dump(all_metadata, f)

    embed_model = OpenAIEmbedding(model="text-embedding-3-large")
    for node in uber_nodes:
        node_embedding = await embed_model.aget_text_embedding_batch(
            node.get_content(metadata_mode="all")
        )
        node.embedding = node_embedding

    vector_store = PineconeVectorStore(pinecone_index=pinecone_index, namespace="llama-index")
    vector_store.add(uber_nodes)

if __name__ == "__main__":
    asyncio.run(main())
```
—— 
Error:
```
Traceback (most recent call last):
  File "/Users/antoineross/miniconda3/envs/llamaindex/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/antoineross/miniconda3/envs/llamaindex/lib/python3.11/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "/Users/antoineross/miniconda3/envs/llamaindex/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 106, in worker
    return await job
           ^^^^^^^^^
  File "/Users/antoineross/miniconda3/envs/llamaindex/lib/python3.11/site-packages/llama_index/core/llms/llm.py", line 292, in apredict
    if self.metadata.is_chat_model:
       ^^^^^^^^^^^^^
  File "/Users/antoineross/miniconda3/envs/llamaindex/lib/python3.11/site-packages/llama_index/llms/openai/base.py", line 231, in metadata
    context_window=openai_modelname_to_contextsize(self._get_model_name()),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antoineross/miniconda3/envs/llamaindex/lib/python3.11/site-packages/llama_index/llms/openai/utils.py", line 198, in openai_modelname_to_contextsize
    raise ValueError(
ValueError: Unknown model 'mistralai/mixtral-8x7b-instruct:nitro'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-0125-preview, gpt-4-turbo-preview, gpt-4-vision-preview, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<tqdm_asyncio.gather.<locals>.wrap_awaitable() done, defined at /Users/antoineross/miniconda3/envs/llamaindex/lib/python3.11/site-packages/tqdm/asyncio.py:75> exception=ValueError("Unknown model 'mistralai/mixtral-8x7b-instruct:nitro'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-0125-preview, gpt-4-turbo-preview, gpt-4-vision-preview, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613")>
Traceback (most recent call last):
```

**Comment by logan-markewich** [comment]
You can use the `OpenAILike` llm class if your API is compatible with the openai client

`pip install llama-index-llms-openai-like`

```
from llama_index.llms.openai_like import OpenAILike

llm = OpenAILike(model="my model", api_key="fake", api_base="....")
```
