### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.readers.schema'

### ISSUE THREAD

**Issue by HelloEveryonehh** [run-llama/llama_index#11937]
### Bug Description

When I run the code 
```python
from llama_hub.tools.tavily_research import pip listToolSpec
from llama_index.agent import OpenAIAgent
import os
BASE_URL = " https://chat.***.****/v1"                
API_SECRET_KEY="sk-1NA1mSaHKprafQ7r27Ca37A74eBc47868c9eEe8b0308112b" 
os.environ["OPENAI_API_KEY"]  =  API_SECRET_KEY
os.environ["OPENAI_API_BASE"] =  BASE_URL
tavily_tool = TavilyToolSpec(
    api_key='tvly-dHbDutyoi5iyCOWopGTb*******',
)
agent = OpenAIAgent.from_tools(tavily_tool.to_tool_list())
agent.chat('Please introduce the city of shanghai')
```
the mistake 
```
Traceback (most recent call last):
  File "e:\langchian_learning\Tavily\search.py", line 1, in <module>
    from llama_hub.tools.tavily_research import TavilyToolSpec
  File "D:\anaconda\envs\LLAMA\lib\site-packages\llama_hub\tools\tavily_research\__init__.py", line 2, in <module>
    from llama_hub.tools.tavily_research.base import (
  File "D:\anaconda\envs\LLAMA\lib\site-packages\llama_hub\tools\tavily_research\base.py", line 4, in <module>    
    from llama_index.readers.schema.base import Document
ModuleNotFoundError: No module named 'llama_index.readers.schema'
```
And the same mistake on colab
![image](https://github.com/run-llama/llama_index/assets/110333012/9e3a8186-161f-4f6f-ba3f-6d80c312d93f)

### Version

0.10.19

### Steps to Reproduce

```
llama-index                              0.10.19
llama-index-agent-openai                 0.1.5
llama-index-cli                          0.1.7
llama-index-core                         0.10.19
llama-index-embeddings-huggingface       0.1.4
llama-index-embeddings-openai            0.1.6
llama-index-indices-managed-llama-cloud  0.1.3
llama-index-legacy                       0.9.48
llama-index-llms-openai                  0.1.7
llama-index-llms-replicate               0.1.3
llama-index-multi-modal-llms-openai      0.1.4
llama-index-program-openai               0.1.4
llama-index-question-gen-openai          0.1.3
llama-index-readers-file                 0.1.7
llama-index-readers-llama-parse          0.1.3
llama-index-vector-stores-chroma         0.1.5
```

Run the code 
```
from llama_hub.tools.tavily_research import TavilyToolSpec
from llama_index.agent import OpenAIAgent
import os
BASE_URL = " https://chat.****.****/v1"                   # 设置代理
API_SECRET_KEY="sk-1NA1mSaHKprafQ7r27Ca37A74eBc4786******" # 设置api-key
os.environ["OPENAI_API_KEY"]  =  API_SECRET_KEY
os.environ["OPENAI_API_BASE"] =  BASE_URL
tavily_tool = TavilyToolSpec(
    api_key='tvly-dHbDutyoi5iyCOWopGTb******',
)
agent = OpenAIAgent.from_tools(tavily_tool.to_tool_list())

agent.chat('Please introduce the city of shanghai')

```

**Comment by anoopshrma** [comment]
Hey! You have posted your openai key. I would highly suggest you remove it!

**Comment by anoopshrma** [comment]
Llamahub is deprecated. All the loaders/tools have been converted into separate pypi packages. 

You'll need to install tavily with `pip install llama-index-tools-tavily-research` 
Then you can import it with 
`from llama_index.tools.tavily_reasearch import TavilyToolSpec`

**Comment by HelloEveryonehh** [comment]
> Llamahub is deprecated. All the loaders/tools have been converted into separate pypi packages.
> 
> You'll need to install tavily with `pip install llama-index-tools-tavily-research` Then you can import it with `from llama_index.tools.tavily_reasearch import TavilyToolSpec`

Thank you for your answer

**Comment by JYC0413** [comment]
> Llamahub is deprecated. All the loaders/tools have been converted into separate pypi packages.
> 
> You'll need to install tavily with `pip install llama-index-tools-tavily-research` Then you can import it with `from llama_index.tools.tavily_reasearch import TavilyToolSpec`

Actually it doesn't matter, but I'm going to correct you, it's spelled wrong
`from llama_index.tools.tavily_reasearch import TavilyToolSpec`
