### ISSUE TITLE
[Bug]: `event_pairs` is empty when debugging

### ISSUE THREAD

**Issue by superb-owl** [run-llama/llama_index#11973]
### Bug Description

When I enable debugging [per the docs](https://docs.llamaindex.ai/en/latest/examples/callbacks/LlamaDebugHandler.html), I'm unable to access any of the debug info. `get_event_time_info` throws a division by zero error, and `get_llm_inputs_outputs` returns an empty list.

### Version

0.10.19

### Steps to Reproduce

Here's my script:
```python
❯ cat ingest.py
import os

from llama_index.core import VectorStoreIndex, StorageContext, load_index_from_storage
from llama_index.core.storage.docstore import SimpleDocumentStore
from llama_index.core.vector_stores import SimpleVectorStore
from llama_index.readers.github import GithubRepositoryReader, GithubClient
from llama_index.core.callbacks import (
    CallbackManager,
    LlamaDebugHandler,
    CBEventType,
)

persistence_dir = "index"

github_token = os.getenv("GITHUB_TOKEN")
owner = "kubernetes"
repo = "kubernetes"
branch = "master"

llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])

if os.getenv("RELOAD_INDEX") == "true":
    github_client = GithubClient(os.getenv("GITHUB_TOKEN"))

    print("getting docs")
    documents = GithubRepositoryReader(
        github_client,
        owner=owner,
        repo=repo,
        use_parser=False,
        verbose=False,
    ).load_data(branch=branch)

    print("creating vector store")
    index = VectorStoreIndex.from_documents(documents, callback_manager=callback_manager)

    print("persisting index")
    index.storage_context.persist(persist_dir=persistence_dir)
else:
    print("loading index")
    storage_context = StorageContext.from_defaults(persist_dir=persistence_dir)
    print("building index")
    index = load_index_from_storage(storage_context, callback_manager=callback_manager)


print("building engine")
query_engine = index.as_query_engine()

print("sending query")
response = query_engine.query(
    "what podcast fields does it parse?"
)
llama_debug.flush_event_logs()

print(response)

print("\n\n=======\nDEBUG\n=======\n\n")
print(llama_debug.get_event_time_info(CBEventType.LLM))

print()
event_pairs = llama_debug.get_llm_inputs_outputs()
print("event pairs", event_pairs)
print()
print(event_pairs[0][0])
print()
print(event_pairs[0][1].payload.keys())
print()
print(event_pairs[0][1].payload["response"])
print()
```

Output is
```bash
❯ python ingest.py
loading index
building index
**********
Trace: index_construction
**********
building engine
sending query
The podcast fields that are parsed include title, link, description, pubDate, guid, itunes:subtitle, itunes:summary, itunes:author, itunes:explicit, itunes:duration, itunes:keywords, itunes:image, media:content, and enclosure.


=======
DEBUG
=======


Traceback (most recent call last):
  File "/home/git/llama-index/ingest.py", line 59, in <module>
    print(llama_debug.get_event_time_info(CBEventType.LLM))
  File "/home/miniforge/lib/python3.9/site-packages/llama_index/core/callbacks/llama_debug.py", line 149, in get_event_time_info
    return self._get_time_stats_from_event_pairs(event_pairs)
  File "/home/miniforge/lib/python3.9/site-packages/llama_index/core/callbacks/llama_debug.py", line 128, in _get_time_stats_from_event_pairs
    average_secs=total_secs / len(event_pairs),
ZeroDivisionError: float division by zero
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/git/llama-index/ingest.py", line 59, in <module>
    print(llama_debug.get_event_time_info(CBEventType.LLM))
  File "/home/miniforge/lib/python3.9/site-packages/llama_index/core/callbacks/llama_debug.py", line 149, in get_event_time_info
    return self._get_time_stats_from_event_pairs(event_pairs)
  File "/home/miniforge/lib/python3.9/site-packages/llama_index/core/callbacks/llama_debug.py", line 128, in _get_time_stats_from_event_pairs
    average_secs=total_secs / len(event_pairs),
ZeroDivisionError: float division by zero
```

**Comment by qsdhj** [comment]
Hi, 

I tried the [ Llama Debug Handler Notebook](https://docs.llamaindex.ai/en/stable/examples/callbacks/LlamaDebugHandler/) with my OpenAI Key. 
There the implementation is also broken.
