### ISSUE TITLE
[Question]: How do I upsert an IndexNode schema to Pinecone index? 

### ISSUE THREAD

**Issue by antoineross** [run-llama/llama_index#12006]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

HI! I amtrying to upsert an IndexNode schema directly into my pinecone index but get an error can I get some help? 

Here's my code:

```# Simple Directory Reader creates Document classes per page
filename = "10k-132"
hierarchy_docs = SimpleDirectoryReader( 
                                    #input_files=["documents/Ethical_Hacking_RHartleyTeachingStudents.pdf"]
                                    #input_dir="../documents"
                                    input_files=[f"documents/{filename}.pdf"]
                                  ).load_data() 
# We call our sentence splitter
node_parser = SentenceSplitter(chunk_size=512)
base_nodes = node_parser.get_nodes_from_documents(hierarchy_docs)

for idx, node in enumerate(base_nodes):
    node.id_ = f"node-{idx}"

# ------------------------- Build a graph of smaller chunks pointing to bigger parent chunks ----------------------------------------- #
sub_chunk_sizes = [128, 256, 512]
sub_node_parsers = [
    SentenceSplitter(chunk_size=c, chunk_overlap=20) for c in sub_chunk_sizes
]

all_nodes = []
for base_node in base_nodes:
    for n in sub_node_parsers:
        sub_nodes = n.get_nodes_from_documents([base_node])
        sub_inodes = [
            IndexNode.from_text_node(sn, base_node.node_id) for sn in sub_nodes
        ]
        all_nodes.extend(sub_inodes)

    # also add original node to node
    original_node = IndexNode.from_text_node(base_node, base_node.node_id)
    all_nodes.append(original_node)

# all_nodes_dict = {n.node_id: n for n in all_nodes}
# ------------------------- Generate Embeddings ----------------------------------------- #
# all_metadata = []
# for node in all_nodes:
#     all_metadata.append(node.metadata)

# # Save all the metadata in a single JSON file
# with open(f"llamaindex-output/{filename}.json", "w") as f:
#     json.dump(all_metadata, f)

embed_model = OpenAIEmbedding(model="text-embedding-3-large")
for node in all_nodes:
    node_embedding = embed_model.get_text_embedding_batch(
        node.get_content(metadata_mode="all")
        )
    node.embedding = node_embedding

vector_store = PineconeVectorStore(pinecone_index=pinecone_index, namespace="llama-index-chunking")
vector_store.add(all_nodes)
```
—-
Then this is the error I am getting:
```
Traceback (most recent call last):
  File "/Users/antoineross/Desktop/Developer/FV2023/Jack-HackerGPT/hackergpt-rag/ingest/llama_chunking.py", line 86, in <module>
    node.embedding = node_embedding
    ^^^^^^^^^^^^^^
  File "/Users/antoineross/miniconda3/envs/llamaindex/lib/python3.11/site-packages/pydantic/v1/main.py", line 384, in __setattr__
    raise ValidationError([error_], self.__class__)
pydantic.v1.error_wrappers.ValidationError: 194 validation errors for IndexNode
embedding -> 0
  value is not a valid float (type=type_error.float)
embedding -> 1
  value is not a valid float (type=type_error.float)
embedding -> 2
  value is not a valid float (type=type_error.float)
embedding -> 3
  value is not a valid float (type=type_error.float)
embedding -> 4
  value is not a valid float (type=type_error.float)
embedding -> 5
  value is not a valid float (type=type_error.float)
embedding -> 6
  value is not a valid float (type=type_error.float)
```

**Comment by antoineross** [comment]
Figured out the issue is that I am passing in a node to a "batch" function of "get_text_embedding".

How should I format my code instead so that it batches it?

**Comment by antoineross** [comment]
Figured it out. Closing this.
