### ISSUE TITLE
[Bug]: github reader quickstart throws error

### ISSUE THREAD

**Issue by michael-berk** [run-llama/llama_index#12019]
### Bug Description

When running the GithubReader MVP, there is a key error. Also, the [demo](https://docs.llamaindex.ai/en/stable/examples/data_connectors/GithubRepositoryReaderDemo.html) needs to be updated to leverage the github client.

### Version

0.10.20

### Steps to Reproduce

```python
# Example gihub repo reader
# %pip install llama-index-readers-github llama-index nest_asyncio httpx
# %env OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# %env GITHUB_TOKEN=github_pat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

import nest_asyncio
nest_asyncio.apply() 

from llama_index.core import VectorStoreIndex
from llama_index.readers.github import GithubRepositoryReader
from llama_index.readers.github.repository.github_client import GithubClient
import os

owner = "jerryjliu"
repo = "llama_index"
branch = "main"

github_client = GithubClient(github_token=os.environ["GITHUB_TOKEN"], verbose=True)
reader = GithubRepositoryReader(github_client=github_client, repo="repo",owner="owner")
reader.load_data(branch="branch") # throws
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/michael.berk/dev/mlflow/llama_index/testing/github_reader.py", line 123, in <module>
    load_data_from_branch()
  File "/Users/michael.berk/dev/mlflow/llama_index/testing/github_reader.py", line 72, in wrapper
    func(*args, **kwargs)
  File "/Users/michael.berk/dev/mlflow/llama_index/testing/github_reader.py", line 117, in load_data_from_branch
    documents = reader1.load_data(branch="main")
  File "/Users/michael.berk/opt/anaconda3/envs/1-dev/lib/python3.10/site-packages/llama_index/readers/github/repository/base.py", line 299, in load_data
    return self._load_data_from_branch(branch)
  File "/Users/michael.berk/opt/anaconda3/envs/1-dev/lib/python3.10/site-packages/llama_index/readers/github/repository/base.py", line 259, in _load_data_from_branch
    branch_data: GitBranchResponseModel = self._loop.run_until_complete(
  File "/Users/michael.berk/opt/anaconda3/envs/1-dev/lib/python3.10/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/Users/michael.berk/opt/anaconda3/envs/1-dev/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/michael.berk/opt/anaconda3/envs/1-dev/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/Users/michael.berk/opt/anaconda3/envs/1-dev/lib/python3.10/site-packages/llama_index/readers/github/repository/github_client.py", line 361, in get_branch
    return GitBranchResponseModel.from_json(
  File "/Users/michael.berk/opt/anaconda3/envs/1-dev/lib/python3.10/site-packages/dataclasses_json/api.py", line 63, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
  File "/Users/michael.berk/opt/anaconda3/envs/1-dev/lib/python3.10/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/Users/michael.berk/opt/anaconda3/envs/1-dev/lib/python3.10/site-packages/dataclasses_json/core.py", line 172, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'commit'
```

Details
* dataclasses-json version: 0.6.4
* This also fails: https://github.com/run-llama/llama_index/blob/5c53f41712785e5558156372bdc4f33a6326fa5f/llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/base.py#L537
```

**Comment by logan-markewich** [comment]
If you change the repo to `run-llama` instead of `jerryliu` it works, otherwise you get a `301 response, moved`

**Comment by sivanola** [comment]
I'm getting the same error. I changed owner to `run-llama`, I updated llama-index to version 0.10.22, I tried to read langchain repo, and that one worked. I used the same settings for both. I tried some other repos and I got mixed results. For some it works okay, for others I get that error.

**Comment by victormimo** [comment]
Same thing here.

I got the `KeyError: 'commit'` as well as `KeyError: 'url'` for a different repo

**Comment by lucasbemol** [comment]
Same error here
`KeyError: 'url'`

**Comment by david1542** [comment]
Same error for me. `KeyError: 'url'`. The function fails at this point (in `llama_index/readers/github/repository/github_client.py)`:

```python
        response = (
            await self.request(
                "getTree",
                "GET",
                owner=owner,
                repo=repo,
                tree_sha=tree_sha,
                timeout=timeout,
                retries=retries,
            )
        ).text
        return GitTreeResponseModel.from_json(response)
```

The error was thrown at the `GitTreeResponseModel.from_json(response)`.  Looks like the reason is that the repository I'm trying to ingest has submodules in it, which creates tree items without the `url` property.

 I managed to bypass this by overriding the original implementation with this implementation:
```python
root = (
            await self._github_client.request(
                "getTree",
                "GET",
                owner=owner,
                repo=repo,
                tree_sha=tree_sha,
                timeout=timeout,
                retries=retries,
            )
        ).json()
        root["tree"] = [path for path in root["tree"] if path.get("url") is not None]
        return GitTreeResponseModel.from_json(json.dumps(root))
```

If anyone wants add a fix to this function that'd be great!

**Comment by brk21** [comment]
There is a similar problem occurring with the following snippet at approximately 364 in github_client.py. It only impacts a subset of the repos I am attempting to pull.

After fiddling with it, I eventually defaulted to just cloning the repo and using the simple directory reader. I don't know if it's the stability of the GitHub API that's driving this or something else, but I'm moving on. 

```python
return GitBranchResponseModel.from_json(
            (
                await self.request(
                    "getBranch",
                    "GET",
                    owner=owner,
                    repo=repo,
                    branch=branch,
                    timeout=timeout,
                    retries=retries,
                )
            ).text
        )
```
