### ISSUE TITLE
[Bug]: PandasQueryEngine unable to deal with pandas functions within the query

### ISSUE THREAD

**Issue by chilicrabcakes** [run-llama/llama_index#12239]
### Bug Description

The PandasQueryEngine does not work if the LLM-generated query contains pandas functions, such as _pd.to_datetime()_ or _pd.get_dummies()_. It throws a 'pd is not defined' error. 

<img width="1041" alt="image" src="https://github.com/run-llama/llama_index/assets/25214379/a2aed2b2-b04a-4b95-b0cb-5d8b1024e2c9">

### Version

0.10.23

### Steps to Reproduce

```
from llama_index.llms.openai import OpenAI

llm = OpenAI(model="gpt-3.5-turbo", api_key="BAD_KEY")

import pandas as pd
df = pd.DataFrame(
    {
        "date": ["Mar 1st, 2020", "Dec 1st, 2020", "Apr 1st, 2021"],
        "revenue": [2930000, 13960000, 3645000],
        "classes": [1, 2, 1]
    }
)

query_engine = PandasQueryEngine(llm=llm, df=df, verbose=True, synthesize_response=True)
response = query_engine.query(
    "Create a one-hot encoding for the 'classes' column",
)
```

### Relevant Logs/Tracbacks

```shell
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
> Pandas Instructions:

pd.get_dummies(df, columns=['classes'])
```
> Pandas Output: There was an error running the output as Python code. Error message: name 'pd' is not defined
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/envs/datascience/lib/python3.9/site-packages/llama_index/core/query_engine/pandas/output_parser.py", line 53, in default_output_processor
    output_str = str(safe_eval(module_end_str, {"np": np}, local_vars))
  File "/usr/local/Caskroom/miniforge/base/envs/datascience/lib/python3.9/site-packages/llama_index/core/exec_utils.py", line 140, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
  File "<string>", line 1, in <module>
NameError: name 'pd' is not defined
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
```

**Comment by chilicrabcakes** [comment]
Have added a fix in PandasQueryEngine. PR is here: https://github.com/run-llama/llama_index/pull/12240, waiting for approval
