### ISSUE TITLE
[Bug]: `Neo4jVectorStore` doesn't seem to respect `embedding_dimension` -- it's pinned to 1536

### ISSUE THREAD

**Issue by tslmy** [run-llama/llama_index#12266]
### Bug Description

I `Neo4jVectorStore` to store my `VectorStoreIndex`. Although I explicitly set `embedding_dimension=1000` in its constructor, when I try to invoke `VectorStoreIndex.as_query_engine().query(...)`, I see that Neo4j complaining about a mismatch between the dimensionalities:

> Index query vector has 384 dimensions, but indexed vectors have 1536.

(384 is the dimensionality of the embedding model when I set `Settings.embed_model = "local"`.)

_This is a rewrite of #12195, #12221, and #12193._

### Version

3878c5038322b289e6cb78dc31354b3a5645c441

### Steps to Reproduce

Script is in this [GitHub gist](https://gist.github.com/tslmy/f673779dd5bccfb454c9dd7da239be3a).

### Relevant Logs/Tracbacks

```shell
File "...neo4j/_sync/io/_common.py", line 245, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `db.index.vector.queryNodes`: Caused by: java.lang.IllegalArgumentException: Index query vector has 384 dimensions, but indexed vectors have 1536.}
Exception ignored in: <function Driver.__del__ at 0x32b028a60>
Traceback (most recent call last):
  File "...neo4j/_sync/driver.py", line 489, in __del__
  File "...neo4j/_meta.py", line 229, in unclosed_resource_warn
TypeError: 'NoneType' object is not callable
```
```

**Comment by tslmy** [comment]
@dosu-bot, nope. I deleted all nodes in that database (`MATCH (n) DETACH DELETE n`), and re-ran the script, and yet I still see the same error. I really think there's a bug in it, but my neo4j-fu is too rusty to be useful there.

**Comment by tslmy** [comment]
@dosu-bot, you're repeating yourself. Please learn from this and don't do that again. When you run out of things to say, just say you don't have more ideas.
