### ISSUE TITLE
[Bug]: cannot download any Packs via llamaindex-cli and download_llama_pack

### ISSUE THREAD

**Issue by kun432** [run-llama/llama_index#12274]
### Bug Description

I tried to download SelfRAGPack via both llamaindex-cli and download_llama_pack but it failed to download.

```
!llamaindex-cli download-llamapack SelfRAGPack --download-dir ./self_rag_pack
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/download/utils.py", line 109, in recursive_tree_traverse
    tree_elements = res.json()["payload"]["tree"]["items"]
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 7 column 1 (char 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/llamaindex-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/llama_index/cli/command_line.py", line 276, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/cli/command_line.py", line 187, in <lambda>
    func=lambda args: handle_download_llama_pack(**vars(args))
  File "/usr/local/lib/python3.10/dist-packages/llama_index/cli/command_line.py", line 39, in handle_download_llama_pack
    download_llama_pack(
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/llama_pack/download.py", line 56, in download_llama_pack
    pack_cls = download_llama_pack_template(
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/download/pack.py", line 115, in download_llama_pack_template
    download_module_and_reqs(
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/download/pack.py", line 52, in download_module_and_reqs
    source_files = get_source_files_recursive(
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/download/utils.py", line 136, in get_source_files_recursive
    return recursive_tree_traverse(initial_tree_urls, [], source_tree_url)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/download/utils.py", line 111, in recursive_tree_traverse
    raise ValueError("Failed to traverse github tree source.")
ValueError: Failed to traverse github tree source.
```

```python
from llama_index.core.llama_pack import download_llama_pack

SelfRAGPack = download_llama_pack("SelfRAGPack", "./self_rag_pack")
```

```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/requests/models.py](https://localhost:8080/#) in json(self, **kwargs)
    970         try:
--> 971             return complexjson.loads(self.text, **kwargs)
    972         except JSONDecodeError as e:

10 frames
JSONDecodeError: Expecting value: line 7 column 1 (char 6)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
JSONDecodeError: Expecting value: line 7 column 1 (char 6)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_index/core/download/utils.py](https://localhost:8080/#) in recursive_tree_traverse(tree_urls, acc, source_tree_url)
    109             tree_elements = res.json()["payload"]["tree"]["items"]
    110         except Exception:
--> 111             raise ValueError("Failed to traverse github tree source.")
    112 
    113         new_trees = [

ValueError: Failed to traverse github tree source.
```

Also, tried to download some other Packs:
- VoyageQueryEnginePack
- OllamaQueryEnginePack
- RaptorPack

all failed with the same error.

### Version

llama-index==0.10.23 llama-index-agent-openai==0.1.7 llama-index-cli==0.1.11 llama-index-core==0.10.23.post1 llama-index-embeddings-openai==0.1.7 llama-index-indices-managed-llama-cloud==0.1.5 llama-index-legacy==0.9.48 llama-index-llms-openai==0.1.12 llama-index-multi-modal-llms-openai==0.1.4 llama-index-program-openai==0.1.4 llama-index-question-gen-openai==0.1.3 llama-index-readers-file==0.1.12 llama-index-readers-llama-parse==0.1.4 llama-parse==0.4.0 llamaindex-py-client==0.1.13

### Steps to Reproduce

create a fresh environment with Colab or local Jupyter.

```
!pip install llama-index
```

then download packs.

```
!llamaindex-cli download-llamapack SelfRAGPack --download-dir ./self_rag_pack
```

or 

```python
from llama_index.core.llama_pack import download_llama_pack

SelfRAGPack = download_llama_pack("SelfRAGPack", "./self_rag_pack")
```

**Comment by cbornet** [comment]
This is due to a change in GitHub API. #12273 fixes this issue.
