### ISSUE TITLE
Critical bug in `llama-index-embeddings-huggingface==0.1.5` from ~10 minutes ago

### ISSUE THREAD

**Issue by tomaarsen** [run-llama/llama_index#12281]
#11939 has introduced a critical bug in `HuggingFaceEmbedding`:

```python
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

embed_model = HuggingFaceEmbedding()
```
```
Traceback (most recent call last):
  File "[sic]\demo.py", line 10, in <module>
    embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5", query_instruction="Represent the query as a text sequence for retrieval: ")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[sic]\llama_index\embeddings\huggingface\base.py", line 83, in __init__ 
    model = AutoModel.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[sic]\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[sic]\transformers\modeling_utils.py", line 3404, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BertModel.__init__() got an unexpected keyword argument 'safe_serialization'
```

See more info in #12277. Please revert this PR - `AutoModel.from_pretrained` does not accept a `safe_serialization` parameter.

#12255 has triggered a new release with this change, so the latest version is now breaking.

@logan-markewich @hatianzhang

_Originally posted by @tomaarsen in https://github.com/run-llama/llama_index/issues/11939#issuecomment-2020853800_

- Tom Aarsen

**Comment by tomaarsen** [comment]
Fixed via #12277
