### ISSUE TITLE
[Bug]: KeyError: 'plugin_config' with TensorRT-LLM 

### ISSUE THREAD

**Issue by teis-e** [run-llama/llama_index#12317]
### Bug Description

Running TensorLLM object:

```
from llama_index.llms.nvidia_tensorrt import LocalTensorRTLLM

llm = LocalTensorRTLLM(
    model_path="./model",
    engine_name="rank0.engine",
    tokenizer_dir="/root/.cache/huggingface/hub/models--Qwen--Qwen1.5-72B-Chat-GPTQ-Int4/snapshots/>
    completion_to_prompt=completion_to_prompt,
    verbose=True,
    max_new_tokens=640,
    temperature=0
)
```
Results in:

```
[TensorRT-LLM] TensorRT-LLM version: 0.8.0Traceback (most recent call last):
  File "/opt/tritonserver/ai.py", line 76, in <module>
    llm = LocalTensorRTLLM(
  File "/usr/local/lib/python3.10/dist-packages/llama_index/llms/nvidia_tensorrt/base.py", line 109, in __init__
    use_gpt_attention_plugin = config["plugin_config"][
KeyError: 'plugin_config'
```

### Version

0.10.23

### Steps to Reproduce

Run the bug description

**Comment by wuchaowei2012** [comment]
cannot use other models besides gpt2, and gpt2 is not a very good llm model.
