### ISSUE TITLE
[Bug]: Issue loading PDF data using PDFReader.load_data

### ISSUE THREAD

**Issue by MCarterSky** [run-llama/llama_index#12382]
### Bug Description

Attempted to load a pdf file into project using:

pdf = PDFReader().load_data(file="data/document.pdf")

Received an error, Identified that lines 56 and 74 in the base.py file had "file.name" when it should be "file"

### Version

0.10.25

### Steps to Reproduce

Attempt to read a PDF file into a project using the following module:

`from llama_index.readers.file import PDFReader
`

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/mct20/code/personal/agent_ai/main.py", line 9, in <module>
    from pdf import uk_engine
  File "/Users/mct20/code/personal/agent_ai/pdf.py", line 18, in <module>
    uk_pdf = PDFReader().load_data(file="data/United_Kingdom.pdf")
  File "/Users/mct20/Library/Caches/pypoetry/virtualenvs/agent-ai--ZHwPXvl-py3.10/lib/python3.10/site-packages/llama_index/readers/file/docs/base.py", line 74, in load_data
    metadata = {"page_label": page_label, "file_name": file.name}
AttributeError: 'str' object has no attribute 'name'
```

**Comment by logan-markewich** [comment]
@MCarterSky the PDF reader expects a path object on input

```
from pathlib import Path

reader.load_data(Path(filepath))
```

**Comment by logan-markewich** [comment]
(Good bot 🤖 )
