### ISSUE TITLE
[Bug]: Qdrant SparseVector won't work (root:Batch upload failed) when we use Qdrant on Docker.

### ISSUE THREAD

**Issue by kevin-tofu** [run-llama/llama_index#12397]
### Bug Description

Attempted to run example in this article.
https://docs.llamaindex.ai/en/stable/examples/vector_stores/qdrant_hybrid/

It looks working fine.
But an error happens when I changed Qdrant Local client to Qdrant docker container.

### Version
llama-index = "0.10.15"
llama-index-vector-stores-qdrant = "^0.1.4"
qdrant-client = "1.7.1"
Qdrant Docker Container: latest

### Version

0.10.15

### Steps to Reproduce

* Copy and paste code on this article,
https://docs.llamaindex.ai/en/stable/examples/vector_stores/qdrant_hybrid/

* Run Qdrant on docker

* and then, change qdrant client to
client = QdrantClient(host="localhost",port="6333")

### Relevant Logs/Tracbacks

```shell
WARNING:root:Batch upload failed 1 times. Retrying...
WARNING:root:Batch upload failed 2 times. Retrying...
WARNING:root:Batch upload failed 3 times. Retrying...

self._upload_collection(
  File "/test/.venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 2257, in _upload_collection
    for _ in updater.process(batches_iterator):
  File "/test/.venv/lib/python3.10/site-packages/qdrant_client/uploader/rest_uploader.py", line 75, in process
    yield upload_batch(
  File "/test/.venv/lib/python3.10/site-packages/qdrant_client/uploader/rest_uploader.py", line 41, in upload_batch
    raise e
  File "/test/.venv/lib/python3.10/site-packages/qdrant_client/uploader/rest_uploader.py", line 32, in upload_batch
    openapi_client.points_api.upsert_points(
  File "/test/.venv/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 1443, in upsert_points
    return self._build_for_upsert_points(
  File "/test/.venv/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 742, in _build_for_upsert_points
    return self.api_client.request(
  File "/test/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
    return self.send(request, type_)
  File "/test/.venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 97, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Format error in JSON body: data did not match any variant of untagged enum VectorStruct at line 1 column 14771"},"time":0.0}'


Log in Qdrant
"PUT /collections/llama2_paper/points?wait=true HTTP/1.1" 400 142 "-" "python-httpx/0.27.0" 0.000295
```

**Comment by Saummya** [comment]
Trying to run example in this article.
[qdrant_hybrid](https://docs.llamaindex.ai/en/stable/examples/vector_stores/qdrant_hybrid/)
```
from llama_index.core import VectorStoreIndex, StorageContext
from llama_index.core import Settings
from llama_index.vector_stores.qdrant import QdrantVectorStore
from qdrant_client import QdrantClient
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

from llama_index.core import SimpleDirectoryReader
documents = SimpleDirectoryReader("./data1/").load_data()


# creates a persistant index to disk
client = QdrantClient(url="http://localhost:6333")

vector_store = QdrantVectorStore(
    "llama2_paper", client=client, enable_hybrid=True, batch_size=20
)

storage_context = StorageContext.from_defaults(vector_store=vector_store)
Settings.chunk_size = 512

index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)


```

ERROR:

```
---------------------------------------------------------------------------
UnexpectedResponse                        Traceback (most recent call last)
Cell In[4], line 14
     11 storage_context = StorageContext.from_defaults(vector_store=vector_store)
     12 Settings.chunk_size = 512
---> 14 index = VectorStoreIndex.from_documents(
     15     documents,
     16     storage_context=storage_context,
     17 )

File /lib/python3.8/site-packages/llama_index/core/indices/base.py:145, in BaseIndex.from_documents(cls, documents, storage_context, show_progress, callback_manager, transformations, service_context, **kwargs)
    136     docstore.set_document_hash(doc.get_doc_id(), doc.hash)
    138 nodes = run_transformations(
    139     documents,  # type: ignore
    140     transformations,
    141     show_progress=show_progress,
    142     **kwargs,
    143 )
--> 145 return cls(
    146     nodes=nodes,
    147     storage_context=storage_context,
    148     callback_manager=callback_manager,
    149     show_progress=show_progress,
    150     transformations=transformations,
    151     service_context=service_context,
    152     **kwargs,
    153 )

File /lib/python3.8/site-packages/llama_index/core/indices/vector_store/base.py:75, in VectorStoreIndex.__init__(self, nodes, use_async, store_nodes_override, embed_model, insert_batch_size, objects, index_struct, storage_context, callback_manager, transformations, show_progress, service_context, **kwargs)
     68 self._embed_model = (
     69     resolve_embed_model(embed_model, callback_manager=callback_manager)
     70     if embed_model
     71     else embed_model_from_settings_or_context(Settings, service_context)
     72 )
     74 self._insert_batch_size = insert_batch_size
---> 75 super().__init__(
     76     nodes=nodes,
     77     index_struct=index_struct,
     78     service_context=service_context,
     79     storage_context=storage_context,
     80     show_progress=show_progress,
     81     objects=objects,
     82     callback_manager=callback_manager,
     83     transformations=transformations,
     84     **kwargs,
     85 )

File /lib/python3.8/site-packages/llama_index/core/indices/base.py:94, in BaseIndex.__init__(self, nodes, objects, index_struct, storage_context, callback_manager, transformations, show_progress, service_context, **kwargs)
     92 if index_struct is None:
     93     nodes = nodes or []
---> 94     index_struct = self.build_index_from_nodes(
     95         nodes + objects  # type: ignore
     96     )
     97 self._index_struct = index_struct
     98 self._storage_context.index_store.add_index_struct(self._index_struct)

File /lib/python3.8/site-packages/llama_index/core/indices/vector_store/base.py:308, in VectorStoreIndex.build_index_from_nodes(self, nodes, **insert_kwargs)
    300 if any(
    301     node.get_content(metadata_mode=MetadataMode.EMBED) == "" for node in nodes
    302 ):
    303     raise ValueError(
    304         "Cannot build index from nodes with no content. "
    305         "Please ensure all nodes have content."
    306     )
--> 308 return self._build_index_from_nodes(nodes, **insert_kwargs)

File /lib/python3.8/site-packages/llama_index/core/indices/vector_store/base.py:280, in VectorStoreIndex._build_index_from_nodes(self, nodes, **insert_kwargs)
    278     run_async_tasks(tasks)
    279 else:
--> 280     self._add_nodes_to_index(
    281         index_struct,
    282         nodes,
    283         show_progress=self._show_progress,
    284         **insert_kwargs,
    285     )
    286 return index_struct

File /lib/python3.8/site-packages/llama_index/core/indices/vector_store/base.py:234, in VectorStoreIndex._add_nodes_to_index(self, index_struct, nodes, show_progress, **insert_kwargs)
    232 for nodes_batch in iter_batch(nodes, self._insert_batch_size):
    233     nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
--> 234     new_ids = self._vector_store.add(nodes_batch, **insert_kwargs)
    236     if not self._vector_store.stores_text or self._store_nodes_override:
    237         # NOTE: if the vector store doesn't store text,
    238         # we need to add the nodes to the index struct and document store
    239         for node, new_id in zip(nodes_batch, new_ids):
    240             # NOTE: remove embedding from node to avoid duplication

File /lib/python3.8/site-packages/llama_index/vector_stores/qdrant/base.py:256, in QdrantVectorStore.add(self, nodes, **add_kwargs)
    249     self._create_collection(
    250         collection_name=self.collection_name,
    251         vector_size=len(nodes[0].get_embedding()),
    252     )
    254 points, ids = self._build_points(nodes)
--> 256 self._client.upload_points(
    257     collection_name=self.collection_name,
    258     points=points,
    259     batch_size=self.batch_size,
    260     parallel=self.parallel,
    261     max_retries=self.max_retries,
    262     wait=True,
    263 )
    265 return ids

File /lib/python3.8/site-packages/qdrant_client/qdrant_client.py:1907, in QdrantClient.upload_points(self, collection_name, points, batch_size, parallel, method, max_retries, wait, shard_key_selector, **kwargs)
   1882 """Upload points to the collection
   1883 
   1884 Similar to `upload_collection` method, but operates with points, rather than vector and payload individually.
   (...)
   1903 
   1904 """
   1905 assert len(kwargs) == 0, f"Unknown arguments: {list(kwargs.keys())}"
-> 1907 return self._client.upload_points(
   1908     collection_name=collection_name,
   1909     points=points,
   1910     batch_size=batch_size,
   1911     parallel=parallel,
   1912     method=method,
   1913     max_retries=max_retries,
   1914     wait=wait,
   1915     shard_key_selector=shard_key_selector,
   1916 )

File /lib/python3.8/site-packages/qdrant_client/qdrant_remote.py:2380, in QdrantRemote.upload_points(self, collection_name, points, batch_size, parallel, method, max_retries, wait, shard_key_selector, **kwargs)
   2364 def upload_points(
   2365     self,
   2366     collection_name: str,
   (...)
   2374     **kwargs: Any,
   2375 ) -> None:
   2376     batches_iterator = self._updater_class.iterate_records_batches(
   2377         records=points, batch_size=batch_size
   2378     )
-> 2380     self._upload_collection(
   2381         batches_iterator=batches_iterator,
   2382         collection_name=collection_name,
   2383         max_retries=max_retries,
   2384         parallel=parallel,
   2385         method=method,
   2386         wait=wait,
   2387         shard_key_selector=shard_key_selector,
   2388     )

File /lib/python3.8/site-packages/qdrant_client/qdrant_remote.py:2332, in QdrantRemote._upload_collection(self, batches_iterator, collection_name, max_retries, parallel, method, wait, shard_key_selector)
   2330 if parallel == 1:
   2331     updater = self._updater_class.start(**updater_kwargs)
-> 2332     for _ in updater.process(batches_iterator):
   2333         pass
   2334 else:

File /lib/python3.8/site-packages/qdrant_client/uploader/rest_uploader.py:81, in RestBatchUploader.process(self, items)
     79 def process(self, items: Iterable[Any]) -> Generator[bool, None, None]:
     80     for batch in items:
---> 81         yield upload_batch(
     82             self.openapi_client,
     83             self.collection_name,
     84             batch,
     85             shard_key_selector=self._shard_key_selector,
     86             max_retries=self.max_retries,
     87             wait=self._wait,
     88         )

File /lib/python3.8/site-packages/qdrant_client/uploader/rest_uploader.py:47, in upload_batch(openapi_client, collection_name, batch, max_retries, shard_key_selector, wait)
     44         logging.warning(f"Batch upload failed {attempt + 1} times. Retrying...")
     46         if attempt == max_retries - 1:
---> 47             raise e
     48 return True

File /lib/python3.8/site-packages/qdrant_client/uploader/rest_uploader.py:37, in upload_batch(openapi_client, collection_name, batch, max_retries, shard_key_selector, wait)
     35 for attempt in range(max_retries):
     36     try:
---> 37         openapi_client.points_api.upsert_points(
     38             collection_name=collection_name,
     39             point_insert_operations=PointsList(points=points, shard_key=shard_key_selector),
     40             wait=wait,
     41         )
     42         break
     43     except Exception as e:

File /lib/python3.8/site-packages/qdrant_client/http/api/points_api.py:1439, in SyncPointsApi.upsert_points(self, collection_name, wait, ordering, point_insert_operations)
   1429 def upsert_points(
   1430     self,
   1431     collection_name: str,
   (...)
   1434     point_insert_operations: m.PointInsertOperations = None,
   1435 ) -> m.InlineResponse2007:
   1436     """
   1437     Perform insert + updates on points. If point with given ID already exists - it will be overwritten.
   1438     """
-> 1439     return self._build_for_upsert_points(
   1440         collection_name=collection_name,
   1441         wait=wait,
   1442         ordering=ordering,
   1443         point_insert_operations=point_insert_operations,
   1444     )

File /lib/python3.8/site-packages/qdrant_client/http/api/points_api.py:738, in _PointsApi._build_for_upsert_points(self, collection_name, wait, ordering, point_insert_operations)
    736 if "Content-Type" not in headers:
    737     headers["Content-Type"] = "application/json"
--> 738 return self.api_client.request(
    739     type_=m.InlineResponse2007,
    740     method="PUT",
    741     url="/collections/{collection_name}/points",
    742     headers=headers if headers else None,
    743     path_params=path_params,
    744     params=query_params,
    745     content=body,
    746 )

File /lib/python3.8/site-packages/qdrant_client/http/api_client.py:76, in ApiClient.request(self, type_, method, url, path_params, **kwargs)
     74     kwargs["timeout"] = int(kwargs["params"]["timeout"])
     75 request = self._client.build_request(method, url, **kwargs)
---> 76 return self.send(request, type_)

File /lib/python3.8/site-packages/qdrant_client/http/api_client.py:99, in ApiClient.send(self, request, type_)
     97     except ValidationError as e:
     98         raise ResponseHandlingException(e)
---> 99 raise UnexpectedResponse.for_response(response)

UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Format error in JSON body: data did not match any variant of untagged enum VectorStruct at line 1 column 12767"},"time":0.0}'
```

**Comment by kevin-tofu** [comment]
Thanks for your trying out, Saummya.
It might be a bug on Qdrant Side, Because the type check of data looks passing in llama-index.
