### ISSUE TITLE
[Question]: deploy llamaindex as a server and has some error.

### ISSUE THREAD

**Issue by lambda7xx** [run-llama/llama_index#12396]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I deploy llamaindex as a webserver and it will handle requests from user. the code is below

```
from gevent import monkey
monkey.patch_all()

from llama_index.core import  SimpleDirectoryReader
import sys

"""### LLM

This should run on a T4 instance on the free tier
"""

import torch
# from transformers import BitsAndBytesConfig

from llama_index.llms.huggingface import HuggingFaceLLM
from llama_index.core.prompts import PromptTemplate

from llama_index.core import Settings

from llama_index.core import VectorStoreIndex
from llama_index.core import  SimpleDirectoryReader
from llama_index.core.response.notebook_utils import display_response

import llama_index.core 
import time 
import os
import gevent
import json
from typing import Dict
import sys
from flask import Flask, request
app = Flask(__name__)
import torch.cuda.nvtx as nvtx

llm = HuggingFaceLLM(
    model_name="mistralai/Mistral-7B-Instruct-v0.1",
    tokenizer_name="mistralai/Mistral-7B-Instruct-v0.1",
    query_wrapper_prompt=PromptTemplate("<s>[INST] {query_str} [/INST] </s>\n"),
    context_window=3900,
    max_new_tokens=256,
    model_kwargs={"torch_dtype": torch.bfloat16},
    # tokenizer_kwargs={},
    generate_kwargs={"temperature": 0.2, "top_k": 5, "top_p": 0.95},
    device_map="auto",
)

Settings.llm = llm

# recordMemory("after embedding ")

llama2_paper_path = "./data/llama2_paper/llama2_paper.json"



import json
origin_queries = []
with open(llama2_paper_path) as f:
    data = json.load(f)
    i  = 0
    for key in data['examples']:
        if i < 20:
            origin_queries.append(key['query'])
            i = i + 1

query_gen_str = """\
You are a helpful assistant that generates multiple search queries based on a \
single input query. Generate {num_queries} search queries, one on each line, \
related to the following input query:
Query: {query}
Queries:
"""
query_gen_prompt = PromptTemplate(query_gen_str)

embeddings = "local:BAAI/bge-small-en-v1.5"

Settings.embed_model = embeddings

def generate_queries(query: str, llm, num_queries: int = 4):
    start = time.time()
    response = llm.predict(
        query_gen_prompt, num_queries=num_queries, query=query
    )
    end = time.time()
    print(f"query write duration:{end - start}")
    query_rewrite_duration = end - start    
    # assume LLM proper put each query on a newline
    queries = response.split("\n")
    queries_str = "\n".join(queries)
    print(f"Generated queries:\n{queries_str}")
    return queries, query_rewrite_duration
    

documents = SimpleDirectoryReader("./data/llama2_paper/").load_data() #data/llmama2_paper.json ./data/survery/llm_survery_paper.json
index = VectorStoreIndex.from_documents(documents=documents)
query_engine = index.as_query_engine()

#warm up 
tmp_query = origin_queries[0]
for k in range(2):
        Settings.llm.complete(tmp_query)

def run_query(j):
    all_time = [] 
    query = origin_queries[j]
    start = time.time()
    queries,quert_rewrite_time = generate_queries(query,Settings.llm)
    end = time.time()
    query_rewrite_duration = end - start
    all_time.append(query_rewrite_duration)
    for query1 in queries:
        start = time.time()
        # print(f"type(query1):{type(query1)} and type(query_engine):{type(query_engine)}")
        response = query_engine.query(query1)
        end = time.time()
        query_time = end - start
        all_time.append(query_time)
        all_time.append(len(query1))
        print(f"query+generate  duration:{end - start}, query1:{query1}")
        display_response(response)
    return sum(all_time)



@app.route('/run',  methods = ['POST'])
def run():
    data = request.get_json(force=True, silent=True)
    index = data['index']
    latency = run_query(index)
    print(f"index:{index}, latency:{latency}")
    return json.dumps({'status': 'ok', 'latency': latency})



GET_NODE_INFO_INTERVAL = 0.1


from gevent.pywsgi import WSGIServer
import logging
if __name__ == '__main__':
    logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%H:%M:%S', level='INFO')
    ip = "127.0.0.1"
    port = "8080"
    server = WSGIServer((ip, port), app)
    server.serve_forever()
    gevent.spawn_later(GET_NODE_INFO_INTERVAL)
```

my error is 
```
Traceback (most recent call last):
  File "/home/ubuntu/uw_llama_index/query_rewrite/query_throughput.py", line 4, in <module>
    from llama_index.core import  SimpleDirectoryReader
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/indices/base.py", line 12, in <module>
    from llama_index.core.ingestion import run_transformations
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/ingestion/__init__.py", line 2, in <module>
    from llama_index.core.ingestion.pipeline import (
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/ingestion/pipeline.py", line 15, in <module>
    from llama_index_client import (
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index_client/__init__.py", line 3, in <module>
    from .types import (
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index_client/types/__init__.py", line 3, in <module>
    from .api_key import ApiKey
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index_client/types/api_key.py", line 6, in <module>
    from ..core.datetime_utils import serialize_datetime
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index_client/core/__init__.py", line 4, in <module>
    from .client_wrapper import AsyncClientWrapper, BaseClientWrapper, SyncClientWrapper
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/llama_index_client/core/client_wrapper.py", line 5, in <module>
    import httpx
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/httpx/_api.py", line 6, in <module>
    from ._client import Client
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/httpx/_client.py", line 32, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/httpx/_transports/default.py", line 32, in <module>
    import httpcore
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 12, in <module>
    from .._synchronization import Lock
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/httpcore/_synchronization.py", line 11, in <module>
    import trio
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/trio/__init__.py", line 23, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: split
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar, RunVarToken
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/trio/_core/_local.py", line 9, in <module>
    from . import _run
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/trio/_core/_run.py", line 2809, in <module>
    from ._io_epoll import (
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/trio/_core/_io_epoll.py", line 202, in <module>
    class EpollIOManager:
  File "/home/ubuntu/anaconda3/envs/llama_index/lib/python3.10/site-packages/trio/_core/_io_epoll.py", line 203, in EpollIOManager
    _epoll: select.epoll = attrs.Factory(select.epoll)
AttributeError: module 'select' has no attribute 'epoll'. Did you mean: 'poll'?


```

**Comment by logan-markewich** [comment]
@lambda7xx I think this is an error in your httpx version? What version are you using?
