### ISSUE TITLE
LLMTextCompletionProgram: when output long json, it will be error , 

### ISSUE THREAD

**Issue by SmileLollipop** [run-llama/llama_index#12395]
### Bug Description

LLMTextCompletionProgram: when output long json, it will be error , can we have a good idea to deal with it?

### Version

0.10.18

### Steps to Reproduce

Traceback (most recent call last):
  File "d:\Baoxin\Program\Demo3\module_ty\data_module.py", line 243, in <module>
    print(cc)
       ^^^^^^^
  File "d:\Baoxin\Program\Demo3\module_ty\data_module.py", line 112, in gen_data
    output2 = program2(text=text)
              ^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\llama_index\core\program\llm_program.py", line 104, in __call__
    output = self._output_parser.parse(raw_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\llama_index\core\output_parsers\pydantic.py", line 63, in parse
    return self._output_cls.parse_raw(json_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\pydantic\main.py", line 1124, in parse_raw
    raise pydantic_core.ValidationError.from_exception_data(cls.__name__, [error])
pydantic_core._pydantic_core.ValidationError: 1 validation error for EmergencyExercise
__root__
  Expecting ',' delimiter: line 151 column 6 (char 3019) [type=value_error.jsondecode, input_value='{\n  "exercise_name": "...      }\n      ]\n    }', input_type=str]

**Comment by SmileLollipop** [comment]
program = LLMTextCompletionProgram.from_defaults(
    output_parser=PydanticOutputParser(output_cls=TableInfo),
    prompt_template_str=prompt_template_str,
    verbose=True,
)
print(str(raw_nodes[1].text))
print('-----------------------------')
output = program(input=raw_nodes[1].text)


how to update the code as above
