### ISSUE TITLE
[Bug]: circular dependency: base_retriever.py imports ServiceContext from base.service_context

### ISSUE THREAD

**Issue by gregory-shklover** [run-llama/llama_index#12738]
### Bug Description

Trying to import ServiceContext results in circular dependency.

$ python -c "from llama_index.core.service_context import ServiceContext"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\service_context.py", line 11, in <module>
    from llama_index.core.indices.prompt_helper import PromptHelper
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\indices\__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\indices\composability\__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\indices\composability\graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\indices\base.py", line 8, in <module>
    from llama_index.core.base.base_retriever import BaseRetriever
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\base\base_retriever.py", line 30, in <module>
    from llama_index.core.service_context import ServiceContext
ImportError: cannot import name 'ServiceContext' from partially initialized module 'llama_index.core.service_context' (most likely due to a circular import) (C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\service_context.py)

Versions:
$ pip list | grep llama-index
llama-index-agent-openai            0.2.2
llama-index-core                    0.10.28
llama-index-embeddings-azure-openai 0.1.6
llama-index-embeddings-openai       0.1.7
llama-index-llms-azure-openai       0.1.5
llama-index-llms-openai             0.1.15
llama-index-readers-file            0.1.16

The issue seems to be in base_retriever where it imports ServiceContext only for the purpose of type hints.

### Version

0.10.28

### Steps to Reproduce

python -c "from llama_index.core.service_context import ServiceContext"

### Relevant Logs/Tracbacks

```shell
$ python -c "from llama_index.core.service_context import ServiceContext"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\service_context.py", line 11, in <module>
    from llama_index.core.indices.prompt_helper import PromptHelper
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\indices\__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\indices\composability\__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\indices\composability\graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\indices\base.py", line 8, in <module>
    from llama_index.core.base.base_retriever import BaseRetriever
  File "C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\base\base_retriever.py", line 30, in <module>
    from llama_index.core.service_context import ServiceContext
ImportError: cannot import name 'ServiceContext' from partially initialized module 'llama_index.core.service_context' (most likely due to a circular import) (C:\ProgramData\anaconda3\lib\site-packages\llama_index\core\service_context.py)
```

**Comment by gregory-shklover** [comment]
Reinstalled llama-index-core with force reinstall. The issue disappeared.
