### ISSUE TITLE
[Question]: Joint QA Summary Query Engine no openAI

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#12749]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

**Code-:**

llm = HuggingFaceLLM(
    model_name=model_id,
    tokenizer_name=model_id,
    query_wrapper_prompt=PromptTemplate(PROMPT),
    context_window=3900,
    max_new_tokens=256,
    model_kwargs={"torch_dtype": torch.float16},
    # tokenizer_kwargs={},
    generate_kwargs={"temperature": 0.3,  "top_p": 0.90},
    device_map="auto",
)

Settings.llm = llm
Settings.embed_model = embeddings
Settings.context_window=4096,
Settings.num_output=1500,
Settings.chunk_overlap_ratio=0.3,

vsi = VectorStoreIndex.from_vector_store(
    vector_store = vector_store
)

query_engine_builder = QASummaryQueryEngineBuilder(
    llm=llm,
)

**Error-:**

Traceback (most recent call last):
  File "/home/seceon/opensearch_lm_index/model2.py", line 123, in <module>
    query_engine_builder = QASummaryQueryEngineBuilder(
  File "/usr/local/lib/python3.10/site-packages/llama_index/core/composability/joint_qa_summary.py", line 77, in __init__
    self._service_context = service_context or ServiceContext.from_defaults()
  File "/usr/local/lib/python3.10/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
  File "/usr/local/lib/python3.10/site-packages/llama_index/core/service_context.py", line 187, in from_defaults
    llm_predictor = llm_predictor or LLMPredictor(
  File "/usr/local/lib/python3.10/site-packages/llama_index/core/service_context_elements/llm_predictor.py", line 108, in __init__
    self._llm = resolve_llm(llm, callback_manager=callback_manager)
  File "/usr/local/lib/python3.10/site-packages/llama_index/core/llms/utils.py", line 48, in resolve_llm
    raise ValueError(
ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******

This time I have defined QASummaryQueryEngineBuilder after LLM, still I am getting this issue.

**Comment by Aekansh-Ak** [comment]
NameError: name 'resolve_llm' is not defined
