### ISSUE TITLE
[Bug]: Using qdrant as vectorstore with RaptorRetriever  

### ISSUE THREAD

**Issue by gtesei** [run-llama/llama_index#12756]
### Bug Description

I'm trying to use RaptorPack/RaptorRetriever with qdrant as vectorstore. 
Here's the code I'm using following https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-raptor/examples/raptor.ipynb .  

```python 
import os 
import nest_asyncio
import openai

from llama_index.packs.raptor import RaptorPack
import qdrant_client
from llama_index.core.node_parser import SentenceSplitter
from llama_index.llms.openai import OpenAI
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.packs.raptor import RaptorRetriever
from llama_index.core import StorageContext
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader

from llama_index.vector_stores.qdrant import QdrantVectorStore

# in the same dir this PDF should be downloaded before  
#!wget https://arxiv.org/pdf/2401.18059.pdf -O ./raptor_paper.pdf

documents = SimpleDirectoryReader(input_files=["./raptor_paper.pdf"]).load_data()

nest_asyncio.apply()

qclient = qdrant_client.QdrantClient(location='http://127.0.0.1:6333')
qvector_store = QdrantVectorStore(collection_name='test_raptor', client=qclient)

llm=OpenAI(model="gpt-4-32k-0613", temperature=0.0)
embed_model = OpenAIEmbedding(model="text-embedding-ada-002")

# This should be done once 
feed_qdrant = True 

if feed_qdrant:
    print(">> FEED vectorstore ... ")
    # >>> This works 
    raptor_pack = RaptorPack(
        documents,
        embed_model=embed_model,  # used for embedding clusters
        llm=llm,  # used for generating summaries
        vector_store=qvector_store,  # used for storage
        similarity_top_k=2,  # top k for each layer, or overall top-k for collapsed
        mode="collapsed",  # sets default mode
        transformations=[
            SentenceSplitter(chunk_size=400, chunk_overlap=50)
        ],  # transformations applied for ingestion
    )

print(">> CREATE RaptorRetriever ... ")
retriever = RaptorRetriever([],
                            embed_model=embed_model,  # used for embedding clusters
                            llm=llm,  # used for generating summaries
                            vector_store=qvector_store,  # used for storage
                            similarity_top_k=2,  # top k for each layer, or overall top-k for collapsed
                            mode="collapsed",  # sets default mode
                            ) 

# <<< This does not work 
nodes = retriever.retrieve("What baselines is raptor compared against?", mode="collapsed")
print(len(nodes))
print(nodes[0].text)
```

Although it is possible to feed the vectorstore, when I build the RaptorRetriever I got this exception: 
```python 
>> CREATE RaptorRetriever ... 
Traceback (most recent call last):
  ...
    nodes = retriever.retrieve("What baselines is raptor compared against?", mode="collapsed")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../lib/python3.11/site-packages/llama_index/packs/raptor/base.py", line 294, in retrieve
    return asyncio.run(self.aretrieve(query_str, mode or self.mode))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/..../lib/python3.11/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/..../lib/python3.11/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "..../lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "..../lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "..../lib/python3.11/site-packages/llama_index/packs/raptor/base.py", line 309, in aretrieve
    return await self.collapsed_retrieval(query_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..../lib/python3.11/site-packages/llama_index/packs/raptor/base.py", line 234, in collapsed_retrieval
    return await self.index.as_retriever(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 233, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..../lib/python3.11/site-packages/llama_index/core/base/base_retriever.py", line 276, in aretrieve
    nodes = await self._aretrieve(query_bundle=query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..../lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 233, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../lib/python3.11/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 113, in _aretrieve
    return await self._aget_nodes_with_embeddings(query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../lib/python3.11/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 183, in _aget_nodes_with_embeddings
    query_result = await self._vector_store.aquery(query, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".....lib/python3.11/site-packages/llama_index/vector_stores/qdrant/base.py", line 714, in aquery
    response = await self._aclient.search(
                     ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'search'
```

### Version

0.10.27

### Steps to Reproduce

1. ```wget https://arxiv.org/pdf/2401.18059.pdf -O ./raptor_paper.pdf```
2. ```python <code above>```

### Relevant Logs/Tracbacks

```shell
>> CREATE RaptorRetriever ... 
Traceback (most recent call last):
  ...
    nodes = retriever.retrieve("What baselines is raptor compared against?", mode="collapsed")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../lib/python3.11/site-packages/llama_index/packs/raptor/base.py", line 294, in retrieve
    return asyncio.run(self.aretrieve(query_str, mode or self.mode))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/..../lib/python3.11/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/..../lib/python3.11/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "..../lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "..../lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "..../lib/python3.11/site-packages/llama_index/packs/raptor/base.py", line 309, in aretrieve
    return await self.collapsed_retrieval(query_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..../lib/python3.11/site-packages/llama_index/packs/raptor/base.py", line 234, in collapsed_retrieval
    return await self.index.as_retriever(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 233, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..../lib/python3.11/site-packages/llama_index/core/base/base_retriever.py", line 276, in aretrieve
    nodes = await self._aretrieve(query_bundle=query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..../lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 233, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../lib/python3.11/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 113, in _aretrieve
    return await self._aget_nodes_with_embeddings(query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../lib/python3.11/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 183, in _aget_nodes_with_embeddings
    query_result = await self._vector_store.aquery(query, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".....lib/python3.11/site-packages/llama_index/vector_stores/qdrant/base.py", line 714, in aquery
    response = await self._aclient.search(
                     ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'search'
```

**Comment by gtesei** [comment]
As explained above `QdrantVectorStore` is properly initialized, as it is populated with the text chunks of the paper. This is the standard output: 

```
>> FEED vectorstore ... 
Generating embeddings for level 0.
Performing clustering for level 0.
Generating summaries for level 0 with 15 clusters.
Level 0 created summaries/clusters: 15
Generating embeddings for level 1.
Performing clustering for level 1.
Generating summaries for level 1 with 3 clusters.
Level 1 created summaries/clusters: 3
Generating embeddings for level 2.
Performing clustering for level 2.
Generating summaries for level 2 with 1 clusters.
Level 2 created summaries/clusters: 1
```
