### ISSUE TITLE
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DataSource[Bug]: 

### ISSUE THREAD

**Issue by samuelw1w** [run-llama/llama_index#12750]
### Bug Description

Had a simple chatbot up and running with no issues yesterday. Noticed this morning that I would get the same validation error that's stemming from the imports. Not sure if this is an issue on my end or a potential bug. 

Just running some import statements such as `from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, StorageContext, load_index_from_storage, Settings
` or `from llama_index.embeddings.openai import OpenAIEmbedding
` will return the following error:

### Version

0.10.28

### Steps to Reproduce

`from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, StorageContext, load_index_from_storage, Settings`
`from llama_index.embeddings.openai import OpenAIEmbedding`

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "c:\Users\sw\Downloads\testbot\myproject\agents3.py", line 6, in <module>
    from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, StorageContext, load_index_from_storage, Settings
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\indices\__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\indices\composability\__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\indices\composability\graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\indices\base.py", line 12, in <module>
    from llama_index.core.ingestion import run_transformations
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\ingestion\__init__.py", line 2, in <module>
    from llama_index.core.ingestion.pipeline import (
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\ingestion\pipeline.py", line 31, in <module>
    from llama_index.core.ingestion.api_utils import get_client
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\ingestion\api_utils.py", line 20, in <module>
    from llama_index.core.ingestion.data_sources import (
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\ingestion\data_sources.py", line 436, in <module>
    ConfigurableDataSources = build_configurable_data_source_enum()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\llama_index\core\ingestion\data_sources.py", line 350, in build_configurable_data_source_enum
    DataSource(
  File "c:\Users\sw\Downloads\testbot\.venv\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DataSource
component_type
  subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)
```

**Comment by logan-markewich** [comment]
@samuelw1w start with a fresh venv, seems your env is corrupted

In a new terminal
```
pip uninstall llama-index  # remove any global install
python -m venv venv
source venv/bin/activate
pip install llama-index ...
```

**Comment by YagoJanos** [comment]
@samuelw1w I have the same problem since tuesday, so i think it's not the env that is corrupted, it's some lib that has been updated, but I can be wrong. I see you closed this issue, did you fix it? Any clue?

**Comment by logan-markewich** [comment]
@YagoJanos I'm 99.9% sure its the end, especially since it works on a fresh google colab instance

**Comment by samuelw1w** [comment]
@YagoJanos Yes, removing and recreating the env was able to fix the issue for me.

**Comment by logan-markewich** [comment]
One really nuclear way to do this is

In a fresh terminal
```
pip freeze | grep llama-index | xargs pip uninstall -y
python -m venv venv
source venv/bin/activate
pip install llama-index
```

Following those steps exactly, I would be very surprised if any issue remained

**Comment by YagoJanos** [comment]
Hey man, it doesn't work, I will open another issue, I think my problem is kind different from this.

**Comment by YagoJanos** [comment]
Sorry, it's the same problem and destroying the env and creating another one doesn't seem to work.
I used 
```
pip freeze | grep llama-index | xargs pip uninstall -y
python -m venv venv
source venv/bin/activate
pip install llama-index
```

And still Console Log:
```
[2024-04-11 19:42:02 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2024-04-11 19:42:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2024-04-11 19:42:02 +0000] [1] [INFO] Using worker: sync
[2024-04-11 19:42:02 +0000] [7] [INFO] Booting worker with pid: 7
[2024-04-11 19:42:11 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/hub_ia/api/app.py", line 3, in <module>
    from hub_ia.rag import rag
  File "/app/hub_ia/rag/rag.py", line 1, in <module>
    from hub_ia.config.config import get_loader, get_pipeline, get_folder_id
  File "/app/hub_ia/config/config.py", line 2, in <module>
    from llama_index.llms.openai import OpenAI
  File "/app/.venv/lib/python3.11/site-packages/llama_index/llms/openai/__init__.py", line 1, in <module>
    from llama_index.llms.openai.base import AsyncOpenAI, OpenAI, SyncOpenAI, Tokenizer
  File "/app/.venv/lib/python3.11/site-packages/llama_index/llms/openai/base.py", line 17, in <module>
    from llama_index.core.llms.llm import ToolSelection
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 12, in <module>
    from llama_index.core.ingestion import run_transformations
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/__init__.py", line 2, in <module>
    from llama_index.core.ingestion.pipeline import (
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 31, in <module>
    from llama_index.core.ingestion.api_utils import get_client
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/api_utils.py", line 20, in <module>
    from llama_index.core.ingestion.data_sources import (
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/data_sources.py", line 436, in <module>
    ConfigurableDataSources = build_configurable_data_source_enum()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/data_sources.py", line 350, in build_configurable_data_source_enum
    DataSource(
  File "/app/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DataSource
component_type
  subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)
[2024-04-11 19:42:11 +0000] [7] [INFO] Worker exiting (pid: 7)
[2024-04-11 19:42:11 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
[2024-04-11 19:42:11 +0000] [1] [ERROR] Shutting down: Master
[2024-04-11 19:42:11 +0000] [1] [ERROR] Reason: Worker failed to boot.
```

My pyproject.toml:

```
[tool.poetry]
name = "hub-ia"
version = "0.1.0-alpha"
description = ""
authors = ["hub"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.2"
llama-index = "^0.10.20"
python-dotenv = "^1.0.1"
llama-index-storage-docstore-redis = "^0.1.2"
llama-index-vector-stores-redis = "^0.1.2"
llama-index-readers-google = "^0.1.7"
docx2txt = "^0.8"
schedule = "^1.2.1"
llama-index-storage-chat-store-redis = "^0.1.2"
gunicorn = "^21.2.0"
flask-cors = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by logan-markewich** [comment]
@YagoJanos your google driver reader is too low for this version of llama-index-core it seems

try `llama-index-readers-google = "^0.2"` instead

**Comment by nataliachodelski** [comment]
@YagoJanos I had the same error and was able to resolve it by repeatedly changing the version of llama_index being installed. 

[Maybe my comment here will be helpful for you.](https://github.com/run-llama/llama_index/issues/11534#issuecomment-2033588707)

**Comment by YagoJanos** [comment]
@nataliachodelski it didn't work to me, but thanks anyway.

@logan-markewich Changing llama-index-readers-google to ^0.2 solved the last issue, but now another problem happened:

```
[2024-04-12 10:19:34 -0300] [628170] [INFO] Starting gunicorn 21.2.0
[2024-04-12 10:19:34 -0300] [628170] [INFO] Listening at: http://0.0.0.0:8000 (628170)
[2024-04-12 10:19:34 -0300] [628170] [INFO] Using worker: sync
[2024-04-12 10:19:34 -0300] [628173] [INFO] Booting worker with pid: 628173
Execute ingestion...
[2024-04-12 10:19:36 -0300] [628173] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yago-janos/Desktop/AgoraVai/projeto-ia-hub/hub_ia/api/app.py", line 36, in <module>
    init_app()
  File "/home/yago-janos/Desktop/AgoraVai/projeto-ia-hub/hub_ia/api/app.py", line 19, in init_app
    execute_ingestion()
  File "/home/yago-janos/Desktop/AgoraVai/projeto-ia-hub/hub_ia/rag/rag.py", line 17, in execute_ingestion
    docs = loader.load_data(folder_id=folder_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/llama_index/readers/google/drive/base.py", line 511, in load_data
    self._creds = self._get_credentials()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/llama_index/readers/google/drive/base.py", line 170, in _get_credentials
    flow = InstalledAppFlow.from_client_config(self.client_config, SCOPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/google_auth_oauthlib/flow.py", line 159, in from_client_config
    raise ValueError("Client secrets must be for a web or installed app.")
ValueError: Client secrets must be for a web or installed app.
```

```
def setup_ingestion_pipeline():
        
        vector_store = RedisVectorStore(
            index_name="redis_vector_store",
            index_prefix="vector_store",
            redis_url="redis://localhost:6379",
        )

        cache = IngestionCache(
            cache=RedisCache.from_host_and_port("localhost", 6379),
            collection="redis_cache",
        )

        pipeline = IngestionPipeline(
            transformations=[
                SentenceSplitter(),
                Settings.embed_model,
            ],
            docstore=RedisDocumentStore.from_host_and_port(
                "localhost", 6379, namespace="document_store"
            ),
            vector_store=vector_store,
            cache=cache,
            docstore_strategy=DocstoreStrategy.UPSERTS,
        )

        index = VectorStoreIndex.from_vector_store(
            pipeline.vector_store, embed_model=Settings.embed_model
        )

        loader = GoogleDriveReader("./credentials.json")
 ```
 I am using account service credentials.json in llama-index-readers-google ^0.1 and it was working. Should I open another issue?

**Comment by YagoJanos** [comment]
Solved, it's not a bug, now we have to use 'service_aacount_key_path' on
loader = GoogleDriveReader(service_account_key_path="./credentials.json")

**Comment by ricardopolo** [comment]
I have the same bug when you upgrade llama-index using `poetry update`.

Modifying `llama-index-readers-google` to `^0.2` fixes it
