### ISSUE TITLE
[Bug]: ValueError: Client secrets must be for a web or installed app

### ISSUE THREAD

**Issue by YagoJanos** [run-llama/llama_index#12806]
### Bug Description

Hi, I am using llama-index-readers-google = "^0.2" in my project and I am getting this error:
```
    flow = InstalledAppFlow.from_client_config(self.client_config, SCOPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/google_auth_oauthlib/flow.py", line 159, in from_client_config
    raise ValueError("Client secrets must be for a web or installed app.")
ValueError: Client secrets must be for a web or installed app.
```

When I was using llama-index-readers-google = "^0.1.7", I could read Google Docs from my Google Drive using the credentials.json service account token.
Now with llama-index-readers-google = "^2.0" it's as if I need to use an OAuth token for it to work, because when I use an OAuth token it directs me to a browser page with an error saying that it couldn't authenticate me instead of raising this error on console log I mentioned above

My code is:
```
def setup_ingestion_pipeline():
        
        vector_store = RedisVectorStore(
            index_name="redis_vector_store",
            index_prefix="vector_store",
            redis_url="redis://localhost:6379",
        )

        cache = IngestionCache(
            cache=RedisCache.from_host_and_port("localhost", 6379),
            collection="redis_cache",
        )

        pipeline = IngestionPipeline(
            transformations=[
                SentenceSplitter(),
                Settings.embed_model,
            ],
            docstore=RedisDocumentStore.from_host_and_port(
                "localhost", 6379, namespace="document_store"
            ),
            vector_store=vector_store,
            cache=cache,
            docstore_strategy=DocstoreStrategy.UPSERTS,
        )

        index = VectorStoreIndex.from_vector_store(
            pipeline.vector_store, embed_model=Settings.embed_model
        )

        loader = GoogleDriveReader("./credentials.json")
        . . .
        . . .
```

I was following this doc https://docs.llamaindex.ai/en/stable/examples/ingestion/ingestion_gdrive/

Is there any recent doc or README of llama-index-readers-google = "^0.2" or any solution to this problem?
I also tried to change llama-index version several times but it didn't help.

I also commented on another post about an issue that forced me to change to llama-index-readers-google = "^0.2" and that is very strange because one day my code was running ok in dev environment and another day after cloning again my project and executing a poetry install with the same pyprojec.toml my code broke as follows: https://github.com/run-llama/llama_index/issues/12750#issuecomment-2051871742

### Version

0.10.28

### Steps to Reproduce

Follow this https://docs.llamaindex.ai/en/v0.10.23/examples/ingestion/ingestion_gdrive/ using llama-index-readers-google = "^0.2"
pyproject.toml is:
```
[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.2"
llama-index = "^0.10.20"
python-dotenv = "^1.0.1"
llama-index-storage-docstore-redis = "^0.1.2"
llama-index-vector-stores-redis = "^0.1.2"
llama-index-readers-google = "^0.2"
docx2txt = "^0.8"
schedule = "^1.2.1"
llama-index-storage-chat-store-redis = "^0.1.2"
gunicorn = "^21.2.0"
flask-cors = "^4.0.0"
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yago-janos/Desktop/AgoraVai/projeto-ia-hub/hub_ia/api/app.py", line 36, in <module>
    init_app()
  File "/home/yago-janos/Desktop/AgoraVai/projeto-ia-hub/hub_ia/api/app.py", line 19, in init_app
    execute_ingestion()
  File "/home/yago-janos/Desktop/AgoraVai/projeto-ia-hub/hub_ia/rag/rag.py", line 17, in execute_ingestion
    docs = loader.load_data(folder_id=folder_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/llama_index/readers/google/drive/base.py", line 511, in load_data
    self._creds = self._get_credentials()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/llama_index/readers/google/drive/base.py", line 170, in _get_credentials
    flow = InstalledAppFlow.from_client_config(self.client_config, SCOPES)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yago-janos/.cache/pypoetry/virtualenvs/hub-ia-tauPM_lo-py3.11/lib/python3.11/site-packages/google_auth_oauthlib/flow.py", line 159, in from_client_config
    raise ValueError("Client secrets must be for a web or installed app.")
ValueError: Client secrets must be for a web or installed app.
[2024-04-12 18:42:12 -0300] [717992] [INFO] Worker exiting (pid: 717992)
[2024-04-12 18:42:12 -0300] [717982] [ERROR] Worker (pid:717992
```
```

**Comment by YagoJanos** [comment]
Solved, it's not a bug, now we have to use 'service_aacount_key_path' on 
```loader = GoogleDriveReader(service_account_key_path="./credentials.json")```
