### ISSUE TITLE
file / unstructured example fails with TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by band** [run-llama/llama_index#1284]
I am trying to follow the example in the [llamahub  file / unstructured](https://llamahub.ai/l/file-unstructured) example. This is a sample of my attempt (using `llama-index 0.5.18`) (any suggestions appreciated):

```python
(venv) beckett: ~/tmp/workbench/gpttest02 $ python3
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from llama_index import SimpleDirectoryReader, GPTSimpleVectorIndex
>>> From llama_index import download_loader
>>> UnstructuredReader = download_loader('UnstructuredReader')
>>> text_dir='/Users/band/tmp/workbench/textdir'
>>> loader = SimpleDirectoryReader(text_dir, file_extractor={
...     ".html":"UnstructuredReader",
...     ".eml":"UnstructuredReader"})

>>> documents = loader.load_data()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/band/tmp/workbench/gpttest02/venv/lib/python3.11/site-packages/llama_index/readers/file/base.py", line 179, in load_data
    if not parser.parser_config_set:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'parser_config_set'
```

**Comment by band** [comment]
I got a helpful response on Discord on how to proceed. I am closing this issue.

**Comment by vince015** [comment]
I encountered the same error. May I know the solution for this?

**Comment by SikandAlex** [comment]
Thanks for sharing your solution @band.... downvote

**Comment by logan-markewich** [comment]
@vince015  @SikandAlex This works fine for me on the latest version of llama-index

```python
>>> from llama_index import download_loader
>>> UnstructuredReader = download_loader("UnstructuredReader")
>>> loader = UnstructuredReader()
[nltk_data] Downloading package punkt to /home/loganm/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/loganm/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
>>> documents = loader.load_data(file="docs/examples/data/paul_graham/paul_graham_essay.txt")
```

**Comment by band** [comment]
yeah; y'all are right that i did not mention why i closed the issue. so, bad  behavior on my part. 
so I just now ran the code i posted in April and it fails with the same error. the solution i found then (in Discord) is that there is no UnstructuredReader parser available in `base.py`. And that still seems to be true. 

My solution to that problem for me is to use other readers for `.html` or `.eml` files, if i want to index then for q&a experiments.

i do apologize for not providing this answer then.

**Comment by band** [comment]
yeah. y'all are right that it would have been better if i said what i learned when i closed this. bad behavior on my part.

i just now re-ran the code i posted in April and it fails again with the same error. what i learned from the Discord was that the failure is that there is no UnstructuredReader parser available (just what the error says ... but it took me a minute to learn that). what i did to get around that error was use specific readers for specific file types like `.html` and `.eml` when i want to index them for q&a experiments.

so, maybe this is still an issue, until there is an UnstructuredReader parser.

i apologize for just closing the issue then without writing all this down.

**Comment by SikandAlex** [comment]
I had this failure when I tried to follow the example: 

[Llama Hub](https://llama-hub-ui.vercel.app/l/file-unstructured)

```
loader = SimpleDirectoryReader('./data', file_extractor={
  ".pdf": "UnstructuredReader",
  ".html": "UnstructuredReader",
  ".eml": "UnstructuredReader",
  ".pptx": "PptxReader"
})
documents = loader.load_data()
```

**Comment by hzzhang88** [comment]
Instead of following the example from Llama Hub, I use '**from llama_index import SimpleDirectoryReader**' to import SimpleDirectoryReader.

**Comment by gfrmin** [comment]
For reference, the current (2023-07-08) of doing this is as follows:

```
from llama_index import SimpleDirectoryReader
from llama_hub.file.unstructured.base import UnstructuredReader

loader = SimpleDirectoryReader('data/', file_extractor={".html": UnstructuredReader()})
documents = loader.load_data()
```

I will file a pull request to the llama hub repo too.

**Comment by ahmetmeleq** [comment]
Thank you @gfrmin ! 

I've tried running [the code in this page](https://llamahub.ai/l/file-unstructured) / [this version of the documentation](https://github.com/emptycrown/llama-hub/commit/ffae490187b077166d6c2740b020da7bd04e30f6), but couldn't succeed. Relevant info below.

The llama packages I use:
```
llama-hub                0.0.14
llama-index              0.7.9
```

The code:
```
from pathlib import Path
from llama_index import download_loader

SimpleDirectoryReader = download_loader("SimpleDirectoryReader")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../llama_index/readers/download.py", line 216, in download_loader
    spec.loader.exec_module(module)  # type: ignore

  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data

FileNotFoundError: [Errno 2] No such file or directory: '.../llama_index/readers/llamahub_modules/file/base.py'
```

**Comment by ahmetmeleq** [comment]
I've submitted a [pull request](https://github.com/emptycrown/llama-hub/pull/418) to address [this](https://github.com/jerryjliu/llama_index/issues/1284#issue-1678991288) issue,  together with a [later issue](https://github.com/jerryjliu/llama_index/issues/1284#issuecomment-1648062084) . 

Hopefully that should solve it. Here is a detailed example:

```
>>> from llama_index import SimpleDirectoryReader
>>> from llama_index import download_loader

>>> UnstructuredReader = download_loader('UnstructuredReader')
>>> loader_instance = UnstructuredReader()

[nltk_data] Downloading package punkt to /Users/ahmet/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/ahmet/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

>>> text_dir='/Users/ahmet/debug_data/'
>>> dir_reader = SimpleDirectoryReader(text_dir, file_extractor={
...     ".html":loader_instance,
...     ".txt":loader_instance,
...     ".jpg":loader_instance,
... })

>>> documents=dir_reader.load_data()
```

Results:
```
>>> documents
[
   Document("id_=""55aeb7bb-8796-414c-b963-ce87bd554b22",
   "embedding=None",
   "metadata="{
      
   },
   "excluded_embed_metadata_keys="[
      
   ],
   "excluded_llm_metadata_keys="[
      
   ],
   "relationships="{
      
   },
   "hash=""879f4dd486ca3c0b5a33ef9836aee80b954feb3a07582e731841c1a6f1823117",
   "text=""arXiv:2103.15348v2 [cs.CV] 21 Jun 2021\n\nLayoutParser: A Unified Toolkit for Deep Learning Based Document Image Analysis\n\n“Zejiang Shen! (FD), Ruochen Zhang?, Melissa Dal, Benjamin Charles Germain Lec, Jacob Carlson’, and Welaing Li\n\n‘agchen tangthrowsedt\n\nseradelsacob\n\n\n\ncarLaon)efar\n\n\n\nharvard.eds\n\n“ Ualverty of Warhington\n\nvente cng ete\n\nAbstract. fect advances in document mage anaes (DIA) have ben ‘pimarliy driven bythe application of neural networks dell roar {uteomer could be aly deployed in production and extended fo farther [nvetigtion. However, various factory ke lcely organize codebanee snd sophisticated modal cnigurations compat the ey ree of ‘erin! innovation by wide sence, Though there have been sng ‘Hors to improve reuablty and simplify deep lees (DL) mode ‘aon, sone of them ae optimized for challenge inthe demain of DIA, This roprscte a major gap in the extng fol, sw DIA i eal to scademic research acon wie range of dpi in the social ssencee [rary for streamlining the sage of DL in DIA research and appicn ‘tons The core LayoutFaraer brary comes with a sch of simple and Intative interfaee or applying and eutomiing DI. odel fr Inyo de pltfom for sharing both protrined modes an fal document dist {ation pipeline We demonutate that LayootPareer shea fr both lightweight and lrgeseledgtieation pipelines in eal-word uae ces The leary pblely smal at Btspe://layost-pareergsthab So\n\n‘Keywords: Document Image Analysis: Dep Leening- Layo Analysis (Character Recognition - Open Source library «Took\n\n1 Introduction\n\nDeep Learning(DL)-basod approaches are the stateaftheart fr a wide rage of document image analysis (DIA) tasks including document image easifcation (II)",
   "start_char_idx=None",
   "end_char_idx=None",
   "text_template=""{metadata_str}\n\n{content}",
   "metadata_template=""{key}: {value}",
   "metadata_seperator=""\n"")",
   "Document(id_=""5a42b43a-ef5d-4de3-9e91-6a054703232c",
   "embedding=None",
   "metadata="{
      
   },
   "excluded_embed_metadata_keys="[
      
   ],
   "excluded_llm_metadata_keys="[
      
   ],
   "relationships="{
      
   },
   "hash=""e5e80685fd768ff657d195bab5c797e64731341eb4ae669003735a19dad7edd9",
   "text=""My First Heading\n\nMy first paragraph.",
   "start_char_idx=None",
   "end_char_idx=None",
   "text_template=""{metadata_str}\n\n{content}",
   "metadata_template=""{key}: {value}",
   "metadata_seperator=""\n"")",
   "Document(id_=""8b4f314d-9d0e-4d0d-be0c-77c30bbf8aa7",
   "embedding=None",
   "metadata="{
      
   },
   "excluded_embed_metadata_keys="[
      
   ],
   "excluded_llm_metadata_keys="[
      
   ],
   "relationships="{
      
   },
   "hash=""1957ff92f34b50fc69216b5dc39f29d752f0a7c8577dfb52a5c9893931f485a3",
   "text=""This is a test document to use for unit tests.\n\nDoylestown, PA 18901\n\nImportant points:\n\nHamburgers are delicious\n\nDogs are the best\n\nI love fuzzy blankets",
   "start_char_idx=None",
   "end_char_idx=None",
   "text_template=""{metadata_str}\n\n{content}",
   "metadata_template=""{key}: {value}",
   "metadata_seperator=""\n"")"
]

```
