### ISSUE TITLE
[Question]: is allow special token not available on llamaIndex?

### ISSUE THREAD

**Issue by Benedixx** [run-llama/llama_index#12863]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

i use <|endoftext|> on my prompt and do retrieval using azureopenai, and i got this error
```
ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...}`.     
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<|endoftext|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`.
```

i search on documentation there is no parameter allowed_special, is allowed_special is not exist?

**Comment by logan-markewich** [comment]
This is maybe coming from tiktoken? Maybe? You'd have to manually allow this in tiktoken, and then set a global tokenizer with a partial

```
import tiktoken
from functools import partial

tokenizer = tiktoken.encoding_for_model("gpt-3.5-turbo").encode
tokenizer = partial(tokenizer, allowed_special="all")

from llama_index.core import Settings
Settings.tokenizer = tokenizer
```

**Comment by Benedixx** [comment]
> This is maybe coming from tiktoken? Maybe? You'd have to manually allow this in tiktoken, and then set a global tokenizer with a partial
> 
> ```
> import tiktoken
> from functools import partial
> 
> tokenizer = tiktoken.encoding_for_model("gpt-3.5-turbo").encode
> tokenizer = partial(tokenizer, allowed_special="all")
> 
> from llama_index.core import Settings
> Settings.tokenizer = tokenizer
> ```

I tried this on my code and i print the settings parameter to make sure the allowed_special is exist on Settings, so the code it look like this
```
tokenizer = tiktoken.encoding_for_model("text-davinci-003").encode
tokenizer = partial(tokenizer, allowed_special="all")
Settings.tokenizer = tokenizer

Settings.embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="corpu-text-embedding-ada-002",
    api_key=os.getenv("API_KEY"),
    azure_endpoint=os.getenv("API_BASE"),
    api_version="2023-05-15",
)

Settings.llm = llama_AzureOpenAI(
    model="text-davinci-003",
    deployment_name="corpu-text-davinci-003",
    temperature=0.4,
    api_key=os.getenv("API_KEY"),
    azure_endpoint=os.getenv("API_BASE"),
    api_version="2023-05-15",
)

print(Settings.tokenizer) # print this to make sure the param is exist

retriever = VectorIndexRetriever(index=create_index(), similarity_top_k=4)

response_synthesizer = get_response_synthesizer()

query_engine = RetrieverQueryEngine.from_args(
    retriever=retriever,
    response_synthesizer=response_synthesizer,
    node_postprocessors=[SimilarityPostprocessor(similarity_cutoff=0.7)],
    response_mode="compact",
)

result = query_engine.query(prompt)
```

but the error still persist even thought the tokenizer param on Settings is exist. Here is error log on my terminal
```
(telkom) D:\TITO\Documents\magang\aamr-api>python model_gen_main.py
functools.partial(<bound method Encoding.encode of <Encoding 'p50k_base'>>, allowed_special='all')
Index found, loading index
Traceback (most recent call last):
  File "D:\TITO\Documents\magang\aamr-api\model_gen_main.py", line 430, in <module>
    generate_content()
  File "D:\TITO\Documents\magang\aamr-api\model_gen_main.py", line 368, in generate_content
    content_list = get_list_content()
  File "D:\TITO\Documents\magang\aamr-api\model_gen_main.py", line 342, in get_list_content
    title = get_module_title()
  File "D:\TITO\Documents\magang\aamr-api\model_gen_main.py", line 287, in get_module_title
    title = request_generate(prompt_generate_title())
  File "D:\TITO\Documents\magang\aamr-api\model_gen_main.py", line 261, in request_generate
    result = query_engine.query(prompt)
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\core\base\base_query_engine.py", line 40, in query
    return self._query(str_or_query_bundle)
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\core\query_engine\retriever_query_engine.py", line 187, in _query       
    response = self._response_synthesizer.synthesize(
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\core\response_synthesizers\base.py", line 184, in synthesize
    response_str = self.get_response(
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\core\response_synthesizers\compact_and_refine.py", line 38, in get_response
    return super().get_response(
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\core\response_synthesizers\refine.py", line 163, in get_response        
    response = self._give_response_single(
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\core\response_synthesizers\refine.py", line 217, in _give_response_single
    program(
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\core\response_synthesizers\refine.py", line 68, in __call__
    answer = self._llm.predict(
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\core\llms\llm.py", line 257, in predict
    response = self.complete(formatted_prompt, formatted=True)
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\core\llms\callbacks.py", line 219, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\llms\openai\base.py", line 257, in complete
    return complete_fn(prompt, **kwargs)
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\llms\openai\base.py", line 411, in _complete
    self._update_max_tokens(all_kwargs, prompt)
  File "D:\Anaconda\envs\telkom\lib\site-packages\llama_index\llms\openai\base.py", line 456, in _update_max_tokens
    num_tokens = len(self._tokenizer.encode(prompt))
  File "D:\Anaconda\envs\telkom\lib\site-packages\tiktoken\core.py", line 117, in encode
    raise_disallowed_special_token(match.group())
  File "D:\Anaconda\envs\telkom\lib\site-packages\tiktoken\core.py", line 400, in raise_disallowed_special_token
    raise ValueError(
ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...}`.  
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<|endoftext|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`
```

**Comment by logan-markewich** [comment]
I'm not even able to replicate the original error tbh. Maybe related to token version?

https://colab.research.google.com/drive/1wdFr9SMzyhwBCp5F079d1vrl1pptTekQ?usp=sharing

I don't think this token should even be used when prompting a model though, in my opinion anyways 🤷🏻

**Comment by Benedixx** [comment]
>I'm not even able to replicate the original error tbh. Maybe related to token version?
>https://colab.research.google.com/drive/1wdFr9SMzyhwBCp5F079d1vrl1pptTekQ?usp=sharing
> don't think this token should even be used when prompting a model though, in my opinion anyways 🤷🏻

hmm that's strange, maybe it doesn't work on completion model(?). I use this token because i want to replicate chat completion system user style on completion model, so my prompt will be like this :

```
system:<|endoftext|>you are helpfull assistant<|endoftext|>
user:<|endoftext|>say hello to mr.sebastian<|endoftext|>
assistant:<|endoftext|>
```
well for now maybe i not using special token i guess, thank you for your answer mr.logan
