### ISSUE TITLE
[Bug]: OpenAIAssistantAgent now breaks because of OpenAI api changes

### ISSUE THREAD

**Issue by parnell** [run-llama/llama_index#12968]
### Bug Description

OpenAI changed their api and now llama-index has errors with OpenAIAssistantAgent.

[Comment](https://community.openai.com/t/typeerror-messages-create-got-an-unexpected-keyword-argument-file-ids/722104) from OpenAI about the issue I believe.
From  [https://docs.llamaindex.ai/en/stable/examples/agent/openai_assistant_agent/](LLama Index example code)
```python
from llama_index.agent.openai import OpenAIAssistantAgent

agent = OpenAIAssistantAgent.from_new(
    name="Math Tutor",
    instructions="You are a personal math tutor. Write and run code to answer math questions.",
    openai_tools=[{"type": "code_interpreter"}],
    instructions_prefix="Please address the user as Jane Doe. The user has a premium account.",
)
```

How should I resolve this until it gets resolved in a better manner?

### Version

0.10.30

### Steps to Reproduce

```python
from llama_index.agent.openai import OpenAIAssistantAgent

agent = OpenAIAssistantAgent.from_new(
    name="Math Tutor",
    instructions="You are a personal math tutor. Write and run code to answer math questions.",
    openai_tools=[{"type": "code_interpreter"}],
    instructions_prefix="Please address the user as Jane Doe. The user has a premium account.",
)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File ".../projects/server/error.py", line 7, in <module>
    agent = OpenAIAssistantAgent.from_new(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../lib/python3.11/site-packages/llama_index/agent/openai/openai_assistant_agent.py", line 230, in from_new
    assistant = client.beta.assistants.create(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Assistants.create() got an unexpected keyword argument 'file_ids'
```

**Comment by logan-markewich** [comment]
Nothing to be done except a PR that fixes it :) Will try to take a look this weekend, but feel free to make a PR now if you are motivated
