### ISSUE TITLE
[Bug]:  Client error '404 Not Found' for url 'http://localhost:11434/api/chat'

### ISSUE THREAD

**Issue by gulshansainis** [run-llama/llama_index#12985]
### Bug Description

When I use 

```
from llama_index.llms.ollama import Ollama
...
Settings.llm = Ollama(model="mistral", request_timeout=60.0)
```
I am getting error
```
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 404 Not Found"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 404 Not Found"
An error occurred: Client error '404 Not Found' for url 'http://localhost:11434/api/chat'
```

```
import sys
import logging

logging.basicConfig(stream=sys.stdout, level=logging.INFO, force=True)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

from llama_index.core.llms import MockLLM
from llama_index.llms.ollama import Ollama

from llama_index.core import Settings, StorageContext, load_index_from_storage
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core.embeddings import resolve_embed_model

# Settings.llm = MockLLM()
Settings.llm = Ollama(model="mistral", request_timeout=60.0)

# Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
Settings.embed_model = HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2")


# rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir="./storage")
# load index
index = load_index_from_storage(storage_context)

print(index)

query_engine = index.as_query_engine()
try:

    response = query_engine.query("show mastercard data")
    print(response)
except Exception as e:
    # Code to handle any other exception
    print(f"An error occurred: {str(e)}")
```

**If I do MockLLM, its just works fine**

### Version

0.10.30

### Steps to Reproduce

In the shared code just change the llm to Ollama mistral as follows

```
from llama_index.llms.ollama import Ollama
...
Settings.llm = Ollama(model="mistral", request_timeout=60.0)
```

### Relevant Logs/Tracbacks

```shell
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2
Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2
INFO:sentence_transformers.SentenceTransformer:2 prompts are loaded, with the keys: ['query', 'text']
2 prompts are loaded, with the keys: ['query', 'text']
INFO:llama_index.core.indices.loading:Loading all indices.
Loading all indices.
<llama_index.core.indices.vector_store.base.VectorStoreIndex object at 0x2a10b1dc0>
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.56it/s]
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 404 Not Found"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 404 Not Found"
Traceback (most recent call last):
  File "/Users/gulshansaini/Downloads/llma_meta/7-run-rag.py", line 29, in <module>
    response = query_engine.query("show mastercard data")
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/base/base_query_engine.py", line 53, in query
    query_result = self._query(str_or_query_bundle)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 190, in _query
    response = self._response_synthesizer.synthesize(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/response_synthesizers/base.py", line 241, in synthesize
    response_str = self.get_response(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/response_synthesizers/compact_and_refine.py", line 43, in get_response
    return super().get_response(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/response_synthesizers/refine.py", line 183, in get_response
    response = self._give_response_single(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/response_synthesizers/refine.py", line 238, in _give_response_single
    program(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/response_synthesizers/refine.py", line 84, in __call__
    answer = self._llm.predict(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/llms/llm.py", line 430, in predict
    chat_response = self.chat(messages)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/core/llms/callbacks.py", line 144, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/llama_index/llms/ollama/base.py", line 105, in chat
    response.raise_for_status()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sd_pwps/lib/python3.9/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://localhost:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
```

**Comment by logan-markewich** [comment]
Is your ollama server running? Did you pull the model properly?

**Comment by gulshansainis** [comment]
yes the server is running 

```
$ curl http://localhost:11434/
Ollama is running
```

and here are models

```
 ollama list
NAME         	ID          	SIZE  	MODIFIED          
llama2:latest	78e26419b446	3.8 GB	5 hours ago      	
llama3:8b    	71a106a91016	4.7 GB	About an hour ago
```

**Comment by gulshansainis** [comment]
aah got it. i am missing the mistral in the list.
