### ISSUE TITLE
[Bug]: llama-index-vector-stores-lantern integration incompatible with latest LanternDB builds

### ISSUE THREAD

**Issue by nataliachodelski** [run-llama/llama_index#13115]
### Background:
As of Feb 21, 2024, [the LanternDB team updated their project](https://github.com/lanterndata/lantern/commit/c3005aacd9c20df0eaf67fb9b5e1c97711c02518) to stop supporting the postgres access method `hnsw` in favor of only supporting their own custom access_method, `lantern_hnsw`. 

Prior to this, the LanternDB codebase supported `hnsw` and only used `lantern_hnsw` if `hnsw` was already being used by another extension, like PGVector (this can be seen in the removed code in the commit linked above).   

This change was rolled out with the [`0.2.3` version of Lantern](https://hub.docker.com/layers/lanterndata/lantern/0.2.3-pg16/images/sha256-1604b2184e7022cfdb1b1cb53a7cd6cbf84db3b6ac5e9b604894ff41e62f7a46?context=explore), which was only released on April 9th, which is why this incompatibility has only recently emerged.

## Issue:
- llama_index's Lantern integration, `llama-index-vector-stores-lantern` is hardcoded to use access_method `hnsw`. 
- now that Lantern no longer supports `hnsw`, the current version of llama_index's Lantern integration is incompatible with LanterDB builds > 0.1.1.  

**The error:** If a later version of Lantern (v0.2.3 or v0.2.4) is used with llama_index, the database returns an error when trying to insert into (or query) the vector database. _See error logs included in logs section._

## Solution:
- In order to keep supporting LanternDB, this llama_index integration needs to be updated to use `lantern_hnsw` instead. 
- This appears fixable with a simple code change from `hnsw` to `lantern_hnsw` [on line 115 of `llama-index-integrations/vector_stores/llama-index-vector-stores-lantern/llama_index/vector_stores/lantern/base.py`.  ](https://github.com/run-llama/llama_index/blob/c80e56a23c2451fed16695122b2c89eaaddd5353/llama-index-integrations/vector_stores/llama-index-vector-stores-lantern/llama_index/vector_stores/lantern/base.py#L115)
- I will submit a PR with the fix once this issue is published. 

### Version

have encountered issue with 0.10.25 -> 0.10.31

### Steps to Reproduce

- Use llama_index's `llama-index-vector-stores-lantern` integration in a python project to insert a document into the LanternVectorStore   (suggest latest 0.10.31 version of llama_index)
- Must use a vector database running the `lantern` postgres extension, with a build of Lantern  > v0.1.1, such as 0.2.3 or 0.2.4.
For example: [this latest pg16 build, which is version 0.2.4](https://hub.docker.com/layers/lanterndata/lantern/latest-pg16/images/sha256-3d2e101601375445c11f1bf09a0ff99a6b00bffb7eaa74392c82d138dbddd798?context=explore)
- I have only used this setup with Docker. Can reproduce the issue 100% of the time if using latest version of LanternDB & latest llama-index.

### Relevant Logs/Tracbacks

**Vector-db container logs:**

```shell
starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
LOG:  database system is ready to accept connections
server started
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
psql:/docker-entrypoint-initdb.d/init.sql:5: NOTICE:  database "vector_db" does not exist, skipping
DROP DATABASE
CREATE DATABASE
You are now connected to database "vector_db" as user "postgres".
CREATE EXTENSION
PostgreSQL init process complete; ready for start up.

LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
LOG:  listening on IPv4 address "0.0.0.0", port 5432
LOG:  listening on IPv6 address "::", port 5432
LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
LOG:  database system is ready to accept connections
ERROR:  access method "hnsw" does not exist
STATEMENT:  CREATE INDEX sop_hnsw_idx ON public.data_sop USING hnsw (embedding dist_cos_ops) WITH (m = 16, ef_construction = 128, ef = 64, dim = 3)
```

**Logs from the service performing the insert into vector-db:**
```shell
INFO:sqlalchemy.engine.Engine:CREATE EXTENSION IF NOT EXISTS lantern
INFO:sqlalchemy.engine.Engine:[generated in 0.00026s] {}
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:CREATE SCHEMA IF NOT EXISTS public
INFO:sqlalchemy.engine.Engine:[generated in 0.00026s] {}
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[generated in 0.00034s] {'table_name': 'data_sop', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'public'}

INFO:sqlalchemy.engine.Engine:
CREATE TABLE public.data_sop (
INFO sqlalchemy.engine.Engine 
CREATE TABLE public.data_sop (
	id BIGSERIAL NOT NULL, 
	text VARCHAR NOT NULL, 
	metadata_ JSON, 
	node_id VARCHAR, 
	embedding REAL[], 
	PRIMARY KEY (id)
)

INFO:sqlalchemy.engine.Engine:[no key 0.00018s] {}
INFO:sqlalchemy.engine.Engine:CREATE INDEX sop_hnsw_idx ON public.data_sop USING hnsw (embedding dist_cos_ops) WITH (m = 16, ef_construction = 128, ef = 64, dim = 3)
INFO:sqlalchemy.engine.Engine:[no key 0.00023s] {}
INFO:sqlalchemy.engine.Engine:ROLLBACK
ERROR:server:Exception calling application: (psycopg2.errors.UndefinedObject) access method "hnsw" does not exist

[SQL: CREATE INDEX sop_hnsw_idx ON public.data_sop USING hnsw (embedding dist_cos_ops) WITH (m = 16, ef_construction = 128, ef = 64, dim = 3)]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: access method "hnsw" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/vectorization_servicer.py", line 35, in VectorizeDocument
    vector_store_uuid = self.vector_store.insert(request.document)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/vector_store.py", line 57, in insert
    self.index.insert(doc)
  File "/usr/local/lib/python3.12/site-packages/llama_index/core/indices/base.py", line 242, in insert
    self.insert_nodes(nodes, **insert_kwargs)
  File "/usr/local/lib/python3.12/site-packages/llama_index/core/indices/vector_store/base.py", line 330, in insert_nodes
    self._insert(nodes, **insert_kwargs)
  File "/usr/local/lib/python3.12/site-packages/llama_index/core/indices/vector_store/base.py", line 312, in _insert
    self._add_nodes_to_index(self._index_struct, nodes, **insert_kwargs)
  File "/usr/local/lib/python3.12/site-packages/llama_index/core/indices/vector_store/base.py", line 234, in _add_nodes_to_index
    new_ids = self._vector_store.add(nodes_batch, **insert_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/llama_index/vector_stores/lantern/base.py", line 325, in add
    self._initialize()
  File "/usr/local/lib/python3.12/site-packages/llama_index/vector_stores/lantern/base.py", line 309, in _initialize
    self._create_tables_if_not_exists()
  File "/usr/local/lib/python3.12/site-packages/llama_index/vector_stores/lantern/base.py", line 293, in _create_tables_if_not_exists
    self._base.metadata.create_all(session.connection())
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 5825, in create_all
    bind._run_ddl_visitor(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2461, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 918, in visit_metadata
    self.traverse_single(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 960, in visit_table
    self.traverse_single(index, create_ok=True)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 997, in visit_index
    CreateIndex(index)._invoke_with(self.connection)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 314, in _invoke_with
    return bind.execute(self)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1533, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) access method "hnsw" does not exist

[SQL: CREATE INDEX sop_hnsw_idx ON public.data_sop USING hnsw (embedding dist_cos_ops) WITH (m = 16, ef_construction = 128, ef = 64, dim = 3)]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

**Comment by logan-markewich** [comment]
Looking forward to the PR, thanks @nataliachodelski !
