### ISSUE TITLE
[Question]: cannot load config_sentence_transformers.json when using local BAAI/bge-small-en-v1.5

### ISSUE THREAD

**Issue by elvisbegovic** [run-llama/llama_index#13265]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

On windows environnment I am trying  : 

```
Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5"
)
```

But got : 
```
Traceback (most recent call last):
  File "C:\Users\eb\vscode-workspace\tst\app.py", line 22, in <module>
    Settings.embed_model = HuggingFaceEmbedding(
  File "C:\Users\eb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\llama_index\embeddings\huggingface\base.py", line 86, in __init__
    self._model = SentenceTransformer(
  File "C:\Users\eb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sentence_transformers\SentenceTransformer.py", line 197, in __init__
    modules = self._load_sbert_model(
  File "C:\Users\eb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sentence_transformers\SentenceTransformer.py", line 1226, in _load_sbert_model
    with open(config_sentence_transformers_json_path) as fIn:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\eb\\AppData\\Local\\llama_index\\models--BAAI--bge-small-en-v1.5\\snapshots\\5c38ec7c405ec4b44b94cc5a9bb96e735b38267a\\config_sentence_transformers.json'
```

File not exist while all are installed using pip (no syntax error on code)

(it works on WSL, not windows)

**Comment by elvisbegovic** [comment]
@dosu thanks works 
```
Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5",
    cache_folder="./"
)
```
