### ISSUE TITLE
[Bug]: QASummaryQueryEngineBuilder raises `ValueError: No API key found for OpenAI` even if llm is specified

### ISSUE THREAD

**Issue by RussellLuo** [run-llama/llama_index#13280]
### Bug Description

Given the following snippet of code:

```python
# test.py

from llama_index.core.composability import QASummaryQueryEngineBuilder
from llama_index.core.embeddings import MockEmbedding
from llama_index.llms.azure_openai import AzureOpenAI

api_key = "<api-key>"
azure_endpoint = "https://<your-resource-name>.openai.azure.com/"
api_version = "2023-07-01-preview"

llm = AzureOpenAI(
    model="gpt-35-turbo-16k",
    deployment_name="my-custom-llm",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

query_engine_builder = QASummaryQueryEngineBuilder(
    llm=llm,
    embed_model=MockEmbedding(0),
)
```

Just run it as below:

```bash
$ python test.py 
Traceback (most recent call last):
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/llms/utils.py", line 41, in resolve_llm
    validate_openai_api_key(llm.api_key)
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/llms/openai/utils.py", line 400, in validate_openai_api_key
    raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/russellluo/Projects/work/opencsg/labs/llama_index/test.py", line 17, in <module>
    query_engine_builder = QASummaryQueryEngineBuilder(
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/composability/joint_qa_summary.py", line 77, in __init__
    self._service_context = service_context or ServiceContext.from_defaults()
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/service_context.py", line 187, in from_defaults
    llm_predictor = llm_predictor or LLMPredictor(
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/service_context_elements/llm_predictor.py", line 108, in __init__
    self._llm = resolve_llm(llm, callback_manager=callback_manager)
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/llms/utils.py", line 48, in resolve_llm
    raise ValueError(
ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******
```

### Version

v0.10.34

### Steps to Reproduce

See steps in Bug Description.

**Comment by RussellLuo** [comment]
Per the traceback given above, the line causing the error is:

https://github.com/run-llama/llama_index/blob/48e0a267335489358844c722bac768f12e88bbb8/llama-index-core/llama_index/core/composability/joint_qa_summary.py#L77

A possible solution is to remove the `ServiceContext.from_defaults()` part:

```diff
- self._service_context = service_context or ServiceContext.from_defaults()
+ self._service_context = service_context
```

While this fix is effective for the above issue, another problem occurred:

```bash
Traceback (most recent call last):
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/llms/utils.py", line 41, in resolve_llm
    validate_openai_api_key(llm.api_key)
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/llms/openai/utils.py", line 400, in validate_openai_api_key
    raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/russellluo/Projects/work/opencsg/labs/llama_index/test_qa_summary.py", line 67, in <module>
    query_engine = query_engine_builder.build_from_documents(documents)
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/composability/joint_qa_summary.py", line 116, in build_from_documents
    return RouterQueryEngine.from_defaults(
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/query_engine/router_query_engine.py", line 157, in from_defaults
    return cls(
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/query_engine/router_query_engine.py", line 117, in __init__
    self._llm = llm or llm_from_settings_or_context(Settings, llm)
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/settings.py", line 264, in llm_from_settings_or_context
    return settings.llm
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/settings.py", line 39, in llm
    self._llm = resolve_llm("default")
  File "/opt/miniconda3/envs/llama_index/lib/python3.10/site-packages/llama_index/core/llms/utils.py", line 48, in resolve_llm
    raise ValueError(
ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******
```

The crux of the problem is that `llm` parameter was not passed when when constructing `RouterQueryEngine`:

https://github.com/run-llama/llama_index/blob/48e0a267335489358844c722bac768f12e88bbb8/llama-index-core/llama_index/core/query_engine/router_query_engine.py#L151-L163

And I guess the solution is quite apparent:

```diff
        return cls(
            selector,
            query_engine_tools,
+           llm=llm,
            service_context=service_context,
            summarizer=summarizer,
            **kwargs,
        )
```
