### ISSUE TITLE
[Bug]: demo for pinecone support broken

### ISSUE THREAD

**Issue by jzhao62** [run-llama/llama_index#13347]
### Bug Description

follow the example code for [pinecone support](https://docs.llamaindex.ai/en/stable/examples/vector_stores/PineconeIndexDemo/)

Cause:
- attempting to instantiate an abstract instance
![image](https://github.com/run-llama/llama_index/assets/25937657/92646b55-5cb6-4c88-b6b2-a2c6ee9339c1)

Remedy: 
-  Changing BaseNode type to TextNode will make the demo work

### Version

0.10.34

### Steps to Reproduce

1. follow the example code for [pinecone support](https://docs.llamaindex.ai/en/stable/module_guides/indexing/vector_store_guide/)
2. you will see error when using query engine 

### Relevant Logs/Tracbacks

```shell
- Traceback

Traceback (most recent call last):
  File "/home/jingyi/PycharmProjects/llama/llama-pinecone.py", line 37, in <module>
    response = query_engine.query("What did the author do growing up?")
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/base/base_query_engine.py", line 53, in query
    query_result = self._query(str_or_query_bundle)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 189, in _query
    nodes = self.retrieve(query_bundle)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 144, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py", line 244, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 101, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 180, in _get_nodes_with_embeddings
    return self._build_node_list_from_query_result(query_result)
  File "/home/jingyi/PycharmProjects/llama/.venv/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 171, in _build_node_list_from_query_result
    node_with_scores.append(NodeWithScore(node=node, score=score))
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for NodeWithScore
node
  Can't instantiate abstract class BaseNode with abstract methods get_content, get_metadata_str, get_type, hash, set_content (type=type_error)
```
```

**Comment by logan-markewich** [comment]
@jzhao62 not an issue with llama-index, there are no abstract methods that aren't implemented. If that was the cause none of our unit tests would pass.

More likely, it's an env issue. Try with a completely fresh venv, or in Google colab.

Locally, I would do this in a new terminal

```
# remove any global install
pip freeze | grep llama-index | xargs pip uninstall -y

# install in a fresh env 
python -m venv venv
source venv/bin/activate
pip install llama-index llama-index-vector-stores-pinecone
```

**Comment by jzhao62** [comment]
@logan-markewich i switched back to 0.9.34 and it works, indeed an env issue

**Comment by logan-markewich** [comment]
@jzhao62 yea, mixing legacy with non-legacy imports will also cause this. Need to use all legacy imports or none
