### ISSUE TITLE
[Bug]: openai http_client type error

### ISSUE THREAD

**Issue by waveBoom** [run-llama/llama_index#13357]
### Bug Description

in the llms/llama-index-llms-openai/llama_index/llms/openai : class OpenAI(FunctionCallingLLM):
in the  " def __init__"  method code: {  http_client: Optional[httpx.Client] = None, }
http_client type is httpx.Client

but in the method : def _get_aclient(self) :
the code : AsyncOpenAI(**self._get_credential_kwargs())
in class AsyncOpenAI      def __init__()
the http_client: httpx.AsyncClient | None = None,
http_client type is httpx.AsyncClient 

so when i use the code to set http_client : 
{
from openai import OpenAI, DefaultAsyncHttpxClient
from llama_index.llms.openai import OpenAI as llmOpenAi
httpclient = DefaultAsyncHttpxClient()
llm = llmOpenAi(temperature=0, model=model_name, http_client=httpclient)
}
is type error.

i think the class OpenAI(FunctionCallingLLM) 's http_client type should be father type rather than now 

### Version

0.10.32

### Steps to Reproduce

when use custom http_client for openAi
{
from openai import OpenAI, DefaultAsyncHttpxClient
from llama_index.llms.openai import OpenAI as llmOpenAi
httpclient = DefaultAsyncHttpxClient()
llm = llmOpenAi(temperature=0, model=model_name, http_client=httpclient)
}

### Relevant Logs/Tracbacks

```shell
TypeError: Invalid `http_client` argument; Expected an instance of `httpx.Client` but got <class 'openai._DefaultAsyncHttpxClient'>
ERROR:server.py:handle_mentions:An error occurred:
Traceback (most recent call last):
  File "/Users/bobo/practise/myGPTReader/app/server.py", line 252, in bot_process
    gpt_response, total_llm_model_tokens, total_embedding_model_tokens = future.result(timeout=300)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bobo/practise/myGPTReader/app/gpt.py", line 303, in get_answer_from_llama_file_route_engine
    answer = query_engine.query(dialog_messages)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/base/base_query_engine.py", line 53, in query
    query_result = self._query(str_or_query_bundle)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/query_engine/router_query_engine.py", line 182, in _query
    responses.append(selected_query_engine.query(query_bundle))
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/base/base_query_engine.py", line 53, in query
    query_result = self._query(str_or_query_bundle)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 190, in _query
    response = self._response_synthesizer.synthesize(
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/response_synthesizers/base.py", line 242, in synthesize
    response_str = self.get_response(
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/response_synthesizers/tree_summarize.py", line 236, in get_response
    return self.get_response(
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/response_synthesizers/tree_summarize.py", line 169, in get_response
    response = self._llm.predict(
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/llms/llm.py", line 430, in predict
    chat_response = self.chat(messages)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/llms/callbacks.py", line 144, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/llms/openai/base.py", line 296, in chat
    return chat_fn(messages, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/llms/openai/base.py", line 360, in _chat
    client = self._get_client()
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/llms/openai/base.py", line 242, in _get_client
    self._client = SyncOpenAI(**self._get_credential_kwargs())
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/openai/_client.py", line 122, in __init__
    super().__init__(
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/openai/_base_client.py", line 808, in __init__
    raise TypeError(
TypeError: Invalid `http_client` argument; Expected an instance of `httpx.Client` but got <class 'openai._DefaultAsyncHttpxClient'>
```

**Comment by waveBoom** [comment]
when i change the httpclient = DefaultHttpxClient()
{
from openai import OpenAI, DefaultHttpxClient
from llama_index.llms.openai import OpenAI as llmOpenAi
httpclient = DefaultHttpxClient()
llm = llmOpenAi(temperature=0, model=model_name, http_client=httpclient)
}

the error is :

ERROR:server.py:handle_mentions:An error occurred:
Traceback (most recent call last):
  File "/Users/bobo/practise/myGPTReader/app/server.py", line 252, in bot_process
    gpt_response, total_llm_model_tokens, total_embedding_model_tokens = future.result(timeout=300)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bobo/practise/myGPTReader/app/gpt.py", line 304, in get_answer_from_llama_file_route_engine
    answer = query_engine.query(dialog_messages)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/base/base_query_engine.py", line 53, in query
    query_result = self._query(str_or_query_bundle)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/query_engine/router_query_engine.py", line 182, in _query
    responses.append(selected_query_engine.query(query_bundle))
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/base/base_query_engine.py", line 53, in query
    query_result = self._query(str_or_query_bundle)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 190, in _query
    response = self._response_synthesizer.synthesize(
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/response_synthesizers/base.py", line 242, in synthesize
    response_str = self.get_response(
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/response_synthesizers/tree_summarize.py", line 207, in get_response
    summary_responses = run_async_tasks(tasks)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/async_utils.py", line 54, in run_async_tasks
    outputs: List[Any] = asyncio.run(_gather())
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/async_utils.py", line 52, in _gather
    return await asyncio.gather(*tasks_to_execute)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in async_wrapper
    result = await func(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/llms/llm.py", line 515, in apredict
    chat_response = await self.achat(messages)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/core/llms/callbacks.py", line 71, in wrapped_async_llm_chat
    f_return_val = await f(_self, messages, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/llms/openai/base.py", line 575, in achat
    return await achat_fn(messages, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/llms/openai/base.py", line 618, in _achat
    aclient = self._get_aclient()
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/llama_index/llms/openai/base.py", line 250, in _get_aclient
    self._aclient = AsyncOpenAI(**self._get_credential_kwargs())
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/openai/_client.py", line 334, in __init__
    super().__init__(
  File "/Users/bobo/practise/myGPTReader/venv/lib/python3.9/site-packages/openai/_base_client.py", line 1375, in __init__
    raise TypeError(
TypeError: Invalid `http_client` argument; Expected an instance of `httpx.AsyncClient` but got <class 'openai._DefaultHttpxClient'>







so so so , So I can't set any kind of http client type

**Comment by logan-markewich** [comment]
`httpx.AsyncClient` is the same as `DefaultAsyncHttpxClient` 

I think the issue is the type is for `httpx.Client` instead of the async client

**Comment by logan-markewich** [comment]
tbh I'm not entirely sure what the issue is, it works fine for me

```python
>>> from httpx import Client
>>> from llama_index.llms.openai import OpenAI
>>> llm = OpenAI(http_client=Client())
>>> llm.complete("Test")
CompletionResponse(text='Hello! How can I assist you today?', additional_kwargs={}, raw={'id': 'chatcmpl-9MdCFrjIKLuHwFmtwUV5U6AOHEZ5w', 'choices': [Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hello! How can I assist you today?', role='assistant', function_call=None, tool_calls=None))], 'created': 1715180915, 'model': 'gpt-3.5-turbo-0125', 'object': 'chat.completion', 'system_fingerprint': None, 'usage': CompletionUsage(completion_tokens=9, prompt_tokens=8, total_tokens=17)}, logprobs=None, delta=None)

>>> from openai import DefaultHttpxClient
>>> llm = OpenAI(http_client=DefaultHttpxClient())
>>> llm.complete("Test")
CompletionResponse(text='Hello! How can I assist you today?', additional_kwargs={}, raw={'id': 'chatcmpl-9MdCugBPsZjMypjV1l55TtRKwzoCE', 'choices': [Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hello! How can I assist you today?', role='assistant', function_call=None, tool_calls=None))], 'created': 1715180956, 'model': 'gpt-3.5-turbo-0125', 'object': 'chat.completion', 'system_fingerprint': None, 'usage': CompletionUsage(completion_tokens=9, prompt_tokens=8, total_tokens=17)}, logprobs=None, delta=None)
>>> 
```

**Comment by logan-markewich** [comment]
I think the actual issue here is just missing the option to provide an async http client instead of sync client
