### ISSUE TITLE
[Bug]: ImportError: cannot import name 'BaseRetriever' from partially initialized module 'llama_index.core.base.base_retriever'

### ISSUE THREAD

**Issue by ForgetThatNight** [run-llama/llama_index#13411]
### Bug Description

Traceback (most recent call last):
  File "/data/env/anaconda3/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py", line 30, in <module>
    from llama_index.core.service_context import ServiceContext
  File "/data/env/anaconda3/lib/python3.10/site-packages/llama_index/core/service_context.py", line 11, in <module>
    from llama_index.core.indices.prompt_helper import PromptHelper
  File "/data/env/anaconda3/lib/python3.10/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/data/env/anaconda3/lib/python3.10/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/data/env/anaconda3/lib/python3.10/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
    from llama_index.core.indices.base import BaseIndex
  File "/data/env/anaconda3/lib/python3.10/site-packages/llama_index/core/indices/base.py", line 8, in <module>
    from llama_index.core.base.base_retriever import BaseRetriever
ImportError: cannot import name 'BaseRetriever' from partially initialized module 'llama_index.core.base.base_retriever' (most likely due to a circular import) (/data/env/anaconda3/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py)

### Version

0.10.34

### Steps to Reproduce

from llama_index.core.base.base_retriever import BaseRetriever

llama-hub                                0.0.79.post1
llama-index                              0.10.34
llama-index-agent-openai                 0.1.7
llama-index-cli                          0.1.12
llama-index-core                         0.10.34
llama-index-embeddings-openai            0.1.9
llama-index-indices-managed-llama-cloud  0.1.6
llama-index-legacy                       0.9.48
llama-index-llms-openai                  0.1.16
llama-index-multi-modal-llms-openai      0.1.5
llama-index-program-openai               0.1.6
llama-index-question-gen-openai          0.1.3
llama-index-readers-file                 0.1.19
llama-index-readers-llama-parse          0.1.4
llama-parse                              0.4.2
llamaindex-py-client                     0.1.19

**Comment by logan-markewich** [comment]
The llama-hub package is deprecated, installing that would have maybe caused some issues.

Try again with a fresh venv. Works fine in google colab
https://colab.research.google.com/drive/155DJxHVgDV7exMct-3dkFA4n0fgDQZ_R?usp=sharing
