### ISSUE TITLE
[Question]: SimpleDirectoryReader failed to load 1 file (but other 100 files are fine)

### ISSUE THREAD

**Issue by 130jd** [run-llama/llama_index#13438]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm using `SimpleDirectoryReader(filename_as_id=True).load_data()` on 350 PDF documents. It works fine on all except 1 PDF, which throws this error.

`Failed to load file C:\Users\MyUsername\OneDrive\Documents\FolderName\FolderName\**[AuthorFirstName-AuthorLastName] CompanyName, Inc..PDF** with error: RetryError[<Future at 0x#########d0 state=finished raised IndexError>]. Skipping...`

I've checked the content of the document, the filename (thought characters like `[` `]` `,` `..` might cause issues but those appear in other PDFs that get read just fine).

Any suggestions for what else I could investigate about this 1 PDF file that would explain it?

Thank you

**Comment by 130jd** [comment]
Thanks @dosu

I tried your suggestion and set `raise_on_error` to `True`

This was the error message; does it help you diagnose what in my PDF document caused the error?

```
Traceback (most recent call last):
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\tenacity\__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\llama_index\readers\file\docs\base.py", line 88, in load_data
    page_text = pdf.pages[page].extract_text()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\pypdf\_page.py", line 2083, in extract_text
    return self._extract_text(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\pypdf\_page.py", line 1593, in _extract_text
    cmaps[f] = build_char_map(f, space_width, obj)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\pypdf\_cmap.py", line 33, in build_char_map
    font_subtype, font_halfspace, font_encoding, font_map = build_char_map_from_dict(
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\pypdf\_cmap.py", line 58, in build_char_map_from_dict
    map_dict, space_code, int_entry = parse_to_unicode(ft, space_code)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\pypdf\_cmap.py", line 227, in parse_to_unicode
    return type1_alternative(ft, map_dict, space_code, int_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\pypdf\_cmap.py", line 498, in type1_alternative
    i = int(words[1])
            ~~~~~^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\llama_index\core\readers\file\base.py", line 416, in load_file
    docs = reader.load_data(input_file, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\tenacity\__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\tenacity\__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\tenacity\__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyUsername\anaconda3\envs\openai-env\Lib\site-packages\tenacity\__init__.py", line 411, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x25300529a90 state=finished raised IndexError>]
```
