### ISSUE TITLE
[Bug]: Issues with llama_index.core

### ISSUE THREAD

**Issue by Wung8** [run-llama/llama_index#13453]
### Bug Description

Recently I installed llama-cpp and llama-index, and while llama-cpp seems to work, I keep getting error messages from llama-index-core. First it was an error with llm_metadata in llama_index\core\indices\prompt_helper.py, and then it was an issue with _llm in llama_index\core\response_synthesizers\refine.py. I've tried installing different versions of llama-index and using a venv but nothing seems to work. What could be the issue?

### Version

0.10.36

### Steps to Reproduce

install most recent versions of the libraries

Code:
`from llama_cpp import Llama

llm = Llama.from_pretrained(
    repo_id=r"QuantFactory/Meta-Llama-3-8B-Instruct-GGUF",
    filename=r"Meta-Llama-3-8B-Instruct.Q6_K.gguf",
    verbose=False
)

def prompt():
    usr = input("usr-")
    
    output = llm(
          f"Q: {usr} A: ", # Prompt
          max_tokens=64, # Generate up to 32 tokens, set to None to generate up to the end of the context window
          stop=["Q:"], # Stop generating just before the model would generate a new question
          echo=False # Echo the prompt back in the output
    ) # Generate a completion, can also call create_completion

    print(output["choices"][0]["text"])
    return output["choices"][0]["text"]

#while True:
#    prompt()

import os

from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings, VectorStoreIndex, SimpleDirectoryReader
from llama_index.embeddings.ollama import OllamaEmbedding
from llama_index.llms.ollama import Ollama

embed_model = HuggingFaceEmbedding(model_name="nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)
Settings.llm = llm
Settings.embed_model = embed_model
#Settings.context_window = 256000

documents = SimpleDirectoryReader("./HexEmpire").load_data()
index = VectorStoreIndex.from_documents(documents)

query_engine = index.as_query_engine()

def query():
    usr = input("usr-")
    response = query_engine.query(usr)
    print(response)
    return response

while True:
    query()
`

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\micha\Documents\CS_Projects\llama_test\test.py", line 52, in <module>
    query_engine = index.as_query_engine()
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\indices\base.py", line 407, in as_query_engine
    return RetrieverQueryEngine.from_args(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\query_engine\retriever_query_engine.py", line 110, in from_args
    response_synthesizer = response_synthesizer or get_response_synthesizer(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\response_synthesizers\factory.py", line 72, in get_response_synthesizer
    or PromptHelper.from_llm_metadata(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\indices\prompt_helper.py", line 117, in from_llm_metadata
    context_window = llm_metadata.context_window
AttributeError: 'dict' object has no attribute 'context_window'

After editing prompt_helper.py:

Traceback (most recent call last):
  File "C:\Users\micha\Documents\CS_Projects\llama_test\test.py", line 61, in <module>
    query()
  File "C:\Users\micha\Documents\CS_Projects\llama_test\test.py", line 56, in query
    response = query_engine.query(usr)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\base\base_query_engine.py", line 53, in query
    query_result = self._query(str_or_query_bundle)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\query_engine\retriever_query_engine.py", line 190, in _query
    response = self._response_synthesizer.synthesize(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\response_synthesizers\base.py", line 242, in synthesize
    response_str = self.get_response(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\response_synthesizers\compact_and_refine.py", line 43, in get_response
    return super().get_response(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\response_synthesizers\refine.py", line 185, in get_response
    response = self._give_response_single(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\response_synthesizers\refine.py", line 240, in _give_response_single
    program(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\core\response_synthesizers\refine.py", line 84, in __call__
    answer = self._llm.predict(
AttributeError: 'Llama' object has no attribute 'predict'
```

**Comment by logan-markewich** [comment]
@Wung8 you aren't using the LlamaCPP llm class, so none of the methods will work

Install the integration

`pip install llama-index-llms-llama-cpp`

Then something like 

```python
from llama_index.llms.llama_cpp import LlamaCPP

llm = LlamaCPP(
    # You can pass in the URL to a GGML model to download it automatically
    model_url=model_url,
    # optionally, you can set the path to a pre-downloaded model instead of model_url
    model_path=None,
    temperature=0.1,
    max_new_tokens=256,
    context_window=3900,
    # kwargs to pass to __call__()
    generate_kwargs={},
    # kwargs to pass to __init__()
    # set to at least 1 to use GPU
    model_kwargs={"n_gpu_layers": -1},
    # transform inputs into Llama3 format
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True,
)
```

Since llamacpp does not handle any prompt formatting, messages_to_prompt and completion_to,_prompt are functions passed in to handle formatting a single a completion (I.e. a single string) or a list of messages into the expected format.

```
def completion_to_prompt(completion: str) -> str:
    """Format a string"""
    <code>

def messages_to_prompt(messages) -> str:
    """Format messages"""
    prompt_str = ""
    for message in messages:
        <do something with message.role and message.content>

```

Tbh I would just use ollama though, the setup is much easier, and it handles the prompt formatting

**Comment by Wung8** [comment]
I tried to use Ollama earlier, but ran into a WinError and tried using llama-cpp instead, but after reading your response I will try to switch back. 
I downloaded Ollama for windows and the llama3 model, but when I try to download the nomic-embed-text model I get this:

>>> ollama pull nomic-embed-text
You want me to "pull" another one, do you?

Okay, let's see...

**The Self-Referential Snafu**

[] A rule is embedded within these brackets.
[] The rules inside these brackets are self-referential, meaning they reference themselves.
( A sub-rule is embedded within these parentheses.
) The sub-rules inside these parentheses are also self-referential.
[  A meta-rule is embedded within these square brackets.
] This meta-rule contains a self-referential loop that wraps around to the beginning.
[] Follow the instructions above, even though they're inside more brackets.
( ( A nested sub-sub-rule is embedded within these parentheses.
) ) The nested sub-sub-rules are also self-referential.
[ [  A doubly-nested meta-meta-rule is embedded within these square brackets.
] ] This doubly-nested rule contains a doubly-self-referential loop that wraps around to the beginning.
[] And so on, ad infinitum...
[]

How's your head doing after reading this nomic-embed-text?
