### ISSUE TITLE
[Bug]: CodeSplitter takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by framsouza** [run-llama/llama_index#13521]
### Bug Description

CodeSplitter doesn't seem to be working as expected

### Version

0.10.36

### Steps to Reproduce

```
from llama_index.core.node_parser import CodeSplitter
from llama_index.readers.file import FlatReader
from pathlib import Path

documents = FlatReader().load_data(Path("index.py"))
splitter = CodeSplitter(
    language="python"
    chunk_lines=40,  # lines per chunk
    chunk_lines_overlap=15  # lines overlap between chunks
    max_chars=1500,  # max chars per chunk
)
nodes = splitter.get_nodes_from_documents(documents)
nodes[0].text
```

### Relevant Logs/Tracbacks

```shell
python test.py 
Could not get parser for language python. Check https://github.com/grantjenks/py-tree-sitter-languages#license for a list of valid languages.
Traceback (most recent call last):
  File "/Users/framsouza/git-assistant/test.py", line 6, in <module>
    splitter = CodeSplitter(
               ^^^^^^^^^^^^^
  File "/Users/framsouza/git-assistant/lib/python3.11/site-packages/llama_index/core/node_parser/text/code.py", line 63, in __init__
    parser = tree_sitter_languages.get_parser(language)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tree_sitter_languages/core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by logan-markewich** [comment]
@framsouza yea this seems like an issue with the tree-sitter version. I don't actually know what the solution is yet, but a band-aid fix was `pip install -U "tree-sitter<0.22.0"`

**Comment by framsouza** [comment]
hey @logan-markewich , i just gave it a try:

```
pip list | grep tree
tree-sitter                             0.21.3
tree-sitter-go                          0.21.0
tree-sitter-languages                   1.10.2
```

```
    pipeline = IngestionPipeline(
        transformations=[
            CodeSplitter(language="go", chunk_lines=20, chunk_lines_overlap=5),
            Settings.embed_model
        ],
        vector_store=get_es_vector_store()
    )
```

got a different error,

```
Data loaded from local directory.
Starting the pipeline...
Parsing nodes:   0%|                                                                                                           | 0/2002 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/framsouza/git-assistant/index.py", line 166, in <module>
    main()
  File "/Users/framsouza/git-assistant/index.py", line 159, in main
    pipeline.run(show_progress=True, documents=documents)
  File "/Users/framsouza/git-assistant/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 734, in run
    nodes = run_transformations(
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/framsouza/git-assistant/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 124, in run_transformations
    nodes = transform(nodes, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/framsouza/git-assistant/lib/python3.11/site-packages/llama_index/core/node_parser/interface.py", line 127, in __call__
    return self.get_nodes_from_documents(nodes, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/framsouza/git-assistant/lib/python3.11/site-packages/llama_index/core/node_parser/interface.py", line 76, in get_nodes_from_documents
    nodes = self._parse_nodes(documents, show_progress=show_progress, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/framsouza/git-assistant/lib/python3.11/site-packages/llama_index/core/node_parser/interface.py", line 145, in _parse_nodes
    splits = self.split_text(node.get_content())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/framsouza/git-assistant/lib/python3.11/site-packages/llama_index/core/node_parser/text/code.py", line 161, in split_text
    raise ValueError(f"Could not parse code with language {self.language}.")
ValueError: Could not parse code with language go.
```

I can see go on supported languages.

**Comment by logan-markewich** [comment]
@framsouza Seems like the if statement at the top if failing

<img width="804" alt="image" src="https://github.com/run-llama/llama_index/assets/22285038/884d1b2a-2386-4fbd-a51c-f715aefe7438">

**Comment by DBvc** [comment]
https://github.com/grantjenks/py-tree-sitter-languages/issues/64

**Comment by sansmoraxz** [comment]
@framsouza perhaps you can build the parser object outside and pass it into the CodeSplitter?

It was provided specifically to not couple with `tree-sitter-languages`.

**Comment by sansmoraxz** [comment]
@logan-markewich will it make sense to add version check for `tree-sitter` within the library?

```py
import pkg_resources
from packaging.version import Version
installed_treesitter_package = [(d.project_name, d.version) for d in pkg_resources.working_set if d.project_name.lower() == 'tree-sitter']
if len(installed_treesitter_package) == 0:
    raise ImportError("tree-sitter not installed")
else:
    print("tree-sitter installed")
    print("Version: ", installed_treesitter_package[0][1])
    if Version(installed_treesitter_package[0][1]) > Version('0.22.0'):
        print("Using tree-sitter version > 0.22.0")
        ... # create with new API
    else:
        print("Using tree-sitter version <= 0.22.0")
        ... # process using old API
```

**Comment by minki-j** [comment]
> @framsouza yea this seems like an issue with the tree-sitter version. I don't actually know what the solution is yet, but a band-aid fix was `pip install -U "tree-sitter<0.22.0"`

This worked for me with llama_index(version 0.10.65). Thank you

**Comment by framsouza** [comment]
```
llama-index==0.11.16
load_dotenv==0.1.0
tree_sitter_languages==0.22.0
llama-index-vector-stores-elasticsearch==0.3.2
llama-index-embeddings-openai==0.2.5
llama_index.llms.ollama==0.3.3
spacy==3.8.2
IPython==8.28.0
tabulate==0.9.0
```

The `CodeSplitter` seems to work, however, the `chunk_size` doesn't seem to be applied

**Comment by ericwb** [comment]
Around the fall of 2024 time frame, tree-sitter and tree-sitter-languages went through a bunch of breaking changes that I also experienced as part of one of my projects. The `tree-sitter-languages` library is pretty much defunct even though the package maintainer hasn't labeled it that way. You can still use it with older tree-sitter, but not newer.

The later versions of tree-sitter only interoperate with tree-sitter-<language> libraries. For example tree-sitter-python, tree-sitter-go, etc. There is no longer a single library for all the languages. 

https://pypi.org/project/tree-sitter-python/
https://pypi.org/project/tree-sitter-go/
https://pypi.org/project/tree-sitter-java/

The new way to use tree-sitter is more like:

```python
tree_sitter_lang = importlib.import_module(f"tree_sitter_{lang}")
language = tree_sitter.Language(tree_sitter_lang.language())
tree_sitter_parser = tree_sitter.Parser(language)
```

**Comment by ioo0s** [comment]
[tree-sitter-language-pack](https://github.com/Goldziher/tree-sitter-language-pack) is great work,  I can fast use any language👍

```python
from tree_sitter_language_pack import get_parser

rust_parser = get_parser('rust')
coder = CodeSplitter(language="rust", parser=rust_parser)
code_list = coder.split_text(demo_rust_code)
```
