### ISSUE TITLE
[Bug]: Milvus vector database：AttributeError: 'NoneType' object has no attribute 'condition'

### ISSUE THREAD

**Issue by shizhengLi** [run-llama/llama_index#13581]
### Bug Description

In function "get_question_retriever", when I pass all_nodes, which is a list of IndexNode, to the VectorStoreIndex, I get an error for MilvusVectorStore.

```
Traceback (most recent call last):
  File "/home/r/nodes2retrievers.py", line 221, in <module>
    nodes = qr.retrieve(" What is the rationale for continuing treatment with lorlatinib beyond disease progression in ALK-positive NSCLC patients, even though it is positioned as the final targeted ALK TKI treatment before chemotherapy")
  File "/home//anaconda3/envs/rag/lib/python3.9/site-packages/llama_index/core/base/base_retriever.py", line 229, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/home//anaconda3/envs/rag/lib/python3.9/site-packages/llama_index/core/retrievers/recursive_retriever.py", line 206, in _retrieve
    retrieved_nodes, _ = self._retrieve_rec(query_bundle, query_id=None)
  File "/home//anaconda3/envs/rag/lib/python3.9/site-packages/llama_index/core/retrievers/recursive_retriever.py", line 179, in _retrieve_rec
    nodes = obj.retrieve(query_bundle)
  File "/home/lishizheng/anaconda3/envs/rag/lib/python3.9/site-packages/llama_index/core/base/base_retriever.py", line 229, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/home//anaconda3/envs/rag/lib/python3.9/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 94, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/home//anaconda3/envs/rag/lib/python3.9/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 170, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/home//anaconda3/envs/rag/lib/python3.9/site-packages/llama_index/vector_stores/milvus/base.py", line 409, in query
    string_expr = f" {query.filters.condition.value} ".join(expr)
AttributeError: 'NoneType' object has no attribute 'condition'

```

However, when I pass the all_nodes to FaissVectorStore, There is no problem.

```

import os
import nest_asyncio
from llama_index.core.retrievers import RecursiveRetriever
from llama_index.core.storage.docstore import SimpleDocumentStore
from llama_index.core import Settings
from llama_index.core.schema import MetadataMode,IndexNode
nest_asyncio.apply()
from llama_index.core.node_parser import(
    SentenceSplitter
)

from llama_index.vector_stores.milvus import MilvusVectorStore
from llama_index.vector_stores.faiss import FaissVectorStore
import faiss

from llama_index.core import (
    VectorStoreIndex,
    ServiceContext,
    StorageContext,
    Document
)
from llama_index.core import Settings
from llama_index.core.schema import IndexNode
import re
from llama_index.core.schema import BaseNode, IndexNode
from modify_files.modify_keywordRetriever import KeywordTableGPTRetriever, KeywordTableRAKERetriever
from llama_index.core import RAKEKeywordTableIndex
nest_asyncio.apply()

from llama_index.core import Settings
import textwrap

import openai
openai.api_key=
openai.base_url=
import json

def get_question_retriever(doc_store_path,  similarity_top_k=5):
    all_nodes = []
    total_nodes = getnodes(doc_store_path)
    total_nodes = list(map(mapfun,total_nodes))
    ori2index = generate_index_nodes(total_nodes=total_nodes, mode="sq")
    for k, v in ori2index.items():
        all_nodes = all_nodes + v["sq"]
    all_nodes_dict = {node.node_id:node for node in total_nodes}  

    # dimensions of text-ada-embedding-002
    # d = 1536
    #faiss_index = faiss.IndexFlatL2(d)
    # For Faiss vector database， it can pass the test
   # vector_store = FaissVectorStore(faiss_index=faiss_index)

    
    # For Milnus vector database
    vector_store = MilvusVectorStore( 
        uri="./milvus_llamaindex.db",
        dim=1536, 
        overwrite=True
    )
    storage_context = StorageContext.from_defaults(vector_store=vector_store)


# =========================================
#   These lines of code resulted in an error.
# =========================================

    index = VectorStoreIndex(
        nodes=all_nodes, storage_context=storage_context, show_progress=True
    )

# =============================================

    vector_sq_retri = index.as_retriever(similarity_top_k = similarity_top_k)
    vector_sq_retri = RecursiveRetriever(
            "vector",
            retriever_dict={"vector":vector_sq_retri},
            node_dict = all_nodes_dict,
            verbose = True
        )
    return vector_sq_retri


def getnodes(persist_path)->list[BaseNode]:
    dc = SimpleDocumentStore.from_persist_path(persist_path)
    node_ids = [v for k, v in dc.get_all_document_hashes().items()]
    total_nodes = dc.get_nodes(node_ids=node_ids)
    return total_nodes


def generate_index_nodes(total_nodes, div_num=4, mode="text"):
    text_len = 0
    metadata_len = 0
    effient_len = 0
    ori2index = {}
    if mode == "text" and div_num == 1:
        for node in total_nodes:
            ori2index[node.id_] = {"st":[IndexNode.from_text_node(node,node.node_id)]}
        return ori2index
    if mode == "text":
        for node in total_nodes:
            node.excluded_llm_metadata_keys=[]
            text_len = len(node.text)
            metadata_len = len(node.get_metadata_str(mode=MetadataMode.LLM))
            effient_len = int(text_len/div_num + metadata_len)+int(text_len)/5
            small_splitter = SentenceSplitter(
                            chunk_size=effient_len ,
                            chunk_overlap=int(text_len)/8
                            )
     
            ori2index = {}
            sub_nodes = small_splitter.get_nodes_from_documents([node])
            st_nodes = [IndexNode.from_text_node(sn,node.node_id) for sn in sub_nodes]
            ori2index[node.id_] = {"st":st_nodes}
    elif mode=="sq":
        for node in total_nodes:
                
                pattern = re.compile(r'\d+\.\s*(.*?)\?')
                merge_que = node.metadata['questions_this_excerpt_can_answer']
                
                sq_inodes = [IndexNode(text=que,index_id=node.node_id) for que in pattern.findall(merge_que)]
                ori2index[node.id_] = {"sq":sq_inodes}
    return ori2index

def mapfun(node,forbid_keys = ["questions_this_excerpt_can_answer","excerpt_keywords"]):
    node.excluded_llm_metadata_keys = forbid_keys
    node.excluded_embed_metadata_keys = forbid_keys

    return node


if __name__ == "__main__":
  
    #queretriever
    qr = get_question_retriever("../formatDocStore.json",similarity_top_k=5)
    nodes = qr.retrieve(" What is the rationale for continuing treatment with lorlatinib beyond disease progression in ALK-positive NSCLC patients, even though it is positioned as the final targeted ALK TKI treatment before chemotherapy")
    print(nodes[0].text)


```

Thanks for your patience.

### Version

llama-index==0.10.18

### Steps to Reproduce

Just run the code.

**Comment by RussellLuo** [comment]
This problem was caused by #11566, which tried to address #11565. However, I think it may have made changes in the wrong place.
