### ISSUE TITLE
[Bug]: sec-filings reader load_data() TypeError

### ISSUE THREAD

**Issue by fdejax90** [run-llama/llama_index#13598]
### Bug Description

```python
from llama_index.readers.sec_filings import SECFilingsLoader

loader = SECFilingsLoader(tickers=["TSLA"], amount=1, filing_type="10-K", num_workers=1)

>>> ---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "[/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py", line 261](http://localhost:8889/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py#line=260), in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py", line 210](http://localhost:8889/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py#line=209), in _process_chunk
    return [fn(*args) for args in chunk]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py", line 210](http://localhost:8889/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py#line=209), in <listcomp>
    return [fn(*args) for args in chunk]
            ^^^^^^^^^
  File "[/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/site-packages/llama_index/readers/sec_filings/sec_filings.py", line 243](http://localhost:8889/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/site-packages/llama_index/readers/sec_filings/sec_filings.py#line=242), in get_text_from_url
    text = self.get_filing(
           ^^^^^^^^^^^^^^^^
TypeError: fake_decorator.<locals>.inner() got an unexpected keyword argument 'company'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[17], line 1
----> 1 loader.load_data()

File [~/.pyenv/versions/3.11.9/lib/python3.11/site-packages/llama_index/readers/sec_filings/base.py:77](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/site-packages/llama_index/readers/sec_filings/base.py#line=76), in SECFilingsLoader.load_data(self)
     72 with concurrent.futures.ThreadPoolExecutor(
     73     max_workers=thread_workers
     74 ) as executor:
     75     results = executor.map(self.multiprocess_run, self.tickers)
---> 77 for res in results:
     78     curr_tic = next(iter(res.keys()))
     79     for data in res[curr_tic]:

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:619](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py#line=618), in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield _result_or_cancel(fs.pop())
    620     else:
    621         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:317](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py#line=316), in _result_or_cancel(***failed resolving arguments***)
    315 try:
    316     try:
--> 317         return fut.result(timeout)
    318     finally:
    319         fut.cancel()

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:449](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py#line=448), in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:401](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py#line=400), in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py:58](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py#line=57), in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File [~/.pyenv/versions/3.11.9/lib/python3.11/site-packages/llama_index/readers/sec_filings/base.py:57](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/site-packages/llama_index/readers/sec_filings/base.py#line=56), in SECFilingsLoader.multiprocess_run(self, tic)
     53 with concurrent.futures.ProcessPoolExecutor(
     54     max_workers=self.num_workers
     55 ) as executor:
     56     results = executor.map(self.se.get_text_from_url, field_urls)
---> 57 for idx, res in enumerate(results):
     58     all_text, filing_type = res
     59     text_dict[tic].append(
     60         {
     61             "year": years[idx],
   (...)
     65         }
     66     )

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py:620](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py#line=619), in _chain_from_iterable_of_lists(iterable)
    614 def _chain_from_iterable_of_lists(iterable):
    615     """
    616     Specialized implementation of itertools.chain.from_iterable.
    617     Each item in *iterable* should be a list.  This function is
    618     careful not to keep references to yielded objects.
    619     """
--> 620     for element in iterable:
    621         element.reverse()
    622         while element:

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:619](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py#line=618), in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield _result_or_cancel(fs.pop())
    620     else:
    621         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:317](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py#line=316), in _result_or_cancel(***failed resolving arguments***)
    315 try:
    316     try:
--> 317         return fut.result(timeout)
    318     finally:
    319         fut.cancel()

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:449](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py#line=448), in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File [~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:401](http://localhost:8889/lab/workspaces/auto-X/tree/jason/~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py#line=400), in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

TypeError: fake_decorator.<locals>.inner() got an unexpected keyword argument 'company'```

### Version

 0.1.19

### Steps to Reproduce

```
pyenv local 3.11.9

pip install --upgrade pipenv

pipenv run pip install llama-index-readers-sec-filings
```

```python
from llama_index.readers.sec_filings import SECFilingsLoader
loader = SECFilingsLoader(tickers=["TSLA"], amount=1, filing_type="10-K", num_workers=1)

loader.load_data()
```

### Relevant Logs/Tracbacks

```shell
Started for TSLA
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py", line 210, in _process_chunk
    return [fn(*args) for args in chunk]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py", line 210, in <listcomp>
    return [fn(*args) for args in chunk]
            ^^^^^^^^^
  File "/Users/floriandejax/.pyenv/versions/3.11.9/lib/python3.11/site-packages/llama_index/readers/sec_filings/sec_filings.py", line 243, in get_text_from_url
    text = self.get_filing(
           ^^^^^^^^^^^^^^^^
TypeError: fake_decorator.<locals>.inner() got an unexpected keyword argument 'company'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[17], line 1
----> 1 loader.load_data()

File ~/.pyenv/versions/3.11.9/lib/python3.11/site-packages/llama_index/readers/sec_filings/base.py:77, in SECFilingsLoader.load_data(self)
     72 with concurrent.futures.ThreadPoolExecutor(
     73     max_workers=thread_workers
     74 ) as executor:
     75     results = executor.map(self.multiprocess_run, self.tickers)
---> 77 for res in results:
     78     curr_tic = next(iter(res.keys()))
     79     for data in res[curr_tic]:

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:619, in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield _result_or_cancel(fs.pop())
    620     else:
    621         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:317, in _result_or_cancel(***failed resolving arguments***)
    315 try:
    316     try:
--> 317         return fut.result(timeout)
    318     finally:
    319         fut.cancel()

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:449, in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File ~/.pyenv/versions/3.11.9/lib/python3.11/site-packages/llama_index/readers/sec_filings/base.py:57, in SECFilingsLoader.multiprocess_run(self, tic)
     53 with concurrent.futures.ProcessPoolExecutor(
     54     max_workers=self.num_workers
     55 ) as executor:
     56     results = executor.map(self.se.get_text_from_url, field_urls)
---> 57 for idx, res in enumerate(results):
     58     all_text, filing_type = res
     59     text_dict[tic].append(
     60         {
     61             "year": years[idx],
   (...)
     65         }
     66     )

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/process.py:620, in _chain_from_iterable_of_lists(iterable)
    614 def _chain_from_iterable_of_lists(iterable):
    615     """
    616     Specialized implementation of itertools.chain.from_iterable.
    617     Each item in *iterable* should be a list.  This function is
    618     careful not to keep references to yielded objects.
    619     """
--> 620     for element in iterable:
    621         element.reverse()
    622         while element:

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:619, in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield _result_or_cancel(fs.pop())
    620     else:
    621         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:317, in _result_or_cancel(***failed resolving arguments***)
    315 try:
    316     try:
--> 317         return fut.result(timeout)
    318     finally:
    319         fut.cancel()

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:449, in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

TypeError: fake_decorator.<locals>.inner() got an unexpected keyword argument 'company'
```

**Comment by fdejax90** [comment]
@dosu  The `llama-index-readers-sec-filings` package specifies compatibility with Python versions requires-python:>=3.9,<3.12

**Comment by logan-markewich** [comment]
sec-fillings had some weird hidden dependencies. Added to the actual dependencies.

This error is solved with that change (but tbh, I just get 403, but thats outside of the scope, this reader seems quite tacky haha)
