### ISSUE TITLE
[Bug]: An error occurs when parsing embedded table nodes.

### ISSUE THREAD

**Issue by zhaozhiming** [run-llama/llama_index#13612]
### Bug Description

When I used UnstructuredElementNodeParser to parse an embedded table, an error occurred. The error message is as follows:

```sh
Traceback (most recent call last):
  File "/Users/me/llamaindex-python/embed_table.py", line 21, in <module>
    raw_nodes = node_parser.get_nodes_from_documents(demo_file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/rag/lib/python3.11/site-packages/llama_index/core/node_parser/interface.py", line 76, in get_nodes_from_documents
    nodes = self._parse_nodes(documents, show_progress=show_progress, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/rag/lib/python3.11/site-packages/llama_index/core/node_parser/relational/base_element.py", line 120, in _parse_nodes
    nodes = self.get_nodes_from_node(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/rag/lib/python3.11/site-packages/llama_index/core/node_parser/relational/unstructured_element.py", line 70, in get_nodes_from_node
    nodes = self.get_nodes_from_elements(elements, node.metadata)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/rag/lib/python3.11/site-packages/llama_index/core/node_parser/relational/base_element.py", line 306, in get_nodes_from_elements
    start_char_idx = ref_doc_text.find(str(element.element))
                     ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
```

After tracing the code, I found that the issue lies in the get_nodes_from_elements method in the file llama_index/core/node_parser/relational/base_element.py. The problem arises because ref_doc_text is initialized as None, and the program does not check for nullity before directly calling the find method, resulting in the error:

```py
# llama_index/core/node_parser/relational/base_element.py
    def get_nodes_from_elements(
        self,
        elements: List[Element],
        metadata_inherited: Optional[Dict[str, Any]] = None,
        ref_doc_text: Optional[str] = None,
    ) -> List[BaseNode]:
           ......
           start_char_idx = ref_doc_text.find(str(element.element))
```

Additionally, I discovered that the ref_doc_text parameter is not passed in the method call:

```py
# llama_index/core/node_parser/relational/unstructured_element.py line 70
    nodes = self.get_nodes_from_elements(elements, node.metadata)
```

The same issue also appears in the reference in llama_index/core/node_parser/relational/llama_parse_json_element.py:

```py
# llama_index/core/node_parser/relational/llama_parse_json_element.py L36
    return self.get_nodes_from_elements(elements, node)
```

I am considering submitting a PR to address this, but I am not sure what the best solution would be. Should it be modified to reference it similarly to markdown_element.py?

```py
# llama_index/core/node_parser/relational/markdown_element.py L35-L37
        nodes = self.get_nodes_from_elements(
            elements, node, ref_doc_text=node.get_content()
        )
```

### Version

0.10.37

### Steps to Reproduce

The issue can be reproduced with the following test code:

```py
from pathlib import Path
from llama_index.readers.file import FlatReader
from llama_index.core.node_parser import UnstructuredElementNodeParser 

reader = FlatReader()
demo_file = reader.load_data(Path("demo.html"))
node_parser = UnstructuredElementNodeParser()

raw_nodes = node_parser.get_nodes_from_documents(demo_file)
```

You can use this demo file, but remember to change the file extension to html:
[demo.md](https://github.com/run-llama/llama_index/files/15384348/demo.md)

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/me/llamaindex-python/embed_table.py", line 21, in <module>
    raw_nodes = node_parser.get_nodes_from_documents(demo_file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/rag/lib/python3.11/site-packages/llama_index/core/node_parser/interface.py", line 76, in get_nodes_from_documents
    nodes = self._parse_nodes(documents, show_progress=show_progress, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/rag/lib/python3.11/site-packages/llama_index/core/node_parser/relational/base_element.py", line 120, in _parse_nodes
    nodes = self.get_nodes_from_node(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/rag/lib/python3.11/site-packages/llama_index/core/node_parser/relational/unstructured_element.py", line 70, in get_nodes_from_node
    nodes = self.get_nodes_from_elements(elements, node.metadata)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/miniconda3/envs/rag/lib/python3.11/site-packages/llama_index/core/node_parser/relational/base_element.py", line 306, in get_nodes_from_elements
    start_char_idx = ref_doc_text.find(str(element.element))
                     ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by logan-markewich** [comment]
Yes, it should be similar to the markdown element node parser
