### ISSUE TITLE
[Bug]: WordpressReader.load_data() fails when it encounters apassword protected post.

### ISSUE THREAD

**Issue by Torlach-LetsChat** [run-llama/llama_index#13625]
### Bug Description

When attempting to ingest data from a WordPress site with a single password protected post WordpressReader.load_data()  failed with the following:
Traceback (most recent call last):
  File "C:\Development\LetsChat\LetsChat\WordPress.py", line 10, in <module>
    documents = loader.load_data()
  File "C:\Python310\lib\site-packages\llama_index\readers\wordpress\base.py", line 43, in load_data
    soup = BeautifulSoup(body, "html.parser")
  File "C:\Python310\lib\site-packages\bs4\__init__.py", line 328, in __init__
    for (self.markup, self.original_encoding, self.declared_html_encoding,
  File "C:\Python310\lib\site-packages\bs4\builder\_htmlparser.py", line 361, in prepare_markup
    dammit = UnicodeDammit(
  File "C:\Python310\lib\site-packages\bs4\dammit.py", line 588, in __init__
    self.detector = EncodingDetector(
  File "C:\Python310\lib\site-packages\bs4\dammit.py", line 389, in __init__
    self.markup, self.sniffed_encoding = self.strip_byte_order_mark(markup)
  File "C:\Python310\lib\site-packages\bs4\dammit.py", line 474, in strip_byte_order_mark
    elif data[:3] == b'\xef\xbb\xbf':
TypeError: unhashable type: 'slice'

type(data)  is <class 'dict'>
data is {'rendered': '', 'protected': True}

### Version

llama-index                      0.5.9

### Steps to Reproduce

Create a wordpress site.
Create two posts.
Password protect one of the posts.
Publish posts.

Run the following:
from llama_index.readers.wordpress import WordpressReader

loader = WordpressReader(
    url=<site url>,
    username=<user name>,
    password=<password>!
)
documents = loader.load_data()

**Comment by Torlach-LetsChat** [comment]
How and when does the new code (which appears to work) make it into production? How are consumers notified?
