### ISSUE TITLE
[Bug]: I encountered an issue while running the official website process

### ISSUE THREAD

**Issue by LJ-Hao** [run-llama/llama_index#13693]
### Bug Description

Here is the example I try with Ubantu 20.04```https://docs.llamaindex.ai/en/stable/examples/multi_modal/ollama_cookbook/```
and I get problem as follow:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_backends/sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mulitRAG.py", line 97, in <module>
    response = mm_program(query_str="Can you summarize what is in the image?")
  File "/usr/local/lib/python3.8/dist-packages/llama_index/core/program/multi_modal_llm_program.py", line 104, in __call__
    response = self._multi_modal_llm.complete(
  File "/usr/local/lib/python3.8/dist-packages/llama_index/multi_modal_llms/ollama/base.py", line 160, in complete
    response = self._client.generate(
  File "/usr/local/lib/python3.8/dist-packages/ollama/_client.py", line 126, in generate
    return self._request_stream(
  File "/usr/local/lib/python3.8/dist-packages/ollama/_client.py", line 97, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
  File "/usr/local/lib/python3.8/dist-packages/ollama/_client.py", line 68, in _request
    response = self._client.request(method, url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

```

### Version

0.10.38

### Steps to Reproduce

```
response = mm_program(query_str="Can you summarize what is in the image?")
for res in response:
    print(res)
```

**Comment by LJ-Hao** [comment]
> The error message `[Errno 111] Connection refused` indicates that your application is unable to connect to the Ollama API server. Here are some steps to resolve this issue:
> 
> 1. **Ensure the Ollama API Server is Running**:
>    Make sure the Ollama API server is running. You can start it with:
>    ```shell
>    ollama serve
>    ```
> 2. **Verify the Server URL and Port**:
>    Ensure the server is running on the correct URL and port. By default, it should be `http://localhost:11434`. If it's different, update the `base_url` accordingly:
>    ```python
>    ollama_model = OllamaMultiModal(base_url="http://0.0.0.0:8001", model="your_model_name")
>    ```
> 3. **Check for Network Issues**:
>    Ensure there are no network issues, such as firewall settings blocking the connection.
> 4. **Set the Request Timeout**:
>    Avoid timeouts by setting the `request_timeout` parameter:
>    ```python
>    ollama_instance = OllamaMultiModal(
>        model="your_model_name",
>        request_timeout=30.0  # Set the timeout to 30 seconds
>    )
>    ```
> 5. **Check Server Logs**:
>    If the server is running but the issue persists, check the server logs for any errors.
> 
> Here is an example of how to initialize the `OllamaMultiModal` class with the correct `base_url` and `request_timeout`:
> 
> ```python
> from llama_index.multi_modal_llms.ollama import OllamaMultiModal
> 
> ollama_model = OllamaMultiModal(
>     base_url="http://localhost:11434",  # Update this if your server is running on a different URL or port
>     model="your_model_name",
>     request_timeout=30.0  # Set the timeout to 30 seconds
> )
> 
> response = ollama_model.complete("Can you summarize what is in the image?")
> for res in response:
>     print(res)
> ```
> 
> Following these steps should help resolve the connection error. If the issue persists, please provide more details about your server setup and any additional error messages.
> 
> #### Details
> _To continue the conversation, mention @dosu._

Thank your very much, that helps me a lot
