### ISSUE TITLE
[Question]: pydantic.v1.error_wrappers.ValidationError: 7 validation errors for QueryEndEvent

### ISSUE THREAD

**Issue by uniltone** [run-llama/llama_index#13706]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### The following is the code that reported the error. I want to merge the vector_tool with sql_tool.

import os,sys
import time
import gradio as gr
# import threading 
os.environ["OPENAI_API_KEY"] = "your openid api_key"
os.environ["OPENAI_API_BASE"] = "your openai api base"
time_start = time.time()
from llama_index.core import Settings,get_response_synthesizer,SQLDatabase
from llama_index.legacy  import VectorStoreIndex, SimpleDirectoryReader, StorageContext, load_index_from_storage,Prompt,ServiceContext,set_global_service_context,SummaryIndex
from llama_index.core.memory import ChatMemoryBuffer
from llama_index.llms.openai import OpenAI
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.legacy.node_parser import SentenceSplitter
from llama_index.legacy.indices.struct_store.sql_query import NLSQLTableQueryEngine
import llama_index.core
from llama_index.core.tools import QueryEngineTool
from llama_index.core.retrievers import VectorIndexAutoRetriever
from llama_index.core.vector_stores import MetadataInfo, VectorStoreInfo
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.query_engine import SQLAutoVectorQueryEngine
from llama_index.core.callbacks import (
    CallbackManager,
    LlamaDebugHandler,
    CBEventType,
)
llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])
node_parser = SentenceSplitter()
Settings.llm = OpenAI(
    model="gpt-3.5-turbo",
    temperature=0.1,
    max_tokens=2200,
)
Settings.embed_model = OpenAIEmbedding(
    model="text-embedding-3-small", embed_batch_size=256
)
Settings.chunk_size = 1024
#加载数据库
from sqlalchemy import (
    create_engine,
    MetaData,
    Table,
    Column,
    String,
    Integer,
    select,
    text,
)
from llama_index.core.query_engine import SQLTableRetrieverQueryEngine
def load_database():
    '''
    加载数据库
    '''
    engine = create_engine("sqlite:///database/abc.db")
    metadata_obj = MetaData()
    sql_database = SQLDatabase(engine,include_tables=["boat_info","boat_weight"],sample_rows_in_table_info=2) 
    from llama_index.core.objects import (
        SQLTableNodeMapping,
        ObjectIndex,
        SQLTableSchema,
    )
    table_schema_objs = [
        (SQLTableSchema(table_name="boat_info",context_str=("这是一张表，存储每艘船只名称，国家，尺寸，服役时间（年）"))),
        (SQLTableSchema(table_name="boat_weight",context_str=("这是一张表，存储每艘船只重量（吨）,boat_id对应boat_info表的id")))
    ]  # add a SQLTableSchema for each table
    table_node_mapping = SQLTableNodeMapping(sql_database)
    obj_index = ObjectIndex.from_objects(
        table_schema_objs,
        table_node_mapping,
        VectorStoreIndex,
    )
    query_engine = SQLTableRetrieverQueryEngine(
        sql_database, obj_index.as_retriever(similarity_top_k=3)
    )
    return query_engine

def load_vector_index():
    '''
    加载索引
    '''
    PERSIST_DIR = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))+".\storage"
    PATH = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))+'\data'
    service_content = ServiceContext.from_defaults(chunk_size=1024)
    vector_query_engines=[]
    if not os.path.exists(PERSIST_DIR):
        documents = SimpleDirectoryReader(input_dir=PATH+'/report').load_data(show_progress=True)
        index = VectorStoreIndex.from_documents(documents,service_context=service_content)
        vector_query_engines.append(index.as_query_engine())
        index.storage_context.persist(persist_dir=PERSIST_DIR+'/report')
        documents = SimpleDirectoryReader(input_dir=PATH+'/rule').load_data(show_progress=True)
        index = VectorStoreIndex.from_documents(documents,service_context=service_content)
        vector_query_engines.append(index.as_query_engine())
        index.storage_context.persist(persist_dir=PERSIST_DIR+'/rule')
    else:
        print("加载向量索引") 
        storage_context = StorageContext.from_defaults(persist_dir=PERSIST_DIR+'/report')
        index = load_index_from_storage(storage_context,callback_manager=callback_manager,embed_model=Settings.embed_model)
        vector_query_engines.append(index.as_query_engine())
        storage_context = StorageContext.from_defaults(persist_dir=PERSIST_DIR+'/rule')
        index = load_index_from_storage(storage_context,callback_manager=callback_manager,embed_model=Settings.embed_model)
        vector_query_engines.append(index.as_query_engine())
    # vector_store_info = VectorStoreInfo(
    #     content_info="articles about shipping industry related information",
    #     metadata_info=[MetadataInfo(name="title", type="str", description="articles about shipping industry related information"),],
    # )
    # vector_auto_retriever = VectorIndexAutoRetriever(
    #     index, 
    #     vector_store_info=vector_store_info,
    #     service_context=service_content
    # )
    # retriever_query_engine = RetrieverQueryEngine.from_args(
    #     vector_auto_retriever,
    # )
    print("断点1")
    return vector_query_engines

def load_SQLAutoVectorQueryEngine(sql_query_engine,retriever_query_engine):
    sql_tool = QueryEngineTool.from_defaults(
        query_engine=sql_query_engine,
        description=(
            "Useful for translating a natural language query into a SQL query over"
            " a database containing: boat_name, country,weight,age of"
            " each boat"
            ),
        return_direct=True
    )
    print("断点2")
    # vector_tool = QueryEngineTool.from_defaults(
    #     query_engine=retriever_query_engine,
    #     description=(
    #         f"Useful for answering semantic questions about shipping industry related information"
    #     ),
    # )
    boats = [
        "关于船舶行业的研究报告",
        "关于船舶行业的规范",
    ]
    vector_tools = []
    for boat, query_engine in zip(boats, retriever_query_engine):
        print("断点3")
        vector_tool = QueryEngineTool.from_defaults(
            query_engine=query_engine,
            name=boat,
            description=f"Useful for answering semantic questions about {boat}",
        )
        vector_tools.append(vector_tool)
    # query_engine = SQLAutoVectorQueryEngine(
    #     sql_tool, vector_tool,llm=Settings.llm,
    # )
    
    from llama_index.core.query_engine import RouterQueryEngine,SQLJoinQueryEngine
    from llama_index.core.selectors import (PydanticMultiSelector,PydanticSingleSelector,LLMSingleSelector,LLMMultiSelector)
    query_engine = RouterQueryEngine(
        selector=LLMSingleSelector.from_defaults(),
        query_engine_tools=([sql_tool]+vector_tools),
        verbose=True,
    )
    print("断点4")
    return query_engine
sql_query_engine=load_database()
retriever_query_engine=load_vector_index()
query_engine = load_SQLAutoVectorQueryEngine(sql_query_engine,retriever_query_engine)
print("断点5")
# query_engine.callback_manager = callback_manager
response = query_engine.query("重大技术装备推广目录的通知?")
print(response)

error:
加载向量索引
断点1
断点2
断点3
断点3
断点4
断点5
Selecting query engine 1: The question is related to a research report about the shipbuilding industry, which is more closely related to choice 2..
Selecting query engine 2: The question is related to regulations in the shipbuilding industry, which is less relevant to choice 3..
重大技术装备推广目录的通知? The notice is about the release of the "Guidance Catalog for the Promotion and Application of Major Technical Equipment - Shipbuilding and Ocean Engineering Field (2022 Edition)" by the China Shipbuilding Industry Association.
Traceback (most recent call last):
  File "e:\AiCompany\llama-index\llama_agent_copy_2.py", line 168, in <module>
    response = query_engine.query("重大技术装备推广目录的通知?")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda\Lib\site-packages\llama_index\core\base\base_query_engine.py", line 55, in query
    dispatch_event(QueryEndEvent(query=str_or_query_bundle, response=query_result))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 7 validation errors for QueryEndEvent
response -> source_nodes -> 0 -> node
  Can't instantiate abstract class BaseNode with abstract methods get_content, get_metadata_str, get_type, hash, set_content (type=type_error)
response -> source_nodes -> 1 -> node
  Can't instantiate abstract class BaseNode with abstract methods get_content, get_metadata_str, get_type, hash, set_content (type=type_error)
response -> source_nodes -> 2 -> node
  Can't instantiate abstract class BaseNode with abstract methods get_content, get_metadata_str, get_type, hash, set_content (type=type_error)
response -> source_nodes -> 3 -> node
  Can't instantiate abstract class BaseNode with abstract methods get_content, get_metadata_str, get_type, hash, set_content (type=type_error)
response
  instance of StreamingResponse, tuple or dict expected (type=type_error.dataclass; class_name=StreamingResponse)
response
  instance of AsyncStreamingResponse, tuple or dict expected (type=type_error.dataclass; class_name=AsyncStreamingResponse)
response
  instance of PydanticResponse, tuple or dict expected (type=type_error.dataclass; class_name=PydanticResponse)

**Comment by uniltone** [comment]
How to improve the source code?@dosu

**Comment by uniltone** [comment]
But I am using RouterQueryEngine, not SQLAutoVectorQueryEngine @dosu

**Comment by uniltone** [comment]
I don’t understand, I can’t@dosu
