### ISSUE TITLE
[Bug]: OpenAILike Can't Parse Result

### ISSUE THREAD

**Issue by chigkim** [run-llama/llama_index#13735]
### Bug Description

When I try to communicate with llama.cpp with OpenAILike, it throws an error: "TypeError: 'NoneType' object is not subscriptable"
However, if I use just regular OpenAI library, not from llamaindex, \it works.

### Version

llama-index-core 0.10.38.post2, llama-index-llms-openai-like 0.1.3

### Steps to Reproduce

!pip install llama-index-llms-openai-like
from llama_index.llms.openai_like import OpenAILike
from llama_index.core.llms import ChatMessage
base_url = "http://localhost:8080/v1/"
api_key = "api"
llm = OpenAILike(model="model", api_base=base_url, api_key=api_key)
system = ChatMessage(role="system", content="You are a helpful assistant.")
message = ChatMessage(role="user", content="Hello!")
messages = [system, message]
response = llm.chat(messages)

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\llama_index\llms\openai_like\base.py", line 103, in chat
    completion_response = self.complete(prompt, formatted=True, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\llama_index\llms\openai_like\base.py", line 88, in complete
    return super().complete(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\llama_index\core\llms\callbacks.py", line 359, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\llama_index\llms\openai\base.py", line 320, in complete
    return complete_fn(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\tenacity\__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\tenacity\__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\tenacity\__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\tenacity\__init__.py", line 390, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chigo\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chigo\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\tenacity\__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "D:\code\python\VOLlama\.venv\Lib\site-packages\llama_index\llms\openai\base.py", line 514, in _complete
    text = response.choices[0].text
           ~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by chigkim** [comment]
I made sure model= is not None. It's still the same.

**Comment by chigkim** [comment]
For more info, this throws the error: TypeError: 'NoneType' object is not subscriptable.

```
from llama_index.llms.openai_like import OpenAILike
from llama_index.core.llms import ChatMessage
from openai import OpenAI
base_url = "http://localhost:8080/v1/"
api_key = "api"
client = OpenAI(base_url=base_url, api_key=api_key)
ids = [i.id for i in list(client.models.list().data)]
model = ids[0]
llm = OpenAILike(model=model, api_base=base_url, api_key=api_key, max_tokens=100)
system = ChatMessage(role="system", content="You are a helpful assistant.")
message = ChatMessage(role="user", content="Hello!")
messages = [system, message]
response = llm.stream_chat(messages)
```

This works perfectly. Continuing from the code above.

```
system = {"role": "system", "content": "You are a helpful assistant."}
message = {"role": "user", "content": "Hi, who are you?"}
messages = [system, message]
response = client.chat.completions.create(messages=messages, model=model, max_tokens=100)
print(response.choices[0].message.content)
```

**Comment by PkmX** [comment]
It seems like it is hitting the `/v1/completions` endpoint and expecting the completion response rather than chat endpoint `/v1/chat/completions`.

I was able to workaround this by setting `llm.is_chat_model = True`.

**Comment by HarrisDePerceptron** [comment]
@PkmX this works. also i had the api base as `http://localhost:8000/v1`, this worlds on VLLM but had to remove the 
"v1" from the url and also set the is_chat_model. with VLLM this worked fine
