### ISSUE TITLE
[Bug]:<MilvusException:(code=1100,message=the length (79145) of dynamic field exceeds max length (65536): invalid parameter[expected=valid length dynamic field][actual=length exceeds max length

### ISSUE THREAD

**Issue by gfoxlin** [run-llama/llama_index#13752]
### Bug Description

Question 1:
    Use a little txt file: The Milvus call the function ‘_create_hybrid_index()’ but the collection is not call 'self._conllection.load()',then the collection cant retrieve. 
Question 2: 
    Use a little bigger PDF file: call the create index function 'VectorStoreIndex(nodes,embed_model=embed_model, transformers=transformers,storage_context=storage_context)' then  report the error!
    <MilvusException:(code=1100,message=the length (79145) of dynamic field exceeds max length (65536): invalid parameter[expected=valid length dynamic field][actual=length exceeds max length

### Version

0.10.38

### Steps to Reproduce

# milvus
       milvus_vector_store = MilvusVectorStore(
            uri=CFG.milvus_uri,
            collection_name=CFG.collection_name,
            dim=512,#512
            overwrite=args.overwrite,
            enable_sparse=True,
            sparse_embedding_function=ExampleEmbeddingFunction(),
            hybrid_ranker="RRFRanker",
            hybrid_ranker_params={"k": 60},
        )

     # node parser
       node_parser = SentenceWindowNodeParser.from_defaults(
            # how many sentences on either side to capture
            window_size=3,
            # the metadata key that holds the window of surrounding sentences
            window_metadata_key="window",
            # the metadata key that holds the original sentence
            original_text_metadata_key="original_sentence",
        )
        nodes = node_parser.get_nodes_from_documents(documents)
        print("Node length = "+ str(len(nodes)))# Output : Node length = 932
# create index
       index = VectorStoreIndex(nodes,embed_model=embed_model, transformers=transformers,storage_context=storage_context)

**Comment by gfoxlin** [comment]
& Use the hybrid retrive the file index very very slowly.

**Comment by gfoxlin** [comment]
@dosu How to fix the error： the length (79145) of dynamic field exceeds max length (65536)? Whitch params can limit the length output?

**Comment by RussellLuo** [comment]
Hi @gfoxlin, as for Question 2, [65535 is the hard limit of a string](https://milvus.io/docs/limitations.md#Length-of-a-string) in Milvus. Therefore, we should ensure that the length of each TextNode does not exceed this limit.

I don't know the details of your PDF, but I guess the text in some nodes you obtained have already exceeded 65536. You can try to print the possible nodes as below:

```python
...

nodes = node_parser.get_nodes_from_documents(documents)
for i, node in enumerate(nodes):
    print(f"Text length of node {i}: {len(node.text)}")

...
```

If that's the case, there might be some problem with your PDF when using the default `sentence_splitter`:

https://github.com/run-llama/llama_index/blob/038d5105b684e5286b5771e7722ad3a9e3e8ec75/llama-index-core/llama_index/core/node_parser/text/sentence_window.py#L70

You could do some analysis on your PDF and try out alternative splitter by explicitly specify it:

```python
node_parser = SentenceWindowNodeParser.from_defaults(
    ...
    sentence_splitter=<YOUR-SPLITTER-HERE>,
    ...
)
```

**Comment by gfoxlin** [comment]
Hi @RussellLuo Thanks !
 Im sure the len(nodes) = 931 and the len(node.text)<65535! But it works well,when delete the hybrid params;

Now another new error ：pymilvus.exceptions.ParamError: <ParamError: (code=1, message=invalid input for sparse float vector)>


Generating embeddings: 100%|██████████| 248/248 [00:47<00:00,  5.27it/s]
RPC error: [insert_rows], <ParamError: (code=1, message=invalid input for sparse float vector)>, <Time:{'RPC start': '2024-05-28 17:09:59.638147', 'RPC error': '2024-05-28 17:09:59.824333'}>

**Comment by gfoxlin** [comment]
Hi @RussellLuo I changed the code like this But it didnt work too.
```
        node_parser = SentenceWindowNodeParser.from_defaults(
            # how many sentences on either side to capture
            window_size=2,
            sentence_splitter=SentenceSplitter(chunk_size=CFG.chunk_size, chunk_overlap=CFG.chunk_overlap),
            # the metadata key that holds the window of surrounding sentences
            window_metadata_key="window",
            # the metadata key that holds the original sentence
            original_text_metadata_key="original_sentence",
        )

```
## Error info
Loading Embedder...
Parsing nodes:   0%|▎                                                                                | 1/237 [00:00<00:00, 5447.15it/s]
Traceback (most recent call last):
  File "/home/mishulin/llm-gen-report/app/core/rag/loader.py", line 149, in <module>
    data_loader.ingest(embed_model=embed_model, llm=llm)
  File "/home/mishulin/llm-gen-report/app/core/rag/loader.py", line 98, in ingest
    nodes = node_parser.get_nodes_from_documents(documents,show_progress=True)
  File "/home/mishulin/.conda/envs/llamaindex310/lib/python3.10/site-packages/llama_index/core/node_parser/interface.py", line 129, in get_nodes_from_documents
    nodes = self._parse_nodes(documents, show_progress=show_progress, **kwargs)
  File "/home/mishulin/.conda/envs/llamaindex310/lib/python3.10/site-packages/llama_index/core/node_parser/text/sentence_window.py", line 96, in _parse_nodes
    nodes = self.build_window_nodes_from_documents([node])
  File "/home/mishulin/.conda/envs/llamaindex310/lib/python3.10/site-packages/llama_index/core/node_parser/text/sentence_window.py", line 108, in build_window_nodes_from_documents
    text_splits = self.sentence_splitter(text)
  File "/home/mishulin/.conda/envs/llamaindex310/lib/python3.10/site-packages/llama_index/core/node_parser/interface.py", line 157, in __call__
    return self.get_nodes_from_documents(nodes, **kwargs)
  File "/home/mishulin/.conda/envs/llamaindex310/lib/python3.10/site-packages/llama_index/core/node_parser/interface.py", line 124, in get_nodes_from_documents
    doc_id_to_document = {doc.id_: doc for doc in documents}
  File "/home/mishulin/.conda/envs/llamaindex310/lib/python3.10/site-packages/llama_index/core/node_parser/interface.py", line 124, in <dictcomp>
    doc_id_to_document = {doc.id_: doc for doc in documents}
AttributeError: 'str' object has no attribute 'id_'

**Comment by RussellLuo** [comment]
To make `node_parser.get_nodes_from_documents()` work properly, you need to pass a list of [Document](https://github.com/run-llama/llama_index/blob/038d5105b684e5286b5771e7722ad3a9e3e8ec75/llama-index-core/llama_index/core/schema.py#L631) (other than a list of str) for the first parameter.

**Comment by gfoxlin** [comment]
> To make `node_parser.get_nodes_from_documents()` work properly, you need to pass a list of [Document](https://github.com/run-llama/llama_index/blob/038d5105b684e5286b5771e7722ad3a9e3e8ec75/llama-index-core/llama_index/core/schema.py#L631) (other than a list of str) for the first parameter. For convenience, you can leverage [SimpleDirectoryReader](https://docs.llamaindex.ai/en/stable/module_guides/loading/simpledirectoryreader/#usage):
> 
> ```python
> documents = SimpleDirectoryReader("path/to/directory").load_data()
> ```

@RussellLuo Thanks! I dont find any quesiton in codes,please help me to check them all. the code any question?
```
     # The model has been downloaded to the 'models' local folder
     # 1. embedding model = "models/bge-small-zh-v1.5"
     # 2. BGEM3FlagModel("models/bge-m3", use_fp16=False)

       documents = SimpleDirectoryReader("datasets/").load_data()

        milvus_vector_store = MilvusVectorStore(
            uri=CFG.milvus_uri,
            collection_name=CFG.collection_name,
            dim=512,
            overwrite=True,
            enable_sparse=True,
           # as the llama-index milvus example
            sparse_embedding_function=ExampleEmbeddingFunction(),
            hybrid_ranker="RRFRanker",
            hybrid_ranker_params={"k": 60},
        )

        node_parser = SentenceWindowNodeParser.from_defaults(
            window_size=2,
           #Last question as you suggest add this line.then get the error (AttributeError: 'str' object has no attribute 'id_')
            sentence_splitter=SentenceSplitter(chunk_size=400, chunk_overlap=20),
            window_metadata_key="window",
            original_text_metadata_key="original_sentence",
        )
        nodes = node_parser.get_nodes_from_documents(documents,show_progress=True)
        for i, node in enumerate(nodes):
            print(f"Text length of node {i}: {len(node.text)}")
            if len(node.text)>65535:
               # no one 
                break
        storage_context = StorageContext.from_defaults(vector_store=milvus_vector_store)
        index = VectorStoreIndex(nodes,embed_model=embed_model, storage_context=storage_context,show_progress=True)
     
```

**Comment by RussellLuo** [comment]
@gfoxlin Try this instead:

```python
node_parser = SentenceWindowNodeParser.from_defaults(
    ...
    # 1. This parameter only accepts a function whose signature is `(str) -> list[str]`
    # 2. Try a smaller `chunk_size` since the final length Milvus got is N times greater than `chunk_size`
    sentence_splitter=SentenceSplitter(chunk_size=100, chunk_overlap=20).split_text,
    ...
)
```

The reason for the second comment is complicated. Milvus hybrid retrieval (i.e. `enable_sparse=True`) will [enable dynamic field](https://milvus.io/docs/enable-dynamic-field.md):

https://github.com/run-llama/llama_index/blob/03bb37fa2334a9a02c47363f64980602ac747d22/llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py#L567-L584

As shown above, this feature will cause all undefined fields (i.e. fields whose names are not "id", "embedding" or "sparse_embedding") to be merged into a single dynamic field. Therefore, it is possible for the length of this merged field to exceed 65535.

**Comment by weiweizwc98** [comment]
I encountered the exact same problem as you.

**Comment by zydmtaichi** [comment]
I encountered the same problem, @RussellLuo 's answer is very helpful, thanks a lot

**Comment by tonypeng1** [comment]
I also got this error when saving the nodes from using llamaparse with LlamaParseJsonNodeParser() into a Milvus database created by MilvusVectorStore(). 

How to resolve this if I still want to keep using Milvus database?

**Comment by micuentadecasa** [comment]
I have the same issue, what is the solution?

**Comment by bubl-ai** [comment]
I just posted this question which is also similar to this problem. On my end I am not working with texts I am working with images.
https://github.com/run-llama/llama_index/issues/16763

**Comment by micuentadecasa** [comment]
Hi @bubl-ai , I have checked and seems to be similar to my issue, the strange thing is that in Milvus lite it doesn't happens but in Milvus happens, I suppose that is because Lite runs usually on a laptop and there is no issue with the size. 
The thing is that I did a first approach reducing the size of the metadata but it didn't worked, and I thought that maybe there was some parameter configuration thing,  I will have to try again.

still I'm considering also two possible workarounds:
- I'm not sure if the metadata is the issue, maybe is the embedding field, I will try to reduce the chunk size
- I will try to modify the enable_dynamic_field=True in the schema, in this thread @RussellLuo  suggests that it works, maybe someone can mention if it worked for them.

**Comment by logan-markewich** [comment]
The main issue here is the sentence window node parser is putting the "window" into the node metadata. When the node is serialized, the size might be too big for milvus

The suggestions here seem sufficient. If anyone is willing to open a PR with better fix, do it! But going to close this out for now.
