### ISSUE TITLE
GPTPandasIndex could not handle long query and threw EOL exception

### ISSUE THREAD

**Issue by justinzyw** [run-llama/llama_index#1378]
GPTPandasIndex.query(): when Pandas Instruction gets too long, an EOL exception was thrown (shown as below). Could elimnate the error by using less conditions but hopefully the program can handle longer Pandas Instruction

```
> Pandas Output: There was an error running the output as Python code. Error message: EOL while scanning string literal (<unknown>, line 2)
Traceback (most recent call last):
  File "C:\Users\justin\AppData\Local\Programs\Python\Python39\lib\site-packages\gpt_index\indices\struct_store\pandas_query.py", line 49, in default_output_processor
    tree = ast.parse(output)
  File "C:\Users\justin\AppData\Local\Programs\Python\Python39\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 2
    df[(df['产品条件名称'].str.contains('整存整取定期存款|约定期限|利率|存款人|支取本息|存期|个人|单位|逐笔计息法|挂牌公告利率')) | (df['产品条件描述'].str.contains('整存整取定期存款|约定期限|利率|存款人|支取本息|存期|个人|单位|逐笔计息法|挂牌公告利率'))]['产品条件
                                                                                                                                                                             ^
SyntaxError: EOL while scanning string literal
```

**Comment by ricardosantosduarte** [comment]
I'm having a similar problem on this, error below

```
Traceback (most recent call last):
  File ".../python3.11/site-packages/llama_index/query_engine/pandas_query_engine.py", line 50, in default_output_processor
    tree = ast.parse(output)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 2
```
