### ISSUE TITLE
ComposableGraph with only local models and embeddings

### ISSUE THREAD

**Issue by erlebach** [run-llama/llama_index#13788]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am writing a demonstration code using `ComposableGraph` that uses local models only. However, the code wants to use the OpenAI language model. Here is my code: 
```
~
sample_ComposableGraph.py [+]                                                                           1,1            All
from llama_index.core import ComposableGraph, SimpleDirectoryReader, TreeIndex, SummaryIndex
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings
from llama_index.llms.ollama import Ollama
from llama_index.core import set_global_handler
from llama_index.core import ServiceContext
from llama_index.core.node_parser import SentenceSplitter

# set_global_handler("arize_phoenix")

# Without this command, OpenAI model is used
embedding_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5"  # small model
)
llm = Ollama(model="phi3:latest", request_timeout=600.0, temperature=0.7)

Settings.llm = llm
Settings.embed_model = embedding_model
Settings.node_parser = SentenceSplitter(chunk_size=512, chunk_overlap=20)
Settings.num_output = 512
Settings.context_window = 3900

print("Settings: ", Settings)
#quit()

print("llm= ", llm)
print("embed_model= ", embedding_model)

documents = SimpleDirectoryReader("files").load_data()
index1 = TreeIndex.from_documents([documents[0]])
index2 = TreeIndex.from_documents([documents[1]])
print(f"{index1=}")
print(f"{index2=}")
summary1 = "A short introduction to ancient Rome"
summary2 = "Some facts about dogs"

# Create the service context with the custom LLM and embedding model
#service_context = ServiceContext(llm=llm, embed_model=embedding_model)

# ERROR. For some reason, the AI LLM is invoked.
graph = ComposableGraph.from_indices(
    SummaryIndex, [index1, index2],
    index_summaries=[summary1, summary2] #,
    #service_context=service_context
)
```
Here is the error message: 
```
/Users/erlebach/src/2024/llama_index_gordon/Building-Data-Driven-Applications-with-LlamaIndex/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Settings:  _Settings(_llm=Ollama(callback_manager=<llama_index.core.callbacks.base.CallbackManager object at 0x32699e0c0>, system_prompt=None, messages_to_prompt=<function messages_to_prompt at 0x157c20720>, completion_to_prompt=<function default_completion_to_prompt at 0x157c9a0c0>, output_parser=None, pydantic_program_mode=<PydanticProgramMode.DEFAULT: 'default'>, query_wrapper_prompt=None, base_url='http://localhost:11434', model='phi3:latest', temperature=0.7, context_window=3900, request_timeout=600.0, prompt_key='prompt', json_mode=False, additional_kwargs={}), _embed_model=HuggingFaceEmbedding(model_name='BAAI/bge-small-en-v1.5', embed_batch_size=10, callback_manager=<llama_index.core.callbacks.base.CallbackManager object at 0x32699e0c0>, num_workers=None, max_length=512, normalize=True, query_instruction=None, text_instruction=None, cache_folder=None), _callback_manager=<llama_index.core.callbacks.base.CallbackManager object at 0x32699e0c0>, _tokenizer=None, _node_parser=SentenceSplitter(include_metadata=True, include_prev_next_rel=True, callback_manager=<llama_index.core.callbacks.base.CallbackManager object at 0x31aa754f0>, id_func=<function default_id_func at 0x157ce4360>, chunk_size=512, chunk_overlap=20, separator=' ', paragraph_separator='\n\n\n', secondary_chunking_regex='[^,.;。？！]+[,.;。？！]?'), _prompt_helper=PromptHelper(context_window=3900, num_output=512, chunk_overlap_ratio=0.1, chunk_size_limit=None, separator=' '), _transformations=None)
llm=  callback_manager=<llama_index.core.callbacks.base.CallbackManager object at 0x32699e0c0> system_prompt=None messages_to_prompt=<function messages_to_prompt at 0x157c20720> completion_to_prompt=<function default_completion_to_prompt at 0x157c9a0c0> output_parser=None pydantic_program_mode=<PydanticProgramMode.DEFAULT: 'default'> query_wrapper_prompt=None base_url='http://localhost:11434' model='phi3:latest' temperature=0.7 context_window=3900 request_timeout=600.0 prompt_key='prompt' json_mode=False additional_kwargs={}
embed_model=  model_name='BAAI/bge-small-en-v1.5' embed_batch_size=10 callback_manager=<llama_index.core.callbacks.base.CallbackManager object at 0x32699e0c0> num_workers=None max_length=512 normalize=True query_instruction=None text_instruction=None cache_folder=None
index1=<llama_index.core.indices.tree.base.TreeIndex object at 0x31bc9ff20>
index2=<llama_index.core.indices.tree.base.TreeIndex object at 0x3272c5a90>
Traceback (most recent call last):
  File "/Users/erlebach/src/2024/llama_index_gordon/Building-Data-Driven-Applications-with-LlamaIndex/.venv/lib/python3.12/site-packages/llama_index/core/llms/utils.py", line 41, in resolve_llm
    validate_openai_api_key(llm.api_key)
  File "/Users/erlebach/src/2024/llama_index_gordon/Building-Data-Driven-Applications-with-LlamaIndex/.venv/lib/python3.12/site-packages/llama_index/llms/openai/utils.py", line 407, in validate_openai_api_key
    raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/erlebach/src/2024/llama_index_gordon/Building-Data-Driven-Applications-with-LlamaIndex/ch5/sample_ComposableGraph.py", line 41, in <module>
    graph = ComposableGraph.from_indices(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erlebach/src/2024/llama_index_gordon/Building-Data-Driven-Applications-with-LlamaIndex/.venv/lib/python3.12/site-packages/llama_index/core/indices/composability/graph.py", line 63, in from_indices
    service_context = service_context or ServiceContext.from_defaults()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erlebach/src/2024/llama_index_gordon/Building-Data-Driven-Applications-with-LlamaIndex/.venv/lib/python3.12/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erlebach/src/2024/llama_index_gordon/Building-Data-Driven-Applications-with-LlamaIndex/.venv/lib/python3.12/site-packages/llama_index/core/service_context.py", line 187, in from_defaults
    llm_predictor = llm_predictor or LLMPredictor(
                                     ^^^^^^^^^^^^^
  File "/Users/erlebach/src/2024/llama_index_gordon/Building-Data-Driven-Applications-with-LlamaIndex/.venv/lib/python3.12/site-packages/llama_index/core/service_context_elements/llm_predictor.py", line 108, in __init__
    self._llm = resolve_llm(llm, callback_manager=callback_manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erlebach/src/2024/llama_index_gordon/Building-Data-Driven-Applications-with-LlamaIndex/.venv/lib/python3.12/site-packages/llama_index/core/llms/utils.py", line 48, in resolve_llm
    raise ValueError(
ValueError:
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******
```

**Comment by logan-markewich** [comment]
Ah, the composable graph was never updated to use settings. It still uses service context 

(FYI the composable graph is basically dead code, i dont think its even mentioned in the docs anymore. it's recommend to just use index nodes)

https://docs.llamaindex.ai/en/stable/examples/retrievers/composable_retrievers/?h=composable

**Comment by erlebach** [comment]
Thanks. I was following the code from a book I purchased on Llama_Index. I got Composable graph to use ServiceContext :-). I'll skip it for now since it might be deprecated.
