### ISSUE TITLE
[Bug]: Pandas Output: There was an error running the output as Python code. Error message: name 'p' is not defined

### ISSUE THREAD

**Issue by uniltone** [run-llama/llama_index#13800]
### Bug Description

I want to use pandas_query_engine to generate a statistical chart, but an error message is reported: name 'p' is not defined

Below is the code

import pandas as pd
from llama_index.experimental.query_engine import PandasQueryEngine
from llama_index.llms.openai import OpenAI
import os
df = pd.DataFrame(
    {
        "country": [
            "United States",
            "United Kingdom",
            "France",
            "Germany",
            "Italy",
            "Spain",
            "Canada",
            "Australia",
            "Japan",
            "China",
        ],
        "gdp": [
            21400000,
            2940000,
            2830000,
            3870000,
            2160000,
            1350000,
            1780000,
            1320000,
            516000,
            14000000,
        ],
        "happiness": [7.3, 7.2, 6.5, 7.0, 6.0, 6.3, 7.3, 7.3, 5.9, 5.0],
    }
)

llm = OpenAI()
query_engine = PandasQueryEngine(df=df,verbose=True)
response = query_engine.query(
    "Visualize barchat of number of happiness of country .",
)

### Version

0.10.40

### Steps to Reproduce

 i don't kown

### Relevant Logs/Tracbacks

```shell
error report：
> Pandas Instructions:


df.plot(kind='bar', x='country', y='happiness')
```
```
Traceback (most recent call last):
  File "E:\anaconda\Lib\site-packages\llama_index\experimental\query_engine\pandas\output_parser.py", line 54, in default_output_processor
    output_str = str(safe_eval(module_end_str, {"np": np, "pd": pd}, local_vars))#修改
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda\Lib\site-packages\llama_index\experimental\exec_utils.py", line 159, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'p' is not defined
> Pandas Output: There was an error running the output as Python code. Error message: name 'p' is not defined
```

**Comment by uniltone** [comment]
生成的统计图，如何保存下来@dosu.

**Comment by uniltone** [comment]
I need to save the image directly after returning response@dosu

**Comment by uniltone** [comment]
I tried your method, but it didn't work.
Keep reporting errors @dosu
Traceback (most recent call last):
  File "E:\anaconda\Lib\site-packages\llama_index\experimental\query_engine\pandas\output_parser.py", line 54, in default_output_processor
    output_str = str(safe_eval(module_end_str, {"np": np}, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda\Lib\site-packages\llama_index\experimental\exec_utils.py", line 159, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'p' is not defined

**Comment by tytung2020** [comment]
same issue here, have you solve it?
I think it is not related to matplotlib. I asked queries that are not related to plotting and it still returns this error: 
```
Traceback (most recent call last):
  File "C:\Users\tytun\anaconda3\envs\pulse_ai\Lib\site-packages\llama_index\experimental\query_engine\pandas\output_parser.py", line 54, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tytun\anaconda3\envs\pulse_ai\Lib\site-packages\llama_index\experimental\exec_utils.py", line 159, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'p' is not defined
```

**Comment by ddaseg** [comment]
Is the issue resolved? I am facing the same issue while querying from a pandas dataframe using PandasQueryEngine from from llama_index.experimental.query_engine.pandas.pandas_query_engine import PandasQueryEngine @dosu

**Comment by ddaseg** [comment]
> same issue here, have you solve it? I think it is not related to matplotlib. I asked queries that are not related to plotting and it still returns this error:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\tytun\anaconda3\envs\pulse_ai\Lib\site-packages\llama_index\experimental\query_engine\pandas\output_parser.py", line 54, in default_output_processor
>     output_str = str(safe_eval(module_end_str, global_vars, local_vars))
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\tytun\anaconda3\envs\pulse_ai\Lib\site-packages\llama_index\experimental\exec_utils.py", line 159, in safe_eval
>     return eval(__source, _get_restricted_globals(__globals), __locals)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<string>", line 1, in <module>
> NameError: name 'p' is not defined
> ```

@tytung2020 were you able to solve this problem. You are correct. This is not related to matplotlib. I am not using this library. I am trying to query from a pandas dataframe using PandasQueryEngine from llama_index.experimental.query_engine.pandas.pandas_query_engine.

**Comment by stefangiftime** [comment]
error persists.

**Comment by gangula-karthik** [comment]
facing this issue as well

**Comment by neil564** [comment]
facing the same issue
