### ISSUE TITLE
[Bug]: NotImplementedError: Messages passed in must be of odd length while using chat_mode="react"

### ISSUE THREAD

**Issue by 1ly1mk** [run-llama/llama_index#13870]
### Bug Description

While creating streamlit chatbot I observed that
chat_engine = index.as_chat_engine(chat_mode="condense_question", verbose=True)
works fine, but
chat_engine = index.as_chat_engine(chat_mode="react", verbose=True)
or other modes like context etc throw a NotImplemented error for hugging face API.
In both cases, I am passing the same message from streamlit UI. So for the same message, one chat mode works and another doesn't.

### Version

0.10.38

### Steps to Reproduce

1. create a vector index from huggingfaceinterfaceapi and embeddings
2. create a chat engine with different mode
3. chat_engine = index.as_chat_engine(chat_mode="condense_question", verbose=True)
4. Observe the result for condensed_quesrion and react chat mode
5. 

### Relevant Logs/Tracbacks

```shell
Local URL: http://localhost:8501
  Network URL: http://192.168.0.7:8501

C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\pydantic\_internal\_fields.py:160: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\langchain\_api\module_import.py:92: LangChainDeprecationWarning: Importing ChatMessageHistory from langchain.memory is deprecated. Please replace deprecated imports:

>> from langchain.memory import ChatMessageHistory

with new imports of:

>> from langchain_community.chat_message_histories import ChatMessageHistory
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here https://python.langchain.com/v0.2/docs/versions/v0_2/
  warn_deprecated(
2024-05-31 23:07:27.003 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "E:\ai\llmaindex\simpledocument\simpleRAG\simplerag\mychatbot.py", line 31, in <module>
    response = chat_engine.chat(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\callbacks\utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\agent\runner\base.py", line 644, in chat
    chat_response = self._chat(
                    ^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\agent\runner\base.py", line 574, in _chat
    cur_step_output = self._run_step(
                      ^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\agent\runner\base.py", line 411, in _run_step
    cur_step_output = self.agent_worker.run_step(step, task, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\callbacks\utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\agent\react\step.py", line 738, in run_step
    return self._run_step(step, task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\agent\react\step.py", line 533, in _run_step
    chat_response = self._llm.chat(input_chat)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
index\llms\huggingface\base.py", line 631, in chat
    **{**chat_messages_to_conversational_kwargs(messages), **kwargs}
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\llms\huggingface\base.py", line 436, in chat_messages_to_conversational_kwargs
    raise NotImplementedError("Messages passed in must be of odd length.")
NotImplementedError: Messages passed in must be of odd length.
```

**Comment by logan-markewich** [comment]
Some huggingface models are very strict about how message passing works. Pretty hard to deal with, would have to update the class to odd some option to force the messages to be an odd length

**Comment by 1ly1mk** [comment]
I added a method to ensure the message is odd but I still get the problem. Seems that an odd check is being done for the message sequence and not the message itself. 
![image](https://github.com/run-llama/llama_index/assets/7780397/66cf2ac6-1a42-458c-a061-8c2949de8cd8)

I printed the 'messages' and it yielded an array of two ChatMessage, one from system and another from user.

[ChatMessage(role=<MessageRole.SYSTEM: 'system'>, content='You are designed to help with a variety of tasks, from answering questions to providing summaries to other types of analyses.\n\n## Tools\n\nYou have access to a wide variety of tools. You are responsible for using the tools in any sequence you deem appropriate to complete the task at 
hand.\nThis may require breaking the task into subtasks and using different tools to complete each subtask.\n\nYou 
have access to the following tools:\n> Tool Name: query_engine_tool\nTool Description: Useful for running a natural language query\nagainst a knowledge base and get back a natural language response.\n\nTool Args: {"type": "object", "properties": {"input": {"title": "Input", "type": "string"}}, "required": ["input"]}\n\n\n\n## Output Format\n\nPlease answer in the same language as the question and use the following format:\n\n```\nThought: The current language of the user is: (user\'s language). I need to use a tool to help me answer the question.\nAction: tool name (one of query_engine_tool) if using a tool.\nAction Input: the input to the tool, in a JSON format representing the kwargs (e.g. {"input": "hello world", "num_beams": 5})\n```\n\nPlease ALWAYS start with a Thought.\n\nPlease use a valid JSON format for the Action Input. Do NOT do this {\'input\': \'hello world\', \'num_beams\': 5}.\n\nIf this format is used, the user will respond in the following format:\n\n```\nObservation: tool response\n```\n\nYou should keep repeating the above format till you have enough information to answer the question without using any more tools. At that point, you MUST respond in the one of the following two formats:\n\n```\nThought: I can answer without using any more tools. I\'ll use the user\'s language to answer\nAnswer: [your answer here (In the same language as the user\'s question)]\n```\n\n```\nThought: I cannot answer the question with the provided tools.\nAnswer: [your answer here (In the same language as the user\'s question)]\n```\n\n## Current Conversation\n\nBelow is the current conversation consisting of interleaving human and assistant messages.\n', additional_kwargs={}), ChatMessage(role=<MessageRole.USER: 'user'>, content='who is paul? ', additional_kwargs={})]

Possibly there is a problem in llama_index\llms\huggingface\base.py implementation.

@logan-markewich @dosubot

**Comment by 1ly1mk** [comment]
Implement ensure odd message and now I get another exception 

 File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\llms\huggingface\base.py", line 450, in chat_messages_to_conversational_kwargs
    raise NotImplementedError(
NotImplementedError: Didn't handle when messages aren't ordered in alternating pairs of (<MessageRole.USER: 'user'>, <MessageRole.ASSISTANT: 'assistant'>).

@logan-markewich @dosu

**Comment by 1ly1mk** [comment]
while implementing ordering below exception pops up,

File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\llama_index\legacy\llms\gemini_utils.py", line 116, in merge_neighboring_same_role_messages
    merged_message = ChatMessage(
                     ^^^^^^^^^^^^
  File "C:\Users\lenovo\AppData\Local\pypoetry\Cache\virtualenvs\simplerag-GtP-BaND-py3.12\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatMessage
additional_kwargs
  none is not an allowed value (type=type_error.none.not_allowed)
  
  @logan-markewich @dosu
