### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by upchunk** [run-llama/llama_index#13904]
### Bug Description

Getting this `RuntimeError: no running event loop` error when running ingestion pipeline on FastAPI, the error are coming from llamaindex asyncio_run function (`from llama_index.core.async_utils import asyncio_run`)

### Version

0.10.41

### Steps to Reproduce

1. Create a Index-Document endpoint on FastAPI to index document
2. Use IngestionPipeline to index the document to pinecone Vector Store with Transformers as follow:
    1. SentenceSplitter
    2. KeywordExtractor
3. Index documents with sizes of 1000 words ++, do it concurrently using aiohttp to the Index Document Endpoint
4. The Error will frequently Showed up 

### Relevant Logs/Tracbacks

```shell
Task exception was never retrieved
future: <Task finished name='Task-87799' coro=<AsyncClient.aclose() done, defined at D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpx\_client.py:2011> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\llama_index\core\async_utils.py", line 29, in asyncio_run
    loop = asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpx\_client.py", line 2018, in aclose
    await self._transport.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpx\_transports\default.py", line 385, in aclose
    await self._pool.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 313, in aclose
    await self._close_connections(closing_connections)
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 305, in _close_connections
    await connection.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_async\connection.py", line 171, in aclose
    await self._connection.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_async\http11.py", line 265, in aclose
    await self._network_stream.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 55, in aclose
    await self._stream.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\anyio\streams\tls.py", line 202, in aclose
    await self.transport_stream.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 1191, in aclose
    self._transport.close()
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 109, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python311\Lib\asyncio\base_events.py", line 762, in call_soon
    self._check_closed()
  File "C:\Python311\Lib\asyncio\base_events.py", line 520, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task exception was never retrieved
future: <Task finished name='Task-87800' coro=<AsyncClient.aclose() done, defined at D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpx\_client.py:2011> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\llama_index\core\async_utils.py", line 29, in asyncio_run
    loop = asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpx\_client.py", line 2018, in aclose
    await self._transport.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpx\_transports\default.py", line 385, in aclose
    await self._pool.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 313, in aclose
    await self._close_connections(closing_connections)
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 305, in _close_connections
    await connection.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_async\connection.py", line 171, in aclose
    await self._connection.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_async\http11.py", line 265, in aclose
    await self._network_stream.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 55, in aclose
    await self._stream.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\anyio\streams\tls.py", line 202, in aclose
    await self.transport_stream.aclose()
  File "D:\PROJECT\aidoc-llm-service\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 1191, in aclose
    self._transport.close()
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 109, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python311\Lib\asyncio\base_events.py", line 762, in call_soon
    self._check_closed()
  File "C:\Python311\Lib\asyncio\base_events.py", line 520, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by upchunk** [comment]
![image](https://github.com/run-llama/llama_index/assets/62106675/9e22cdc7-73a8-4685-b486-5729a3d78988)

**Comment by upchunk** [comment]
I have done it with and without the asyncio_run, and the problem still occurs on both methods. I think the problem is in the asyncio_run helper itself

**Comment by logan-markewich** [comment]
@upchunk weird, this code is in a try/except, how was it not caught? 🙃 

In any case, if you are using fastapi, you should be using async entry points to the pipeline

`pipeline.arun(documents=documents)`

**Comment by logan-markewich** [comment]
@upchunk I am not able to replicate actually 

```python
from fastapi import FastAPI
from llama_index.core import Document
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.node_parser import SentenceSplitter
from llama_index.embeddings.openai import OpenAIEmbedding

text = Document.example().text * 1000

app = FastAPI()

@app.get("/")
async def hello():
  return {"Hello": "World"}

@app.get("/test")
async def run_test():
  pipeline = IngestionPipeline(transformations=[
      SentenceSplitter(),
      OpenAIEmbedding(),
    ]
  )
  await pipeline.arun(documents=[Document(text=text), Document(text=text)])
  return "Complete"


if __name__ == "__main__":
  import uvicorn
  uvicorn.run(app)
```

**Comment by logan-markewich** [comment]
I am not able to replicate actually

```python
from fastapi import FastAPI
from llama_index.core import Document
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.node_parser import SentenceSplitter
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.core.extractors import KeywordExtractor

text = Document.example().text * 1000

app = FastAPI()

@app.get("/")
async def hello():
  return {"Hello": "World"}

@app.get("/test")
async def run_test():
  pipeline = IngestionPipeline(transformations=[
      SentenceSplitter(),
      KeywordExtractor(),
      OpenAIEmbedding(),
    ]
  )
  await pipeline.arun(documents=[Document(text=text), Document(text=text)])
  return "Complete"


if __name__ == "__main__":
  import uvicorn
  uvicorn.run(app)
```

**Comment by upchunk** [comment]
I do the request to the endpoint using aiohttp with 10.000 data sourced from pdf, each data contains texts with the length of 1000 - 2000 words++ , limited by asynio.Semaphore(10)

**Comment by upchunk** [comment]
Using async on fastAPI actually resulted in slower indexing time for my use case
