### ISSUE TITLE
[Bug]:   MarkdownElementNodeParser：pandas.errors.ParserError: Error tokenizing data. C error: EOF inside string starting at row 0

### ISSUE THREAD

**Issue by SmileLollipop** [run-llama/llama_index#13942]
### Bug Description

 Error:
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "d:\Baoxin\Program\knowledgeManager\module\b_extract copy.py", line 174, in <module>
    raw_nodes = parser.get_nodes_from_documents(md_doc)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\llama_index\core\node_parser\interface.py", line 129, in get_nodes_from_documents
    nodes = self._parse_nodes(documents, show_progress=show_progress, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\llama_index\core\node_parser\relational\base_element.py", line 120, in _parse_nodes
    nodes = self.get_nodes_from_node(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\llama_index\core\node_parser\relational\markdown_element.py", line 25, in get_nodes_from_node
    elements = self.extract_elements(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\llama_index\core\node_parser\relational\markdown_element.py", line 168, in extract_elements
    should_keep = all(tf(element) for tf in table_filters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\llama_index\core\node_parser\relational\markdown_element.py", line 168, in <genexpr>
    should_keep = all(tf(element) for tf in table_filters)
                      ^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\llama_index\core\node_parser\relational\markdown_element.py", line 220, in filter_table
    table_df = md_to_df(table_element.element)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\llama_index\core\node_parser\relational\utils.py", line 26, in md_to_df
    return pd.read_csv(StringIO(md_str))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\pandas\io\parsers\readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda3\envs\llm_env\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 574, in pandas._libs.parsers.TextReader.__cinit__
  File "parsers.pyx", line 663, in pandas._libs.parsers.TextReader._get_header
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: EOF inside string starting at row 0

### Version

0.10.18

### Steps to Reproduce

 from llama_index.core.node_parser import MarkdownElementNodeParser
parser = MarkdownElementNodeParser(
    num_workers=3,
    include_metadata=True,
)
 
 raw_nodes = parser.get_nodes_from_documents(md_doc)

**Comment by sheresaidon** [comment]
+1 @logan-markewich is there a way to ignore errors on this?
