### ISSUE TITLE
[Question]: I want to buid a local multimodal RAG chatbot, but I get error below

### ISSUE THREAD

**Issue by LJ-Hao** [run-llama/llama_index#13943]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

```
# This class will transform video to text and images
class VideoProcessor:
    def __init__(self, video_path, output_audio_path, output_folder):
        self.video_path = video_path
        self.output_audio_path = output_audio_path
        self.image_path = output_folder
        self.text_path = output_folder

    def extract_audio(self):
        video = VideoFileClip(os.path.join(self.video_path, "input.mp4"))
        audio_part = video.audio
        audio_part.write_audiofile(os.path.join(self.output_audio_path, "output_audio.mp3"))

    def extract_text(self):
        model = whisper.load_model("base")
        result = model.transcribe(os.path.join(self.output_audio_path, "output_audio.mp3"))
        with open(os.path.join(self.text_path, "audio.md"), "w") as file:
            file.write(result['text'])
            file.close()

    def extract_frames(self):
            clip = VideoFileClip(os.path.join(self.video_path, "input.mp4"))
            clip.write_images_sequence(os.path.join(self.image_path, "frame%04d.png"), fps=0.2)

    def process_video(self):
        self.extract_audio()
        self.extract_text()
        self.extract_frames()

# This class maker sure RAG and ask
class retriever_ask:
    def __init__(self, output_folder, similarity_top_k, image_similarity_top_k) -> None:
        self.text_store = LanceDBVectorStore(uri="lancedb", table_name="text_collection")
        self.image_store = LanceDBVectorStore(uri="lancedb", table_name="image_collection")
        self.output_folder = output_folder
        self.similarity_top_k = similarity_top_k
        self.image_similarity_top_k = image_similarity_top_k
        # self.llm = Ollama(model='llava', request_timeout=100)
        self.llm = OllamaMultiModal(model='llava', request_timeout=3600) 
        self.qa_tmpl_str = (
    """
 Given the provided information, including relevant images and retrieved context from the video,\
 accurately and precisely answer the query without any additional prior knowledge.\n"
    "Please ensure honesty and responsibility, refraining from any racist or sexist remarks.\n"
    "---------------------\n"
    "Context: {context_str}\n"
    "Metadata for video: {metadata_str} \n"
    "---------------------\n"
    "Query: {query_str}\n"
    "Answer: "
"""
)
    def retriever_engine(self):
        documents = SimpleDirectoryReader(self.output_folder).load_data()
        storage_context = StorageContext.from_defaults(vector_store=self.text_store, image_store=self.image_store)
        index = MultiModalVectorStoreIndex.from_documents(documents, storage_context=storage_context)
        retriever_engine = index.as_retriever(similarity_top_k=self.similarity_top_k, image_similarity_top_k=self.image_similarity_top_k)
        return retriever_engine
    
    def retrieve(self, retriever_engine, query_str):
        retrieval_results = retriever_engine.retrieve(query_str)
        retrieved_image = []
        retrieved_text = []
        for res_node in retrieval_results:
            if isinstance(res_node.node, ImageNode):
                retrieved_image.append(res_node.node.metadata["file_path"])
            else:
                retrieved_text.append(res_node.text)

        return retrieved_image, retrieved_text
    
    def ask(self):
        retriever_engine = self.retriever_engine()
  
        while True:
            try:
                query_str = input('\033[94m' +"Prompt: " + '\033[0m')
                image, text = self.retrieve(retriever_engine=retriever_engine, query_str=query_str)
                context_str = "".join(text)
                metadata_str= image
                image_documents = SimpleDirectoryReader(input_dir=self.output_folder, input_files=image).load_data()
                response = self.llm.complete(prompt=self.qa_tmpl_str.format(context_str=context_str, query_str=query_str, metadata_str=metadata_str),image_documents=image_documents)
                print(response)
            except KeyboardInterrupt:
                break

if __name__ == '__main__':

    Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

    video_path = './video/'
    output_audio_path = './audio/'
    output_folder= './output/'
# process video to images and text
    processor = VideoProcessor(video_path, output_audio_path, output_folder)
    processor.process_video()
# Ask question
    engine = retriever_ask(output_folder, 5, 5)
    engine.ask()
```
But I get problem like below:
```
Prompt: hello
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./mulitRAG.py", line 153, in <module>
    engine.ask()
  File "./mulitRAG.py", line 135, in ask
    response = self.llm.complete(prompt=self.qa_tmpl_str.format(context_str=context_str, query_str=query_str, metadata_str=metadata_str),image_documents=image_documents)
  File "/usr/local/lib/python3.8/dist-packages/llama_index/multi_modal_llms/ollama/base.py", line 160, in complete
    response = self._client.generate(
  File "/usr/local/lib/python3.8/dist-packages/ollama/_client.py", line 126, in generate
    return self._request_stream(
  File "/usr/local/lib/python3.8/dist-packages/ollama/_client.py", line 97, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
  File "/usr/local/lib/python3.8/dist-packages/ollama/_client.py", line 68, in _request
    response = self._client.request(method, url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out
```
I am sure that  my computer is inferencing my question, but I don’t get a response to the question.

**Comment by LJ-Hao** [comment]
So someone helps, did I use some function with a wrong way?

**Comment by LJ-Hao** [comment]
`Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")`
Hi, I want use [clip](https://github.com/openai/CLIP) to embedding my images and text, how can I use it, could you give me an example.

**Comment by LJ-Hao** [comment]
> To switch to using CLIP to embed your images and text in your local multimodal RAG chatbot, you can use the `ClipEmbedding` class provided in the `llama_index/embeddings/clip/base.py` file. Here is a step-by-step guide:
> 
> 1. **Install the required packages**:
>    ```shell
>    pip install git+https://github.com/openai/CLIP.git
>    pip install torch pillow
>    ```
> 2. **Initialize the `ClipEmbedding` class**:
>    ```python
>    from llama_index.embeddings.clip import ClipEmbedding
>    
>    clip_embedding = ClipEmbedding(
>        embed_batch_size=10,  # You can adjust the batch size as needed
>        model_name="ViT-B/32"  # You can choose from the available CLIP models
>    )
>    ```
> 3. **Generate text embeddings**:
>    ```python
>    text = "Your text here"
>    text_embedding = clip_embedding._get_text_embedding(text)
>    ```
> 4. **Generate image embeddings**:
>    ```python
>    img_file_path = "path/to/your/image.jpg"
>    image_embedding = await clip_embedding._aget_image_embedding(img_file_path)
>    ```
> 
> Here is a complete example:
> 
> ```python
> import asyncio
> from llama_index.embeddings.clip import ClipEmbedding
> 
> # Initialize the ClipEmbedding class
> clip_embedding = ClipEmbedding(
>     embed_batch_size=10,  # Adjust the batch size as needed
>     model_name="ViT-B/32"  # Choose from the available CLIP models
> )
> 
> # Generate text embedding
> text = "Your text here"
> text_embedding = clip_embedding._get_text_embedding(text)
> print("Text Embedding:", text_embedding)
> 
> # Generate image embedding
> async def get_image_embedding():
>     img_file_path = "path/to/your/image.jpg"
>     image_embedding = await clip_embedding._aget_image_embedding(img_file_path)
>     print("Image Embedding:", image_embedding)
> 
> # Run the async function to get image embedding
> asyncio.run(get_image_embedding())
> ```
> 
> This code will initialize the CLIP model, generate embeddings for the provided text and image, and print the embeddings [[1]](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/embeddings/clip.py)[[2]](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/embeddings/llama-index-embeddings-clip/llama_index/embeddings/clip/base.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

And use clip with LanceDBVectorStore, give me an example
