### ISSUE TITLE
[Bug]: Nebulagraph - upsert_triplet() function has empty string obj

### ISSUE THREAD

**Issue by hungbui-io** [run-llama/llama_index#14092]
### Bug Description

I am trying to generate a Nebulagraph  knowledge graph from a code data in an xlsx file that contain function_name, file_name and function_definition columns. But an error occurs in the upsert_triplet() function saying that the created object vertex has empty string (pls check the log below)

### Version

0.10.44

### Steps to Reproduce

- Load the code data from xlsx file that has 3 columns containing function_name, file_name, and function_defintion. 
- Use KnowledgeGraphIndex.from_documents() to generate knowledge graph from the code data. The error occurs during this step 

### Relevant Logs/Tracbacks

```shell
DEBUG:llama_index.graph_stores.nebula.nebula_graph_store:upsert_triplet()
DML query: INSERT VERTEX `entity`(name)   VALUES "Generate_telemetry_data":("Generate_telemetry_data");INSERT VERTEX `entity`(name)   VALUES "Model_name":("Model_name");INSERT EDGE `relationship`(`relationship`)   VALUES "Generate_telemetry_data"->"Model_name"@1155094724010351908:("Has parameter");
upsert_triplet()
DML query: INSERT VERTEX `entity`(name)   VALUES "Generate_telemetry_data":("Generate_telemetry_data");INSERT VERTEX `entity`(name)   VALUES "Model_name":("Model_name");INSERT EDGE `relationship`(`relationship`)   VALUES "Generate_telemetry_data"->"Model_name"@1155094724010351908:("Has parameter");
test 111...
obj:  
subj:  Generate_telemetry_data
rel:  Has default value
************
Traceback (most recent call last):
  File "/home/aion/Hung/change_impact_analysis/CIA_nebulagraph_demo.py", line 447, in <module>
    _load_doc_from_excel()
  File "/home/aion/Hung/change_impact_analysis/CIA_nebulagraph_demo.py", line 367, in _load_doc_from_excel
    genGraph_from_doc(code_method_docs, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aion/Hung/change_impact_analysis/CIA_nebulagraph_demo.py", line 131, in genGraph_from_doc
    kg_index = KnowledgeGraphIndex.from_documents(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aion/anaconda3/envs/cia_/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 145, in from_documents
    return cls(
           ^^^^
  File "/home/aion/anaconda3/envs/cia_/lib/python3.11/site-packages/llama_index/core/indices/knowledge_graph/base.py", line 99, in __init__
    super().__init__(
  File "/home/aion/anaconda3/envs/cia_/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 94, in __init__
    index_struct = self.build_index_from_nodes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aion/anaconda3/envs/cia_/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 212, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aion/anaconda3/envs/cia_/lib/python3.11/site-packages/llama_index/core/indices/knowledge_graph/base.py", line 211, in _build_index_from_nodes
    self.upsert_triplet(triplet)
  File "/home/aion/anaconda3/envs/cia_/lib/python3.11/site-packages/llama_index/core/indices/knowledge_graph/base.py", line 259, in upsert_triplet
    self._graph_store.upsert_triplet(*triplet)
  File "/home/aion/anaconda3/envs/cia_/lib/python3.11/site-packages/llama_index/graph_stores/nebula/nebula_graph_store.py", line 499, in upsert_triplet
    obj = escape_str(obj)
          ^^^^^^^^^^^^^^^
  File "/home/aion/anaconda3/envs/cia_/lib/python3.11/site-packages/llama_index/graph_stores/nebula/nebula_graph_store.py", line 103, in escape_str
    if value[0] == " " or value[-1] == " ":
       ~~~~~^^^
IndexError: string index out of range
```

**Comment by logan-markewich** [comment]
Hmm, guess it should filter empty entities/relations then
