### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.utilities'

### ISSUE THREAD

**Issue by arvindkc** [run-llama/llama_index#14179]
### Bug Description

I was trying to chat with a database following instructions [here](https://github.com/run-llama/llama-hub/blob/main/llama_hub/tools/notebooks/intro_to_tools.ipynb) and received the error **No module named 'llama_index.utilities'**

### Version

0.10.45

### Steps to Reproduce

Execute the contents of this workbook to repro this error
https://github.com/run-llama/llama-hub/blob/main/llama_hub/tools/notebooks/intro_to_tools.ipynb

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/kc/dev/kc-pygwalker-demo/pages/3_📀_Chat_with_datalake.py", line 7, in <module>
    from llama_hub.tools.database.base import DatabaseToolSpec
  File "/opt/homebrew/lib/python3.11/site-packages/llama_hub/tools/database/__init__.py", line 2, in <module>
    from llama_hub.tools.database.base import (
  File "/opt/homebrew/lib/python3.11/site-packages/llama_hub/tools/database/base.py", line 5, in <module>
    from llama_index.utilities.sql_wrapper import SQLDatabase
```

**Comment by logan-markewich** [comment]
@arvindkc llamahub  repo is deprecated, and not expected to work (check out the readme over there, I think there's also a banner at the top)

If you are trying to use tools from that notebook,  you need to install them

`pip install llama-index-tools-database`

https://llamahub.ai/l/tools/llama-index-tools-database?from=
