### ISSUE TITLE
[Bug]: IngestionPipeline can not work with local HuggingFaceEmbedding 

### ISSUE THREAD

**Issue by yydxlv** [run-llama/llama_index#14236]
### Bug Description

```python
from llama_index.core import Settings
from llama_index.core import SimpleDirectoryReader
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.ingestion import IngestionPipeline
from llama_index.embeddings.huggingface import HuggingFaceEmbedding


embed_model = HuggingFaceEmbedding(model_name="../../BAAI/bge-base-zh-v1.5")
Settings.embed_model = embed_model
documents = SimpleDirectoryReader(input_dir="data/director", recursive=True, required_exts=[".txt",]).load_data(num_workers=8)

pipeline = IngestionPipeline(
    transformations=[SentenceSplitter(chunk_size=128, chunk_overlap=0), Settings.embed_model,],
#     vector_store=vector_store,
    )

start = time.time()
nodes = pipeline.run(documents=documents, num_workers=64, show_progress=True)
end = time.time()
print(f"Ingested {len(nodes)} Nodes")
print(f"Elapsed time (min): {(end-start)/60}")

```

### Version

0.10.46

### Steps to Reproduce

```python
pipeline = IngestionPipeline(
    transformations=[SentenceSplitter(chunk_size=128, chunk_overlap=0), Settings.embed_model,],
#     vector_store=vector_store,
    )

nodes = pipeline.run(documents=documents, num_workers=64, show_progress=True)

```

### Relevant Logs/Tracbacks

```shell
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/ingestion/pipeline.py", line 127, in run_transformations
    nodes = transform(nodes, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/base/embeddings/base.py", line 440, in __call__
    embeddings = self.get_text_embedding_batch(
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/base/embeddings/base.py", line 332, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/embeddings/huggingface/base.py", line 149, in _get_text_embeddings
    return self._embed(texts, prompt_name="text")
  File "/usr/local/lib/python3.10/dist-packages/llama_index/embeddings/huggingface/base.py", line 124, in _embed
    return self._model.encode(
AttributeError: 'HuggingFaceEmbedding' object has no attribute '_model'
"""
The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
Cell In[63], line 18
     12 pipeline = IngestionPipeline(
     13     transformations=[SentenceSplitter(chunk_size=128, chunk_overlap=0), Settings.embed_model,],
     14 #     vector_store=vector_store,
     15     )
     17 start = time.time()
---> 18 nodes = pipeline.run(documents=documents, num_workers=64, show_progress=True)
     19 # nodes = await pipeline.arun(documents=docs, num_workers=64, show_progress=True)
     20 end = time.time()

File /usr/local/lib/python3.10/dist-packages/llama_index/core/ingestion/pipeline.py:722, in run(self, show_progress, documents, nodes, cache_collection, in_place, store_doc_text, num_workers, **kwargs)
    716 if num_workers > multiprocessing.cpu_count():
    717     warnings.warn(
    718         "Specified num_workers exceed number of CPUs in the system. "
    719         "Setting `num_workers` down to the maximum CPU count."
    720     )
--> 722 with multiprocessing.get_context("spawn").Pool(num_workers) as p:
    723     node_batches = self._node_batcher(
    724         num_batches=num_workers, nodes=nodes_to_run
    725     )
    726     nodes_parallel = p.starmap(
    727         run_transformations,
    728         zip(
   (...)
    734         ),
    735     )

File /usr/lib/python3.10/multiprocessing/pool.py:375, in Pool.starmap(self, func, iterable, chunksize)
    369 def starmap(self, func, iterable, chunksize=None):
    370     '''
    371     Like `map()` method but the elements of the `iterable` are expected to
    372     be iterables as well and will be unpacked as arguments. Hence
    373     `func` and (a, b) becomes func(a, b).
    374     '''
--> 375     return self._map_async(func, iterable, starmapstar, chunksize).get()

File /usr/lib/python3.10/multiprocessing/pool.py:774, in ApplyResult.get(self, timeout)
    772     return self._value
    773 else:
--> 774     raise self._value

AttributeError: 'HuggingFaceEmbedding' object has no attribute '_model'
```

**Comment by logan-markewich** [comment]
You can't multiprocess with a local embedding model. It's a limitation of pytorch/transformers

**Comment by logan-markewich** [comment]
Set num_workers=1 and it would work

**Comment by yydxlv** [comment]
That is ture, thank you

**Comment by theta-lin** [comment]
@logan-markewich Would you mind elaborating more on this?

> You can't multiprocess with a local embedding model. It's a limitation of pytorch/transformers

I just tested the following code:

```python
from sentence_transformers import SentenceTransformer
import multiprocessing as mp
from itertools import repeat


class C:
    def __init__(self, model_name):
        self.model = SentenceTransformer(model_name)

    def encode(self, sentences):
        return self.model.encode(sentences)


def f(model, sentence):
    return model.encode(sentence)


def main():
    c = C("BAAI/bge-small-en-v1.5")
    sentences = ["hello", "world"]
    with mp.get_context("spawn").Pool(processes=2) as pool:
        print(pool.starmap(f, zip(repeat(c), sentences)))


if __name__ == "__main__":
    main()
```

Which I assume should mimic how `HuggingFaceEmbedding` interacts with `IngestionPipeline`. However, the code ran just fine.

I now suspect that this is related to the deepcopy/pickling issue in #14464 and #14570, but I did not investigate further. I thought it would be weird to have the error `'HuggingFaceEmbedding' object has no attribute '_model'` suppose that this is the issue with pytorch/transformers.
