### ISSUE TITLE
[Question]: I want to add SQLAutoVectorQueryEngine to ReActAgent, but an error is reported

### ISSUE THREAD

**Issue by uniltone** [run-llama/llama_index#14261]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question :I want to add SQLAutoVectorQueryEngine to ReActAgent, but an error is reported

`
```
def load_SQLAutoVectorQueryEngine(sql_tool,vector_tool):
    query_engine = SQLAutoVectorQueryEngine(
        sql_query_tool = sql_tool,
        vector_query_tool = vector_tool,
        selector=LLMSingleSelector.from_defaults(
            prompt_template_str="Some choices are given below. It is provided in a numbered list "
                                "(1 to {num_choices}), "
                                "where each item in the list corresponds to a summary.\n"
                                "---------------------\n"
                                "{context_list}"
                                "\n---------------------\n"
                                "Using only the choices above and not prior knowledge, return "
                                "first select the database tool based on the problem: '{query_str}'\n",
            output_parser=SelectionOutputParser(),
        ),
        sql_vector_synthesis_prompt=DEFAULT_SQL_VECTOR_SYNTHESIS_PROMPT,
        callback_manager=callback_manager
    )
    return query_engine

query_engine = load_SQLAutoVectorQueryEngine(sql_tool,s_engine_tool)
    sqlAutoVector_tool = QueryEngineTool(
        query_engine=query_engine,
        metadata=ToolMetadata(
            name="query_agent", description="query engine for sql database and local document vector searching."
        ),
    ),
    from llama_index.core.agent import ReActAgent
    agent = ReActAgent.from_tools([sqlAutoVector_tool,s_engine_tool],callback_manager=callback_manager)
    agent.update_prompts({"agent_worker:system_prompt": react_system_prompt})
    text = input("question:")
    response = agent.chat(text)
`


----------erro-------------------
question:hello
Traceback (most recent call last):
  File "/home/zwf_llama3_2_2.py", line 404, in <module>
    response = agent.chat(text)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 617, in chat
    chat_response = self._chat(
                    ^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 547, in _chat
    cur_step_output = self._run_step(
                      ^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/agent/runner/base.py", line 384, in _run_step
    cur_step_output = self.agent_worker.run_step(step, task, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/agent/react/step.py", line 744, in run_step
    return self._run_step(step, task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/agent/react/step.py", line 532, in _run_step
    input_chat = self._react_chat_formatter.format(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/agent/react/formatter.py", line 68, in format
    "tool_desc": "\n".join(get_react_tool_descriptions(tools)),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/agent/react/formatter.py", line 27, in get_react_tool_descriptions
    f"> Tool Name: {tool.metadata.name}\n"
                    ^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/tools/types.py", line 185, in metadata
    return self.base_tool.metadata
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'metadata'
```

**Comment by uniltone** [comment]
谢谢，你回答完全正确，解决了我的问题 @Dosu
