### ISSUE TITLE
[Bug]: Ingestion pipeline failed with num_workers>1 and SentenceWindowNodeParser

### ISSUE THREAD

**Issue by melya** [run-llama/llama_index#14280]
### Bug Description

When attempting to run the **ingestion pipeline** with more than one worker (`num_workers > 1`), the process fails when using the `SentenceWindowNodeParser`.

### Version

0.10.47

### Steps to Reproduce

[Here is code which reproduces the bug](https://github.com/melya/llamaindex-ingestion-pipeline-bug)

```python
import os

from llama_index.core import SimpleDirectoryReader
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.node_parser import SentenceWindowNodeParser

num_cores = os.cpu_count()
num_workers = min(4, num_cores)

director_reader = SimpleDirectoryReader(
    input_dir="./data"
)

documents = director_reader.load_data()

pipeline = IngestionPipeline(
    transformations=[
        SentenceWindowNodeParser.from_defaults(
            window_size=6,
            window_metadata_key="window",
            original_text_metadata_key="original_text",
        ),
    ],
)

pipeline.run(documents=documents, show_progress=True, num_workers=num_workers)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/username/PycharmProjects/llamaindex-ingestion-pipeline-bug/main.py", line 26, in <module>
    nodes = pipeline.run(documents=documents, show_progress=True, num_workers=num_workers)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/PycharmProjects/llamaindex-ingestion-pipeline-bug/.venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/PycharmProjects/llamaindex-ingestion-pipeline-bug/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 726, in run
    nodes_parallel = p.starmap(
                     ^^^^^^^^^^
  File "/Users/username/.pyenv/versions/3.11.9/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/.pyenv/versions/3.11.9/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/Users/username/.pyenv/versions/3.11.9/lib/python3.11/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "/Users/username/.pyenv/versions/3.11.9/lib/python3.11/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/.pyenv/versions/3.11.9/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'split_by_sentence_tokenizer.<locals>.split'
```

**Comment by houtaroy** [comment]
I found the reason

In file 'llama-index-core\llama_index\core\node_parser\text\utils.py', the function `split_by_sentence_tokenizer` defined an internal function `split` and return it, but it can't pickle:

```python
def split_by_sentence_tokenizer() -> Callable[[str], List[str]]:
    import nltk

    tokenizer = nltk.tokenize.PunktSentenceTokenizer()

    # get the spans and then return the sentences
    # using the start index of each span
    # instead of using end, use the start of the next span if available
    def split(text: str) -> List[str]:
        spans = list(tokenizer.span_tokenize(text))
        sentences = []
        for i, span in enumerate(spans):
            start = span[0]
            if i < len(spans) - 1:
                end = spans[i + 1][0]
            else:
                end = len(text)
            sentences.append(text[start:end])

        return sentences

    return split
```

I'm not good at multiprocessing, I try to move `tokenizer = nltk.tokenize.PunktSentenceTokenizer()` into `split`, but `split_by_sentence_tokenizer` and `split` have different call times, this change will affect performance.

how can we extract `split` to the top level?
