### ISSUE TITLE
[Question]: read neo4j data into llama-index without local persist file

### ISSUE THREAD

**Issue by zydmtaichi** [run-llama/llama_index#14331]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Surpose we have a neo4j database with concern data, and no persist file of json format on local. Is it possible to read data only relay on neo4jgraphstore and convert the data to index?

I try to pass the graph store merely to Storagecontext and use load_index_from_storage to get the index like below code but it's not working at all. the `infer_index` is empty
```
storage_context = StorageContext.from_defaults(graph_store=graph_store)

infer_index = load_index_from_storage(storage_context=storage_context, sercice_context=sercice_context)
```

**Comment by zydmtaichi** [comment]
I notice the `PropertyGraphIndex` has the `from_existing` method, but it's not suitable for other kind index like `KnowledgeGraphIndex`, so i want to know the general method for load data from neo4j, not just for PropertyGraph

**Comment by zydmtaichi** [comment]
per my test, use `PropertyGraphIndex.from_existing` on non-PropertyGraph neo4j graph store cause a error, paste info below:
```
Traceback (most recent call last):
  File "f:\test\llamaidxinfertest.py", line 38, in <module>
    infer_index = PropertyGraphIndex.from_existing(property_graph_store=graph_store, llm=llm, embed_model=embed_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda\envs\test\Lib\site-packages\llama_index\core\indices\property_graph\base.py", line 163, in from_existing
    return cls(
           ^^^^
  File "E:\anaconda\envs\test\Lib\site-packages\llama_index\core\indices\property_graph\base.py", line 111, in __init__
    storage_context.property_graph_store.supports_vector_queries
AttributeError: 'Neo4jGraphStore' object has no attribute 'supports_vector_queries'
```

**Comment by zydmtaichi** [comment]
@dosubot it's still relay on local documents to read from neo4j
