### ISSUE TITLE
[Bug]: Groq is giving `Error`  

### ISSUE THREAD

**Issue by moonlightnexus** [run-llama/llama_index#14701]
### Bug Description

Generally after 3-4 correct responses I'm getting this 400 error while I'm just testing it using a simple chat engine no tools no query no agent nothing.

```Retrying llama_index.llms.openai.base.OpenAI._achat in 0.9220853964165006 seconds as it raised BadRequestError: Error code: 400 - {'error': {'message': "'messages.2' : for 'role:assistant' the following must be satisfied[('messages.2' : property 'status' is unsupported, did you mean 'name'?)]", 'type': 'invalid_request_error'}}. 

File ".venv\lib\site-packages\openai\_base_client.py", line 1577, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "'messages.2' : for 'role:assistant' the following must 
be satisfied[('messages.2' : property 'status' is unsupported, did you mean 'name'?)]", 'type': 'invalid_request_error'}}
```

### Version

0.10.28

### Steps to Reproduce

Simple, just use Groq LLM llama-70b with `SimpleChatEngine`

### Relevant Logs/Tracbacks

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File ".venv\lib\site-packages\llama_index\core\llms\callbacks.py", line 76, in wrapped_async_llm_chat
    f_return_val = await f(_self, messages, **kwargs)
  File ".venv\lib\site-packages\llama_index\llms\openai\base.py", line 628, in achat
    return await achat_fn(messages, **kwargs)
  File ".venv\lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File ".venv\lib\site-packages\tenacity\_asyncio.py", line 47, in __call__  
    do = self.iter(retry_state=retry_state)
  File ".venv\lib\site-packages\tenacity\__init__.py", line 314, in iter     
    return fut.result()
  File "\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 438, in result     
    return self.__get_result()
  File "\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File ".venv\lib\site-packages\tenacity\_asyncio.py", line 50, in __call__  
    result = await fn(*args, **kwargs)
  File ".venv\lib\site-packages\llama_index\llms\openai\base.py", line 675, in _achat
    response = await aclient.chat.completions.create(
  File ".venv\lib\site-packages\openai\resources\chat\completions.py", line 1334, in create
    return await self._post(
  File ".venv\lib\site-packages\openai\_base_client.py", line 1783, in post  
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File ".venv\lib\site-packages\openai\_base_client.py", line 1486, in request
    return await self._request(
  File ".venv\lib\site-packages\openai\_base_client.py", line 1577, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "'messages.2' : for 'role:assistant' the following must 
be satisfied[('messages.2' : property 'status' is unsupported, did you mean 'name'?)]", 'type': 'invalid_request_error'}}
```

**Comment by moonlightnexus** [comment]
@dosu its already the same
