### ISSUE TITLE
[Bug]: No available version integration of NvidiaTriton

### ISSUE THREAD

**Issue by rkoyanagi** [run-llama/llama_index#14716]
### Bug Description

First I use
`
llama-index 0.9.13
`
and 
`pip install llama-index-llms-nvidia-triton`(version==0.0.1  is installed and llama-index-core==0.9.56 installed)

But I cannot import client. (Below code was error.)
```
llama_index.llms import NvidiaTriton
```

I saw repository, and  at version0.10, nvidia_triton_client added.
So I update 
`llama_index==0.10.0`
But below error occurred.
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llama-index-llms-nvidia-triton 0.0.1 requires llama-index-core<0.10.0,>=0.9.32, but you have llama-index-core 0.10.54.post1 which is incompatible.
```

So I tried
```pip install llama-index-core==0.9.56```
But below error occurred.
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llama-index 0.10.0 requires llama-index-core<0.11.0,>=0.10.0, but you have llama-index-core 0.9.56 which is incompatible.
llama-index-agent-openai 0.1.7 requires llama-index-core<0.11.0,>=0.10.1, but you have llama-index-core 0.9.56 which is incompatible.
llama-index-embeddings-openai 0.1.10 requires llama-index-core<0.11.0,>=0.10.1, but you have llama-index-core 0.9.56 which is incompatible.
llama-index-llms-openai 0.1.25 requires llama-index-core<0.11.0,>=0.10.24, but you have llama-index-core 0.9.56 which is incompatible.
llama-index-multi-modal-llms-openai 0.1.7 requires llama-index-core<0.11.0,>=0.10.1, but you have llama-index-core 0.9.56 which is incompatible.
llama-index-program-openai 0.1.6 requires llama-index-core<0.11.0,>=0.10.1, but you have llama-index-core 0.9.56 which is incompatible.
llama-index-question-gen-openai 0.1.3 requires llama-index-core<0.11.0,>=0.10.1, but you have llama-index-core 0.9.56 which is incompatible.
llama-index-readers-file 0.1.30 requires llama-index-core<0.11.0,>=0.10.37.post1, but you have llama-index-core 0.9.56 which is incompatible.
```

I think no available version set integration of NvidiaTriton.
How to use NvidiaTriton Integration?

### Version

0.10.0

### Steps to Reproduce

pip install above version set.

**Comment by rkoyanagi** [comment]
I tried, but at `pip install llama-index-llms-nvidia-triton==0.1.5`
below error occurred.
```
ERROR: Cannot install tritonclient[all]==2.41.1, tritonclient[all]==2.42.0, tritonclient[all]==2.43.0, tritonclient[all]==2.44.0, tritonclient[all]==2.45.0, tritonclient[all]==2.46.0 and tritonclient[all]==2.47.0 because these package versions have conflicting dependencies.
```

**Comment by rkoyanagi** [comment]
I tried  with this version, and exec proposed code.
But below error occurred.what library version was wrong?

Code
```
from llama_index.llms.nvidia_triton import NvidiaTriton

# Provide the correct URL for your Triton server instance
triton_url = "localhost:8001"

# Instantiate the NvidiaTriton class
triton_client = NvidiaTriton(server_url=triton_url)

# Call the complete method with a prompt
resp = triton_client.complete("The tallest mountain in North America is ")
print(resp.text)
```

Version
```
llama-index==0.10.55
llama-index-core==0.10.55
llama-index-llms-nvidia-triton==0.1.5
grpcio-health-checking==1.64.1
grpcio-tools==1.64.1
tritonclient==2.47.0
```

Error
```
Traceback (most recent call last):
  File "/home/ubuntu/dev_weaviate/a.py", line 10, in <module>
    resp = triton_client.complete("The tallest mountain in North America is ")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/llama_index/llms/nvidia_triton/base.py", line 270, in complete
    client.stop_stream(model_params["model_name"], request_id)
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/llama_index/llms/nvidia_triton/utils.py", line 376, in stop_stream
    self._send_stop_signals(model_name, request_id)
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/llama_index/llms/nvidia_triton/utils.py", line 268, in _send_stop_signals
    self._client.async_stream_infer(
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/tritonclient/grpc/_client.py", line 1934, in async_stream_infer
    self._stream._enqueue_request(request)
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/tritonclient/grpc/_infer_stream.py", line 121, in _enqueue_request
    raise_error(
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/tritonclient/utils/__init__.py", line 40, in raise_error
    raise InferenceServerException(msg=msg) from None
tritonclient.utils.InferenceServerException: The stream is no longer in valid state, the error detail is reported through provided callback. A new stream should be started after stopping the current stream.
Exception ignored in: <function InferenceServerClient.__del__ at 0x7529d3d58cc0>
Traceback (most recent call last):
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/tritonclient/grpc/_client.py", line 257, in __del__
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/tritonclient/grpc/_client.py", line 265, in close
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/grpc/_channel.py", line 2250, in close
  File "/home/ubuntu/dev_weaviate/venv/lib/python3.12/site-packages/grpc/_channel.py", line 2231, in _close
AttributeError: 'NoneType' object has no attribute 'StatusCode'
```

**Comment by rkoyanagi** [comment]
In Triton Inference Server logs, below error occurred.How to stop streaming mode?

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Streaming is only supported if model is deployed using decoupled mode.
Signal (6) received.
 0# 0x000055AE18C9EA9D in /opt/tritonserver/bin/tritonserver
 1# 0x00007BA54A15B520 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# pthread_kill in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# raise in /usr/lib/x86_64-linux-gnu/libc.so.6
 4# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 5# 0x00007BA54C076B9E in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007BA54C08220C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007BA54C082277 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 8# 0x00007BA54C0824D8 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 9# 0x00007BA4D34696FA in /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so
10# 0x00007BA4D3490F9C in /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so
11# 0x00007BA4D34912FB in /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so
12# 0x00007BA4D3492BDB in /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so
13# 0x00007BA4D3496C2C in /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so
14# TRITONBACKEND_ModelInstanceExecute in /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so
15# 0x00007BA54A92BF04 in /opt/tritonserver/bin/../lib/libtritonserver.so
16# 0x00007BA54A92C26B in /opt/tritonserver/bin/../lib/libtritonserver.so
17# 0x00007BA54AA3E88D in /opt/tritonserver/bin/../lib/libtritonserver.so
18# 0x00007BA54A930694 in /opt/tritonserver/bin/../lib/libtritonserver.so
19# 0x00007BA54C0B0253 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
20# 0x00007BA54A1ADAC3 in /usr/lib/x86_64-linux-gnu/libc.so.6
21# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
I0718 01:00:40.759750 391 pb_stub.cc:1971]  Non-graceful termination detected.
I0718 01:00:40.759849 390 pb_stub.cc:1971]  Non-graceful termination detected.
I0718 01:00:40.886518 426 pb_stub.cc:1971]  Non-graceful termination detected.
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node ip-10-0-3-52 exited on signal 6 (Aborted).
--------------------------------------------------------------------------

```

**Comment by rkoyanagi** [comment]
@dosu.

**Comment by rkoyanagi** [comment]
@dosu
Proposed method `stream_complete` has grammatical error, and error I occurred is not `NotImplementedError ` 
I occurred below error ```tritonclient.utils.InferenceServerException: The stream is no longer in valid state, the error detail is reported through provided callback. A new stream should be started after stopping the current stream.
Exception ignored in: <function InferenceServerClient.__del__ at 0x7529d3d58cc0>```.
