### ISSUE TITLE
[Bug]: An error occurred while accessing SharePoint: 'name'

### ISSUE THREAD

**Issue by sharad28** [run-llama/llama_index#14734]
### Bug Description

i had create a folder in sharepoint site. 
i had share the path for site as well as for folder. however, i m getting error 

An error occurred while accessing SharePoint: 'name'

### Version

llama-index-core==0.10.55

### Steps to Reproduce

Trying to create a chatbot using llama-hub connect i.e., from llama_index.readers.microsoft_sharepoint import SharePointReader
start with create a new sharepoint site and upload documents in document under folder and subfolders.
if you try to read them using using the sharepointreader
i had received following error : An error occurred while accessing SharePoint: 'name'

Traceback (most recent call last):
  File "c:\Users\sarad\OneDrive\Documents\GenAI\Chatbot_streamlit_llamaindex\streamlit_app.py", line 51, in <module>
    index = load_data()
  File "C:\Users\sarad\OneDrive\Documents\GenAI\Chatbot_streamlit_llamaindex\env3\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 168, in wrapper
    return cached_func(*args, **kwargs)
  File "C:\Users\sarad\OneDrive\Documents\GenAI\Chatbot_streamlit_llamaindex\env3\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 199, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "C:\Users\sarad\OneDrive\Documents\GenAI\Chatbot_streamlit_llamaindex\env3\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 224, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "C:\Users\sarad\OneDrive\Documents\GenAI\Chatbot_streamlit_llamaindex\env3\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 280, in _handle_cache_miss
  File "c:\Users\sarad\OneDrive\Documents\GenAI\Chatbot_streamlit_llamaindex\streamlit_app.py", line 48, in load_data
    index = VectorStoreIndex.from_documents(docs,show_progress=True)
  File "C:\Users\sarad\OneDrive\Documents\GenAI\Chatbot_streamlit_llamaindex\env3\lib\site-packages\llama_index\core\indices\base.py", line 135, in from_documents
    for doc in documents:
TypeError: 'NoneType' object is not iterable

**Comment by sharad28** [comment]
i have used the following : 

@st.cache_resource(show_spinner=False)
def load_data():
    with st.spinner(text='loading and indexing data'):
        print("enter the loader")
        print({
    "client_id":os.getenv('client_id'),
    "client_secret":os.getenv('client_secret'),
    "tenant_id":os.getenv('tenant_id')})
        loader = SharePointReader(
    client_id=os.getenv('client_id'),
    client_secret=os.getenv('client_secret'),
    tenant_id=os.getenv('tenant_id'),
        sharepoint_site_name="sharepointsite",
        sharepoint_folder_path="internal_folder")
        print(f"loader : {loader}")
        try:
            docs = loader.load_data(
        sharepoint_site_name="sharepointsite",
        sharepoint_folder_path="internal_folder",
        recursive=True)
        except Exception as e:
            print(e)
        # reader = SimpleDirectoryReader('data')
        # docs = reader.load_data()  
        print(docs)      
        index = VectorStoreIndex.from_documents(docs,show_progress=True)
        return index
    and all the parameters where correct 
    still i was getting the error
    
    An error occurred while accessing SharePoint: 'name'

**Comment by sharad28** [comment]
I know how to solve the issue with window file path. can i create a PR

**Comment by sharad28** [comment]
I know how to solve the issue with window file path. can i create a PR?

**Comment by sharad28** [comment]
Hi @dosu
I know how to solve the issue with window file path. can i create a PR?

**Comment by sharad28** [comment]
Hi @dosu
please share the process of PR

**Comment by sharad28** [comment]
hi @dosu 
what is pending for PR review?

**Comment by sher-somas** [comment]
I keep getting An error occurred while accessing SharePoint: The specified sharepoint site <site-name> is not found error. 

I've given all the required permissions. Can you please elaborate on how to get the sharepoint site name?
