### ISSUE TITLE
[Bug]: [OpenAILike] Cannot use llm_chat_callback on an instance without a callback_manager attribute

### ISSUE THREAD

**Issue by allex083** [run-llama/llama_index#14786]
### Bug Description

I am using OpenAILike

My code snippet:
```
from llama_index.legacy.llms.openai_like import OpenAILike, ChatMessage
from llama_index.core.llms.callbacks import llm_completion_callback
from llama_index.core import Settings
from llama_index.legacy.callbacks import CallbackManager

from llama_index.embeddings.openai import OpenAIEmbedding

# Define a callback manager
cb_manager = CallbackManager()
print(isinstance(cb_manager, CallbackManager))

# define LLM
llm = OpenAILike(api_key="EMPTY", 
                 api_base="http://localhost:9997/v1", 
                 model="llama3", 
                 is_chat_model=True, 
                 temperature=0.3, 
                 callback_manager=cb_manager
                 )

Settings.llm = llm
Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-small")
Settings.node_parser = SentenceSplitter(chunk_size=512, chunk_overlap=20)
Settings.num_output = 512
Settings.context_window = 3900
Settings.chunk_size = 512

callback_manager = getattr(llm, "callback_manager", None)
print(isinstance(callback_manager, CallbackManager))

chat_history = [  
     ChatMessage(role="system", content="You are a bartender."),  
     ChatMessage(role="user", content="What do I enjoy drinking?"),  
 ]  
output = llm.chat(chat_history)  
print(output)
```

Below is the console output:
```
True
False
Traceback (most recent call last):
  File "/root/iGPTAgentEngine/server/create_graph.py", line 63, in <module>
    output = llm.chat(chat_history)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/legacy/llms/openai_like.py", line 113, in chat
    return super().chat(messages, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/legacy/llms/base.py", line 91, in wrapped_llm_chat
    with wrapper_logic(_self) as callback_manager:
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/legacy/llms/base.py", line 37, in wrapper_logic
    raise ValueError(
ValueError: Cannot use llm_chat_callback on an instance without a callback_manager attribute.
```

### Version

0.10.55

### Steps to Reproduce

1.create an OpenAILike llm;
2.call llm.chat()
3.error gets printed in the console.

### Relevant Logs/Tracbacks

```shell
True
False
Traceback (most recent call last):
  File "/root/iGPTAgentEngine/server/create_graph.py", line 63, in <module>
    output = llm.chat(chat_history)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/legacy/llms/openai_like.py", line 113, in chat
    return super().chat(messages, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/legacy/llms/base.py", line 91, in wrapped_llm_chat
    with wrapper_logic(_self) as callback_manager:
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/legacy/llms/base.py", line 37, in wrapper_logic
    raise ValueError(
ValueError: Cannot use llm_chat_callback on an instance without a callback_manager attribute.
```

**Comment by logan-markewich** [comment]
Any reason to use legacy here?  Mixing legacy and non legacy imports is a bad time

`pip install llama-index-llms-openai-like`

```
from llama_index.le.llms.openai_like import OpenAILike
from llama_index.core.llms ChatMessage 
from llama_index.core.llms.callbacks import llm_completion_callback
from llama_index.core import Settings
from llama_index.core.callbacks import CallbackManager

from llama_index.embeddings.openai import OpenAIEmbedding

```

**Comment by allex083** [comment]
When I changed `from llama_index.legacy.callbacks import CallbackManager` to `from llama_index.core.llms.callbacks import CallbackManager`, then the console outputs:
```
    llm = OpenAILike(api_key="EMPTY",
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/legacy/llms/openai.py", line 153, in __init__
    super().__init__(
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for OpenAILike
callback_manager
  instance of CallbackManager expected (type=type_error.arbitrary_type; expected_arbitrary_type=CallbackManager)
```

But if I used legacy CallbackManager, llm.callback_manager is NOT instance of CallbackManager. Why?
@tobi

**Comment by allex083** [comment]
close.
