### ISSUE TITLE
[Bug]: CUDA error: device-side assert triggered when calling index.refresh_ref_docs(documents=documents, batch_size=5)

### ISSUE THREAD

**Issue by allex083** [run-llama/llama_index#14798]
### Bug Description

I was refreshing the graphic from local documents and got this error. Xinference got down. The error is so weird!

My code snippet: 
```
from llama_index.core import KnowledgeGraphIndex, SimpleDirectoryReader
from llama_index.core import StorageContext
from llama_index.graph_stores.neo4j import Neo4jGraphStore
from llama_index.graph_stores.neo4j import Neo4jPropertyGraphStore
from llama_index.core import PropertyGraphIndex

documents = SimpleDirectoryReader(
    "/root/autodl-tmp/knowledge_base/documents"
).load_data()

graph_store = Neo4jPropertyGraphStore(
    username=username,
    password=password,
    url=url,
    database=database,
)

storage_context = StorageContext.from_defaults(graph_store=graph_store)
# loading from existing graph store (and optional vector store)
# load from existing graph/vector store
index: PropertyGraphIndex = PropertyGraphIndex.from_existing(
    property_graph_store=graph_store,
    embed_kg_nodes=True,
)
print("index before refresh: ", index)

# NOTE: can take a while!
refreshed_documents = index.refresh_ref_docs(documents=documents, batch_size=1)
print("refreshed_documents: ", refreshed_documents)
```

The python console output below:
```
(agentengine) root@autodl-container-e64141a3a0-b3043a09:~/iGPTAgentEngine/server# python refresh_graph.py
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: /hub/bge-m3/Xorbits/bge-m3
INFO:sentence_transformers.SentenceTransformer:2 prompts are loaded, with the keys: ['query', 'text']
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The procedure has a deprecated field. ('config' used by 'apoc.meta.graphSample' is deprecated.)} {position: line: 1, column: 1, offset: 0} for query: "CALL apoc.meta.graphSample() YIELD nodes, relationships RETURN nodes, [rel in relationships | {name:apoc.any.property(rel, 'type'), count: apoc.any.property(rel, 'count')}] AS relationships"
index before refresh:  <llama_index.core.indices.property_graph.base.PropertyGraphIndex object at 0x7fdc6b0efe50>
INFO:httpx:HTTP Request: POST http://localhost:9997/v1/chat/completions "HTTP/1.1 200 OK"
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.10s/it]
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The procedure has a deprecated field. ('config' used by 'apoc.meta.graphSample' is deprecated.)} {position: line: 1, column: 1, offset: 0} for query: "CALL apoc.meta.graphSample() YIELD nodes, relationships RETURN nodes, [rel in relationships | {name:apoc.any.property(rel, 'type'), count: apoc.any.property(rel, 'count')}] AS relationships"
INFO:openai._base_client:Retrying request to /chat/completions in 0.873289 seconds
INFO:httpx:HTTP Request: POST http://localhost:9997/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 0.834315 seconds
INFO:httpx:HTTP Request: POST http://localhost:9997/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 1.902912 seconds
INFO:httpx:HTTP Request: POST http://localhost:9997/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 1.728772 seconds
INFO:httpx:HTTP Request: POST http://localhost:9997/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 3.661815 seconds
INFO:httpx:HTTP Request: POST http://localhost:9997/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 3.074013 seconds
^CTraceback (most recent call last):
  File "/root/iGPTAgentEngine/server/refresh_graph.py", line 133, in <module>
    refreshed_documents = index.refresh_ref_docs(documents=documents, batch_size=1)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/core/indices/base.py", line 371, in refresh_ref_docs
    self.insert(document, **update_kwargs.pop("insert_kwargs", {}))
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/core/indices/base.py", line 246, in insert
    self.insert_nodes(nodes, **insert_kwargs)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/core/indices/base.py", line 234, in insert_nodes
    self._insert(nodes, **insert_kwargs)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/core/indices/property_graph/base.py", line 391, in _insert
    self._insert_nodes(nodes)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/llama_index/core/indices/property_graph/base.py", line 198, in _insert_nodes
    nodes = asyncio.run(
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
Exception ignored in: <function Driver.__del__ at 0x7fdc6b4a5240>
Traceback (most recent call last):
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/neo4j/_sync/driver.py", line 544, in __del__
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/neo4j/_sync/driver.py", line 640, in close
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 480, in close
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 414, in _close_connections
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 950, in close
  File "/root/autodl-tmp/miniconda3/envs/agentengine/lib/python3.10/site-packages/neo4j/_sync/io/_bolt5.py", line 327, in goodbye
AttributeError: 'NoneType' object has no attribute 'debug'
```

Pls look at the logs/tracebacks for the Xinference console output. 

Awaiting your kind help. Thanks!

### Version

0.10.55

### Steps to Reproduce

1. start Xinference;
2. run local models;
3. start neo4j server;
4. run the code and then got the error.

### Relevant Logs/Tracbacks

```shell
2024-07-18 02:03:45,638 xinference.api.restful_api 29288 ERROR    [address=0.0.0.0:41737, pid=29453] CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
Traceback (most recent call last):
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/model.py", line 505, in chat
    response = await self._call_wrapper(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/model.py", line 388, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/model/llm/pytorch/core.py", line 759, in chat
    c = self.generate(full_prompt, generate_config)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/model/llm/pytorch/core.py", line 390, in generate
    for completion_chunk, completion_usage in generate_stream(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/model/llm/pytorch/utils.py", line 196, in generate_stream
    out = model(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1221, in forward
    outputs = self.model(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1023, in forward
    layer_outputs = decoder_layer(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 777, in forward
    hidden_states = self.mlp(hidden_states)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 186, in forward
    return self.down_proj(self.act_fn(self.gate_proj(hidden_state)) * self.up_proj(hidden_state))
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: [address=0.0.0.0:41737, pid=29453] CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
2024-07-18 02:03:45,648 xinference.api.restful_api 29288 ERROR    [address=0.0.0.0:41737, pid=29453] CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
Traceback (most recent call last):
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/model.py", line 505, in chat
    response = await self._call_wrapper(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/core/model.py", line 388, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/model/llm/pytorch/core.py", line 759, in chat
    c = self.generate(full_prompt, generate_config)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/model/llm/pytorch/core.py", line 390, in generate
    for completion_chunk, completion_usage in generate_stream(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/xinference/model/llm/pytorch/utils.py", line 196, in generate_stream
    out = model(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1221, in forward
    outputs = self.model(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1023, in forward
    layer_outputs = decoder_layer(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 763, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 700, in forward
    attn_output = self.o_proj(attn_output)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/miniconda3/envs/xinference/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: [address=0.0.0.0:41737, pid=29453] CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [1,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [2,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [3,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [4,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [5,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [6,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [7,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [8,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [9,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
```

**Comment by allex083** [comment]
ps, xinference launched qwen2-7b with transformers engine and the model format is pytorch. quantization is none.

**Comment by logan-markewich** [comment]
Usually this is some kind of max length error. An input was too long

**Comment by allex083** [comment]
> Usually this is some kind of max length error. An input was too long

Thank you. Probably yes. But how to resolve this problem? I just call index.refresh_ref_docs(documents=documents, batch_size=1) in order to refresh the index in case of document changes. And the local model's context length is quite limited.

**Comment by allex083** [comment]
What if I create graph from same documents (no matter whether have changes or not) and store to neo4j and persist again and again, to replacing the index.refresh_ref_docs() call? Any side effect?
