### ISSUE TITLE
[Question]: Pandas Query Engine does not give proper response( Especially when exposed via API, works well in local jupyter notebook)

### ISSUE THREAD

**Issue by Sridevi17j** [run-llama/llama_index#14804]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Below is my code

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import pandas as pd
from IPython.display import Markdown, display
import time

import pandas as pd
from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.experimental.query_engine import PandasQueryEngin

# Initialize the PandasQueryEngine

query_engine = PandasQueryEngine(df=df, llm=llm, verbose=True, synthesize_response=True)

class Query(BaseModel):
    query: str

app = FastAPI()

# Load the CSV file
df = pd.read_csv("sample.csv")

@app.post("/query")
async def process_query(query: Query):
    try:
        response = query_engine.query(query.query)
        return {"response": response.response}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=7000)
    
    I am using Azure OPenAI for LLM, the same code, without API, works very well, when I expose it via API, response is like below 
    {
  "query": "Give me the number of users in the document"
}
{
    "response": "The number of unique users in the document is [insert output from running the Pandas instruction]."
}

**Comment by Sridevi17j** [comment]
@dosu, we tried multiple ways, it does not work when it comes to API or a single python file. But the same code works in Jupyter notebook. I wonder how?

**Comment by Sridevi17j** [comment]
@dosu, This is my question- "What was the first activity".

This question works on Jupyter, and gives the first activity name. Because it interprets the question well and search for the column name "Operation Name".  But the same code when I execute in python API, it searched for the column named " Activity" and giving me the Key Error, which is resulting in "    The first activity cannot be determined as there is no information provided in the query results."

Your given code also does not work in API... what is happening ?

**Comment by Sridevi17j** [comment]
@dosu, The environment is same for both Jupyter and FastAPIPython(Both uses same python version). What I understood is when executed in Jupyter it interprets the prompt to right query... like from activity to correct column name " Operation Name" .. But in Python file, "Activity" is being interpreted as activity itself and searches the column in the dataframe "Activity" and fails... If I give the right column name like "Operation Name" then it works in API python.. why so?

**Comment by Sridevi17j** [comment]
@dosu, could you give me the complete code for the pandad query engine that should work on fast API, with the prompt formatting you just mentioned above?

**Comment by Sridevi17j** [comment]
@dosu, your code give below error
{
    "detail": "1 validation error for LLMPredictStartEvent\ntemplate\n  Can't instantiate abstract class BasePromptTemplate without an implementation for abstract methods 'format', 'format_messages', 'get_template', 'partial_format' (type=type_error)"
}

**Comment by Sridevi17j** [comment]
@dosu, My prompt was- "what was the first activity"

and I get below error


> Pandas Instructions:
```
df['Activity'].iloc[0]
```
Traceback (most recent call last):
  File "C:\Users\sride\PycharmProjects\Test AI\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Activity'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sride\PycharmProjects\Test AI\.venv\Lib\site-packages\llama_index\experimental\query_engine\pandas\output_parser.py", line 54, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sride\PycharmProjects\Test AI\.venv\Lib\site-packages\llama_index\experimental\exec_utils.py", line 159, in safe_eval  
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "C:\Users\sride\PycharmProjects\Test AI\.venv\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sride\PycharmProjects\Test AI\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Activity'
> Pandas Output: There was an error running the output as Python code. Error message: 'Activity'
Traceback (most recent call last):
  File "C:\Users\sride\PycharmProjects\Test AI\.venv\Lib\site-packages\llama_index\experimental\query_engine\pandas\output_parser.py", line 40, in default_output_processor
    tree = ast.parse(output)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\sride\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    There was an error running the output as Python code. Error message: 'Activity'
    
    I don't know why the same code runs well with Jupyter without API,

**Comment by Sridevi17j** [comment]
@dosu, no luck, still the same error

**Comment by Sridevi17j** [comment]
@logan-markewich , to explain the issue, 

I'm encountering an issue with the pandas query engine behaving differently in various environments. Let me explain:
The setup:

I have a simple pandas query engine code.
My dataframe has a column named "Operation Name".

In Jupyter Notebook:

The code works perfectly.
When I input the query "What was the first activity?", it correctly interprets "activity" as the "Operation Name" column.
It searches the "Operation Name" column and returns the expected results.

However, in a .py file or when exposed as an API:

The same code doesn't work as expected.
Using the same query "What was the first activity?", the query engine literally searches for an "Activity" column.
Since there's no "Activity" column in my dataframe, it throws a KeyError.
The error message is: "> Pandas Output: There was an error running the output as Python code. Error message: 'Activity'"

It seems the query engine's ability to map natural language to the correct column name is working in Jupyter, but failing in other environments. Do you have any insights on why this might be happening or how to resolve it?

Below is my code- I am using Azure OpenAI as an LLM( I am not giving LLM details here), but I have declared it in my code

`from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.experimental.query_engine.pandas.pandas_query_engine import PandasQueryEngine
import pandas as pd

#llm = AzureOpenAI()- I have given the details in my code

df= pd.read_csv("sample.csv")

query_engine = PandasQueryEngine(df=df,llm=llm,verbose=True,synthesize_response=True)

response = query_engine.query("What was the first activity")
print(response.response)`

**Comment by Sridevi17j** [comment]
@dosu, @logan-markewich 

Any help can be done on my issue pls....

**Comment by Sridevi17j** [comment]
@Dosu any idea how long should i wait for someone to address this issue.. I understand and I can wait. But just want to know the timeline

**Comment by Sridevi17j** [comment]
@logan-markewich  is it possible to help me on this?

@dosu, is it possible to get any update?

**Comment by Sridevi17j** [comment]
@pulkitmehtaworkmetacube  could you share your working code pls
