### ISSUE TITLE
[Bug]: Unexpected keyword argument for run_transformations() method

### ISSUE THREAD

**Issue by FlorentGrenier** [run-llama/llama_index#14809]
### Bug Description

In the `run()` method (line 542 in llama_index.core.ingestion.**pipeline.py**) the parameter show_progress is passed to the `run_transformation()` method, but this method doesn't take this parameter.

Instantiate the run_transformations() method in the run() method: :
```       Python      
nodes = run_transformations(
  nodes_to_run,
  self.transformations,
  show_progress=show_progress,
  cache=self.cache if not self.disable_cache else None,
  cache_collection=cache_collection,
  in_place=in_place,
  **kwargs,
)
```

run_transformations() method signature :

``` Python
def run_transformations(
    nodes: List[BaseNode],
    transformations: Sequence[TransformComponent],
    in_place: bool = True,
    cache: Optional[IngestionCache] = None,
    cache_collection: Optional[str] = None,
    **kwargs: Any,
) -> List[BaseNode]:
```

### Version

0.10.55

### Steps to Reproduce

Run a pipeline ingestion

My code : 
``` Python
pipeline = IngestionPipeline(
    transformations=[
        sentence_split,
        text_cleaner,
        self.embed_model
    ],
    vector_store=self.vector_store,
    docstore=self.docstore
)
pipeline.run(documents=documents)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\data\git\.......\test.py", line 110, in <module>
    data_ingestion.main()
  File "C:\data\git\.......\test.py", line 105, in main
    self.create_index_local()
  File "C:\data\git\.......\test.py", line 83, in create_index_local
    nodes = self.run_pipeline(documents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\data\git\.......\test.py", line 101, in run_pipeline
    nodes = pipeline.run(documents=documents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\anaconda3\envs\llama-index\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 230, in wrapper      
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\anaconda3\envs\llama-index\Lib\site-packages\llama_index\core\ingestion\pipeline.py", line 122, in run_transformations  
    nodes = transform(nodes, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\anaconda3\envs\llama-index\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 221, in wrapper      
    bound_args = inspect.signature(func).bind(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\anaconda3\envs\llama-index\Lib\inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\anaconda3\envs\llama-index\Lib\inspect.py", line 3231, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'show_progress'
```

**Comment by skvrd** [comment]
The `show_process` ends up in `**kwargs: Any`.

It seems like one of the transformations is not accepting the `show_progress`.

Which  sentence_split,  text_cleaner are you using? Could you provide class names, or some code?

**Comment by FlorentGrenier** [comment]
Yes, my code : 
```    Python
def run_pipeline(self, documents: List[Document]) -> Sequence[BaseNode]:
  sentence_split = SentenceSplitter(chunk_size=Configs.chunk_size, chunk_overlap=Configs.chunk_overlap)
  text_cleaner = TextCleaner()
  
  pipeline = IngestionPipeline(
      transformations=[
          sentence_split,
          text_cleaner,
          self.embed_model
      ]
  )
  nodes = pipeline.run(documents=documents)
  return nodes

class TextCleaner(TransformComponent):
    def __init__(self):
        self.nlp = spacy.load(Configs.spacy_language_fr)
        self.stop_words = set(stopwords.words('french') + stopwords.words('english'))
        self.punctuations = set(['.', ',', '/', '!', '?', ';', ':', '(', ')', '[', ']', '-', '_', '%'])

    def __call__(self, nodes):
        for node in nodes:
            node.text = self.clean_text(node.text)
        return nodes
    
    def clean_text(self, text: str) -> str:
        doc = self.nlp(text.lower())
        keywords = [token.lemma_ for token in doc if token.text not in self.stop_words and token.text not in self.punctuations and not token.is_digit and len(token.text) > 1]
        clean_data = ' '.join(keywords)
        return clean_data
``` 

I don't think the error comes from my code, but from the llama_index library, because in the `run()` method when `run_transformation()` is instantiated, it tries to pass `show_progress`.

**Comment by logan-markewich** [comment]
Pretty sure you should have this in your code

```
 def __call__(self, nodes, **kwargs: Any):
        for node in nodes:
            node.text = self.clean_text(node.text)
        return nodes
```

**Comment by is4dmitry** [comment]
@FlorentGrenier, @logan-markewich right, you should pass kwargs into __call__ method.
