### ISSUE TITLE
[Bug]: PrevNextNodePostprocessor using index.docstore from VectorStoreIndex don't retrieve node_id

### ISSUE THREAD

**Issue by AutoScrape123TX** [run-llama/llama_index#14829]
### Bug Description

When using `PrevNextNodePostprocessor` with `docstore=index.docstore` from `VectorStoreIndex`, the node postprocessor seems to always use `doc_id` instead of `node_id` for retrieving other nodes.
```
def get_query_engine_from_index(self, index: VectorStoreIndex, similarity_top_k: int, streaming: bool) -> BaseQueryEngine:
    # configure retriever
    retriever = VectorIndexRetriever(
        index=index,
        similarity_top_k=10,
        verbose=True
    )

    # configure response synthesizer with special prompts
    response_synthesizer = get_response_synthesizer(
        response_mode=ResponseMode.NO_TEXT
    )

    print(index.docstore.get_node("000d1ca2-ed42-49d3-b915-863cced4ebf4"))
    print(index.docstore.get_document("000d1ca2-ed42-49d3-b915-863cced4ebf4"))

    # assemble query engine
    query_engine = RetrieverQueryEngine(
        retriever=retriever,
        response_synthesizer=response_synthesizer,
        node_postprocessors=[
            PrevNextNodePostprocessor(
                docstore=index.docstore,
                mode="next",
                num_nodes=1)
        ]
    )
    return query_engine
```

### Version

0.10.55

### Steps to Reproduce

Just create a 
 ```
initial_node = TextNode(
    text=issue_body,
    id_=current_node_id,
    metadata=node_metadata
)
```

and store it using a `VectorStoreIndex` then use the above snippet.

Using `print(index.docstore.get_node("000d1ca2-ed42-49d3-b915-863cced4ebf4"))`  or `print(index.docstore.get_document("000d1ca2-ed42-49d3-b915-863cced4ebf4"))` always try to retrieve a `doc_id` while the first one is supposed to retrieve a `node_id`...

### Relevant Logs/Tracbacks

```shell
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:6333/collections/torproject_nyx/points/search "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:6333/collections/torproject_nyx/points/search "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/modules/frontend/every_tests.py", line 53, in <module>
    rag_manager.start_question_thread_with_query_engine(query_engine=query_engine, streaming=True)
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/modules/rag/rag_manager.py", line 106, in start_question_thread_with_query_engine
    response = query_engine.query(question)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/base/base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 189, in _query
    nodes = self.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 145, in retrieve
    return self._apply_node_postprocessors(nodes, query_bundle=query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 138, in _apply_node_postprocessors
    nodes = node_postprocessor.postprocess_nodes(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/postprocessor/types.py", line 56, in postprocess_nodes
    return self._postprocess_nodes(nodes, query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/postprocessor/node.py", line 186, in _postprocess_nodes
    all_nodes.update(get_forward_nodes(node, self.num_nodes, self.docstore))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/postprocessor/node.py", line 116, in get_forward_nodes
    next_node = docstore.get_node(next_node_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/storage/docstore/types.py", line 181, in get_node
    doc = self.get_document(node_id, raise_error=raise_error)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/storage/docstore/keyval_docstore.py", line 354, in get_document
    raise ValueError(f"doc_id {doc_id} not found.")
ValueError: doc_id 17454cda-4b3d-4d1e-b854-1d19cdb3a057 not found.


Above is the output when running full script, when adding the test print : 

Traceback (most recent call last):
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/modules/frontend/every_tests.py", line 51, in <module>
    query_engine = rag_manager.get_query_engine_from_index(index=index, similarity_top_k=10, streaming=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/modules/rag/rag_manager.py", line 76, in get_query_engine_from_index
    print(index.docstore.get_node("000d1ca2-ed42-49d3-b915-863cced4ebf4"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/storage/docstore/types.py", line 181, in get_node
    doc = self.get_document(node_id, raise_error=raise_error)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/storage/docstore/keyval_docstore.py", line 354, in get_document
    raise ValueError(f"doc_id {doc_id} not found.")
ValueError: doc_id 000d1ca2-ed42-49d3-b915-863cced4ebf4 not found.


Traceback (most recent call last):
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/modules/frontend/every_tests.py", line 51, in <module>
    query_engine = rag_manager.get_query_engine_from_index(index=index, similarity_top_k=10, streaming=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/modules/rag/rag_manager.py", line 77, in get_query_engine_from_index
    print(index.docstore.get_document("000d1ca2-ed42-49d3-b915-863cced4ebf4"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bb/Documents/VERYPLUGAPPSS/GITHUB_CHAT/github_rag/venv/lib/python3.11/site-packages/llama_index/core/storage/docstore/keyval_docstore.py", line 354, in get_document
    raise ValueError(f"doc_id {doc_id} not found.")
ValueError: doc_id 000d1ca2-ed42-49d3-b915-863cced4ebf4 not found.
```

**Comment by logan-markewich** [comment]
get_node() calls get_document 😅 They are the same method

My guess is maybe you are using a vector db integration, and the docstore is not populated by default in that case

**Comment by logan-markewich** [comment]
https://colab.research.google.com/drive/1mqmS7K4uXgPXi-v6UagIEmeMgzYOPeWK?usp=sharing

**Comment by AutoScrape123TX** [comment]
@logan-markewich Yes exactly I'm using a vector db integration with qdrant. 

`
vector_store = self.qdrant_manager.get_vector_store_from_collection(collection_name=collection_name)
index = VectorStoreIndex.from_vector_store(
    vector_store=vector_store,
    service_context=self.service_context
)`

`
 def _create_a_new_vector_collection_if_not_exists(self, collection_name: str):
        if not self.qdrant_client.collection_exists(collection_name=collection_name):
            self.qdrant_client.create_collection(
                collection_name=collection_name,
                vectors_config=models.VectorParams(size=3072, distance=models.Distance.COSINE, on_disk=True),
                optimizers_config=models.OptimizersConfigDiff(
                    indexing_threshold=0,
                ),
            )

    def get_vector_store_from_collection(self, collection_name: str) -> QdrantVectorStore:
        self._create_a_new_vector_collection_if_not_exists(collection_name=collection_name)
        return QdrantVectorStore(client=self.qdrant_client, collection_name=collection_name)
`

I try to found out how to populate a docstore with db integration and I update here.

**Comment by AutoScrape123TX** [comment]
@logan-markewich So i have try your example and it works, but when doing 

```
vector_store = self.qdrant_manager.get_vector_store_from_collection(collection_name=collection_name)
index = VectorStoreIndex.from_vector_store(
    vector_store=vector_store,
    service_context=self.service_context
)

print(index.docstore.get_node("uuid"))
```

The docstore is not reconstructed when using a vector store and I can't use the Postprocessor...

Please help

**Comment by logan-markewich** [comment]
You'll either need to manually maintain and  persist the docstore like i was kind of doing in that example, or use the override to enable the docstore `VectorStoreIndex.from_documents(..., store_nodes_override=True)`  -- you just need  to make sure you are saving the docstore from the storage context somewhere

**Comment by AutoScrape123TX** [comment]
So after some reading I have seen that your general `NodePostProcessor` don't handle `VectorStore` natively. We have to build custom node post processor tailored to our vector db.

As seen here : https://github.com/run-llama/llama_index/discussions/13930
@ShawonAshraf pointed me in the right direction and sended me a copy/paste [QdrantVectorPrevNextNodePostprocessor](https://gist.github.com/AutoScrape123TX/174dc0f0f610019ab2cd53ce7fd4163f#file-qdrantvectorprevnextnodepostprocessor-py)

**Comment by ShawonAshraf** [comment]
> You'll either need to manually maintain and persist the docstore like i was kind of doing in that example, or use the override to enable the docstore `VectorStoreIndex.from_documents(..., store_nodes_override=True)` -- you just need to make sure you are saving the docstore from the storage context somewhere

That adds additional maintenance overhead, sadly. The default behaviour of disabling the docstore when a vector store is used should be made optional and anyone using the api should be able to keep both. 

I would rather suggest adding some documentation around the node post processors so that people can adapt them for their use cases. I can open a PR or write a post somewhere and then add it as a reference.

**Comment by AutoScrape123TX** [comment]
Now the next step is to build a child-parent_next-prev redundant node fetching (I'm going to build it I share it here soon)

**Comment by ShawonAshraf** [comment]
> Now the next step is to build a child-parent_next-prev redundant node fetching (I'm going to build it I share it here soon)

That'd be great. I once tried reaching the parent from a node, but it ran into an infinite loop. I was probably doing something wrong there.

**Comment by vkuptcov** [comment]
@AutoScrape123TX @logan-markewich hello, I just had the same issue.
I have a number of multinode documents, it means a bunch of qdrant points share the same `doc_id` and have different node ids.
It looks like `BaseDocumentStore` shouldn't be implemented in this way for storages where we have multiple nodes per document
```
class BaseDocumentStore(ABC):
...
    def get_node(self, node_id: str, raise_error: bool = True) -> Optional[BaseNode]:
        """
        Get node from docstore.

        Args:
            node_id (str): node id
            raise_error (bool): raise error if node_id not found

        """
        doc = self.get_document(node_id, raise_error=raise_error)
```

And it should be fixed in a proper way, at bare minimum it should be allowed to pass a custom node/document load function.

The question is, why did you decide to close the issue? Do you think it's not a bug?
