### ISSUE TITLE
[Bug]: local model responds with [object Object]

### ISSUE THREAD

**Issue by ff6f8d68** [run-llama/llama_index#14875]
### Bug Description

local model responds with [object Object]

### Version

3

### Steps to Reproduce

install llama3
run the programm main.js

### Relevant Logs/Tracbacks

```shell
keys.json not found. Defaulting to environment variables.
Using chat settings: { model: 'local', api: 'ollama' }
Using embedding settings: { api: 'none' }
Unknown embedding:  none . Using word overlap.
Loading examples...
Examples loaded.
Logging in...
(node:5422) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.
SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at Client.<anonymous> (/Users/atom20003113/Downloads/mindcraft-main/node_modules/minecraft-protocol/src/client/versionChecking.js:6:21)
    at Client.emit (node:events:532:35)
    at emitPacket (/Users/atom20003113/Downloads/mindcraft-main/node_modules/minecraft-protocol/src/client.js:83:12)
    at FullPacketParser.<anonymous> (/Users/atom20003113/Downloads/mindcraft-main/node_modules/minecraft-protocol/src/client.js:112:9)
    at FullPacketParser.emit (node:events:520:28)
    at addChunk (/Users/atom20003113/Downloads/mindcraft-main/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:279:12)
    at readableAddChunk (/Users/atom20003113/Downloads/mindcraft-main/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:262:11)
    at Readable.push (/Users/atom20003113/Downloads/mindcraft-main/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:228:10)
    at Transform.push (/Users/atom20003113/Downloads/mindcraft-main/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:132:32)
Agent process exited with code 0 and signal null
```

**Comment by logan-markewich** [comment]
@ff6f8d68 I think you meant to open this in the TS repo? https://github.com/run-llama/LlamaIndexTS

Closing for now
