### ISSUE TITLE
[Bug]: Pandas Query Engine does not give proper response( Especially when exposed via API, works well in local jupyter notebook) 

### ISSUE THREAD

**Issue by Nitheeswaran-E** [run-llama/llama_index#14897]
### Bug Description

if pandas query engine run in a jupyter notebook it gives a proper result, but it does not give a proper result if runned as a single .py file

### Version

llama-index==0.10.50

### Steps to Reproduce

making it as a single .py file

### Relevant Logs/Tracbacks

```shell
(venv) PS C:\Users\Nitheeswaran\Desktop\csv> & c:/Users/Nitheeswaran/Desktop/csv/venv/Scripts/python.exe c:/Users/Nitheeswaran/Desktop/csv/s.py
Traceback (most recent call last):
  File "C:\Users\Nitheeswaran\Desktop\csv\venv\lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Time generated'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nitheeswaran\Desktop\csv\venv\lib\site-packages\llama_index\experimental\query_engine\pandas\output_parser.py", line 54, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
  File "C:\Users\Nitheeswaran\Desktop\csv\venv\lib\site-packages\llama_index\experimental\exec_utils.py", line 159, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
  File "<string>", line 1, in <module>
  File "C:\Users\Nitheeswaran\Desktop\csv\venv\lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Nitheeswaran\Desktop\csv\venv\lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Time generated'
The earliest log entry was generated at [insert timestamp here] and the latest log entry was generated at [insert timestamp here].
```

**Comment by pulkitmehtaworkmetacube** [comment]
I am facing the same issue .. The same code works well in jupyter notebook but produces issues while trying from python script .
