### ISSUE TITLE
[Bug]: LlamaIndex:  Parallelizing Ingestion Pipeline: httpx.ReadTimeout: Error running coroutine

### ISSUE THREAD

**Issue by LuoXinYu930515** [run-llama/llama_index#14901]
### Bug Description

I wrote a chatbot without a front-end interface (the way to ask questions is to write them in prompt.txt, and the program returns each question on a line-by-line basis) , and after loading llama2-7b locally using Ollama, I adjusted the pre-trained model with LlamaIndex (RAG)
In the Transformation phase, I parallelized the Ingest Pipeline execution.
Using serial execution doesn't cause problems, but when using parallel execution it shows a series of exceptions about timeout
Here is my code: 
`
import torch
import chromadb
import time
import os
import cProfile
import pstats
from pstats import SortKey

from llama_index.llms.ollama import Ollama
from llama_index.llms.openai import OpenAI
from llama_index.core import Settings
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.node_parser import SimpleNodeParser
from llama_index.core import ServiceContext
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core import StorageContext
from llama_index.embeddings.ollama import OllamaEmbedding
from llama_index.core.extractors import TitleExtractor
from llama_index.core.postprocessor import LongContextReorder
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.evaluation import (FaithfulnessEvaluator,
                                         QueryResponseEvaluator,
                                         DatasetGenerator,
                                         RelevancyEvaluator)
import asyncio
import nest_asyncio
nest_asyncio.apply()

# load for the uploaded files
def data_loading():
    reader = SimpleDirectoryReader(input_dir="data/", recursive=True)
    documents = reader.load_data(num_workers=4)
    print("finish reading files\n")
    return documents

# RAG
def building_reg_pipeline():
    # LLM, Llama2
    Settings.llm = Ollama(model="llama2",
                          request_timeout=300.0,
                          device_map="cpu")

    # load documents, parallel programming
    # use cProfile to evaluate performance
    profiler = cProfile.Profile()
    profiler.enable()
    documents = data_loading()
    profiler.disable()
    profiler.dump_stats("newstas")

    # chroma database initialize
    db = chromadb.PersistentClient(path="./chroma_db")

    # create collection
    chroma_collection = db.get_or_create_collection("chroma_collection")

    # vector store
    vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
    storage_context = StorageContext.from_defaults(vector_store=vector_store)

    # Transformation
    start_time = time.time()

    # parallelizing ingestion pipeline
    pipeline = IngestionPipeline(
        transformations=[
            SentenceSplitter(chunk_size=512, chunk_overlap=20),
            TitleExtractor(),
            OllamaEmbedding(model_name="llama2-7b")
        ]
    )
    pipeline.disable_cache = True

    # nodes = parallel_ingestion(pipeline, documents)
    nodes = pipeline.run(documents=documents, num_works=16)
    Settings.embed_model = OllamaEmbedding(model_name="llama2-7b")
    index = VectorStoreIndex(nodes=nodes,
                             vector_store=vector_store,
                             storage_context=storage_context)

    end_time = time.time()
    print("finish transformation, time cost: ", end_time - start_time, "s\n")

    # create query engin
    # Reorder the searched Node
    # solve the missing content problem
    start_time = time.time()
    reorder = LongContextReorder()
    query_engine = index.as_query_engine(llm=Settings.llm,
                                         node_postprocessor=[reorder],
                                         similarity_top_k=5,
                                         streaming=True)
    end_time = time.time()
    print("finish query engin creation, time cost: ", end_time - start_time, "s\n")

    return query_engine

# query from the LLM via query engine
def querying(prompt, query_engine):
    start_time = time.time()
    response = query_engine.query(prompt)
    query_time = time.time() - start_time
    print("Total query time : ", query_time, "\n")
    return response

# load for prompts(our questions)
def prompt_loading():
    with open("prompt/prompt.txt", "r") as prompt_file:
        lines = prompt_file.readlines()
        for line in lines:
            yield line.rstrip()

# load for auto generation prompts(questions), not finished yet
def auto_generator_prompt(documents):
    data_generator = DatasetGenerator.from_documents(documents)
    eval_questions = data_generator.generate_questions_from_nodes()
    yield eval_questions

def main():
    # load for query_engine
    query_engine = building_reg_pipeline()
    # performance evaluation of data loading
    p = pstats.Stats("newstas")
    p.strip_dirs().sort_stats(SortKey.CUMULATIVE).print_stats(15)

    # load for prompt(questions)
    prompt_generator = prompt_loading()

    # querying
    for prompt in prompt_generator:
        print("Ask : ", prompt)
        response = querying(prompt, query_engine)
        print("Answer : ")
        print(str(response))

if __name__ == '__main__':
    main()
`

### Version

OS: Windows10 Python: 3.11 llama-index:  Ollama: 0.2.0  CPU: i7-1260P core: 12 logical processor: 16 RAM: 46.2G

### Steps to Reproduce

Use pip install to install the required packages.

### Relevant Logs/Tracbacks

```shell
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 20 0 (offset 0)
Ignoring wrong pointing object 22 0 (offset 0)
Ignoring wrong pointing object 24 0 (offset 0)
Ignoring wrong pointing object 26 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 30 0 (offset 0)
Ignoring wrong pointing object 32 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [03:29<00:00, 209.34s/it]
100%|██████████| 1/1 [03:29<00:00, 209.36s/it]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [03:52<00:00, 232.78s/it]
100%|██████████| 1/1 [03:52<00:00, 232.78s/it]

  0%|          | 0/2 [00:00<?, ?it/s]
 50%|█████     | 1/2 [03:46<03:46, 226.57s/it]Traceback (most recent call last):
  File "E:\Data\python\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "E:\Data\python\lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "E:\Data\python\lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "E:\Data\python\lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "E:\Data\python\lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "E:\Data\python\lib\site-packages\httpcore\_async\http11.py", line 143, in handle_async_request
    raise exc
  File "E:\Data\python\lib\site-packages\httpcore\_async\http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "E:\Data\python\lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "E:\Data\python\lib\site-packages\httpcore\_async\http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
  File "E:\Data\python\lib\site-packages\httpcore\_backends\anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "E:\Data\python\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\Data\python\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Data\python\lib\site-packages\llama_index\core\async_utils.py", line 33, in asyncio_run
    return loop.run_until_complete(coro)
  File "E:\Data\python\lib\site-packages\nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "E:\Data\python\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "E:\Data\python\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "E:\Data\python\lib\site-packages\llama_index\core\extractors\interface.py", line 120, in aprocess_nodes
    cur_metadata_list = await self.aextract(new_nodes)
  File "E:\Data\python\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 255, in async_wrapper
    result = await func(*args, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\core\extractors\metadata_extractors.py", line 104, in aextract
    titles_by_doc_id = await self.extract_titles(nodes_by_doc_id)
  File "E:\Data\python\lib\site-packages\llama_index\core\extractors\metadata_extractors.py", line 131, in extract_titles
    title_candidates = await self.get_title_candidates(nodes)
  File "E:\Data\python\lib\site-packages\llama_index\core\extractors\metadata_extractors.py", line 147, in get_title_candidates
    return await run_jobs(
  File "E:\Data\python\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 255, in async_wrapper
    result = await func(*args, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\core\async_utils.py", line 150, in run_jobs
    results = await tqdm_asyncio.gather(*pool_jobs, desc=desc)
  File "E:\Data\python\lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "E:\Data\python\lib\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "E:\Data\python\lib\asyncio\tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "E:\Data\python\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "E:\Data\python\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "E:\Data\python\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "E:\Data\python\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 255, in async_wrapper
    result = await func(*args, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\core\async_utils.py", line 143, in worker
    return await job
  File "E:\Data\python\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 255, in async_wrapper
    result = await func(*args, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\core\llms\llm.py", line 523, in apredict
    chat_response = await self.achat(messages)
  File "E:\Data\python\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 255, in async_wrapper
    result = await func(*args, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\core\llms\callbacks.py", line 76, in wrapped_async_llm_chat
    f_return_val = await f(_self, messages, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\llms\ollama\base.py", line 226, in achat
    response = await client.post(
  File "E:\Data\python\lib\site-packages\httpx\_client.py", line 1892, in post
    return await self.request(
  File "E:\Data\python\lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "E:\Data\python\lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "E:\Data\python\lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "E:\Data\python\lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "E:\Data\python\lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "E:\Data\python\lib\site-packages\httpx\_transports\default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "E:\Data\python\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\Data\python\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Code\Internship\Retry_LlamaIndex\chatbot.py", line 174, in <module>
    if __name__ == '__main__':
  File "E:\Code\Internship\Retry_LlamaIndex\chatbot.py", line 157, in main
    # load for query_engine
  File "E:\Code\Internship\Retry_LlamaIndex\chatbot.py", line 101, in building_reg_pipeline
    # nodes = parallel_ingestion(pipeline, documents)
  File "E:\Data\python\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\core\ingestion\pipeline.py", line 542, in run
    nodes = run_transformations(
  File "E:\Data\python\lib\site-packages\llama_index\core\ingestion\pipeline.py", line 100, in run_transformations
    nodes = transform(nodes, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\core\extractors\interface.py", line 159, in __call__
    return self.process_nodes(nodes, **kwargs)
  File "E:\Data\python\lib\site-packages\llama_index\core\extractors\interface.py", line 142, in process_nodes
    return asyncio_run(
  File "E:\Data\python\lib\site-packages\llama_index\core\async_utils.py", line 47, in asyncio_run
    raise type(e)(f"Error running coroutine: {e!s}") from e
httpx.ReadTimeout: Error running coroutine: 

 50%|█████     | 1/2 [05:01<05:01, 301.51s/it]
```

**Comment by logan-markewich** [comment]
Ollama timed out. You can increase the timeout with `llm = Ollama(..., request_timeout=3600.0)`
