### ISSUE TITLE
[Question]: 使用·PropertyGraphIndex.from_documents()方法报错

### ISSUE THREAD

**Issue by GOOD-N-LCM** [run-llama/llama_index#15053]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

我的代码为： 
if not os.path.exists(f"./data2/index_storage"):
    index = PropertyGraphIndex.from_documents(
        documents,
        embed_model=embed_model,
        kg_extractors=[kg_extractor],
        property_graph_store=graph_store,
        show_progress=True,
    )
    index.storage_context.persist("./data2/index_storage")
else:
    print('Loading index...\n')
    storage_context = StorageContext.from_defaults(persist_dir="./data2/index_storage", property_graph_store=graph_store)
    index = load_index_from_storage(storage_context=storage_context)

但是会在NebulaGraphStore报错：
Traceback (most recent call last):
  File "D:\code_llm\LLama-Index\lcm4.py", line 99, in <module>
    index = PropertyGraphIndex.from_documents(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\base.py", line 145, in from_documents
    return cls(
           ^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\property_graph\base.py", line 134, in __init__
    super().__init__(
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\base.py", line 94, in __init__
    index_struct = self.build_index_from_nodes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\base.py", line 216, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **build_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\property_graph\base.py", line 328, in _build_index_from_nodes
    nodes = self._insert_nodes(nodes or [])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\property_graph\base.py", line 234, in _insert_nodes
    existing_kg_nodes = self.property_graph_store.get(ids=list(kg_node_ids))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NebulaGraphStore.get() got an unexpected keyword argument 'ids'

请问大佬们是如何解决的

**Comment by GOOD-N-LCM** [comment]
> embed_model
抱歉，按照您的方式修改代码以后是那个错误。
我看了一下 PropertyGraphIndex这个类，他是继承了父类BaseIndex里面的from_documents方法。BaseIndex.from_documents貌似需要传入service_context和storage_context两个参数。我是否缺少的是这两个参数么？以下是我的全部代码：
import os
from llama_index.embeddings.ollama import OllamaEmbedding
from llama_index.llms.ollama import Ollama
from llama_index.core import SimpleDirectoryReader
from llama_index.graph_stores.nebula import NebulaGraphStore
from llama_index.core import PropertyGraphIndex
from llama_index.core.indices.property_graph import SimpleLLMPathExtractor
from llama_index.core import StorageContext
from llama_index.core import load_index_from_storage
from llama_index.core.llms.mock import MockLLM
from llama_index.core import MockEmbedding

# 实例化llm 与 embedding_model
llm = Ollama(model="qwen2:1.5b", request_timeout=360.0)
embed_model = OllamaEmbedding(model_name="znbang/bge:large-zh-v1.5-f32")


# 加载文档数据
documents = SimpleDirectoryReader(input_files=['./data2/text.txt']).load_data()
print('>>>  documents : ', documents)

# nebula存储
os.environ["NEBULA_USER"] = "root"
os.environ["NEBULA_PASSWORD"] = "nebula"
os.environ["NEBULA_ADDRESS"] = "192.168.3.114:9669"
space_name = "lcm_test"
edge_types, rel_prop_names = ["relationship"], ["relationship"]
tags = ["entity"]

# 初始化Nebula图存储
graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags
)
graph_store.supports_vector_queries = False
print('>>>  graph_store : ', graph_store)

# 知识抽取的提示词
prompt_new = '''
prompt.....
'''


# 抽取结果的解析
def parse_fn(response_str: str):
    '''
     List[Tuple[str, str, str]]
    :param response_str:
    :return:
    '''
    lines = response_str.split("\n")
    triples = [line.split(",") for line in lines]
    return triples


# 定义知识抽取器
kg_extractor = SimpleLLMPathExtractor(
    llm=llm,
    extract_prompt=prompt_new,
    max_paths_per_chunk=20,
    parse_fn=parse_fn,
)

# 抽取创建图知识库索引（本地化做持久，避免反复抽取）
if not os.path.exists(f"./data2/index_storage"):
    index = PropertyGraphIndex.from_documents(
        documents,
        llm=llm,
        # embed_model=MockEmbedding(embed_dim=256),
        embed_model=embed_model,
        kg_extractors=[kg_extractor],
        property_graph_store=graph_store,
        show_progress=True,
    )
    index.storage_context.persist("./data2/index_storage")
else:
    print('Loading index...\n')
    storage_context = StorageContext.from_defaults(persist_dir="./data2/index_storage", property_graph_store=graph_store)
    index = load_index_from_storage(storage_context=storage_context)

**Comment by GOOD-N-LCM** [comment]
> ```python
>     index.storage_context.persist("./data2/index_storage")
> else:
>     print('Loading index...\n')
>     storage_context = StorageContext.from_defaults(persist_dir="./data2/index_storage", property_graph_store=graph_store)
>     index = load_index_from_storage(storage_context=storage_context)
> ```

呃呃呃..请问您发的代码，与我的代码有什么区别么？

**Comment by GOOD-N-LCM** [comment]
> 代码中的主要问题是该`NebulaGraphStore.get()`方法不接受`ids`关键字参数。通过确保您使用的是最新版本的类`NebulaGraphStore`（其中包含正确的方法签名）可以解决此问题`get`。
> 
> `NebulaGraphStore`以下是针对您的初始化和使用进行的更正的代码片段：
> 
> ```python
> import os
> from llama_index.embeddings.ollama import OllamaEmbedding
> from llama_index.llms.ollama import Ollama
> from llama_index.core import SimpleDirectoryReader
> from llama_index.graph_stores.nebula import NebulaGraphStore
> from llama_index.core import PropertyGraphIndex
> from llama_index.core.indices.property_graph import SimpleLLMPathExtractor
> from llama_index.core import StorageContext
> from llama_index.core import load_index_from_storage
> 
> llm = Ollama(model="qwen2:1.5b", request_timeout=360.0)
> embed_model = OllamaEmbedding(model_name="znbang/bge:large-zh-v1.5-f32")
> 
> documents = SimpleDirectoryReader(input_files=['./data2/text.txt']).load_data()
> print('>>>  documents : ', documents)
> 
> os.environ["NEBULA_USER"] = "root"
> os.environ["NEBULA_PASSWORD"] = "nebula"
> os.environ["NEBULA_ADDRESS"] = "192.168.3.111:9669"
> space_name = "lcm_test"
> edge_types, rel_prop_names = ["relationship"], ["relationship"]
> tags = ["entity"]
> 
> graph_store = NebulaGraphStore(
>     space_name=space_name,
>     edge_types=edge_types,
>     rel_prop_names=rel_prop_names,
>     tags=tags
> )
> graph_store.supports_vector_queries = False
> print('>>>  graph_store : ', graph_store)
> 
> prompt_new = '''xxxx'''
> 
> def parse_fn(response_str: str):
>     '''
>      List[Tuple[str, str, str]]
>     :param response_str:
>     :return:
>     '''
>     lines = response_str.split("\n")
>     triples = [line.split(",") for line in lines]
>     return triples
> 
> kg_extractor = SimpleLLMPathExtractor(
>     llm=llm,
>     extract_prompt=prompt_new,
>     max_paths_per_chunk=20,
>     parse_fn=parse_fn,
> )
> 
> if not os.path.exists(f"./data2/index_storage"):
>     index = PropertyGraphIndex.from_documents(
>         documents,
>         llm=llm,
>         embed_model=embed_model,
>         kg_extractors=[kg_extractor],
>         property_graph_store=graph_store,
>         show_progress=True,
>     )
>     index.storage_context.persist("./data2/index_storage")
> else:
>     print('Loading index...\n')
>     storage_context = StorageContext.from_defaults(persist_dir="./data2/index_storage", property_graph_store=graph_store)
>     index = load_index_from_storage(storage_context=storage_context)
> ```
> 
> 确保你拥有该类的最新版本，其中包含正确处理参数`NebulaGraphStore`的正确方法签名[[1] ](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/nebula_property_graph.py)[[2]](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/nebula_graph_store.py)。`get``ids`[](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/nebula_property_graph.py)[](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/nebula_graph_store.py)
> 
> _要继续与[Dosu](https://dosu.dev)交谈，请提及@dosu。_



是的，我确认了 已经使用最新的NebulaGraphStore  ，也将您的代码重新修改到我的代码里去了。但还是会报错TypeError: NebulaGraphStore.get() got an unexpected keyword argument 'ids'

**Comment by logan-markewich** [comment]
@GOOD-N-LCM I noticed you are using `NebulaGraphStore`, but you probably meant to use `NebulaPropertyGraphStore`
