### ISSUE TITLE
[Question]: Accessing vector store chunk text

### ISSUE THREAD

**Issue by aclifton314** [run-llama/llama_index#15096]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

llama-index: 0.10.36
python: 3.11.9
Ubunutu 22.04

I have written the following code:
```python
import weaviate
from llama_index.core import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    Settings,
    StorageContext,
)
from llama_index.vector_stores.weaviate import WeaviateVectorStore
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.openai_like import OpenAILike
from llama_index.core.query_engine import FLAREInstructQueryEngine


class MyFlare:
    def __init__(self):
        Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
        docs = SimpleDirectoryReader("/path/to/my/data").load_data()
        client = weaviate.Client("http://localhost:8080")
        vector_store = WeaviateVectorStore(
            weaviate_client=client, index_name="My_index"
        )

        storage_context = StorageContext.from_defaults(vector_store=vector_store)
        self.index = VectorStoreIndex.from_documents(
            docs,
            storage_context=storage_context,
            embed_model=Settings.embed_model,
        )

        query_engine = self.index.as_query_engine(llm=Settings.llm)

        flare_query_engine = FLAREInstructQueryEngine(
            query_engine=query_engine, max_iterations=1, verbose=True
        )


flare = MyFlare()
print(flare.index.docstore.to_dict())
print("*" * 76)
print(flare.index.docstore.get_all_ref_doc_info())
print("*" * 76)
print(flare.index.docstore.docs)

```

I am wanting to access the text of the individual chunks in the vector store but:
```python
print(flare.index.docstore.get_all_ref_doc_info())
print(flare.index.docstore.docs)
```

are empty. However, `print(flare.index.docstore.to_dict())` produces something like:
```python
f5d31664-beea-43d0-8f4f-5593d47f9890 {'doc_hash': '26ab2ce6768825d46f0d84aa3dddbd12aa486039d823688a5e41ac4068d9fedb'}
```

Any ideas on how to access these chunks? Thanks in advance for your help!

**Comment by aclifton314** [comment]
@dosu, thanks for the response. Implementing the suggestions, I get the following error: 
```python
AttributeError: 'WeaviateVectorStore' object has no attribute 'get_all_texts'
```

**Comment by aclifton314** [comment]
@dosu thank you for that response. Your suggestions allow me to retrieve the top N chunks. How would I go about retrieving every chunk stored in the vector store?

**Comment by aclifton314** [comment]
@dosu, thank you for that response. The suggestion produces the following error:
```python
Traceback (most recent call last):
  File "/home/user/scratch.py", line 71, in <module>
    result = flare.index.vector_store.query(query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/thdt04/lib/python3.11/site-packages/llama_index/vector_stores/weaviate/base.py", line 362, in query
    parsed_result = parse_get_response(query_result)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/thdt04/lib/python3.11/site-packages/llama_index/vector_stores/weaviate/utils.py", line 65, in parse_get_response
    raise ValueError("Invalid query, got errors: {}".format(response["errors"]))
ValueError: Invalid query, got errors: [{'locations': [{'column': 6, 'line': 1}], 'message': 'explorer: list class: search: invalid pagination params: query maximum results exceeded', 'path': ['Get', 'My_index']}]
```

It seems to come from the `query_embedding=None` argument in `VectorStoreQuery`, but I am not totally sure.

**Comment by aclifton314** [comment]
@dosu Thank you for the response. This answers all my questions.

**Comment by aclifton314** [comment]
@dosu apologies for reopening this issue, but what is  `class_name` and `class_prefix` in this suggestion?

**Comment by aclifton314** [comment]
@dosu, could you provide a concrete example of the code you outlines above? I'm not sure I understand.

**Comment by aclifton314** [comment]
@dosu thank you!
