### ISSUE TITLE
[Question]: Having trouble with async SubQuestionQueryEngine

### ISSUE THREAD

**Issue by nazim-ashman-oc** [run-llama/llama_index#15103]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have been trying to get a SubQuestionQueryEngine working in async mode for a while in combination with FastAPI.

I have already applied:
`nest_asyncio.apply()`

and am using the "asyncio" loop:
`uvicorn.run(app, host="0.0.0.0", port=8000, loop="asyncio")`

I am setting up my sub_qestion_query_engine like this:
```
    recursive_retriever = RecursiveRetriever(
                                            "vector",
                                            retriever_dict=retriever_dict,
                                            verbose=True)
    response_synthesizer = get_response_synthesizer(response_mode="compact", 
                                                    streaming=True, 
                                                    service_context=ctx_base, 
                                                    use_async=True
                                                    )
    
    vector_query_engine = RetrieverQueryEngine.from_args(recursive_retriever, 
                                                         response_synthesizer=response_synthesizer, 
                                                         streaming=True,
                                                         use_async=True
                                                         )

    query_engine_tools = [
        QueryEngineTool(
            query_engine=vector_query_engine,
            metadata=ToolMetadata(
                name="vector_store_query_engine",
                description="Vector Store Query engine",
            ),
        ),
    ]

    query_engine = SubQuestionQueryEngine.from_defaults(
        query_engine_tools=query_engine_tools,
        use_async=True,
        service_context=ctx_base,
        response_synthesizer=response_synthesizer
    )
```

It is then put as a tool into a RouterQueryEngine. The RouterQueryEngine is then called from a FastAPI endpoint which in turn calls this function:

```
async def generate_chat_reply(request_query: str):
    engine_container = get_engine_container_singleton()
    router_query_engine = engine_container.router_query_engine
    response = await router_query_engine.aquery(request_query)
    response_gen = response.response_gen
    async for chunk in response_gen:
        yield chunk
```

Now I am getting this error:

```
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 234, in __step
    |     result = coro.throw(exc)
    |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/app/app/endpoints/chat.py", line 80, in generate_chat_reply
    |     response = await router_query_engine.aquery(request_query)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 255, in async_wrapper
    |     result = await func(*args, **kwargs)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/base/base_query_engine.py", line 64, in aquery
    |     query_result = await self._aquery(str_or_query_bundle)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 255, in async_wrapper
    |     result = await func(*args, **kwargs)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/query_engine/router_query_engine.py", line 246, in _aquery
    |     final_response = await selected_query_engine.aquery(query_bundle)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 255, in async_wrapper
    |     result = await func(*args, **kwargs)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/base/base_query_engine.py", line 64, in aquery
    |     query_result = await self._aquery(str_or_query_bundle)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 255, in async_wrapper
    |     result = await func(*args, **kwargs)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/query_engine/sub_question_query_engine.py", line 200, in _aquery
    |     qa_pairs_all = await asyncio.gather(*tasks)
    |   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    |     future.result()
    |   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 232, in __step
    |     result = coro.send(None)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/query_engine/sub_question_query_engine.py", line 240, in _aquery_subq
    |     response_text = str(response)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/base/response/schema.py", line 183, in __str__
    |     return asyncio_run(self._async_str)
    |   File "/usr/local/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 47, in asyncio_run
    |     raise type(e)(f"Error running coroutine: {e!s}") from e
    | TypeError: Error running coroutine: An asyncio.Future, a coroutine or an awaitable is required
```

I am guessing this error hints at something wrong with the response sent back from the RetrieverQueryEngine layers, but I am not too sure, I have set use_async=True where I can and streaming=True. Not sure where I am going wrong.

**Comment by logan-markewich** [comment]
@nazim-ashman-oc you arent using an async generator 

It should be `async for chunk in response.async_response_gen():`

**Comment by nazim-ashman-oc** [comment]
> response.async_response_gen():

Ah thanks. Made the changes, but still getting the same error :(

**Comment by nazim-ashman-oc** [comment]
Any other code snippets I could add to help out?

**Comment by arunnuve** [comment]
Is the issue is in all query that you are giving or particular one query ,for me this issue also raised but for only particular queries except that other works well than that it works well.

**Comment by nazim-ashman-oc** [comment]
> Is the issue is in all query that you are giving or particular one query ,for me this issue also raised but for only particular queries except that other works well than that it works well.

Well, from the RouterQueryEngine, if an engine other than SubQuestionQueryEngine is chosen, it works. It breaks down when SubQuestionQueryEngine is chosen.

**Comment by nazim-ashman-oc** [comment]
Ok, problem here was that I was using the same response synthesizer (set to streaming=True) for the RetrieverQueryEngine and the SubQuestionQueryEngine. Making a separate response synthesizer for RetrieverQueryEngine (with streaming=False) fixes this problem.

Practically this makes sense for me, since there is no point for RetrieverQueryEngine to be streaming since it is being fed into the SubQuestionQueryEngine. However, it still feels like unintended behaviour. The str() does not seem to work well with an AsyncStreamingResponse.

**Comment by nazim-ashman-oc** [comment]
@logan-markewich 

Ok dosu pretty much pointed us in the right direction here, it looks like in 

```
@dataclass
class AsyncStreamingResponse:
    """AsyncStreamingResponse object.

    Returned if streaming=True while using async.

    Attributes:
        _async_response_gen: The response async generator.

    """

    response_gen: TokenAsyncGen
    source_nodes: List[NodeWithScore] = field(default_factory=list)
    metadata: Optional[Dict[str, Any]] = None
    response_txt: Optional[str] = None

    def __post_init__(self) -> None:
        self._lock = asyncio.Lock()

    def __str__(self) -> str:
        """Convert to string representation."""
        return asyncio_run(self._async_str)

    async def _async_str(self) -> str:
        """Convert to string representation."""
        async for _ in self._yield_response():
            ...
        return self.response_txt or "None"

    async def _yield_response(self) -> TokenAsyncGen:
        """Yield the string response."""
        async with self._lock:
            if self.response_txt is None and self.response_gen is not None:
                self.response_txt = ""
                async for text in self.response_gen:
                    self.response_txt += text
                    yield text
            else:
                yield self.response_txt

    async def async_response_gen(self) -> TokenAsyncGen:
        """Yield the string response."""
        async for text in self._yield_response():
            yield text

    async def get_response(self) -> Response:
        """Get a standard response object."""
        async for _ in self._yield_response():
            ...
        return Response(self.response_txt, self.source_nodes, self.metadata)

    async def print_response_stream(self) -> None:
        """Print the response stream."""
        streaming = True
        async for text in self._yield_response():
            print(text, end="", flush=True)
        # do an empty print to print on the next line again next time
        print()

    def get_formatted_sources(self, length: int = 100, trim_text: int = True) -> str:
        """Get formatted sources text."""
        texts = []
        for source_node in self.source_nodes:
            fmt_text_chunk = source_node.node.get_content()
            if trim_text:
                fmt_text_chunk = truncate_text(fmt_text_chunk, length)
            node_id = source_node.node.node_id or "None"
            source_text = f"> Source (Node id: {node_id}): {fmt_text_chunk}"
            texts.append(source_text)
        return "\n\n".join(texts)

```

the str dunder method should be this instead (it was missing the brackets):

```
    def __str__(self) -> str:
        """Convert to string representation."""
        return asyncio_run(self._async_str())

```

I make a PR for this?

**Comment by bmax** [comment]
thanks for your contribution!
