### ISSUE TITLE
[Bug]: Various Issues and Concerns Associated with Sub Question Query Engine

### ISSUE THREAD

**Issue by HarikrishnanK9** [run-llama/llama_index#15136]
### Bug Description

I have tried different open source llms,as well as gpt 3.5 turbo;Except for gpt for all other llms i had various  kinds of issues like coroutine,key error,etc (For majority of my questions i got appropriate response)   Currently iam using microsoft phi3 mini 4k instruct as per your documentation page with the combination of subquestion query engine.I have tried distinctive names for documents to ensure query engine tools are not identical to avoid possible Hallucinations.But i felt coroutine error and key error for some question i have asked with sub question query engine,the error is  as follows:   

Traceback (most recent call last):
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 33, in asyncio_run
    return loop.run_until_complete(coro)
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 79, in _gather
    return await asyncio.gather(*tasks_to_execute)
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/site-packages/llama_index/core/query_engine/sub_question_query_engine.py", line 232, in _aquery_subq
    query_engine = self._query_engines[sub_q.tool_name]
KeyError: 'LMAR'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/paperspace/clinsight/backend/dataingestion/test/h_dev/demo3_working.py", line 256, in <module>
    result = qa_test(input_dict)
  File "/home/paperspace/clinsight/backend/dataingestion/test/h_dev/demo3_working.py", line 241, in qa_test
    qa_response = sub_query_engine.query(f"{query}")
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/site-packages/llama_index/core/base/base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/site-packages/llama_index/core/query_engine/sub_question_query_engine.py", line 156, in _query
    qa_pairs_all = run_async_tasks(tasks)
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 81, in run_async_tasks
    outputs: List[Any] = asyncio_run(_gather())
  File "/home/paperspace/anaconda3/envs/finetune_env/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 47, in asyncio_run
    raise type(e)(f"Error running coroutine: {e!s}") from e
KeyError: "Error running coroutine: 'LMAR'"

 Another notable thing found that if OPENAI API KEY is in our .env fille and at the same time if we are using another open source llms like llama2 70b,zypher,etc the SubQuestionQueryEngine will utilize the openai key without our permission.Its a serious matter of concern as we are properly specified in variables which llm should be taken.

If an organization deals with confidential documents,it may cause data leakage and possible legal actions against them.

### Version

llama-index==0.10.57

### Steps to Reproduce

try Sub Question Query Engine[  https://docs.llamaindex.ai/en/stable/examples/query_engine/sub_question_query_engine/ ] with open source llms specified in [ https://docs.llamaindex.ai/en/stable/module_guides/models/llms/ ] remember input datas are in .pkl form (pdfs files are parsed into .pkl files );I have tried 2 dozen of different combinations with SubQuestionQueryEngine (phi3mini4k,zyphr,llama,gpt3.5,etc).unfortunately iam not able to share the code due to confidentiality.Yet why iam reporting this because the current bug can sue several startups and sometimes llamaindex due to dataleakage.

**Comment by HarikrishnanK9** [comment]
when somebody uses pip install llama-index-core it will automatically installs  openai related dpendencies automatically.for example i have created a new environment named index_env and tried pip install llama-index-core,not only installed llama-index-core==0.10.60 but also openai==1.38.0 ;So when a user uses open source llms by keeping openai key in his .env had no direct idea about this because there is another installation recommended in your github page " pip install llama-index-llms-openai " to install openai related dependencies seperately!!. if i use pip install llama-index-core and separately deletes openai,after that when i installs pip install llama-index-llms-openai then also i get both the openai==1.38.0 and llama-index-llms-openai==0.1.27 ;so i request you to separate openai installation from pip install llama-index-core otherwise user can directly istall openai separately.Remember this is just a suggestion to overcome to avoid unintentional use or installation of openai that sometimes user may not aware it exists or not

I will inspect the responses you have shared associated with SubQuestionQueryEngine later ,will compare with my existing code anyway  and will share if any conflicts arise.

But the issues associated with openai in this message is always a concern not only for SubQuestionQuery but also for any other

**Comment by logan-markewich** [comment]
The error you are getting here is the LLM hallucinating the name of a query engine. This is pretty common for most open-source llms, as they aren't totally reliable. Maybe try llama3.1 (my recommendation is using Ollama), as that seems to be the best right now.

Also fyi, `llama-index` is a starter package around several namespaces sub-packages. You can always install llama-index-core and whatever else you need.

There is a `Settings` object that controls global defaults. If you don't want to use openai, set these to something else.
