### ISSUE TITLE
How to use 'Azure Cosmos DB for MongoDB account (RU)' instance as DocStore to store document nodes

### ISSUE THREAD

**Issue by prabhuperumalofficial** [run-llama/llama_index#15198]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

We are running MongoDB in Azure as 'Azure Cosmos DB for MongoDB account (RU)' service. When we try to use that instance as MongoDocumentStore it fails while trying to add document nodes with the following error

`ERROR  -  Collection name contains invalid character., full error: {'ok': 0.0, 'errmsg': 'Collection name contains invalid character.', 'code': 73, 'codeName': 'InvalidNamespace'}`

### Code:
`documents = SimpleDirectoryReader(payload_location).load_data()
parser = SentenceSplitter()
nodes = parser.get_nodes_from_documents(documents)        
docstore=MongoDocumentStore.from_uri(uri='mongodb://xxxxxxxxxxxxx.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=xxxxxx', db_name='Embeddings')
indexstore = MongoIndexStore.from_uri(uri='uri='mongodb://xxxxxxxxxxxxx.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=xxxxxx', db_name='Embeddings')

docstore.add_documents(nodes)
storage_context = StorageContext.from_defaults(docstore=docstore, index_store=indexstore)
vector_index = VectorStoreIndex(nodes, storage_context=storage_context)
vector_index.storage_context.persist()
vector_id = vector_index.index_id` 

### Stacktrace:
It fails with the following error while executing this line 'nodes = parser.get_nodes_from_documents(documents)'  

`2024-08-07 22:23:58,570  - ERROR  -  Collection name contains invalid character., full error: {'ok': 0.0, 'errmsg': 'Collection name contains invalid character.', 'code': 73, 'codeName': 'InvalidNamespace'}
Traceback (most recent call last):
  File "D:\llamaindex\app\utils\helper.py", line 225, in common_training
    docstore.add_documents(nodes)
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\core\storage\docstore\keyval_docstore.py", line 223, in add_documents
    node_kv_pairs, metadata_kv_pairs, ref_doc_kv_pairs = self._prepare_kv_pairs(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\core\storage\docstore\keyval_docstore.py", line 184, in _prepare_kv_pairs
    ref_doc_info = self.get_ref_doc_info(node.ref_doc_id) or RefDocInfo()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\core\storage\docstore\keyval_docstore.py", line 395, in get_ref_doc_info
    ref_doc_info = self._kvstore.get(
                   ^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\storage\kvstore\mongodb\base.py", line 206, in get
    result = self._db[collection].find_one({"_id": key})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\collection.py", line 1506, in find_one
    for result in cursor.limit(-1):
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\cursor.py", line 1264, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\cursor.py", line 1181, in _refresh
    self.__send_message(q)
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\cursor.py", line 1060, in __send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\mongo_client.py", line 1394, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\mongo_client.py", line 1492, in _retryable_read
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\mongo_client.py", line 1462, in _retry_internal
    ).run()
      ^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
           ^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\mongo_client.py", line 2445, in _read
    return self._func(self._session, self._server, conn, read_pref)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\mongo_client.py", line 1390, in _cmd
    return server.run_operation(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\helpers.py", line 322, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\server.py", line 167, in run_operation
    _check_command_response(first, conn.max_wire_version)
  File "D:\llamaindex\venv\Lib\site-packages\pymongo\helpers.py", line 230, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Collection name contains invalid character., full error: {'ok': 0.0, 'errmsg': 'Collection name contains invalid character.', 'code': 73, 'codeName': 'InvalidNamespace'}
`

**Comment by prabhuperumalofficial** [comment]
@dosu

```
valid_db_name = "Embeddings"
valid_docstore_namespace = "docstore"
valid_indexstore_namespace = "indexstore"

docstore = MongoDocumentStore.from_uri(
            uri='xxxx',
            db_name=valid_db_name,
            namespace=valid_docstore_namespace)
indexstore = MongoIndexStore.from_uri(
            uri='xxxx',
            db_name=valid_db_name,
            namespace=valid_indexstore_namespace)
docstore.add_documents(nodes)
```

Even after updating the code as suggested it fails with the same error
`2024-08-07 23:18:32,263  - ERROR  -  Collection name contains invalid character., full error: {'ok': 0.0, 'errmsg': 'Collection name contains invalid character.', 'code': 73, 'codeName': 'InvalidNamespace'}
Traceback (most recent call last):
  File "D:\llamaindex\app\utils\helper.py", line 236, in common_training
    docstore.add_documents(nodes)
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\core\storage\docstore\keyval_docstore.py", line 223, in add_documents
    node_kv_pairs, metadata_kv_pairs, ref_doc_kv_pairs = self._prepare_kv_pairs(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\core\storage\docstore\keyval_docstore.py", line 184, in _prepare_kv_pairs
    ref_doc_info = self.get_ref_doc_info(node.ref_doc_id) or RefDocInfo()`

**Comment by prabhuperumalofficial** [comment]
@dosu

Thanks for the suggestions we were able to solve the issue as follows:

```   
docstore = MongoDocumentStore.from_uri(
             uri=constants.MONGO_CLIENT_URI,
             db_name=constants.EMBEDDING_DB_NAME,
             namespace=constants.EMBEDDING_DOCSTORE_NAMESPACE,
             node_collection_suffix=f'_{service_name}',
             ref_doc_collection_suffix=f'_{service_name}',
             metadata_collection_suffix=f'_{service_name}')
indexstore = MongoIndexStore.from_uri(
             uri=constants.MONGO_CLIENT_URI,
             db_name=constants.EMBEDDING_DB_NAME,
             namespace=constants.EMBEDDING_INDEXSTORE_NAMESPACE,
             collection_suffix=f'_{service_name}')
```
