### ISSUE TITLE
[Question]: How to use Azure Table Storage for indexing large files

### ISSUE THREAD

**Issue by prabhuperumalofficial** [run-llama/llama_index#15258]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

We are trying to use Azure Table Storage to store indexes as below

```
        storage_context = StorageContext.from_defaults(
            docstore=AzureDocumentStore.from_connection_string(
                constants.STORAGE_ACCOUNT_CONNECTION_STRING,
                service_mode=ServiceMode.STORAGE,
                partition_key=service_name
            ),
            index_store=AzureIndexStore.from_connection_string(
                constants.STORAGE_ACCOUNT_CONNECTION_STRING,
                service_mode=ServiceMode.STORAGE,
                partition_key=service_name
            )
        )
        storage_context.docstore.add_documents(nodes)

        index = VectorStoreIndex(nodes, storage_context=storage_context, show_progress=True)
        index.storage_context.persist()
```

But it throws the following error when trying to index a larger file

`2024-08-09 12:24:55,996  - ERROR  -  The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.
RequestId:5897b37c-a002-000e-5257-ea4e3b000000
Time:2024-08-09T12:24:55.9923447Z
ErrorCode:PropertyValueTooLarge
Content: {"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:5897b37c-a002-000e-5257-ea4e3b000000\nTime:2024-08-09T12:24:55.9923447Z"}}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/azure/data/tables/_table_client.py", line 658, in upsert_entity
    self._client.table.update_entity(
  File "/usr/local/lib/python3.12/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/data/tables/_generated/operations/_operations.py", line 1280, in update_entity
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:5897b37c-a002-000e-5257-ea4e3b000000\nTime:2024-08-09T12:24:55.9923447Z"}}}
`

**Comment by prabhuperumalofficial** [comment]
@dosu

As in the original message we are using `AzureDocumentStore from llama_index.storage.docstore.azure package`

```
storage_context = StorageContext.from_defaults(
            docstore=AzureDocumentStore.from_connection_string(
                constants.STORAGE_ACCOUNT_CONNECTION_STRING,
                service_mode=ServiceMode.STORAGE,
                partition_key=service_name
            ),
            index_store=AzureIndexStore.from_connection_string(
                constants.STORAGE_ACCOUNT_CONNECTION_STRING,
                service_mode=ServiceMode.STORAGE,
                partition_key=service_name
            )
        )
        
        storage_context.docstore.add_documents(nodes)

        index = VectorStoreIndex(nodes, storage_context=storage_context, show_progress=True)
        index.storage_context.persist()
````

Getting error in `index = VectorStoreIndex(nodes, storage_context=storage_context, show_progress=True)` in this line

**Comment by prabhuperumalofficial** [comment]
@dosu 

How to solve this issue with AzureDocumentStore? is there any additional properties to be passed to handle it automatically?

**Comment by prabhuperumalofficial** [comment]
@dosu 

Even the same results after using the above code

Can someone else help me here?

Code:
```
        storage_context = StorageContext.from_defaults(
            docstore=AzureDocumentStore.from_connection_string(
                constants.STORAGE_ACCOUNT_CONNECTION_STRING,
                service_mode=ServiceMode.STORAGE,
                namespace=service_name
            ),
            index_store=AzureIndexStore.from_connection_string(
                constants.STORAGE_ACCOUNT_CONNECTION_STRING,
                service_mode=ServiceMode.STORAGE,
                partition_key=service_name
            )
        )
        
        storage_context.docstore.add_documents(nodes)

        index = VectorStoreIndex(nodes, storage_context=storage_context, show_progress=True)
        index.storage_context.persist()
```

Stacktrace:
```
2024-08-09 23:43:00,806  - ERROR  -  The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.
RequestId:d97da7d5-3002-0041-1f87-ea3f6f000000
Time:2024-08-09T18:13:00.7082413Z
ErrorCode:PropertyValueTooLarge
Content: {"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:d97da7d5-3002-0041-1f87-ea3f6f000000\nTime:2024-08-09T18:13:00.7082413Z"}}}
Traceback (most recent call last):
  File "D:\llamaindex\venv\Lib\site-packages\azure\data\tables\_table_client.py", line 658, in upsert_entity
    self._client.table.update_entity(
  File "D:\llamaindex\venv\Lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\azure\data\tables\_generated\operations\_operations.py", line 1280, in update_entity
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:d97da7d5-3002-0041-1f87-ea3f6f000000\nTime:2024-08-09T18:13:00.7082413Z"}}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\llamaindex\app\utils\helper.py", line 305, in persist_index_into_docstore
    index = VectorStoreIndex(nodes, storage_context=storage_context, show_progress=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\core\indices\vector_store\base.py", line 78, in __init__
    super().__init__(
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\core\indices\base.py", line 98, in __init__
    self._storage_context.index_store.add_index_struct(self._index_struct)
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\core\storage\index_store\keyval_index_store.py", line 46, in add_index_struct
    self._kvstore.put(key, data, collection=self._collection)
  File "D:\llamaindex\venv\Lib\site-packages\llama_index\storage\kvstore\azure\base.py", line 189, in put
    table_client.upsert_entity(
  File "D:\llamaindex\venv\Lib\site-packages\azure\core\tracing\decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\llamaindex\venv\Lib\site-packages\azure\data\tables\_table_client.py", line 672, in upsert_entity
    _process_table_error(error, table_name=self.table_name)
  File "D:\llamaindex\venv\Lib\site-packages\azure\data\tables\_error.py", line 210, in _process_table_error
    raise decoded_error from storage_error
azure.core.exceptions.HttpResponseError: The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.
RequestId:d97da7d5-3002-0041-1f87-ea3f6f000000
Time:2024-08-09T18:13:00.7082413Z
ErrorCode:PropertyValueTooLarge
Content: {"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:d97da7d5-3002-0041-1f87-ea3f6f000000\nTime:2024-08-09T18:13:00.7082413Z"}}}
2024-08-09 23:43:00,840  - INFO  -  index persisted in azure storage======> None
2024-08-09 23:43:00,849  - INFO  -  URL Training end at: 18:13:00
2024-08-09 23:43:03,876  - INFO  -  URL crawl Training Completed ============================>653228ec0dc3235cd8399141_EleviantCTG-GenAIBot
```

**Comment by prabhuperumalofficial** [comment]
@logan-markewich any updates on this issue?

**Comment by prabhuperumalofficial** [comment]
@dosu any help on this ticket would be appreciated

**Comment by logan-markewich** [comment]
There's been a lot of updates to the table storage integration. I think this works now?

Feel free to open a new issue if not
