### ISSUE TITLE
[Bug]: googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0

### ISSUE THREAD

**Issue by peejay2** [run-llama/llama_index#15308]
### Bug Description

INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
file_cache is only supported with oauth2client<4.0.0

### Version

llama-index-core==0.10.62

### Steps to Reproduce

```
from llama_index.readers.google import GoogleDriveReader

import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

from llama_index.core import SummaryIndex
from llama_index.readers.google import GoogleDriveReader

from IPython.display import Markdown, display

folder_id = [EDITED]

documents = GoogleDriveReader().load_data(folder_id=folder_id)

```

Also configure Google Cloud API keys and authorisation.

### Relevant Logs/Tracbacks

```shell
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0
file_cache is only supported with oauth2client<4.0.0
ERROR:llama_index.readers.google.drive.base:An error occurred while getting fileids metadata: can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "c:\Users\EDITED\Documents\GitHub\EDITED\venv\lib\site-packages\llama_index\readers\google\drive\base.py", line 213, in _get_fileids_meta
    query = "('" + folder_id + "' in parents)"
TypeError: can only concatenate str (not "list") to str
An error occurred while getting fileids metadata: can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "c:\Users\EDITED\venv\lib\site-packages\llama_index\readers\google\drive\base.py", line 213, in _get_fileids_meta
    query = "('" + folder_id + "' in parents)"
TypeError: can only concatenate str (not "list") to str
ERROR:llama_index.readers.google.drive.base:An error occurred while loading data from fileids meta: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "c:\Users\EDITED\venv\lib\site-packages\llama_index\readers\google\drive\base.py", line 405, in _load_data_fileids_meta
    for fileid_meta in fileids_meta:
TypeError: 'NoneType' object is not iterable
An error occurred while loading data from fileids meta: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "EDITED\venv\lib\site-packages\llama_index\readers\google\drive\base.py", line 405, in _load_data_fileids_meta
    for fileid_meta in fileids_meta:
TypeError: 'NoneType' object is not iterable
```

**Comment by peejay2** [comment]
Resolve the TypeError related to GoogleDriveReader._get_fileids_meta:
The error indicates that folder_id is being passed as a list instead of a string. Ensure folder_id is a string:

folder_id = "your_folder_id"  # Ensure this is a string, not a list
documents = GoogleDriveReader().load_data(folder_id=folder_id)

Sorted. Thank you!
