### ISSUE TITLE
[Bug]: impossible to use PDfReader with an S3 file because of Path() casting

### ISSUE THREAD

**Issue by seeifsalem** [run-llama/llama_index#15406]
### Bug Description

Hey, so to sum it up, I create a SimpleDirectoryReader with a PDFReader as an extractor and an s3 bucket as an input_dir, with also s3 as a fs.
ThenI call load_data() which leads to the PDFReader's method load_data(file=input_dir). the input dir is in the s3 format but first thing in load_data are these 2 lines
if not isinstance(file, Path):
file = Path(file)
This transforms it into a WindowsPath instead of a PosixPath and that doesn't work with S3. I think these two lines should be deleted or at least adapted to the filesystem at use
PS: I opened this issue with the wrong github account minutes ago, don't mind that one, I closed it

### Version

0.10.65

### Steps to Reproduce

versions used are the most recent as of today 15.08.2024 for llama-index-readers-file llama-index and llama-index-core
input_dir = f"{bucket}/{files_dir}"
files_to_exclude = processed_files
loader = SimpleDirectoryReader(input_dir=input_dir, exclude=files_to_exclude, file_extractor=extractors, fs=s3fs])
#s3fs being an instance of s3fs.core.S3FileSystem
docs = loader.load_data()

### Relevant Logs/Tracbacks

```shell
The error for one of the files, including additional traceback:

Failed to load file dtc-rag-lab/dtc-internal-test/files/TSLA-Q4-2021-Update.pdf with error: RetryError[<Future at 0x1b42c66de40 state=finished raised ValueError>]. Skipping...
Traceback (most recent call last):
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\tenacity\__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\llama_index\readers\file\docs\base.py", line 56, in load_data        
    with fs.open(str(file), "rb") as fp:
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\fsspec\spec.py", line 1303, in open
    f = self._open(
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\s3fs\core.py", line 688, in _open
    return S3File(
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\s3fs\core.py", line 2155, in __init__
    raise ValueError("Attempt to open non key-like path: %s" % path)
ValueError: Attempt to open non key-like path: dtc-rag-lab\dtc-internal-test\files\TSLA-Q4-2021-Update.pdf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\llama_index\core\readers\file\base.py", line 540, in load_file       
    docs = reader.load_data(input_file, **kwargs)
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\tenacity\__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\tenacity\__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\tenacity\__init__.py", line 376, in iter
    result = action(retry_state)
  File "c:\Users\VM-User\Desktop\RagLab\dtc_rag_lab\venv\lib\site-packages\tenacity\__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1b42c66de40 state=finished raised ValueError>]
```

**Comment by Chris-SL-Apps** [comment]
also suffering from this issue... short time fix would be much appreciated

**Comment by logan-markewich** [comment]
This should already be fixed in latest versions imo?

There is a check `_Path = Path if is_default_fs(self.fs) else PurePosixPath`

`PurePosixPath` will not return a path with incorrect slashes

https://github.com/run-llama/llama_index/blob/17f23014953e07eb8f8e7690d4cca7fb26c2109c/llama-index-core/llama_index/core/readers/file/base.py#L249

https://github.com/run-llama/llama_index/blob/17f23014953e07eb8f8e7690d4cca7fb26c2109c/llama-index-core/llama_index/core/readers/file/base.py#L284

**Comment by wapiflapi** [comment]
Hi ! 

I'm encountering a similar issue, but with `DirFileSystem` and not S3.

I'm reading the discussion and I have a question : Why would ``PurePosixPath`` be compatible with `fsspec` ? fsspec seems to take strings, which makes sense given the variety of cases it aims to handle.

For example: I want to use fsspec's `DirFileSystem` and I'm running into:

```
  File "[...]/.venv/lib/python3.10/site-packages/fsspec/implementations/dirfs.py", line 61, in _join
    return [self._join(_path) for _path in path]
TypeError: 'PurePosixPath' object is not iterable
```

They check if it's a string, if not they check if it's a dict, if not they assume it's an itterable like a list. 
Anyway, doesn't seem to be wrong what they're doing.

I don't understand why llamaindex is passing `Path` (or `PurePosixPath` ...) to a library that is not designed to handle them. I don't think using `PurePosixPath` is a good fix to this issue.

**Comment by NguyenTuan9347** [comment]
![image](https://github.com/user-attachments/assets/ff8ad566-d5e5-46cf-aa2f-0e589ebcb460)
I think because the object never get initialize so when you call it result in error ? 
This way of doing is kind of hacky which is intialize the custom data reader when pass it into the file_extractor arguments 
![image](https://github.com/user-attachments/assets/98da7695-dea5-40ca-ab2c-aa59b57bcf51)

**Comment by jmaerki** [comment]
Same problem with a MemoryFileSystem returning a PurePosixPath (listing files in a directory) which does not inherit from Path. Why go through all the trouble to pass through an AbstractFileSystem only to expect a "Path" object there?

**Comment by spideyashith** [comment]
"Hi @logan-markewich , I've implemented the fix for the S3 Path casting crash. Could you please approve the CI workflows to run? I've verified the fix locally on Windows."

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this one looks resolved on `main`.

`PDFReader.load_data` no longer blindly casts the input to `Path` — it picks `Path` only when the filesystem is the default local one, and `PurePosixPath` otherwise (so S3 paths via `s3fs` stay POSIX-style). It also accepts both `Path` and `PurePosixPath` in the `isinstance` check.

Evidence:
- Current `PDFReader.load_data` in [llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py#L40-L50](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py#L40-L50):
  ```python
  _Path = Path if is_default_fs(fs) else PurePosixPath
  if not isinstance(file, (Path, PurePosixPath)):
      file = _Path(file)
  ```
- This matches the fix @logan-markewich pointed at in the original thread: [`_Path = Path if is_default_fs(self.fs) else PurePosixPath`](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/readers/file/base.py) — already propagated to the integrations `PDFReader`.

If anyone can still repro with `SimpleDirectoryReader(input_dir=..., fs=s3fs.S3FileSystem(...))` + `PDFReader` on a current `llama-index-readers-file`, please share the version + a minimal repro. Otherwise this can probably be closed.

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against `main`.*
