### ISSUE TITLE
[Bug]: NameError: name 'p' is not defined

### ISSUE THREAD

**Issue by tytung2020** [run-llama/llama_index#15581]
### Bug Description

I use PandasQueryEngine to query large database, but it gives this error output:

> Pandas Instructions:
```python
df['gl'].apply(lambda x: x['Account']).value_counts()
```
```
Traceback (most recent call last):
  File "c:\Users\tytun\anaconda3\envs\pulse_ai\Lib\site-packages\llama_index\experimental\query_engine\pandas\output_parser.py", line 54, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tytun\anaconda3\envs\pulse_ai\Lib\site-packages\llama_index\experimental\exec_utils.py", line 159, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'p' is not defined
```

but strangely, 'p' is not shown in the Pandas Instructions above.

### Version

llama-index 0.11.0

### Steps to Reproduce

```

from llama_index.experimental.query_engine import PandasQueryEngine
from llama_index.llms.vertex import Vertex
import pandas as pd


def process_large_dataset_with_llamaindex(data: Dict[str, Any], query: str) -> str:
    """Process large dataset with LlamaIndex."""
    df = pd.DataFrame(data)
    vertex_gemini = Vertex(model="gemini-1.5-flash", temperature=0, additional_kwargs={})
    query_engine = PandasQueryEngine(df=df, verbose=True, llm=vertex_gemini)
    response = query_engine.query(query)
    return str(response)
    
result = <some large database here>
user_query = "summarize the data"
llamaindex_response = process_large_dataset_with_llamaindex(result, user_query)

```

**Comment by tytung2020** [comment]
I have tried your code and the same error still occurs. @dosu

**Comment by Shubh789da** [comment]
Even I am also facing the same issue, sometimes when I say provide answer only in text then some times it resolves not mostly not. Its fustration when working with mutiple query engines please help.

**Comment by yangxg** [comment]
I am encountering the same issue. The PandasQueryEngine gives the correct code instruction, but when running the code, there are the error. Please help, thanks!

```
> Pandas Output: There was an error running the output as Python code. Error message: name 'p' is not defined
Traceback (most recent call last):
  File "/home/yxg/.pyenv/versions/3.12.7/envs/llamaindex/lib/python3.12/site-packages/llama_index/experimental/query_engine/pandas/output_parser.py", line 61, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yxg/.pyenv/versions/3.12.7/envs/llamaindex/lib/python3.12/site-packages/llama_index/experimental/exec_utils.py", line 159, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'p' is not defined
```
