### ISSUE TITLE
[Question]: How can a VectorStoreIndex be generated via parallel processing?

### ISSUE THREAD

**Issue by compilebunny** [run-llama/llama_index#15655]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am working on a RAG project that involves ingesting large numbers of PDF documents. SimpleDirectoryReader is slow but acceptable, however digestion using Document and VectorStoreIndex.from_documents is unacceptably slow running on one CPU.

Is there a way to get these processes running across multiple CPUs or the GPU?

Sample code below

```
  documents = SimpleDirectoryReader(
    input_dir = document_dir,
    recursive = True,
  ).load_data()

  documents = Document(text = "\n\n".join([doc.text for doc in documents]))

  index = VectorStoreIndex.from_documents(
    [documents], service_context=saved_context
  )
```

**Comment by logan-markewich** [comment]
Really depends on the embedding model and vector store you are using.

But in any case, seeing an example of what from_documents is doing (and how you can do it) will probably help (imo i would use async instead of multiprocessing if using remote apis for your embedding model and vector store)

Synchronous
```
from llama_index.core.node_parser import SentenceSplitter
from llama_index.embeddings.openai import OpenAIEmbedding

splitter = SentenceSplitter(chunk_size=1024)

nodes = splitter(documents)

embed_model = OpenAIEmbedding(model_name="text-embedding-3-small", embed_batch_size=512)

node_texts = [node.get_content(metadata_mode="embed") for node in nodes]
embeddings = embed_model.get_text_embedding_batch(node_texts)
for (embedding, node) in zip(nodes, embeddings):
  node.embedding = embedding

vector_store.add(nodes)
```

Async:
```
from llama_index.core.node_parser import SentenceSplitter
from llama_index.embeddings.openai import OpenAIEmbedding

splitter = SentenceSplitter(chunk_size=1024)

nodes = splitter(documents)

embed_model = OpenAIEmbedding(model_name="text-embedding-3-small", embed_batch_size=512, num_workers=4)

node_texts = [node.get_content(metadata_mode="embed") for node in nodes]
embeddings = await embed_model.aget_text_embedding_batch(node_texts)
for (embedding, node) in zip(nodes, embeddings):
  node.embedding = embedding

await vector_store.async_add(nodes)
```

**Comment by logan-markewich** [comment]
If you are using the default vector store (i wouldn't tbh), you'd have to do `index.insert_nodes(nodes)` instead of inserting directly into the vector store like I did

**Comment by compilebunny** [comment]
Thanks @dosu

Can you explain how to get from the Document object returned by SimpleDirectoryReader to the nodes that are referenced in your example of parallel processing and incremental indexing in a parallel way?

**Comment by Gzj369** [comment]
> If you are using the default vector store (i wouldn't tbh), you'd have to do `index.insert_nodes(nodes)` instead of inserting directly into the vector store like I did

@logan-markewich I have a question, I use the class "FaissVectorStore" build to get "vector_store", then use vector_store.add([new_node]), finally query the new added knowledge,but cannot find ? The code is bellow:
embed_model.embed_query cant convert str to List[float], it can work well.
```python
new_add_knowledge = 'new add a sentence' (just a example)
vector_store = FaissVectorStore.from_persist_dir(vector_store_path)
metadata = {"source": "add"}
excluded = ["source"]
node = TextNode(text=new_add_knowledge, 
                metadata=metadata, 
                excluded_embed_metadata_keys=excluded, 
                excluded_llm_metadata_keys=excluded,
                embedding=embed_model.embed_query(new_add_knowledge))
logger.debug("node.embedding: {}", node.embedding)
vector_store.add([node])
print("--------------111")
# vector_store.persist(persist_path=vector_store_path)
res = vector_store.query(VectorStoreQuery(query_embedding=embed_model.embed_query(new_add_knowledge), similarity_top_k=2))
print("--------------222")
assert res.nodes
print("--------------333")
logger.debug("result: {}", res.nodes[0].get_content())
```

just "--------------222" has been printed, but "--------------333" and  "result: " have not been  printed , 
please have a look

**Comment by Gzj369** [comment]
and another question,  the parametter of vector_store.persist is **like file_path**, the parametter of  vector_index.storage_context.persist is **like dir**, so for the code above,  when I  run the code 
```python
vector_store.persist(persist_path=vector_store_path)
```
it occur the error, so how can I solve it ?

**Comment by ZJL0111** [comment]
> Hey @compilebunny! I'm here to help you out with any bugs, questions, or contributions you have. Let's tackle this issue together while we wait for the human maintainers.
> 
> I found a similar issue that addresses the slow creation and reading times of the `VectorStoreIndex` with large datasets. Here are some suggested optimizations:
> 
> 1. **Parallel Processing**: Utilize parallel processing to expedite the index creation. This involves dividing your data into smaller chunks and processing them simultaneously across multiple CPU cores.
> 2. **Incremental Indexing**: Build the index incrementally by adding data in smaller batches, which can be more efficient than processing everything at once.
> 3. **Optimize Reading**: Improve read times by using techniques like memory mapping (`mmap`) to map the index file into memory, which can significantly reduce loading times.
> 4. **Efficient Data Structures**: Employ data structures that support fast search and insertion operations to enhance both creation and reading speeds.
> 5. **Hardware Acceleration**: If available, leverage GPUs for hardware acceleration to further speed up processing.
> 
> Here's a practical example of implementing parallel processing and incremental indexing:
> 
> ```python
> from multiprocessing import Pool
> from llama_index.core import VectorStoreIndex
> 
> def create_index(nodes):
>     return VectorStoreIndex(nodes, include_embeddings=True)
> 
> # Split nodes into manageable chunks
> chunks = [nodes[i:i + 10000] for i in range(0, len(nodes), 10000)]
> 
> # Process chunks in parallel
> with Pool(processes=4) as pool:
>     indices = pool.map(create_index, chunks)
> 
> # Merge the processed indices
> index = VectorStoreIndex.merge(indices)
> 
> # Persist the index
> index.storage_context.persist(persist_dir="../storage/")
> ```
> 
> These strategies are aimed at optimizing performance by leveraging parallel processing, managing data more efficiently, and utilizing hardware capabilities. Testing different approaches to find the best fit for your specific needs is crucial, as optimizations can vary based on the dataset and system configuration [[1]](https://github.com/run-llama/llama_index/issues/12786).
> 
> Additionally, you can optimize the reading speed of PDF documents in `SimpleDirectoryReader` by using parallel processing. This can be achieved by setting the `num_workers` parameter to a positive integer value when calling the `load_data()` method. Example:
> 
> ```python
> from multiprocessing import cpu_count
> 
> # Set the number of workers to the minimum of 2 or the number of available CPU cores
> num_workers = min(2, cpu_count())
> 
> # Initialize the reader with desired configurations
> reader = SimpleDirectoryReader(directory_path, recursive=True, exclude_hidden=True, num_files_limit=100)
> 
> # Load data using parallel processing
> documents = reader.load_data(num_workers=num_workers)
> ```
> 
> This configuration allows the `SimpleDirectoryReader` to utilize multiple processes to load the data, significantly speeding up the reading process [[2]](https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/data_connectors/simple_directory_reader_parallel.ipynb).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

hi, what if i use Milvus as my vector store? can i just replace the function create index as the following 
```Python
def cerate_milvus_index(nodes):
    milvus_store = MilvusVectorStore(
        uri=MILVUS_URI,
        collection_name=COLLECTION_NAME,
        dim=1024,  # 根据您的嵌入维度设置
        overwrite=True
    )
    vector_storage_context = StorageContext.from_defaults(vector_store=milvus_store)
    vector_storage_context.docstore.add_documents(nodes)
    # vector_index = VectorStoreIndex(nodes, storage_context=vector_storage_context) 
    return VectorStoreIndex(nodes, storage_context=vector_storage_context)
```

 and when my amount is huge like 2K long pdf files, are there any method revelent with milvus to speed up the  indexing process? except already mentioned; my failed code is bellow 

``` Python
 # 检查是否已存在存储的索引
    if not os.path.exists(_persist_dir):
        # 如果不存在，创建新的索引
        documents = SimpleDirectoryReader(_data_dir).load_data()
        # documents = SimpleDirectoryReader("./data/TEST_V1/Antibody").load_data()
        # documents = SimpleDirectoryReader("./data/demo_metadata").load_data()
        nodes = meta_data2_nodes(documents)

        # 使用milvus创建vector index# 保存索引; 注milvus会自动保存index, 不用手动保存
        milvus_store = MilvusVectorStore(
            uri=MILVUS_URI,
            collection_name=COLLECTION_NAME,
            dim=1024,  # 根据您的嵌入维度设置
            overwrite=True
        )
        vector_storage_context = StorageContext.from_defaults(vector_store=milvus_store)
        vector_storage_context.docstore.add_documents(nodes)
        vector_index = VectorStoreIndex(nodes, storage_context=vector_storage_context)

        # 创建关键词索引（使用默认存储）
        key_storage_context = StorageContext.from_defaults()
        key_storage_context.docstore.add_documents(nodes)
        keyword_index = SimpleKeywordTableIndex(nodes, storage_context=key_storage_context)
        keyword_index.set_index_id("keyword_index")
        keyword_index.storage_context.persist(persist_dir=PERSIST_DIR + "keyword/")
```

and get error 

``` Python
92%|█████████▏| 102604/111773 [48:53:46<8:15:11,  3.24s/it]
 92%|█████████▏| 102605/111773 [48:54:07<19:50:20,  7.79s/it]
 92%|█████████▏| 102606/111773 [48:54:12<17:50:33,  7.01s/it]
 92%|█████████▏| 102606/111773 [48:54:12<4:22:08,  1.72s/it] 
Traceback (most recent call last):
  File "/home/zjl/miniforge3/envs/RAG/lib/python3.12/site-packages/httpcore/backends/asyncio.py", line 33, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjl/miniforge3/envs/RAG/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1203, in receive
    await self._protocol.read_event.wait()
  File "/home/zjl/miniforge3/envs/RAG/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError
```

**Comment by Gzj369** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件我已经收到。看到后我一定会在第一时间内阅读并回复您。

**Comment by Gzj369** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件我已经收到。看到后我一定会在第一时间内阅读并回复您。
