### ISSUE TITLE
[Bug]: ValueError: Failed to convert output to JSON: '```json\n[]\n```'

### ISSUE THREAD

**Issue by dimartinez** [run-llama/llama_index#15768]
### Bug Description

If you use 'gpt-4o-mini' with a specific questions responded by VectorStorageIndex you will get a error about convert output to JSON when is used throw RouterQueryEngine. It don't be throw if you use gpt-4o model.

### Version

0.11.3

### Steps to Reproduce

from http.client import responses

from llama_index.core import (
    SimpleDirectoryReader,
    Settings,
    SummaryIndex,
    VectorStoreIndex
)
from llama_index.core.tools import QueryEngineTool
from llama_index.core.query_engine.router_query_engine import RouterQueryEngine
from llama_index.core.selectors.llm_selectors import LLMSingleSelector
from llama_index.llms.openai import OpenAI
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.core.node_parser import SentenceSplitter

Settings.llm = OpenAI(model="gpt-4o-mini")
Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-small")

from llama_index.core import SimpleDirectoryReader

documents = SimpleDirectoryReader(
    input_files=['a pdf file... fails with any document...']
).load_data()

splitter = SentenceSplitter(chunk_size=1024)
nodes = splitter.get_nodes_from_documents(documents)

summary_index = SummaryIndex(nodes)
vector_index = VectorStoreIndex(nodes)

summary_query_engine = summary_index.as_query_engine(
    response_mode="tree_summarize",
    use_async=True
)

vector_query_engine = vector_index.as_query_engine()

summary_tool = QueryEngineTool.from_defaults(
    query_engine=summary_query_engine,
    description=(
        "Useful for respond to summarizations questions about bla bla"
    )

)

vector_tool = QueryEngineTool.from_defaults(
    query_engine=vector_query_engine,
    description=(
        "Useful for respond to specific questions about bla bla"
    )
)

query_engine = RouterQueryEngine(
    selector=LLMSingleSelector.from_defaults(),
    query_engine_tools=[
        summary_tool,
        vector_tool
    ],
    verbose=True
)

response = query_engine.query("What's a tech radar?")
print(str(response))

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\tabar\PycharmProjects\tech-radar\tech-radar.py", line 69, in <module>
    response = query_engine.query("What's a tech radar?")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tabar\anaconda3\envs\tech-radar\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tabar\anaconda3\envs\tech-radar\Lib\site-packages\llama_index\core\base\base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tabar\anaconda3\envs\tech-radar\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tabar\anaconda3\envs\tech-radar\Lib\site-packages\llama_index\core\query_engine\router_query_engine.py", line 154, in _query
    result = self._selector.select(self._metadatas, query_bundle)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tabar\anaconda3\envs\tech-radar\Lib\site-packages\llama_index\core\base\base_selector.py", line 88, in select
    return self._select(choices=metadatas, query=query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tabar\anaconda3\envs\tech-radar\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tabar\anaconda3\envs\tech-radar\Lib\site-packages\llama_index\core\selectors\llm_selectors.py", line 114, in _select
    parse = self._prompt.output_parser.parse(prediction)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tabar\anaconda3\envs\tech-radar\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tabar\anaconda3\envs\tech-radar\Lib\site-packages\llama_index\core\output_parsers\selection.py", line 97, in parse
    raise ValueError(f"Failed to convert output to JSON: {output!r}")
ValueError: Failed to convert output to JSON: '\n[]\n'

Process finished with exit code 1
```

**Comment by dimartinez** [comment]
@dosubot it will works ok if use PydanticSingleSelector
