### ISSUE TITLE
[Bug]: AssertionError assert isinstance(node, BaseNode) or node is None

### ISSUE THREAD

**Issue by YashiroNanakse** [run-llama/llama_index#15824]
### Bug Description

Traceback (most recent call last):
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\async_utils.py", line 30, in asyncio_run
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python 3.11.9\Lib\asyncio\events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\graph-index\main.py", line 26, in <module>
    nodes = retriever.retrieve("丽维嘉")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 264, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\base\base_retriever.py", line 245, in retrieve
    nodes = self._retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 264, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\indices\property_graph\retriever.py", line 52, in _retrieve
    return asyncio_run(self._aretrieve(query_bundle))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\async_utils.py", line 38, in asyncio_run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "E:\Python 3.11.9\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "E:\Python 3.11.9\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python 3.11.9\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\indices\property_graph\retriever.py", line 64, in _aretrieve
    async_results = await run_jobs(
                    ^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 296, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\async_utils.py", line 148, in run_jobs
    results = await asyncio.gather(*pool_jobs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 296, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\async_utils.py", line 139, in worker
    return await job
           ^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 296, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\base\base_retriever.py", line 276, in aretrieve
    nodes = await self._aretrieve(query_bundle=query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\indices\property_graph\sub_retrievers\base.py", line 145, in _aretrieve
    nodes = await self.async_add_source_text(nodes)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\indices\property_graph\sub_retrievers\base.py", line 134, in async_add_source_text
    return self._add_source_text(nodes, og_node_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\graph-index\.venv\Lib\site-packages\llama_index\core\indices\property_graph\sub_retrievers\base.py", line 89, in _add_source_text
    assert isinstance(node, BaseNode) or node is None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

### Version

0.11.4

### Steps to Reproduce

documents = SimpleDirectoryReader("./data").load_data()

Settings.embed_model = dashscope_embed

Settings.llm = dashscope_llm

index = PropertyGraphIndex.from_documents(documents)

print('------index-----')
print(index)

retriever = index.as_retriever(
    include_text=True,
    similarity_top_k=2,
)

print('------retriever-----')
nodes = retriever.retrieve("丽维嘉")

**Comment by YashiroNanakse** [comment]
How do you generate nodes?
Why generate nodes when I'm following the documentation example and there are no nodes?

**Comment by YashiroNanakse** [comment]
I don't think that's the reason for the error, whenever I execute the code nodes = retriever.retrieve(“Riviera”) I get the above error can you help me to analyze what's wrong?

**Comment by YashiroNanakse** [comment]
from llama_index.core.indices.property_graph import QueryBundle
ImportError: cannot import name 'QueryBundle' from 'llama_index.core.indices.property_graph'

**Comment by YashiroNanakse** [comment]
from llama_index.legacy.schema import QueryBundle
ModuleNotFoundError: No module named 'llama_index.legacy'

**Comment by YashiroNanakse** [comment]
llama-cloud==0.0.15
llama-index==0.11.4
llama-index-agent-openai==0.3.0
llama-index-cli==0.3.0
llama-index-core==0.11.4
llama-index-embeddings-dashscope==0.2.1
llama-index-embeddings-openai==0.2.4
llama-index-graph-stores-neo4j==0.3.1
llama-index-indices-managed-llama-cloud==0.3.0
llama-index-legacy==0.9.48.post3
llama-index-llms-dashscope==0.2.0
llama-index-llms-openai==0.2.2
llama-index-multi-modal-llms-openai==0.2.0
llama-index-program-openai==0.2.0
llama-index-question-gen-openai==0.2.0
llama-index-readers-file==0.2.0
llama-index-readers-llama-parse==0.3.0
llama-parse==0.5.1
