### ISSUE TITLE
[Bug]: PydanticSerializationError raised by LLM(s) that base OpenAI during openinference instrumentation

### ISSUE THREAD

**Issue by enrico-stauss** [run-llama/llama_index#15851]
### Bug Description

The serialization issue has been floating around for a few days I believe (https://github.com/Arize-ai/phoenix/issues/4423) but it really seems to come down to the implementation of the `llama_index.core.base.llms.types.ChatResponse` with the attribute raw being of type `oepnai.types.chat.chat_completion.ChatCompletion`.

The error occurs here: https://github.com/Arize-ai/openinference/blob/9e91a74700326281b5a45880b178f5d74e572995/python/instrumentation/openinference-instrumentation-llama-index/src/openinference/instrumentation/llama_index/_handler.py#L248

but does not happen when calling `result.model_dump_json(exclude_unset=True, exclude={"raw"})` OR `result.raw.model_dump_json(exclude_unset=True)`. So it should be possible to fix it by modifying 
 `llama_index.core.base.llms.types.ChatResponse`.

I hope this helps and kind regards
Enrico

### Version

0.11.4

### Steps to Reproduce

Install llama-index into an env and run the below snippet. The response will be printed just fine, but an ERROR will be logged.

```python

import os

import phoenix as px  # NOQA: package name is arize-phoenix
from llama_index.core import set_global_handler
from llama_index.core.prompts.base import PromptTemplate
from llama_index.llms.groq import Groq

px.launch_app(use_temp_dir=True)
set_global_handler("arize_phoenix")


os.environ["GROQ_API_KEY"] = ""
llm = Groq("gemma2-9B-it")

PROMPT_TEMPLATE_STR = """{query}"""
prompt_template = PromptTemplate(PROMPT_TEMPLATE_STR)
response = llm.predict(prompt_template, query="Why is the sky blue?")
print(response)
```

For reference, this is an excerpt of my environment:
```
arize-phoenix                                 4.16.1
arize-phoenix-evals                           0.14.1
llama-cloud                                   0.0.15
llama-index                                   0.11.4
llama-index-agent-openai                      0.3.0
llama-index-callbacks-arize-phoenix           0.2.1
llama-index-cli                               0.3.0
llama-index-core                              0.11.4
llama-index-embeddings-databricks             0.2.0
llama-index-embeddings-openai                 0.2.4
llama-index-indices-managed-llama-cloud       0.3.0
llama-index-legacy                            0.9.48.post3
llama-index-llms-databricks                   0.2.0
llama-index-llms-groq                         0.2.0
llama-index-llms-openai                       0.2.2
llama-index-llms-openai-like                  0.2.0
llama-index-multi-modal-llms-openai           0.2.0
llama-index-postprocessor-cohere-rerank       0.2.0
llama-index-postprocessor-mixedbreadai-rerank 0.2.0
llama-index-program-openai                    0.2.0
llama-index-question-gen-openai               0.2.0
llama-index-readers-file                      0.2.0
llama-index-readers-llama-parse               0.3.0
llama-index-vector-stores-qdrant              0.3.0
llama-parse                                   0.5.1
openai                                        1.37.1
openinference-instrumentation                 0.1.9
openinference-instrumentation-langchain       0.1.23
openinference-instrumentation-llama-index     2.1.1
openinference-instrumentation-openai          0.1.9
openinference-semantic-conventions            0.1.9
opentelemetry-api                             1.26.0
opentelemetry-exporter-otlp                   1.26.0
opentelemetry-exporter-otlp-proto-common      1.26.0
opentelemetry-exporter-otlp-proto-grpc        1.26.0
opentelemetry-exporter-otlp-proto-http        1.26.0
opentelemetry-instrumentation                 0.47b0
opentelemetry-proto                           1.26.0
opentelemetry-sdk                             1.26.0
opentelemetry-semantic-conventions            0.47b0
pydantic                                      2.8.2
pydantic_core                                 2.20.1
```

### Relevant Logs/Tracbacks

```shell
ERROR [openinference.instrumentation.llama_index._handler] Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
Traceback (most recent call last):
  File "C:\Users\stauss\AppData\Local\pypoetry\Cache\virtualenvs\interactive-documentation-4Z7Ya2eB-py3.10\lib\site-packages\openinference\instrumentation\llama_index\_handler.py", line 248, in process_output
    self[OUTPUT_VALUE] = result.model_dump_json(exclude_unset=True)
  File "C:\Users\stauss\AppData\Local\pypoetry\Cache\virtualenvs\interactive-documentation-4Z7Ya2eB-py3.10\lib\site-packages\pydantic\main.py", line 415, in model_dump_json
    return self.__pydantic_serializer__.to_json(
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```
```

**Comment by enrico-stauss** [comment]
The issue is fixed in https://github.com/Arize-ai/openinference/pull/997, so updating the dependency to `openinference-instrumentation-llama-index = "^3.0.1"` should resolve this issue.
