### ISSUE TITLE
[Bug]: SimpleDirectoryReader reads "once" and then says no files

### ISSUE THREAD

**Issue by WASasquatch** [run-llama/llama_index#15858]
### Bug Description

When I run the SimpleDirectoryReader it will find files, work as intended. But if I run it again, it will complain there are no files in the directory if ran again in same Python session on same dir. 

### Version

llama-index==0.11.1

### Steps to Reproduce

Load files with simple directory reader, do things. Run again on same documents (inefficient, yes, but has a issue) and `reader.load_data()` will evaluate `False`. Files in directory still exist on disk. 

### Relevant Logs/Tracbacks

```shell
documents = reader.load_data()
if not documents:
    raise ValueError("No documents found in the specified directory.")
```

```
Traceback (most recent call last):
  File "M:\ComfyUI_slow_2\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "M:\ComfyUI_slow_2\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "M:\ComfyUI_slow_2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "M:\ComfyUI_slow_2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "M:\ComfyUI_slow_2\custom_nodes\SaltAI_Language_Toolkit\nodes\readers.py", line 1012, in read_directory
    raise ValueError("No documents found in the specified directory.")
ValueError: No documents found in the specified directory.
```

**Comment by WASasquatch** [comment]
> Hey @WASasquatch! I'm here to help with any bugs, questions, or contributions you have for llama-index. I'm looking forward to assisting you with this issue!
> 
> The issue you're encountering with `SimpleDirectoryReader` in `llama-index==0.11.1` is due to the class caching the list of input files when it is first instantiated. Subsequent attempts to read files in the same session will use the cached list, which does not get updated.
> 
> To work around this, you need to create a new instance of `SimpleDirectoryReader` each time you want to read the files again in the same session. This will ensure that the directory is scanned afresh and the list of files is updated.
> 
> Here's a brief explanation of the behavior:
> 
>     * When `SimpleDirectoryReader` is instantiated, it initializes the `input_files` attribute by calling the `_add_files` method, which scans the directory and caches the list of files.
> 
>     * Subsequent calls to `load_data()` will use this cached list, and if the list is empty or unchanged, it will result in no files being found.
> 
> 
> To avoid this, instantiate a new `SimpleDirectoryReader` like this:
> 
> ```python
> from llama_index import SimpleDirectoryReader
> 
> # First read
> reader = SimpleDirectoryReader(input_dir="your_directory_path")
> documents = reader.load_data()
> 
> # Do some processing...
> 
> # Second read (create a new instance)
> reader = SimpleDirectoryReader(input_dir="your_directory_path")
> documents = reader.load_data()
> ```
> 
> This approach ensures that the directory is scanned afresh each time you want to read the files [[1]](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/tests/readers/test_file.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I do in fact re-instantiate the simple directory reader in the method which is called each "run":


```
    def read_directory(self, input_directory, optional_path_list=[], recursive=False, required_ext_list=None, exclude_glob_list=None):

        if required_ext_list.strip():
            required_exts = [ext.strip() for ext in required_ext_list.split(",") if ext.strip()]
        else:
            required_exts = None

        if exclude_glob_list.strip():
            exclude = [pattern.strip() for pattern in exclude_glob_list.split(",") if pattern.strip()]
        else:
            exclude = None

        logger.info(f"Excluding: {exclude}")
        logger.info(f"Required Extensions: {required_exts}")

        if not optional_path_list:
            full_path = get_full_path(1, input_directory.strip())
            input_dir = full_path if os.path.isdir(full_path) else None
            if not input_dir:
                raise ValueError("The provided subdirectory does not exist.")

            reader = SimpleDirectoryReader(
                input_dir=input_dir,
                exclude_hidden=True,
                recursive=recursive,
                required_exts=required_exts,
                exclude=exclude
            )
        elif optional_path_list and isinstance(optional_path_list, (str, list)):

            if isinstance(optional_path_list, str):
                path_list = [optional_path_list]
            else:
                path_list = []
                for path in optional_path_list:
                    if os.path.isfile(path): # and path.startswith(folder_paths.get_input_directory()):
                        path_list.append(path)

            reader = SimpleDirectoryReader(
                input_files=path_list,
            )


        documents = reader.load_data()
        if not documents:
            raise ValueError("No documents found in the specified directory.")

        return (documents,)
 ```
 
 So it is re-instantiated.

**Comment by WASasquatch** [comment]
I think the issue is it's having a really hard time with `.ipynb` files.

**Comment by logan-markewich** [comment]
Going to close this out -- `.ipynb` parsing isn't implemented, but feel free to open a PR to add it or a new github issue
