### ISSUE TITLE
[Bug]: Pandas Query Engine Eval Problem with "*=" sign

### ISSUE THREAD

**Issue by mohamedhazem24** [run-llama/llama_index#15865]
### Bug Description

I requested a query to multiply some column with specific constant and it gave me the right code but unfortunately the llama index safe_eval function cannot execute this code 
df.loc[df['product'].isin([1069104, 1069105]), 'score'] *= 10
despite it is written in the right syntax .
![image](https://github.com/user-attachments/assets/36dc1d67-8934-418f-9020-16ba8b39189b)

### Version

latest version

### Steps to Reproduce

run this code after install proper libs and using a groq API
groq_API=""
llm = Groq(model="llama3-70b-8192", api_key=groq_API)
code_string = '''
df = pd.DataFrame({'product': [1179160, 1066490, 1148126, 1069104, 1069105, 1160330, 1069098, 1077784, 1193369, 1179741],
                   'score': [0.424654, 0.424509, 0.422207, 0.420455, 0.414603, 0.168784, 0.168749, 0.168738, 0.168703, 0.168684]})
print(df)
'''

exec(code_string)
query_engine = PandasQueryEngine(df=df, verbose=True,llm=llm)
print(query_engine.query(''' 
what I'm trying to achieve is to multiply certain score values corresponding to specific products by a constant.
I have the products target of this multiplication in a list like this: [1069104, 1069105] (this is just a simplified
example, in reality it would be more than two products) and my goal is to obtain this:
Multiply scores corresponding to products 1069104 and 1069105 by 10
'''))

**Comment by mohamedhazem24** [comment]
@dosu 
no I am getting this error 
> Pandas Output: There was an error running the output as Python code. Error message: invalid syntax (<string>, line 1)
There was an error running the output as Python code. Error message: invalid syntax (<string>, line 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_index/experimental/query_engine/pandas/output_parser.py", line 54, in default_output_processor
    output_str = str(safe_exec(module_end_str, global_vars, local_vars))
  File "/usr/local/lib/python3.10/dist-packages/llama_index/experimental/exec_utils.py", line 159, in safe_eval
  File "<string>", line 1
    df.loc[df['product'].isin([1069104, 1069105]), 'score'] *= 10

**Comment by logan-markewich** [comment]
I don't think there is an easy way to fix this, especially if `eval()` won't execute it
