### ISSUE TITLE
[Question]: how can i solve the utf8 problem

### ISSUE THREAD

**Issue by 912100012** [run-llama/llama_index#15897]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

when I use the propertygraphindex to persist to disk，the other file such as  “default__vector_store.json” saved as utf8 because it use the "json.dump(assic=True)" when vector_store.persist() is called.But the propertygraph.persist use the "model_dump_json()"  when its persist() is called,the "model_dump_json()" do not have the assic=True paramaeter to cover the chinese to the format like “\u6235"
So how can i solve this problem,only the property_graph_store.json file can not  be saved as utf-8.

**Comment by 912100012** [comment]
why error happen？code and error as follow:@dosu
code:
storage_context = StorageContext.from_defaults(persist_dir="../storage/yanbao-SchemaEXT")
index = load_index_from_storage(storage_context)
query_engine = index.as_query_engine()

streaming_response = query_engine.query("请你说一下，文字的中心思想？")
streaming_response.print_response_stream()
-----------------------------------------------------
error:
Traceback (most recent call last):
  File "F:\Project\pythonWorkspace\text2Sql-Demo\test\testCn.py", line 12, in <module>
    streaming_response = query_engine.query("请你说一下，文字的中心思想？")
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\base\base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\query_engine\retriever_query_engine.py", line 175, in _query
    nodes = self.retrieve(query_bundle)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\query_engine\retriever_query_engine.py", line 130, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\base\base_retriever.py", line 245, in retrieve
    nodes = self._retrieve(query_bundle)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\indices\property_graph\retriever.py", line 52, in _retrieve
    return asyncio_run(self._aretrieve(query_bundle))
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\async_utils.py", line 33, in asyncio_run
    return loop.run_until_complete(coro)
  File "E:\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\indices\property_graph\retriever.py", line 64, in _aretrieve
    async_results = await run_jobs(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 297, in async_wrapper
    result = await func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\async_utils.py", line 148, in run_jobs
    results = await asyncio.gather(*pool_jobs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 297, in async_wrapper
    result = await func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\async_utils.py", line 139, in worker
    return await job
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 297, in async_wrapper
    result = await func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\base\base_retriever.py", line 276, in aretrieve
    nodes = await self._aretrieve(query_bundle=query_bundle)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\indices\property_graph\sub_retrievers\base.py", line 145, in _aretrieve
    nodes = await self.async_add_source_text(nodes)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\indices\property_graph\sub_retrievers\base.py", line 134, in async_add_source_text
    return self._add_source_text(nodes, og_node_map)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\indices\property_graph\sub_retrievers\base.py", line 89, in _add_source_text
    assert isinstance(node, BaseNode) or node is None
AssertionError

Process finished with exit code 1

**Comment by 912100012** [comment]
why my code error happend?
----------------code--------------------
storage_context = StorageContext.from_defaults(persist_dir="../storage/testnew")

--------------error------------
 raise ValueError(f"Could not infer node type for data: {node_dict!s}")
ValueError: Could not infer node type for data {'label': 'text_chunk', 'embedding': [0.049393251550212604, ...........................

@dosu

**Comment by 912100012** [comment]
Request body: {'model': 'qwen-turbo', 'parameters': {'max_tokens': 1000, 'temperature': 0.1, 'seed': 1234, 'result_format': 'message'}, 'input': {'messages': [{'role': 'user', 'content': "Given some initial query, generate synonyms or related keywords up to 10 in total, considering possible cases of capitalization, pluralization, common expressions, etc.\nProvide all synonyms/keywords separated by '^' symbols: 'keyword1^keyword2^...'\nNote, result should be in one-line, separated by '^' symbols.----\nQUERY: 老陈和女主的一些事，请你进行总结\n----\nKEYWORDS: "}]}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dashscope.aliyuncs.com:443
Starting new HTTPS connection (1): dashscope.aliyuncs.com:443
DEBUG:urllib3.connectionpool:https://dashscope.aliyuncs.com:443 "POST /api/v1/services/aigc/text-generation/generation HTTP/11" 200 None
https://dashscope.aliyuncs.com:443 "POST /api/v1/services/aigc/text-generation/generation HTTP/11" 200 None
DEBUG:dashscope:Response: {'output': {'choices': [{'finish_reason': 'stop', 'message': {'role': 'assistant', 'content': '老陈^女主^一些事情^总结^关系^情节^发展^互动^故事^事件'}}]}, 'usage': {'total_tokens': 117, 'output_tokens': 21, 'input_tokens': 96}, 'request_id': 'ef9dd55c-ffa6-9548-bbdb-ae05265b9542'}
Response: {'output': {'choices': [{'finish_reason': 'stop', 'message': {'role': 'assistant', 'content': '老陈^女主^一些事情^总结^关系^情节^发展^互动^故事^事件'}}]}, 'usage': {'total_tokens': 117, 'output_tokens': 21, 'input_tokens': 96}, 'request_id': 'ef9dd55c-ffa6-9548-bbdb-ae05265b9542'}

这是我在控制台上看到的，这一步在干什么，为什么要把我的问题，先用大模型进行同义词总结？后续的意义是什么？@dosu

**Comment by omegazerore** [comment]
> Request body: {'model': 'qwen-turbo', 'parameters': {'max_tokens': 1000, 'temperature': 0.1, 'seed': 1234, 'result_format': 'message'}, 'input': {'messages': [{'role': 'user', 'content': "Given some initial query, generate synonyms or related keywords up to 10 in total, considering possible cases of capitalization, pluralization, common expressions, etc.\nProvide all synonyms/keywords separated by '^' symbols: 'keyword1^keyword2^...'\nNote, result should be in one-line, separated by '^' symbols.----\nQUERY: 老陈和女主的一些事，请你进行总结\n----\nKEYWORDS: "}]}} DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dashscope.aliyuncs.com:443 Starting new HTTPS connection (1): dashscope.aliyuncs.com:443 DEBUG:urllib3.connectionpool:https://dashscope.aliyuncs.com:443 "POST /api/v1/services/aigc/text-generation/generation HTTP/11" 200 None https://dashscope.aliyuncs.com:443 "POST /api/v1/services/aigc/text-generation/generation HTTP/11" 200 None DEBUG:dashscope:Response: {'output': {'choices': [{'finish_reason': 'stop', 'message': {'role': 'assistant', 'content': '老陈^女主^一些事情^总结^关系^情节^发展^互动^故事^事件'}}]}, 'usage': {'total_tokens': 117, 'output_tokens': 21, 'input_tokens': 96}, 'request_id': 'ef9dd55c-ffa6-9548-bbdb-ae05265b9542'} Response: {'output': {'choices': [{'finish_reason': 'stop', 'message': {'role': 'assistant', 'content': '老陈^女主^一些事情^总结^关系^情节^发展^互动^故事^事件'}}]}, 'usage': {'total_tokens': 117, 'output_tokens': 21, 'input_tokens': 96}, 'request_id': 'ef9dd55c-ffa6-9548-bbdb-ae05265b9542'}
> 
> 这是我在控制台上看到的，这一步在干什么，为什么要把我的问题，先用大模型进行同义词总结？后续的意义是什么？[@dosu](https://github.com/dosu)

因為在PropertyGraph中，會用到Exact Match來提取節點。若是沒用同義詞，一些意思相近但不相同的詞會被忽略掉。所以產生一組同義詞，盡可能地抓取可能的節點來拉高recall。
然後你在index.as_query_engine 中，可能沒有 include_text=True，我猜的，導致出現很奇怪的response。

**Comment by Kaif10** [comment]
This appears to have been fixed by #21111 (commit 17fba87, merged 2026-04-20), which added explicit `encoding="utf-8"` to the `fs.open()` calls in `SimplePropertyGraphStore.persist()`/`from_persist_path()` (and the other simple stores). On current `main`, persisting a graph with non-ASCII (e.g. CJK) text writes real UTF-8 and round-trips correctly, and there is a regression test (`tests/graph_stores/test_simple_lpg.py::test_persist_utf8_round_trip`). This can likely be closed as a duplicate of #21109.
