### ISSUE TITLE
[Bug]: llamaindex-cli : pydantic_core._pydantic_core.ValidationError: 1 validation error for RagCLI chat_engine

### ISSUE THREAD

**Issue by qiulang** [run-llama/llama_index#15909]
### Bug Description

```
llamaindex-cli rag --files "./data/*.pdf"
Traceback (most recent call last):
  File "/Users/langqiu/anaconda3/bin/llamaindex-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/langqiu/anaconda3/lib/python3.11/site-packages/llama_index/cli/command_line.py", line 276, in main
    args.func(args)
  File "/Users/langqiu/anaconda3/lib/python3.11/site-packages/llama_index/cli/rag/base.py", line 370, in <lambda>
    instance_generator().handle_cli(**vars(args))
    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/langqiu/anaconda3/lib/python3.11/site-packages/llama_index/cli/command_line.py", line 135, in default_rag_cli
    return RagCLI(
           ^^^^^^^
  File "/Users/langqiu/anaconda3/lib/python3.11/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for RagCLI
chat_engine
  Field required [type=missing, input_value={'ingestion_pipeline': In...es/llama_index/rag_cli'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
```

### Version

Version: 0.11.7

### Steps to Reproduce

I just followed https://docs.llamaindex.ai/en/stable/ step by step and I got the error.

**Comment by qiulang** [comment]
I just want to try the cli, so how do I ensure query_pipeline is configured ?

**Comment by qiulang** [comment]
I run your code but got another error, how do I fix it ?

TypeError: FnComponent.__init__() missing 1 required positional argument: 'fn'

**Comment by qiulang** [comment]
@logan-markewich I upgrade to 0.11.8 now I hit another error. So if I don't want to use openai but ollama, what should I do or can I ?

```
llamaindex-cli rag --files "./data/*.pdf"
Retrying llama_index.embeddings.openai.base.aget_embeddings in 0.534294520109774 seconds as it raised APIConnectionError: Connection error..
```
