### ISSUE TITLE
[Bug]: Custom Embedding Model example not working due to Pydantic errors

### ISSUE THREAD

**Issue by larme** [run-llama/llama_index#15923]
### Bug Description

Use [Custom Embedding Model](https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings/#custom-embedding-model) example not working due to Pydantic errors

### Version

0.11.7

### Steps to Reproduce

First install the following requirements:

```
InstructorEmbedding==1.0.1
llama-index==0.11.7
pydantic<2.9
sentence_transformers==2.2.2
```

Then run the following codes:

```python
from typing import Any, List
from InstructorEmbedding import INSTRUCTOR
from llama_index.core.embeddings import BaseEmbedding


class InstructorEmbeddings(BaseEmbedding):
    def __init__(
        self,
        instructor_model_name: str = "hkunlp/instructor-large",
        instruction: str = "Represent the Computer Science documentation or question:",
        **kwargs: Any,
    ) -> None:
        self._model = INSTRUCTOR(instructor_model_name)
        self._instruction = instruction
        super().__init__(**kwargs)

    def _get_query_embedding(self, query: str) -> List[float]:
        embeddings = self._model.encode([[self._instruction, query]])
        return embeddings[0]

    def _get_text_embedding(self, text: str) -> List[float]:
        embeddings = self._model.encode([[self._instruction, text]])
        return embeddings[0]

    def _get_text_embeddings(self, texts: List[str]) -> List[List[float]]:
        embeddings = self._model.encode(
            [[self._instruction, text] for text in texts]
        )
        return embeddings

    async def _aget_query_embedding(self, query: str) -> List[float]:
        return self._get_query_embedding(query)

    async def _aget_text_embedding(self, text: str) -> List[float]:
        return self._get_text_embedding(text)

embed = InstructorEmbeddings()
```

Even just initializing the `InstructorEmbeddings` will give the following errors:

### Relevant Logs/Tracbacks

```shell
/workspace/codes/examples/rag-tutorials/03-custom-llm/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
/workspace/codes/examples/rag-tutorials/03-custom-llm/venv/lib/python3.10/site-packages/sentence_transformers/models/Dense.py:63: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(os.path.join(input_path, 'pytorch_model.bin'), map_location=torch.device('cpu')))
load INSTRUCTOR_Transformer
max_seq_length  512
Traceback (most recent call last):
  File "/workspace/codes/examples/rag-tutorials/03-custom-llm/test_bug.py", line 37, in <module>
    embed = InstructorEmbeddings()
  File "/workspace/codes/examples/rag-tutorials/03-custom-llm/test_bug.py", line 13, in __init__
    self._model = INSTRUCTOR(instructor_model_name)
  File "/workspace/codes/examples/rag-tutorials/03-custom-llm/venv/lib/python3.10/site-packages/pydantic/main.py", line 837, in __setattr__
    if self.__pydantic_private__ is None or name not in self.__private_attributes__:
  File "/workspace/codes/examples/rag-tutorials/03-custom-llm/venv/lib/python3.10/site-packages/pydantic/main.py", line 825, in __getattr__
    return super().__getattribute__(item)  # Raises AttributeError if appropriate
AttributeError: 'InstructorEmbeddings' object has no attribute '__pydantic_private__'. Did you mean: '__pydantic_complete__'?
```

**Comment by larme** [comment]
@dosu That will also result an error like the following:

```
Traceback (most recent call last):
  File "/workspace/codes/examples/rag-tutorials/03-custom-llm/test_bug2.py", line 6, in <module>
    class InstructorEmbeddings(BaseEmbedding):
  File "/workspace/codes/examples/rag-tutorials/03-custom-llm/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 96, in __new__
    private_attributes = inspect_namespace(
  File "/workspace/codes/examples/rag-tutorials/03-custom-llm/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 376, in inspect_namespace
    raise NameError(
NameError: Fields must not use names with leading underscores; e.g., use 'instruction' instead of '_instruction'.
```

Because lama_index migrate to pydantic v2 weeks ago so your knowledge seems to be a little bit outdated
