### ISSUE TITLE
[Bug]: Custom Embeddings Implementation does not work for current llama index verison

### ISSUE THREAD

**Issue by kobiche** [run-llama/llama_index#15927]
### Bug Description

I tried defining a custom embedding class, but the program exits when setting method attributes.
This only happens for llama-index-core version 0.11.7. If I downgrade the version to 0.10.* it works.

### Version

0.11.7

### Steps to Reproduce

```python
from typing import Any, List
from sentence_transformers import SentenceTransformer

from llama_index.core.bridge.pydantic import PrivateAttr
from llama_index.core.embeddings import BaseEmbedding


class SBertEmbeddings(BaseEmbedding):
    _model: SentenceTransformer = PrivateAttr()

    def __init__(
        self,
        model_name: str = "sentence-transformers/all-MiniLM-L6-v2",
        **kwargs: Any,
    ) -> None:
        self._model = SentenceTransformer(model_name)
        super().__init__(**kwargs)

    @classmethod
    def class_name(cls) -> str:
        return "SBertEmbeddings"

    async def _aget_query_embedding(self, query: str) -> List[float]:
        return self._get_query_embedding(query)

    async def _aget_text_embedding(self, text: str) -> List[float]:
        return self._get_text_embedding(text)

    def _get_query_embedding(self, query: str) -> List[float]:
        embeddings = self._model.encode([query], convert_to_numpy=True)
        return embeddings.tolist()

    def _get_text_embedding(self, text: str) -> List[float]:
        embeddings = self._model.encode([text], convert_to_numpy=True)
        return embeddings.tolist()

    def _get_text_embeddings(self, texts: List[str]) -> List[List[float]]:
        embeddings = self._model.encode(texts)
        return embeddings.tolist()


if __name__ == "__main__":
    embed_model = SBertEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
    sample_text = 'hello there'
    output_embeddings = embed_model.get_text_embedding(sample_text)
    print(output_embeddings)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/srv/workspaces/ricardoch/AI/chat_systems/cibai/shared/custom_embedding_service.py", line 58, in <module>
    embed_model = CustomAPIEmbeddings(uri="http://ridmix.cib.de:3000")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/workspaces/ricardoch/AI/chat_systems/cibai/shared/custom_embedding_service.py", line 20, in __init__
    self._uri = uri
    ^^^^^^^^^
  File "/srv/workspaces/ricardoch/venvs/rag_311/lib/python3.11/site-packages/pydantic/main.py", line 820, in __setattr__
    if self.__pydantic_private__ is None or name not in self.__private_attributes__:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/workspaces/ricardoch/venvs/rag_311/lib/python3.11/site-packages/pydantic/main.py", line 808, in __getattr__
    return super().__getattribute__(item)  # Raises AttributeError if appropriate
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CustomAPIEmbeddings' object has no attribute '__pydantic_private__'. Did you mean: '__pydantic_complete__'?
```

**Comment by logan-markewich** [comment]
Just need to swap this


```
def __init__(
        self,
        model_name: str = "sentence-transformers/all-MiniLM-L6-v2",
        **kwargs: Any,
    ) -> None: 
        super().__init__(**kwargs)
        self._model = SentenceTransformer(model_name)
```

I can open a PR in a bit

**Comment by kobiche** [comment]
Ah great! This was an easy fix.
As a side note, I followed this documentation page: https://docs.llamaindex.ai/en/stable/examples/embeddings/custom_embeddings/#custom-embeddings-implementation

**Comment by logan-markewich** [comment]
yea, I just need to update the page in the docs I think 👍🏻
