### ISSUE TITLE
[Bug]: Bedrock Embeddings on eu-west-3 - The provided model identifier is invalid

### ISSUE THREAD

**Issue by Brokray** [run-llama/llama_index#15976]
### Bug Description

An error is raised while trying to use `BedrockEmbedding` with an embedding model on eu-west-3 region. 
The call works flawlessly if the same embedding model is call on us-east-1 region. 

Error received :
```
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: The provided model identifier is invalid.
```

I thought the problem was with the boto3 sdk, I installed it and made the call directly through the invoke method, it worked flawlessly even on eu-west-3.

### Version

0.3.0 (llama_index.embeddings.bedrock)

### Steps to Reproduce

```python
from llama_index.embeddings.bedrock import BedrockEmbedding;

embed_model = BedrockEmbedding(
    model="amazon.titan-embed-image-v1",
    aws_access_key_id="<key>",
    aws_secret_access_key="<access_key>",
    region_name="eu-west-3"
)


embeddings = [embed_model.get_text_embedding("bonjour")]
print(embeddings)
```

Simply run the above python code with proper credentials on an activated model. Changing the region_name to us-east-1 works, however I would like to use the eu-west-3 one.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "callBedrock.py", line 11, in <module>
    embeddings = [embed_model.get_text_embedding("bonjour")]
  File "/Users/ulysse/Library/Caches/pypoetry/virtualenvs/tests-38aH6Wdu-py3.8/lib/python3.8/site-packages/llama_index/core/instrumentation/dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ulysse/Library/Caches/pypoetry/virtualenvs/tests-38aH6Wdu-py3.8/lib/python3.8/site-packages/llama_index/core/base/embeddings/base.py", line 260, in get_text_embedding
    text_embedding = self._get_text_embedding(text)
  File "/Users/ulysse/Library/Caches/pypoetry/virtualenvs/tests-38aH6Wdu-py3.8/lib/python3.8/site-packages/llama_index/core/instrumentation/dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ulysse/Library/Caches/pypoetry/virtualenvs/tests-38aH6Wdu-py3.8/lib/python3.8/site-packages/llama_index/embeddings/bedrock/base.py", line 357, in _get_text_embedding
    return self._get_embedding(text, "text")
  File "/Users/ulysse/Library/Caches/pypoetry/virtualenvs/tests-38aH6Wdu-py3.8/lib/python3.8/site-packages/llama_index/embeddings/bedrock/base.py", line 340, in _get_embedding
    response = self._client.invoke_model(
  File "/Users/ulysse/Library/Caches/pypoetry/virtualenvs/tests-38aH6Wdu-py3.8/lib/python3.8/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/ulysse/Library/Caches/pypoetry/virtualenvs/tests-38aH6Wdu-py3.8/lib/python3.8/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: The provided model identifier is invalid.
```

**Comment by Brokray** [comment]
@dosu 

Found the problem! 
The `model` field does not exists, the library awaits `model_name`. 
However the library sets a default model name which is indeed not available in EU, explaining the behaviour where I thought it was a region problem. 

The code then becomes : 
```
embed_model = BedrockEmbedding(
    model_name=model_name,
    aws_access_key_id="<key>",
    aws_secret_access_key="<access_key>",
    region_name="eu-west-3"
)
```

Suggestions : update the library documentation so that `model_name` is used rather than `model`.

<img width="1119" alt="Screenshot 2024-09-12 at 15 32 26" src="https://github.com/user-attachments/assets/3baf225f-cedf-4f6f-92bb-5c20c8262af0">
