### ISSUE TITLE
[Question]: ModuleNotFoundError: No module named 'llama_index.core.llms.function_calling'

### ISSUE THREAD

**Issue by li-hhhh** [run-llama/llama_index#15999]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

在使用Ollama时报错，显示没有llama_index.core.llms.function_calling模块。
代码：
from llama_index.llms.ollama import Ollama

llm = Ollama(model="llama3.1:latest", request_timeout=60.0)

response = llm.complete("hello?")
print(response)

报错：
Traceback (most recent call last):
  File "/home/huidao/KnowledgeProject/pythonProject/Trimming/Trimming_Embedding/test_codes/test_ollama.py", line 1, in <module>
    from llama_index.llms.ollama import Ollama
  File "/home/huidao/KnowledgeProject/pythonProject/.venv/lib/python3.12/site-packages/llama_index/llms/ollama/__init__.py", line 1, in <module>
    from llama_index.llms.ollama.base import Ollama
  File "/home/huidao/KnowledgeProject/pythonProject/.venv/lib/python3.12/site-packages/llama_index/llms/ollama/base.py", line 18, in <module>
    from llama_index.core.llms.function_calling import FunctionCallingLLM
ModuleNotFoundError: No module named 'llama_index.core.llms.function_calling'

我查看官方文档，pip install llama-index-llms-ollama之后代码可以正常运行，我照官方文档步骤执行依旧有这个问题，所以这个问题具体应该如何解决呢？

**Comment by logan-markewich** [comment]
@li-hhhh What version of llama-index do you have? Like dosu is suggesting, make sure you have the latest version of llama-index-core
