### ISSUE TITLE
[Question]:  AttributeError: 'AgenticLLMWorkflow' object has no attribute '_sessions' 

### ISSUE THREAD

**Issue by Tisha-linkenite** [run-llama/llama_index#16003]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

**Problem :** 
I am working with llama_index, which follows agentic workflow framework. The code works perfectly fine in local environment (windows os) but when hosted on apache server (linux os), strangely it's throws the below, Error : 

Finding it difficult to maintain os-specific project / libraries configurations. 

**Code :** 

**# Agentic LLM Workflow**
```
# Agentic LLM Workflow
class AgenticLLMWorkflow(Workflow):

    final_result = ""
    image_result : Response = None

    def __init__(self, query, llm, tools,query_engine):
        super().__init__()
        self.query = query
        self.llm = llm
        self.tools = tools
        self.query_engine = query_engine

    def get_infographics_function(encoded_image):
        # Decode the base64 string
        image_data = base64.b64decode(encoded_image)

        return send_file(
        BytesIO(image_data),
        mimetype='image/png',
        as_attachment=True,
        download_name='infographic.png'
        )    
    
    async def run(self, query, llm, tools, ctx):
        ctx = Context(session=ctx)
        
```

**/process_research :**  

```
# Route for processing research output
@app.route('/process_research', methods=['POST'])
def process_research():
        query = request.form["user_input"]
        file = request.files.get('pdf-file')

        if file:
        # Create a temporary file to save the uploaded PDF
          with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_file:
            file.save(temp_file.name)
            temp_file_path = temp_file.name

        # Load and index the PDF using the temporary file path
        documents = SimpleDirectoryReader(input_files=[temp_file_path]).load_data()

        print('The document from SimpleDirectoryReader' + '\n')
        for doc in documents:
            text = doc.text
            print(text)

        index = VectorStoreIndex.from_documents(documents, show_progress=True)
        print('The index result from VectorStoreIndex' + '\n' + str(index))

        # Create tools
        query_engine = index.as_query_engine()
        tools = [
            QueryEngineTool(
                query_engine=query_engine,
                metadata=ToolMetadata(
                    name="research_paper",
                    description="{The entire content of the research paper} given by the user",
                ),
            ),
        ]

        # Initialize LLM
        llm = Anthropic(
            model="claude-3-opus-20240229",
            max_tokens=3000,
            max_retries=50
        )

        # Initialize and run workflow
        workflow = AgenticLLMWorkflow(query=query,
            llm=llm,
            tools=tools,
            query_engine=query_engine)
        

        # Store the workflow object in the cache
        workflow_id = 'workflow_1'
        workflow_cache[workflow_id] = workflow
        

        async def run_workflow():

            # Initialize the context of workflow session
            session = workflow._sessions
            ctx = Context(session=session)
            print('workflow timeout before: ' + str(workflow._timeout))
            workflow._timeout = 500
            print('workflow timeout after: ' + str(workflow._timeout))

            # set the query, llm, and tools
            await ctx.set("query", query, make_private=False)
            await ctx.set("llm", llm, make_private=False)
            await ctx.set("tools", tools, make_private=False)

            # Print context contents for debugging
            print("Context contents before running workflow:", ctx._globals)

            print('trying to get the tools from context')
            await ctx.get("tools")
            print('got the tools from context')
            
            # Run the workflow and store the results 
            result = await workflow.run(    
            query=query,
            llm=llm,
            tools=tools,
            ctx=ctx
            )

            # Print result contents for debugging
            print("final result of the workflow: " + result)

            return result

        result = asyncio.run(run_workflow())
        print(result)

        # Extract the research report from the result
        # research_report = result.split("Research Report:")[1].split("Infographic:")[0].strip()

        return jsonify(result)


```

**Project details :** 
- framework : Flask application 
- python version : 3.12.6

**Error :** 
ep 13 08:15:36.577031 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551] \rGenerating embeddings: 100%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88| 14/14 [00:00<00:00, 17.02it/s]
[Fri Sep 13 08:15:36.577339 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551] \rGenerating embeddings: 100%|\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88| 14/14 [00:00<00:00, 17.01it/s]
[Fri Sep 13 08:15:36.577372 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551] 
[Fri Sep 13 08:15:36.585885 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551] The index result from VectorStoreIndex
[Fri Sep 13 08:15:36.585951 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551] <llama_index.core.indices.vector_store.base.VectorStoreIndex object at 0x7fc0a6438a90>
[Fri Sep 13 08:15:36.585964 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551] 
[Fri Sep 13 08:15:36.691352 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551] [2024-09-13 08:15:36,688] ERROR in app: Exception on /process_research [POST]
[Fri Sep 13 08:15:36.691414 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551] Traceback (most recent call last):
[Fri Sep 13 08:15:36.691458 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]   File "/var/www/myapp/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
[Fri Sep 13 08:15:36.691468 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]     response = self.full_dispatch_request()
[Fri Sep 13 08:15:36.691476 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Fri Sep 13 08:15:36.691483 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]   File "/var/www/myapp/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
[Fri Sep 13 08:15:36.691491 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]     rv = self.handle_user_exception(e)
[Fri Sep 13 08:15:36.691499 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Fri Sep 13 08:15:36.691508 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]   File "/var/www/myapp/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
[Fri Sep 13 08:15:36.691516 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]     rv = self.dispatch_request()
[Fri Sep 13 08:15:36.691524 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]          ^^^^^^^^^^^^^^^^^^^^^^^
[Fri Sep 13 08:15:36.691532 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]   File "/var/www/myapp/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
[Fri Sep 13 08:15:36.691541 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
[Fri Sep 13 08:15:36.691549 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Fri Sep 13 08:15:36.691559 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]   File "/var/www/myapp/app.py", line 474, in process_research
[Fri Sep 13 08:15:36.691567 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]     result = asyncio.run(run_workflow())
[Fri Sep 13 08:15:36.691576 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Fri Sep 13 08:15:36.691584 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
[Fri Sep 13 08:15:36.691594 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]     return runner.run(main)
[Fri Sep 13 08:15:36.691603 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]            ^^^^^^^^^^^^^^^^
[Fri Sep 13 08:15:36.691611 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
[Fri Sep 13 08:15:36.691620 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]     return self._loop.run_until_complete(task)
[Fri Sep 13 08:15:36.691629 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Fri Sep 13 08:15:36.691638 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
[Fri Sep 13 08:15:36.691648 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]     return future.result()
[Fri Sep 13 08:15:36.691657 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]            ^^^^^^^^^^^^^^^
[Fri Sep 13 08:15:36.691665 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]   File "/var/www/myapp/app.py", line 443, in run_workflow
[Fri Sep 13 08:15:36.691674 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]     session = workflow._sessions
[Fri Sep 13 08:15:36.691684 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551]               ^^^^^^^^^^^^^^^^^^
[Fri Sep 13 08:15:36.691716 2024] [wsgi:error] [pid 44419:tid 44431] [remote 103.194.158.12:52551] AttributeError: 'AgenticLLMWorkflow' object has no attribute '_sessions'

**Comment by logan-markewich** [comment]
@Tisha-linkenite tbh, the way you are using a workflow is not documented anywhere. I'm really curious why you took this approach? 

In any cases, the sessions variable was removed, and tbh your usage looks like it won't work anymore.

I'm guessing your local and remote machines have different versions of `llama-index-core` ?

**Comment by Tisha-linkenite** [comment]
The local and remote machines have the same versions of` llama-index-core` that is `0.11.1`

**Comment by logan-markewich** [comment]
@Tisha-linkenite hmmm, well if that's actually true, both machines should run the code.

If you want to extra confirm, you can open the installed package in a text editor. Specifically, `llama_index/core/workflows/workflow.py` -- you should see code that aligns with this snapshot of v0.11.1
https://github.com/run-llama/llama_index/blob/eecc1bc0abfdc1a6e5e5b6f50d43a46cdf4fc5d0/llama-index-core/llama_index/core/workflow/workflow.py#L46

**Comment by logan-markewich** [comment]
But also, just my two cents, if you want stable code, i wouldn't be accessing so many private variables and methods 😅

**Comment by Tisha-linkenite** [comment]
Yeah, I agree with you logan. Will work on the required changes in the approach
