### ISSUE TITLE
[Bug]: TypeError: RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'

### ISSUE THREAD

**Issue by bsyg** [run-llama/llama_index#16022]
### Bug Description

Hello, I recently followed your excellent tutorial on https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/cookbooks/GraphRAG_v2.ipynb and https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/llm/xinference_local_deployment.ipynb, run successfully on MacOS, but report this erorr on CentOS. 

### Version

0.11.0

### Steps to Reproduce

# 加载文档
documents=load_data()
# 创建nodes
nodes=create_nodes(documents)

# 使用 GraphRAGExtractor 和 GraphRAGStore 构建 ProperGraphIndex
kg_extractor=build_proper_graph_index.kg_extractor

# Neo4J 设置
graph_store=neo4j_store.graph_store

# 将文档nodes生成知识图谱
index = PropertyGraphIndex(
    nodes=nodes,
    embed_model=embed_model,
    kg_extractors=[kg_extractor],
    property_graph_store=graph_store,
    show_progress=True,
)

# 使用社区检测算法对图中的相关节点nodes进行分组,并使用LLM为每个分组生成摘要
index.property_graph_store.build_communities()

### Relevant Logs/Tracbacks

```shell
/root/anaconda3/envs/xiaopai/bin/python /home/ai_xiaopai_xieyexin/backend/start_files_handle.py
['/home/ai_xiaopai_xieyexin/backend', '/root/anaconda3/envs/xiaopai/lib/python311.zip', '/root/anaconda3/envs/xiaopai/lib/python3.11', '/root/anaconda3/envs/xiaopai/lib/python3.11/lib-dynload', '/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages', '/home/ai_xiaopai_xieyexin']
/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_uid" in Xinference has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/pydantic/_internal/_fields.py:132: UserWarning: Field "model_description" in Xinference has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
WARNING 09-14 15:44:53 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The procedure has a deprecated field. ('config' used by 'apoc.meta.graphSample' is deprecated.)} {position: line: 1, column: 1, offset: 0} for query: "CALL apoc.meta.graphSample() YIELD nodes, relationships RETURN nodes, [rel in relationships | {name:apoc.any.property(rel, 'type'), count: apoc.any.property(rel, 'count')}] AS relationships"
Neo4j Graph Store Created
5
Extracting paths from text:   0%|                                                                                                          | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ai_xiaopai_xieyexin/backend/start_files_handle.py", line 31, in <module>
    index = PropertyGraphIndex(
            ^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/indices/property_graph/base.py", line 134, in __init__
    super().__init__(
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 77, in __init__
    index_struct = self.build_index_from_nodes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 185, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **build_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/indices/property_graph/base.py", line 328, in _build_index_from_nodes
    nodes = self._insert_nodes(nodes or [])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/indices/property_graph/base.py", line 198, in _insert_nodes
    nodes = asyncio.run(
            ^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 137, in arun_transformations
    nodes = await transform.acall(nodes, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai_xiaopai_xieyexin/backend/code/graph_rag/graph_rag_extractor.py", line 147, in acall
    return await run_jobs(
           ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 146, in run_jobs
    results = await tqdm_asyncio.gather(*pool_jobs, desc=desc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
           ^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/asyncio/tasks.py", line 615, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 139, in worker
    return await job
           ^^^^^^^^^
  File "/home/ai_xiaopai_xieyexin/backend/code/graph_rag/graph_rag_extractor.py", line 101, in _aextract
    llm_response = await self.llm.apredict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/llm.py", line 668, in apredict
    response = await self.acomplete(formatted_prompt, formatted=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 334, in wrapped_async_llm_predict
    f_return_val = await f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/custom.py", line 68, in acomplete
    return self.complete(prompt, formatted=formatted, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 429, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/llms/xinference/base.py", line 247, in complete
    response_text = self._generator.chat(
                    ^^^^^^^^^^^^^^^^^^^^^
TypeError: RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'
Extracting paths from text:   0%|                                                                                                          | 0/5 [00:01<?, ?it/s]
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<tqdm_asyncio.gather.<locals>.wrap_awaitable() done, defined at /root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py:75> exception=TypeError("RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'")>
Traceback (most recent call last):
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 139, in worker
    return await job
           ^^^^^^^^^
  File "/home/ai_xiaopai_xieyexin/backend/code/graph_rag/graph_rag_extractor.py", line 101, in _aextract
    llm_response = await self.llm.apredict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/llm.py", line 668, in apredict
    response = await self.acomplete(formatted_prompt, formatted=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 334, in wrapped_async_llm_predict
    f_return_val = await f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/custom.py", line 68, in acomplete
    return self.complete(prompt, formatted=formatted, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 429, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/llms/xinference/base.py", line 247, in complete
    response_text = self._generator.chat(
                    ^^^^^^^^^^^^^^^^^^^^^
TypeError: RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<tqdm_asyncio.gather.<locals>.wrap_awaitable() done, defined at /root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py:75> exception=TypeError("RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'")>
Traceback (most recent call last):
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 139, in worker
    return await job
           ^^^^^^^^^
  File "/home/ai_xiaopai_xieyexin/backend/code/graph_rag/graph_rag_extractor.py", line 101, in _aextract
    llm_response = await self.llm.apredict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/llm.py", line 668, in apredict
    response = await self.acomplete(formatted_prompt, formatted=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 334, in wrapped_async_llm_predict
    f_return_val = await f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/custom.py", line 68, in acomplete
    return self.complete(prompt, formatted=formatted, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 429, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/llms/xinference/base.py", line 247, in complete
    response_text = self._generator.chat(
                    ^^^^^^^^^^^^^^^^^^^^^
TypeError: RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<tqdm_asyncio.gather.<locals>.wrap_awaitable() done, defined at /root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py:75> exception=TypeError("RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'")>
Traceback (most recent call last):
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 139, in worker
    return await job
           ^^^^^^^^^
  File "/home/ai_xiaopai_xieyexin/backend/code/graph_rag/graph_rag_extractor.py", line 101, in _aextract
    llm_response = await self.llm.apredict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/llm.py", line 668, in apredict
    response = await self.acomplete(formatted_prompt, formatted=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 334, in wrapped_async_llm_predict
    f_return_val = await f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/custom.py", line 68, in acomplete
    return self.complete(prompt, formatted=formatted, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 429, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/llms/xinference/base.py", line 247, in complete
    response_text = self._generator.chat(
                    ^^^^^^^^^^^^^^^^^^^^^
TypeError: RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<tqdm_asyncio.gather.<locals>.wrap_awaitable() done, defined at /root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py:75> exception=TypeError("RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'")>
Traceback (most recent call last):
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 139, in worker
    return await job
           ^^^^^^^^^
  File "/home/ai_xiaopai_xieyexin/backend/code/graph_rag/graph_rag_extractor.py", line 101, in _aextract
    llm_response = await self.llm.apredict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/llm.py", line 668, in apredict
    response = await self.acomplete(formatted_prompt, formatted=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 291, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 334, in wrapped_async_llm_predict
    f_return_val = await f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/custom.py", line 68, in acomplete
    return self.complete(prompt, formatted=formatted, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 261, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 429, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/xiaopai/lib/python3.11/site-packages/llama_index/llms/xinference/base.py", line 247, in complete
    response_text = self._generator.chat(
                    ^^^^^^^^^^^^^^^^^^^^^
TypeError: RESTfulChatModelHandle.chat() got an unexpected keyword argument 'prompt'
```

**Comment by bsyg** [comment]
llama-index                             0.11.0
llama-index-core                        0.11.0.post1
llama-index-graph-stores-neo4j          0.3.2
llama-index-llms-xinference             0.2.2
graspologic                             3.3.0
graspologic-native                      1.2.1
numpy                                   1.24.4
scipy                                   1.12.0

**Comment by bsyg** [comment]
I find the code is called in llama_index/llms/xinference/base.py line 193  uses prompt by message converted：

   @llm_chat_callback()
    def chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponse:
        assert self._generator is not None
        prompt = messages[-1].content if len(messages) > 0 else ""
        history = [xinference_message_to_history(message) for message in messages[:-1]]
        response_text = self._generator.chat(
            prompt=prompt,
            chat_history=history,
            generate_config={
                "stream": False,
                "temperature": self.temperature,
                "max_tokens": self.max_tokens,
            },
        )["choices"][0]["message"]["content"]
        return ChatResponse(
            message=ChatMessage(
                role=MessageRole.ASSISTANT,
                content=response_text,
            ),
            delta=None,
        )

but in llama_index/core/llms/custom.py line 49, use message:
    @llm_chat_callback()
    async def achat(
        self,
        messages: Sequence[ChatMessage],
        **kwargs: Any,
    ) -> ChatResponse:
        return self.chat(messages, **kwargs)

So, I guess that some logical calls is running error within llama_index. 
Please contact a human engineer to solve the problem, thank you.

**Comment by bsyg** [comment]
@dosu Hi, is there progress on this issue so far?
LLM uses llama3.1-instruct-8B, which is the type of chat LLM.
