### ISSUE TITLE
[Bug]: ValueError - Invalid format specifier

### ISSUE THREAD

**Issue by nbahar-intel** [run-llama/llama_index#16202]
### Bug Description

Using `index.as_chat_engine()`, one of the assistant returned prompts contains a formatted python code.
It seems like `_get_available_chunk_size` is failing on formatting that message with:
`ValueError('Invalid format specifier')`.

EDIT: I've updated steps to reproduce.
Is there anyway to avoid string formatting altogether?

### Version

0.11.13

### Steps to Reproduce
Mentioned in the comment below: https://github.com/run-llama/llama_index/issues/16202#issuecomment-2372894858

**Comment by nbahar-intel** [comment]
I was able to create a simplified example, outside of llama index:

```python
    args = {'var': '{var}', 'mem': '{mem}', 'reg': '{reg}'}
    content = "{var: SomeValue for var in x87_registers}"
    content.format(**args)
```
Should raise:
```
Traceback (most recent call last):
  File "stest.py", line 9, in <module>
    main()
  File "stest.py", line 6, in main
    content.format(**args)
ValueError: Invalid format specifier
```

**Comment by nbahar-intel** [comment]
I was able to create a simplified example, outside of llama index:

```python
    args = {'var': '{var}', 'mem': '{mem}', 'reg': '{reg}'}
    content = "{var: SomeValue for var in some_dict.items()}"
    content.format(**args)
```
Should raise:
```
Traceback (most recent call last):
  File "stest.py", line 9, in <module>
    main()
  File "stest.py", line 6, in main
    content.format(**args)
ValueError: Invalid format specifier
```

**Comment by nbahar-intel** [comment]
In case someone asks, the original string also had `{var}` in it for some formatting
