### ISSUE TITLE
[Bug]: 'OpenAIMultiModal' object has no attribute '_update_tool_calls'

### ISSUE THREAD

**Issue by dinoelT** [run-llama/llama_index#16297]
### Bug Description

Hello,
I am trying to get the output of the model gpt4-o model where it can be a message to the user(streamed) or a function call.
I can't know beforehand if it's going to be a function call, so both should be streamed and I want to implement the logic on top of that. When I include the tools parameter in the stream_chat call, I get the following error:
'OpenAIMultiModal' object has no attribute '_update_tool_calls'

I use python 3.12 on windows 10.

These are the packages installed:

```
llama-index==0.11.14
llama-index-agent-openai==0.3.4
llama-index-cli==0.3.1
llama-index-core==0.11.14
llama-index-embeddings-openai==0.2.5
llama-index-indices-managed-llama-cloud==0.4.0
llama-index-legacy==0.9.48.post3
llama-index-llms-gemini==0.3.5
llama-index-llms-openai==0.2.9
llama-index-multi-modal-llms-gemini==0.3.1
llama-index-multi-modal-llms-openai==0.2.1
llama-index-program-openai==0.2.0
llama-index-question-gen-openai==0.2.0
llama-index-readers-file==0.2.2
llama-index-readers-llama-parse==0.3.0
llama-index-vector-stores-chroma==0.2.0
```
My test code is:

```
from dotenv import load_dotenv
import os
from pydantic import BaseModel

from llama_index.multi_modal_llms.openai import OpenAIMultiModal
from llama_index.core.tools import FunctionTool, ToolMetadata
from llama_index.core.types import ChatMessage 

load_dotenv()

llm = OpenAIMultiModal(
    model="gpt-4o",
    api_key=os.getenv("OPENAI_API_KEY"),
)

def get_available_slots(date: str):
    return "Available slots: 10:00, 11:00, 12:00"

class NoParams(BaseModel):
    pass

DATE_PICKER_TOOLS = [
    FunctionTool(
        fn=get_available_slots,
        metadata=ToolMetadata(
            name="get_available_slots",
            description="Get available slots.",
            fn_schema=NoParams,
        ),
    )
]

r = llm.stream_chat(
    messages=[
        ChatMessage(
            role="user",
            content="What are the slots available?",
        ),
    ],
    tools=[t.metadata.to_openai_tool() for t in DATE_PICKER_TOOLS],
)

for chunk in r:
    print(chunk, end="")


````

I'm not sure if this is a bug, if I misunderstand something or if it's just a feature that is not supported(in this case maybe including an error message would be cool).
Thank you very much! 

### Version

0.11.14

### Steps to Reproduce

Make a OpenAIMultiModal.stream_chat call with the tools parameter present

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\LeonidTanas\source\onboarding_bot\backend\llama_test.py", line 43, in <module>
    for chunk in r:
  File "C:\Users\LeonidTanas\source\onboarding_bot\backend\.venv\Lib\site-packages\llama_index\core\llms\callbacks.py", line 186, in wrapped_gen
    for x in f_return_val:
  File "C:\Users\LeonidTanas\source\onboarding_bot\backend\.venv\Lib\site-packages\llama_index\core\llms\callbacks.py", line 186, in wrapped_gen
    for x in f_return_val:
  File "C:\Users\LeonidTanas\source\onboarding_bot\backend\.venv\Lib\site-packages\llama_index\multi_modal_llms\openai\base.py", line 318, in gen
    tool_calls = self._update_tool_calls(tool_calls, delta.tool_calls)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LeonidTanas\source\onboarding_bot\backend\.venv\Lib\site-packages\pydantic\main.py", line 853, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'OpenAIMultiModal' object has no attribute '_update_tool_calls'
```

**Comment by logan-markewich** [comment]
Yea the openai multimodal class isn't updated to work with tools really 

We have some pending backlog work to merge this multi-modal class into the normal OpenAI class -- maintaining nearly duplicate versions of the same thing hasn't been easy

**Comment by logan-markewich** [comment]
In this case, it's a bug and the openai multimodal class is just missing a function
