### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Shubh789da** [run-llama/llama_index#16387]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using PandasInstructionParser(df_1) but its throwing effor as df_1 not defined how to over come that?

I am using 2 query pipeline for 2 different data one has dataframe as df that is running fine but this is causing problem

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_index/experimental/query_engine/pandas/output_parser.py", line 61, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
  File "/usr/local/lib/python3.10/dist-packages/llama_index/experimental/exec_utils.py", line 159, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
  File "<string>", line 1, in <module>
NameError: name 'df_1' is not defined

**Comment by Shubh789da** [comment]
@dosu

how to Check Variable Scope if df_1 is in correct scope?
