### ISSUE TITLE
[Question]: why generate these error? The evironment is gpt4o.

### ISSUE THREAD

**Issue by 912100012** [run-llama/llama_index#16399]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

17:43:57 Encountered httpx.HTTPStatusError
==============================
Traceback (most recent call last):
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\callbacks\utils.py", line 31, in wrapper
    callback_manager = getattr(self, callback_manager_attr)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\pydantic\main.py", line 828, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'FnAgentWorker' object has no attribute 'callback_manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\openai\_base_client.py", line 1020, in _request
    response.raise_for_status()
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\httpx\_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://use.52apikey.cn/v1/chat/completions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
17:43:57 Not retrying
==============================

17:43:57 Re-raising status error
==============================

Traceback (most recent call last):
  File "F:\Project\pythonWorkspace\text2Sql-Demo\demo\CustomAgent\CustomAgent.py", line 240, in <module>
    response = agent.chat("Which countries are each city from?")
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\callbacks\utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\agent\runner\base.py", line 647, in chat
    chat_response = self._chat(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\agent\runner\base.py", line 579, in _chat
    cur_step_output = self._run_step(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\agent\runner\base.py", line 412, in _run_step
    cur_step_output = self.agent_worker.run_step(step, task, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\callbacks\utils.py", line 38, in wrapper
    return func(self, *args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\agent\custom\simple_function.py", line 151, in run_step
    agent_response, is_done = self._run_step(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\agent\custom\simple_function.py", line 119, in _run_step
    current_state, is_done = self.fn(state)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\demo\CustomAgent\CustomAgent.py", line 199, in retry_agent_fn
    response_eval = llm_program(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\program\function_program.py", line 202, in __call__
    agent_response = self._llm.predict_and_call(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\llms\function_calling.py", line 182, in predict_and_call
    response = self.chat_with_tools(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\llms\function_calling.py", line 48, in chat_with_tools
    response = self.chat(**chat_kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\core\llms\callbacks.py", line 173, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\llms\openai\base.py", line 342, in chat
    return chat_fn(messages, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\llms\openai\base.py", line 103, in wrapper
    return retry(f)(self, *args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\tenacity\__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\tenacity\__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\tenacity\__init__.py", line 376, in iter
    result = action(retry_state)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\tenacity\__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "E:\Python\Python39\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "E:\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\tenacity\__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\llama_index\llms\openai\base.py", line 416, in _chat
    response = client.chat.completions.create(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\openai\resources\chat\completions.py", line 668, in create
    return self._post(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\openai\_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\openai\_base_client.py", line 937, in request
    return self._request(
  File "F:\Project\pythonWorkspace\text2Sql-Demo\venv\lib\site-packages\openai\_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'Function call is not supported for this model. (request id: 20241007174352788824917HvqAPjz0)', 'type': 'upstream_error', 'param': '400', 'code': 'bad_response_status_code'}}

**Comment by logan-markewich** [comment]
This is coming directly from openai -- not sure how you setup your code to produce this error
