### ISSUE TITLE
[Bug]: Common Readers (such as `CSVReader`) Cannot Be Used with ReaderConfig + IngestionPipeline

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#16490]
### Bug Description

`ReaderConfig` expects a `BasePydanticReader` while all the readers supported by `SimpleDirectoryReader` (as described here) are `BaseReader`.  Since `ReaderConfig` is the required type for `IngestionPipeline.readers`, it is not possible to use a common type, such as `CSVReader` in `IngestionPipeline`.

### Version

0.11.17

### Steps to Reproduce

```python
from llama_index.core.readers import ReaderConfig
from llama_index.readers.file import CSVReader

ReaderConfig(
    reader=CSVReader
)
```

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[13], line 1
----> 1 ReaderConfig(
      2     reader=CSVReader
      3 )

File ~/Library/Caches/pypoetry/virtualenvs/.../lib/python3.11/site-packages/pydantic/main.py:212, in BaseModel.__init__(self, **data)
    210 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    211 __tracebackhide__ = True
--> 212 validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
    213 if self is not validated_self:
    214     warnings.warn(
    215         'A custom validator is returning a value other than `self`.\n'
    216         "Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.\n"
    217         'See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.',
    218         category=None,
    219     )

ValidationError: 1 validation error for ReaderConfig
reader
  Input should be a valid dictionary or instance of BasePydanticReader [type=model_type, input_value=<llama_index.readers.file...r object at 0x32f3e14d0>, input_type=CSVReader]
    For further information visit https://errors.pydantic.dev/2.9/v/model_type
```

**Comment by logan-markewich** [comment]
@brycecf in all honesty, I should probably remove ReaderConfig lol

its not documented anywhere (to my knowledge)

It originally existed to enable uploading reader configs to llama-cloud, but we abandoned that idea. So this should likely be removed at some point

On the other hand, the base pydantic reader class Is helpful, but just been converting them piece-by-piece as needed for llama-cloud (feel free to convert any though!)

**Comment by frk-ti8m** [comment]
The issue is still unresolved, since as of now it is not possible to use reader with the ingestion pipeline, as described in the original issue. I run into a related issue when trying to use the IngestionPipeline with a custom subclass of base pydantic reader with the signature

```python
class MyReader(BasePydanticReader):
    ...
```

The concrete error message is:

```
  File "/.../src/indexer/ingest/pipeline.py", line 29, in <module>
    website_reader = ReaderConfig(
                     ^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ReaderConfig
reader
  Input should be a valid dictionary or instance of BasePydanticReader [type=model_type, input_value=<class 'src.indexer.reade...er.MyReader'>, input_type=ModelMetaclass]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
```

is there any plan to fix this? This is potentially relevant for extending docstore and caching mechanisms of the ingestion pipeline to the reader.
