### ISSUE TITLE
[Bug]: Unable to use multi-process in llamaindex

### ISSUE THREAD

**Issue by main-2983** [run-llama/llama_index#16508]
### Bug Description

I ran the `SimpleDirectoryReader` with `num_workers` > 1, wait for a few seconds then the Logs appear like below

### Version

0.11.17

### Steps to Reproduce

This simple code snippet below 
```
from llama_index.core import SimpleDirectoryReader


documents = SimpleDirectoryReader(input_dir="data/markdown").load_data(
    show_progress=True, num_workers=4
)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Code\PyCharm\Projects\luna-tax-copilot\misc.py", line 4, in <module>
    documents = SimpleDirectoryReader(input_dir="data/markdown").load_data(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\site-packages\llama_index\core\readers\file\base.py", line 674, in load_data
    with multiprocessing.get_context("spawn").Pool(num_workers) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\pool.py", line 215, in __init__
    self._repopulate_pool()
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "E:\Code\Miniconda\conda\envs\aibyte\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
```

**Comment by GhostDog98** [comment]
PS. I've found this is also necessary on linux systems (or at least mine).
