### ISSUE TITLE
[Bug]: My inner workflow faces a timeout error

### ISSUE THREAD

**Issue by tituslhy** [run-llama/llama_index#16549]
### Bug Description

Despite specifying a generous timeout limit for all my workflows, my inner workflow of my nested workflow always times out within 10 seconds once deployed on LlamaDeploy.
1. This error did not exist on Jupyter Notebooks
2. When I pinged the inner workflow directly using LlamaDeployClient I get no timeout error

Which means that the timeout error only happens when I ping the outer workflow which then routes to the inner workflow.

### Version

0.11.17

### Steps to Reproduce

Deployment of core
```
from llama_deploy import (
    deploy_core,
    ControlPlaneConfig,
)
from llama_deploy.message_queues.simple import (
    SimpleMessageQueueConfig
)
control_plane_config = ControlPlaneConfig()
message_queue_config = SimpleMessageQueueConfig()

if __name__ == "__main__":
    import asyncio
    
    asyncio.run(
        deploy_core(
            control_plane_config = control_plane_config,
            message_queue_config=message_queue_config,
            disable_control_plane=False,
            disable_message_queue=False,
        )
    )
```

Deployment of workflow
```
from llama_index.core.workflow import Workflow, StartEvent, StopEvent, step
import asyncio
from llama_deploy import (
    WorkflowServiceConfig,
    ControlPlaneConfig,
    deploy_workflow,
)

class InnerWorkflow(Workflow):
    @step()
    async def run_step(self, ev: StartEvent) -> StopEvent:
        result = ... #some long step here
        return StopEvent(result=str(result))


class OuterWorkflow(Workflow):
    @step()
    async def run_step(
        self, ev: StartEvent, inner: InnerWorkflow
    ) -> StopEvent:
        arg1 = ev.get("arg1")
        result = await inner.run(arg1=arg1)

        return StopEvent(result=str(result))


inner = InnerWorkflow(timeout=1200.0,verbose=True)
outer = OuterWorkflow(timeout=6000.0, verbose = True)
outer.add_workflows(inner=InnerWorkflow())

async def main():
    inner_task = asyncio.create_task(
        deploy_workflow(
            inner,
            WorkflowServiceConfig(
                host="127.0.0.1", port=8003, service_name="inner"
            ),
            ControlPlaneConfig(),
        )
    )

    outer_task = asyncio.create_task(
        deploy_workflow(
            outer,
            WorkflowServiceConfig(
                host="127.0.0.1", port=8002, service_name="outer"
            ),
            ControlPlaneConfig(),
        )
    )

    await asyncio.gather(inner_task, outer_task)


if name == "main":
    import asyncio
    asyncio.run(main())
```

Calling of workflow
```
from llama_deploy import AsyncLlamaDeployClient, ControlPlaneConfig
control_plane_config = ControlPlaneConfig()
client = AsyncLlamaDeployClient(control_plane_config)
session = await client.create_session()
result = await session.run(
   "outer"
   query = ...
)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/app/tlim2/anaconda3/envs/llamaindex/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 281, in handle_future_result
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/app/tlim2/anaconda3/envs/llamaindex/lib/python3.12/site-packages/llama_index/core/workflow/workflow.py", line 380, in _run_workflow
    raise WorkflowTimeoutError(msg)
llama_index.core.workflow.errors.WorkflowTimeoutError: Operation timed out after 10.0 seconds
```

**Comment by tituslhy** [comment]
Sorry I made a typo. This was how I added the inner workflow

```
inner = InnerWorkflow(timeout=1200.0,verbose=True)
outer = OuterWorkflow(timeout=6000.0, verbose = True)
outer.add_workflows(inner=inner)
```

**Comment by tituslhy** [comment]
I went to the raw file of LlamaIndex's `workflow.py` on my machine and changed the timeout settings. It works now. This means that for some reason, the nested workflow is still only calling on a default setting instead of registering my provided timeout setting.
