### ISSUE TITLE
[Bug]: Qdrant VectorStore as QueryEngine not Working

### ISSUE THREAD

**Issue by TJKlein** [run-llama/llama_index#16574]
### Bug Description

I keep getting a pydantic error when trying to retrieve from the vector DB from an existing collection. I can see that the points are retrieved from the Qdrant vectorDB.

```bash
pydantic_core._pydantic_core.ValidationError: 1 validation error for TextNode
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
``

### Version

0.11.18

### Steps to Reproduce

```python
from llama_index.core import VectorStoreIndex
import qdrant_client
import llama_index
from llama_index.embeddings.openai import OpenAIEmbedding

client = qdrant_client.QdrantClient(
url="XXXXXXX",
api="XXXXXXX",
)

vector_store = llama_index.vector_stores.qdrant.QdrantVectorStore(
    "my_collection",
    client=client,)

query_engine = VectorStoreIndex.from_vector_store(vector_store=vector_store,embed_model=OpenAIEmbedding(model="text-embedding-ada-002")).as_query_engine()

response = query_engine.query("Why does this query not work?")
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/XXXXXX/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/XXXXXX/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/XXXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/Users/XXXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/Users/XXXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/XXXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/Users/XXXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/Users/XXXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/Users/XXXXXX/Notebooks/test_llamaindex.py", line 173, in <module>
    response = query_engine.query("Why does this query not work?")
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/base/base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 177, in _query
    nodes = self.retrieve(query_bundle)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 132, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/base/base_retriever.py", line 245, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 103, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 180, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/vector_stores/qdrant/base.py", line 842, in query
    return self.parse_to_query_result(response)
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/llama_index/vector_stores/qdrant/base.py", line 997, in parse_to_query_result
    node = TextNode(
  File "/Users/XXXXXX/miniconda3/lib/python3.9/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for TextNode
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
```

**Comment by logan-markewich** [comment]
@TJKlein did you populate the vector store with llama-index? 

If not, you'll need to set `text_key` in the constructor to point to what field in qdrant has the chunk text

**Comment by logan-markewich** [comment]
Actually, got my vector stores mixed up, it's currently hardcoded 
https://github.com/run-llama/llama_index/blob/3e3b6840b35f3ecb40916335ffbd92e7d3457ce8/llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py#L999

**Comment by logan-markewich** [comment]
Would need a pr to set a dynamic field (along with the other fields there)

**Comment by TJKlein** [comment]
No, it was not populated with LlamaIndex but with LangChain. Let's why it differs from text. I guess the same issue applies with additional fields such as meta-data that is stored together with the text field?

**Comment by TJKlein** [comment]
By the way, when I want to do a hybrid retrieval (even when changing the hard-coded name of the text field), it also does not work but gives a different error.

```bash
Traceback (most recent call last):
  File "/Users/XXXXX/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/XXXXX/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/Users/XXXXX/Notebooks/test_llamaindex.py", line 175, in <module>
    response = query_engine.query("What does this query not work")
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/base/base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 177, in _query
    nodes = self.retrieve(query_bundle)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 132, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/base/base_retriever.py", line 245, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 103, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 180, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/vector_stores/qdrant/base.py", line 819, in query
    response = self._client.search_batch(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/qdrant_client.py", line 285, in search_batch
    return self._client.search_batch(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/qdrant_remote.py", line 451, in search_batch
    self.http.points_api.search_batch_points(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/http/api/points_api.py", line 1752, in search_batch_points
    return self._build_for_search_batch_points(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/http/api/points_api.py", line 716, in _build_for_search_batch_points
    return self.api_client.request(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 79, in request
    return self.send(request, type_)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 102, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for text-dense are not specified in config"},"time":0.000188279}
```

**Comment by logan-markewich** [comment]
You can't do hybrid retrieval unless you created the index with sparse params initially 

And yes, if you populated with langchain, probably none of the fields are lining up (text, metadata, etc.) -- either recreate with llama-index, or opening a PR to add options for what keys to load from would be helpful!

**Comment by TJKlein** [comment]
> You can't do hybrid retrieval unless you created the index with sparse params initially
> 
> And yes, if you populated with langchain, probably none of the fields are lining up (text, metadata, etc.) -- either recreate with llama-index, or opening a PR to add options for what keys to load from would be helpful!

Yes, I also created a collection with sparse vectors to do that experiment.
