### ISSUE TITLE
[Bug]: Hybrid Retrieval not Working with QdrantVectorDatabase with LangChain Populated Database

### ISSUE THREAD

**Issue by TJKlein** [run-llama/llama_index#16587]
### Bug Description

When trying to do a hybrid search with QdrantVectorDatabase (which was populated by LangChain), I get an error concerning the configuration of **text-dense**

```bash
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for text-dense are not specified in config"},"time":0.000483735}'
```

### Version

0.11.18

### Steps to Reproduce

```python
from llama_index.core import VectorStoreIndex
import qdrant_client
import llama_index
from llama_index.embeddings.openai import OpenAIEmbedding

client = qdrant_client.QdrantClient(
url="XXXXXXX",
api="XXXXXXX",
enable_hybrid=True,
    fastembed_sparse_model= "Qdrant/bm25",
   mode=VectorStoreQueryMode.HYBRID
)

vector_store = llama_index.vector_stores.qdrant.QdrantVectorStore(
    "my_collection",
    client=client,)

index = VectorStoreIndex.from_vector_store(vector_store=vector_store,embed_model=OpenAIEmbedding(model="text-embedding-ada-002"))
hybrid_retriever = VectorIndexRetriever(
    index=index,
    vector_store_query_mode=VectorStoreQueryMode.HYBRID,
    sparse_top_k=5,
    similarity_top_k=5,
    alpha=0.1,
)

nodes = hybrid_retriever.retrieve("What is the best way to learn programming?")
```

### Relevant Logs/Tracbacks

```shell
Fetching 29 files: 100%|████| 29/29 [00:00<00:00, 19542.87it/s]
Traceback (most recent call last):
  File "/Users/XXXXX/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/XXXXX/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/Users/XXXXX/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/Users/XXXXX/Notebooks/test_llamaindex.py", line 184, in <module>
    nodes = hybrid_retriever.retrieve("What is the best way to learn programming?")
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/base/base_retriever.py", line 245, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/instrumentation/dispatcher.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 103, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 180, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/llama_index/vector_stores/qdrant/base.py", line 749, in query
    sparse_response = self._client.search_batch(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/qdrant_client.py", line 285, in search_batch
    return self._client.search_batch(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/qdrant_remote.py", line 451, in search_batch
    self.http.points_api.search_batch_points(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/http/api/points_api.py", line 1752, in search_batch_points
    return self._build_for_search_batch_points(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/http/api/points_api.py", line 716, in _build_for_search_batch_points
    return self.api_client.request(
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 79, in request
    return self.send(request, type_)
  File "/Users/XXXXX/miniconda3/lib/python3.9/site-packages/qdrant_client/http/api_client.py", line 102, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for text-dense are not specified in config"},"time":0.000483735}'
```

**Comment by TJKlein** [comment]
The vectors show up correctly configured in the Qdrant dashboard, named *text-dense* and *text-sparse*, with the correct properties (dimensionality).

**Comment by logan-markewich** [comment]
Pass in the configs

https://github.com/run-llama/llama_index/blob/f633e7393aaa3f36ef518429672b931b1e3bdae8/llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py#L142

There's a kwarg in the constructor for both the sparse and dense configs. These are just qdramt objects, you can look at their docs or our source code for what they should look like

Normally, you wouldn't have to do that, if the index was populated by llama-index.

**Comment by logan-markewich** [comment]
(Which in our source code, is over here https://github.com/run-llama/llama_index/blob/f633e7393aaa3f36ef518429672b931b1e3bdae8/llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py#L619)

**Comment by TJKlein** [comment]
I added the configs, but unfortunately it does not change anything. Same error:

```python
vector_store = llama_index.vector_stores.qdrant.QdrantVectorStore(
    "my_collection",
    client=client,

# added configs
    dense_config= {
        "text-dense": models.VectorParams(
            size=1536,  # openai vector size
            distance=models.Distance.COSINE,
        )},
    sparse_config= {
        "text-sparse": models.SparseVectorParams(
            index=models.SparseIndexParams(
                on_disk=False,
            )
        )},
)
```
