### ISSUE TITLE
[Bug]: Attempted import error: 'PineconeVectorStore' is not exported from 'llamaindex'

### ISSUE THREAD

**Issue by GiveMeMoreLoansZeroInterest** [run-llama/llama_index#16616]
### Bug Description

Attempting to construct PineconeVectorStore and running into an issue. On Typescript. Any help is much appreciated!

Here's my code:
```
import {
  Document,
  VectorStoreIndex,
  OpenAI,
  Settings,
  PineconeVectorStore
} from "llamaindex";

const pineconeVectorStore = new PineconeVectorStore({
  indexName: "defiai"
});
```

Here's my error:

```
./src/app/api/generate-answer/route.ts
Attempted import error: 'PineconeVectorStore' is not exported from 'llamaindex' (imported as 'PineconeVectorStore').

Import trace for requested module:
./src/app/api/generate-answer/route.ts

 ✓ Linting and checking validity of types    
   Collecting page data  ..TypeError: eG.PineconeVectorStore is not a constructor
    at 25086 (/Users/seonglee/Desktop/aidefi/defiai/.next/server/app/api/generate-answer/route.js:184:1332)
    at t (/Users/seonglee/Desktop/aidefi/defiai/.next/server/webpack-runtime.js:1:143)
    at __webpack_exec__ (/Users/seonglee/Desktop/aidefi/defiai/.next/server/app/api/generate-answer/route.js:376:574667)
    at /Users/seonglee/Desktop/aidefi/defiai/.next/server/app/api/generate-answer/route.js:376:574766
    at t.X (/Users/seonglee/Desktop/aidefi/defiai/.next/server/webpack-runtime.js:1:1285)
    at /Users/seonglee/Desktop/aidefi/defiai/.next/server/app/api/generate-answer/route.js:376:574752
    at Object.<anonymous> (/Users/seonglee/Desktop/aidefi/defiai/.next/server/app/api/generate-answer/route.js:376:574827)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
```

### Version

"llamaindex": "^0.7.0",

### Steps to Reproduce

Attempt to construct PineconeVectorStore

**Comment by GiveMeMoreLoansZeroInterest** [comment]
@dosu are you sure that's the import statement for typescript?

**Comment by GiveMeMoreLoansZeroInterest** [comment]
No i don't think that's right

**Comment by GiveMeMoreLoansZeroInterest** [comment]
@dosu that returns an import error. Are you sure this is the right import from Typescript? The documentation returns import {PineconeVectorStore} from 'llamaindex'
