### ISSUE TITLE
[Bug]: Vertex LLM does not Handle FunctionCall tools

### ISSUE THREAD

**Issue by stfines-clgx** [run-llama/llama_index#16678]
### Bug Description

When using a FunctionTool, I receive the following error:
`
AttributeError: 'FunctionCall' object has no attribute '_pb'
`

It seems that this tool makes some assumptions about the input data types. 

### Version

0.11.7, llama-index-llms-vertex==0.3.7

### Steps to Reproduce

Update the code in [The multi-agent concierge example](https://github.com/run-llama/multi-agent-concierge.git) to use Vertex, then try and run.

### Relevant Logs/Tracbacks

```shell
INFO:chromadb.telemetry.product.posthog:Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
ERROR:asyncio:Exception in callback Dispatcher.span.<locals>.wrapper.<locals>.handle_future_result(span_id='Workflow.run...-6419e73b17c5', bound_args=<BoundArgumen...bose': True})>, instance=<clgx.agent.e...t 0x3230e6a50>, context=<_contextvars...t 0x31fb73e00>)(<WorkflowHand...ibute '_pb'")>) at /Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py:273
handle: <Handle Dispatcher.span.<locals>.wrapper.<locals>.handle_future_result(span_id='Workflow.run...-6419e73b17c5', bound_args=<BoundArgumen...bose': True})>, instance=<clgx.agent.e...t 0x3230e6a50>, context=<_contextvars...t 0x31fb73e00>)(<WorkflowHand...ibute '_pb'")>) at /Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py:273>
Traceback (most recent call last):
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 283, in handle_future_result
    raise exception
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/stfines/workspace/propertyPoc-LlamaIndex/clgx/agent/CoreSearchAgent.py", line 242, in main
    result = await handler
             ^^^^^^^^^^^^^
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/futures.py", line 290, in __await__
    return self.result()  # May raise too.
           ^^^^^^^^^^^^^
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/workflow/workflow.py", line 376, in _run_workflow
    raise exception_raised
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/workflow/workflow.py", line 233, in _task
    raise e from None
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/workflow/workflow.py", line 229, in _task
    new_ev = await instrumented_step(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 357, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stfines/workspace/propertyPoc-LlamaIndex/clgx/agent/events/CoreSearchEvents.py", line 358, in orchestrator
    tool_calls = llm.get_tool_calls_from_response(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/llms/vertex/base.py", line 498, in get_tool_calls_from_response
    response_dict = MessageToDict(tool_call._pb)
                                  ^^^^^^^^^^^^^
AttributeError: 'FunctionCall' object has no attribute '_pb'
Traceback (most recent call last):
  File "/Users/stfines/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers-pro/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stfines/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers-pro/pydevd_asyncio/pydevd_nest_asyncio.py", line 243, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/stfines/workspace/propertyPoc-LlamaIndex/clgx/agent/CoreSearchAgent.py", line 242, in main
    result = await handler
             ^^^^^^^^^^^^^
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/futures.py", line 290, in __await__
    return self.result()  # May raise too.
           ^^^^^^^^^^^^^
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/workflow/workflow.py", line 376, in _run_workflow
    raise exception_raised
  File "/Users/stfines/.pyenv/versions/3.11.6/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/workflow/workflow.py", line 233, in _task
    raise e from None
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/workflow/workflow.py", line 229, in _task
    new_ev = await instrumented_step(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 357, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stfines/workspace/propertyPoc-LlamaIndex/clgx/agent/events/CoreSearchEvents.py", line 358, in orchestrator
    tool_calls = llm.get_tool_calls_from_response(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stfines/Library/Caches/pypoetry/virtualenvs/propertypoc-llamaindex-CWmV6wNU-py3.11/lib/python3.11/site-packages/llama_index/llms/vertex/base.py", line 498, in get_tool_calls_from_response
    response_dict = MessageToDict(tool_call._pb)
                                  ^^^^^^^^^^^^^
AttributeError: 'FunctionCall' object has no attribute '_pb'
```

**Comment by logan-markewich** [comment]
Probably could be related to the package version for the generative-ai package?

I don't have access to vertex to test, but the code is here
https://github.com/run-llama/llama_index/blob/bfd25142f2098bc8da9a0b091874090a94834ff5/llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py#L498

Happy to accept a PR to fix

**Comment by stfines-clgx** [comment]
That does seem possible, esp since the pyproject.toml lists a aiplatform dependency of 1.39.0 and the current version is 1.70.0; I'll pull locally and see if I can build this lib with a newer dependency

**Comment by logan-markewich** [comment]
That would be amazing, thank you!

**Comment by stfines-clgx** [comment]
Taking a look at this, the entire set of interfaces has changed significantly. I've forked and will re-work how to interact with gemini so that it uses the actual released interface and as such doesn't depend on unreleased/private features. which should address the problem. 

Once I can verify that it functions I'll submit a PR - it'll probably require a new version update.

**Comment by stfines-clgx** [comment]
Ok [this fork](https://github.com/stfines-clgx/llama_index.git) has a branch - dev/1_70_protobuf_only that _seems_ to resolve this issue. My testing with several different types of functions and non-function invocations has it working well. It does not resolve 
#16625 - it looks like that will take action from the google-cloud-aiplatform team though I will continue to explore mitigations. 

@logan-markewich if you would take a look prior to my creating a PR and let me know what else needs doing to make a good PR for this project I would appreciate it.

**Comment by noabenefraim** [comment]
I encountered the same bug. However this fix did not resolve my issue. I will investigate further and see what insights I can offer.

Thank you for investigating this @stfines-clgx, appreciate it.

**Comment by stfines-clgx** [comment]
If you can post your error and input I can take a look and see what I need to add - I can't test all the different variations in input here so If I can make some unit tests It would help quite a bit.

**Comment by stfines-clgx** [comment]
@logan-markewich can you assign this and #16625 to me? It will make it easier for me to keep track of comments on both

**Comment by noabenefraim** [comment]
@stfines-clgx 

We confirmed we are running your version. Here is the error we are seeing - **google.protobuf.json_format.ParseError: Failed to parse properties field: Failed to parse anyOf field: Failed to parse type field: Invalid enum value NULL for enum type google.cloud.aiplatform.v1beta1.Type at Schema.properties[images].anyOf[1].type...**

Before we merged your code, we were getting this error: **AttributeError: 'FunctionCall' object has no attribute '_pb'**

Going to add more context below:

This is the repo we are working off of - https://github.com/run-llama/multi-agent-concierge/tree/main
The only file I changed is this repository is main.py. I have attached it as a .txt because github won't let me upload a .py file.
I've also attached my current environment dependencies. 

[main.txt](https://github.com/user-attachments/files/17805633/main.txt)
[req_llama_fork.txt](https://github.com/user-attachments/files/17805615/req_llama_fork.txt)

Thank you for your help.

**Comment by noabenefraim** [comment]
Here's another simple unit test that is failing.

Coming from this documentation - https://docs.llamaindex.ai/en/stable/examples/workflow/function_calling_agent/

[function_calling.txt](https://github.com/user-attachments/files/17806456/function_calling.txt)

**Comment by jeffbryner** [comment]
FWIW: I was able to get this to work by overriding the function to alter this line https://github.com/run-llama/llama_index/blob/bfd25142f2098bc8da9a0b091874090a94834ff5/llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py#L498

```response_dict = MessageToDict(tool_call._pb)```

to

```response_dict = tool_call.to_dict()```

My class: 
```
class MyVertex(Vertex):
    def get_tool_calls_from_response(
        self,
        response: "ChatResponse",
        error_on_no_tool_call: bool = True,
        **kwargs: Any,
    ) -> List[ToolSelection]:
        """Predict and call the tool."""
        tool_calls = response.message.additional_kwargs.get("tool_calls", [])


        if len(tool_calls) < 1:
            if error_on_no_tool_call:
                raise ValueError(
                    f"Expected at least one tool call, but got {len(tool_calls)} tool calls."
                )
            else:
                return []

        tool_selections = []
        for tool_call in tool_calls:
#            response_dict = MessageToDict(tool_call._pb)
            response_dict = tool_call.to_dict()
            if "args" not in response_dict or "name" not in response_dict:
                raise ValueError("Invalid tool call.")
            argument_dict = response_dict["args"]

            tool_selections.append(
                ToolSelection(
                    tool_id="None",
                    tool_name=tool_call.name,
                    tool_kwargs=argument_dict,
                )
            )

        return tool_selections```

**Comment by ex0ns** [comment]
I can confirm that this workaround work as well with the latest version of the `google-cloud-aiplatform`. I did not see any other issues so far. except from the fact that llamaindex will always try to call `.text` on the response (https://github.com/run-llama/llama_index/blob/v0.12.15/llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py#L286 and https://github.com/run-llama/llama_index/blob/v0.12.15/llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py#L429 which fails if the model only generated a function call.

I will try to open a PR to bump google-cloud-aiplatform  to `1.79.0` and include the fix from @jeffbryner as well as checking what I can do about the `.text` being call, however I'm a bit worried that it might break a lot of other stuff that used to work.

**Comment by HejiaZ2023** [comment]
Hi @ex0ns any updates on this potential PR? We have met the same `.pb` issue and have also confirmed that the fix from @jeffbryner works. It would be great for us to see the fix merged; Please let us know if we can help.

**Comment by ex0ns** [comment]
I did not worked on that as we ended up using Gemini api instead of vertex, we however had to fix a similar issue in the Gemini api (llama-index-llms-gemini 0.4.6+) that we could probably draw inspiration from. I will not have the time to work on the vertex api as this is not a priority anymore

**Comment by ABZ187** [comment]
Created PR https://github.com/run-llama/llama_index/pull/18201 with the bugfix.
