### ISSUE TITLE
[Question]: What happend in this error

### ISSUE THREAD

**Issue by 912100012** [run-llama/llama_index#16718]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I encounter the error in my code,which is copied from the part of the llamaindex CLI in llamaindex doc website,I want to know why?My terminal code and the error as follow:

```
# terminal code
pip install -U llama-index
pip install -U chromadb
 llamaindex-cli rag --files "./绿毛水怪节选.txt"
llamaindex-cli rag --question "简介剧情"

```

````
#error
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\lib\site-packages\llama_index\cli\rag\base.py", line 300, in handle_question
    raise ValueError("query_pipeline is not defined.")
ValueError: query_pipeline is not defined.


``

**Comment by 912100012** [comment]
why always alert error "query_pipeline is not defined" in cli terminal  when I input the "llamaindex-cli rag --files "./cqa.json" --question "简介剧情"
@Dosu

**Comment by 912100012** [comment]
I do not have the right to edit the source code,I just use the llamaindex-cli to integration the file and ask the question,I just want to solve the problem , please watch this error alert carefully.
Tell me the key to solve it.

````
(novelRAG-LlamaIndex-py39) PS F:\Project\pythonWorkspace\novel-rag> llamaindex-cli rag --files "./data" --chat -v
Saving/Loading from persist_dir:  C:\Users\Lenovo\AppData\Local\llama_index\rag_cli
Loading files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.86file/s] 
Traceback (most recent call last):
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\Scripts\llamaindex-cli.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\lib\site-packages\llama_index\cli\command_line.py", line 276, in main
    args.func(args)
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\lib\site-packages\llama_index\cli\rag\base.py", line 369, in <lambda>
    func=lambda args: asyncio.run(
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\lib\site-packages\llama_index\cli\rag\base.py", line 296, in handle_cli
    await self.start_chat_repl()
  File "E:\anaconda3\envs\novelRAG-LlamaIndex-py39\lib\site-packages\llama_index\cli\rag\base.py", line 317, in start_chat_repl
    raise ValueError("query_pipeline is not defined.")
ValueError: query_pipeline is not defined.


``

@dosu

**Comment by analytic-garden** [comment]
That doesn't help. The error comes from  llamaindex-cli rag --question. Unless the user wants to debug and edit llamaindex-cli, they can't initialize query_pipeline.  If you try to execute the example from the tutorial at https://docs.llamaindex.ai/en/stable/getting_started/starter_tools/rag_cli/, you will get this error.  It's a bug and needs to be fixed at the llamaindex level.

**Comment by 912100012** [comment]
YES.It spent me one noon to try to fix it.My head has boomed and I give it up.
@analytic-garden

**Comment by ArthurSrz** [comment]
Got the same error and can't use the cli from llama index as a result. Any idea now @912100012, @analytic-garden ?

**Comment by heisenburgger** [comment]
anyone figured this out? jeez.
