### ISSUE TITLE
[Bug]: AttributeError: __pydantic_private__ when I try to run multi_modal_video_RAG.ipynb

### ISSUE THREAD

**Issue by chatzikon** [run-llama/llama_index#16787]
### Bug Description

Got the error AttributeError: __pydantic_private__ when I try to run multi_modal_video_RAG.ipynb.

I install the pckages in the order mentioned at the beginning of the ipynb file and at the command    

` text_store = LanceDBVectorStore(uri="lancedb", table_name="text_collection")`

I get the error:

### Version

0.11.21

### Steps to Reproduce

That's my code up to the error:

```
from moviepy.editor import VideoFileClip
from pathlib import Path
import speech_recognition as sr
from pytubefix import YouTube
from pprint import pprint

import os

OPENAI_API_KEY = ""
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

video_url = "https://www.youtube.com/watch?v=d_qvLDhkg00"
output_video_path = "./video_data/"
output_folder = "./mixed_data/"
output_audio_path = "./mixed_data/output_audio.wav"

filepath = output_video_path + "input_vid.mp4"
Path(output_folder).mkdir(parents=True, exist_ok=True)

from PIL import Image
import matplotlib.pyplot as plt
import os


def plot_images(image_paths):
    images_shown = 0
    plt.figure(figsize=(16, 9))
    for img_path in image_paths:
        if os.path.isfile(img_path):
            image = Image.open(img_path)

            plt.subplot(2, 3, images_shown + 1)
            plt.imshow(image)
            plt.xticks([])
            plt.yticks([])

            images_shown += 1
            if images_shown >= 7:
                break


def download_video(url, output_path):
    """
    Download a video from a given url and save it to the output path.

    Parameters:
    url (str): The url of the video to download.
    output_path (str): The path to save the video to.

    Returns:
    dict: A dictionary containing the metadata of the video.
    """
    yt = YouTube(url)
    metadata = {"Author": yt.author, "Title": yt.title, "Views": yt.views}
    yt.streams.get_highest_resolution().download(
        output_path=output_path, filename="input_vid.mp4"
    )
    return metadata


def video_to_images(video_path, output_folder):
    """
    Convert a video to a sequence of images and save them to the output folder.

    Parameters:
    video_path (str): The path to the video file.
    output_folder (str): The path to the folder to save the images to.

    """
    clip = VideoFileClip(video_path)
    clip.write_images_sequence(
        os.path.join(output_folder, "frame%04d.png"), fps=0.2
    )


def video_to_audio(video_path, output_audio_path):
    """
    Convert a video to audio and save it to the output path.

    Parameters:
    video_path (str): The path to the video file.
    output_audio_path (str): The path to save the audio to.

    """
    clip = VideoFileClip(video_path)
    audio = clip.audio
    audio.write_audiofile(output_audio_path)


def audio_to_text(audio_path):
    """
    Convert audio to text using the SpeechRecognition library.

    Parameters:
    audio_path (str): The path to the audio file.

    Returns:
    test (str): The text recognized from the audio.

    """
    recognizer = sr.Recognizer()
    audio = sr.AudioFile(audio_path)

    with audio as source:
        # Record the audio data
        audio_data = recognizer.record(source)

        try:
            # Recognize the speech
            text = recognizer.recognize_whisper(audio_data)
        except sr.UnknownValueError:
            print("Speech recognition could not understand the audio.")
        except sr.RequestError as e:
            print(f"Could not request results from service; {e}")

    return text


try:
    metadata_vid = download_video(video_url, output_video_path)
    video_to_images(filepath, output_folder)
    video_to_audio(filepath, output_audio_path)
    text_data = audio_to_text(output_audio_path)

    with open(output_folder + "output_text.txt", "w") as file:
        file.write(text_data)
    print("Text data saved to file")
    file.close()
    os.remove(output_audio_path)
    print("Audio file removed")

except Exception as e:
    raise e



from llama_index.core.indices import MultiModalVectorStoreIndex

from llama_index.core import SimpleDirectoryReader, StorageContext
from llama_index.vector_stores.lancedb import LanceDBVectorStore


from llama_index.core import SimpleDirectoryReader

text_store = LanceDBVectorStore(uri="lancedb", table_name="text_collection")
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/chatziko/PycharmProjects/pythonProject1/rag_implementations/llama_rag/main.py", line 145, in <module>
    text_store = LanceDBVectorStore(uri="lancedb", table_name="text_collection")

  File "/home/chatziko/PycharmProjects/pythonProject1/rag_env/lib/python3.8/site-packages/llama_index/vector_stores/lancedb/base.py", line 184, in __init__
    self._table_name = table_name

  File "/home/chatziko/PycharmProjects/pythonProject1/rag_env/lib/python3.8/site-packages/pydantic/main.py", line 865, in __setattr__
    if self.__pydantic_private__ is None or name not in self.__private_attributes__:

  File "/home/chatziko/PycharmProjects/pythonProject1/rag_env/lib/python3.8/site-packages/pydantic/main.py", line 853, in __getattr__
    return super().__getattribute__(item)  # Raises AttributeError if appropriate
AttributeError: __pydantic_private__
```

**Comment by logan-markewich** [comment]
@chatzikon What version of `llama-index-vector-stores-lancedb` do you have? The latest fixes this error (I see the traceback does not match the current source code)

Try `pip install -U llama-index-vector-stores-lancedb` and restart your notebook

**Comment by chatzikon** [comment]
I think that version 0.2.4 requires a python version >3.8 and I have 3.8. Is there any workaround?

**Comment by logan-markewich** [comment]
@chatzikon sadly no -- python3.8 is actually not supported anymore though (its end-of-life), I really suggest updating
https://devguide.python.org/versions/
