### ISSUE TITLE
[Bug]: VectorMemory delete nodes not implemented

### ISSUE THREAD

**Issue by lmaddox** [run-llama/llama_index#16795]
### Bug Description

I'm messing with the SimpleComposableMemory, but this is reproducible with just the VectorMemory. I'm using the redis backend, which I believe to be the culprit.

also, when using the SimpleComposableMemory with a ChatMemoryBuffer and a ChatSummaryMemoryBuffer causes the LLM to complain about duplicated messages.

### Version

0.11.21

### Steps to Reproduce

[llama-index-chat-debug.py.txt](https://github.com/user-attachments/files/17608474/llama-index-chat-debug.py.txt)

### Relevant Logs/Tracbacks

```shell
. ~/venv/bin/activate&&cd src/py/ia/debug/debug/ && ./chat.py
16:47:28 redisvl.index.index INFO   Index already exists, not overwriting.
User: test
Traceback (most recent call last):
  File "/home/frederick/src/py/ia/debug/debug/./chat.py", line 455, in <module>
    response:str = chat_engine.chat(query)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/chat_engine/simple.py", line 78, in chat
    self._memory.put(ChatMessage(content=message, role="user"))
  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/memory/vector_memory.py", line 188, in put
    self._commit_node(override_last=True)
  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/memory/vector_memory.py", line 168, in _commit_node
    self.vector_index.delete_nodes([self.cur_batch_textnode.id_])
  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/indices/vector_store/base.py", line 353, in delete_nodes
    self._vector_store.delete_nodes(node_ids, **delete_kwargs)
  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/vector_stores/types.py", line 392, in delete_nodes
    raise NotImplementedError("delete_nodes not implemented")
NotImplementedError: delete_nodes not implemented
```
```

**Comment by logan-markewich** [comment]
indeed `delete_nodes` is not implemented for the redis vector store -- that would have to be added in a PR 👍🏻

**Comment by lmaddox** [comment]
@dosu please help me get started implementing `delete_nodes` in the RedisVectorStore. I've copied the code from the simple vector store. It would appear that the main difference is that the simple vector store just holds some dicts in memory. Can you walk me through the differences between that and the RedisVectorStore so that I can refactor this?

```
def delete_nodes(
        self,
        node_ids: Optional[List[str]] = None,
        filters: Optional[MetadataFilters] = None,
        **delete_kwargs: Any,
    ) -> None:
        filter_fn = _build_metadata_filter_fn( # llama_index.core.vector_stores.simple
            # TODO need to convert node_id to metadata_lookup_fn: Callable[[str], Mapping[str, Any]],
            lambda node_id: self.data.metadata_dict[node_id], filters
        )
        # TODO convert to redis filter ?
        # _to_redis_filter(field: BaseField, filter: MetadataFilter) -> FilterExpression:

        if node_ids is not None:
            node_id_set = set(node_ids)

            def node_filter_fn(node_id: str) -> bool:
                return node_id in node_id_set and filter_fn(node_id)

        else:

            def node_filter_fn(node_id: str) -> bool:
                return filter_fn(node_id)

        for node_id in list(self.data.embedding_dict.keys()): # TODO whence to get embedding_dict
            if node_filter_fn(node_id):
                del self.data.embedding_dict[node_id] # TODO
                del self.data.text_id_to_ref_doc_id[node_id] # TODO
                self.data.metadata_dict.pop(node_id, None) # TODO
```

**Comment by lmaddox** [comment]
@dosu let's try it one line at a time.

What would be the RedisVectorStore counterpart to the SimpleVectorStoreData's metadata_dict?

**Comment by lmaddox** [comment]
@dosu I'm not too familiar with Redis, actually. A code sample would be appreciated. Furthermore, I think I may have offered the wrong helper function. I'm noticing this:

```
_create_redis_filter_expression(self, metadata_filters: MetadataFilters) -> FilterExpression:
```

Perhaps we should try to use the resulting FilterExpression to delete the nodes and associated docs?

For reference, we're trying to refactor this to work with the RedisVectorStore:

```
del self.data.embedding_dict[node_id]
del self.data.text_id_to_ref_doc_id[node_id]
self.data.metadata_dict.pop(node_id, None)

```

**Comment by lmaddox** [comment]
@dosu great work. I think we're making progress. I think we've made it further into the execution, and now it's failing when we try to insert the chat message.

```
redis.exceptions.DataError: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.

  File "/home/frederick/src/py/ia/debug/debug/./chat.py", line 455, in <module>
    response:str = chat_engine.chat(query)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/chat_engine/simple.py", line 78, in chat
    self._memory.put(ChatMessage(content=message, role="user"))

  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/memory/vector_memory.py", line 188, in put
    self._commit_node(override_last=True)

  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/memory/vector_memory.py", line 170, in _commit_node
    self.vector_index.insert_nodes([self.cur_batch_textnode])

  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/indices/vector_store/base.py", line 333, in insert_nodes
    self._insert(nodes, **insert_kwargs)

  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/indices/vector_store/base.py", line 314, in _insert
    self._add_nodes_to_index(self._index_struct, nodes, **insert_kwargs)

  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/core/indices/vector_store/base.py", line 233, in _add_nodes_to_index
    new_ids = self._vector_store.add(nodes_batch, **insert_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frederick/venv/lib/python3.12/site-packages/llama_index/vector_stores/redis/base.py", line 262, in add
    keys = self._index.load(data, id_field=NODE_ID_FIELD_NAME, **add_kwargs)

```

**Comment by lmaddox** [comment]
@dosu it already is passing a list of dict. but I notice that the dict is deeply nested and also contains some `None` values. perhaps the problem lies therein.

```
[{'id': 'dea30963-d4b3-4049-8dbc-aab5f60c2a69', 'doc_id': 'None', 'text': 'test', 'vector': b'(a long hex string)',  'sub_dicts': [{'role': <MessageRole.USER: 'user'>, 'content': 'test', 'additional_kwargs': {}}], '_node_content': '{"id_": "dea30963-d4b3-4049-8dbc-aab5f60c2a69", "embedding": null, "metadata": {"sub_dicts": [{"role": "user", "content": "test", "additional_kwargs": {}}]}, "excluded_embed_metadata_keys": ["sub_dicts"], "excluded_llm_metadata_keys": ["sub_dicts"], "relationships": {}, "text": "", "mimetype": "text/plain", "start_char_idx": null, "end_char_idx": null, "text_template": "{metadata_str}\\n\\n{content}", "metadata_template": "{key}: {value}", "metadata_seperator": "\\n", "class_name": "TextNode"}', '_node_type': 'TextNode', 'document_id': 'None', 'ref_doc_id': 'None'}]
```
