### ISSUE TITLE
[Bug]: Chroma Persist Client raises a ValueError when retrieving nodes

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#16805]
### Bug Description

I am using the chroma Persistent Client. It was working fine until it started raising a ValueError. Not sure what is causing it.

### Version

llama-index-core: v0.11.21 llama-index-vector-stores-chroma: 0.2.2

### Steps to Reproduce

Construct a vector store index using a ChromaVectorStore instance that uses a chromadb PersistentClient.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/models/CollectionCommon.py", line 90, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/models/CollectionCommon.py", line 294, in _validate_and_prepare_query_request
    validate_filter_set(filter_set=filters)
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/types.py", line 339, in validate_filter_set
    validate_where(filter_set["where"])
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/types.py", line 598, in validate_where
    raise ValueError(f"Expected where to have exactly one operator, got {where}")
ValueError: Expected where to have exactly one operator, got {}





File 
    response: AgentChatResponse = chat_engine.chat(input_text)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/BAYESNET/.venv/lib/python3.12/site-packages/llama_index/core/chat_engine/condense_plus_context.py", line 308, in chat
    synthesizer, context_source, context_nodes = self._run_c3(message, chat_history)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/core/chat_engine/condense_plus_context.py", line 256, in _run_c3
    context_nodes = self._get_nodes(condensed_question)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/core/chat_engine/condense_plus_context.py", line 197, in _get_nodes
    nodes = self._retriever.retrieve(message)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/core/base/base_retriever.py", line 245, in retrieve
    nodes = self._retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 103, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 180, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/vector_stores/chroma/base.py", line 371, in query
    return self._query(
           ^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/llama_index/vector_stores/chroma/base.py", line 381, in _query
    results = self._collection.query(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/models/Collection.py", line 210, in query
    query_request = self._validate_and_prepare_query_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/models/CollectionCommon.py", line 93, in wrapper
    raise type(e)(msg).with_traceback(e.__traceback__)
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/models/CollectionCommon.py", line 90, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/models/CollectionCommon.py", line 294, in _validate_and_prepare_query_request
    validate_filter_set(filter_set=filters)
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/types.py", line 339, in validate_filter_set
    validate_where(filter_set["where"])
  File "/home/gich2009/Work/.venv/lib/python3.12/site-packages/chromadb/api/types.py", line 598, in validate_where
    raise ValueError(f"Expected where to have exactly one operator, got {where}")
ValueError: Expected where to have exactly one operator, got {} in query.
```

**Comment by logan-markewich** [comment]
@gich2009 chroma had a breaking change. Try updating the vector store

`pip install -U llama-index-vector-stores-chroma`

**Comment by gich2009** [comment]
Hi @logan-markewich, already did. 
These are the version I have:
![image](https://github.com/user-attachments/assets/64c2411c-163d-452a-a4d4-9479442d3348)

**Comment by logan-markewich** [comment]
Update again, just published a newer version

**Comment by gich2009** [comment]
Hey @logan-markewich , which library did you patch? core or vector-stores-chroma?

**Comment by gich2009** [comment]
Never mind.
For anyone else with this issue, there is a major version update to llama-index-vector-stores-chroma >= v0.3.0

Thanks @logan-markewich
