### ISSUE TITLE
[Bug]: PG Vector - DB parameters with a valid default create a broken connection string

### ISSUE THREAD

**Issue by Morikko** [run-llama/llama_index#16878]
### Bug Description

**Reason**

In `/llama_index/vector_stores/postgres/base.py`

```
        conn_str = (
            connection_string
            or f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
        )
        async_conn_str = async_connection_string or (
            f"postgresql+asyncpg://{user}:{password}@{host}:{port}/{database}"
        )
```

If no connection string is present, one is generated from the function parameters but all of them accept `None` though it is going to create a broken connection string.

Only sync mode is required, but it would hold the same if only async was required.

**Workaround**

Provide explicitly a connection string or explicitly set all the DB parameters even if a default should be compatible.

**Proposition**

1. To not generate a connection string but to just store a `sqlalchemy.engine.URL` that is already able to manage all the connection details
2. Split `_connect` with `_sync_connect` and `_async_connect` because I don't see a reason to always connect in both mode if only one is required. 

### Version

llama-index-core                   0.11.22 llama-index-vector-stores-postgres 0.2.6

### Steps to Reproduce

from llama_index.vector_stores.postgres import PGVectorStore

pg_vector = PGVectorStore.from_params(
    connection_string="postgresql://localhost/test",
    table_name="test",
    embed_dim=514,
)

pg_vector._connect()

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/llama_index/vector_stores/postgres/base.py", line 339, in _connect
    self._async_engine = create_async_engine(
  File ".../site-packages/sqlalchemy/ext/asyncio/engine.py", line 120, in create_async_engine
    sync_engine = _create_engine(url, **kw)
  File "<string>", line 2, in create_engine
  File ".../site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File ".../site-packages/sqlalchemy/engine/create.py", line 546, in create_engine
    u = _url.make_url(url)
  File ".../site-packages/sqlalchemy/engine/url.py", line 842, in make_url
    return _parse_url(name_or_url)
  File ".../site-packages/sqlalchemy/engine/url.py", line 903, in _parse_url
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by slyapustin** [comment]
It looks like it always required `async_connection_string` to be set when you create vector store using:
```python
PGVectorStore.from_params(
    connection_string=os.environ["DATABASE_URL"],
    async_connection_string=os.environ["ASYNC_DATABASE_URL"],
    ...
)
```
