### ISSUE TITLE
[Bug]: download_llama_pack() failure due to site's restrictions

### ISSUE THREAD

**Issue by mingqxu7** [run-llama/llama_index#16906]
### Bug Description

>>> from llama_index.core.llama_pack import download_llama_pack
>>> download_llama_pack("FuzzyCitationEnginePack", "./fuzzy_citation_pack")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/llama_pack/download.py", line 56, in download_llama_pack
    pack_cls = download_llama_pack_template(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/download/pack.py", line 131, in download_llama_pack_template
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/fuzzy_citation_pack/llama_index/packs/fuzzy_citation/__init__.py", line 17
    .container { margin: 30px auto 40px auto; width: 800px; text-align: center; }
                          ^
SyntaxError: invalid decimal literal.

The root cause is that the __init__.py file from fuzzy_citation_pack/llama_index/packs/fuzzy_citation is the following web content:

<!DOCTYPE html>
<html>
  <head>
    <meta content="origin" name="referrer">
    <title>Forbidden &middot; GitHub</title>
    <style type="text/css" media="screen">
      body {
        background-color: #f1f1f1;
        margin: 0;
      }
      body,
      input,
      button {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      }
      .container { margin: 30px auto 40px auto; width: 800px; text-align: center
; }
      a { color: #4183c4; text-decoration: none; font-weight: bold; }
      a:hover { text-decoration: underline; }
      h1, h2, h3 { color: #666; }
      ul { list-style: none; padding: 25px 0; }
      li {
        display: inline;
        margin: 10px 50px 10px 0px;
      }
      .logo { display: inline-block; margin-top: 35px; }
      .logo-img-2x { display: none; }
      @media
      only screen and (-webkit-min-device-pixel-ratio: 2),
      only screen and (   min--moz-device-pixel-ratio: 2),
      only screen and (     -o-min-device-pixel-ratio: 2/1),
      only screen and (        min-device-pixel-ratio: 2),
      only screen and (                min-resolution: 192dpi),
      only screen and (                min-resolution: 2dppx) {
        .logo-img-1x { display: none; }
        .logo-img-2x { display: inline-block; }
      }
    </style>
  </head>
  <body>

    <div class="container">
      <h1>Access to this site has been restricted.</h1>

      <p>
        <br>
        If you believe this is an error,
        please contact <a href="https://support.github.com">Support</a>.
      </p>

      <div id="s">
        <a href="https://githubstatus.com">GitHub Status</a> &mdash;
        <a href="https://twitter.com/githubstatus">@githubstatus</a>
      </div>
    </div>
  </body>
</html>

The content reads: 
Access to this site has been restricted.

If you believe this is an error, please contact [Support](https://support.github.com/).

[GitHub Status](https://githubstatus.com/) — [@githubstatus](https://twitter.com/githubstatus)

### Version

0.11.22

### Steps to Reproduce

% python
>>> from llama_index.core.llama_pack import download_llama_pack
>>> download_llama_pack("FuzzyCitationEnginePack", "./fuzzy_citation_pack")

**Comment by logan-markewich** [comment]
I dont think this is anything that llama-index can fix right now, it's totally dependant on your internet provider and other settings

**Comment by nmhjklnm** [comment]
I'm not sure if this will solve your problem. My assumption is that the VPN service is working properly, and I need to configure the Git proxy additionally before using Llama Pack. 

To configure a Git proxy, For global configuration, use the following commands:

1. **HTTP Proxy:**
   ```bash
   git config --global http.proxy http://xxxxx
   ```

2. **HTTPS Proxy:**
   ```bash
   git config --global https.proxy http://xxxx
   ```
