### ISSUE TITLE
[Bug]: ReAct Agent loops and does not return a final answer

### ISSUE THREAD

**Issue by maciekmalachowski** [run-llama/llama_index#16982]
### Bug Description

I use ReAct Agent to pull information from the data frame. Mostly it has correct answer, but it does not return a final result to the given prompt, it loops and creates its own `thoughts` and `action inputs`.  I use the mistral model from Ollama as LLM locally``

### Version

llama-index==0.11.23

### Steps to Reproduce

here is the code for main.py:
```python
import os
import pandas as pd
from dotenv import load_dotenv
from llama_index.llms.ollama import Ollama
from llama_index.experimental.query_engine import PandasQueryEngine
from llama_index.core.tools import QueryEngineTool, ToolMetadata
from llama_index.core.agent import ReActAgent
from prompts import instruction_str, new_prompt, context
from mailing import email_engine

load_dotenv()

data_path = os.path.join("data", "company_data.xlsx")
company_df = pd.read_excel(data_path)

llm = Ollama(model="mistral", request_timeout=60.0)

company_query_engine = PandasQueryEngine(df=company_df, verbose=True, instruction_str=instruction_str, llm=llm)

company_query_engine.update_prompts({"pandas_prompt": new_prompt})

tools = [
    # email_engine,
     QueryEngineTool(query_engine=company_query_engine, metadata=ToolMetadata(
         name="company_data",
         description="This tool retrieves information about company names and their associated email addresses."
     ))
]

agent = ReActAgent.from_tools(tools=tools, llm=llm, verbose=True, context=context)

while (prompt := input("Enter a prompt (q to quit): ")) != "q":
    result = agent.query(prompt)
    print(result)
```

and here are the prompts.py:
```python
from llama_index.core import PromptTemplate

instruction_str = """\
1. Convert the query to executable Python code using Pandas.
2. The code should retrieve data directly from the dataframe based on the query.
3. The dataframe is named `df`.
4. The final line of code should be a Python expression that can be executed with the `eval()` function.
5. PRINT ONLY THE EXPRESSION.
6. Do not quote the expression."""

new_prompt = PromptTemplate(
    """\
    You are working with a pandas dataframe containing company names and emails in Python.
    The name of the dataframe is `df`.
    This is the result of `print(df.head())`:
    {df_str}

    Follow these instructions:
    {instruction_str}
    Query: {query_str}

    Expression: """
)

context = """Purpose: 
The primary role of this agent is to retrieve data from a dataframe (`df`) in response to user queries and to send emails when requested.

- For any query that involves retrieving data, directly analyze the dataframe to provide the requested information.
- If the query involves sending an email, use the provided `email_engine` to send the email based on the necessary data.
- Avoid unnecessary observations, thoughts, or steps.
- Focus on returning the data or sending the email immediately, and finalize the task after the first response."""

```

data:
[company_data (1).xlsx](https://github.com/user-attachments/files/17787069/company_data.1.xlsx)

### Relevant Logs/Tracbacks

```shell
Enter a prompt (q to quit): send email to company named 'example1'
> Running step 9e39f69f-2e85-4e99-9db8-aa73b76940ce. Step input: send email to company named 'example1'
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.
> Running step d3ec4ce3-c6b5-4781-a984-3bac786d3a3f. Step input: None
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
Thought: The user has requested me to send an email to a specific company named 'example1'. I need to use a tool to help me find the email address associated with this company name.
Action: company_data
Action Input: {'properties': AttributedDict([('input', 'example1')])}
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
> Pandas Instructions:

 df[df['Company_name'] == 'example1']['Company_email'].values[0]
```
> Pandas Output: wilih88561@cironex.com
Observation: wilih88561@cironex.com
> Running step 2fdfb390-9f85-4a78-9bff-ac6179177159. Step input: None
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.
> Running step 766888c6-b717-4b59-b437-2d60fd2de0cd. Step input: None
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.
> Running step 4883c4e1-c44a-41b6-bc7d-ac0e461fa547. Step input: None
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
Thought: The user has provided an email address for a company, but I need to find out the name of the company associated with that email address. To accomplish this task, I will use the 'company_data' tool.
Action: company_data
Action Input: {'properties': AttributedDict([('input', 'wilih88561@cironex.com')])}
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
> Pandas Instructions:
```
 df[df['Company_email'] == 'wilih88561@cironex.com']
```
> Pandas Output:   Company_name           Company_email
0     example1  wilih88561@cironex.com
1     example2  wilih88561@cironex.com
Observation:   Company_name           Company_email
0     example1  wilih88561@cironex.com
1     example2  wilih88561@cironex.com
> Running step 5a9cc3e3-b0ea-4db8-89a3-ab997ac00dde. Step input: None
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.
> Running step a34512d5-447a-4948-b1e9-29b595384c2a. Step input: None
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
Thought: The user is asking for the company name associated with the email address 'wilih88561@cironex.com'. I will use the 'company_data' tool to find this information.
Action: company_data
Action Input: {}
INFO:httpx:HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
> Pandas Instructions:
```
 df[df['Company_name'] == 'example2']['Company_email'].values[0]
```
> Pandas Output: wilih88561@cironex.com
Observation: wilih88561@cironex.com
Traceback (most recent call last):
  File "D:\Projects\SmartMailer\App\agent.py", line 33, in <module>
    result = agent.query(prompt)
             ^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\base\base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\callbacks\utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\base\agent\types.py", line 49, in _query
    agent_response = self.chat(
                     ^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\callbacks\utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\agent\runner\base.py", line 647, in chat
    chat_response = self._chat(
                    ^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\agent\runner\base.py", line 579, in _chat
    cur_step_output = self._run_step(
                      ^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\agent\runner\base.py", line 412, in _run_step
    cur_step_output = self.agent_worker.run_step(step, task, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\callbacks\utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\agent\react\step.py", line 818, in run_step
    return self._run_step(step, task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\agent\react\step.py", line 576, in _run_step
    agent_response = self._get_response(
                     ^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\SmartMailer\ai\Lib\site-packages\llama_index\core\agent\react\step.py", line 437, in _get_response
    raise ValueError("Reached max iterations.")
ValueError: Reached max iterations.
```

**Comment by logan-markewich** [comment]
As you can see from the logs, the llm is not following the proper react loop

`Could not parse output. Please follow the thought-action-input format. Try again.`

Open source llms are pretty bad at being agents. Try a different, more recent llm (llama3.1 or 3.2 is slightly better). All open source llms are pretty bad at being agents though imo

**Comment by maciekmalachowski** [comment]
I think you are right, because when I query the engine it returns me proper values, eg.
```python
company_query_engine.update_prompts({"pandas_prompt": new_prompt})
result = company_query_engine.query("Display all company names")
print(result)
```

```shell
Name: Company_name, dtype: object
0    example1
1    example2
```

But there is something I can do with this parser ?
