### ISSUE TITLE
[Bug]: guideline evaluation is throwing error

### ISSUE THREAD

**Issue by Rohith-Scalers** [run-llama/llama_index#17012]
### Bug Description

guideline evaluation is throwing error saying missing model

### Version

latest

### Steps to Reproduce

run the guideline evaluation example 

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/rohit/.local/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 33, in asyncio_run
    return loop.run_until_complete(coro)
  File "/home/rohit/.local/lib/python3.10/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/rohit/.local/lib/python3.10/site-packages/llama_index/core/evaluation/guideline.py", line 118, in aevaluate
    eval_data = self._output_parser.parse(eval_response)
  File "/home/rohit/.local/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
  File "/home/rohit/.local/lib/python3.10/site-packages/llama_index/core/output_parsers/pydantic.py", line 62, in parse
    return self._output_cls.parse_raw(json_str)
  File "/home/rohit/.local/lib/python3.10/site-packages/pydantic/v1/main.py", line 549, in parse_raw
    return cls.parse_obj(obj)
  File "/home/rohit/.local/lib/python3.10/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
  File "/home/rohit/.local/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for EvaluationData
passing
  field required (type=value_error.missing)
feedback
  field required (type=value_error.missing)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohit/RagEval/src/main.py", line 86, in <module>
    GuidelineData.get_score(query,reference_answer,reference_contexts,[guideline_index])
  File "/home/rohit/RagEval/src/evaluation_metrics/guideline_score.py", line 25, in get_score
    eval_result = evaluator.evaluate(
  File "/home/rohit/.local/lib/python3.10/site-packages/llama_index/core/evaluation/base.py", line 62, in evaluate
    return asyncio_run(
  File "/home/rohit/.local/lib/python3.10/site-packages/llama_index/core/async_utils.py", line 47, in asyncio_run
    raise type(e)(f"Error running coroutine: {e!s}") from e
TypeError: ValidationError.__init__() missing 1 required positional argument: 'model'
```

**Comment by Rohith-Scalers** [comment]
@dosu can you give me a example output parser

**Comment by Rohith-Scalers** [comment]
@dosu can you identify the error 
``` 
from llama_index.core.evaluation import GuidelineEvaluator
import nest_asyncio
from pydantic import BaseModel
nest_asyncio.apply()
# Define the EvaluationData model with the required fields
# class EvaluationData(BaseModel):
#     passing: bool
#     feedback: str

# # Example output parser function
# def parse_evaluation_response(response: str) -> EvaluationData:
#     try:
#         # Assuming the response is a JSON string
#         eval_data = EvaluationData.model_validate_json(response)
#         return eval_data
#     except Exception as e:
#         print(f"Error parsing evaluation response: {e}")
#         raise



class GuidelineScore:
    def __init__(self, llm , guidelines):
        self.llm = llm
        self.guidelines = guidelines
        self.evaluators  = [GuidelineEvaluator(llm=llm, guidelines=guide) for guide in self.guidelines]
        self.counterList = [0 for i in range(len(guidelines))]
        self.running_total_List = [0 for i in range(len(guidelines))]

    def get_score(self,query,response,contexts,indexs):
        for idx , (guideline, evaluator) in enumerate(zip(self.guidelines, self.evaluators)):
            if idx in indexs:
                eval_result = evaluator.evaluate(
                    query=query,
                    contexts=contexts,
                    response=response,
                )
                result = 1 if eval_result.passing else 0
                self.counterList[idx] = self.counterList[idx] + 1
                self.running_total_List[idx] = self.running_total_List[idx] + result ```

**Comment by Rohith-Scalers** [comment]
@dosu its not the problem , sometimes the code works and sometimes its throwing this error , it think its due to llm unable to respond in this format  passing: bool , feedback: str .
