### ISSUE TITLE
[Question]: pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for typing.AsyncGenerator[str, NoneType]

### ISSUE THREAD

**Issue by gianx89** [run-llama/llama_index#17010]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm using llama-index with these versions together with other libraries to compare them:

```
python = "^3.11,<3.13"
atomic-agents = "^1.0.10"
autogen = "^0.3.1"
deepeval = "^1.5.0"
instructor = "^1.0.1"
rich = "^13.9.4"
instructorembedding = "^1.0.1"
sentence-transformers = "^3.3.0"
emoji = "^2.14.0"
ipython = "^8.29.0"
markdownify = "^0.13.1"
flaml = {extras = ["automl"], version = "^2.3.2"}
chromadb = "0.5.0"
llama-index = "^0.11.23"
llama-index-llms-ollama = "^0.3.6"
llama-index-vector-stores-chroma = "0.2.2"
llama-index-embeddings-ollama = "^0.3.1"
llama-index-embeddings-huggingface = "^0.3.1"
```

Running every sample code da imports llama-index I get:
```

/Users/gianluca.sabato/PycharmProjects/tesi_sabato/.venv/bin/python /Users/gianx89/PycharmProjects/tesi_sabato/llama_index_rag/llama_index_rag.py 
Traceback (most recent call last):
  File "/Users/gianx89/PycharmProjects/tesi_sabato/llama_index_rag/llama_index_rag.py", line 3, in <module>
    from llama_index.core import Settings, SimpleDirectoryReader, VectorStoreIndex, StorageContext
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/llama_index/core/__init__.py", line 19, in <module>
    from llama_index.core.indices import (
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
    from llama_index.core.indices.composability.graph import ComposableGraph
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/llama_index/core/indices/composability/graph.py", line 5, in <module>
    from llama_index.core.base.base_query_engine import BaseQueryEngine
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/llama_index/core/base/base_query_engine.py", line 20, in <module>
    from llama_index.core.instrumentation.events.query import (
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/llama_index/core/instrumentation/events/query.py", line 21, in <module>
    class QueryEndEvent(BaseEvent):
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 226, in __new__
    complete_model_class(
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 658, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/main.py", line 697, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 881, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 693, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 693, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1073, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1261, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2051, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2032, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 988, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1016, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1323, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 984, in match_type
    return self._dataclass_schema(obj, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1765, in _dataclass_schema
    args = sorted(
           ^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1766, in <genexpr>
    (self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1090, in _generate_dc_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1261, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2051, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2032, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 988, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1045, in _match_generic_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gianx89/PycharmProjects/tesi_sabato/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 515, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for typing.AsyncGenerator[str, NoneType]. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.10/u/schema-for-unknown-type

Process finished with exit code 1
```

This happens before I get to the code, by only importing llama-index

**Comment by logan-markewich** [comment]
Seems like an issue with your pydantic version?

**Comment by logan-markewich** [comment]
You did not list that

**Comment by gianx89** [comment]
The problem was in the lib, not inside my code. I solved using pydantic@2.9.2

**Comment by gianx89** [comment]
I was using the version brought back by my dependencies, I don't remember which one.

**Comment by abdulhuq-cimulate** [comment]
I ran into this issue as well and noticed my pydantic version was 2.10.0b2, a pre-release version of pydantic (https://pypi.org/project/pydantic/#history). Downgrading it to 2.9.2 which is the latest stable version of pydantic fixed it.
