### ISSUE TITLE
[Bug]: AssertionError 2024-12-01 12:51:18.470 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_

### ISSUE THREAD

**Issue by Kitdit** [run-llama/llama_index#17117]
### Bug Description

AssertionError
2024-12-01 12:51:18.470 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_

### Version

python = "3.11" llama-index = "0.11.23"

### Steps to Reproduce

python = "^3.11"
llama-index = "0.11.23"
llama-index-vector-stores-chroma = "0.3.0"
llama-index-llms-ollama = "0.3.6"

### Relevant Logs/Tracbacks

```shell
2024-12-01 12:51:17.157 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 751, in <module>
    main()
  File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 386, in main
    init_llm_ollama(temperature=temperature)
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 300, in init_llm_ollama
    Settings.llm = llm
    ^^^^^^^^^^^^
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\llama_index\core\settings.py", line 46, in llm      
    self._llm = resolve_llm(llm)
                ^^^^^^^^^^^^^^^^
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\llama_index\core\llms\utils.py", line 102, in resolve_llm
    assert isinstance(llm, LLM)
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
2024-12-01 12:51:18.470 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_
  Stopping...
```

**Comment by Kitdit** [comment]
llama-index = "0.11.23"
llama-index-vector-stores-chroma = "0.3.0"
llama-index-llms-ollama = "0.3.6" --> these are the versions I am using

**Comment by logan-markewich** [comment]
@Kitdit there is no code here to reproduce.

Did you set `Settings.llm` to a pytorch model maybe?

**Comment by Kitdit** [comment]
@dosu, @logan-markewich here is the code, help me resolve the error
class CustomOllama(LLM):
    """Wrapper around Ollama to handle custom headers."""

    def __init__(
        self,
        model: str,
        request_timeout: float,
        base_url: str,
        headers: Dict[str, str] = None,
        **kwargs,
    ):
        self.headers = headers or {}
        self.ollama = Ollama(
            model=model, request_timeout=request_timeout, base_url=base_url, **kwargs
        )

    @property
    def metadata(self) -> LLMMetadata:
        DEFAULT_NUM_OUTPUTS = 30
        """LLM metadata."""
        return LLMMetadata(
            context_window=self.ollama.context_window,
            num_output=DEFAULT_NUM_OUTPUTS,
            model_name=self.ollama.model,
            is_chat_model=True,
        )

    def _get_client(self):
        return httpx.Client(
            timeout=Timeout(self.ollama.request_timeout), headers=self.headers
        )

    def chat(self, messages: Sequence[ChatMessage], **kwargs: Any) -> ChatResponse:
        payload = {
            "model": self.ollama.model,
            "messages": [
                {
                    "role": message.role.value,
                    "content": message.content,
                    **message.additional_kwargs,
                }
                for message in messages
            ],
            "options": self.ollama._model_kwargs,
            "stream": False,
            **kwargs,
        }

        if self.ollama.json_mode:
            payload["format"] = "json"

        with self._get_client() as client:
            response = client.post(
                url=f"{self.ollama.base_url}/api/chat",
                json=payload,
            )
            response.raise_for_status()
            raw = response.json()
            message = raw["message"]
            return ChatResponse(
                message=ChatMessage(
                    content=message.get("content"),
                    role=MessageRole(message.get("role")),
                    additional_kwargs=get_additional_kwargs(
                        message, ("content", "role")
                    ),
                ),
                raw=raw,
                additional_kwargs=get_additional_kwargs(raw, ("message",)),
            )

    def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:
        payload = {
            self.ollama.prompt_key: prompt,
            "model": self.ollama.model,
            "options": self.ollama._model_kwargs,
            "stream": False,
            **kwargs,
        }

        if self.ollama.json_mode:
            payload["format"] = "json"

        with self._get_client() as client:
            response = client.post(
                url=f"{self.ollama.base_url}/api/generate",
                json=payload,
            )
            response.raise_for_status()
            raw = response.json()
            text = raw.get("response")
            return CompletionResponse(text=text, raw=raw)

    def predict(self, prompt: str, **kwargs: Any) -> str:
        response = self.complete(prompt, **kwargs)
        return response.text

    
    def stream_chat(
        self, messages: Sequence[ChatMessage], **kwargs: Any
    ) -> ChatResponseGen:
        assert self.messages_to_prompt is not None

        prompt = self.messages_to_prompt(messages)
        completion_response_gen = self.stream_complete(prompt, formatted=True, **kwargs)
        return stream_completion_response_to_chat_response(completion_response_gen)


    async def achat(
        self,
        messages: Sequence[ChatMessage],
        **kwargs: Any,
    ) -> ChatResponse:
        return self.chat(messages, **kwargs)


    async def astream_chat(
        self,
        messages: Sequence[ChatMessage],
        **kwargs: Any,
    ) -> ChatResponseAsyncGen:
        async def gen() -> ChatResponseAsyncGen:
            for message in self.stream_chat(messages, **kwargs):
                yield message

        # NOTE: convert generator to async generator
        return gen()


    async def acomplete(
        self, prompt: str, formatted: bool = False, **kwargs: Any
    ) -> CompletionResponse:
        return self.complete(prompt, formatted=formatted, **kwargs)
    

    def stream_complete(self, prompt: str, **kwargs: Any) -> CompletionResponseGen:
        """Synchronously stream completion responses."""
        # Prepare the payload for the request
        payload = {
            self.ollama.prompt_key: prompt,
            "model": self.ollama.model,
            "options": self.ollama._model_kwargs,
            "stream": True,
            **kwargs,
        }

        if self.ollama.json_mode:
            payload["format"] = "json"

        # Use the _request_stream utility for streaming responses
        response = _request_stream(
            endpoint=f"{self.ollama.base_url}/api/generate",
            api_key=self.ollama.api_key,  # Assuming `_api_key` maps to `self.ollama.api_key`
            payload=payload,
            headers=self.headers,
        )

        completion = ""
        # Stream tokens and yield completion responses incrementally
        for token in response:
            completion += token
            yield CompletionResponse(text=completion, delta=token)

    @llm_completion_callback()
    async def astream_complete(
        self, prompt: str, formatted: bool = False, **kwargs: Any
    ) -> CompletionResponseAsyncGen:
        async def gen() -> CompletionResponseAsyncGen:
            for message in self.stream_complete(prompt, formatted=formatted, **kwargs):
                yield message

        # NOTE: convert generator to async generator
        return gen()
Error thrown 
2024-12-01 23:35:15.270 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Vil\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\Vil\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 751, in <module>
    main()
  File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 386, in main
    init_llm_ollama(temperature=0.7)
  File "C:\Users\Vil\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vil\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vil\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 720, in init_llm_ollama
    llm = CustomOllama(
          ^^^^^^^^^^^^^
  File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 326, in __init__
    self.headers = headers or {}
    ^^^^^^^^^^^^
  File "C:\Users\Vil\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\pydantic\main.py", line 926, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "CustomOllama" object has no field "headers"

**Comment by Kitdit** [comment]
@dosu updated the code and resulted in below error
class CustomOllama(BaseModel):
    """Wrapper around Ollama to handle custom headers."""

    model: str
    request_timeout: float
    base_url: str
    headers: Dict[str, str] = {}

    def __init__(self, **data: Any):
        super().__init__(**data)
        self.ollama = Ollama(
            model=self.model, request_timeout=self.request_timeout, base_url=self.base_url, **data
        )

here is my def init_llm_ollama(temperature):
llm = CustomOllama(
model="llama3.1:8b",
request_timeout=600.0,
base_url=base_url,
temperature=temperature,
headers={"Authorization": f"Bearer {bearer_token}"},
)
Settings.llm = llm
embed_model = CustomEmbedding(
model="mxbai-embed-large:latest",
request_timeout=600.0,
base_url=base_url,
headers={"Authorization": f"Bearer {bearer_token}"},
)

Settings.embed_model = embed_model
Traceback (most recent call last):
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 751, in <module>
    main()
  File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 386, in main
    init_llm_ollama(temperature=0.7)
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 721, in init_llm_ollama
    llm = CustomOllama(
          ^^^^^^^^^^^^^
  File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 328, in __init__
    self.ollama = Ollama(
                  ^^^^^^^
TypeError: llama_index.llms.ollama.base.Ollama() got multiple values for keyword argument 'model'

**Comment by Kitdit** [comment]
@dosu, resulted in this error after updating 
ValueError: "CustomOllama" object has no field "ollama"
Traceback:
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 751, in <module>
    main()
File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 386, in main
    init_llm_ollama(temperature=0.7)
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 729, in init_llm_ollama
    llm = CustomOllama(
          ^^^^^^^^^^^^^
File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 336, in __init__
    self.ollama = Ollama(
    ^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\pydantic\main.py", line 926, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')

**Comment by Kitdit** [comment]
@dosu, please help to resolve.. updated
class CustomOllama(BaseModel):
    """Wrapper around Ollama to handle custom headers."""

    model: str
    request_timeout: float
    base_url: str
    headers: Dict[str, str] = {}
    _ollama: Any = PrivateAttr()

    def __init__(self, **data: Any):
        super().__init__(**data)
        self._ollama = Ollama(
            model=self.model, request_timeout=self.request_timeout, base_url=self.base_url, **data
        )

TypeError: llama_index.llms.ollama.base.Ollama() got multiple values for keyword argument 'model'
Traceback:
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 751, in <module>
    main()
File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 386, in main
    init_llm_ollama(temperature=0.7)
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 721, in init_llm_ollama
    llm = CustomOllama(
          ^^^^^^^^^^^^^
File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 329, in __init__
    self._ollama = Ollama(
                   ^^^^^^^

**Comment by Kitdit** [comment]
@dosu After modifying getting this error
AssertionError
Traceback:
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 751, in <module>
    main()
File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 386, in main
    init_llm_ollama(temperature=0.7)
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 737, in init_llm_ollama
    Settings.llm = llm
    ^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\llama_index\core\settings.py", line 46, in llm
    self._llm = resolve_llm(llm)
                ^^^^^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\llama_index\core\llms\utils.py", line 102, in resolve_llm
    assert isinstance(llm, LLM)
           ^^^^^^^^^^^^^^^^^^^^

**Comment by Kitdit** [comment]
@dosu throwing error
ImportError: cannot import name 'LLM' from 'llama_index.core.base.llms' (C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\llama_index\core\base\llms\__init__.py)
Traceback:
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 19, in <module>
    from rag_functions import (
File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 317, in <module>
    from llama_index.core.base.llms import LLM

**Comment by Kitdit** [comment]
@dosu..here is the updated code 
class CustomEmbedding(BaseEmbedding):
    """Custom embedding implementation."""

    def __init__(self, model: str, request_timeout: float, base_url: str, headers: dict = None, **kwargs: Any):
        super().__init__()
        self.model = model
        self.request_timeout = request_timeout
        self.base_url = base_url
        self.headers = headers or {}

    def _get_query_embedding(self, query: str) -> Any:
        """Generate an embedding for a single query."""
        return self._get_embedding(query)

    def _get_text_embedding(self, text: str) -> Any:
        """Generate an embedding for a single text."""
        return self._get_embedding(text)

    def _get_embedding(self, text: str) -> Any:
        """Helper method to request an embedding from the API."""
        payload = {"model": self.model, "prompt": text}
        embed_url = f"{self.base_url}/api/embeddings"

        try:
            with self._get_client() as client:
                response = client.post(embed_url, json=payload)
                response.raise_for_status()
                response_json = response.json()

                if "embedding" in response_json or "embeddings" in response_json:
                    return response_json.get("embedding", response_json.get("embeddings", []))
                else:
                    print("Unexpected response format:", response_json)
                    return []
        except httpx.RequestError as e:
            print(f"Request Error: {e}")
            return []
        except httpx.HTTPStatusError as e:
            print(f"HTTP Status Error: {e}")
            return []

    def _get_client(self):
        return httpx.Client(timeout=Timeout(self.request_timeout), headers=self.headers)

    def embed(self, prompts: List[str]) -> List[List[float]]:
        embeddings = []
        for prompt in prompts:
            embedding = self._get_embedding(prompt)
            embeddings.append(embedding)
        return embeddings

    def get_text_embedding_batch(self, texts: List[str], **kwargs) -> List[List[float]]:
        return self.embed(texts)

    def get_agg_embedding_from_queries(self, queries: List[str], **kwargs) -> List[List[float]]:
        return self.embed(queries)
error thrown
TypeError: Can't instantiate abstract class CustomEmbedding with abstract method _aget_query_embedding
Traceback:
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 751, in <module>
    main()
File "C:\TestingBot\GB\Hybrid_11_23\chat.py", line 386, in main
    init_llm_ollama(temperature=0.7)
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\VilvanSS\AppData\Local\pypoetry\Cache\virtualenvs\golden_build-6-JWb2q3-py3.11\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\TestingBot\GB\Hybrid_11_23\rag_functions.py", line 735, in init_llm_ollama
    embed_model = CustomEmbedding(
                  ^^^^^^^^^^^^^^^^

**Comment by Kitdit** [comment]
@dosu -- Any solution?
