### ISSUE TITLE
[Bug]: TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by hcmlinj** [run-llama/llama_index#17151]
### Bug Description

The error message `unsupported operand type(s) for +: 'NoneType' and 'NoneType'` is caused by the `_get_response_token_counts` method in Ollama attempting to add two `None` values. This typically indicates that the `prompt_tokens` and `completion_tokens` fields in the response are `None`.

### Version

0.12.2

### Steps to Reproduce

```python
import asyncio
from llama_index.llms.ollama.base import Ollama


async def run_ollama_stream():
    llm = Ollama(model="mistral-nemo")
    prompt = "Please summarize the book 'Moby Dick' in three sentences."
    try:
        gen = await llm.astream_complete(prompt)
        async for response in gen:
            print(response.delta, end="", flush=True)
    except Exception as e:
        print(e.with_traceback())

asyncio.run(run_ollama_stream())
```

### Relevant Logs/Tracbacks

```shell
an error occurred during closing of asynchronous generator <async_generator object AsyncClient.stream at 0x1098cd170>
asyncgen: <async_generator object AsyncClient.stream at 0x1098cd170>
Traceback (most recent call last):
  File "/Users/jamie/github/llm-app/llm_app/ollama_original.py", line 10, in run_ollama_stream
    async for response in gen:
        print(response.delta, end="", flush=True)
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/core/llms/callbacks.py", line 347, in wrapped_gen
    async for x in f_return_val:
    ...<8 lines>...
        last_response = x
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/core/base/llms/generic_utils.py", line 286, in gen
    async for response in chat_response_gen:
    ...<5 lines>...
        )
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/core/llms/callbacks.py", line 88, in wrapped_gen
    async for x in f_return_val:
    ...<8 lines>...
        last_response = x
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/llms/ollama/base.py", line 388, in gen
    token_counts = self._get_response_token_counts(r)
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/llms/ollama/base.py", line 203, in _get_response_token_counts
    total_tokens = prompt_tokens + completion_tokens
                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/jamie/github/llm-app/llm_app/ollama_original.py", line 13, in run_ollama_stream
    print(e.with_traceback())
          ~~~~~~~~~~~~~~~~^^
TypeError: BaseException.with_traceback() takes exactly one argument (0 given)

During handling of the above exception, another exception occurred:

RuntimeError: aclose(): asynchronous generator is already running
Traceback (most recent call last):
  File "/Users/jamie/github/llm-app/llm_app/ollama_original.py", line 10, in run_ollama_stream
    async for response in gen:
        print(response.delta, end="", flush=True)
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/core/llms/callbacks.py", line 347, in wrapped_gen
    async for x in f_return_val:
    ...<8 lines>...
        last_response = x
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/core/base/llms/generic_utils.py", line 286, in gen
    async for response in chat_response_gen:
    ...<5 lines>...
        )
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/core/llms/callbacks.py", line 88, in wrapped_gen
    async for x in f_return_val:
    ...<8 lines>...
        last_response = x
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/llms/ollama/base.py", line 388, in gen
    token_counts = self._get_response_token_counts(r)
  File "/Users/jamie/github/llm-app/.venv/lib/python3.13/site-packages/llama_index/llms/ollama/base.py", line 203, in _get_response_token_counts
    total_tokens = prompt_tokens + completion_tokens
                   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamie/github/llm-app/llm_app/ollama_original.py", line 15, in <module>
    asyncio.run(run_ollama_stream())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/jamie/github/llm-app/llm_app/ollama_original.py", line 13, in run_ollama_stream
    print(e.with_traceback())
          ~~~~~~~~~~~~~~~~^^
TypeError: BaseException.with_traceback() takes exactly one argument (0 given)
```

**Comment by hcmlinj** [comment]
After I've patched `_get_response_token_counts` method, it's good to me.

```python
import asyncio
from llama_index.llms.ollama.base import Ollama


def patched_get_response_token_counts(self, response):
    prompt_tokens = response.get("prompt_tokens", 0) or 0
    completion_tokens = response.get("completion_tokens", 0) or 0
    return prompt_tokens + completion_tokens


Ollama._get_response_token_counts = patched_get_response_token_counts


async def run_ollama_stream():
    llm = Ollama(model="mistral-nemo")
    prompt = "Please summarize the book 'Moby Dick' in three sentences."
    try:
        gen = await llm.astream_complete(prompt)
        async for response in gen:
            print(response.delta, end="", flush=True)
    except Exception as e:
        print(e.with_traceback())

asyncio.run(run_ollama_stream())
```
