### ISSUE TITLE
[Bug]: GCS issue

### ISSUE THREAD

**Issue by yuce-8** [run-llama/llama_index#17185]
### Bug Description

I'm trying to read a an index from gcs but it fails. When I read it from local drive it does work.

```
storage_context = StorageContext.from_defaults(
    persist_dir="gs://mybucket/llama_text_index/", 
    fs=fs
),
text_index = load_index_from_storage(storage_context)

```

### Version

0.11.16

### Steps to Reproduce

move the persisted index to gcs bucket

### Relevant Logs/Tracbacks

```shell
ERROR@build_text_query_engine:  'tuple' object has no attribute 'index_store'
trace =  Traceback (most recent call last):
  File "/My Drive/mylibs/cancierge_15.11.2024/core/literatur/ago_library.py", line 297, in build_text_query_engine
    text_index = load_index_from_storage(storage_context, include_embeddings=True )
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/torsten/Library/Python/3.11/lib/python/site-packages/llama_index/core/indices/loading.py", line 33, in load_index_from_storage
    indices = load_indices_from_storage(storage_context, index_ids=index_ids, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/torsten/Library/Python/3.11/lib/python/site-packages/llama_index/core/indices/loading.py", line 64, in load_indices_from_storage
    index_structs = storage_context.index_store.index_structs()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'index_store'
```

**Comment by yuce-8** [comment]
<*_*>

works :-)
