### ISSUE TITLE
AttributeError: 'ServiceContext' object has no attribute 'add'

### ISSUE THREAD

**Issue by susht3** [run-llama/llama_index#17256]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

when i use image retriever, i get this error :
llama-index Version: 0.10.38

type:  <class 'llama_index.core.schema.IndexNode'>
Generating embeddings: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/mnt/sense-rag/index_server_image_retrieve.py", line 327, in <module>
    image_retriever = build_image_retriever(
  File "/home/mnt/sense-rag/retriever/retriever_builder.py", line 79, in build_image_retriever
    return ImageRetriever(nodes,service_context)
  File "/home/mnt/sense-rag/retriever/image_retriever.py", line 17, in ImageRetriever
    united_vector_index = build_united_vector_index(nodes,vector_store=vector_store, service_context=service_context)
  File "/home/mnt/sense-rag/indices/build_index.py", line 32, in build_united_vector_index
    united_vector_index = VectorStoreIndex(
  File "/home/mnt/miniconda3/envs/sense-rag/lib/python3.9/site-packages/llama_index/core/indices/vector_store/base.py", line 75, in __init__
    super().__init__(
  File "/home/mnt/miniconda3/envs/sense-rag/lib/python3.9/site-packages/llama_index/core/indices/base.py", line 94, in __init__
    index_struct = self.build_index_from_nodes(
  File "/home/mnt/miniconda3/envs/sense-rag/lib/python3.9/site-packages/llama_index/core/indices/vector_store/base.py", line 308, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
  File "/home/mnt/miniconda3/envs/sense-rag/lib/python3.9/site-packages/llama_index/core/indices/vector_store/base.py", line 280, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "/home/mnt/miniconda3/envs/sense-rag/lib/python3.9/site-packages/llama_index/core/indices/vector_store/base.py", line 234, in _add_nodes_to_index
    new_ids = self._vector_store.add(nodes_batch, **insert_kwargs)
AttributeError: 'ServiceContext' object has no attribute 'add'

**Comment by logan-markewich** [comment]
What does your code look like? Looks like you passed in the service context as a vector store?

**Comment by susht3** [comment]
> What does your code look like? Looks like you passed in the service context as a vector store?

my code is:
service_context = ServiceContext.from_defaults(
    llm=response_llm,
    embed_model=image_embedding_model,
    prompt_helper=prompt_helper,
    callback_manager=callback_manager
)
united_index_storage_context = StorageContext.from_defaults()
united_vector_index = VectorStoreIndex(
    nodes,
    storage_context=united_index_storage_context,
    service_context=service_context,
    show_progress =True)

nodes type is <class 'llama_index.core.schema.IndexNode'>

**Comment by susht3** [comment]
> What does your code look like? Looks like you passed in the service context as a vector store?

you are right，thank you
