### ISSUE TITLE
[Bug]: Query failure with Document Summary Index using Azure AI Search and Cosmos DB

### ISSUE THREAD

**Issue by zhongshuai-cao** [run-llama/llama_index#17304]
### Bug Description

Thank you for taking the time to review this issue! Our team is actively developing around Azure Cloud, and we have found LlamaIndex to be a fantastic framework for building RAG-based AI applications.

When implementing the Document Summary Index with Azure AI Search and Cosmos DB as part of a fully Azure-based setup, we encounter an issue during querying. The index builds successfully, but querying fails with a KeyError regarding a missing mapping from document_id to node_id.

Here is what we observed:

Before moving to Azure: Querying works correctly in a local persistent storage context.

In Azure: When using Azure AI Search as the vector store, the index_store does not seem to be used. Instead, the document summary mapping is stored in the docstore with __type__='document_summary', while other entries have __type__='1' (TextNode).

If the docstore is queried to retrieve all documents, it fails due to the presence of document_summary entries that should ideally reside in the index_store.

This behavior seems specific to how Azure AI Search handles the vector store and storage for the Document Summary Index.

Additional Context

The issue does not occur when using a local persistent storage setup.

The behavior appears specific to Azure AI Search as the vector store.

The docstore contains entries of type document_summary, which should ideally reside in the index_store.

### Version

0.12.5

### Steps to Reproduce

Instantiate docstore, index_store, and vector_store using Azure services.

Index the documents.

Construct the Document Summary Index with the same parameters used for querying.

Run a query using query_engine.query(question).

Additionally, attempt to retrieve all documents from the docstore.

Code Example

```python
docstore = AzureDocumentStore.from_connection_string(
            connection_string=cosmos_table_connection_string,
            namespace=namespace,
            service_mode=ServiceMode.STORAGE,
            partition_key=self.index_name    # use index name as partition key
        )

index_store = AzureIndexStore.from_connection_string(
                connection_string=cosmos_table_connection_string,
                namespace=namespace,
                service_mode=ServiceMode.STORAGE,
                partition_key=self.index_name    # use index name as partition key
                )

index_vector_store = AzureAISearchVectorStore(
            search_or_index_client=self.index_client,
            # filterable_metadata_field_keys=metadata_fields,
            index_name=self.index_name,
            index_management=IndexManagement.CREATE_IF_NOT_EXISTS,
            id_field_key="id",
            chunk_field_key="chunk",
            embedding_field_key="embedding",
            embedding_dimensionality=self.embeddings_dimension,
            metadata_string_field_key="metadata",
            doc_id_field_key="doc_id",
            language_analyzer="en.lucene",
            vector_algorithm_type="exhaustiveKnn",
            # compression_type="binary" # Option to use "scalar" or "binary". NOTE: compression is only supported for HNSW
        )

storage_context = StorageContext.from_defaults(
            docstore=docstore,
            index_store=index_store,
            vector_store=search_vector_store,
            )

index = DocumentSummaryIndex.from_documents(
            documents=documents,
            storage_context=self.search_storage_context,
            llm=self.llm,
            embed_model=self.embed_model)
query_engine =index.as_query_engine()

response = query_engine.query(question)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "<user-path>/manual_test_document_summary_index_indexing.py", line 31, in <module>
    response = query_engine.query(question)
  File "<llama-index-path>/instrumentation/dispatcher.py", line 321, in wrapper
    result = func(*args, **kwargs)
  File "<llama-index-path>/base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
  File "<llama-index-path>/instrumentation/dispatcher.py", line 321, in wrapper
    result = func(*args, **kwargs)
  File "<llama-index-path>/retriever_query_engine.py", line 178, in _query
    nodes = self.retrieve(query_bundle)
  File "<llama-index-path>/retriever_query_engine.py", line 133, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "<llama-index-path>/instrumentation/dispatcher.py", line 321, in wrapper
    result = func(*args, **kwargs)
  File "<llama-index-path>/base_retriever.py", line 245, in retrieve
    nodes = self._retrieve(query_bundle)
  File "<llama-index-path>/instrumentation/dispatcher.py", line 321, in wrapper
    result = func(*args, **kwargs)
  File "<llama-index-path>/document_summary/retrievers.py", line 185, in _retrieve
    node_ids = self._index_struct.summary_id_to_node_ids[summary_id]
KeyError: '358720ff-2d3b-4d1a-9f00-6eb137ff8ed0'
```

**Comment by Nordmaennchen** [comment]
I observe the exact same behaviour with the PostgreSQL Database using PostgresIndexStore, PostgresDocumentStore and the PGVectoreStore classes in the storage context when building the DocumentSummaryIndex. Unfortunately this has heavy impact on the retrieval process (e.g. using multiple tools for the RouterQueryEngine etc., as the querying aborts then and no answer will be returned.

**Comment by lfrass** [comment]
I can confirm the bug, too. It would be very helpful to have a fix for the DocumentSummaryIndex. Thanks for looking into this.

**Comment by Nordmaennchen** [comment]
I did some investigations and found the following workarounds:

1. If I used the retriever_mode="llm" instead of the "embedding", which is the default, the Documentsummaryindex seems to work without errors. Unfortunately with a big amount of documents the runtime gets inacceptable. To try this you can pass the retriever_mode as an argument to the as_retriever or to the as_query_engine method 
2. From what I have seen the retriever itself works well, as the  key that is printed in the error message is indeed contained in the vectorstore, but I could not find it in the index_store table (I don't know where the indexes are stored in your DB). There I could not find the key that was printed out in my case, although it was a summary for sure from the content.

3. As a workaround I tried out the TreeIndex that works with embeddings as well (try one of the retrievermodes TreeRetrieverMode.SELECT_LEAF, TreeRetrieverMode.SELECT_LEAF_EMBEDDING, TreeRetrieverMode.ROOT) The rest is quite straightforward: you can use the same from_documents method with the same storagecontext and replace the documentsummaryindex constructor with the TreeIndex constructor. The error is gone for me. I did not yet check whether all is okay contentwise now.

**Comment by LiuJiaoShouYa** [comment]
Did you find a solution? I got the same error.
