### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by buckmaxwell** [run-llama/llama_index#7189]
### Bug Description

A few days ago I was getting a fatal error with 0.7.17 -- `TypeError: multiple bases have instance lay-out conflict`. Changing my python version from 3.9.8 to 3.10.12 seemed to solve the error. Today I upgraded to 0.7.21 and started getting the same error. My python version is 3.10.12.  The error originates in an import line of mine,

`from llama_index.agent import OpenAIAgent`

I am unsure what is happening or how to resolve.

UPDATE: python 3.11.4 produces the same error.

UPDATE 2: maybe it's a langchain thing? https://github.com/langchain-ai/langchain/issues/8577

### Version

0.7.21

### Steps to Reproduce

In a python 3.10.12 or python 3.9.8 environment do

```python
from llama_index.agent import OpenAIAgent
```

### Relevant Logs/Tracbacks

```shell
╰─ docker-compose logs -f web
api-web-1  | Debug is disabled
api-web-1  | Debug is disabled
api-web-1  | Performing system checks...
api-web-1  |
api-web-1  |
api-web-1  | INFO 2023-08-07 21:55:58,709 utils.py:160 _init_num_threads() 16 139851127159680 NumExpr defaulting to 8 threads.
api-web-1  | Exception in thread django-main-thread:
api-web-1  | Traceback (most recent call last):
api-web-1  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
api-web-1  |     self.run()
api-web-1  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
api-web-1  |     self._target(*self._args, **self._kwargs)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
api-web-1  |     fn(*args, **kwargs)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
api-web-1  |     self.check(display_num_errors=True)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 419, in check
api-web-1  |     all_issues = checks.run_checks(
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 76, in run_checks
api-web-1  |     new_errors = check(app_configs=app_configs, databases=databases)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 13, in check_url_config
api-web-1  |     return check_resolver(resolver)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 23, in check_resolver
api-web-1  |     return check_method()
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 412, in check
api-web-1  |     for pattern in self.url_patterns:
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
api-web-1  |     res = instance.__dict__[self.name] = self.func(instance)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 598, in url_patterns
api-web-1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
api-web-1  |     res = instance.__dict__[self.name] = self.func(instance)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
api-web-1  |     return import_module(self.urlconf_name)
api-web-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
api-web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
api-web-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
api-web-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
api-web-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
api-web-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
api-web-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
api-web-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
api-web-1  |   File "/code/sittingsecured/urls.py", line 46, in <module>
api-web-1  |     from tracking.urls import tracking_urls
api-web-1  |   File "/code/tracking/urls.py", line 7, in <module>
api-web-1  |     from tracking.api import router
api-web-1  |   File "/code/tracking/api.py", line 2, in <module>
api-web-1  |     from tracking import viewsets
api-web-1  |   File "/code/tracking/viewsets/__init__.py", line 3, in <module>
api-web-1  |     from .ExternalMessageViewSet import ExternalMessageViewSet
api-web-1  |   File "/code/tracking/viewsets/ExternalMessageViewSet.py", line 36, in <module>
api-web-1  |     from sitter.vendor.ai.llamaindex.agenttest import agent
api-web-1  |   File "/code/sitter/vendor/ai/llamaindex/agenttest.py", line 8, in <module>
api-web-1  |     from llama_index import (
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/__init__.py", line 12, in <module>
api-web-1  |     from llama_index.data_structs.struct_type import IndexStructType
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/data_structs/__init__.py", line 3, in <module>
api-web-1  |     from llama_index.data_structs.data_structs import (
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/data_structs/data_structs.py", line 14, in <module>
api-web-1  |     from llama_index.schema import BaseNode, TextNode
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/schema.py", line 9, in <module>
api-web-1  |     from llama_index.bridge.langchain import Document as LCDocument
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/bridge/langchain.py", line 1, in <module>
api-web-1  |     import langchain
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/__init__.py", line 6, in <module>
api-web-1  |     from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/agents/__init__.py", line 31, in <module>
api-web-1  |     from langchain.agents.agent import (
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/agents/agent.py", line 15, in <module>
api-web-1  |     from langchain.agents.agent_iterator import AgentExecutorIterator
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/agents/agent_iterator.py", line 21, in <module>
api-web-1  |     from langchain.callbacks.manager import (
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/callbacks/__init__.py", line 10, in <module>
api-web-1  |     from langchain.callbacks.aim_callback import AimCallbackHandler
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/callbacks/aim_callback.py", line 5, in <module>
api-web-1  |     from langchain.schema import AgentAction, AgentFinish, LLMResult
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/schema/__init__.py", line 4, in <module>
api-web-1  |     from langchain.schema.memory import BaseChatMessageHistory, BaseMemory
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/schema/memory.py", line 7, in <module>
api-web-1  |     from langchain.schema.messages import AIMessage, BaseMessage, HumanMessage
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/schema/messages.py", line 147, in <module>
api-web-1  |     class HumanMessageChunk(HumanMessage, BaseMessageChunk):
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 367, in __new__
api-web-1  |     cls = super().__new__(mcs, name, bases, new_namespace, **kwargs)
api-web-1  |   File "/usr/local/lib/python3.10/abc.py", line 106, in __new__
api-web-1  |     cls = super().__new__(mcls, name, bases, namespace, **kwargs)
api-web-1  | TypeError: multiple bases have instance lay-out conflict
api-web-1  | Debug is disabled


api-web-1  | Debug is disabled



api-web-1  | Performing system checks...
api-web-1  |
api-web-1  |
api-web-1  | INFO 2023-08-07 22:02:39,487 utils.py:160 _init_num_threads() 16 140507908381568 NumExpr defaulting to 8 threads.
api-web-1  | Exception in thread django-main-thread:
api-web-1  | Traceback (most recent call last):
api-web-1  |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
api-web-1  |     self.run()
api-web-1  |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
api-web-1  |     self._target(*self._args, **self._kwargs)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
api-web-1  |     fn(*args, **kwargs)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
api-web-1  |     self.check(display_num_errors=True)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 419, in check
api-web-1  |     all_issues = checks.run_checks(
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 76, in run_checks
api-web-1  |     new_errors = check(app_configs=app_configs, databases=databases)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 13, in check_url_config
api-web-1  |     return check_resolver(resolver)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 23, in check_resolver
api-web-1  |     return check_method()
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 412, in check
api-web-1  |     for pattern in self.url_patterns:
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
api-web-1  |     res = instance.__dict__[self.name] = self.func(instance)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 598, in url_patterns
api-web-1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
api-web-1  |     res = instance.__dict__[self.name] = self.func(instance)
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
api-web-1  |     return import_module(self.urlconf_name)
api-web-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
api-web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
api-web-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
api-web-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
api-web-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
api-web-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
api-web-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
api-web-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
api-web-1  |   File "/code/sittingsecured/urls.py", line 46, in <module>
api-web-1  |     from tracking.urls import tracking_urls
api-web-1  |   File "/code/tracking/urls.py", line 7, in <module>
api-web-1  |     from tracking.api import router
api-web-1  |   File "/code/tracking/api.py", line 2, in <module>
api-web-1  |     from tracking import viewsets
api-web-1  |   File "/code/tracking/viewsets/__init__.py", line 3, in <module>
api-web-1  |     from .ExternalMessageViewSet import ExternalMessageViewSet
api-web-1  |   File "/code/tracking/viewsets/ExternalMessageViewSet.py", line 36, in <module>
api-web-1  |     from sitter.vendor.ai.llamaindex.agenttest import agent
api-web-1  |   File "/code/sitter/vendor/ai/llamaindex/agenttest.py", line 8, in <module>
api-web-1  |     from llama_index.agent import OpenAIAgent
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/__init__.py", line 12, in <module>
api-web-1  |     from llama_index.data_structs.struct_type import IndexStructType
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/data_structs/__init__.py", line 3, in <module>
api-web-1  |     from llama_index.data_structs.data_structs import (
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/data_structs/data_structs.py", line 14, in <module>
api-web-1  |     from llama_index.schema import BaseNode, TextNode
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/schema.py", line 9, in <module>
api-web-1  |     from llama_index.bridge.langchain import Document as LCDocument
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/llama_index/bridge/langchain.py", line 1, in <module>
api-web-1  |     import langchain
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/__init__.py", line 6, in <module>
api-web-1  |     from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/agents/__init__.py", line 31, in <module>
api-web-1  |     from langchain.agents.agent import (
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/agents/agent.py", line 15, in <module>
api-web-1  |     from langchain.agents.agent_iterator import AgentExecutorIterator
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/agents/agent_iterator.py", line 21, in <module>
api-web-1  |     from langchain.callbacks.manager import (
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/callbacks/__init__.py", line 10, in <module>
api-web-1  |     from langchain.callbacks.aim_callback import AimCallbackHandler
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/callbacks/aim_callback.py", line 5, in <module>
api-web-1  |     from langchain.schema import AgentAction, AgentFinish, LLMResult
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/schema/__init__.py", line 4, in <module>
api-web-1  |     from langchain.schema.memory import BaseChatMessageHistory, BaseMemory
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/schema/memory.py", line 7, in <module>
api-web-1  |     from langchain.schema.messages import AIMessage, BaseMessage, HumanMessage
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/schema/messages.py", line 147, in <module>
api-web-1  |     class HumanMessageChunk(HumanMessage, BaseMessageChunk):
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 367, in __new__
api-web-1  |     cls = super().__new__(mcs, name, bases, new_namespace, **kwargs)
api-web-1  |   File "/usr/local/lib/python3.10/abc.py", line 106, in __new__
api-web-1  |     cls = super().__new__(mcls, name, bases, namespace, **kwargs)
api-web-1  | TypeError: multiple bases have instance lay-out conflict
```

**Comment by logan-markewich** [comment]
@buckmaxwell maybe try downgrading a few pydantic versions, or langchain versions? One of those seems to be the issue 🤔

**Comment by buckmaxwell** [comment]
I'll try pydantic. I did try quite a few different langchain versions without success.

**Comment by buckmaxwell** [comment]
@logan-markewich It does seem like the issue is somewhere in langchain - I linked an open issue in the original. Sadly downgrading to an earlier version only seems to produce a different error.

```
Python 3.11.4 (main, Aug  7 2023, 22:19:13) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from llama_index.agent.openai_agent import OpenAIAgent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/llama_index/__init__.py", line 12, in <module>
    from llama_index.data_structs.struct_type import IndexStructType
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/llama_index/data_structs/__init__.py", line 3, in <module>
    from llama_index.data_structs.data_structs import (
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/llama_index/data_structs/data_structs.py", line 14, in <module>
    from llama_index.schema import BaseNode, TextNode
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/llama_index/schema.py", line 9, in <module>
    from llama_index.bridge.langchain import Document as LCDocument
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/llama_index/bridge/langchain.py", line 1, in <module>
    import langchain
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/tools/__init__.py", line 3, in <module>
    from langchain.tools.arxiv.tool import ArxivQueryRun
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/tools/arxiv/tool.py", line 12, in <module>
    from langchain.utilities.arxiv import ArxivAPIWrapper
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/utilities/__init__.py", line 3, in <module>
    from langchain.utilities.apify import ApifyWrapper
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/utilities/apify.py", line 5, in <module>
    from langchain.document_loaders import ApifyDatasetLoader
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/document_loaders/__init__.py", line 46, in <module>
    from langchain.document_loaders.embaas import EmbaasBlobLoader, EmbaasLoader
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/langchain/document_loaders/embaas.py", line 54, in <module>
    class BaseEmbaasLoader(BaseModel):
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 299, in __new__
    fields[ann_name] = ModelField.infer(
                       ^^^^^^^^^^^^^^^^^
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/fields.py", line 411, in infer
    return cls(
           ^^^^
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/fields.py", line 342, in __init__
    self.prepare()
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/fields.py", line 456, in prepare
    self.populate_validators()
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/fields.py", line 670, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/validators.py", line 688, in find_validators
    yield make_typeddict_validator(type_, config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/validators.py", line 582, in make_typeddict_validator
    TypedDictModel = create_model_from_typeddict(typeddict_cls, __config__=config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/annotated_types.py", line 35, in create_model_from_typeddict
    return create_model(typeddict_cls.__name__, **kwargs, **field_definitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 990, in create_model
    return type(__model_name, (__base__,), namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 299, in __new__
    fields[ann_name] = ModelField.infer(
                       ^^^^^^^^^^^^^^^^^
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/fields.py", line 411, in infer
    return cls(
           ^^^^
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/fields.py", line 342, in __init__
    self.prepare()
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/fields.py", line 451, in prepare
    self._type_analysis()
  File "/Users/maxbuck/Library/Caches/pypoetry/virtualenvs/api-SaE22jeN-py3.11/lib/python3.11/site-packages/pydantic/fields.py", line 550, in _type_analysis
    if issubclass(origin, Tuple):  # type: ignore
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxbuck/.asdf/installs/python/3.11.4/lib/python3.11/typing.py", line 1576, in __subclasscheck__
    return issubclass(cls, self.__origin__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
```

**Comment by logan-markewich** [comment]
@buckmaxwell I see! I think then langchain either needs to limit the pydantic version or update their code 🤔 I suppose we could also limit the pydantic version for them, but that's kind of tacky

**Comment by buckmaxwell** [comment]
Agreed. Maybe just a wait and see thing since others have raised the issue in their repo. Thanks for looking into it with me.
