### ISSUE TITLE
[Bug]: Persisting to s3 storage is causing "botocore.exceptions.ClientError: An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: All non-trailing parts must have the same length."

### ISSUE THREAD

**Issue by scoobyd0027** [run-llama/llama_index#7241]
### Bug Description

This issue happens with only specific files. Following this tutorial https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/storage/save_load.html and using the same code I am trying to upload the index of this file to s3 https://file.io/fWYseeDdhaTD.

s3fs - [2023.6.0](https://github.com/fsspec/s3fs/releases/tag/2023.6.0)

### Version

v0.8.0

### Steps to Reproduce

Here is the same code, I am using cloudflare R2 btw. This file can be used to index and upload  https://file.io/fWYseeDdhaTD.

`import os, s3fs
from llama_index.indices.vector_store.base import VectorStoreIndex
from llama_index import SimpleDirectoryReader

documents = SimpleDirectoryReader(input_files=["biochemistry.pdf"]).load_data()
index = VectorStoreIndex.from_documents(documents)

AWS_KEY = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET = os.environ['AWS_SECRET_ACCESS_KEY']
R2_ACCOUNT_ID = os.environ['R2_ACCOUNT_ID']

assert AWS_KEY is not None and AWS_KEY != ""

s3 = s3fs.S3FileSystem(
   key=AWS_KEY,
   secret=AWS_SECRET,
   endpoint_url=f'https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com',
   s3_additional_kwargs={'ACL': 'public-read'}
)

index.set_index_id("vector_index")
index.storage_context.persist('llama-index/storage_demo', fs=s3)`

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/s3fs/core.py", line 113, in _error_wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiobotocore/client.py", line 378, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: All non-trailing parts must have the same length.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "persist_s3_issue.py", line 25, in <module>
    index.storage_context.persist('monic-chats/bio', fs=s3)
  File "/usr/local/lib/python3.8/site-packages/llama_index/storage/storage_context.py", line 118, in persist
    self.vector_store.persist(persist_path=vector_store_path, fs=fs)
  File "/usr/local/lib/python3.8/site-packages/llama_index/vector_stores/simple.py", line 191, in persist
    json.dump(self._data.to_dict(), f)
  File "/usr/local/lib/python3.8/site-packages/fsspec/spec.py", line 1876, in close
    self.flush(force=True)
  File "/usr/local/lib/python3.8/site-packages/fsspec/spec.py", line 1747, in flush
    if self._upload_chunk(final=force) is not False:
  File "/usr/local/lib/python3.8/site-packages/s3fs/core.py", line 2250, in _upload_chunk
    self.commit()
  File "/usr/local/lib/python3.8/site-packages/s3fs/core.py", line 2278, in commit
    write_result = self._call_s3(
  File "/usr/local/lib/python3.8/site-packages/s3fs/core.py", line 2117, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/fsspec/asyn.py", line 121, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/fsspec/asyn.py", line 106, in sync
    raise return_result
  File "/usr/local/lib/python3.8/site-packages/fsspec/asyn.py", line 61, in _runner
    result[0] = await coro
  File "/usr/local/lib/python3.8/site-packages/s3fs/core.py", line 348, in _call_s3
    return await _error_wrapper(
  File "/usr/local/lib/python3.8/site-packages/s3fs/core.py", line 140, in _error_wrapper
    raise err
OSError: [Errno 22] All non-trailing parts must have the same length.
```

**Comment by scoobyd0027** [comment]
Hey team, I still need help, this happens randomly for different files, upgraded to latest boto3, botocore, s3fs, llama-index

**Comment by mattmcgiv** [comment]
Hi @scoobyd0027 I can help with this. So I can troubleshoot the issue, would you provide any files that reliably cause the multi part upload exception? It seems like the file.io links you previously provided have expired (it says the files have been deleted).

**Comment by scoobyd0027** [comment]
Hey @mattmcgiv, thanks for reaching out, here is the file which is constantly failing https://drive.google.com/file/d/1lrGL6Aj_f6Tu_3GTDrBWvSw9e0BgXHQF/view?usp=sharing

**Comment by mattmcgiv** [comment]
Thanks @scoobyd0027 ... taking a look.
