### ISSUE TITLE
[Bug]: Streamlit and Llama_index - asyncio.Queue for StreamingAgentChatResponse - RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'

### ISSUE THREAD

**Issue by InnovatorEsq** [run-llama/llama_index#7244]
### Bug Description

error from StreamingAgentChatResponse for line 60:
_aqueue: asyncio.Queue = asyncio.Queue()

### Version

0.8.0

### Steps to Reproduce

When running llama_index with a simple streamlit example:
App.py
import streamlit as st
from llama_index import LLMPredictor

run: 
streamlit run App.py 

### Relevant Logs/Tracbacks

```shell
error occurs in StreamingAgentChatResponse for _aqueue: asyncio.Queue = asyncio.Queue()
2023-08-12 08:38:47.123 Uncaught app exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/wjwong/work/test_app/App.py", line 2, in <module>
    from llama_index import LLMPredictor
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/llama_index/__init__.py", line 20, in <module>
    from llama_index.indices.keyword_table import (
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import (
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import (
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/llama_index/indices/keyword_table/base.py", line 18, in <module>
    from llama_index.indices.base import BaseIndex
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/llama_index/indices/base.py", line 6, in <module>
    from llama_index.chat_engine.types import BaseChatEngine, ChatMode
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/llama_index/chat_engine/__init__.py", line 1, in <module>
    from llama_index.chat_engine.condense_question import CondenseQuestionChatEngine
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/llama_index/chat_engine/condense_question.py", line 5, in <module>
    from llama_index.chat_engine.types import (
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/llama_index/chat_engine/types.py", line 51, in <module>
    class StreamingAgentChatResponse:
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/llama_index/chat_engine/types.py", line 60, in StreamingAgentChatResponse
    _aqueue: asyncio.Queue = asyncio.Queue()
  File "/root/miniconda3/envs/py39/lib/python3.9/asyncio/queues.py", line 36, in __init__
    self._loop = events.get_event_loop()
  File "/root/miniconda3/envs/py39/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.
```

**Comment by InnovatorEsq** [comment]
@dosu-bot - If I don't plan on using StreamingAgentChatResponse, why should I add this code into my application?

**Comment by jtrancas-ti** [comment]
I'm having the same issue when I tried to do some small chat prototype, the bot suggestion doesn't solve the issue, and I have to give up using streaming responses.

**Comment by lucaslascano** [comment]
Hi. I have the same issue: when trying to stream the response from the chat engine, I get the "There is no current event loop in thread 'Thread-xx'" error. The strange thing is that I have no problem streaming the response from a query engine. However, I am forced to use the chat engine because I need to provide the chat history, which I cannot do when using the query engine (I could do it in previous releases - 0.6.30 - but I was forced to update to the current stable one - 0.855 -).

I tried adding the event loop with asyncio as suggested above but I couldn't solve it.

Is there any workaround this?

Thanks for all the work around llama-index. I find it very useful.

**Comment by olsen-zobar** [comment]
I am having a similar issue! I cannot stream my outputs on streamlit. Looking for some suggestions!

**Comment by tonykipkemboi** [comment]
Seems like adding this code on top of your code (from above answer) seems to solve the issue.
```python
import asyncio

# Create a new event loop
loop = asyncio.new_event_loop()

# Set the event loop as the current event loop
asyncio.set_event_loop(loop)

# Now you can run your Streamlit script
import streamlit as st
```
