### ISSUE TITLE
[Bug]: Exceeding submit limit in ChromaVectorStore

### ISSUE THREAD

**Issue by ValMobYKang** [run-llama/llama_index#7648]
### Bug Description

There are too many documents. When converting them into embeddings and loading them into chroma at once, chroma shows that they exceed the submit limit.

### Version

v0.8.24.post1 Latest

### Steps to Reproduce

```python
self.index = VectorStoreIndex.from_documents(
                                    documents,
                                    storage_context=storage_context,
                                    service_context=service_context,
                                    show_progress=True,
                                )
```

### Relevant Logs/Tracbacks

```shell
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.57s/it]
Generating embeddings: 100%|███████████████████████████████████████████████████████████████████████████████████████| 293144/293144 [7:01:19<00:00, 11.60it/s]
Traceback (most recent call last):
  File ".../index/index.py", line 147, in <module>
    index = MobilityBuddyIndex()
            ^^^^^^^^^^^^^^^^^^^^
  File ".../index/index.py", line 36, in __init__
    self._setup_index()
  File ".../index/index.py", line 87, in _setup_index
    self.index = VectorStoreIndex.from_documents(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 102, in from_documents
    return cls(
           ^^^^
  File ".../.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 46, in __init__
    super().__init__(
  File ".../.venv/lib/python3.11/site-packages/llama_index/indices/base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 265, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 253, in _build_index_from_nodes
    self._add_nodes_to_index(
  File ".../.venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 214, in _add_nodes_to_index
    new_ids = self._vector_store.add(nodes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/llama_index/vector_stores/chroma.py", line 146, in add
    self._collection.add(
  File ".../.venv/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 99, in add
    self._client._add(ids, self.id, embeddings, metadatas, documents)
  File ".../.venv/lib/python3.11/site-packages/chromadb/api/segment.py", line 249, in _add
    self._producer.submit_embeddings(coll["topic"], records_to_submit)
  File ".../.venv/lib/python3.11/site-packages/chromadb/db/mixins/embeddings_queue.py", line 127, in submit_embeddings
    raise ValueError(
ValueError: 
                Cannot submit more than 41,666 embeddings at once.
                Please submit your embeddings in batches of size
                41,666 or less.
```

**Comment by ValMobYKang** [comment]
here: .../llama_index/vector_stores/chroma.py:136
```python
        for node in nodes:
            embeddings.append(node.get_embedding())
            metadatas.append(
                node_to_metadata_dict(
                    node, remove_text=True, flat_metadata=self.flat_metadata
                )
            )
            ids.append(node.node_id)
            documents.append(node.get_content(metadata_mode=MetadataMode.NONE))

        self._collection.add(
            embeddings=embeddings,
            ids=ids,
            metadatas=metadatas,
            documents=documents,
        )
```
should be use smaller chunks to add node into self._collection.

**Comment by ValMobYKang** [comment]
The possible solution is to use `index.insert()`:
```python

index = VectorStoreIndex.from_documents(
    [],
    storage_context=storage_context,
    service_context=service_context,
)

for doc in docs:
    index.insert(doc)
```

**Comment by Disiok** [comment]
Thanks for raising this issue. Looks like we are missing some batching logic here. Will try to get a fix in soon!
