### ISSUE TITLE
[Bug]: SQLDatabase wrapper does not include schema while getting column/foreign keys

### ISSUE THREAD

**Issue by ashpytho** [run-llama/llama_index#8064]
### Bug Description

When initializing the SQLDatabase wrapper, schema name can be provided as an argument. However, when retrieving column and foreign key details from the database, the schema name is not consistently passed as an argument. This can result in issues with certain databases that require the specification of a schema name. 
SQLAlchemy has designated the schema as an optional parameter, with its default value set to None. Nevertheless, when a schema name has been explicitly defined in the SQLDatabase class during initialization, it should be automatically included in subsequent database operations to ensure proper compatibility and adherence to the defined schema structure.

### Version

0.8.36

### Steps to Reproduce

1. Create an instance of SQLDatabase class. Make sure we pass schema name as argument when initializing.
2. Create node mappings for a database. Make sure DB requires schema name while fetching data.
3. Create object index  for the same.
4. An error will occur when index is being created mentioning that no such table is present in the DB.

### Relevant Logs/Tracbacks

```shell
c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\langchain\__init__.py:24: UserWarning: Importing PromptTemplate from langchain root module is no longer supported.
  warnings.warn(
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string   
    module = importlib.import_module(module_str)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Other Projects\text-to-sql-generator\backend\main.py", line 3, in <module>
    from apis import endpoints
  File "C:\Other Projects\text-to-sql-generator\backend\apis\endpoints.py", line 4, in <module>
    from controller.text_to_sql_controller import text_to_sql_controller
  File "C:\Other Projects\text-to-sql-generator\backend\controller\__init__.py", line 1, in <module>
    from .text_to_sql_controller import text_to_sql_controller
  File "C:\Other Projects\text-to-sql-generator\backend\controller\text_to_sql_controller.py", line 2, in <module>
    from llama_utils import QUERY_ENGINE
  File "C:\Other Projects\text-to-sql-generator\backend\llama_utils\__init__.py", line 5, in <module>
    QUERY_ENGINE = initialize_llama()
  File "C:\Other Projects\text-to-sql-generator\backend\llama_utils\build_engine.py", line 30, in initialize_llama
    obj_index = ObjectIndex.from_objects(
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\llama_index\objects\base.py", line 50, in from_objects
    nodes = object_mapping.to_nodes(objects)
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\llama_index\objects\base_node_mapping.py", line 55, in to_nodes      
    return [self.to_node(obj) for obj in objs]
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\llama_index\objects\base_node_mapping.py", line 55, in <listcomp>    
    return [self.to_node(obj) for obj in objs]
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\llama_index\objects\table_node_mapping.py", line 47, in to_node
    f"{self._sql_database.get_single_table_info(obj.table_name)}\n"
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\llama_index\langchain_helpers\sql_wrapper.py", line 52, in get_single_table_info
    for column in self._inspector.get_columns(table_name):
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\sqlalchemy\engine\reflection.py", line 859, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\sqlalchemy\engine\reflection.py", line 97, in cache
    ret = fn(self, con, *args, **kw)
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\sqlalchemy\dialects\postgresql\base.py", line 3484, in get_columns   
    return self._value_or_raise(data, table_name, schema)
  File "c:\Other Projects\text-to-sql-generator\backend\env\lib\site-packages\sqlalchemy\dialects\postgresql\base.py", line 3452, in _value_or_raise
    raise exc.NoSuchTableError(
sqlalchemy.exc.NoSuchTableError: crawled_products
```

**Comment by ashpytho** [comment]
Please raise the PR

**Comment by devstein** [comment]
Hey @ashpytho Dosu misspoke! It can't create PRs (yet). We'll make sure it stops saying that 😄 

Maybe @logan-markewich or @Disiok provide some assistance

**Comment by jeanaristide22** [comment]
I also encounter the same error despite implementing the solution above. seems like the error lies `elsewhere.

`NoSuchTableError                          Traceback (most recent call last)
Cell In[18], [line 2](vscode-notebook-cell:?execution_count=18&line=2)
      [1](vscode-notebook-cell:?execution_count=18&line=1) query_str = "How many users are created"
----> [2](vscode-notebook-cell:?execution_count=18&line=2) response = query_engine.query(query_str)

File [c:\Users\jeanaristide.aquino\anaconda3\Lib\site-packages\llama_index\core\base_query_engine.py:30](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/core/base_query_engine.py:30), in BaseQueryEngine.query(self, str_or_query_bundle)
     [28](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/core/base_query_engine.py:28) if isinstance(str_or_query_bundle, str):
     [29](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/core/base_query_engine.py:29)     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> [30](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/core/base_query_engine.py:30) return self._query(str_or_query_bundle)

File [c:\Users\jeanaristide.aquino\anaconda3\Lib\site-packages\llama_index\indices\struct_store\sql_query.py:326](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_query.py:326), in BaseSQLTableQueryEngine._query(self, query_bundle)
    [324](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_query.py:324) def _query(self, query_bundle: QueryBundle) -> Response:
    [325](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_query.py:325)     """Answer a query."""
--> [326](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_query.py:326)     retrieved_nodes, metadata = self.sql_retriever.retrieve_with_metadata(
    [327](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_query.py:327)         query_bundle
    [328](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_query.py:328)     )
    [330](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_query.py:330)     sql_query_str = metadata["sql_query"]
    [331](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_query.py:331)     if self._synthesize_response:

File [c:\Users\jeanaristide.aquino\anaconda3\Lib\site-packages\llama_index\indices\struct_store\sql_retriever.py:269](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_retriever.py:269), in NLSQLRetriever.retrieve_with_metadata(self, str_or_query_bundle)
    [267](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_retriever.py:267) else:
    [268](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_retriever.py:268)     query_bundle = str_or_query_bundle
--> [269](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_retriever.py:269) table_desc_str = self._get_table_context(query_bundle)
    [270](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/llama_index/indices/struct_store/sql_retriever.py:270) logger.info(f"> Table desc str: {table_desc_str}")
...
-> [2007](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/sqlalchemy/dialects/oracle/base.py:2007)     raise exc.NoSuchTableError(
   [2008](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/sqlalchemy/dialects/oracle/base.py:2008)         f"{schema}.{table}" if schema else table
   [2009](file:///C:/Users/jeanaristide.aquino/anaconda3/Lib/site-packages/sqlalchemy/dialects/oracle/base.py:2009)     ) from None

NoSuchTableError: cs_user_dct`

**Comment by jeanaristide22** [comment]
```python
def get_table_columns(self, table_name: str) -> List[Any]:
    """Get table columns."""
    return self._inspector.get_columns(table_name, schema=self._schema)

def get_single_table_info(self, table_name: str) -> str:
    """Get table info for a single table."""
    # same logic as table_info, but with specific table names
    template = (
        "Table '{table_name}' has columns: {columns}, "
        "and foreign keys: {foreign_keys}."
    )
    columns = []
    for column in self._inspector.get_columns(table_name, schema=self._schema):
        if column.get("comment"):
            columns.append(
                (
                    f"{column['name']} ({str(column['type'])}): "
                    f"'{column.get('comment')}'"
                )
            )
        else:
            columns.append(f"{column['name']} ({str(column['type'])})")

    column_str = ", ".join(columns)
    foreign_keys = []
    for foreign_key in self._inspector.get_foreign_keys(table_name, schema=self._schema):
        foreign_keys.append(
            f"{foreign_key['constrained_columns']} -> "
            f"{foreign_key['referred_table']}.{foreign_key['referred_columns']}"
        )
    foreign_key_str = ", ".join(foreign_keys)
    table_str = template.format(
        table_name=table_name, columns=column_str, foreign_keys=foreign_key_str
    )
    return table_str
```

**Comment by jeanaristide22** [comment]
Also experiencing this. the solution above didn't work for me. How were you able to solve this?

**Comment by ashpytho** [comment]
Hi @logan-markewich 
Yes the issue still persists. What I did to fix this issue was to create a custom SQL wrapper and add the changes suggested by DosuBot. I can raise a PR if you want me against this issue.

**Comment by logan-markewich** [comment]
@ashpytho yea if you want to make a PR, that would be helpful :)
