### ISSUE TITLE
[Bug]: Cannot serialize VectorStoreIndex object

### ISSUE THREAD

**Issue by BrianP8701** [run-llama/llama_index#8090]
### Bug Description

I want to save the VectorStoreIndex to GCS so i don't need to reindex everytime, but I cant serialize the VectorStoreIndex object

### Version

0.8.43

### Steps to Reproduce

from llama_index import VectorStoreIndex
from llama_index import SimpleDirectoryReader
import time

start_time = time.time()
index=VectorStoreIndex([])

documents = SimpleDirectoryReader('test_library', recursive=True).load_data()
for doc in documents:
    index.insert(doc)
retriever = index.as_retriever()
print("--- %s seconds ---" % (time.time() - start_time))
print(dir(index))

# Assuming you have a VectorStoreIndex object named index
index = VectorStoreIndex.from_vector_store(index)

# Persist the index
index.persist('saved_index.json')

Inside of test_library is just a small pdf

### Relevant Logs/Tracbacks

```shell
(venv) (base) brianprzezdziecki@Brians-MacBook-Pro-6 OI_Memory % /Users/brianprzezdziecki/Code/OI_Memory/venv/bin/python /Users/brianprzezdziecki/Code/OI_Mem
ory/oi_cloud/test.py
--- 4.245954990386963 seconds ---
['__abstractmethods__', '__annotations__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_add_nodes_to_index', '_aget_node_with_embedding', '_async_add_nodes_to_index', '_build_index_from_nodes', '_delete_node', '_docstore', '_get_node_with_embedding', '_graph_store', '_index_struct', '_insert', '_is_protocol', '_service_context', '_show_progress', '_storage_context', '_store_nodes_override', '_use_async', '_vector_store', 'as_chat_engine', 'as_query_engine', 'as_retriever', 'build_index_from_nodes', 'delete', 'delete_nodes', 'delete_ref_doc', 'docstore', 'from_documents', 'from_vector_store', 'index_id', 'index_struct', 'index_struct_cls', 'insert', 'insert_nodes', 'ref_doc_info', 'refresh', 'refresh_ref_docs', 'service_context', 'set_index_id', 'storage_context', 'summary', 'update', 'update_ref_doc', 'vector_store']
Traceback (most recent call last):
  File "/Users/brianprzezdziecki/Code/OI_Memory/oi_cloud/test.py", line 18, in <module>
    index = VectorStoreIndex.from_vector_store(index)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brianprzezdziecki/Code/OI_Memory/venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 65, in from_vector_store
    if not vector_store.stores_text:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VectorStoreIndex' object has no attribute 'stores_text'
```

**Comment by logan-markewich** [comment]
@BrianP8701 you can use the fsspec integration for google cloud buckets

It should be similar to the S3 integration
https://docs.llamaindex.ai/en/stable/core_modules/data_modules/storage/save_load.html#using-a-remote-backend
