### ISSUE TITLE
[Bug]: Langchain parser breaks with llama 70b

### ISSUE THREAD

**Issue by smyja** [run-llama/llama_index#8091]
### Bug Description

Tried to use llama 70b from anyscale with this [langchain parser](https://docs.llamaindex.ai/en/stable/examples/output_parsing/LangchainOutputParserDemo.html) and got this error.

```
******
Could not load OpenAI model. Using default LlamaCPP=llama2-13b-chat. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

******
Traceback (most recent call last):
  File "/Users/mac/Documents/GitHub/datagpt/pluralsh/dev/lib/python3.8/site-packages/llama_index/llms/llama_cpp.py", line 88, in __init__
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "llamas.py", line 32, in <module>
    llm_predictor = StructuredLLMPredictor()
  File "/Users/mac/Documents/GitHub/datagpt/pluralsh/dev/lib/python3.8/site-packages/llama_index/llm_predictor/base.py", line 88, in __init__
    self._llm = resolve_llm(llm)
  File "/Users/mac/Documents/GitHub/datagpt/pluralsh/dev/lib/python3.8/site-packages/llama_index/llms/utils.py", line 40, in resolve_llm
    llm = LlamaCPP(
  File "/Users/mac/Documents/GitHub/datagpt/pluralsh/dev/lib/python3.8/site-packages/llama_index/llms/llama_cpp.py", line 90, in __init__
    raise ImportError(
ImportError: Could not import llama_cpp library.Please install llama_cpp with `pip install llama-cpp-python`.See the full installation guide for GPU support at `https://github.com/abetlen/llama-cpp-python`
```

### Version

0.8.43

### Steps to Reproduce

follow the [guide ](https://docs.llamaindex.ai/en/stable/examples/output_parsing/LangchainOutputParserDemo.html) then setup a custom llm, specifically anyscale.

**Comment by logan-markewich** [comment]
@smyja can you share your setup? This error is because you don't have an openai key set, and something in llama-index is creating an LLM (which is falling back to llama-cpp because you don't have a key set)

**Comment by smyja** [comment]
> @smyja can you share your setup? This error is because you don't have an openai key set, and something in llama-index is creating an LLM (which is falling back to llama-cpp because you don't have a key set)

You are right, i had to export again. I am closing this.
