### ISSUE TITLE
[Bug]: DocumentSummaryIndex() ignores the embed_model setting in service_context

### ISSUE THREAD

**Issue by jc1518** [run-llama/llama_index#8102]
### Bug Description

DocumentSummaryIndex() ignores the embed_model setting.

embed_model is explicitly configured in the service_context to use langchain.embeddings.BedrockEmbedding, but the DocumentSummaryIndex() ignores it and falls back to the default embedding model (try openai first, if not available, try local llamacpp).

### Version

0.8.44

### Steps to Reproduce

The following code can be used:

```python
import boto3
from langchain.embeddings import BedrockEmbeddings
from langchain.llms import Bedrock

from llama_index import (
    LLMPredictor,
    ServiceContext,
    VectorStoreIndex,
    get_response_synthesizer,
)
from llama_hub.web.simple_web.base import SimpleWebPageReader
from llama_index.callbacks import CallbackManager, LlamaDebugHandler
from llama_index.indices.document_summary import DocumentSummaryIndex

# Change the region if needed 
session = boto3.Session(region_name="us-west-2")
boto3_bedrock = session.client("bedrock-runtime")

llm = Bedrock(
    client=boto3_bedrock,
    model_id="anthropic.claude-v2",
    streaming=True,
    verbose=True,
    model_kwargs={"temperature": 0.1, "max_tokens_to_sample": 512},
)

llm_predictor = LLMPredictor(llm)

embed_model = BedrockEmbeddings(
    client=boto3_bedrock,
    model_id="amazon.titan-embed-text-v1",
)

llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])

service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embed_model,
    callback_manager=callback_manager,
)

reader = SimpleWebPageReader(html_to_text=True)
docs = reader.load_data(
    urls=["https://blog.llamaindex.ai/llamaindex-update-2023-10-10-3718a3d19fb9"]
)

# Vector index embedding works fine
index = VectorStoreIndex.from_documents(
    docs, service_context=service_context, show_progress=True
)
query_engine = index.as_query_engine()
print(query_engine.query("What are the updates?"))

response_synthesizer = get_response_synthesizer(
    response_mode="tree_summarize", use_async=True
)

# Summary index embedding falls back to default (OpenAI then llamacpp)
# Even the embed_model is set to use Bedrock in service_context
summary_index = DocumentSummaryIndex(
    docs,
    service_context=service_context,
    response_synthesizer=response_synthesizer,
    show_progress=True,
)
summary_query_engine = summary_index.as_query_engine()
print(summary_query_engine.query("What are the updates?"))

```

### Relevant Logs/Tracbacks

```shell
➜  sandbox python test.py
Parsing documents into nodes: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.06it/s]
Generating embeddings: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [00:09<00:00,  2.77it/s]
**********
Trace: index_construction
    |_node_parsing ->  0.117312 seconds
      |_chunking ->  0.094967 seconds
    |_embedding ->  4.161817 seconds
    |_embedding ->  3.396642 seconds
    |_embedding ->  1.81063 seconds
**********
**********
Trace: query
    |_query ->  14.047066 seconds
      |_retrieve ->  0.273317 seconds
        |_embedding ->  0.269527 seconds
      |_synthesize ->  13.773558 seconds
        |_templating ->  5.4e-05 seconds
        |_llm ->  13.763149 seconds
**********
 Based on the context provided, here are the key updates:

- RetrieverEvaluator allows enhanced retrieval evaluations with benchmarking, metrics, and synthetic dataset creation.

- Added support for 3 more HuggingFace embedding models - base embeddings wrapper, instructor embeddings, and optimum embeddings in ONNX format. 

- Introduced multi-document agents (v0) for advanced QA beyond typical top-k RAG. Supports diverse queries from single to multiple docs.

- Experimenting with ensemble retriever using diverse document chunking and ensembling for improved retrieval.

- Using OpenAI's latest function calling fine-tuning to enhance gpt-3.5-turbo's structured data extraction for RAG.

- Integrated with Arize AI Phoenix for full observability in RAG pipelines - tracking prompts, timing, retrieval visualizations etc. while keeping data local.

- Streamlit hackathon winners - NewsGPT and FinSight.

# This is where the issue is - DocumentSummaryIndex() ignores the embed_model setting in service_context.
******
Could not load OpenAI model. Using default LlamaCPP=llama2-13b-chat. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

******
Traceback (most recent call last):
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/llms/llama_cpp.py", line 88, in __init__
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jackiexc/Desktop/sandbox/test.py", line 53, in <module>
    response_synthesizer = get_response_synthesizer(
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/response_synthesizers/factory.py", line 50, in get_response_synthesizer
    service_context = service_context or ServiceContext.from_defaults(
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 154, in from_defaults
    llm_predictor = llm_predictor or LLMPredictor(llm=llm)
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/llm_predictor/base.py", line 89, in __init__
    self._llm = resolve_llm(llm)
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/llms/utils.py", line 40, in resolve_llm
    llm = LlamaCPP(
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/llms/llama_cpp.py", line 90, in __init__
    raise ImportError(
ImportError: Could not import llama_cpp library.Please install llama_cpp with `pip install llama-cpp-python`.See the full installation guide for GPU support at `https://github.com/abetlen/llama-cpp-python`
```

**Comment by logan-markewich** [comment]
I think it's because the service context on the index isn't passed into the retriever when calling as_query_engine

https://github.com/run-llama/llama_index/blob/5ffd8fb2c63b0528f01c0c9e22aae93e33d0d8c9/llama_index/indices/document_summary/base.py#L128

Would be an easy PR

You can also work around thos right now by passing in the service context to as_query_engine()

**Comment by jc1518** [comment]
> I think it's because the service context on the index isn't passed into the retriever when calling as_query_engine
> 
> https://github.com/run-llama/llama_index/blob/5ffd8fb2c63b0528f01c0c9e22aae93e33d0d8c9/llama_index/indices/document_summary/base.py#L128
> 
> Would be an easy PR
> 
> You can also work around this right now by passing in the service context to as_query_engine()

Thanks @logan-markewich for the input, I tried `set_global_service_context(service_context)`, now it gives another different error.
```
**********
Trace: index_construction
    |_exception ->  0.0 seconds
**********
Traceback (most recent call last):
  File "/Users/jackiexc/Desktop/sandbox/test.py", line 63, in <module>
    summary_index = DocumentSummaryIndex(
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/indices/document_summary/base.py", line 89, in __init__
    super().__init__(
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/indices/base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/indices/base.py", line 171, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/indices/document_summary/base.py", line 213, in _build_index_from_nodes
    self._add_nodes_to_index(index_struct, nodes, self._show_progress)
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/indices/document_summary/base.py", line 156, in _add_nodes_to_index
    raise ValueError(
ValueError: ref_doc_id of node cannot be None when building a document summary index
```

**Comment by logan-markewich** [comment]
Correct -- you should use `DocumentSummaryIndex.from_documents(documents)` so that the node parser is applied and that attribute is set properly

**Comment by jc1518** [comment]
> Correct -- you should use `DocumentSummaryIndex.from_documents(documents)` so that the node parser is applied and that attribute is set properly

I tried this:
```
summary_index = DocumentSummaryIndex(
    response_synthesizer=response_synthesizer,
    show_progress=True,
).from_documents(docs)
```
then get a new error:
```
Traceback (most recent call last):
  File "/Users/jackiexc/Desktop/sandbox/test.py", line 63, in <module>
    summary_index = DocumentSummaryIndex(
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/indices/document_summary/base.py", line 89, in __init__
    super().__init__(
  File "/Users/jackiexc/.pyenv/versions/3.10.12/lib/python3.10/site-packages/llama_index/indices/base.py", line 47, in __init__
    raise ValueError("One of nodes or index_struct must be provided.")
ValueError: One of nodes or index_struct must be provided.
```

**Comment by jc1518** [comment]
> Correct -- you should use `DocumentSummaryIndex.from_documents(documents)` so that the node parser is applied and that attribute is set properly

Ah, thanks! All good now, after changed it to `summary_index = DocumentSummaryIndex.from_documents(docs, show_progress=True)`
