### ISSUE TITLE
[Bug]: LlamaIndex doesn't currently support Python 3.12

### ISSUE THREAD

**Issue by yisding** [run-llama/llama_index#8153]
### Bug Description

LlamaIndex doesn't currently support the latest stable version of Python: 3.12.0.

I believe we're blocked on this release: https://github.com/aio-libs/aiohttp/issues/7675

### Version

0.8.45.post1

### Steps to Reproduce

Install Python 3.12.0

pip install llama-index

**Comment by cay89** [comment]
Hi,

Can anyone inform me about the severity of the issues with Python 3.12? I've initiated a new project using 3.12 and would like to proceed with it.

**Comment by logan-markewich** [comment]
Tbh I haven't even tried with 3.12 yet. There might be zero issues and we just need to loosen the pyproject.toml reqs

**Comment by jamesbraza** [comment]
After https://github.com/run-llama/llama_index/pull/9213, and changing `pyproject.toml` to have `python = ">=3.8.1,<4"`, it's possible to have a successful `poetry lock` with Python 3.12.0 🥳 .

However, when running `poetry install --with dev`, I hit a `numpy` build error `ModuleNotFoundError: No module named 'distutils'`. This seems related to https://numpy.org/doc/stable/reference/distutils_status_migration.html.  Moving to `setuptools<60` as it requests did not fix the installation issue for me.

So if someone wants to figure out this `numpy` install issue, I think LlamaIndex can have 3.12 support.

**Comment by jonathanpv** [comment]
> After #9213, and changing `pyproject.toml` to have `python = ">=3.8.1,<4"`, it's possible to have a successful `poetry lock` with Python 3.12.0 🥳 .
> 
> However, when running `poetry install --with dev`, I hit a `numpy` build error `ModuleNotFoundError: No module named 'distutils'`. This seems related to https://numpy.org/doc/stable/reference/distutils_status_migration.html. Moving to `setuptools<60` as it requests did not fix the installation issue for me.
> 
> So if someone wants to figure out this `numpy` install issue, I think LlamaIndex can have 3.12 support.

I'm getting the same error from numpy, gonna try that setuptools thing

Also I'm fairly new to poetry and python in general, however poetry seems miles better than requirements.txt

**Comment by jonathanpv** [comment]
> > After #9213, and changing `pyproject.toml` to have `python = ">=3.8.1,<4"`, it's possible to have a successful `poetry lock` with Python 3.12.0 🥳 .
> > However, when running `poetry install --with dev`, I hit a `numpy` build error `ModuleNotFoundError: No module named 'distutils'`. This seems related to https://numpy.org/doc/stable/reference/distutils_status_migration.html. Moving to `setuptools<60` as it requests did not fix the installation issue for me.
> > So if someone wants to figure out this `numpy` install issue, I think LlamaIndex can have 3.12 support.
> 
> I'm getting the same error from numpy, gonna try that setuptools thing
> 
> Also I'm fairly new to poetry and python in general, however poetry seems miles better than requirements.txt

hmm seesm like setuptools is another packaging tool, gonna try seeing what poetry needs from me

**Comment by jonathanpv** [comment]
this is what i get
```
teto@Ashleys-iMac InternHelper % poetry install
Updating dependencies
Resolving dependencies... (6.9s)

Package operations: 45 installs, 0 updates, 0 removals

  - Installing numpy (1.24.4): Failed

  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.
  
  Traceback (most recent call last):
    File "/Users/teto/.local/pipx/venvs/poetry/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "/private/var/folders/lc/4tns9ms91bzgsptncmlrmplm0000gp/T/tmpv520bwny/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
      import distutils.core
  ModuleNotFoundError: No module named 'distutils'
  

  at ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with numpy (1.24.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "numpy (==1.24.4)"'.

```

using 3.12 seems like

**Comment by jonathanpv** [comment]
update:
so i ended up switching over to python3.8.1

and don't have issues with the dependency after running poetry install

i'm using m1 macos and had issues installing python3.8.1 with pyenv
so i just installed it using the installer in the official python downloads

after installing python3.8 it was then just a matter using pyenv to make that the global python usage

then in poetry to make the env using python3.8.1 you do:

```
poetry env use python3.8
poetry shell
poetry install
```

**Comment by ranga291257** [comment]
I will wait till it works for Python 12.x
