### ISSUE TITLE
[Documentation]: Example for custom embedding model doesn't work

### ISSUE THREAD

**Issue by geodavic** [run-llama/llama_index#8186]
### Documentation Issue Description

Running the example for the [custom embedding model](https://docs.llamaindex.ai/en/stable/core_modules/model_modules/embeddings/usage_pattern.html#custom-embedding-model) doesn't work, as it returns a pydantic error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't instantiate abstract class InstructorEmbeddings with abstract methods _aget_query_embedding, class_name
```

Even after implementing the `_aget_query_embedding` and `class_name` methods as follows:

```
    def _aget_query_embedding(self, query: Union[str, List[str]]) -> List[float]:
        return self._get_query_embedding(text)

    def class_name(cls) -> str:
        return self.instructor_model_name
```

a pydantic error raises:

```
max_seq_length  512
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gtorres/dev/rag/initial_testing/embedding.py", line 46, in __init__
    self._model = INSTRUCTOR(instructor_model_name)
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "InstructorEmbeddings" object has no field "_model"
```

### Documentation Link

https://docs.llamaindex.ai/en/stable/core_modules/model_modules/embeddings/usage_pattern.html#custom-embedding-model

**Comment by logan-markewich** [comment]
Opened a PR with the fix

If you are curious, here is the updated example

```python
from pydantic import PrivateAttr
from typing import Any, List
from InstructorEmbedding import INSTRUCTOR
from llama_index.embeddings.base import BaseEmbedding

class InstructorEmbeddings(BaseEmbedding):
  _model: Any = PrivateAttr()
  _instruction: str = PrivateAttr()

  def __init__(
    self,
    model_name: str = "hkunlp/instructor-large",
    instruction: str = "Represent the Computer Science documentation or question:",
    embed_batch_size: int = 2,
    **kwargs: Any,
  ) -> None:
    self._model = INSTRUCTOR(model_name)
    self._instruction = instruction
    super().__init__(model_name=model_name, embed_batch_size=embed_batch_size, **kwargs)

  @classmethod
  def class_name(cls) -> str:
    return "InstructorEmbedding"

  def _get_query_embedding(self, query: str) -> List[float]:
    embeddings = self._model.encode([[self._instruction, query]])
    return embeddings[0]

  def _get_text_embedding(self, text: str) -> List[float]:
    embeddings = self._model.encode([[self._instruction, text]])
    return embeddings[0]

  def _get_text_embeddings(self, texts: List[str]) -> List[List[float]]:
    embeddings = self._model.encode([[self._instruction, text] for text in texts])
    return embeddings

  async def _aget_query_embedding(self, query: str) -> List[float]:
    return self._get_query_embedding(query)

  async def _aget_text_embedding(self, text: str) -> List[float]:
    return self._get_text_embedding(text)
```

**Comment by limoncc** [comment]
I test. you need add self.__class__._model not self._model in v0.9.40
```python
from pydantic import PrivateAttr
from typing import Any, List
from InstructorEmbedding import INSTRUCTOR
from llama_index.embeddings.base import BaseEmbedding

class InstructorEmbeddings(BaseEmbedding):
  _model: Any = PrivateAttr()
  _instruction: str = PrivateAttr()

  def __init__(
    self,
    model_name: str = "hkunlp/instructor-large",
    instruction: str = "Represent the Computer Science documentation or question:",
    embed_batch_size: int = 2,
    **kwargs: Any,
  ) -> None:
    self.__class__._model = INSTRUCTOR(model_name)
    self.__class__._instruction = instruction
    super().__init__(model_name=model_name, embed_batch_size=embed_batch_size, **kwargs)
```

**Comment by logan-markewich** [comment]
@limoncc that's kind of hacky.

This example is updated properly these days
https://docs.llamaindex.ai/en/stable/examples/embeddings/custom_embeddings.html#custom-embeddings-implementation
