### ISSUE TITLE
[Bug]: self.ctx is not None:

### ISSUE THREAD

**Issue by Lowpower** [run-llama/llama_index#8252]
### Bug Description

error loading model: unknown (magic, version) combination: 46554747, 00000002; is this really a GGML file?
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/Users/shengzhiqiang/dev/LLM/new-chat-flow-created-at-2023-10-23/llama_langchain.py", line 11, in <module>
    llm = llms.LlamaCPP(
          ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 110, in __init__
    self._model = Llama(model_path=model_path, **model_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/llama_cpp/llama.py", line 313, in __init__
    assert self.model is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception ignored in: <function Llama.__del__ at 0x11ddb6b60>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/llama_cpp/llama.py", line 1510, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'

### Version

new

### Steps to Reproduce

wen i load llama.cpp/models/llama-2-13b.Q4_0.gguf

**Comment by Lowpower** [comment]
ok， my version is 0.1.77,  I upgrade to 0.2.11 it works
