### ISSUE TITLE
[Question]: llama-index package connectivity issue in an offline environment

### ISSUE THREAD

**Issue by wilberlee** [run-llama/llama_index#8452]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

After deploying the project in an intranet environment, when I tried to import llama_index for the first time, I encountered an error due to the lack of internet connectivity in the intranet environment.  Even with just one line of code: "import llama_index," the same error occurs.

I was able to reproduce this issue on a computer in an internet-connected environment as well. I first connected to the internet and installed llama-index, then disconnected from the network. When I attempted to import llama_index for the first time, I encountered the same error mentioned above. 
The error message is as follows:
`
Traceback (most recent call last):
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdb307d3640>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdb307d3640>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/llm_group/code/Llama_index_for_kg/demo-kg-build-main/graph_rag_chatbot.py", line 10, in <module>
    from llama_index import PromptHelper
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/__init__.py", line 20, in <module>
    from llama_index.indices.keyword_table import (
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import (
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import (
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/indices/keyword_table/base.py", line 17, in <module>
    from llama_index.indices.base import BaseIndex
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/indices/base.py", line 6, in <module>
    from llama_index.chat_engine.types import BaseChatEngine, ChatMode
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/chat_engine/__init__.py", line 1, in <module>
    from llama_index.chat_engine.condense_question import CondenseQuestionChatEngine
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/chat_engine/condense_question.py", line 6, in <module>
    from llama_index.chat_engine.types import (
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/chat_engine/types.py", line 11, in <module>
    from llama_index.memory import BaseMemory
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/memory/__init__.py", line 1, in <module>
    from llama_index.memory.chat_memory_buffer import ChatMemoryBuffer
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/memory/chat_memory_buffer.py", line 16, in <module>
    class ChatMemoryBuffer(BaseMemory):
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/memory/chat_memory_buffer.py", line 22, in ChatMemoryBuffer
    default_factory=cast(Callable[[], Any], GlobalsHelper().tokenizer),
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/llama_index/utils.py", line 50, in tokenizer
    enc = tiktoken.get_encoding("gpt2")
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/tiktoken_ext/openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/tiktoken/load.py", line 75, in data_gym_to_mergeable_bpe_ranks
    vocab_bpe_contents = read_file_cached(vocab_bpe_file).decode()
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/tiktoken/load.py", line 48, in read_file_cached
    contents = read_file(blobpath)
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/tiktoken/load.py", line 24, in read_file
    resp = requests.get(blobpath)
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/miniconda3/envs/graph_rag_1018/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdb307d3640>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Process finished with exit code 1
`

**Comment by Disiok** [comment]
looks like it's trying to download some necessary files for `tiktoken` (mostly used for tokenization, token counting) etc.

This might be a solution: https://stackoverflow.com/questions/76106366/how-to-use-tiktoken-in-offline-mode-computer

**Comment by wilberlee** [comment]
> looks like it's trying to download some necessary files for `tiktoken` (mostly used for tokenization, token counting) etc.
> 
> This might be a solution: https://stackoverflow.com/questions/76106366/how-to-use-tiktoken-in-offline-mode-computer

Thank you for your suggestion. It indeed turned out to be an issue with `tiktoken`. While debugging into `load.py` of `tiktoken`, I found that the `read_file_cache `function reads from a cache file and directory. By copying this directory from the internet-connected server to the intranet, I was able to resolve my problem. @Disiok
