### ISSUE TITLE
[Bug]: Retry query engine does not work with Auto query engine

### ISSUE THREAD

**Issue by Sawaiz8** [run-llama/llama_index#8492]
### Bug Description

When I try to wrapper my Sql autovector engine class with the retry query engine. I get the following error:
**Traceback (most recent call last):
  File "/home/sawaiz/Documents/Lab/Hamza Projects/Secure-GPT/Initial code/query_engine.py", line 649, in <module>
    RESPONSE = eng.query(
  File "/home/sawaiz/Documents/Lab/Hamza Projects/Secure-GPT/Initial code/query_engine.py", line 333, in query
    return str(self.query_engine.query(query))
  File "/home/sawaiz/anaconda3/envs/llamaindex/lib/python3.9/site-packages/llama_index/indices/query/base.py", line 32, in query
    return self._query(str_or_query_bundle)
  File "/home/sawaiz/anaconda3/envs/llamaindex/lib/python3.9/site-packages/llama_index/query_engine/sql_join_query_engine.py", line 314, in _query
    if result.ind == 0:
  File "/home/sawaiz/anaconda3/envs/llamaindex/lib/python3.9/site-packages/llama_index/selectors/types.py", line 27, in ind
    raise ValueError(
ValueError: There are 2 selections, please use .inds.**

I want to retry for querying because I am not the right answer in my query with the database:
![image](https://github.com/run-llama/llama_index/assets/97668778/fbb5c157-b995-41a3-8203-8c6434a44a2f)

### Version

0.8.51

### Steps to Reproduce

Use the Auto Query engine and just wrapp it with router query engine at the end. 
I am using the following function to wrap it:

    def _router(self, autoQueryEngine):
        query_response_evaluator = RelevancyEvaluator()
        retry_query_engine = RetryQueryEngine(
            autoQueryEngine, query_response_evaluator
        )
        return retry_query_engine

Why does it not work?

**Comment by Disiok** [comment]
I think the error you are encountering isn't related to using retry query engine on top of the auto query engine.
Looks it's just that the LLM is not generating the correct query in the auto query engine. Maybe try with a different model e.g. GPT-4 if you are not using that to see if it resolves the issue.
