### ISSUE TITLE
[Bug]: OpenInferenceCallbackHandler error

### ISSUE THREAD

**Issue by Inkorak** [run-llama/llama_index#8576]
### Bug Description

Error when using OpenInferenceCallbackHandler. 'str' object has no attribute 'node'

### Version

0.8.55

### Steps to Reproduce

The problem is when you use a OpenInferenceCallbackHandler with a recursive retriever that uses a router retrievers.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/home/user/PycharmProjects/QA_llm/prototype_v2/data_agent.py", line 138, in <module>
    response = data_agent.stream_chat(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/agent/react/base.py", line 451, in stream_chat
    reasoning_steps, _ = self._process_actions(
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/agent/react/base.py", line 198, in _process_actions
    tool_output = tool.call(**reasoning_step.action_input)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/PycharmProjects/QA_llm/prototype_v2/custom_query_engine.py", line 19, in call
    response = self._query_engine.query(query_str)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/indices/query/base.py", line 32, in query
    return self._query(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py", line 176, in _query
    nodes = self.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py", line 128, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/indices/base_retriever.py", line 34, in retrieve
    return self._retrieve(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py", line 185, in _retrieve
    retrieved_nodes, _ = self._retrieve_rec(query_bundle, query_id=None)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py", line 161, in _retrieve_rec
    nodes_to_add, additional_nodes = self._query_retrieved_nodes(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py", line 99, in _query_retrieved_nodes
    cur_retrieved_nodes, cur_additional_nodes = self._retrieve_rec(
                                                ^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py", line 158, in _retrieve_rec
    nodes = obj.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/indices/base_retriever.py", line 34, in retrieve
    return self._retrieve(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/retrievers/router_retriever.py", line 96, in _retrieve
    query_event.on_end(payload={EventPayload.NODES: retrieved_results})
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/callbacks/base.py", line 258, in on_end
    self._callback_manager.on_event_end(
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/callbacks/base.py", line 116, in on_event_end
    handler.on_event_end(event_type, payload, event_id=event_id, **kwargs)
  File "/home/user/anaconda3/envs/transformers/lib/python3.11/site-packages/llama_index/callbacks/open_inference_callback.py", line 210, in on_event_end
    node = node_with_score.node
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'node'
```

**Comment by Inkorak** [comment]
Still not working.
