### ISSUE TITLE
[Bug]:Exception raised on load_index_from_storage() and VectorStoreIndex.from_vector_store().

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#8769]
### Bug Description

TypeError is raised when loading an index due to an unexpected keyword argument 'socket_options'

### Version

0.8.64

### Steps to Reproduce

Try loading an index using either load_index_from_storage() or VectorStoreIndex.from_vector_store()

### Relevant Logs/Tracbacks

```shell
###load_index_from_storage()
Traceback (most recent call last):
  File "/home/gich2009/Work/BAYESNET/lib/nets/comparisonChatEngine.py", line 273, in <module>
    chatbot = ComparisonChatBot(
  File "/home/gich2009/Work/BAYESNET/lib/nets/comparisonChatEngine.py", line 88, in __init__
    self.setup_query_engines()
  File "/home/gich2009/Work/BAYESNET/lib/nets/comparisonChatEngine.py", line 159, in setup_query_engines
    self.setup_index(context=context)
  File "/home/gich2009/Work/BAYESNET/lib/nets/comparisonChatEngine.py", line 190, in setup_index
    self.index = load_index_from_storage(storage_context)
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/indices/loading.py", line 33, in load_index_from_storage
    indices = load_indices_from_storage(storage_context, index_ids=index_ids, **kwargs)
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/indices/loading.py", line 78, in load_indices_from_storage
    index = index_cls(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 49, in __init__
    super().__init__(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/indices/base.py", line 61, in __init__
    self._service_context = service_context or ServiceContext.from_defaults()
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 157, in from_defaults
    llm_predictor = llm_predictor or LLMPredictor(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/llm_predictor/base.py", line 92, in __init__
    self._llm = resolve_llm(llm)
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/llms/utils.py", line 20, in resolve_llm
    llm = OpenAI()
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/llms/openai.py", line 116, in __init__
    self._client, self._aclient = self._get_clients(**kwargs)
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/llms/openai.py", line 119, in _get_clients
    client = SyncOpenAI(**self._get_credential_kwargs())
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/openai/_client.py", line 105, in __init__
    super().__init__(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/openai/_base_client.py", line 738, in __init__
    self._client = http_client or httpx.Client(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/httpx/_client.py", line 672, in __init__
    self._transport = self._init_transport(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/httpx/_client.py", line 720, in _init_transport
    return HTTPTransport(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/httpx/_transports/default.py", line 136, in __init__
    self._pool = httpcore.ConnectionPool(
TypeError: ConnectionPool.__init__() got an unexpected keyword argument 'socket_options'







###VectorStoreIndex.from_vector_store():
Traceback (most recent call last):
  File "/home/gich2009/Work/BAYESNET/lib/nets/comparisonChatEngine.py", line 273, in <module>
    chatbot = ComparisonChatBot(
  File "/home/gich2009/Work/BAYESNET/lib/nets/comparisonChatEngine.py", line 88, in __init__
    self.setup_query_engines()
  File "/home/gich2009/Work/BAYESNET/lib/nets/comparisonChatEngine.py", line 159, in setup_query_engines
    self.setup_index(context=context)
  File "/home/gich2009/Work/BAYESNET/lib/nets/comparisonChatEngine.py", line 197, in setup_index
    self.index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 71, in from_vector_store
    return cls(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 49, in __init__
    super().__init__(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/indices/base.py", line 61, in __init__
    self._service_context = service_context or ServiceContext.from_defaults()
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 157, in from_defaults
    llm_predictor = llm_predictor or LLMPredictor(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/llm_predictor/base.py", line 92, in __init__
    self._llm = resolve_llm(llm)
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/llms/utils.py", line 20, in resolve_llm
    llm = OpenAI()
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/llms/openai.py", line 116, in __init__
    self._client, self._aclient = self._get_clients(**kwargs)
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/llama_index/llms/openai.py", line 119, in _get_clients
    client = SyncOpenAI(**self._get_credential_kwargs())
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/openai/_client.py", line 105, in __init__
    super().__init__(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/openai/_base_client.py", line 738, in __init__
    self._client = http_client or httpx.Client(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/httpx/_client.py", line 672, in __init__
    self._transport = self._init_transport(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/httpx/_client.py", line 720, in _init_transport
    return HTTPTransport(
  File "/home/gich2009/Work/BAYESNET/venv-fastapi/lib/python3.10/site-packages/httpx/_transports/default.py", line 136, in __init__
    self._pool = httpcore.ConnectionPool(
TypeError: ConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
```

**Comment by gich2009** [comment]
Thanks
