### ISSUE TITLE
[Question]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices while trying out index.as_chat_engine()

### ISSUE THREAD

**Issue by junpuf** [run-llama/llama_index#8789]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I encountered an issue while following the [Customization Tutorial](https://docs.llamaindex.ai/en/stable/getting_started/customization.html) for the section “I want a chatbot instead of Q&A”. Below is the error i got:
```
Starting Q&A Session...
User: tell me about the author

llama_print_timings:        load time =    3864.22 ms
llama_print_timings:      sample time =      77.19 ms /   117 runs   (    0.66 ms per token,  1515.66 tokens per second)
llama_print_timings: prompt eval time =    3862.87 ms /   512 tokens (    7.54 ms per token,   132.54 tokens per second)
llama_print_timings:        eval time =   32098.75 ms /   117 runs   (  274.35 ms per token,     3.65 tokens per second)
llama_print_timings:       total time =   36425.16 ms
Traceback (most recent call last):
  File "/fsx/save/llama_index/starter.py", line 94, in <module>
    main(num_gpus, args.model_url, args.data_path)
 ...
    File "/fsx/conda/envs/llama_index/lib/python3.10/site-packages/llama_index/embeddings/huggingface.py", line 175, in _get_query_embedding
    return self._embed([query])[0]
  File "/fsx/conda/envs/llama_index/lib/python3.10/site-packages/llama_index/embeddings/huggingface.py", line 154, in _embed
    model_output = self._model(**encoded_input)
  File "/fsx/conda/envs/llama_index/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/conda/envs/llama_index/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1006, in forward
    embedding_output = self.embeddings(
  File "/fsx/conda/envs/llama_index/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/conda/envs/llama_index/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 232, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/fsx/conda/envs/llama_index/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fsx/conda/envs/llama_index/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/fsx/conda/envs/llama_index/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

The code that i am using

```python
import logging
import sys
import os.path
import argparse

import torch
from llama_index import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    ServiceContext,
    StorageContext,
    load_index_from_storage,
)
from llama_index.llms import LlamaCPP
from llama_index.llms.llama_utils import (
    messages_to_prompt,
    completion_to_prompt,
)
from llama_index.embeddings import HuggingFaceEmbedding

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))


def main(num_gpus, model_url, data_path):
    def initialize_index(num_gpus, model_url):
        llm = LlamaCPP(
            # You can pass in the URL to a GGML model to download it automatically
            model_url=model_url,
            # optionally, you can set the path to a pre-downloaded model instead of model_url
            model_path=None,
            temperature=0.1,
            max_new_tokens=256,
            # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
            context_window=3900,
            # kwargs to pass to __call__()
            generate_kwargs={},
            # kwargs to pass to __init__()
            # set to at least 1 to use GPU
            model_kwargs={"n_gpu_layers": num_gpus},
            # transform inputs into Llama2 format
            messages_to_prompt=messages_to_prompt,
            completion_to_prompt=completion_to_prompt,
            verbose=True,
        )
        # use Huggingface embeddings
        embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
        
        # create a service context
        service_context = ServiceContext.from_defaults(
            llm=llm,
            embed_model=embed_model,
        )

        # check if storage already exists
        if not os.path.exists("./storage"):
            print("load the documents and create the index")
            documents = SimpleDirectoryReader(data_path).load_data()
            for doc in documents:
                print(doc.metadata)
            # create vector store index
            index = VectorStoreIndex.from_documents(documents, service_context=service_context)
            # store it for later
            index.storage_context.persist()
        else:
            print("load the existing index")
            storage_context = StorageContext.from_defaults(persist_dir="./storage")
            index = load_index_from_storage(storage_context, service_context=service_context)
        return index

    try:
        index = initialize_index(num_gpus, model_url)
        # query_engine = index.as_query_engine()
        query_engine = index.as_chat_engine()
        print("Starting Q&A Session...")
        while True:
            user_input = input("User: ")
            response = query_engine.chat(user_input)
            # response = query_engine.query(user_input)
            print(f"LLM: {response}")
    except KeyboardInterrupt:
        print("\nProgram terminated by user (Ctrl+C). Exiting.")
        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Continuous input processing with command-line arguments")
    parser.add_argument("--model_url", type=str, default="https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q4_0.gguf", help="URL of the model")
    parser.add_argument("--data_path", type=str, default="./data/conda", help="Path to data")
    args = parser.parse_args()
    if torch.cuda.is_available():
        # Get the number of available GPUs
        num_gpus = torch.cuda.device_count()
        print(f"Number of available GPUs: {num_gpus}")
        main(num_gpus, args.model_url, args.data_path)
    else:
        print("No GPUs available on this system.")
```

Appreciate any help on this.

**Comment by logan-markewich** [comment]
Since you have multiple GPUs, another option is specifying the device exactly in the embeddings

`HuggingFaceEmbeddings(device="cuda:0", ...)`
