### ISSUE TITLE
[Bug]: When using the Milvus database, inserting too many nodes will cause the insertion to fail.   

### ISSUE THREAD

**Issue by Tangent-90C** [run-llama/llama_index#8869]
### Bug Description

When I try to reproduce this tutorial using Milvus as a vector database, I get an error.

https://gpt-index.readthedocs.io/en/stable/examples/node_postprocessor/MetadataReplacementDemo.html

```
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "grpc: received message larger than max (79782097 vs. 67108864)"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:19530 {created_time:"2023-11-12T08:47:41.991414553+00:00", grpc_status:8, grpc_message:"grpc: received message larger than max (79782097 vs. 67108864)"}"
```

I guessed that this was caused by too many entities being inserted into the database at once, so I tried to insert fewer nodes and it worked.

failed:
![image](https://github.com/run-llama/llama_index/assets/28804414/2ff69772-14fc-48c3-9fcc-022713bfb5aa)

succeed:
![image](https://github.com/run-llama/llama_index/assets/28804414/69538e0a-78b1-4efa-8329-c0a39609387c)

### Version

0.8.68

### Steps to Reproduce

run the code

```
from llama_index import SimpleDirectoryReader
from llama_index.node_parser import SentenceWindowNodeParser, SimpleNodeParser
from llama_index import VectorStoreIndex, StorageContext
from llama_index.vector_stores import MilvusVectorStore
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index.llms import OpenAI
from llama_index import ServiceContext
import openai
import os

os.environ["OPENAI_API_KEY"] = "sk-xxxxxxxxxxxxxxxxxxxxxxx"
openai.api_key = os.environ["OPENAI_API_KEY"]

llm = OpenAI(model="gpt-3.5-turbo", temperature=0.1)
embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/all-mpnet-base-v2", max_length=512
)

documents = SimpleDirectoryReader(
    input_files=["./IPCC_AR6_WGII_Chapter03.pdf"]
).load_data()

node_parser = SentenceWindowNodeParser.from_defaults(
    window_size=3,
    window_metadata_key="window",
    original_text_metadata_key="original_text",
)
nodes = node_parser.get_nodes_from_documents(documents)

ctx = ServiceContext.from_defaults(
    llm=llm,
    embed_model=embed_model,
    node_parser=node_parser,
)

storage_context = StorageContext.from_defaults(
    vector_store=MilvusVectorStore(collection_name="IPCC_sentence", dim="768")
)

VectorStoreIndex(nodes, service_context=ctx, storage_context=storage_context)
```

This is the required PDF file:
https://www.ipcc.ch/report/ar6/wg2/downloads/report/IPCC_AR6_WGII_Chapter03.pdf

This is how my Milvus deployed:
https://milvus.io/docs/install_standalone-docker.md

### Relevant Logs/Tracbacks

```shell
E:\envs\openai\python.exe E:\llama-index-test\run.py 
grpc RpcError: [insert_rows], <_MultiThreadedRendezvous: StatusCode.RESOURCE_EXHAUSTED, grpc: received message larger than max (79782097 vs. 67108864)>, <Time:{'RPC start': '2023-11-12 16:47:41.239809', 'gRPC error': '2023-11-12 16:47:41.998676'}>
Failed to insert batch starting at entity: 0/11087
Traceback (most recent call last):
  File "E:\llama-index-test\run.py", line 40, in <module>
    VectorStoreIndex(nodes, service_context=ctx, storage_context=storage_context)
  File "E:\envs\openai\lib\site-packages\llama_index\indices\vector_store\base.py", line 49, in __init__
    super().__init__(
  File "E:\envs\openai\lib\site-packages\llama_index\indices\base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "E:\envs\openai\lib\site-packages\llama_index\indices\vector_store\base.py", line 254, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
  File "E:\envs\openai\lib\site-packages\llama_index\indices\vector_store\base.py", line 235, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "E:\envs\openai\lib\site-packages\llama_index\indices\vector_store\base.py", line 189, in _add_nodes_to_index
    new_ids = self._vector_store.add(nodes, **insert_kwargs)
  File "E:\envs\openai\lib\site-packages\llama_index\vector_stores\milvus.py", line 180, in add
    self.milvusclient.insert(self.collection_name, insert_list)
  File "E:\envs\openai\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 206, in insert
    raise ex from ex
  File "E:\envs\openai\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 198, in insert
    res = conn.insert_rows(collection_name, insert_batch, timeout=timeout)
  File "E:\envs\openai\lib\site-packages\pymilvus\decorators.py", line 141, in handler
    raise e from e
  File "E:\envs\openai\lib\site-packages\pymilvus\decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "E:\envs\openai\lib\site-packages\pymilvus\decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "E:\envs\openai\lib\site-packages\pymilvus\decorators.py", line 79, in handler
    raise e from e
  File "E:\envs\openai\lib\site-packages\pymilvus\decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "E:\envs\openai\lib\site-packages\pymilvus\client\grpc_handler.py", line 505, in insert_rows
    response = rf.result()
  File "E:\envs\openai\lib\site-packages\grpc\_channel.py", line 797, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "grpc: received message larger than max (79782097 vs. 67108864)"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:19530 {created_time:"2023-11-12T08:47:41.991414553+00:00", grpc_status:8, grpc_message:"grpc: received message larger than max (79782097 vs. 67108864)"}"
>

Process finished with exit code 1
```

**Comment by Tangent-90C** [comment]
> _🤖_
> 
> The error you're encountering, "grpc: received message larger than max", is a gRPC error that occurs when the size of the data being sent in a single request exceeds the maximum limit set by the gRPC framework. In the context of Milvus and LlamaIndex, this error can occur when you're trying to insert a large number of nodes into the Milvus database in a single request.
> 
> To resolve this issue, you can break down the large batch of nodes into smaller batches and insert them separately. This can be done by modifying the `add` method in the `MilvusVectorStore` class. Here's an example of how you can do this:
> 
> ```python
> def add(self, nodes: List[BaseNode], batch_size: int = 1000, **add_kwargs: Any) -> List[str]:
>     """Add the embeddings and their nodes into Milvus.
> 
>     Args:
>         nodes (List[BaseNode]): List of nodes with embeddings
>             to insert.
>         batch_size (int): The number of nodes to insert in a single request.
> 
>     Raises:
>         MilvusException: Failed to insert data.
> 
>     Returns:
>         List[str]: List of ids inserted.
>     """
>     insert_ids = []
> 
>     # Process that data we are going to insert
>     for i in range(0, len(nodes), batch_size):
>         batch_nodes = nodes[i:i+batch_size]
>         insert_list = []
> 
>         for node in batch_nodes:
>             entry = node_to_metadata_dict(node)
>             entry[MILVUS_ID_FIELD] = node.node_id
>             entry[self.embedding_field] = node.embedding
> 
>             insert_ids.append(node.node_id)
>             insert_list.append(entry)
> 
>         # Insert the data into milvus
>         self.milvusclient.insert(self.collection_name, insert_list)
>         logger.debug(
>             f"Successfully inserted embeddings into: {self.collection_name} "
>             f"Num Inserted: {len(insert_list)}"
>         )
> 
>     return insert_ids
> ```
> 
> In this modified `add` method, the `nodes` are divided into smaller batches of size `batch_size`, and each batch is inserted separately. This should prevent the "grpc: received message larger than max" error from occurring. Please adjust the `batch_size` according to your specific requirements and the limitations of your system.
> 
> As for the maximum size of data that can be sent in a single request by the gRPC framework in the current LlamaIndex implementation, I wasn't able to find an exact answer within the repository. However, the error message suggests that the current limit is around 67MB. You might want to consider this when deciding on the batch size for your insertions.
> 
> I hope this helps! If you have any other questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [llama_index/vector_stores/milvus.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/milvus.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I knew I could break up a large number of nodes into smaller batches and insert them separately, but I wanted lama-index to automatically break up these large numbers of nodes into smaller batches instead of doing it myself.

**Comment by Tangent-90C** [comment]
> _🤖_
> 
> To modify the LlamaIndex code to automatically divide large numbers of nodes into smaller batches for insertion, you can modify the method in the class.`add``MilvusVectorStore`
> 
> Here's how you can do it:
> 
> ```python
> from llama_index.utils import iter_batch
> 
> class MilvusVectorStore(VectorStore):
>     # ... existing code ...
> 
>     def add(self, nodes: List[BaseNode], **add_kwargs: Any) -> List[str]:
>         """Add the embeddings and their nodes into Milvus.
> 
>         Args:
>             nodes (List[BaseNode]): List of nodes with embeddings
>                 to insert.
> 
>         Raises:
>             MilvusException: Failed to insert data.
> 
>         Returns:
>             List[str]: List of ids inserted.
>         """
>         insert_ids = []
> 
>         # Process that data we are going to insert
>         for batch_nodes in iter_batch(nodes, self.config.batch_size):
>             insert_list = []
>             for node in batch_nodes:
>                 entry = node_to_metadata_dict(node)
>                 entry[MILVUS_ID_FIELD] = node.node_id
>                 entry[self.embedding_field] = node.embedding
> 
>                 insert_ids.append(node.node_id)
>                 insert_list.append(entry)
> 
>             # Insert the data into milvus
>             self.milvusclient.insert(self.collection_name, insert_list)
>             logger.debug(
>                 f"Successfully inserted embeddings into: {self.collection_name} "
>                 f"Num Inserted: {len(insert_list)}"
>             )
> 
>         return insert_ids
> ```
> 
> In the above code, we are dividing the nodes into smaller batches of size and then inserting each batch into the Milvus vector store. This will help to avoid the gRPC error "grpc: received message larger than max" when dealing with large numbers of nodes.`self.config.batch_size`
> 
> Please note that is a utility function that you would need to implement. It should take an iterable and a batch size as input, and yield batches of the specified size. Here's a simple implementation:`iter_batch`
> 
> ```python
> def iter_batch(iterable, batch_size):
>     iterator = iter(iterable)
>     for first in iterator:
>         yield list(itertools.chain([first], itertools.islice(iterator, batch_size - 1)))
> ```
> 
> This function uses and to efficiently create batches from the input iterable.`itertools.chain``itertools.islice`
> 
> Please replace with the appropriate batch size that suits your needs. This batch size should be small enough to avoid the gRPC error but large enough to ensure efficient data insertion.`self.config.batch_size`
> 
> I hope this helps! Let me know if you have any other questions.
> 
> ## Sources
> * [llama_index/vector_stores/postgres.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/postgres.py)
> * [llama_index/vector_stores/milvus.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/milvus.py)
> * [llama_index/vector_stores/chroma.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/chroma.py)
> * [llama_index/vector_stores/myscale.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/myscale.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosu-bot
Good work, so can you submit a PR yourself to fix this BUG?
