### ISSUE TITLE
[Bug]: cannot deepcopy TextNode

### ISSUE THREAD

**Issue by stdweird** [run-llama/llama_index#8895]
### Bug Description

when trying to use the metadataextractor, it fails with deepcopy a TextNode. this can be reproduced with

```
>>> t=TextNode(text='abc')
>>> deepcopy(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
  File "/home/me/.local/lib/python3.11/site-packages/llama_index/schema.py", line 48, in __getstate__
    state["__dict__"].pop("tokenizer", None)
    ~~~~~^^^^^^^^^^^^
KeyError: '__dict__'
```

This is with #8889 in place, using the original code of latest release i get 

```  File "/home/me/.local/lib/python3.11/site-packages/llama_index/node_parser/extractors/metadata_extractors.py", line 116, in process_nodes
    new_nodes = [deepcopy(node) for node in nodes]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.local/lib/python3.11/site-packages/llama_index/node_parser/extractors/metadata_extractors.py", line 116, in <listcomp>
    new_nodes = [deepcopy(node) for node in nodes]
                 ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/copy.py", line 273, in _reconstruct
    y.__setstate__(state)
  File "pydantic/main.py", line 416, in pydantic.main.BaseModel.__setstate__
KeyError: '__dict__'

```

### Version

latest 0.8.68, and with #8889 as well

### Steps to Reproduce

>>> t=TextNode(text='abc')
>>> deepcopy(t)

**Comment by logan-markewich** [comment]
@stdweird this will be fixed in the next release. You can install from source to yet the fix now, but should have it out in a few hours

**Comment by stdweird** [comment]
@logan-markewich i'll wait for the release. thanks for the quick followup

**Comment by logan-markewich** [comment]
v0.8.69 should be out in about 1 minute (just kicked off the auto build)
