### ISSUE TITLE
[Bug] AttributeError in LiteLLM class with litellm==1.0.0

### ISSUE THREAD

**Issue by SeeknnDestroy** [run-llama/llama_index#8906]
### Bug Description

I am encountering an error when trying to use litellm through llama-index, following the example provided in the [llama-index documentation](https://docs.llamaindex.ai/en/stable/examples/llm/litellm.html#call-complete-with-a-prompt). This issue arose after the release of litellm version 1.0.0, which supports OpenAI v1.0.0+. 

This seems to be a compatibility issue with the new versions of litellm and llama-index, especially after the recent updates to support OpenAI v1.0.0+. Any insights or fixes for this issue would be greatly appreciated.

When running the provided example code, I receive an `AttributeError` related to the `pop` method on a `Message` object.

### Version

- llama-index: 0.8.68 - litellm: 1.0.0

### Steps to Reproduce

1. Set up the environment with the latest versions of llama-index and litellm.
2. Run the following code from the [llama-index documentation](https://docs.llamaindex.ai/en/stable/examples/llm/litellm.html#call-complete-with-a-prompt):

   ```python
   import os
   from llama_index.llms import LiteLLM, ChatMessage
   from dotenv import load_dotenv

   load_dotenv()

   message = ChatMessage(role="user", content="Hey! how's it going?")

   # llm params
   model = "gpt-3.5-turbo"
   temperature = 0.9
   max_tokens = 512
   # openai call
   llm = LiteLLM(model=model, temperature=temperature, max_tokens=max_tokens)
   chat_response = llm.chat([message])

   print(chat_response)
   ```

### Relevant Logs/Tracbacks

```shell
/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/pydantic/main.py:308: UserWarning: Pydantic serializer warnings:
  Expected `Usage` but got `dict` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
message_dict: Message(content="Hello! I'm an AI language model, so I don't have feelings, but I'm here to help you. How can I assist you today?", role='assistant')
additional_kwargs: Message(content="Hello! I'm an AI language model, so I don't have feelings, but I'm here to help you. How can I assist you today?", role='assistant')
Traceback (most recent call last):
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/pydantic/main.py", line 751, in __getattr__
    return pydantic_extra[item]
KeyError: 'pop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/seekndestroy/safeVideo/github/autollm/testing.py", line 15, in <module>
    chat_response = llm.chat([message])
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/llama_index/llms/base.py", line 187, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/llama_index/llms/litellm.py", line 123, in chat
    return chat_fn(messages, **kwargs)
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/llama_index/llms/litellm.py", line 195, in _chat
    message = from_openai_message_dict(message_dict)
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/llama_index/llms/litellm_utils.py", line 169, in from_openai_message_dict
    additional_kwargs.pop("role")
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/pydantic/main.py", line 753, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'Message' object has no attribute 'pop'
```

**Comment by fcakyon** [comment]
Hey @krrishdholakia, can you help us on this issue?
