### ISSUE TITLE
[Bug]: TextNode object has no attribute __fields_set__

### ISSUE THREAD

**Issue by stdweird** [run-llama/llama_index#8907]
### Bug Description

`QuestionsAnsweredExtractor` triggers following error during `MetadataExtractor.process_nodes` when processing TextNode

```

  File "/home/me/.local/lib/python3.11/site-packages/llama_index/node_parser/extractors/metadata_extractors.py", line 118, in process_nodes                      
    cur_metadata_list = extractor.extract(new_nodes)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.local/lib/python3.11/site-packages/llama_index/node_parser/extractors/metadata_extractors.py", line 386, in extract                            
    node.excluded_llm_metadata_keys = ["questions_this_excerpt_can_answer"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 405, in pydantic.main.BaseModel.__setattr__
AttributeError: 'TextNode' object has no attribute '__fields_set__'

```

(fyi TitleExtractor and KeywordExtractor work fine)

### Version

0.8.69

### Steps to Reproduce

will add once i get access back to the system

**Comment by prd-tuong-nguyen** [comment]
same problem

**Comment by stdweird** [comment]
much easier reproducer
```
>>> n1=TextNode(text='abc')
>>> n2=deepcopy(n1)
>>> n2.embedding=1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 405, in pydantic.main.BaseModel.__setattr__
AttributeError: 'TextNode' object has no attribute '__fields_set__'
```

**Comment by prd-tuong-nguyen** [comment]
go back to v0.8.65 work for me
