### ISSUE TITLE
[Bug]: The starter tutorial failed with "ModuleNotFoundError: No module named 'jinja2'"

### ISSUE THREAD

**Issue by eoinoreilly30** [run-llama/llama_index#8969]
### Bug Description

Created a venv, ran pip install llama-index.

Followed the steps in the starter tutorial: https://docs.llamaindex.ai/en/stable/getting_started/starter_example.html

Ran the python script and it failed with "ModuleNotFoundError: No module named 'jinja2'"

pip install jinja2 fixed it.

### Version

0.9.2

### Steps to Reproduce

python  -m venv venv
. venv/bin/activate
pip install llama-index

main.py:
`
from llama_index import VectorStoreIndex, SimpleDirectoryReader

print("Loading data...")
documents = SimpleDirectoryReader("data").load_data()

print("Indexing...")
index = VectorStoreIndex.from_documents(documents)

query_engine = index.as_query_engine()

print("Querying...")
response = query_engine.query("What did the author do growing up?")
print(response)
`

python main.py

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/github/llm/venv/lib/python3.10/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/.pyenv/versions/3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jinja2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/github/llm/main.py", line 9, in <module>
    query_engine = index.as_query_engine()
  File "/Users/github/llm/venv/lib/python3.10/site-packages/llama_index/indices/base.py", line 344, in as_query_engine
    from llama_index.query_engine.retriever_query_engine import RetrieverQueryEngine
  File "/Users/github/llm/venv/lib/python3.10/site-packages/llama_index/query_engine/__init__.py", line 21, in <module>
    from llama_index.query_engine.retry_query_engine import (
  File "/Users/github/llm/venv/lib/python3.10/site-packages/llama_index/query_engine/retry_query_engine.py", line 6, in <module>
    from llama_index.evaluation.base import BaseEvaluator
  File "/Users/github/llm/venv/lib/python3.10/site-packages/llama_index/evaluation/__init__.py", line 15, in <module>
    from llama_index.evaluation.notebook_utils import get_retrieval_results_df
  File "/Users/github/llm/venv/lib/python3.10/site-packages/llama_index/evaluation/notebook_utils.py", line 7, in <module>
    from pandas.io.formats.style import Styler
  File "/Users/github/llm/venv/lib/python3.10/site-packages/pandas/io/formats/style.py", line 44, in <module>
    jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
  File "/Users/github/llm/venv/lib/python3.10/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.
```

**Comment by Ademola111** [comment]
@dosu-bot is this issue closed or still open and can i still proceed on doing it
