### ISSUE TITLE
[Bug]: Using ChatPromptTemplate with context_str no longer works in 0.9 because of faulty _get_available_chunk_size logic

### ISSUE THREAD

**Issue by martinkozle** [run-llama/llama_index#9020]
### Bug Description

The behavior of `ChatPromptTemplate` in llama_index 0.9 has changed so that it no longer works with context_str. It fails in the function for checking available chunk size. In version 0.9 a commit was added (95e77ab9e1e61719e7e759523638cbb1b980417a) which does custom logic for this specific class, which I believe is faulty.

The specific code snippet that errors is in `llama_index/indices/prompt_helper.py`:

```python
# get string variables (if any)
template_vars = [
    var
    for _, var, _, _ in Formatter().parse(str(message))
    if var is not None
]

# figure out which variables are partially formatted
used_vars = {}
for var_name, val in prompt.kwargs.items():
    if var_name in template_vars:
        used_vars[var_name] = val

# format partial message
if len(used_vars) > 0 and partial_message.content is not None:
    partial_message.content = partial_message.content.format(
        **used_vars
    )
```

I kept trying to understand what this part of code is trying to do, and according to the code and the comment I could only guess that it is trying to replace only parts of the prompt string. But this is not how the Python format method works.

For example:

```python
>>> "{arg1} {arg2}".format(arg1=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'arg2'
```

If this is truly what the code is supposed to do then I suggest adding a default value to `used_vars` like so:

```python
# get string variables (if any)
template_vars = [
    var
    for _, var, _, _ in Formatter().parse(str(message))
    if var is not None
]

# figure out which variables are partially formatted
used_vars = {template_var: f"{{{template_var}}}" for template_var in template_vars}
for var_name, val in prompt.kwargs.items():
    if var_name in template_vars:
        used_vars[var_name] = val

# format partial message
if len(used_vars) > 0 and partial_message.content is not None:
    partial_message.content = partial_message.content.format(
        **used_vars
    )
```

This change would replace the fields that do not have values back to their unformatted selves.
But since this function is trying to estimate the length, then they could maybe be replaced with any dummy value that would be an estimate.

In any case, some default value has to be given to the missing fields so it doesn't error out. If you have a suggestion what this could be I can submit a PR.

### Version

0.9

### Steps to Reproduce

I tried to create a mock code that doesn't depend on anything else:

```python
import os

from llama_index import ChatPromptTemplate, PromptTemplate, ServiceContext
from llama_index.llms.base import ChatMessage, MessageRole
from llama_index.llms.mock import MockLLM
from llama_index.response_synthesizers import get_response_synthesizer
from llama_index.schema import NodeWithScore, TextNode

os.environ["OPENAI_API_KEY"] = "..."

PROMPT_TEMPLATE_STR = """
SYSTEM
{context_str}
Query: {query_str}
Answer:
"""

CHAT_PROMPT_TEMPLATE = """
SYSTEM
__&&__
{context_str}
Query: {query_str}
Answer:
"""


prompt_template = PromptTemplate(PROMPT_TEMPLATE_STR)

system_user_delimiter = "__&&__"
system_prompt, user_prompt = CHAT_PROMPT_TEMPLATE.split(system_user_delimiter)
message_templates = [
    ChatMessage(content=system_prompt, role=MessageRole.SYSTEM),
    ChatMessage(content=user_prompt, role=MessageRole.USER),
]
chat_prompt_template = ChatPromptTemplate(message_templates=message_templates)


service_context = ServiceContext.from_defaults(llm=MockLLM(10))
mock_nodes = [NodeWithScore(node=TextNode(text="abc"))]

chat_prompt_synthesizer = get_response_synthesizer(
    service_context=service_context,
    text_qa_template=prompt_template,
)
prompt_response = chat_prompt_synthesizer.synthesize(query="...", nodes=mock_nodes)
print(prompt_response)
print("=" * 10)

chat_prompt_synthesizer = get_response_synthesizer(
    service_context=service_context, text_qa_template=chat_prompt_template
)
chat_prompt_response = chat_prompt_synthesizer.synthesize(query="...", nodes=mock_nodes)
print(chat_prompt_response)
```

In llama_index 0.8 it outputs:

```
text text text text text text text text text text
==========
text text text text text text text text text text
```

While in llama_index 0.9 it errors with (paths are redacted):

```
text text text text text text text text text text
==========
Traceback (most recent call last):
  File ".../scripts/bug_report_example.py", line 53, in <module>
    chat_prompt_response = chat_prompt_synthesizer.synthesize(query="...", nodes=mock_nodes)
  File ".../.venv/lib/python3.10/site-packages/llama_index/response_synthesizers/base.py", line 146, in synthesize
    response_str = self.get_response(
  File ".../.venv/lib/python3.10/site-packages/llama_index/response_synthesizers/compact_and_refine.py", line 38, in get_response
    return super().get_response(
  File ".../.venv/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 127, in get_response
    response = self._give_response_single(
  File ".../.venv/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 169, in _give_response_single
    text_chunks = self._service_context.prompt_helper.repack(
  File ".../.venv/lib/python3.10/site-packages/llama_index/indices/prompt_helper.py", line 270, in repack
    text_splitter = self.get_text_splitter_given_prompt(
  File ".../.venv/lib/python3.10/site-packages/llama_index/indices/prompt_helper.py", line 228, in get_text_splitter_given_prompt
    chunk_size = self._get_available_chunk_size(
  File ".../.venv/lib/python3.10/site-packages/llama_index/indices/prompt_helper.py", line 198, in _get_available_chunk_size
    partial_message.content = partial_message.content.format(
KeyError: 'context_str'
```

**Comment by logan-markewich** [comment]
@martinkozle The original code is basically attempting to only call `format()` on the chat message that actually a) has the proper string variables and b) has the var available to format, in order to estimate length yea.

Your suggested fix seems good enough for now -- I will use that with some minor tweaks (thanks a ton btw for diagnosing)
