### ISSUE TITLE
ImportError: cannot import name 'TrafilaturaWebReader' from 'llama_index'

### ISSUE THREAD

**Issue by sqpollen** [run-llama/llama_index#9046]
### Bug Description

TrafilaturaWebReader doesn't seem to be included in the latest version of LLamaIndex.

`from llama_index import TrafilaturaWebReader`

gives

```Traceback (most recent call last):
  File "/Users/***/***/pinecone-index/insert.py", line 1, in <module>
    from lib.utils import init_vector, save_page
  File "/Users/***/***/pinecone-index/lib/utils.py", line 7, in <module>
    from llama_index import TrafilaturaWebReader
ImportError: cannot import name 'TrafilaturaWebReader' from 'llama_index'
```

### Version

0.9.4

### Steps to Reproduce

`pip install llama-index`

import into your Python file

`from llama_index import TrafilaturaWebReader`

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/***/***/pinecone-index/insert.py", line 1, in <module>
    from lib.utils import init_vector, save_page
  File "/Users/***/***/pinecone-index/lib/utils.py", line 7, in <module>
    from llama_index import TrafilaturaWebReader
ImportError: cannot import name 'TrafilaturaWebReader' from 'llama_index'
```

**Comment by sqpollen** [comment]
```
pip install trafilatura
pip freeze > requirements.txt
```

# requirements.txt

```
aiohttp==3.9.0
aiosignal==1.3.1
aiostream==0.5.2
annotated-types==0.6.0
anyio==3.7.1
attrs==23.1.0
beautifulsoup4==4.12.2
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
courlan==0.9.4
dataclasses-json==0.5.14
dateparser==1.2.0
Deprecated==1.2.14
distro==1.8.0
dnspython==2.4.2
frozenlist==1.4.0
fsspec==2023.10.0
greenlet==3.0.1
h11==0.14.0
htmldate==1.5.2
httpcore==1.0.2
httpx==0.25.1
idna==3.4
joblib==1.3.2
jusText==3.0.0
langcodes==3.3.0
llama-index==0.9.4
loguru==0.7.2
lxml==4.9.2
marshmallow==3.20.1
multidict==6.0.4
mypy-extensions==1.0.0
nest-asyncio==1.5.8
nltk==3.8.1
numpy==1.26.2
openai==1.3.3
packaging==23.2
pandas==2.1.3
pinecone-client==2.2.4
pydantic==2.5.1
pydantic_core==2.14.3
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.10.3
requests==2.31.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
SQLAlchemy==2.0.23
tenacity==8.2.3
tiktoken==0.5.1
tld==0.13
tqdm==4.66.1
trafilatura==1.6.2
typing-inspect==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
tzlocal==5.2
urllib3==1.26.18
wrapt==1.16.0
yarl==1.9.3
```

same error

`ImportError: cannot import name 'TrafilaturaWebReader' from 'llama_index'`

**Comment by sqpollen** [comment]
Trafilatura has been moved to a LLamaHub loader

https://llamahub.ai/l/web-trafilatura_web
