### ISSUE TITLE
[Bug]: OpenAIAgent does not work anymore with Azure

### ISSUE THREAD

**Issue by ret2libc** [run-llama/llama_index#9084]
### Bug Description

Recently OpenAI has changed the schema for calling functions, replacing `functions` with `tools`. llama-index seems to have adapted the OpenAIAgent to follow the new schema, but Azure OpenAI still follow the old schema and it should probably support it until there will be Azure OpenAI versions that have that.

### Version

0.9.5

### Steps to Reproduce

```python
from llama_index.llms import AzureOpenAI, OpenAI
from llama_index.agent import OpenAIAgent
from llama_index.tools import BaseTool, FunctionTool
import sys
import os

def multiply(a: int, b: int) -> int:
    """Multiple two integers and returns the result integer"""
    return a * b

def add(a: int, b: int) -> int:
    """Add two integers and returns the result integer"""
    return a + b

multiply_tool = FunctionTool.from_defaults(fn=multiply)
add_tool = FunctionTool.from_defaults(fn=add)

if os.getenv("OPENAI_API_TYPE") == "azure":
    llm = AzureOpenAI(deployment="gpt-4", api_version="2023-07-01-preview")
else:
    llm = OpenAI()

agent = OpenAIAgent.from_tools([multiply_tool, add_tool], llm=llm, verbose=True)
print(agent.chat(sys.argv[1]))
```

This works:
```
OPENAI_API_KEY=<openai-api-key> OPENAI_LOG=debug python test.py '2+3'
```

This does not work:
```
OPENAI_API_KEY=<azure-api-key> OPENAI_API_TYPE=azure OPENAI_LOG=debug AZURE_OPENAI_DEPLOYMENT=gpt-4 AZURE_OPENAI_ENDPOINT=<azure-openai-endpoint> python test.py '2+3'
```

### Relevant Logs/Tracbacks

```shell
[2023-11-22 14:14:59 - httpx:78 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2023-11-22 14:14:59 - httpx:144 - DEBUG] load_verify_locations cafile='/venv/lib/python3.11/site-packages/certifi/cacert.pem'
[2023-11-22 14:14:59 - httpx:78 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2023-11-22 14:14:59 - httpx:144 - DEBUG] load_verify_locations cafile='/venv/lib/python3.11/site-packages/certifi/cacert.pem'
STARTING TURN 1
---------------

[2023-11-22 14:14:59 - openai._base_client:427 - DEBUG] Request options: {'method': 'post', 'url': '/deployments/gpt-4/chat/completions', 'files': None, 'json_data': {'messages': [{'role': <MessageRole.USER: 'user'>, 'content': '2+3'}], 'model': 'gpt-4', 'stream': False, 'temperature': 0.1, 'tool_choice': 'auto', 'tools': [{'type': 'function', 'function': {'name': 'multiply', 'description': 'multiply(a: int, b: int) -> int\nMultiple two integers and returns the result integer', 'parameters': {'title': 'multiply', 'type': 'object', 'properties': {'a': {'title': 'A', 'type': 'integer'}, 'b': {'title': 'B', 'type': 'integer'}}, 'required': ['a', 'b']}}}, {'type': 'function', 'function': {'name': 'add', 'description': 'add(a: int, b: int) -> int\nAdd two integers and returns the result integer', 'parameters': {'title': 'add', 'type': 'object', 'properties': {'a': {'title': 'A', 'type': 'integer'}, 'b': {'title': 'B', 'type': 'integer'}}, 'required': ['a', 'b']}}}]}, 'headers': {'api-key': '<api-key>'}}
[2023-11-22 14:14:59 - httpx:1013 - INFO] HTTP Request: POST https://<endpoint>.azure.com//openai/deployments/gpt-4/chat/completions?api-version=2023-07-01-preview "HTTP/1.1 400 model_error"
[2023-11-22 14:14:59 - openai._base_client:867 - DEBUG] HTTP Request: POST https://<endpoint>.azure.com//openai/deployments/gpt-4/chat/completions?api-version=2023-07-01-preview "400 model_error"
Traceback (most recent call last):
  File "/test.py", line 24, in <module>
    print(agent.chat(sys.argv[1]))
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/llama_index/agent/openai_agent.py", line 438, in chat
    chat_response = self._chat(
                    ^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/llama_index/agent/openai_agent.py", line 360, in _chat
    agent_chat_response = self._get_agent_response(mode=mode, **llm_chat_kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/llama_index/agent/openai_agent.py", line 322, in _get_agent_response
    chat_response: ChatResponse = self._llm.chat(**llm_chat_kwargs)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/llama_index/llms/base.py", line 187, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/llama_index/llms/openai.py", line 191, in chat
    return chat_fn(messages, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/llama_index/llms/openai.py", line 244, in _chat
    response = self._client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
           ^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/openai/_base_client.py", line 842, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/openai/_base_client.py", line 885, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'Unrecognized request arguments supplied: tool_choice, tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by logan-markewich** [comment]
@ret2libc pretty sure you need to redeploy azure with a newer api version.

For example, I can confirm this worked in colab just yesterday

https://colab.research.google.com/drive/1-lX9cG3P3KFaLxSCqT6-YidCOp627a4i?usp=sharing

**Comment by ret2libc** [comment]
Thanks a lot! Sorry for the noise :)
