### ISSUE TITLE
[Bug]: HuggingFace Optimum ONNX Embeddings not working

### ISSUE THREAD

**Issue by vanduyta** [run-llama/llama_index#9139]
### Bug Description

I am trying to follow the documentation and use HuggingFace Optimum ONNX Embeddings. However, it is not working on my m1 device. I have tried to convert the model from huggingface and also the onnx model which present in the repo.  Therefore, there should be no error in the conversion. Maybe the problem is with apple silicon. Any tips appreciated.

### Version

0.9.7

### Steps to Reproduce

```
from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_hub.file.pymu_pdf.base import PyMuPDFReader
from llama_index import ServiceContext
import torch
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index.embeddings import OptimumEmbedding
import os

folder_path = "./multilingual-e5-large_onnx_console"

if os.path.exists(folder_path) and os.path.isdir(folder_path):
    print(f"The folder '{folder_path}' exists already and so does the optimum model.")
else:
    print(f"The folder '{folder_path}' does not exist yet. Creating optimum model")
    OptimumEmbedding.create_and_save_optimum_model(
        "intfloat/multilingual-e5-large", folder_path
    )

torch.device("mps")
embed_model = OptimumEmbedding(folder_name=folder_path)

service_context = ServiceContext.from_defaults(embed_model=embed_model, llm=None)
# Load documents and build index
documents = SimpleDirectoryReader(
    "your_path",
    required_exts=[".pdf"],
    file_extractor={".pdf": PyMuPDFReader()},
    num_files_limit=2,
).load_data()
index = VectorStoreIndex.from_documents(documents, service_context=service_context, show_progress=True)

```

### Relevant Logs/Tracbacks

```shell
Generating embeddings:   0%|          | 0/61 [00:00<?, ?it/s]2023-11-25 13:03:03.817589 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Gather node. Name:'/embeddings/position_embeddings/Gather' Status Message: indices element out of data bounds, idx=514 must be within the inclusive range [-514,513]
Traceback (most recent call last):
  File "script.py", line 30, in <module>
    index = VectorStoreIndex.from_documents(documents, service_context=service_context, show_progress=True)
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/indices/base.py", line 106, in from_documents
    return cls(
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py", line 49, in __init__
    super().__init__(
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/indices/base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py", line 255, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py", line 236, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py", line 189, in _add_nodes_to_index
    nodes = self._get_node_with_embedding(nodes, show_progress)
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py", line 101, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/indices/utils.py", line 137, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/embeddings/base.py", line 255, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/embeddings/huggingface_optimum.py", line 175, in _get_text_embeddings
    return self._embed(texts)
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/llama_index/embeddings/huggingface_optimum.py", line 136, in _embed
    model_output = self._model(**encoded_input)
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/optimum/modeling_base.py", line 90, in __call__
    return self.forward(*args, **kwargs)
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/optimum/onnxruntime/modeling_ort.py", line 954, in forward
    outputs = self.model.run(None, onnx_inputs)
  File "/Users/miniforge3/envs/llamaindex/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'/embeddings/position_embeddings/Gather' Status Message: indices element out of data bounds, idx=514 must be within the inclusive range [-514,513]
Generating embeddings:  15%|█▍        | 9/61 [00:00<00:00, 108.37it/s]
```

**Comment by vanduyta** [comment]
Closing, it was because of the wrong length of input sequences and also the wrong tokenizer.

**Comment by stephanedebove** [comment]
@vanduyta do you care sharing your working code? I’m also trying to use the intfloat/multilingual-e5-large model as the embedding model but I’m getting "out of range" issues. How did you set the input length and what tokenizer did you use? My code looks like this:


```
llm_replicate = Replicate(
    model="tomasmcm/zephyr-7b-beta:961cd6665b811d0c43c0b9488b6dfa85ff5c7bfb875e93b4533e4c7f96c7c526",
)

from llama_index.embeddings import HuggingFaceEmbedding
embed_model = HuggingFaceEmbedding(model_name="intfloat/multilingual-e5-large")

from llama_index import set_global_tokenizer
# huggingface
from transformers import AutoTokenizer
set_global_tokenizer(
    AutoTokenizer.from_pretrained("HuggingFaceH4/zephyr-7b-beta").encode
)

service_context = ServiceContext.from_defaults(
    llm=llm_replicate, 
    embed_model="local:intfloat/multilingual-e5-large", 
)

documents = SimpleDirectoryReader("data").load_data()
index = VectorStoreIndex.from_documents(documents, service_context=service_context, show_progress=True)
```

**Comment by vanduyta** [comment]
Hi @stephanedebove ,  in my example I had to add a text splitter that makes sure that the input chunks have the correct length. 

```
from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_hub.file.pymu_pdf.base import PyMuPDFReader
from llama_index import ServiceContext
import torch
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index.embeddings import OptimumEmbedding
import os

folder_path = "./multilingual-e5-large_onnx_console"

if os.path.exists(folder_path) and os.path.isdir(folder_path):
    print(f"The folder '{folder_path}' exists already and so does the optimum model.")
else:
    print(f"The folder '{folder_path}' does not exist yet. Creating optimum model")
    OptimumEmbedding.create_and_save_optimum_model(
        "intfloat/multilingual-e5-large", folder_path
    )

torch.device("mps")
embed_model = OptimumEmbedding(folder_name=folder_path)

# This part fixed it
text_splitter = TokenTextSplitter(
    chunk_size=512,
    chunk_overlap=10,
    tokenizer=AutoTokenizer.from_pretrained("intfloat/multilingual-e5-large").encode,
)

service_context = ServiceContext.from_defaults(
    embed_model=embed_model, llm=None, text_splitter=text_splitter
)
# Up to here

# Load documents and build index
documents = SimpleDirectoryReader(
    "your_path",
    required_exts=[".pdf"],
    file_extractor={".pdf": PyMuPDFReader()},
    num_files_limit=2,
).load_data()
index = VectorStoreIndex.from_documents(documents, service_context=service_context, show_progress=True)
```

**Comment by stephanedebove** [comment]
ok thanks and nothing else? I’m getting a

```
  File "C:\Users\Stephane\Documents\llamaindex\test.py", line 115, in <module>
    index = VectorStoreIndex.from_documents(documents, service_context=service_context, show_progress=True)
  File "C:\Users\Stephane\miniconda3\envs\llamaindex\lib\site-packages\llama_index\indices\base.py", line 99, in from_documents
    nodes = run_transformations(
  File "C:\Users\Stephane\miniconda3\envs\llamaindex\lib\site-packages\llama_index\ingestion\pipeline.py", line 70, in run_transformations
    nodes = transform(nodes, **kwargs)
TypeError: 'str' object is not callable
```

error when I add these lines.
