### ISSUE TITLE
[Bug]: Llama index Guidance for Sub-Question Query Engine

### ISSUE THREAD

**Issue by xHeler** [run-llama/llama_index#9339]
### Bug Description

Guidence package with the newest version throwing an error with openai library.
Version of guidance 0.0.64.
Version of llamaindex 0.9.12

### Version

0.9.12

### Steps to Reproduce

Just try to run our google colab example:
https://docs.llamaindex.ai/en/latest/examples/output_parsing/guidance_sub_question.html#

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 665, in __call__
    out = await self.llm.caller(**call_args)
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 348, in _library_call
    prev_base = openai.api_base
AttributeError: module 'openai' has no attribute 'api_base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 109, in run
    await self.visit(self.parse_tree, VariableStack([self.program._variables], self))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 559, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 524, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/usr/local/lib/python3.10/dist-packages/guidance/library/_geneach.py", line 119, in geneach
    new_content += await parser.visit(
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 559, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 559, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 266, in visit
    visited_children = [await self.visit(child, variable_stack, next_node, next_next_node, prev_node, node, parent_node) for child in node]
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 266, in <listcomp>
    visited_children = [await self.visit(child, variable_stack, next_node, next_next_node, prev_node, node, parent_node) for child in node]
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 379, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/usr/local/lib/python3.10/dist-packages/guidance/library/_gen.py", line 140, in gen
    gen_obj = await parser.llm_session(
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 667, in __call__
    except openai.error.RateLimitError:
AttributeError: module 'openai' has no attribute 'error'

Error in program:  module 'openai' has no attribute 'error'
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/llama_index/output_parsers/utils.py in parse_json_markdown(text)
     44     try:
---> 45         json_obj = json.loads(json_string)
     46     except json.JSONDecodeError as e_json:

22 frames
JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 14 (char 15)

During handling of the above exception, another exception occurred:

ParserError                               Traceback (most recent call last)
ParserError: while parsing a flow mapping
  in "<unicode string>", line 2, column 13:
      "items": [{#geneach 'items' stop=']'}{#unl ... 
                ^
expected ',' or '}', but got '<scalar>'
  in "<unicode string>", line 3, column 47:
     ... n": "{gen 'sub_question' stop='"'}",
                                         ^

During handling of the above exception, another exception occurred:

OutputParserException                     Traceback (most recent call last)
OutputParserException: Got invalid JSON object. Error: Expecting property name enclosed in double quotes: line 2 column 14 (char 15) while parsing a flow mapping
  in "<unicode string>", line 2, column 13:
      "items": [{#geneach 'items' stop=']'}{#unl ... 
                ^
expected ',' or '}', but got '<scalar>'
  in "<unicode string>", line 3, column 47:
     ... n": "{gen 'sub_question' stop='"'}",
                                         ^. Got JSON string: {
  "items": [{#geneach 'items' stop=']'}{#unless @first}, {/unless}{
  "sub_question": "{gen 'sub_question' stop='"'}",
  "tool_name": "{gen 'tool_name' stop='"'}",
}{/geneach}],
}

The above exception was the direct cause of the following exception:

OutputParserException                     Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/llama_index/prompts/guidance_utils.py in parse_pydantic_from_guidance_program(program, cls, verbose)
    150         sub_questions = cls.parse_obj(json_dict)
    151     except Exception as e:
--> 152         raise OutputParserException(
    153             "Failed to parse pydantic object from guidance program"
    154         ) from e

OutputParserException: Failed to parse pydantic object from guidance program
```

**Comment by SeeknnDestroy** [comment]
same here. I tried to run the colab notebook with the latest version of `guidance==0.1.5` and it does not even recognize `guidance.llms` and having the following error at line:

```python
question_gen = GuidanceQuestionGenerator.from_defaults(
    guidance_llm=guidance.llms.OpenAI("text-davinci-003"), verbose=False
)
```

```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-14-7a045db4cc78>](https://localhost:8080/#) in <cell line: 1>()
      1 question_gen = GuidanceQuestionGenerator.from_defaults(
----> 2     guidance_llm=guidance.llms.OpenAI("text-davinci-003"), verbose=False
      3 )

AttributeError: module 'guidance' has no attribute 'llms'
```

**Comment by stepp1** [comment]
First, @xHeler's issue is due to changes in pydantic's v2 and isn't catched by any tests because there are no checks of inheritance in `tests/program/test_guidance.py`. Second, @SeeknnDestroy you're using the newest version of guidance and llama_index still uses v0.0.64.

**Comment by stepp1** [comment]
None of the issues above reproduce when installing: `"guidance==0.0.63"` and `"pydantic==1.*"`

**Comment by SeeknnDestroy** [comment]
@stepp1 thanks for the clarification. Probably it will be better to specify which version should we use on the docs for other users too

**Comment by xHeler** [comment]
> First, @xHeler's issue is due to changes in pydantic's v2. These aren't catched by any tests because `tests/program/test_guidance.py` doesn't check for inheritance (Specifically, this seems an issue with `llama_index.prompts.guidance_utils:pydantic_to_guidance_output_template_markdown`).
> 
> Second, @SeeknnDestroy yours is a totally different issue. You're using the newest version of guidance and llama_index still uses v0.0.64.

I used this suggested versions, but still has an error like this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 543, in __call__
    out = await self.llm.caller(**call_args)
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 292, in _library_call
    prev_base = openai.api_base
AttributeError: module 'openai' has no attribute 'api_base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 111, in run
    await self.visit(self.parse_tree, VariableStack([self.program._variables], self))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 535, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 500, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/usr/local/lib/python3.10/dist-packages/guidance/library/_geneach.py", line 121, in geneach
    new_content += await parser.visit(
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 535, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 535, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 256, in visit
    visited_children = [await self.visit(child, variable_stack, next_node, next_next_node, prev_node, node, parent_node) for child in node]
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 256, in <listcomp>
    visited_children = [await self.visit(child, variable_stack, next_node, next_next_node, prev_node, node, parent_node) for child in node]
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 353, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/usr/local/lib/python3.10/dist-packages/guidance/library/_gen.py", line 141, in gen
    gen_obj = await parser.llm_session(
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 545, in __call__
    except openai.error.RateLimitError:
AttributeError: module 'openai' has no attribute 'error'

Error in program:  module 'openai' has no attribute 'error'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py](https://localhost:8080/#) in __call__(self, prompt, stop, stop_regex, temperature, n, max_tokens, logprobs, top_p, echo, logit_bias, token_healing, pattern, stream, cache_seed, caching, **completion_kwargs)
    542                         call_args["logit_bias"] = {str(k): v for k,v in logit_bias.items()} # convert keys to strings since that's the open ai api's format
--> 543                     out = await self.llm.caller(**call_args)
    544 

20 frames
AttributeError: module 'openai' has no attribute 'api_base'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py](https://localhost:8080/#) in __call__(self, prompt, stop, stop_regex, temperature, n, max_tokens, logprobs, top_p, echo, logit_bias, token_healing, pattern, stream, cache_seed, caching, **completion_kwargs)
    543                     out = await self.llm.caller(**call_args)
    544 
--> 545                 except openai.error.RateLimitError:
    546                     await asyncio.sleep(3)
    547                     try_again = True

AttributeError: module 'openai' has no attribute 'error'
```

**Comment by stepp1** [comment]
That's another incorrect version. See: https://community.openai.com/t/attributeerror-module-openai-has-no-attribute-error/486676

@SeeknnDestroy, you're right. Still, this is a general issue with packages that are directly with pip as it doesn't check compatibility.

**Comment by stepp1** [comment]
> First, @xHeler's issue is due to changes in pydantic's v2. These aren't catched by any tests because `tests/program/test_guidance.py` doesn't check for inheritance (Specifically, this seems an issue with `llama_index.prompts.guidance_utils:pydantic_to_guidance_output_template_markdown`).

Also, there's space to improve tests and catch this but I don't know who to ping.
