### ISSUE TITLE
[Bug]: Empty Messages OpenAI Error

### ISSUE THREAD

**Issue by Daniel199438** [run-llama/llama_index#9342]
### Bug Description

I get an error message after a successful call history of a LlamaHub tool and probably a response or summary to my prompt following error message

### Version

0.9.12

### Steps to Reproduce

Execute this code: 

` 

    gmail_client = GmailToolSpec()
    gmail_client.set_credentials(delegated_credentials)
    # gmail_client.load_data()
        
     gmail_tools = gmail_client.to_tool_list()
    # gcal_tools = GoogleCalendarToolSpec().to_tool_list()

    print("Wrapping gmail " + gmail_tools[0].metadata.name)
    gmail_load_and_search_tools = LoadAndSearchToolSpec.from_defaults(
        gmail_tools[0],
    ).to_tool_list()

    all_tools = [
        *gmail_load_and_search_tools,
        *gmail_tools[1::],
    ]

    agent = OpenAIAgent.from_tools(all_tools, verbose=True)

    agent.chat(question)

`

### Relevant Logs/Tracbacks

```shell
STARTING TURN 3
---------------

Traceback (most recent call last):
  File "C:\Users\ONEWORX\Documents\AutoGen Test\app.py", line 125, in <module>
    print(answer_gmail_questions("Kannst du mir meine letzten 5 Mails zusammenfassen?"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\Documents\AutoGen Test\gmail.py", line 65, in answer_gmail_questions
    agent.chat(question)
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\llama_index\callbacks\utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\llama_index\agent\openai_agent.py", line 438, in chat
    chat_response = self._chat(
                    ^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\llama_index\agent\openai_agent.py", line 360, in _chat
    agent_chat_response = self._get_agent_response(mode=mode, **llm_chat_kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\llama_index\agent\openai_agent.py", line 322, in _get_agent_response
    chat_response: ChatResponse = self._llm.chat(**llm_chat_kwargs)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\llama_index\llms\base.py", line 187, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\llama_index\llms\openai.py", line 220, in chat
    return chat_fn(messages, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\llama_index\llms\openai.py", line 275, in _chat
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\openai\_utils\_utils.py", line 301, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\openai\resources\chat\completions.py", line 598, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\openai\_base_client.py", line 1096, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\openai\_base_client.py", line 856, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\ONEWORX\.pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\openai\_base_client.py", line 908, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "[] is too short - 'messages'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by Daniel199438** [comment]
@dosu-bot The question param ist just a string containing the prompt. 
I tried to include a chat_history list with one element but it still outputs this error
