### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chengdaqi** [run-llama/llama_index#9398]
### Bug Description

When I use the correct api-key, the requested URL is incorrect. When my api-key is incorrect, such as XX, the requested URL is correct but I get a 401 error, indicating that my api-key is incorrect.

`embed_model = AzureOpenAIEmbedding(api_key="XXX",
                                   azure_endpoint="XXX",
                                   azure_deployment="XXX",
                                   model="text-embedding-ada-002",
                                   api_type='azure',
                                   api_base="https://XXX.openai.azure.com",
                                   api_version="2023-07-01-preview"
                                   )
service_context = ServiceContext.from_defaults(embed_model=embed_model)

documents = SimpleDirectoryReader("./data").load_data()

index = VectorStoreIndex.from_documents(documents, service_context=service_context)

llm = AzureOpenAI(
    engine="aios-gpt35-16k", model="gpt-35-turbo-16k", temperature=0.0
)

engine = index.as_query_engine()
response = engine.query("What is azure openai service?")`

the correct api-key, the requested URL is incorrect：
![image](https://github.com/run-llama/llama_index/assets/20795442/256ce28e-764a-46e1-ad4f-732ff785b1a4)

my api-key is incorrect, such as XX, the requested URL is correct
![image](https://github.com/run-llama/llama_index/assets/20795442/a868e25d-85c3-40f6-8243-043b54bcc021)

### Version

0.9.18

### Steps to Reproduce

![image](https://github.com/run-llama/llama_index/assets/20795442/f718e7e1-4753-4fb0-aa18-3ef25c532e0f)

**Comment by chengdaqi** [comment]
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/yan/trl/data-collect/llama_index/llama_index/callbacks/base.py", line 178, in as_trace
    yield
  File "/Users/yan/trl/data-collect/llama_index/llama_index/indices/base.py", line 106, in from_documents
    return cls(
  File "/Users/yan/trl/data-collect/llama_index/llama_index/indices/vector_store/base.py", line 49, in __init__
    super().__init__(
  File "/Users/yan/trl/data-collect/llama_index/llama_index/indices/base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "/Users/yan/trl/data-collect/llama_index/llama_index/indices/vector_store/base.py", line 255, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
  File "/Users/yan/trl/data-collect/llama_index/llama_index/indices/vector_store/base.py", line 236, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "/Users/yan/trl/data-collect/llama_index/llama_index/indices/vector_store/base.py", line 189, in _add_nodes_to_index
    nodes = self._get_node_with_embedding(nodes, show_progress)
  File "/Users/yan/trl/data-collect/llama_index/llama_index/indices/vector_store/base.py", line 101, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
  File "/Users/yan/trl/data-collect/llama_index/llama_index/indices/utils.py", line 137, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
  File "/Users/yan/trl/data-collect/llama_index/llama_index/embeddings/base.py", line 255, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
  File "/Users/yan/trl/data-collect/llama_index/llama_index/embeddings/openai.py", line 385, in _get_text_embeddings
    return get_embeddings(
  File "/Users/yan/trl/data-collect/llama_index/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/yan/trl/data-collect/llama_index/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/yan/trl/data-collect/llama_index/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/Users/yan/trl/data-collect/llama_index/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/yan/trl/data-collect/llama_index/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/yan/trl/data-collect/llama_index/llama_index/embeddings/openai.py", line 162, in get_embeddings
    data = client.embeddings.create(input=list_of_text, model=engine, **kwargs).data
  File "/Users/yan/trl/data-collect/llama_index/venv/lib/python3.9/site-packages/openai/resources/embeddings.py", line 105, in create
    return self._post(
  File "/Users/yan/trl/data-collect/llama_index/venv/lib/python3.9/site-packages/openai/_base_client.py", line 1096, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/Users/yan/trl/data-collect/llama_index/venv/lib/python3.9/site-packages/openai/_base_client.py", line 856, in request
    return self._request(
  File "/Users/yan/trl/data-collect/llama_index/venv/lib/python3.9/site-packages/openai/_base_client.py", line 908, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}

**Comment by younes-io** [comment]
I have the same issue:

```
INFO:httpx:HTTP Request: POST https://XXXXXXXXXX.openai.azure.com/openai/deployments/openai-embedding/embeddings?api-version=2023-07-01-preview "HTTP/1.1 401 Unauthorized"
HTTP Request: POST https://XXXXXXXXXX.openai.azure.com/openai/deployments/openai-embedding/embeddings?api-version=2023-07-01-preview "HTTP/1.1 401 Unauthorized"
WARNING:llama_index.llms.openai_utils:Retrying llama_index.embeddings.openai.get_embeddings in 0.18432211996213954 seconds as it raised AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}.
Retrying llama_index.embeddings.openai.get_embeddings in 0.18432211996213954 seconds as it raised AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}.
INFO:httpx:HTTP Request: POST https://XXXXXXXXXX.openai.azure.com/openai/deployments/openai-embedding/embeddings?api-version=2023-07-01-preview "HTTP/1.1 401 Unauthorized"
HTTP Request: POST https://XXXXXXXXXX.openai.azure.com/openai/deployments/openai-embedding/embeddings?api-version=2023-07-01-preview "HTTP/1.1 401 Unauthorized"
```

Version:

![image](https://github.com/run-llama/llama_index/assets/3153107/894f7207-1eab-40c7-bb9a-444374c20518)

**Comment by nx-chen02** [comment]
I have the same issue, wait for a response
