### ISSUE TITLE
i get these error when i search 

### ISSUE THREAD

**Issue by nitin0909** [run-llama/llama_index#9417]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

i get error when i type for searching An error occured while performing search: [Errno 2] No such file or directory: '/tmp/llama_index'

**Comment by nitin0909** [comment]
ok

**Comment by logan-markewich** [comment]
It would help if you had the full traceback. 

/tmp/llama_index is the default cache dir for downloaded things

**Comment by nitin0909** [comment]
File "/home/schoolso/l/models/search_model.py", line 251, in search
    query_refined = await llm_predictor_presearch.apredict(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/langchain/chat_models/base.py", line 662, in apredict
    result = await self._call_async(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/langchain/chat_models/base.py", line 615, in _call_async
    result = await self.agenerate(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/langchain/chat_models/base.py", line 429, in agenerate
    raise exceptions[0]
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/langchain/chat_models/base.py", line 532, in _agenerate_with_cache
    return await self._agenerate(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/langchain/chat_models/openai.py", line 501, in _agenerate
    response = await acompletion_with_retry(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/langchain/chat_models/openai.py", line 101, in acompletion_with_retry
    return await llm.async_client.create(**kwargs)
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 1191, in create
    return await self._post(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/openai/_base_client.py", line 1480, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/openai/_base_client.py", line 1275, in request
    return await self._request(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/openai/_base_client.py", line 1318, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-1106-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
Traceback (most recent call last):
  File "/home/schoolso/l/cogs/search_service_cog.py", line 563, in search_command
    response, refined_text = await self.model.search(
  File "/home/schoolso/l/models/search_model.py", line 354, in search
    service_context = ServiceContext.from_defaults(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/llama_index/indices/service_context.py", line 177, in from_defaults
    node_parser = node_parser or _get_default_node_parser(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/llama_index/indices/service_context.py", line 32, in _get_default_node_parser
    return SimpleNodeParser.from_defaults(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/llama_index/node_parser/simple.py", line 56, in from_defaults
    text_splitter = text_splitter or get_default_text_splitter(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/llama_index/text_splitter/__init__.py", line 22, in get_default_text_splitter
    return SentenceSplitter(
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/llama_index/text_splitter/sentence_splitter.py", line 91, in __init__
    chunking_tokenizer_fn = chunking_tokenizer_fn or split_by_sentence_tokenizer()
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/llama_index/text_splitter/utils.py", line 42, in split_by_sentence_tokenizer
    cache_dir = get_cache_dir()
  File "/home/schoolso/virtualenv/l/3.9/lib/python3.9/site-packages/llama_index/utils.py", line 281, in get_cache_dir
    os.makedirs(
  File "/opt/alt/python39/lib64/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/llama_index'

**Comment by logan-markewich** [comment]
Yea for whatever reason, this is failing (it really shouldn't be though)

In any case, set the env var to change the location

Something like
```
export LLAMA_INDEX_CACHE_DIR="/home/llama_index_cache"
```

**Comment by nitin0909** [comment]
now these erroi An error occured while performing search: [Errno 13] Permission denied: '/home/llama_index_cache' when i used
 these in my .env file export export LLAMA_INDEX_CACHE_DIR="/home/username/llama_index_cache"

**Comment by logan-markewich** [comment]
Well you need permission to use that location 👍🏻

**Comment by nyaitech-admin** [comment]
Where is the default location (LLAMA_INDEX_CACHE_DIR)_ on Windows?

**Comment by logan-markewich** [comment]
@nyaitech-admin in appdata/local 

https://github.com/run-llama/llama_index/blob/b20675ae7d3fb2a61f220bb324399f62443624ef/llama_index/utils.py#L326
