### ISSUE TITLE
[Bug]: Error when storing to mongo DB index and document store for Knowledge Graph

### ISSUE THREAD

**Issue by keenhon** [run-llama/llama_index#9546]
### Bug Description

I am trying to create a KnowledgeGraphIndex using Nebula, the default document store and index store is very big and takes a long time to load, it is working though. 

I am experimenting on using MongoDB as a alternative to see if it resolve the long loading issue. However I hit error after the LLM has generated the triplets.

It is showing error that the Command Document too large from pymongo module.

Here are the docs I am following
https://docs.llamaindex.ai/en/stable/examples/docstore/MongoDocstoreDemo.html
https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_query_engine.html

### Version

0.9.15

### Steps to Reproduce

Here's the code snippet

documents = SimpleDirectoryReader("kg").load_data()
graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
)
docstore = MongoDocumentStore.from_uri(uri=MONGO_URI)
index_store = MongoIndexStore.from_uri(uri=MONGO_URI)

storage_context = StorageContext.from_defaults(
        graph_store=graph_store,
        docstore=docstore,
        index_store=index_store
)
index = KnowledgeGraphIndex.from_documents(
    documents,
    max_triplets_per_chunk=10,
    storage_context=storage_context,
    service_context=service_context,
    include_embeddings=True,
)

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/ssm-user/llama/testnebula.py", line 84, in <module>
    index = KnowledgeGraphIndex.from_documents(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/llama_index/indices/base.py", line 106, in from_documents
    return cls(
           ^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/llama_index/indices/knowledge_graph/base.py", line 81, in __init__
    super().__init__(
  File "/home/ssm-user/llama/lib/python3.11/site-packages/llama_index/indices/base.py", line 73, in __init__
    self._storage_context.index_store.add_index_struct(self._index_struct)
  File "/home/ssm-user/llama/lib/python3.11/site-packages/llama_index/storage/index_store/keyval_index_store.py", line 38, in add_index_struct
    self._kvstore.put(key, data, collection=self._collection)
  File "/home/ssm-user/llama/lib/python3.11/site-packages/llama_index/storage/kvstore/mongodb_kvstore.py",line 112, in put
    self._db[collection].replace_one(
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/collection.py", line 973, in replace_one
    self._update_retryable(
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/collection.py", line 881, in _update_retryable
    return self.__database.client._retryable_write(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1523, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1421, in _retry_with_session
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1462, in _retry_internal
    ).run()
      ^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 2423, in _write
    return self._func(self._session, conn, self._retryable)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/collection.py", line 862, in _update
    return self._update(
           ^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/collection.py", line 816, in _update
    result = conn.command(
             ^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/helpers.py", line 322, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/pool.py", line 996, in command
    self._raise_connection_failure(error)
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/pool.py", line 968, in command
    return command(
           ^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/network.py", line 164, in command
    message._raise_document_too_large(name, size, max_bson_size + message._COMMAND_OVERHEAD)
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/message.py", line 1182, in _raise_document_too_large
    raise DocumentTooLarge(f"{operation!r} command document too large")
pymongo.errors.DocumentTooLarge: 'update' command document too large
```

**Comment by keenhon** [comment]
I did some further testing. Now my code only insert node chunk size 512 one by one. I have lots of nodes though. It still failed with error 

Traceback (most recent call last):
  File "/home/ssm-user/llama/testnebula.py", line 112, in <module>
    index.insert_nodes([node])
  File "/home/ssm-user/llama/lib/python3.11/site-packages/llama_index/indices/base.py", line 186, in insert_nodes
    self._storage_context.index_store.add_index_struct(self._index_struct)
  File "/home/ssm-user/llama/lib/python3.11/site-packages/llama_index/storage/index_store/keyval_index_store.py", line 38, in add_index_struct
    self._kvstore.put(key, data, collection=self._collection)
  File "/home/ssm-user/llama/lib/python3.11/site-packages/llama_index/storage/kvstore/mongodb_kvstore.py",line 112, in put
    self._db[collection].replace_one(
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/collection.py", line 973, in replace_one
    self._update_retryable(
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/collection.py", line 881, in _update_retryable
    return self.__database.client._retryable_write(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1523, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1421, in _retry_with_session
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1462, in _retry_internal
    ).run()
      ^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/mongo_client.py", line 2423, in _write
    return self._func(self._session, conn, self._retryable)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/collection.py", line 862, in _update
    return self._update(
           ^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/collection.py", line 816, in _update
    result = conn.command(
             ^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/helpers.py", line 322, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/pool.py", line 996, in command
    self._raise_connection_failure(error)
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/pool.py", line 968, in command
    return command(
           ^^^^^^^^
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/network.py", line 164, in command
    message._raise_document_too_large(name, size, max_bson_size + message._COMMAND_OVERHEAD)
  File "/home/ssm-user/llama/lib/python3.11/site-packages/pymongo/message.py", line 1182, in _raise_document_too_large
    raise DocumentTooLarge(f"{operation!r} command document too large")
pymongo.errors.DocumentTooLarge: 'update' command document too large


Here's my code snippet:

# directory with >1000 txt files
documents = SimpleDirectoryReader("kg").load_data()

parser = SentenceSplitter(chunk_size=512,chunk_overlap=20)
nodes = parser.get_nodes_from_documents(documents)

space_name = "cas_incidents"
edge_types, rel_prop_names = ["relationship"], ["relationship"]  # default, could be omit if create from an empty kg
tags = ["entity"]  # default, could be omit if create from an empty kg

graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
)
docstore = MongoDocumentStore.from_uri(uri=MONGO_URI, db_name=space_name)
index_store = MongoIndexStore.from_uri(uri=MONGO_URI, db_name=space_name)

storage_context = StorageContext.from_defaults(
        graph_store=graph_store,
        docstore=docstore,
        index_store=index_store
)

index = KnowledgeGraphIndex(
    [],
    max_triplets_per_chunk=10,
    storage_context=storage_context,
    service_context=service_context,
    include_embeddings=True,
)
for node in nodes:
    print(node)
    index.insert_nodes([node])

**Comment by keenhon** [comment]
Upon further debugging. Seems that the index store is the issue. It is using only one key and keep increasing in size.

Any advise what would be a good index store for embeddings apart from local storage?

**Comment by keenhon** [comment]
Fyi.

On local storage. The index store is >500MB, bulk of it are embeddings.

Hope someone can guide me in the right direction for a solution that I don't need to wait very long to start asking questions. The current loading time from local storage is not usable for production use cases.

**Comment by nictuku** [comment]
FWIW @keenhon I'm having a similar problem with IngestionCache, it looks like the mongodb_kvstore has a hard limit because it stores the entire thing in one document and hits the document size limit. I will investigate other KV options like redis until this is resolved.

**Comment by paul-asvb** [comment]
same problem here. What a wierd implementation. The index store is always in one big mongo document. Did anyone find a fix?
