### ISSUE TITLE
[Bug]: Details: invalid options: formatted with ollama

### ISSUE THREAD

**Issue by YashKumarVerma** [run-llama/llama_index#9579]
### Bug Description

Was trying the commands given in docs around integrating ollama with llama_index.

## Behavior when giving an isolated prompts:
**Code**
```py
from llama_index.llms import Ollama
llm = Ollama(model="llama2-uncensored:latest")
resp = llm.complete("say hello")
print(resp)
```

**Output**
`Hello`

## Issue
When running via chat, getting a 400 from the server.
```py
from llama_index.llms import ChatMessage, Ollama
llm = Ollama(model="llama2-uncensoredb")

messages = [
    ChatMessage(
        role="system", content="You are a pirate with a colorful personality"
    ),
    ChatMessage(role="user", content="What is your name"),
]
resp = llm.chat(messages)
```

**Output**
```
ValueError: Ollama call failed with status code 404. Details: model 'llama2-uncensoredb' not found, try pulling it first
```
_traceback attached_

### Version

llama-index==0.9.15.post2

### Steps to Reproduce

1. Run the script given in the issue body.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/yash/Desktop/yashkumarverma.com/github.com/llamaindex/chat.py", line 10, in <module>
    resp = llm.chat(messages)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/yash/Desktop/yashkumarverma.com/github.com/llamaindex/venv/lib/python3.11/site-packages/llama_index/llms/base.py", line 97, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash/Desktop/yashkumarverma.com/github.com/llamaindex/venv/lib/python3.11/site-packages/llama_index/llms/ollama.py", line 85, in chat
    completion_response = self.complete(prompt, formatted=True, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash/Desktop/yashkumarverma.com/github.com/llamaindex/venv/lib/python3.11/site-packages/llama_index/llms/base.py", line 223, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash/Desktop/yashkumarverma.com/github.com/llamaindex/venv/lib/python3.11/site-packages/llama_index/llms/ollama.py", line 98, in complete
    response_gen = self.stream_complete(prompt, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash/Desktop/yashkumarverma.com/github.com/llamaindex/venv/lib/python3.11/site-packages/llama_index/llms/base.py", line 223, in wrapped_llm_predict
    f_return_val = f(_self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash/Desktop/yashkumarverma.com/github.com/llamaindex/venv/lib/python3.11/site-packages/llama_index/llms/ollama.py", line 126, in stream_complete
    raise ValueError(
ValueError: Ollama call failed with status code 404. Details: model 'llama2-uncensoredb' not found, try pulling it first
```

**Comment by hatianzhang** [comment]
should be fixed by https://github.com/run-llama/llama_index/pull/9591

**Comment by hatianzhang** [comment]
this issue should have been fixed. let me know if it is still not fixed
