### ISSUE TITLE
[Bug]:  Unterminated string starting at: line 1 column 2407517 (char 2407516)

### ISSUE THREAD

**Issue by yasergsi** [run-llama/llama_index#9603]
### Bug Description

I am trying to load a simple `VectorStoreIndex`  from a remote file storage i.e. AWS S3 bucket. I never got any error in the past 6 months until now from yesterday i.e. 19th December 2023 I get the following error: 
```
[Bug]:  Unterminated string starting at: line 1 column 2407517 (char 2407516)
```

As a result of the following line of code _(full code given below)_

```
storage_context = StorageContext.from_defaults(persist_dir=s3_index_path, fs=s3)
```

### Version

0.9.10

### Steps to Reproduce

Using the script:
```
import s3fs
from llama_index import StorageContext, load_index_from_storage

s3 = s3fs.S3FileSystem()
s3_index_path = f"s3://{bucket_name}/indexes/{project_id}/{bot_id}/storage_context"
storage_context = StorageContext.from_defaults(persist_dir=s3_index_path, fs=s3)
index = load_index_from_storage(storage_context=storage_context)
```

### Relevant Logs/Tracbacks

```shell
ERROR:root:Unterminated string starting at: line 1 column 2407517 (char 2407516)	

Unterminated string starting at: line 1 column 2407517 (char 2407516)	


ERROR:root:Traceback: Traceback (most recent call last):	


File "/home/app.py", line 495, in query_apigateway	

storage_context = StorageContext.from_defaults(persist_dir=index_path, fs=s3)	


File "/usr/local/lib/python3.10/site-packages/llama_index/storage/storage_context.py", line 88, in from_defaults	


docstore = docstore or SimpleDocumentStore.from_persist_dir(	


File "/usr/local/lib/python3.10/site-packages/llama_index/storage/docstore/simple_docstore.py", line 56, in from_persist_dir	


return cls.from_persist_path(persist_path, namespace=namespace, fs=fs)	


File "/usr/local/lib/python3.10/site-packages/llama_index/storage/docstore/simple_docstore.py", line 73, in from_persist_path	


simple_kvstore = SimpleKVStore.from_persist_path(persist_path, fs=fs)	


File "/usr/local/lib/python3.10/site-packages/llama_index/storage/kvstore/simple_kvstore.py", line 76, in from_persist_path	


data = json.load(f)	


File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load	

return loads(fp.read(),	

File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads	


return _default_decoder.decode(s)	

File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode	

obj, end = self.raw_decode(s, idx=_w(s, 0).end())	


File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode	

obj, end = self.scan_once(s, idx)

json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2407517 (char 2407516)
```
```

**Comment by yasergsi** [comment]
The same index files when downloaded to my local system and tested works fine.
