### ISSUE TITLE
[Bug]: FunctionTool.from_defaults crashes if there are no function arguments

### ISSUE THREAD

**Issue by redswimmer** [run-llama/llama_index#9657]
### Bug Description

FunctionTool.from_defaults(fn=useless_tool) throws the error `ValueError: invalid method signature` when no parameters are specified in the "useless" function tool.

### Version

0.9.19

### Steps to Reproduce

I followed the [docs example here](https://github.com/run-llama/llama_index/blob/main/docs/examples/agent/openai_forced_function_call.ipynb) for creating the "useless tool"

```python
def useless_tool() -> int:
    """This is a uselss tool."""
    return "This is a uselss output."

useless_tool = FunctionTool.from_defaults(fn=self.useless_tool)
```

and get the error `ValueError: invalid method signature`

adding a dummy parameter makes the error go away i.e. `def useless_tool(dummy: int) -> int:`

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\redsw\Documents\Development\ProcedureCard\preference-card-streamlit\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\redsw\Documents\Development\ProcedureCard\preference-card-streamlit\streamlit_app.py", line 43, in <module>
    data_agent.initialize(SYSTEM_PROMPT)
  File "C:\Users\redsw\Documents\Development\ProcedureCard\preference-card-streamlit\helpers\agent.py", line 38, in initialize
    self._load_tools()
  File "C:\Users\redsw\Documents\Development\ProcedureCard\preference-card-streamlit\helpers\agent.py", line 73, in _load_tools
    format_tool = FunctionTool.from_defaults(fn=self.useless_tool)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\redsw\Documents\Development\ProcedureCard\preference-card-streamlit\.venv\Lib\site-packages\llama_index\tools\function_tool.py", line 55, in from_defaults
    description = description or f"{name}{signature(fn)}\n{docstring}"
                                          ^^^^^^^^^^^^^
  File "C:\Python312\Lib\inspect.py", line 3327, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\inspect.py", line 3071, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\inspect.py", line 2492, in _signature_from_callable
    return _signature_bound_method(sig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\inspect.py", line 2105, in _signature_bound_method
    raise ValueError('invalid method signature')
ValueError: invalid method signature
```

**Comment by redswimmer** [comment]
Nevermind this only happens if the function tool is inside a class.
