### ISSUE TITLE
At MacOS, not working well[Bug]: 

### ISSUE THREAD

**Issue by apollo812** [run-llama/llama_index#9673]
### Bug Description

Now I am fine-tuning using llama_index==0.9.15 and openai==1.1.0 version.
When I use the Window 10 OS, it working well but when I use the MacOS, not working well.
It returns to such error.

``` 
/usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/test_all.py:7: in <module>
    from src.main import app  # Import the FastAPI application instance from the main module
src/main.py:19: in <module>
    from finetune.FineTuningClass import FineTuningClass
src/finetune/FineTuningClass.py:8: in <module>
    from llama_index import SimpleDirectoryReader, ServiceContext, VectorStoreIndex
.local/lib/python3.11/site-packages/llama_index/__init__.py:17: in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
.local/lib/python3.11/site-packages/llama_index/embeddings/__init__.py:16: in <module>
    from llama_index.embeddings.openai import OpenAIEmbedding
.local/lib/python3.11/site-packages/llama_index/embeddings/openai.py:18: in <module>
    from llama_index.llms.openai_utils import (
.local/lib/python3.11/site-packages/llama_index/llms/__init__.py:2: in <module>
    from llama_index.llms.anyscale import Anyscale
.local/lib/python3.11/site-packages/llama_index/llms/anyscale.py:11: in <module>
    from llama_index.llms.openai import OpenAI
.local/lib/python3.11/site-packages/llama_index/llms/openai.py:28: in <module>
    from llama_index.llms.openai_utils import (
.local/lib/python3.11/site-packages/llama_index/llms/openai_utils.py:6: in <module>
    from openai import ChatCompletion, Completion
E   ImportError: cannot import name 'ChatCompletion' from 'openai' (/home/user/.local/lib/python3.11/site-packages/openai/__init__.py)
```

So I upgraded the OpenAI version to 1.3.7 but got such error.
```
from openai.openai_object import OpenAIObject
ModuleNotFoundError: No module named 'openai.openai_object'
```

I think this is a dependency issue between the llama_index and openai.
Is there anyone who know the solution?

Thank you!!!

### Version

0.9.15

### Steps to Reproduce

When I use the Window 10 OS, it working well but when I use the MacOS, not working well.
This is requirements.txt file.

```
httpx
pytest
black
isort
mypy
fastapi
uvicorn
python-multipart
python-dotenv
requests
Pillow
openai==1.1.0
pdf2image
gpt_index
langchain
llama_index==0.9.15
pypdf
spacy
ragas
datasets
docx2txt
cryptography
```

### Relevant Logs/Tracbacks

- openai==1.1.0 & llama_index==0.9.15
```shell 
/usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/test_all.py:7: in <module>
    from src.main import app  # Import the FastAPI application instance from the main module
src/main.py:19: in <module>
    from finetune.FineTuningClass import FineTuningClass
src/finetune/FineTuningClass.py:8: in <module>
    from llama_index import SimpleDirectoryReader, ServiceContext, VectorStoreIndex
.local/lib/python3.11/site-packages/llama_index/__init__.py:17: in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
.local/lib/python3.11/site-packages/llama_index/embeddings/__init__.py:16: in <module>
    from llama_index.embeddings.openai import OpenAIEmbedding
.local/lib/python3.11/site-packages/llama_index/embeddings/openai.py:18: in <module>
    from llama_index.llms.openai_utils import (
.local/lib/python3.11/site-packages/llama_index/llms/__init__.py:2: in <module>
    from llama_index.llms.anyscale import Anyscale
.local/lib/python3.11/site-packages/llama_index/llms/anyscale.py:11: in <module>
    from llama_index.llms.openai import OpenAI
.local/lib/python3.11/site-packages/llama_index/llms/openai.py:28: in <module>
    from llama_index.llms.openai_utils import (
.local/lib/python3.11/site-packages/llama_index/llms/openai_utils.py:6: in <module>
    from openai import ChatCompletion, Completion
E   ImportError: cannot import name 'ChatCompletion' from 'openai' (/home/user/.local/lib/python3.11/site-packages/openai/__init__.py)
```

- openai==1.3.7 & llama_index==0.9.15
```
from openai.openai_object import OpenAIObject
ModuleNotFoundError: No module named 'openai.openai_object'
```

**Comment by logan-markewich** [comment]
I work on a mac and windows every day, both work fine in my case with llama-index

Newer versions of llama-index are only compatible with openai>1.0

```
from openai.openai_object import OpenAIObject
ModuleNotFoundError: No module named 'openai.openai_object'
```

Where is this being imported?

**Comment by apollo812** [comment]
Hi @logan-markewich 
Thank you for quick reply.

When I am using openai==1.3.7 & llama_index==0.9.15
I got such error.

```
from openai.openai_object import OpenAIObject
ModuleNotFoundError: No module named 'openai.openai_object'
```

Not sure the reason.

**Comment by logan-markewich** [comment]
`from openai.openai_object import OpenAIObject` -- are you running this in your code anywhere? It seems like the latest openai client either doesn't support this import or the import moved

**Comment by apollo812** [comment]
```
Traceback (most recent call last):
  File "/home/jupiter/github/img2txt-fine-tuning-api/chatting.py", line 7, in <module>
    from src.chatting.ChattingClass import ChattingClass
  File "/home/jupiter/github/img2txt-fine-tuning-api/src/chatting/ChattingClass.py", line 4, in <module>
    from llama_index import ServiceContext, SimpleDirectoryReader, VectorStoreIndex
  File "/home/jupiter/anaconda3/envs/img2txt_fine_tuning/lib/python3.12/site-packages/llama_index/__init__.py", line 17, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "/home/jupiter/anaconda3/envs/img2txt_fine_tuning/lib/python3.12/site-packages/llama_index/embeddings/__init__.py", line 16, in <module>
    from llama_index.embeddings.openai import OpenAIEmbedding
  File "/home/jupiter/anaconda3/envs/img2txt_fine_tuning/lib/python3.12/site-packages/llama_index/embeddings/openai.py", line 18, in <module>
    from llama_index.llms.openai_utils import (
  File "/home/jupiter/anaconda3/envs/img2txt_fine_tuning/lib/python3.12/site-packages/llama_index/llms/__init__.py", line 23, in <module>
    from llama_index.llms.litellm import LiteLLM
  File "/home/jupiter/anaconda3/envs/img2txt_fine_tuning/lib/python3.12/site-packages/llama_index/llms/litellm.py", line 28, in <module>
    from llama_index.llms.litellm_utils import (
  File "/home/jupiter/anaconda3/envs/img2txt_fine_tuning/lib/python3.12/site-packages/llama_index/llms/litellm_utils.py", line 4, in <module>
    from openai.openai_object import OpenAIObject
ModuleNotFoundError: No module named 'openai.openai_object'
```

**Comment by logan-markewich** [comment]
Are you sure your llama-index package is updated? Maybe try `pip install --upgrade llama-index` again, and if you are using a notebook, totallly restarting it

That line of code does not exist in the current codebase
https://github.com/run-llama/llama_index/blob/9bb287b0e7c354824ddc3eb51f54a31f28ef6b33/llama_index/llms/litellm_utils.py#L4

**Comment by apollo812** [comment]
Got it.
But I am using docker, I think, everytime will install new version.
Btw, I will try it.
Thank you.
👍

**Comment by apollo812** [comment]
@logan-markewich 

It working well. Incredible!!!
Really thank you!!!
👍
