### ISSUE TITLE
[Bug]: cannot import name 'AzureOpenAIEmbedding' from 'llama_index.embeddings'

### ISSUE THREAD

**Issue by Anang1502** [run-llama/llama_index#9701]
### Bug Description

I am trying to import the AzureOpenAIEmbedding class to create embeddings as per the below documentation. But it throws an error 

`from llama_index.embeddings import AzureOpenAIEmbedding`

**documentation link** --> https://docs.llamaindex.ai/en/stable/examples/customization/llms/AzureOpenAI.html

**error**

> 
> /home/anang/simplifai_projects/nelfo_llm/venv/bin/python /home/anang/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/231.9225.15/plugins/python-ce/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 38071 --file /home/anang/simplifai_projects/nelfo_llm/source/utils/llamaindex_test.py 
> Connected to pydev debugger (build 231.9225.15)
> Traceback (most recent call last):
>   File "/home/anang/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/231.9225.15/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/home/anang/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/231.9225.15/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
> 
>   File "/home/anang/simplifai_projects/nelfo_llm/source/utils/llamaindex_test.py", line 2, in <module>
>     from llama_index.embeddings import AzureOpenAIEmbedding
> ImportError: cannot import name 'AzureOpenAIEmbedding' from 'llama_index.embeddings' (/home/anang/simplifai_projects/nelfo_llm/venv/lib/python3.10/site-packages/llama_index/embeddings/__init__.py)
> python-BaseException

### Version

Version: 0.8.62

### Steps to Reproduce

```
!pip install llama-index==0.8.62
from llama_index.embeddings import AzureOpenAIEmbedding
```

**Comment by Anang1502** [comment]
Hi, 
It was the version issue. I updated the llama-index version to the latest version 0.9.21. The imports are working fine now.
