### ISSUE TITLE
[Bug]: llama_index.vector_stores import PGVectorStore forces the creation of Schema in restrictive environments

### ISSUE THREAD

**Issue by dpsalvatierra** [run-llama/llama_index#9710]
### Bug Description

When using PGVectorStore from the Llama Index library in environments where the database user has restricted permissions, specifically lacking the privilege to create new schemas, the library encounters a permission issue. This is due to PGVectorStore attempting to create a new schema even when it's unnecessary or not feasible due to user permissions.

### Version

0.9.21

### Steps:
1. Use PGVectorStore in an environment where the database user has restricted permissions and cannot create new schemas.
2. Initialize PGVectorStore with the required parameters.
3. Observe that PGVectorStore attempts to create a new schema and fails due to insufficient privileges.

### Expected Behavior:
PGVectorStore should either not attempt to create a new schema if it already exists and specified using "schema_name" argument.

### Actual Behavior:
PGVectorStore attempts to create a schema and fails in environments where the database user does not have schema creation privileges per below:

#### Create a vector store using make url and env settings:
```
url = make_url(os.getenv('PGVECTOR_CONNECTION_STRING'))
vector_store = PGVectorStore.from_params(
    schema_name="authorized_schema",
    database=db_name,
    host=url.host,
    password=url.password,
    port=url.port,
    user=url.username,   
    embed_dim=768,  # Hugginface embedding dimension
)
```
### Exception error:
Exception has occurred: ProgrammingError
(psycopg2.errors.InsufficientPrivilege) permission denied for database pgvector

[SQL: CREATE SCHEMA IF NOT EXISTS lab_test]
(Background on this error at: https://sqlalche.me/e/20/f405)
psycopg2.errors.InsufficientPrivilege: permission denied for database pgvector

The above exception was the direct cause of the following exception:

  File "/home/me/myproject/test.py", line 124, in <module>
    index = VectorStoreIndex.from_documents(
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for database vector_db

#### Generate subclass and use it to create the vector_store

```
# Subclass the PGVectorStore to deal with the schema creation error
class CustomPGVectorStore(PGVectorStore):
    def _create_schema_if_not_exists(self):
        # Skip schema creation
        pass

db_name = "pgvector"
# Create an alchemy engine    
url = make_url(os.getenv('PGVECTOR_CONNECTION_STRING'))
try:
    vector_store = CustomPGVectorStore.from_params(
        schema_name="authorized_schema",
        database=db_name,
        host=url.host,
        password=url.password,
        port=url.port,
        user=url.username,      
        embed_dim=768,  # Hugginface embedding dimension
    )
except Exception as e:
    traceback.print_exc()
    print(f'Error creating vector store: {e}')
```

### Environment:
Postgres 15 
Llama Index 0.9.21
Python 3.10

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 294, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "/home/me/myproject/test.py", line 115
    except ImportError, Exception as e:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
(myproject) [me@server1 myproject]$  cd /home/me/myproject ; /usr/bin/env /home/me/miniconda3/envs/myproject/bin/python /home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 55117 -- /home/me/myproject/test.py 
768
[-0.01605335995554924, -0.07031058520078659, -0.014634493738412857, 0.02681606262922287, 0.043894585222005844]
Document ID: b4350ce3-8d0d-4c96-9291-b6483e231ab9
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 691.40it/s]
Generating embeddings: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:01<00:00, 14.48it/s]
Traceback (most recent call last):
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied for database pgvector


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/me/.vscode-server/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/me/myproject/test.py", line 124, in <module>
    index = VectorStoreIndex.from_documents(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/llama_index/indices/base.py", line 106, in from_documents
    return cls(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 52, in __init__
    super().__init__(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/llama_index/indices/base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 262, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 243, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 197, in _add_nodes_to_index
    new_ids = self._vector_store.add(nodes_batch, **insert_kwargs)
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/llama_index/vector_stores/postgres.py", line 306, in add
    self._initialize()
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/llama_index/vector_stores/postgres.py", line 289, in _initialize
    self._create_schema_if_not_exists()
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/llama_index/vector_stores/postgres.py", line 269, in _create_schema_if_not_exists
    session.execute(statement)
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2199, in _execute_internal
    result = conn.execute(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/home/me/miniconda3/envs/myproject/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for database pgvector

[SQL: CREATE SCHEMA IF NOT EXISTS url.username ]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

**Comment by logan-markewich** [comment]
The code does check if the schema exists before creating it?

If you have an alternative way of doing this, please raise a PR :) 

https://github.com/run-llama/llama_index/blob/50b9f75461ec7a5baa625126d071f76ea5dc5a5d/llama_index/vector_stores/postgres.py#L268

**Comment by dpsalvatierra** [comment]
> The code does check if the schema exists before creating it?
> 
> If you have an alternative way of doing this, please raise a PR :)
> 
> https://github.com/run-llama/llama_index/blob/50b9f75461ec7a5baa625126d071f76ea5dc5a5d/llama_index/vector_stores/postgres.py#L268

Yes, overriding the check is what I used as a workaround. However, some environment's won't even allow this statement "CREATE SCHEMA IF NOT EXISTS", I will check into it.

**Comment by dpsalvatierra** [comment]
Pull request created:
https://github.com/run-llama/llama_index/pull/9712

**Comment by dpsalvatierra** [comment]
Heads folks, same problem with SupabaseVectorStore when testing collections

```
create schema if not exists vecs
````

**Comment by dpsalvatierra** [comment]
PR I submitted resolved the problem
