### ISSUE TITLE
[Bug]: Incorrect Default Service Context Handling in Service Initialization in DatasetGenerator and RagDatasetGenerator

### ISSUE THREAD

**Issue by lakshminarayanannn** [run-llama/llama_index#9774]
### Bug Description

The code incorrectly initializes the default service context. When a service context is not specified, it should default to the global context via ServiceContext.from_defaults(). However, the code calls _get_default_service_context(), which returns OpenAI with preset parameters, bypassing the global context. This leads to potential inconsistencies and unexpected behaviors in the application, as it does not adhere to the intended default context settings.

### Version

0.9.1.post1

### Steps to Reproduce

1. Import DatasetGenerator from llama_index.evaluation.
2. Create a DatasetGenerator instance using DatasetGenerator.from_documents(documents).
3. Call generate_questions_from_nodes on the instance with the argument num=10
4. his sequence triggers the bug, as the error occurs after initializing DatasetGenerator and then invoking generate_questions_from_nodes.

```
from llama_index.evaluation import DatasetGenerator

data_generator = DatasetGenerator.from_documents(
        documents,
        )
generated_questions  = data_generator.generate_questions_from_nodes(num=10)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "generate_questions.py", line 89, in <module>
    generated_questions  = data_generator.generate_questions_from_nodes(num=50)
  File "/usr/local/lib/python3.8/dist-packages/llama_index/evaluation/dataset_generation.py", line 301, in generate_questions_from_nodes
    return asyncio.run(self.agenerate_questions_from_nodes(num=num))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/llama_index/evaluation/dataset_generation.py", line 286, in agenerate_questions_from_nodes
    dataset = await self._agenerate_dataset(
  File "/usr/local/lib/python3.8/dist-packages/llama_index/evaluation/dataset_generation.py", line 240, in _agenerate_dataset
    responses = await async_module.gather(*query_tasks)
  File "/usr/local/lib/python3.8/dist-packages/llama_index/core/base_query_engine.py", line 36, in aquery
    return await self._aquery(str_or_query_bundle)
  File "/usr/local/lib/python3.8/dist-packages/llama_index/query_engine/retriever_query_engine.py", line 187, in _aquery
    response = await self._response_synthesizer.asynthesize(
  File "/usr/local/lib/python3.8/dist-packages/llama_index/response_synthesizers/base.py", line 179, in asynthesize
    response_str = await self.aget_response(
  File "/usr/local/lib/python3.8/dist-packages/llama_index/response_synthesizers/compact_and_refine.py", line 19, in aget_response
    return await super().aget_response(
  File "/usr/local/lib/python3.8/dist-packages/llama_index/response_synthesizers/refine.py", line 325, in aget_response
    response = await self._agive_response_single(
  File "/usr/local/lib/python3.8/dist-packages/llama_index/response_synthesizers/refine.py", line 430, in _agive_response_single
    structured_response = await program.acall(
  File "/usr/local/lib/python3.8/dist-packages/llama_index/response_synthesizers/refine.py", line 79, in acall
    answer = await self._llm.apredict(
  File "/usr/local/lib/python3.8/dist-packages/llama_index/llms/llm.py", line 261, in apredict
    chat_response = await self.achat(messages)
  File "/usr/local/lib/python3.8/dist-packages/llama_index/llms/base.py", line 54, in wrapped_async_llm_chat
    f_return_val = await f(_self, messages, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/llama_index/llms/openai.py", line 484, in achat
    return await achat_fn(messages, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/llama_index/llms/openai.py", line 526, in _achat
    response = await aclient.chat.completions.create(
  File "/usr/local/lib/python3.8/dist-packages/openai/resources/chat/completions.py", line 1295, in create
    return await self._post(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1536, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1315, in request
    return await self._request(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1358, in _request
    return await self._retry_request(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1418, in _retry_request
    return await self._request(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1358, in _request
    return await self._retry_request(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1418, in _retry_request
    return await self._request(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1358, in _request
    return await self._retry_request(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1418, in _retry_request
    return await self._request(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1367, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```

**Comment by logan-markewich** [comment]
I'm not sure what the solution is here -- it sets the temperate to `0` since the default temperature is `0.1`.

Not sure how we can respect any service context defaults while still changing the default temperature to 0.1 🤔

**Comment by lakshminarayanannn** [comment]
@logan-markewich 
I have pushed my PR, could you please check here
https://github.com/run-llama/llama_index/pull/9775

What I did was, instead of calling a function that returns an OpenAI LLM, which might cause an error if there are no API keys, I set up the service context from global service context
Even in the llm_generators.py, it is implemented as same as I did. After seeing that as reference. I have changed.
