### ISSUE TITLE
Use of Mixtral with Ollama and Quadrant Db

### ISSUE THREAD

**Issue by erlebach** [run-llama/llama_index#9816]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am seeking to run Mixtral in local mode without needing the internet. Here is some code: 
```
from pathlib import Path
import qdrant_client
from llama_index import (
    VectorStoreIndex,
    ServiceContext,
    download_loader,
)
from llama_index.llms import Ollama
from llama_index.storage.storage_context import StorageContext
from llama_index.vector_stores.qdrant import QdrantVectorStore

# JSONReader = download_loader("JSONReader")
PDFReader = download_loader("PDFReader")
loader = PDFReader()
filenm = "./data/Retentive network, successor to transformer, 2023_read.pdf"
documents = loader.load_data(Path(filenm))

# Vector Database
client = qdrant_client.QdrantClient(path="./qdrant_data")
vector_store = QdrantVectorStore(client=client, collection_name="papers")
storage_context = StorageContext.from_defaults(vector_store=vector_store)

llm = Ollama(model="mixtral")   # or "mistral"
service_context = ServiceContext.from_defaults(llm=llm, embed_model="local")

index = VectorStoreIndex.from_documents(
    documents, service_context=service_context, storage_context=storage_context
)

query_engine = index.as_query_engine()
response = query_engine.query("What is the main characteristic of retentive networks")
print(response)
```
I get a `reader timeout` error when executing `index.as_query_engine()`: 
```
Traceback (most recent call last):
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/load_and_index.py", line 32, in <module>
    response = query_engine.query("What is the main characteristic of retentive networks")
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/core/base_query_engine.py", line 30, in query
    return self._query(str_or_query_bundle)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py", line 171, in _query
    response = self._response_synthesizer.synthesize(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/response_synthesizers/base.py", line 146, in synthesize
    response_str = self.get_response(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/response_synthesizers/compact_and_refine.py", line 38, in get_response
    return super().get_response(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 146, in get_response
    response = self._give_response_single(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 202, in _give_response_single
    program(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py", line 64, in __call__
    answer = self._llm.predict(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/llms/llm.py", line 220, in predict
    chat_response = self.chat(messages)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/llms/base.py", line 97, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/llama_index/llms/ollama.py", line 102, in chat
    response = client.post(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1146, in post
    return self.request(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/erlebach/src/2023/gordon_llama_index/mixtral/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
  ```
  indicating the internet is accessed, which should not be the case. If I replace `mixtral` by `mistral`, the code runs perfectly fine. I am running on a Mac notebook with 96 GB ram and several TB of SSD.  What could possibly be wrong? My code is based off one of the blogs written by LlamaIndex developers, titled: "Running Mixtral 8x7 locally with LlamaIndex". Any help is appreciated. Thanks!

**Comment by logan-markewich** [comment]
@erlebach Did you run `ollama run mixtral` so that it downloads the model?

**Comment by erlebach** [comment]
@logan-markewich  I did. In fact, the following works: 
```
from llama_index.llms import Ollama

llm = Ollama(model="mixtral")
response = llm.complete("Who is Laurie Voss?")
print(response)
```

**Comment by logan-markewich** [comment]
@erlebach if that works, then maybe the timeout needs to be increased on ollama? Tbh I'm not even sure that's configurable or not, I'd have to look.

Mixtral will definitely be slower to respond than mistral, it's a lot bigger

**Comment by erlebach** [comment]
@logan-markewich : Good point. Note that it worked for whomever wrote the  blog. Also, I do not understand why the web is accessed (via httpx.). thanks.

**Comment by logan-markewich** [comment]
@erlebach httpx is not really accessing the web, it's accessing the model at the specified endpoint 
https://github.com/run-llama/llama_index/blob/cd892a51d31cc3aa47b7adf9db60e88d9ee96188/llama_index/llms/ollama.py#L101

Also, looks like you can set `request_timeout` in the constructor

**Comment by erlebach** [comment]
Thank you, @logan-markewich ! I will look into this.
