### ISSUE TITLE
llama-index 0.4.40 upgraded to 0.5.2 prompts KeyError: 'index_struct' error

### ISSUE THREAD

**Issue by onesecurity** [run-llama/llama_index#988]
llama-index 0.4.40 upgraded to 0.5.2 prompts KeyError: 'index_struct' error,This sample code can run normally in version 0.4.40.

```
       load_json = 'json/%s.json' % model
        print(load_json)
        graph = ComposableGraph.load_from_disk(load_json)
        llm_predictor_chatgpt = LLMPredictor(llm=OpenAIChat(temperature=0, model_name="gpt-3.5-turbo"))
        decompose_transform = DecomposeQueryTransform(
            llm_predictor_chatgpt, verbose=True
        )
```

```

  File "/code/main.py", line 198, in newask
    graph = ComposableGraph.load_from_disk('json/%s.json' % model)
  File "/code/llama_index/indices/composability/graph.py", line 220, in load_from_disk
    return cls.load_from_string(file_contents, **kwargs)
  File "/code/llama_index/indices/composability/graph.py", line 197, in load_from_string
    index_struct = load_index_struct_from_dict(result_dict["index_struct"])
KeyError: 'index_struct'
```

**Comment by BrunoLiegiBastonLiegi** [comment]
+1 Same error here when trying to load a `KnowledgeGraphIndex` with:
```
index = GPTKnowledgeGraphIndex.load_from_disk(args.load_index, service_context=service_context)
```
Apparently `load_from_dict()` is expecting a dictionary containing the `index_struct` key but the saved index only contains `dict_keys(['index_struct_id', 'docstore'])`. I thought the problem was that the key had been renamed and thus I tried adding the `index_struct` key with the same content of the `index_struct_id` key:
```
with open(args.load_index, 'r') as f:
    index_dict = json.load(f)
index_dict['index_struct'] = index_dict['index_struct_id']
```
but then I get a type error:
```
Traceback (most recent call last):
  File "/home/users/u7177797/git/testing_llama/kg_construction.py", line 89, in <module>
    index = GPTKnowledgeGraphIndex.load_from_dict(index_dict, service_context=service_context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/u7177797/miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/indices/base.py", line 302, in load_from_dict
    index_struct = load_index_struct_from_dict(result_dict[INDEX_STRUCT_KEY])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/u7177797/miniconda3/envs/llama/lib/python3.11/site-packages/llama_index/indices/registry.py", line 90, in load_index_struct_from_dict
    type = struct_dict[TYPE_KEY]
           ~~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by onesecurity** [comment]
Use index migration tool to solve this problem.

```
Migration tool:

We added a tool to help migrated saved index json from 0.4.x to 0.5.0. Use it as python gpt_index/tools/migrate_v1_to_v2.py --v1_path <tree_v1.json> --index_struct_type <tree> --v2_path <tree_v2.json>
```
